### ISSUE TITLE
aws_sqs_queue. New aws feature "moving messages out of a dead-letter queue" not implemented

### ISSUE THREAD

**Issue by sgabenov** [hashicorp/terraform-provider-aws#22865] opened 2022-02-01 10:03 UTC
Aws has introduced SQS Dead Letter Queue redrive in december 2021 https://aws.amazon.com/blogs/compute/introducing-amazon-simple-queue-service-dead-letter-queue-redrive-to-source-queues/ , but this feature could not be implemented through terraform. If i try to do this with `redrive_policy` for normal queue, it will create an error with loop dependancy. So i guess the DLQ redrive to normal queue should be added with:

1. documentation on how to configure new DLQ redrive
2. created additional resource for new feature

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.4

### Affected Resource(s)

aws_sqs_queue

### Terraform Configuration Files
```
resource "aws_sqs_queue" "s3_tags_prefix" {
  name                       = "${terraform.workspace}-s3-tags-prefix"
  kms_master_key_id          = aws_kms_alias.aws_sqs_encrypt_key_alias.name
  visibility_timeout_seconds = 1000
  policy                     = data.template_file.s3_tags_prefix_policy.rendered
  receive_wait_time_seconds  = 2
  redrive_policy             = "{\"deadLetterTargetArn\":\"${aws_sqs_queue.dlq_s3_tags_prefix.arn}\",\"maxReceiveCount\":5}"
}

resource "aws_sqs_queue" "dlq_s3_tags_prefix" {
  name                            = "${terraform.workspace}-dlq-s3-tags-prefix"
  kms_master_key_id    = aws_kms_alias.aws_sqs_encrypt_key_alias.name
  policy                           = data.template_file.dlq_s3_tags_prefix_policy.rendered

  redrive_policy = jsonencode({
    deadLetterTargetArn = aws_sqs_queue.s3_tags_prefix.arn
    maxReceiveCount     = 4
  })
  redrive_allow_policy = jsonencode({
    redrivePermission = "byQueue",
    sourceQueueArns   = [aws_sqs_queue.s3_tags_prefix.arn]
  })
}
```

### Expected Behavior

Create DLQ redrive

### Actual Behavior

Feature is not supported by provider

### Steps to Reproduce

```
$ terraform apply
Acquiring state lock. This may take a few moments...
Releasing state lock. This may take a few moments...
╷
│ Error: Cycle: module.dsp.aws_sqs_queue.dlq_s3_tags_prefix, module.dsp.aws_sqs_queue.s3_tags_prefix
│ 
│ 
╵
```

### References
https://aws.amazon.com/blogs/compute/introducing-amazon-simple-queue-service-dead-letter-queue-redrive-to-source-queues/
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-dead-letter-queues.html#sqs-dead-letter-queues-redrive

**Comment by justinretzolk** [comment] 2022-02-01 22:09
Hey @sgabenov 👋 Thanks for taking the time to submit this issue. It looks like this is a duplicate of #22577. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #22577.

**Closed by justinretzolk** 2022-02-01 22:09 UTC
Labels: service/sqs, needs-triage
