### ISSUE TITLE
[New Service]: AWS CodePipeline V2 Trigger based on tags

### ISSUE THREAD

**Issue by sandy318** [hashicorp/terraform-provider-aws#35765] opened 2024-02-12 13:09 UTC
### Description

AWS CodePipeline announces support for starting a pipeline execution on git tags pushed to repositories in GitHub, GitHub Enterprise Server, GitLab Cloud and Bitbucket Cloud using CodeStarSourceConnection source actions. 

looks like an argument named trigger is not available. 

![aws-codepipeline-trigger](https://github.com/hashicorp/terraform-provider-aws/assets/101539488/4767470b-6879-40a0-8645-36fd18639cb5)

### Requested Resource(s) and/or Data Source(s)

aws_codepipeline.codepipeline

### Potential Terraform Configuration

```terraform
resource "aws_codepipeline" "codepipeline" {
  name          = "app"
  pipeline_type = "V2"
  TriggerType      = "SpecifyFilter"
  EventType        = "Push"
  FilterType       = "Tags"
  FilterTags       = ["release-*"]
}
  role_arn      = aws_iam_role.codepipeline_role.arn
  artifact_store {
    location = aws_s3_bucket.codepipeline_bucket.bucket
    type     = "S3"
  }
  stage {
    name = "Source"
    action {
      name             = "Source"
      category         = "Source"
      owner            = "AWS"
      provider         = "CodeStarSourceConnection"
      version          = "1"
      output_artifacts = ["SourceArtifact"]
      namespace        = "SourceVariables"
      configuration = {
        ConnectionArn = aws_codestarconnections_connection.example.arn
        FullRepositoryId = var.repo
        BranchName       = var.branch_name

      }
    }
  }
}
```

### References

https://aws.amazon.com/about-aws/whats-new/2023/10/aws-codepipeline-triggering-git-tags/
https://aws.amazon.com/about-aws/whats-new/2024/02/codepipeline-trigger-filters-execution-modes/

### Would you like to implement a fix?

None

**Comment by trevorrea** [comment] 2024-02-12 15:46
Looks to be a dupe of https://github.com/hashicorp/terraform-provider-aws/issues/35475

**Comment by justinretzolk** [comment] 2024-02-12 20:29
Duplicate of #35475

**Closed by justinretzolk** 2024-02-12 20:29 UTC
Labels: service/codepipeline, needs-triage
