### ISSUE TITLE
[Enhancement]: Improvements to aws_rds_cluster_actiivty_stream

### ISSUE THREAD

**Issue by jbbeal** [hashicorp/terraform-provider-aws#38646] opened 2024-08-01 17:18 UTC
### Description

Currently trying to set up RDS Cluster activity streams in Terraform for tracking database changes.

At a minimum, the `aws_rds_cluster_activity_stream` should export the ARN for the underlying kinesis data stream. (Using a firehose delivery stream to dump logs into S3 seems like a common use case for this data, and firehose requires a correctly formatted ARN for the kinesis stream.) 

 It should also be possible to set tags on the activity stream so we can allocate costs of the Kinesis stream.

### Affected Resource(s) and/or Data Source(s)

* aws_rds_cluster_activity_stream

### Potential Terraform Configuration

```terraform
resource "aws_rds_cluster_activity_stream" "this" {
  ...

  tags = {}
}

resource "aws_firehose_delivery_stream" {
  kinesis_source_configuration {
    aws_rds_cluster_actitivity_stream.this.arn
  }
}
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-08-27 20:24
Hey @jbbeal 👋 Thank you for taking the time to raise this! The [upstream API action](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_StartActivityStream.html) used doesn't return the Kinesis stream ARN, so that's not something we'd be able to add to this resources without upstream changes.

On the other hand, the `aws_rds_cluster_activity_stream` resource exports a [`kinesis_stream_name` attribute](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster_activity_stream#kinesis_stream_name), which can be used with the [`aws_kinesis_stream` data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/kinesis_stream) in order to get the ARN you're looking for.

Can you verify whether that would work in your scenario?

**Comment by jbbeal** [comment] 2024-08-28 04:30
The data source is exactly how I worked around the limitation in the resource, but it does not allow me to apply tagging to the kinesis stream.  Are terraform providers constrained to be no better than the underlying AWS API? That would be unfortunate.

**Comment by justinretzolk** [comment] 2024-08-28 18:35
Glad to hear the data source helped work around the limitation for you! As far as being constrained to the underlying API -- outside of a few edge cases, the provider maps as closely to 1:1 with the underlying API as possible. This aligns with the [provider design principles](https://developer.hashicorp.com/terraform/plugin/best-practices/hashicorp-provider-design-principles) that we recommend all providers follow.

If you'd like to manage the Kinesis stream that gets created, you could [import it](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_stream), but it would need to be two separate applies (I'd actually recommend to separate the configurations so that you don't wind up overly reliant on targeted applies). There are a few open issues in the main Terraform repository that are tracking requests like yours, as ultimately, this is something that will require a change in Terraform Core before it can be supported:

- https://github.com/hashicorp/terraform/issues/34152
- https://github.com/hashicorp/terraform/issues/30937

I'd be remiss if I didn't at least mention [Terraform Stacks](https://www.hashicorp.com/blog/terraform-stacks-explained) as well, which should eventually help with this type of multi-apply situation.

Since there's no further action for the AWS Provider team at this point in time, I'm going to close this issue. If you run into any other unexpected behavior, please do let us know!

**Closed by justinretzolk** 2024-08-28 18:35 UTC
Labels: enhancement, service/rds, needs-triage
