### ISSUE TITLE
Unable to update desired_count in ECS service with CODE_DEPLOY deployment controller !

### ISSUE THREAD

**Issue by Reli4ble** [hashicorp/terraform-provider-aws#17311] opened 2021-01-27 11:21 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/aws v3.25.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

* aws_ecs_service

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_ecs_service" "worker" {
  name            = join("-", [data.aws_ssm_parameter.app_name.value, data.aws_ssm_parameter.environment.value, "service"])
  cluster         = data.aws_ssm_parameter.cluster_id.value
  task_definition = aws_ecs_task_definition.task_definition.arn
  scheduling_strategy                = "REPLICA"
  launch_type                        = "EC2"
  desired_count                      = var.container_count
  deployment_maximum_percent         = 200
  deployment_minimum_healthy_percent = 100
//  depends_on = [aws_lb.ecs-alb]
  propagate_tags = "SERVICE"

  tags = merge(map(
               "Name", join("-", [data.aws_ssm_parameter.app_name.value, data.aws_ssm_parameter.environment.value, "service"]),
    ), local.default_tags)

  ordered_placement_strategy {
    type  = "spread"
    field = "attribute:ecs.availability-zone"
  }  

  
  network_configuration {
    assign_public_ip = false
    security_groups = [data.aws_ssm_parameter.worker_sec_group.value]
    subnets = var.private_subnets
  }
  
  deployment_controller {
    type = "CODE_DEPLOY"
  }

  load_balancer {
    target_group_arn = data.aws_ssm_parameter.lb_tg1_arn.value
    container_name   = var.container_name
    container_port   = var.container_port
  }
}

```

### Debug Output

https://gist.github.com/Reli4ble/e2ca0e74ae65c69750e2cea7d5ffed2c

### Expected Behavior

After changing the desired_count in ecs_service from 2 to 3 and running terraform apply the service starts an additional task.

### Actual Behavior

Terraform apply fails and produced the following error:
Error: Error updating ECS Service (arn:aws:ecs:eu-central-1:208741481725:service/frdlso-abn-13e7534ad2/frdlso-abn-service): InvalidParameterException: Unable to update network parameters on services with a CODE_DEPLOY deployment controller. Use AWS CodeDeploy to trigger a new deployment.

### Steps to Reproduce

1. `terraform apply`
2. Edit desired_count
3. `terraform apply`

### References

* #0000

**Comment by bflad** [comment] 2021-01-27 19:19
Hi @Reli4ble :wave: Thank you for raising this issue and sorry you ran into trouble here. This appears to be a duplicate of https://github.com/hashicorp/terraform-provider-aws/issues/13658, so to consolidate discussions and efforts, I'm going to close this issue in preference of the linked one. Please :+1: react and subscribe to that issue for further updates. Thanks.

**Closed by bflad** 2021-01-27 19:19 UTC
Labels: bug, service/ecs
