### ISSUE TITLE
Bug in aws_cloudfront_distribution with AWS Provider v4.29.0 - Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by NickHirras** [hashicorp/terraform-provider-aws#26743] opened 2022-09-09 20:54 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Installing terraform (1.2.0-r2)
 ...
Initializing provider plugins...
- Finding hashicorp/aws versions matching ">= 4.0.0"...
- Finding latest version of hashicorp/null...
- Installing hashicorp/null v3.1.1...
- Installed hashicorp/null v3.1.1 (signed by HashiCorp)
- Installing hashicorp/aws v4.29.0...
- Installed hashicorp/aws v4.29.0 (signed by HashiCorp)
```

### Affected Resource(s)

* aws_cloudfront_distribution

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_cloudfront_distribution" "s3_distribution" {
  origin {
    domain_name = aws_s3_bucket.service.bucket_regional_domain_name
    origin_id   = "s3_web"
    origin_path = "/www"

    s3_origin_config {
      origin_access_identity = aws_cloudfront_origin_access_identity.service.cloudfront_access_identity_path
    }
  }

  origin {
    domain_name = aws_s3_bucket.service.bucket_regional_domain_name
    origin_id   = "s3_analysis_reports"

    s3_origin_config {
      origin_access_identity = aws_cloudfront_origin_access_identity.service.cloudfront_access_identity_path
    }
  }

  origin {
    domain_name = replace(aws_api_gateway_deployment.api_v1.invoke_url, "/^https?://([^/]*).*/", "$1")
    origin_id   = "api_v1"
    origin_path = "/${var.env}"

    custom_origin_config {
      http_port              = "80"
      https_port             = "443"
      origin_protocol_policy = "https-only"
      origin_ssl_protocols   = ["SSLv3", "TLSv1.2", "TLSv1.1"]
    }
  }

  enabled             = true
  is_ipv6_enabled     = true
  comment             = "Cloudfront distribution for the interchange optimization service."
  default_root_object = "index.html"

  logging_config {
    include_cookies = false
    bucket          = aws_s3_bucket.log_bucket.bucket_domain_name
    prefix          = "cloudfrontLogs/"
  }

  aliases = ["interchangeoptimization.${data.aws_route53_zone.private.name}"]

  default_cache_behavior {
    allowed_methods  = ["GET", "HEAD"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = "s3_web"

    forwarded_values {
      query_string = true
      headers      = []
      cookies {
        forward = "none"
      }
    }

    min_ttl                = 0       # do-not-cache
    default_ttl            = 3600    # 1 hour
    max_ttl                = 86400   # 1 day
    
    compress               = true
    viewer_protocol_policy = "redirect-to-https"
  }

  ordered_cache_behavior {
    path_pattern     = "/index.html"
    allowed_methods  = ["GET", "HEAD"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = "s3_web"

    forwarded_values {
      query_string = false
      headers      = []
      cookies {
        forward = "none"
      }
    }

    min_ttl                = 0
    default_ttl            = 20
    max_ttl                = 60

    compress               = true
    viewer_protocol_policy = "redirect-to-https"
  }

  ordered_cache_behavior {
    path_pattern     = "/interchange_analysis/*"
    allowed_methods  = ["GET", "HEAD"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = "s3_analysis_reports"

    forwarded_values {
      query_string = false
      headers      = []
      cookies {
        forward = "none"
      }
    }

    min_ttl                = 86400   # 1 day
    default_ttl            = 86400   # 1 day
    max_ttl                = 864000  # 10 days

    compress               = true
    viewer_protocol_policy = "redirect-to-https"
  }

  ordered_cache_behavior {
    path_pattern     = "/api/v1/*"
    allowed_methods  = ["DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = "api_v1"

    forwarded_values {
      query_string = false
      headers      = ["*"]
      cookies {
        forward    = "all"
      }
    }

    # No caching for API requests
    min_ttl                = 0
    default_ttl            = 0
    max_ttl                = 0

    compress               = true
    viewer_protocol_policy = "redirect-to-https"
  }

  price_class = "PriceClass_100"

  restrictions {
    geo_restriction {
      restriction_type = "whitelist"
      locations        = ["US", "BR", "BE", "FR", "DE", "GB", "IE", "IT", "NL", "BV", "NO", "SG", "AU"]
    }
  }

  viewer_certificate {
    cloudfront_default_certificate = false 
    acm_certificate_arn            = data.aws_acm_certificate.cert.arn
    minimum_protocol_version       = "TLSv1"
    ssl_support_method             = "sni-only"
  }
}
```

### Expected Behavior

Expect terraform to apply any changes.

### Actual Behavior

```
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ module.interchange_optimization_service.aws_cloudfront_distribution.s3_distribution
│ to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for
│ .origin: planned set element
│ cty.ObjectVal(map[string]cty.Value{"connection_attempts":cty.NumberIntVal(3),
│ "connection_timeout":cty.NumberIntVal(10),
│ "custom_header":cty.SetValEmpty(cty.Object(map[string]cty.Type{"name":cty.String,
│ "value":cty.String})),
│ "custom_origin_config":cty.ListValEmpty(cty.Object(map[string]cty.Type{"http_port":cty.Number,
│ "https_port":cty.Number, "origin_keepalive_timeout":cty.Number,
│ "origin_protocol_policy":cty.String, "origin_read_timeout":cty.Number,
│ "origin_ssl_protocols":cty.Set(cty.String)})),
│ "domain_name":cty.StringVal("interchange-optimization-service-dev-us-east-1.s3.amazonaws.com"),
│ "origin_access_control_id":cty.NullVal(cty.String),
│ "origin_id":cty.StringVal("s3_analysis_reports"),
│ "origin_path":cty.StringVal(""),
│ "origin_shield":cty.ListValEmpty(cty.Object(map[string]cty.Type{"enabled":cty.Bool,
│ "origin_shield_region":cty.String})),
│ "s3_origin_config":cty.ListVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"origin_access_identity":cty.StringVal("origin-access-identity/cloudfront/EP8A9XJJEPZP5")})})})
│ does not correlate with any element in actual.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ module.interchange_optimization_service.aws_cloudfront_distribution.s3_distribution
│ to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for
│ .origin: planned set element
│ cty.ObjectVal(map[string]cty.Value{"connection_attempts":cty.NumberIntVal(3),
│ "connection_timeout":cty.NumberIntVal(10),
│ "custom_header":cty.SetValEmpty(cty.Object(map[string]cty.Type{"name":cty.String,
│ "value":cty.String})),
│ "custom_origin_config":cty.ListValEmpty(cty.Object(map[string]cty.Type{"http_port":cty.Number,
│ "https_port":cty.Number, "origin_keepalive_timeout":cty.Number,
│ "origin_protocol_policy":cty.String, "origin_read_timeout":cty.Number,
│ "origin_ssl_protocols":cty.Set(cty.String)})),
│ "domain_name":cty.StringVal("interchange-optimization-service-dev-us-east-1.s3.amazonaws.com"),
│ "origin_access_control_id":cty.NullVal(cty.String),
│ "origin_id":cty.StringVal("s3_web"), "origin_path":cty.StringVal("/www"),
│ "origin_shield":cty.ListValEmpty(cty.Object(map[string]cty.Type{"enabled":cty.Bool,
│ "origin_shield_region":cty.String})),
│ "s3_origin_config":cty.ListVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"origin_access_identity":cty.StringVal("origin-access-identity/cloudfront/EP8A9XJJEPZP5")})})})
│ does not correlate with any element in actual.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

### Steps to Reproduce

1. `terraform apply`

**Comment by NickHirras** [comment] 2022-09-12 14:08
This bug appeared in AWS provider v4.29.0, with v4.28.0 it works as expected.

**Comment by ewbankkit** [comment] 2022-09-12 14:27
Possibly related: https://github.com/hashicorp/terraform-provider-aws/pull/26510.

**Comment by roberth-k** [comment] 2022-09-13 19:07
Hi @NickHirras 👋, and thank you for the bug report!

Would you be able to provide the following details about the situation in which this bug occurs for you?

- Was the resource originally created with provider version 4.28 or below?
- When you ran `terraform apply` and the bug occurred, was this the first time the Terraform code had been applied since the provider was upgraded to version 4.29?
- Did the failing run of `terraform apply` include any changes to the `aws_cloudfront_distribution` resource? If yes, what were the changes?
- Does the issue persist after running `terraform apply` multiple times?

I've been unable to reproduce this issue, so any additional information would be very helpful. Thanks again!

**Comment by NickHirras** [comment] 2022-09-15 17:50
- Was the resource originally created with provider version 4.28 or below?
  - Originally created with an older version.  This is run in a CD pipeline which always uses the latest provider.  4.28 the last successful deployment.
- When you ran terraform apply and the bug occurred, was this the first time the Terraform code had been applied since the provider was upgraded to version 4.29?
  - Yes.  It was deployed successfully the previous day using 4.28.  Then with the release of 4.29 it began failing.  We locked provider to 4.28 and it applies successfully.
- Did the failing run of terraform apply include any changes to the aws_cloudfront_distribution resource? If yes, what were the changes?
  - No changes
- Does the issue persist after running terraform apply multiple times?
  - Yes, it's tried unsuccessfully to terraform apply 12 times before we stopped and reverted the provider version to 4.28  I didn't try to immediately re-run it, it was over the course of a few days.

**Comment by jasonmarlin** [comment] 2022-10-15 12:07
Just to add on, I saw the same behavior on 4.34 with a Cloudfront resource created in a much earlier version. Locking to 4.28 allowed the run to complete.

**Comment by devin-duan** [comment] 2022-11-08 03:23
We added this, and somehow it works for us.
`origin_shield {
  enabled = false
  origin_shield_region = "us-east-1"
} `

**Comment by jar-b** [comment] 2023-02-10 15:35
Hi @NickHirras - I've attempted to reproduce this error with a minimal configuration, but have thus far been unable to do so. At a high level I created a cloud front distribution with `v4.28.0` of the provider, upgraded to `v4.29.0`, then applied various types of changes (unrelated resources as [this response indicated](https://github.com/hashicorp/terraform-provider-aws/issues/26743#issuecomment-1248419136), `origin` modifications, and `tag` changes). Complete details are documented below.

A couple follow-ups:
- Can you provide any more information about the planned changes prior to the `apply` that failed? This might help to create a configuration that will reproduce the error.
- Are you still pinned to v4.28.0? If so have you attempted updating to later versions of the provider and/or terraform?


### Terraform configuration

<details>
<summary>Show configuration</summary>

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      # first apply - last working version
      version = "4.28.0"
      # second apply - version observing regression
      #version = "4.29.0"
    }
  }
}

# Configure the AWS Provider
provider "aws" {}

resource "aws_cloudfront_origin_access_identity" "test" {
  comment = "testing"
}

resource "aws_s3_bucket" "test" {
  bucket        = "jb-test-cloudfront-distribution-inconsistent-final-plan"
  force_destroy = true
}

resource "aws_s3_bucket_acl" "test" {
  bucket = aws_s3_bucket.test.id
  acl    = "private"
}

# attempt 1 - modify an unrelated resource (ie. no changes to the cloudfront distribution on apply)
#resource "aws_s3_bucket" "test2" {
  #bucket        = "jb-test-unrelated-resource2"
  #force_destroy = true
#}

resource "aws_cloudfront_distribution" "test" {
  enabled = true

  default_cache_behavior {
    allowed_methods        = ["GET", "HEAD"]
    cached_methods         = ["GET", "HEAD"]
    target_origin_id       = "s3_web"
    viewer_protocol_policy = "allow-all"

    forwarded_values {
      query_string = false

      cookies {
        forward = "all"
      }
    }
  }

  origin {
    domain_name = aws_s3_bucket.test.bucket_regional_domain_name
    origin_id   = "s3_web"
    origin_path = "/www"

    s3_origin_config {
      origin_access_identity = aws_cloudfront_origin_access_identity.test.cloudfront_access_identity_path
    }
  }

  origin {
    domain_name = aws_s3_bucket.test.bucket_regional_domain_name
    origin_id   = "s3_analysis_reports"

    s3_origin_config {
      origin_access_identity = aws_cloudfront_origin_access_identity.test.cloudfront_access_identity_path
    }
  }

  # attempt 2 - adding a new origin attribute
  #origin {
    #domain_name = aws_s3_bucket.test.bucket_regional_domain_name
    #origin_id   = "s3_new_thing"

    #s3_origin_config {
      #origin_access_identity = aws_cloudfront_origin_access_identity.test.cloudfront_access_identity_path
    #}
  #}

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  viewer_certificate {
    cloudfront_default_certificate = true
  }

  # attempt 3 - changing a non-origin attribute
  #tags = {
    #"Key1" = "Value1"
  #}
}
```

</details>

### Attempted Reproduction

1. `terraform apply` with v4.28.0

2. Upgrade to v4.29.0, `terraform init -upgrade`

<details>
<summary>Show command</summary>

```console
$ terraform init -upgrade

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/aws versions matching "4.29.0"...
- Installing hashicorp/aws v4.29.0...
- Installed hashicorp/aws v4.29.0 (signed by HashiCorp)

Terraform has made some changes to the provider dependency selections recorded
in the .terraform.lock.hcl file. Review those changes and commit them to your
version control system if they represent changes you intended to make.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

</details>


3a. Attempt 1 - Modify an unrelated resource

<details>
<summary>Show command</summary>

```console
$ terraform -v
Terraform v1.2.0
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.29.0

Your version of Terraform is out of date! The latest version
is 1.3.7. You can update by downloading from https://www.terraform.io/downloads.html
```

```console
$ terraform apply
aws_cloudfront_origin_access_identity.test: Refreshing state... [id=E1GK3NDZ9RZ57P]
aws_s3_bucket.test2: Refreshing state... [id=jb-test-unrelated-resource]
aws_s3_bucket.test: Refreshing state... [id=jb-test-cloudfront-distribution-inconsistent-final-plan]
aws_s3_bucket_acl.test: Refreshing state... [id=jb-test-cloudfront-distribution-inconsistent-final-plan,private]
aws_cloudfront_distribution.test: Refreshing state... [id=E3LCLAX4YE34VS]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # aws_s3_bucket.test2 must be replaced
-/+ resource "aws_s3_bucket" "test2" {
      + acceleration_status         = (known after apply)
      + acl                         = (known after apply)
      ~ arn                         = "arn:aws:s3:::jb-test-unrelated-resource" -> (known after apply)
      ~ bucket                      = "jb-test-unrelated-resource" -> "jb-test-unrelated-resource2" # forces replacement
      ~ bucket_domain_name          = "jb-test-unrelated-resource.s3.amazonaws.com" -> (known after apply)
 <snip>

Plan: 1 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_s3_bucket.test2: Destroying... [id=jb-test-unrelated-resource]
aws_s3_bucket.test2: Destruction complete after 0s
aws_s3_bucket.test2: Creating...
aws_s3_bucket.test2: Creation complete after 3s [id=jb-test-unrelated-resource2]

Apply complete! Resources: 1 added, 0 changed, 1 destroyed.
```

</details>


3b. Attempt 2 - Add a new `origin` block

<details>
<summary>Show command</summary>

```console
$ terraform -v
Terraform v1.2.0
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.29.0

Your version of Terraform is out of date! The latest version
is 1.3.7. You can update by downloading from https://www.terraform.io/downloads.html
```

```console
$ terraform apply
aws_cloudfront_origin_access_identity.test: Refreshing state... [id=E1P1UZPXCMTMY9]
aws_s3_bucket.test: Refreshing state... [id=jb-test-cloudfront-distribution-inconsistent-final-plan]
aws_s3_bucket_acl.test: Refreshing state... [id=jb-test-cloudfront-distribution-inconsistent-final-plan,private]
aws_cloudfront_distribution.test: Refreshing state... [id=E3SZMPDR1O154B]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_cloudfront_distribution.test will be updated in-place
  ~ resource "aws_cloudfront_distribution" "test" {
        id                             = "E3SZMPDR1O154B"
        tags                           = {}
        # (18 unchanged attributes hidden)


      - origin {
          - connection_attempts = 3 -> null
          - connection_timeout  = 10 -> null
          - domain_name         = "jb-test-cloudfront-distribution-inconsistent-final-plan.s3.us-west-2.amazonaws.com" -> null
          - origin_id           = "s3_analysis_reports" -> null

          - s3_origin_config {
              - origin_access_identity = "origin-access-identity/cloudfront/E1P1UZPXCMTMY9" -> null
            }
        }
      + origin {
          + connection_attempts = 3
          + connection_timeout  = 10
          + domain_name         = "jb-test-cloudfront-distribution-inconsistent-final-plan.s3.us-west-2.amazonaws.com"
          + origin_id           = "s3_new_thing"

          + s3_origin_config {
              + origin_access_identity = "origin-access-identity/cloudfront/E1P1UZPXCMTMY9"
            }
        }
      - origin {
          - connection_attempts = 3 -> null
          - connection_timeout  = 10 -> null
          - domain_name         = "jb-test-cloudfront-distribution-inconsistent-final-plan.s3.us-west-2.amazonaws.com" -> null
          - origin_id           = "s3_web" -> null
          - origin_path         = "/www" -> null

          - s3_origin_config {
              - origin_access_identity = "origin-access-identity/cloudfront/E1P1UZPXCMTMY9" -> null
            }
        }
      + origin {
          + connection_attempts = 3
          + connection_timeout  = 10
          + domain_name         = "jb-test-cloudfront-distribution-inconsistent-final-plan.s3.us-west-2.amazonaws.com"
          + origin_id           = "s3_analysis_reports"

          + s3_origin_config {
              + origin_access_identity = "origin-access-identity/cloudfront/E1P1UZPXCMTMY9"
            }
        }
      + origin {
          + connection_attempts = 3
          + connection_timeout  = 10
          + domain_name         = "jb-test-cloudfront-distribution-inconsistent-final-plan.s3.us-west-2.amazonaws.com"
          + origin_id           = "s3_web"
          + origin_path         = "/www"

          + s3_origin_config {
              + origin_access_identity = "origin-access-identity/cloudfront/E1P1UZPXCMTMY9"
            }
        }


        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_cloudfront_distribution.test: Modifying... [id=E3SZMPDR1O154B]
aws_cloudfront_distribution.test: Still modifying... [id=E3SZMPDR1O154B, 10s elapsed]
aws_cloudfront_distribution.test: Still modifying... [id=E3SZMPDR1O154B, 20s elapsed]
<snip>
aws_cloudfront_distribution.test: Still modifying... [id=E3SZMPDR1O154B, 11m35s elapsed]
aws_cloudfront_distribution.test: Modifications complete after 11m42s [id=E3SZMPDR1O154B]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

</details>


3c. Attempt 3 - Modify a non-`origin` block (tags)

<details>
<summary>Show command</summary>

```console
$ terraform -v
Terraform v1.2.0
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.29.0

Your version of Terraform is out of date! The latest version
is 1.3.7. You can update by downloading from https://www.terraform.io/downloads.html
```

```console
$ terraform apply
aws_cloudfront_origin_access_identity.test: Refreshing state... [id=E2OM7C64LVZQNE]
aws_s3_bucket.test: Refreshing state... [id=jb-test-cloudfront-distribution-inconsistent-final-plan]
aws_s3_bucket_acl.test: Refreshing state... [id=jb-test-cloudfront-distribution-inconsistent-final-plan,private]
aws_cloudfront_distribution.test: Refreshing state... [id=E1FJ2YUMQB0EOD]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_cloudfront_distribution.test will be updated in-place
  ~ resource "aws_cloudfront_distribution" "test" {
        id                             = "E1FJ2YUMQB0EOD"
      ~ tags                           = {
          + "Key1" = "Value1"
        }
      ~ tags_all                       = {
          + "Key1" = "Value1"
        }
        # (17 unchanged attributes hidden)




        # (5 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_cloudfront_distribution.test: Modifying... [id=E1FJ2YUMQB0EOD]
aws_cloudfront_distribution.test: Still modifying... [id=E1FJ2YUMQB0EOD, 10s elapsed]
aws_cloudfront_distribution.test: Still modifying... [id=E1FJ2YUMQB0EOD, 20s elapsed]
<snip>
aws_cloudfront_distribution.test: Still modifying... [id=E1FJ2YUMQB0EOD, 3m0s elapsed]
aws_cloudfront_distribution.test: Modifications complete after 3m8s [id=E1FJ2YUMQB0EOD]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

</details>

**Comment by jar-b** [comment] 2023-02-28 19:13
@stephanedesjardins-qc - Can you please open a new issue with your complete configuration and terraform output?

**Comment by jar-b** [comment] 2023-02-28 20:22
At this time we have not received confirmation of an ongoing issue with the configuration described in the original issue, and have been unable to reproduce the behavior. 

We will be closing this issue, and ask that those commenting with similar errors please open a new issue. The complete configuration, version information, and terraform output allows us to more accurately assess cause and reproduce errors.

**Closed by jar-b** 2023-02-28 20:22 UTC
Labels: bug, regression, service/cloudfront
