### ISSUE TITLE
How to ignore maintenance schedule start time on aws_elasticsearch_domain

### ISSUE THREAD

**Issue by bodgit** [hashicorp/terraform-provider-aws#23669] opened 2022-03-14 17:40 UTC
I'm trying to set the auto tune settings for an Elastic^WOpenSearch domain, the default start time seems to be set to the creation time of the domain plus one day, so I've set the `start_at` attribute using `timeadd(timestamp(), "1d")`.

Because this will change on every plan/apply, I want to ignore this value on future runs however I can't find valid syntax to do this.

If I use `auto_tune_options.0.maintenance_schedule.0.start_at`, I get this error:

```
Block type "maintenance_schedule" is represented by a set of objects, and set elements do not have addressable keys. To find elements matching specific criteria, use a "for" expression with an "if" clause.
```

When I tried setting the `start_at` value to just `""`, I got this error:

```
Error: expected "auto_tune_options.0.maintenance_schedule.0.start_at" to be a valid RFC3339 date, got "": parsing time "" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "2006"
```

So the error message uses the exact same notation that I'm trying to use.

The best I have managed to do is ignore `auto_tune_options.0.maintenance_schedule` but that ignores the whole block. The other solution currently is to just put a static timestamp when writing the resource out.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform 1.1.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.72.0
```
### Affected Resource(s)

* aws_elasticsearch_domain

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_elasticsearch_domain" "es" {
  domain_name = "test"

  auto_tune_options {
    desired_state       = "ENABLED"
    rollback_on_disable = "DEFAULT_ROLLBACK"

    maintenance_schedule {
      start_at                       = timeadd(timestamp(), "1d")
      cron_expression_for_recurrence = "cron(0 0 ? * 1 *)"

      duration {
        value = 2
        unit  = "HOURS"
      }
    }
  }

  lifecycle {
    ignore_changes = [
      auto_tune_options.0.maintenance_schedule.0.start_at, # DOES NOT WORK
    ]
  }
}
```

### Expected Behavior

I should be able to ignore the start time.

### Actual Behavior

I can't find a satisfactory syntax to only ignore the start time.

### Steps to Reproduce

1. `terraform apply`

**Comment by tyrken** [comment] 2023-02-27 17:50
Duplicate of #22239

**Closed** 2023-02-28 20:29 UTC
Labels: question, service/elasticsearch
