### ISSUE TITLE
Add support for graviton fargate

### ISSUE THREAD

**Issue by bacoboy** [hashicorp/terraform-provider-aws#21885] opened 2021-11-23 22:39 UTC
Support for graviton Fargate containers was recently announced.
We'll need an additional parameter added to specify the architecture in the `aws_ecs_task_definition` resource (as well as the reading via the data source counterpart.

https://aws.amazon.com/blogs/aws/announcing-aws-graviton2-support-for-aws-fargate-get-up-to-40-better-price-performance-for-your-serverless-containers/

**Comment by acdha** [comment] 2021-11-24 17:07
This looks like a duplicate of #21706

**Comment by bacoboy** [comment] 2021-11-24 17:48
I wasn't sure -- I guess it depends on the underlying implementation.  Could be that the same PR solves both of these.

**Comment by justinretzolk** [comment] 2021-12-09 19:25
Hey @acdha 👋 Thanks for taking the time to submit this issue. It looks like this is indeed a duplicate of #21706. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #21706.

**Closed by justinretzolk** 2021-12-09 19:25 UTC
Labels: enhancement, needs-triage
