### ISSUE TITLE
Configure aws_lambda_layer_version for AWS Managed Layer

### ISSUE THREAD

**Issue by shreyanshmohnot** [hashicorp/terraform-provider-aws#22681] opened 2022-01-20 09:16 UTC
How can we configure aws_lambda_layer_version for AWS Managed Layers, specifically **data "aws_lambda_layer_version"**?

### Affected Resource(s)

aws_lambda_layer_version

### Terraform Configuration Files

data "aws_lambda_layer_version" "awswrangler_layer" {
  layer_name = "AWSDataWrangler-Python38"
  version = 2
}

### Debug Output

Error: error getting Lambda Layer Version (AWSDataWrangler-Python38, version 2): ResourceNotFoundException: The resource you requested does not exist.
│ {
│   RespMetadata: {
│     StatusCode: 404,
│     RequestID: "3b1ccef5-34ac-4aff-8a1e-62f14611483e"
│   },
│   Message_: "The resource you requested does not exist.",
│   Type: "User"
│ }

### References

https://github.com/awslabs/aws-data-wrangler
https://aws-data-wrangler.readthedocs.io/en/stable/install.html

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by justinretzolk** [comment] 2022-01-20 22:31
Hey @shreyanshmohnot 👋 Thank you for taking the time to raise this. So that we have the information we need in order to look into this, can you update the issue description to include the full debug logs (redacted as necessary)?

**Comment by shreyanshmohnot** [comment] 2022-01-20 23:38
> Hey @shreyanshmohnot 👋 Thank you for taking the time to raise this. So that we have the information we need in order to look into this, can you update the issue description to include the full debug logs (redacted as necessary)?
Hi @justinretzolk! Thanks for your response. So this is basically an Public AWS Managed Lambda Layer and I want to access that using the Terraform.
Let me know if the log files helps.

[apply.txt](https://github.com/hashicorp/terraform-provider-aws/files/7909146/apply.txt)

**Comment by justinretzolk** [comment] 2022-01-22 01:46
Hey @shreyanshmohnot 👋 I looked into this a bit more and noticed that the [`aws` CLI documentation](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/get-layer-version.html) required an ARN for the `--layer-name` argument. With that in mind, I updated the configuration you supplied as follows and was able to successfully use the data source:

```hcl
data "aws_lambda_layer_version" "awswrangler_layer" {
  layer_name = "arn:aws:lambda:us-east-1:336392948345:layer:AWSDataWrangler-Python38"
  version    = 2
}
```

**Comment by shreyanshmohnot** [comment] 2022-01-22 02:16
That's great. Thanks for the find @justinretzolk . I had not realized as https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/lambda_layer_version required only the layer name, so.

**Comment by justinretzolk** [comment] 2022-01-24 19:42
I'm glad that helped @shreyanshmohnot! I'll go ahead and close this issue out since we've figured out the cause of the issue. If you feel I've done this in error, please do let me know.

**Closed by justinretzolk** 2022-01-24 19:42 UTC
Labels: question, service/lambda

**Comment by DanielDaCosta** [comment] 2022-04-04 18:02
hello everyone, does anyone is still facing this problem?

I tried the proposed solution using the layer_name ARN, but I am still facing the same problem.

Terraform code:
```
data "aws_lambda_layer_version" "awswrangler_layer" {
  layer_name = "arn:aws:lambda:${var.region}:${data.aws_caller_identity.current.account_id}:layer:AWSDataWrangler-Python38"
  version = 3
}
```


Error Message: 
```
│ Error: error getting Lambda Layer Version (arn:aws:lambda:us-east-1:{ACCOUNT_ID}:layer:AWSDataWrangler-Python38, version 3): ResourceNotFoundException: The resource you requested does not exist.
│ {
│   RespMetadata: {
│     StatusCode: 404,
│     RequestID: "1c22c426-2a58-4832-9ab2-730a9e632eac"
│   },
│   Message_: "The resource you requested does not exist.",
│   Type: "User"
│ }
│ 
│   with data.aws_lambda_layer_version.awswrangler_layer,
│   on lambdas.tf line 347, in data "aws_lambda_layer_version" "awswrangler_layer":
│  347: data "aws_lambda_layer_version" "awswrangler_layer" {`
```

**Comment by DanielDaCosta** [comment] 2022-04-04 18:14
> 

I just realized that the lambda layer ARN and ACCOUNT_ID are not my own but a constant ARN for everyone: `arn:aws:lambda:us-east-1:336392948345:layer:AWSDataWrangler-Python38`

I hope this realization helps someone.
