### ISSUE TITLE
[Docs]: Docsite infinitely loading

### ISSUE THREAD

**Issue by hazmeister** [hashicorp/terraform-provider-aws#27624] opened 2022-11-03 14:26 UTC
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_acl

### Description

Have tried a couple of different browsers, but the documentation fails to finish loading.  Developer tools seems to suggest that the analytics  request is not resolving, but that might be a red herring.

https://cdn.segment.com/analytics.js/v1/U76qKvXYmVH2WMznuNr4GisZyPJymtZv/analytics.min.js 

![image](https://user-images.githubusercontent.com/11080542/199746415-bfee30c0-9c6d-49a7-acbf-0e60a92b4c08.png)
![image](https://user-images.githubusercontent.com/11080542/199747260-b50f7ba2-8e16-49af-be40-5de6a1bb587c.png)

**Comment by codymaust** [comment] 2022-11-03 14:28
duplicate of #27623

**Comment by Mattie112** [comment] 2022-11-03 14:55
You can see the docs here if you need them: https://github.com/hashicorp/terraform-provider-aws/tree/main/website/docs/r

**Comment by ewbankkit** [comment] 2022-11-03 15:19
https://status.hashicorp.com/incidents/vbr6hdbp9y4g

**Comment by justinretzolk** [comment] 2022-11-03 16:05
Hey y'all 👋 This was due to an incident with the Terraform Registry that [has now been resolved](https://status.hashicorp.com/incidents/vbr6hdbp9y4g), so we'll close this issue. If you have further issues with the Terraform Registry, please do let us know.

**Closed by justinretzolk** 2022-11-03 16:05 UTC
Labels: documentation, needs-triage
