### ISSUE TITLE
[Bug] There aren't platform data in terraform registry versions api at v5.71.0

### ISSUE THREAD

**Issue by weijiany** [hashicorp/terraform-provider-aws#39706] opened 2024-10-14 05:39 UTC
### Description

Hello Contributors,

I discovered that the Terraform registry version API lacks platform data, which is causing issues for Renovate. As a result, Renovate is unable to successfully update the Terraform lock file. I'm unsure if this is the correct place to raise this issue.

Renovate attempts to retrieve all the hash lines from the Terraform lock file via the [Terraform Registry API](https://developer.hashicorp.com/terraform/registry/api-docs). However, for the latest provider version (5.71.0), no platform data is available.

```shell
curl https://registry.terraform.io/v1/providers/hashicorp/aws/versions | jq '.versions | .[] | select(.version == "5.71.0")'
```

### Would you like to implement a fix?

None

**Comment by jasonm3-netapp** [comment] 2024-10-14 19:39
Has anyone figured out a workaround for this?

**Comment by justinretzolk** [comment] 2024-10-14 21:58
Hey @weijiany 👋 Thank you for taking the time to raise this! The `5.71.0` release had issues that caused us to pull the release. We plan to release a new version of the provider (`5.72.0`) on Thursday, October 17th that includes the changes that were originally included in `5.71.0`, and have [updated the changelog](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md) to reflect this. 

As far as the issue with Renovate, that would need to be reported in the bot's repository (while I'm not familiar, I believe that repository is located [here](https://github.com/renovatebot/renovate), but given I've not used the tool, that may be incorrect).

Since there's further action for the AWS Provider team to take, I'm going to close this issue. If you encounter unexpected behavior in the future, please do let us know!

**Closed by justinretzolk** 2024-10-14 21:58 UTC
Labels: needs-triage

**Comment by EvansM4** [comment] 2024-10-14 23:14
@justinretzolk just FYI the current provider 5.71.0 is still not listing the available architectures hence you still get build failures if you are not version locking see below<img width="496" alt="image" src="https://github.com/user-attachments/assets/b08bbe64-eda6-4a3d-a2fe-899a5e03cd00">

**Comment by et304383** [comment] 2024-10-15 13:25
This needs to be addressed asap.  We cannot be blocked on pulling a new version of the provider when all of our projects are pinned at `~> 5.0`.
