### ISSUE TITLE
[Bug]: Changing aws_api_gateway_method request_parameters's required property results in the unexpected toggling of the existing caching setting

### ISSUE THREAD

**Issue by vargabi** [hashicorp/terraform-provider-aws#39360] opened 2024-09-17 14:25 UTC
### Terraform Core Version

1.9.5

### AWS Provider Version

5.67.0

### Affected Resource(s)

aws_api_gateway_method
aws_api_gateway_integration

### Expected Behavior

The modification of the request_parameters' entry's **Required** setting (either from false to true or from true to false) doesn't cause the existing cache_key_parameter's **Caching** setting to toggle. 

### Actual Behavior

I have an existing **aws_api_gateway_method** resource with configured **request_parameters**, and also with the relevant caching settings configured under **aws_api_gateway_integration**'s **cache_key_parameters**. I changed the Required setting for the parameter from **true** to **false** and this caused the Caching setting for the param to change from **true** to **false**.
There are no sings of this change anywhere in the planning phase, before I apply the change.

This is the relevant resource configuration:
```
resource "aws_api_gateway_method" "my_content_provider" {
  rest_api_id = aws_api_gateway_rest_api.my_api.id
  resource_id = aws_api_gateway_resource.my_content_provider.id
  http_method = "GET"
  authorization = "NONE"

  request_parameters = {
    "method.request.querystring.id" = true
  }
  request_validator_id = aws_api_gateway_request_validator.request_query_param.id
}

resource "aws_api_gateway_integration" "my_content_provider" {
  rest_api_id = aws_api_gateway_rest_api.my_api.id
  resource_id = aws_api_gateway_resource.my_content_provider.id
  http_method = aws_api_gateway_method.my_content_provider.http_method
  integration_http_method = "POST"
  type = "AWS_PROXY"
  uri = aws_lambda_function.page_content_data_provider.invoke_arn

  cache_key_parameters = [
    "method.request.querystring.id"
  ]
}
```

I would expect the **Caching** setting to **NOT** toggle when I update the Required setting of the query param.

### Terraform Configuration Files

```
resource "aws_api_gateway_method" "my_content_provider" {
  rest_api_id = aws_api_gateway_rest_api.my_api.id
  resource_id = aws_api_gateway_resource.my_content_provider.id
  http_method = "GET"
  authorization = "NONE"

  request_parameters = {
    "method.request.querystring.id" = true
  }
  request_validator_id = aws_api_gateway_request_validator.request_query_param.id
}

resource "aws_api_gateway_integration" "my_content_provider" {
  rest_api_id = aws_api_gateway_rest_api.my_api.id
  resource_id = aws_api_gateway_resource.my_content_provider.id
  http_method = aws_api_gateway_method.my_content_provider.http_method
  integration_http_method = "POST"
  type = "AWS_PROXY"
  uri = aws_lambda_function.page_content_data_provider.invoke_arn

  cache_key_parameters = [
    "method.request.querystring.id"
  ]
}
```

### Steps to Reproduce

Modify an existing query parameter's Required value and watch the Caching field also change.

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment] 2024-11-04 18:49
Hey @vargabi 👋 Thank you for taking the time to raise this! I'm fairly confident that the behavior you're seeing is a result of how the upstream API behaves.

When updating a `aws_api_gateway_method` resource, the provider uses API Gateway's [`UpdateMethod`](https://docs.aws.amazon.com/apigateway/latest/api/API_UpdateMethod.html) action ([provider source reference](https://github.com/hashicorp/terraform-provider-aws/blob/7a515b4fefe12fe9da295a048bfd9bc73d8c1cc7/internal/service/apigateway/method.go#L286-L291)). In order to use `UpdateMethod`, a list of `PatchOperation` [is constructed](https://github.com/hashicorp/terraform-provider-aws/blob/7a515b4fefe12fe9da295a048bfd9bc73d8c1cc7/internal/service/apigateway/flex.go#L75-L116) by the provider. The  [operation types available](https://docs.aws.amazon.com/apigateway/latest/api/patch-operations.html#UpdateMethod-Patch) for `requestParameters` are `add`, `replace`, and `remove`, so in your case, the provider would use `replace`.

Considering the Terraform plan, the change to `aws_api_gateway_method` is detected due to the change to the resource configuration. At that point in time, nothing has changed about the `aws_api_gateway_integration` resource's configuration (upstream or in the Terraform configuration). Because of that, no changes are detected by Terraform, and Terraform does not attempt to modify the `aws_api_gateway_integration` resource in any way. When the plan is applied, the request parameter is replaced (as mentioned above), at which point it seems that AWS flips the cache setting as well, introducing drift that I suspect would show up in subsequent runs as drift in the `aws_api_gateway_integration` resource. Are you seeing this drift on subsequent runs?

If I'm correct that the drift is detected on subsequent runs, this would be considered expected behavior that could be resolved by modifying the Terraform configuration. One way to do this would be to split the configuration up so that the `aws_api_gateway_method` resource is separate from `aws_api_gateway_integration` so that the plan/apply for the two of them happens separately. Alternatively, you could potentially leverage [`replace_triggered_by`](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#replace_triggered_by) to replace the `aws_api_gateway_integration` when the `aws_api_gateway_method.request_parameters` are modified. The latter feels like a bit of an extreme way to handle this situation, but figured I'd mention it in case it worked for you use case.

**Comment by vargabi** [comment] 2024-11-11 13:33
Hi @justinretzolk 👋 Thank you very much for taking the time to read and respond to my report.

I understand now how the provider applies this change and how it has no information about the unintended modifications in the background by AWS. I played around with aws cli (`aws apigateway update-method`), and also on the web console, and found that there is no way to modify the request parameter's **Required** setting and to keep the **Caching** setting enabled at the same time.

I also tried out the `replace_triggered_by` option but it resulted in an undefined integration. During the plan stage it wrote that my resource `..will be replaced due to changes in replace_triggered_by..` but in the end it got destroyed. Only when I ran the terraform again did it recreate it.

**Comment by justinretzolk** [comment] 2024-11-11 21:06
Thanks for the follow up here, @vargabi! While it's unfortunate, I'm glad you were able to reproduce the behavior in the CLI and AWS console, confirming that this seems to be upstream behavior rather than a provider bug. That `replace_triggered_by` behavior seems odd, but exploring that would be more fitting for a discussion in the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) rather than this issue, since we use issues in this repository to track bugs and/or feature requests in the provider. With that in mind, I'm going to close this issue, but if you experience any further unexpected behavior, please do let us know!

**Closed by justinretzolk** 2024-11-11 21:06 UTC
Labels: bug, service/apigateway, needs-triage
