### ISSUE TITLE
How to split a list of multiple maps into multiple lists of maps

### ISSUE THREAD

**Issue by pranavnateri** [hashicorp/terraform-provider-aws#31066] opened 2023-04-29 05:39 UTC
### Description

How to split a list of multiple maps into multiple lists of maps based on a certain condition.

I have the below list of maps for example

```
[{
domain_name           = "*.xpressplay.net"
resource_record_name  = "_f2190142da19f544c2976cd4b225a2a2.xpressplay.net."
resource_record_type  = "CNAME"
resource_record_value = "_20ac738536e444d53d5b027c7044ea88.fpktwqqglf.acm-validations.aws."
},
{
domain_name           = "test.expressplay.com"
resource_record_name  = "_60404817e3b91e87d065a72aa74c8872.test.expressplay.com."
resource_record_type  = "CNAME"
resource_record_value = "_87c90e7599f22e65ee4bbee68d09ac59.tctzzymbbs.acm-validations.aws."
},
{
domain_name           = "*.test.expressplay.com"
resource_record_name  = "_60404817e3b91e87d065a72aa74c8872.test.expressplay.com."
resource_record_type  = "CNAME"
resource_record_value = "_87c90e7599f22e65ee4bbee68d09ac59.tctzzymbbs.acm-validations.aws."
},
{
domain_name           = "dev.expressplay.com"
resource_record_name  = "_4c56de95440b3671a98d9cd8469bfc98.dev.expressplay.com."
resource_record_type  = "CNAME"
resource_record_value = "_1eef2b9329f955c0642f3313d94bf2bb.mzlfeqexyx.acm-validations.aws."
},
{
domain_name           = "*.dev.expressplay.com"
resource_record_name  = "_4c56de95440b3671a98d9cd8469bfc98.dev.expressplay.com."
resource_record_type  = "CNAME"
resource_record_value = "_1eef2b9329f955c0642f3313d94bf2bb.mzlfeqexyx.acm-validations.aws."
},
{
domain_name           = "xpressplay.net"
resource_record_name  = "_f2190142da19f544c2976cd4b225a2a2.xpressplay.net."
resource_record_type  = "CNAME"
resource_record_value = "_20ac738536e444d53d5b027c7044ea88.fpktwqqglf.acm-validations.aws."
},
{
domain_name           = "*.staging.expressplay.com"
resource_record_name  = "_bf2e2162667dd8254fbf25ac54efc7a9.staging.expressplay.com."
resource_record_type  = "CNAME"
resource_record_value = "_8b07502b93801fe901c449fcb6c0f27e.tctzzymbbs.acm-validations.aws."
},
{
domain_name           = "staging.expressplay.com"
resource_record_name  = "_bf2e2162667dd8254fbf25ac54efc7a9.staging.expressplay.com."
resource_record_type  = "CNAME"
resource_record_value = "_8b07502b93801fe901c449fcb6c0f27e.tctzzymbbs.acm-validations.aws."
},
]

```
i want to split this list of maps into 2 lists of maps based on the condition that if domain_name is "xpressplay.net" or "*.xpressplay.net" eventually to become like below

List 1:

```
[{
domain_name           = "*.xpressplay.net"
resource_record_name  = "_f2190142da19f544c2976cd4b225a2a2.xpressplay.net."
resource_record_type  = "CNAME"
resource_record_value = "_20ac738536e444d53d5b027c7044ea88.fpktwqqglf.acm-validations.aws."
},
{
domain_name           = "xpressplay.net"
resource_record_name  = "_f2190142da19f544c2976cd4b225a2a2.xpressplay.net."
resource_record_type  = "CNAME"
resource_record_value = "_20ac738536e444d53d5b027c7044ea88.fpktwqqglf.acm-validations.aws."
}
]
```
LIST2:

```
[{
domain_name           = "test.expressplay.com"
resource_record_name  = "_60404817e3b91e87d065a72aa74c8872.test.expressplay.com."
resource_record_type  = "CNAME"
resource_record_value = "_87c90e7599f22e65ee4bbee68d09ac59.tctzzymbbs.acm-validations.aws."
},
{
domain_name           = "*.test.expressplay.com"
resource_record_name  = "_60404817e3b91e87d065a72aa74c8872.test.expressplay.com."
resource_record_type  = "CNAME"
resource_record_value = "_87c90e7599f22e65ee4bbee68d09ac59.tctzzymbbs.acm-validations.aws."
},
{
domain_name           = "dev.expressplay.com"
resource_record_name  = "_4c56de95440b3671a98d9cd8469bfc98.dev.expressplay.com."
resource_record_type  = "CNAME"
resource_record_value = "_1eef2b9329f955c0642f3313d94bf2bb.mzlfeqexyx.acm-validations.aws."
},
{
domain_name           = "*.dev.expressplay.com"
resource_record_name  = "_4c56de95440b3671a98d9cd8469bfc98.dev.expressplay.com."
resource_record_type  = "CNAME"
resource_record_value = "_1eef2b9329f955c0642f3313d94bf2bb.mzlfeqexyx.acm-validations.aws."
},
{
domain_name           = "*.staging.expressplay.com"
resource_record_name  = "_bf2e2162667dd8254fbf25ac54efc7a9.staging.expressplay.com."
resource_record_type  = "CNAME"
resource_record_value = "_8b07502b93801fe901c449fcb6c0f27e.tctzzymbbs.acm-validations.aws."
},
{
domain_name           = "staging.expressplay.com"
resource_record_name  = "_bf2e2162667dd8254fbf25ac54efc7a9.staging.expressplay.com."
resource_record_type  = "CNAME"
resource_record_value = "_8b07502b93801fe901c449fcb6c0f27e.tctzzymbbs.acm-validations.aws."
},
]

```

Please help

Regards,
Pranav

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2023-05-01 21:37
Duplicate of #31065

**Closed by justinretzolk** 2023-05-01 21:37 UTC
Labels: enhancement, needs-triage
