### ISSUE TITLE
Feature Request: AWS Shield Subscription

### ISSUE THREAD

**Issue by jrbeilke** [hashicorp/terraform-provider-aws#23214] opened 2022-02-15 21:40 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Looking to use AWS Shield and would like to be able to use Terraform to manage Shield subscriptions. Ideally there would be some sort of new `aws_shield_subscription` resource that could be used in Terraform to manage the creation and renewal of Shield in an AWS account.

Here's the API ref from AWS:
https://docs.aws.amazon.com/waf/latest/DDOSAPIReference/API_CreateSubscription.html

### New or Affected Resource(s)

* aws_shield_subscription

### Potential Terraform Configuration

```hcl
resource "aws_shield_subscription" "example" {
  auto_renew = true
}
```

### References

* #1769

**Comment by justinretzolk** [comment] 2022-02-15 23:00
Hey @jrbeilke 👋 Thanks for taking the time to submit this issue. It looks like this is a duplicate of #21430. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #21430.

**Closed by justinretzolk** 2022-02-15 23:00 UTC
Labels: enhancement, service/shield, needs-triage
