### ISSUE TITLE
Support Cloudformation operation-preferences (RegionConcurrencyType, RegionOrder , FailureToleranceCount , FailureTolerancePercentage , MaxConcurrentCount , MaxConcurrentPercentage )

### ISSUE THREAD

**Issue by ashraf133** [hashicorp/terraform-provider-aws#21307] opened 2021-10-14 15:47 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

actually we can add these options to stackset deployment : 

```
{
  "RegionConcurrencyType": "SEQUENTIAL"|"PARALLEL",
  "RegionOrder": ["string", ...],
  "FailureToleranceCount": integer,
  "FailureTolerancePercentage": integer,
  "MaxConcurrentCount": integer,
  "MaxConcurrentPercentage": integer
}
```

### Potential Terraform Configuration

```hcl
resource "aws_cloudformation_stack_set_instance" "example" {
  deployment_targets {
    organizational_unit_ids = [aws_organizations_organization.example.roots[0].id]
  }

  region         = "us-east-1"
  stack_set_name = aws_cloudformation_stack_set.example.name
  failure_tolerance_count = 1
  max_concurrent_count = 10
}
```

### References

* https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack-instances.html

**Comment by tikicoder** [comment] 2021-12-07 00:58
Is this still pending information or is this waiting to be tasked?

**Comment by justinretzolk** [comment] 2021-12-16 22:48
@tikicoder at this point, I think we have the necessary information, so this is waiting to be prioritized or picked up by a community member (whichever comes first)

**Comment by pshuman-heb** [comment] 2022-02-04 15:30
I believe this is a duplicate of #18490, though I'm not sure the best way to combine them, since there are useful things in each.

**Closed** 2022-03-23 19:25 UTC
Labels: enhancement, service/cloudformation
