### ISSUE TITLE
Add support for SERVICE_MANAGED permission model to aws_cloudformation_stack_set resource

### ISSUE THREAD

**Issue by mattshep** [hashicorp/terraform-provider-aws#15626] opened 2020-10-13 18:38 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for SERVICE_MANAGED permission model on CloudFormation Stack Set. Currently there is no way to create a stack set that uses this permission model. The SELF_MANAGED permission model is implicitly used, however when using AWS Organizations with trusted access, this is likely not the desired behavior and requires the explicit creation of the execution IAM role in the target account.

### New or Affected Resource(s)

* aws_cloudformation_stack_set

### Potential Terraform Configuration

```hcl
resource "aws_cloudformation_stack_set" "example" {
  name             = "example"
  permission_model = "SERVICE_MANAGED"

  template_body = <<TEMPLATE
TEMPLATE
}
```

### References

* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacksets-orgs-enable-trusted-access.html
* https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_CreateStackSet.html
* https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_UpdateStackSet.html

**Comment by bflad** [comment] 2020-10-14 14:44
Drive-by note: I believe this is a duplicate of https://github.com/terraform-providers/terraform-provider-aws/issues/12422

**Comment by bflad** [comment] 2021-01-06 16:18
Hi folks :wave: This appears to be a duplicate of https://github.com/hashicorp/terraform-provider-aws/issues/12422, so to consolidate discussions and efforts, I'm going to close this issue in preference of the linked one. Please :+1: react and subscribe to that issue for further updates. Thanks.

**Closed by bflad** 2021-01-06 16:18 UTC
Labels: enhancement, service/cloudformation
