### ISSUE TITLE
[Bug]: MANUAL_DISCOUNT_COMPATIBILITY is still not supported in aws_cur_report_definition

### ISSUE THREAD

**Issue by sean-zou** [hashicorp/terraform-provider-aws#33490] opened 2023-09-15 20:51 UTC
### Terraform Core Version

1.3

### AWS Provider Version

0.5.17

### Affected Resource(s)

aws_cur_report_definition

### Expected Behavior

MANUAL_DISCOUNT_COMPATIBILITY should work in additional_schema_elements. 
The feature is supposed to be added in: https://github.com/hashicorp/terraform-provider-aws/issues/30813

### Actual Behavior

MANUAL_DISCOUNT_COMPATIBILITY doesn't work

### Relevant Error/Panic Output Snippet

```shell
│ Error: expected additional_schema_elements.0 to be one of ["RESOURCES" "SPLIT_COST_ALLOCATION_DATA"], got MANUAL_DISCOUNT_COMPATIBILITY
│ 
│   with aws_cur_report_definition.this,
│   on cur.tf line 21, in resource "aws_cur_report_definition" "this":
│   21:   additional_schema_elements = ["RESOURCES", "MANUAL_DISCOUNT_COMPATIBILITY"]
```

### Terraform Configuration Files

`additional_schema_elements = ["RESOURCES", "MANUAL_DISCOUNT_COMPATIBILITY"]`

### Steps to Reproduce

just run terraform with the code above.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2023-11-14 18:12
Duplicate of #33308

**Closed by justinretzolk** 2023-11-14 18:12 UTC
Labels: bug, needs-triage, service/cur
