### ISSUE TITLE
[Bug]: aws Failed to install provider

### ISSUE THREAD

**Issue by koushiqiang** [hashicorp/terraform-provider-aws#39218] opened 2024-09-09 03:36 UTC
### Terraform Core Version

v1.9.5

### AWS Provider Version

v5.66.0

### Affected Resource(s)

all kinds of aws resources

### Expected Behavior

aws ec2 execute "terraform init" successfully

### Actual Behavior

╷
│ Error: Failed to install provider
│
│ Error while installing hashicorp/aws v5.66.0: unexpected EOF

### Terraform Configuration Files

terraform {
 required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "5.66.0"
    }
  }
}

provider "aws" {
  region     = var.configuration.region
  access_key = var.access_key
  secret_key = var.secret_key
}

### Steps to Reproduce

execute "terraform init" using aws providers {source = "hashicorp/aws"  version = "5.66.0"}

### Would you like to implement a fix?

None

**Comment by stefanfreitag** [comment] 2024-09-09 17:36
Hi @koushiqiang!
Thank you for raising this issue. We would need additional details to better understand/ investigate the issue.
Could you please set the debug level to trace before running `terraform init` (see below) and attach the ouput?

```shell
export TF_LOG=TRACE
terraform init
```

**Comment by vriabets-blackbird** [comment] 2024-09-11 17:19
I'm seeing same behaviour on github actions with atlantis 
```
Initializing the backend...
Upgrading modules...
- ....

Initializing provider plugins...
- Finding latest version of hashicorp/aws...
- Installing hashicorp/aws v5.66.0...
╷
│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/aws v5.66.0: open
│ /atlantis-data/plugin-cache/registry.terraform.io/hashicorp/aws/5.66.0/linux_amd64/terraform-provider-aws_v5.66.0_x5:
│ text file busy
╵
```
But when I'm trying `terraform init` locally on mac it's working ok

**Comment by stefanfreitag** [comment] 2024-09-11 19:16
Hi @vriabets-blackbird 

not sure if your finding is same as reported in the initial  description. There it was an EOF, in your case it is "text file is busy" error message. Latter one _could_ be caused by your terraform workflow setup. 
Here are some references that may point you in the right direction

- [#32915 in terraform issue tracker](https://github.com/hashicorp/terraform/issues/32915)
- [https://github.com/hashicorp/terraform/issues/31964#issuecomment-1526300003](https://github.com/hashicorp/terraform/issues/31964#issuecomment-1526300003)
- [https://github.com/hashicorp/terraform-cdk/issues/2741](https://github.com/hashicorp/terraform-cdk/issues/2741)

Could you please attach your trace logs for the terraform run?

**Comment by vriabets-blackbird** [comment] 2024-09-12 14:28
atlantis plan

**Comment by breathingdust** [comment] 2024-09-16 16:28
Closing as It looks like @vriabets-blackbird is unblocked. Thank you for @stefanfreitag for the help!

**Closed by breathingdust** 2024-09-16 16:28 UTC
Labels: bug
