### ISSUE TITLE
[Bug]: aws_s3_bucket data sources cannot be destroyed if the bucket no longer exists

### ISSUE THREAD

**Issue by josephmidura** [hashicorp/terraform-provider-aws#39673] opened 2024-10-10 18:56 UTC
### Terraform Core Version

1.5.3

### AWS Provider Version

4.67.0

### Affected Resource(s)

data.aws_s3_bucket

### Expected Behavior

A warning is displayed and `terraform destroy` continues to remove the resource as normal.

### Actual Behavior

The aws_s3_bucket data source is unable to delete during `terraform destroy` if the associated bucket is already deleted.

### Terraform Configuration Files

```
data "aws_s3_bucket" "glue" {
  bucket = "${local.project_stage}-glue" 
}
```

### Steps to Reproduce

The `terraform destroy` was run on a project. The destroy operations stopped with an error because deletion protection was enabled on an RDS database. After deletion protection was disabled in the console for the RDS database, `terraform destroy` command was run again.

The aws_s3_bucket data source now references a bucket that no longer exists (was deleted during the initial terraform destroy) and the destroy operation failed with the following error:

`Error: Failed getting S3 bucket (bucket-name): NotFound: Not Found`

`terraform state list` does not show the bucket resource.

### Important Factoids

terraform installed via asdf

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-10-11 17:40
Hey @josephmidura 👋 Thank you for taking the time to raise this! Can you give me an idea of what `local.project_stage` looks like? I'm also curious -- are you creating a bucket using an `aws_s3_bucket` resource and then reading it using the corresponding data source in the same configuration?

Unfortunately, I don't believe there's a way to skip a data source being read during a destroy (Terraform assumes you need the most up to date information possible), so this might be a bit tricky to get around.

**Comment by josephmidura** [comment] 2024-10-11 21:10
Thanks for the reply @justinretzolk. Here is some additional code that helps explain local.project_stage:

```
variable "project" {
  description = "Project name"
  default     = "name"
}

variable "stage" {
  type        = string
  description = "Stage"
  default     = "prod"
}

locals {
  project_stage = "${var.project}-${var.stage}"
  region        = data.aws_region.current.name
  account_id    = data.aws_caller_identity.current.account_id
}
```

So the code snippet I included above could be rewritten as the following:
```
data "aws_s3_bucket" "glue" {
  bucket = "${var.project}-${var.stage}-glue" 
}
```
or
```
data "aws_s3_bucket" "glue" {
  bucket = "name-prod-glue" 
}
```

Yes, I created the **name-prod-glue** bucket using an `aws_s3_bucket` resource and the `aws_s3_bucket` data in the same configuration.

## Additional work today
Today, I created the **name-prod-glue** bucket manually, ran `terraform destroy` again, and this time all resources deleted, including **data.aws_s3_bucket**. I'm happy about that all resources were cleanly destroyed, but this workaround is not a robust solution. I'll appreciate any insight you can offer.

**Comment by justinretzolk** [comment] 2024-10-15 21:13
Hey @josephmidura 👋 Thank you for the additional insight! The only thing that still stands out to me is the use of the data source paired with the resource as well. I'm fairly confident that doing so is what caused this issue, and I'm having a hard time understanding why you would need to do so. Are you able to give me a better idea of why that's needed?

As an aside, I'd not tested using `terraform state rm` on a data source before, but apparently it works! If you find yourself in this situation again, that's probably an easier solution than needing to create the bucket again, etc.

```console
$ terraform state list
data.null_data_source.this

$ terraform state rm data.null_data_source.this
Removed data.null_data_source.this
Successfully removed 1 resource instance(s).

$ terraform state list

```

**Comment by josephmidura** [comment] 2024-10-16 18:59
Hi @justinretzolk thanks for the suggestion. When I ran `terraform state list` previously there was no data souce that showed up in the list, so I wasn't able to use the `terraform state rm` option. I am using terraform 1.5.3 and it's possible I need a later version for the functionality you mentioned.

In my use case, there is an s3 bucket used with a data lake. The goal is to register a lake formation resource (S3) to the data lake. Here are the relevant parts of the code:

```
variable "project" {
  description = "Project name"
  default     = "name"
}

variable "stage" {
  type        = string
  description = "Stage"
  default     = "prod"
}

locals {
  project_stage = "${var.project}-${var.stage}"
  region        = data.aws_region.current.name
  account_id    = data.aws_caller_identity.current.account_id
}

resource "aws_s3_bucket" "glue" {
  bucket = "${local.project_stage}-glue" 
}

data "aws_s3_bucket" "glue" {
  bucket = "${local.project_stage}-glue" 
}

resource "aws_lakeformation_resource" "glue-bucket-as-location" {
  arn = data.aws_s3_bucket.glue.arn
}
```

**Comment by justinretzolk** [comment] 2024-10-21 16:27
Thanks for the additional information here @josephmidura! Based on your sample configuration, this should be a fairly easy fix. 

Right now, there's no dependency between `aws_s3_bucket.glue` and `data.aws_s3_bucket.glue`, so there's no guarantee that creation/deletion of those two will happen in an order that will actually work. The data source could be attempted to be read before it's actually created, or after it's been deleted (as happened in your initial report).

On the other hand, the `aws_s3_bucket` resource [has an `arn` attribute](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#arn), so it's not necessary to use the related data source to do a separate lookup in order to retrieve that information. Refactoring your example configuration would look like:

```hcl
variable "project" {
  description = "Project name"
  default     = "name"
}

variable "stage" {
  type        = string
  description = "Stage"
  default     = "prod"
}

locals {
  project_stage = "${var.project}-${var.stage}"
  region        = data.aws_region.current.name
  account_id    = data.aws_caller_identity.current.account_id
}

resource "aws_s3_bucket" "glue" {
  bucket = "${local.project_stage}-glue" 
}

resource "aws_lakeformation_resource" "glue-bucket-as-location" {
  arn = aws_s3_bucket.glue.arn
}
```

**Comment by justinretzolk** [comment] 2024-10-31 15:02
Glad to hear that helped out @josephmidura! Since it seems that this came down to a configuration issue rather than a bug with the provider itself, I'm going to close this issue out. If you experience any other unexpected behavior, please do let us know!

**Closed by justinretzolk** 2024-10-31 15:02 UTC
Labels: bug, service/s3, needs-triage
