### ISSUE TITLE
aws_backup_plan Rule Lifecycle Should Be Optional in Terraform 11

### ISSUE THREAD

**Issue by exavier-slf** [hashicorp/terraform-provider-aws#14063] opened 2020-07-06 18:37 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.14
+ provider.archive v1.3.0
+ provider.aws v2.63.0
+ provider.null v2.1.2
+ provider.template v2.1.2
```

### Affected Resource(s)

* aws_backup_plan

### Terraform Configuration Files

```hcl
resource "aws_backup_plan" "aws_backup_plan" {
  name = "tf_example_backup_plan"
  rule {
    rule_name         = "resource_nackup"
    target_vault_name = "${aws_backup_vault.backup_vault.name}"
    schedule          = "cron(0 12 * * ? *)"
    copy_action = {
      destination_vault_arn = "arn:aws:backup:us-east-1:ACCOUNT_NUMBER:backup-vault:backup-cross-region"
      lifecycle           = {
        cold_storage_after = 0 
        delete_after = 0
      }
    }
  }
}

```

  ## Or the below code also fails

```hcl
resource "aws_backup_plan" "aws_backup_plan" {
  name = "tf_example_backup_plan"
  rule {
    rule_name         = "resource_nackup"
    target_vault_name = "${aws_backup_vault.backup_vault.name}"
    schedule          = "cron(0 12 * * ? *)"
    copy_action = {
      destination_vault_arn = "arn:aws:backup:us-east-1:ACCOUNT_NUMBER:backup-vault:backup-cross-region"
    }
  }
}

```

### Debug Output

```
1 error occurred:
        * module.main.aws_backup_plan.aws_backup_plan: 1 error occurred:
        * aws_backup_plan.aws_backup_plan: error creating Backup Plan: InvalidParameterValueException: Error in rule resource_nackup : Invalid lifecycle. Both MoveToColdStorageAfterDays and DeleteAfterDays are missing.
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "997f46aa-ade5-4358-85bb-f99bcfcd85cf"
  },
  Code_: "ERROR_3015",
  Context: "[\"resource_nackup\",\"Invalid lifecycle. Both MoveToColdStorageAfterDays and DeleteAfterDays are missing.\"]",
  Message_: "Error in rule resource_nackup : Invalid lifecycle. Both MoveToColdStorageAfterDays and DeleteAfterDays are missing."
}

```
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by agiwalpooja20** [comment] 2020-07-29 11:09
Facing exactly same issue

**Comment by DrFaust92** [comment] 2020-11-10 09:35
Duplicate of #13165

**Closed by DrFaust92** 2020-11-10 09:35 UTC
Labels: bug, service/backup
