### ISSUE TITLE
[Bug]: failed to create ecr repo 

### ISSUE THREAD

**Issue by adolya** [hashicorp/terraform-provider-aws#30044] opened 2023-03-15 22:21 UTC
### Terraform Core Version

1.4.0

### AWS Provider Version

4.56.0

### Affected Resource(s)

* aws_ecr

### Expected Behavior

The resource to be created, and traced by Terraform

### Actual Behavior

The resource is created, but crashed to be added to state

### Relevant Error/Panic Output Snippet

```shell
panic: interface conversion: interface {} is nil, not *ecr.Repository

goroutine 44 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/ecr.resourceRepositoryRead({0xe5376c0?, 0xc003cc33b0}, 0xc003359b80, {0xd091680?, 0xc00043d400})
        github.com/hashicorp/terraform-provider-aws/internal/service/ecr/repository.go:185 +0x12cc
github.com/hashicorp/terraform-provider-aws/internal/service/ecr.resourceRepositoryCreate({0xe5376c0, 0xc003cc33b0}, 0xc003359b80, {0xd091680?, 0xc00043d400})
        github.com/hashicorp/terraform-provider-aws/internal/service/ecr/repository.go:166 +0xe3e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xe5376c0?, {0xe5376c0?, 0xc003cc33b0?}, 0xd?, {0xd091680?, 0xc00043d400?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:702 +0x84
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc001105500, {0xe5376c0, 0xc003cc33b0}, 0xc0037eda00, 0xc003359a00, {0xd091680, 0xc00043d400})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000281a70, {0xe5376c0?, 0xc003cc3290?}, 0xc001fa6190)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.muxServer.ApplyResourceChange({0xc003250b10, 0xc003250b70, {0xc004b07160, 0x2, 0x2}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...)
        github.com/hashicorp/terraform-plugin-mux@v0.9.0/tf5muxserver/mux_server_ApplyResourceChange.go:27 +0x102
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0023bd900, {0xe5376c0?, 0xc003cbbb60?}, 0xc003e11030)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xcda6b00?, 0xc0023bd900}, {0xe5376c0, 0xc003cbbb60}, 0xc003e10fc0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00464e3c0, {0xe546640, 0xc0007ae4e0}, 0xc003eb6ea0, 0xc004973fb0, 0x14c30480, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc00464e3c0, {0xe546640, 0xc0007ae4e0}, 0xc003eb6ea0, 0x0)
        google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.53.0/server.go:963 +0x28a

Error: The terraform-provider-aws_v4.56.0_x5 plugin crashed!
```

### Terraform Configuration Files

terraform apply
confirm apply

### Steps to Reproduce

```terraform
resource "aws_ecr_repository" "cact" {
  name                 = "cact"
  image_tag_mutability = "MUTABLE"

  image_scanning_configuration {
    scan_on_push = true
  }
}
```

### Would you like to implement a fix?

None

**Comment by adolya** [comment] 2023-03-15 22:43
After downgrading to version 4.22 I was able to see that actual reason is lack of permissions to etc:DescribeRepositories and some other

**Comment by justinretzolk** [comment] 2023-03-17 20:37
Hey @adolya 👋 Thank you for taking the time to raise this and to come back with the root cause that you found. Given that information, we'll close this issue out.

**Closed by justinretzolk** 2023-03-17 20:37 UTC
Labels: bug, crash, service/ecr, needs-triage

**Comment by adolya** [comment] 2023-03-17 21:00
Was it completed? Or the valid error should of appear? As it was in previous version?
