### ISSUE TITLE
[Bug]: Importing Resource into Module Creates Resource Instead of Importing

### ISSUE THREAD

**Issue by dke-a** [hashicorp/terraform-provider-aws#34379] opened 2023-11-13 17:04 UTC
### Terraform Core Version

1.5.2

### AWS Provider Version

5.24.0

### Affected Resource(s)

aws_s3_bucket

### Expected Behavior

Attempted to import an existing S3 bucket into an s3_bucket modules (from the registry)and expected that the S3 bucket would successfully be imported into Terraform management.

### Actual Behavior

Applying `terraform plan` shows that it is trying to create the resource instead of importing it.

### Relevant Error/Panic Output Snippet

```shell
module.s3_bucket.data.aws_caller_identity.current: Reading...
module.s3_bucket.data.aws_region.current: Reading...
module.s3_bucket.data.aws_canonical_user_id.this[0]: Reading...
module.s3_bucket.data.aws_partition.current: Reading...
module.s3_bucket.data.aws_partition.current: Read complete after 0s [id=aws]
module.s3_bucket.data.aws_region.current: Read complete after 0s [id=us-east-1]
module.s3_bucket.data.aws_caller_identity.current: Read complete after 0s [id=408810908626]
module.s3_bucket.data.aws_canonical_user_id.this[0]: Read complete after 0s [id=075a95cf921eea7668bf9224ea784cb6f326d0dcd5945d0a60cee1f19df339b5]

Terraform used the selected providers to generate the following execution plan.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.s3_bucket.aws_s3_bucket.this[0] will be created
  + resource "aws_s3_bucket" "this" {
      + acceleration_status         = (known after apply)
      + acl                         = (known after apply)
      + arn                         = (known after apply)
      + bucket                      = "deployed_bucket"
      + bucket_domain_name          = (known after apply)
      + bucket_prefix               = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = false
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + object_lock_enabled         = false
      + policy                      = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + tags_all                    = (known after apply)
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)
    }

  # module.s3_bucket.aws_s3_bucket_acl.this[0] will be created
  + resource "aws_s3_bucket_acl" "this" {
      + acl    = "private"
      + bucket = (known after apply)
      + id     = (known after apply)
    }

  # module.s3_bucket.aws_s3_bucket_public_access_block.this[0] will be created
  + resource "aws_s3_bucket_public_access_block" "this" {
      + block_public_acls       = true
      + block_public_policy     = true
      + bucket                  = (known after apply)
      + id                      = (known after apply)
      + ignore_public_acls      = true
      + restrict_public_buckets = true
    }

  # module.s3_bucket.aws_s3_bucket_versioning.this[0] will be created
  + resource "aws_s3_bucket_versioning" "this" {
      + bucket = (known after apply)
      + id     = (known after apply)

      + versioning_configuration {
          + mfa_delete = (known after apply)
          + status     = "Suspended"
        }
    }

Plan: 4 to add, 0 to change, 0 to destroy.

Changes to Outputs:
 + s3_bucket_arn = (known after apply)
```

### Terraform Configuration Files

```terraform
import {
    to = module.s3_bucket.aws_s3_bucket.this
    id = "deployed_bucket"
}

module "s3_bucket" {
  source = "terraform-aws-modules/s3-bucket/aws"
  bucket = "deployed_bucket"
  acl    = "private"

  versioning = {
    enabled = false
  }
}
```

### Steps to Reproduce

Simply run `terraform init` and `terraform plan` using the code provided.

### Important Factoids

Running the code while specifying the index of [0] as in the following would successfully import the resource.

```terraform
import {
    to = module.s3_bucket.aws_s3_bucket.this[0]
    id = "deployed_bucket"
}
```

Should there be an error to be raised when importing into a module without specifying the index of [0]? 

### Would you like to implement a fix?

None

**Comment by acwwat** [comment] 2023-11-13 18:14
This question should probably be addressed to the [terraform-aws-s3-bucket](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket) project. Anyway, I believe this is by design in the module. If you look at [main.tf](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/blob/7263d096e3386493dc5113ad61ad0670e6c99028/main.tf#L25-L34
) in the module, the `aws_s3_bucket` resource has a `count`, so the actual resource reference should be `aws_s3_bucket.this[0]` if it were created/managed by the module.

As a side note, I am not sure what impact you might have for importing just one (being the bucket) of the [many resources that the module manages](https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/tree/7263d096e3386493dc5113ad61ad0670e6c99028#resources). There would be a lot of missing info from the module that might cause more downstream configuration differences. You would either need to import all those, or rethink whether you should import/manage resources individually.

Hope this helps.

**Comment by justinretzolk** [comment] 2023-11-14 20:26
Hey @dke-a 👋 Thank you for taking the time to file this issue, and I'm glad to see the additional discussion going on around it! The issue here is indeed the missing index when importing the resource, as that imports the resource to the state incorrectly. Since this is more of a Terraform Core behavior, I'd recommend opening an issue in [that repository](https://github.com/hashicorp/terraform) for any follow up questions -- they'll have the best insight into this 🙂.

Since this is related to Terraform Core rather than the AWS Provider, closing this issue out.

**Closed by justinretzolk** 2023-11-14 20:26 UTC
Labels: bug, service/s3, needs-triage
