### ISSUE TITLE
Add Tags to Resource: aws_acmpca_certificate

### ISSUE THREAD

**Issue by wr-nathan** [hashicorp/terraform-provider-aws#26782] opened 2022-09-13 10:39 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, there is no way to add tags to the resource; aws_acmpca_certificate via terrraform. 
Please can this be added as you can tag private certificates when creating them via the API, CLI and AWS Console. 

E.g:
https://docs.aws.amazon.com/cli/latest/reference/acm/request-certificate.html

### New or Affected Resource(s)

* aws_acmpca_certificate

* #0000

**Comment by justinretzolk** [comment] 2022-09-13 15:27
Hey @wr-nathan 👋 Thank you for taking the time to raise this! It looks like you linked to the `acm` documentation for `request-certificate`, rather than the [`acm-pca` documentation](https://docs.aws.amazon.com/cli/latest/reference/acm-pca/issue-certificate.html) for `issue-certificate`. Unfortunately, the latter does not appear to support tagging. I confirmed this by checking the appropriate [Go SDK type (`IssueCertificateInput`)](https://docs.aws.amazon.com/sdk-for-go/api/service/acmpca/#IssueCertificateInput).

Since this is limited by the underlying SDK/API, I'll close this issue for now. If tagging support is added at a later date, we'll be more than happy to take another look. If you feel I've done this in error, please do let me know.

**Closed by justinretzolk** 2022-09-13 15:27 UTC
Labels: enhancement, service/acmpca, needs-triage
