### ISSUE TITLE
Error: The terraform-provider-aws_v3.60.0_x5 plugin crashed! Jenkins job failed.

### ISSUE THREAD

**Issue by Gauravlwplabs** [hashicorp/terraform-provider-aws#21079] opened 2021-09-29 03:35 UTC
Error: The terraform-provider-aws_v3.60.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

# This file is maintained automatically by "terraform init".
# Manual edits may be lost in future updates.

provider "registry.terraform.io/hashicorp/aws" {
  version     = "3.60.0"
  constraints = "~> 3.0, 3.60.0"
  hashes = [
    "h1:prm+ifU5Mx229LA9yhhzHisSTEUrY/I9m+IzDp6wN2w=",
    "zh:01323eedb8f006c8f9fffdfc23b449625b1446c1e43b8454e4a40a7461193661",
    "zh:03513ffdae205832be480b30d332b47a573e48623390e8f9f833141c8ceccb6a",
    "zh:47611a8b361ced9a3b58b9868be2004677cf4ea0d04cfb5f54c6ae95e997e7c7",
    "zh:9a7e80c2a2ed0f2e59b05e27374daaafd64785161546ed40f4db11048fbc78a7",
    "zh:9e809746c4fdaa4214700e81a67b35f02afc1f2873591b0360c473cfd7193877",
    "zh:a009d48e4ebcf78e24af9299c6a8664e0375411b4f16d5d0d7c7454b12052c10",
    "zh:adc910f48f5ddc402e7653e70429d150d61bee5190aba7495575303aba6ca6c8",
    "zh:b702e219532bc09be58f8a30cb3239626ffc9bc0e42b44497b0644f9ecc657b5",
    "zh:bc50d787593e714acb54d65e8df026490a968e54d2184496efda7ba07c211836",
    "zh:bd74e3b1c815d5a9c710cb5c55f2d5f6742471a23e63f924fd3a6493f384cd43",
    "zh:fa7eb23bcf4c01f93d74c509c0e9b039148f43424c3b4ce64619af17ee12265c",
  ]
}

**Comment by henderjm** [comment] 2021-09-29 10:16
We are experiencing the same issue today which I think is caused by the VPC module.

```
Stack trace from the terraform-provider-aws_v3.60.0_x5 plugin:

panic: interface conversion: interface {} is nil, not *aws.AWSClient

goroutine 88 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsSubnetRead(0x14001a77300, 0x0, 0x0, 0x108ec8e38, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_subnet.go:234 +0xd2c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x14000ec1ce0, 0x1092cf128, 0x14001a82c40, 0x14001a77300, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:335 +0x170
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x14000ec1ce0, 0x1092cf128, 0x14001a82c40, 0x14001a783f0, 0x0, 0x0, 0x14000306010, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:624 +0x160
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x1400000c4f8, 0x1092cf128, 0x14001a82c40, 0x14001a82c80, 0x14001a82c40, 0x1024ed5dc, 0x1089b5ae0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/grpc_provider.go:575 +0x380
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0x1400237e560, 0x1092cf1d0, 0x14001a82c40, 0x14001a6d740, 0x1400237e560, 0x10244d4d0, 0x108a32740)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0xe4
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x108ca5760, 0x1400237e560, 0x1092cf1d0, 0x14001d00210, 0x14001a6d6e0, 0x0, 0x1092cf1d0, 0x14001d00210, 0x14001ae8580, 0x294)
        /opt/teamcity-agent/w╷
│ Error: Plugin did not respond
│
│   with module.vpc.aws_nat_gateway.this[0],
│   on .terraform/modules/vpc/main.tf line 1091, in resource "aws_nat_gateway" "this":
│ 1091: resource "aws_nat_gateway" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain more details.
╵
ork/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x1c8
google.golang.org/grpc.(*Server).processUnaryRPC(0x14001600a80, 0x1092f1ff8, 0x140015c9380, 0x140007e6900, 0x14000af7470, 0x10cc427b0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x3e8
google.golang.org/grpc.(*Server).handleStream(0x14001600a80, 0x1092f1ff8, 0x140015c9380, 0x140007e6900, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xa50
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x1400142ea10, 0x14001600a80, 0x1092f1ff8, 0x140015c9380, 0x140007e6900)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1f8

Error: The terraform-provider-aws_v3.60.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

**Comment by ewbankkit** [comment] 2021-09-29 11:46
Similar:

* #21019
* #20941
* #20878
* #20461
* #20438
* #20131
* #20015
* #19807
* #19788
* #19740
* #19601

**Comment by JeremyPDC** [comment] 2021-12-29 17:27
> Hi @Gauravlwplabs 👋 Terraform `v1.0.9` was released yesterday which [includes a fix](https://github.com/hashicorp/terraform/blob/v1.0.9/CHANGELOG.md#109-october-13-2021) that should correct this. Can you test again with this newer version to verify that you're no longer experience this issue?

Similar problem updated from 1.0.8 to 1.0.9 and this did not help. Just in case anyone comes across this in the future.

**Comment by aragavan1** [comment] 2022-01-04 10:11
Moving to v1.0.9 solved the issue.

**Closed** 2022-01-04 11:55 UTC
Labels: bug, crash, service/ec2
