### ISSUE TITLE
organisations_policy is missing the content when BACKUP_POLICY

### ISSUE THREAD

**Issue by anton-stamenov-SWO** [hashicorp/terraform-provider-aws#26446] opened 2022-08-23 09:33 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.2.7 on darwin_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v4.23.0
+ provider registry.terraform.io/hashicorp/external v2.2.2

### Affected Resource(s)

* aws_organizations_policy

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

resource "aws_organizations_policy" "policy" {
  name = "Landing Zone AWS Backups"

  content = <<CONTENT
{
  "plans": {
    "HLZ-Backup": {
      "regions": {
        "@@assign": [
          "eu-west-1"
        ]
      },
      "rules": {
        "Backup-Rule": {
          "schedule_expression": {
            "@@assign": "cron(0 5 ? * * *)"
          },
          "start_backup_window_minutes": {
            "@@assign": "480"
          },
          "complete_backup_window_minutes": {
            "@@assign": "10080"
          },
          "lifecycle": {
            "delete_after_days": {
              "@@assign": "35"
            }
          },
          "target_backup_vault_name": {
            "@@assign": "Default"
          },
          "enable_continuous_backup": {
            "@@assign": true
          }
        }
      },
      "selections": {
        "tags": {
          "Resources": {
            "iam_role_arn": {
              "@@assign": "arn:aws:iam::$account:role/AWSBackupRole"
            },
            "tag_key": {
              "@@assign": "Backup"
            },
            "tag_value": {
              "@@assign": [
                "TRUE"
              ]
            }
          }
        }
      }
    }
  }
}
CONTENT

  type = "BACKUP_POLICY"
}
```

### Debug Output

https://gist.github.com/anton-stamenov-SWO/3bf136b204a636c57a337842fdc8a8c0

### Expected Behavior

In the plan the "content" attribute should be present.

### Actual Behavior

In the plan the "content" attribute is missing and policy could not be applied later on.

Note: this is working as expected with provider version v4.22.0. It is not working with >=v4.23.0.

Note: I've noticed that if I add "Version": "2012-10-17" to the policy content, the "plan" works just fine, but doing so, the AWS API rejects the policy.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### References

* #0000

**Comment by justinretzolk** [comment] 2022-08-23 17:15
Hey @anton-stamenov-SWO 👋 Thanks for taking the time to submit this issue. It looks like this is a duplicate of #25977. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #25977.

**Closed by justinretzolk** 2022-08-23 17:15 UTC
Labels: service/organizations, needs-triage
