### ISSUE TITLE
Inconsistency in AWS Terraform provider with aws_lambda_function

### ISSUE THREAD

**Issue by SarahRiley** [hashicorp/terraform-provider-aws#11787] opened 2020-01-28 19:11 UTC
When using a data resource for aws_lambda_function, the qualified_arn comes back as:

```
arn:aws:lambda:us-east-1:1234:function:foo:$LATEST
```

But the non-data resource has a qualified_arn of:

```
arn:aws:lambda:us-east-1:1234:function:foo:5
```

Why is this different?

This breaks for us when using the data resource for a lambda with a cloudfront distribution, as it requires the qualified_arn to end with a number:

Error: error creating CloudFront Distribution: InvalidLambdaFunctionAssociation: The function ARN must reference a specific function version. (The ARN must end with the version number.)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.12.19

### Affected Resource(s)

 * aws_lambda_function
 * data.aws_lambda_function

### Expected Behavior

Data resource for aws_lambda_function should have returned `arn:aws:lambda:us-east-1:1234:function:foo:5`, like the non-data resource.

### Actual Behavior

Data resource for aws_lambda_function returned `arn:aws:lambda:us-east-1:1234:function:foo:$LATEST`

**Comment by justinretzolk** [comment] 2021-11-18 21:42
Hey @SarahRiley 👋 Thank you for taking the time to file this issue. In reviewing the documentation, it seems as though the behavior _may_ have changed, but I'm not not entirely sure which version of the AWS provider you were previously using, so it's difficult for me to say with certainty. With that in mind, given that there's been a number of AWS provider releases since you initially filed this, I wanted to follow up and see if you're still experiencing this behavior.

**Comment by Discipe** [comment] 2021-12-09 18:44
This is still reproducable in Terraform 1.0.11 and aws provider 3.68.0

**Comment by breathingdust** [comment] 2022-02-03 14:19
Hi all 👋  Just letting you know that this is issue is featured on this quarters [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md). If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!

**Closed** 2023-01-19 13:17 UTC
Labels: bug, service/lambda
