### ISSUE TITLE
[Enhancement]: Export roleArn in aws_prometheus_scraper resource

### ISSUE THREAD

**Issue by RAMathews** [hashicorp/terraform-provider-aws#35365] opened 2024-01-18 12:24 UTC
### Description

When we create a 'Amazon Managed Service for Prometheus collector' it creates a scraper and there is a roleArn associated with it. This roleArn is needed to configure the Amazon EKS to allow the scraper to access metrics. 

https://docs.aws.amazon.com/prometheus/latest/userguide/AMP-collector-how-to.html#AMP-collector-eks-setup

Is it possible to add the ' roleArn' as an output for 'aws_prometheus_scraper' resource? 

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/prometheus_scraper

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-01-18 17:31
Hey @RAMathews 👋 Thanks for taking the time to submit this issue. It looks like this is a duplicate of #35322. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of that one.

**Comment by justinretzolk** [comment] 2024-01-18 17:31
Duplicate of #35322

**Closed by justinretzolk** 2024-01-18 17:31 UTC
Labels: enhancement, needs-triage
