### ISSUE TITLE
BadRequestException: VPCEndpoints can only be specified with PRIVATE apis. During api-gateway types update from PRIVATE to EDGE/REGIONAL

### ISSUE THREAD

**Issue by stsefanovich** [hashicorp/terraform-provider-aws#14269] opened 2020-07-21 09:34 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform: v0.12.24
AWS provider: 2.64.0
AWS provider: 2.70.0 - also tested

### Affected Resource(s)

aws_api_gateway_rest_api

### Terraform Configuration Files

Here is a module for api_gateway_rest_api creation:
```hcl
resource "aws_api_gateway_rest_api" "this" {
  name = local.resource_name
  description = var.description

  body = local.is_swagger ? var.swagger_body : null

  policy = var.access_type == "PRIVATE" ? data.aws_iam_policy_document.this[0].json : null
  endpoint_configuration {
    types = [var.access_type]
    vpc_endpoint_ids = var.access_type == "PRIVATE" ? [module.datasources.vpc.endpoints.apigw] : null
  }
}
```

### Expected Behavior

Api gateway with types PRIVATE could be updated to EDGE/REGIONAL

### Actual Behavior

During update api-gateway with types PRIVATE to api-gateway with types EDGE/REGIONAL apply failed 

### Steps to Reproduce

Create api-gateway with types PRIVATE. Change types from PRIVATE to EDGE/REGIONAL.

1. `terraform plan`

Terraform will perform the following actions:
```hcl
    # aws_api_gateway_rest_api.this will be updated in-place
  ~ resource "aws_api_gateway_rest_api" "this" {
        api_key_source           = "HEADER"
        arn                      = "arn:aws:apigateway:us-east-1::/restapis/***"
        binary_media_types       = []
        created_date             = "2020-07-21T08:54:54Z"
        execution_arn            = "arn:aws:execute-api:us-east-1:***:***"
        id                       = "***"
        minimum_compression_size = -1
        name                     = "***"
      - policy                   = jsonencode(
            {
              - Statement = [
                  - {
                      - Action    = "execute-api:Invoke"
                      - Condition = {
                          - StringEquals = {
                              - aws:SourceVpce = "vpce-***"
                            }
                        }
                      - Effect    = "Allow"
                      - Principal = "*"
                      - Resource  = "arn:aws:apigateway:us-east-1:***:apis/*"
                      - Sid       = ""
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> null
        root_resource_id         = "***"
        tags                     = { *** }

      ~ endpoint_configuration {
          ~ types            = [
              - "PRIVATE",
              + "EDGE",
            ]
          ~ vpc_endpoint_ids = [
              - "vpce-***",
            ]
        }
    }
```
Plan: 0 to add, 1 to change, 0 to destroy.

2. `terraform apply`

Error: BadRequestException: VPCEndpoints can only be specified with PRIVATE apis.

**Comment by DrFaust92** [comment] 2020-07-24 22:53
not a tf issue, vpc endpoints are supported only for Private endpoints.

**Comment by DrFaust92** [comment] 2020-07-28 21:12
Hey @stsefanovich, im able to recreate the issue. i've tried to play around with it and maybe introduce retries but it seems to br an issue on API Gateway side where you can remove the vpc endpoint and  change the type in the same request.

ill take a look if its an issue or order of actions and this can be worked around. otherwise it might be split this logic to update it in parts.

**Comment by DrFaust92** [comment] 2020-07-28 21:37
Update, i've played around with the order and either way this does not seem like a valid action

`Error: BadRequestException: Cannot update endpoint from PRIVATE to EDGE`

so its not a bug apparently.

**Comment by saedalavinia** [comment] 2020-11-18 14:33
I ran into the same issue. But checking [AWS Documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-api-migration.html), it says: 

- You cannot change a private API into an edge-optimized API.

**Comment by DrFaust92** [comment] 2020-11-18 19:30
Closing this based on @saedalavinia. Thanks!

**Closed by DrFaust92** 2020-11-18 19:30 UTC
Labels: service/apigateway
