### ISSUE TITLE
aws_organizations_policy not working properly in newest release

### ISSUE THREAD

**Issue by erikrin** [hashicorp/terraform-provider-aws#26129] opened 2022-08-04 14:18 UTC
We want to update our AWS Organisations Tag Policy but terraform is not evaluating the content block with the provided policy. 
It was working until version v4.22.0. See terraform output below.

### Affected Resource(s)

* aws_organizations_policy

### Code to reproduce

```hcl
resource "aws_organizations_policy" "test_policy" {
  name = "cb-test-policy"
  type = "TAG_POLICY"
  content = jsonencode({
    "tags" = {
      "key" = {
        "tag_key" = {
          "@@assign" = "key"
        },
        "tag_value" = {
          "@@assign" = "value"
        }
        "enforced_for" = {
          "@@assign" = "ec2:*"
        }
      }
    }
  })
}
```

### AWS Provider v4.22.0 

```zsh
terraform -v
Terraform v1.2.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.22.0
```

```zsh


  # aws_organizations_policy.test_policy will be created
  + resource "aws_organizations_policy" "test_policy" {
      + arn      = (known after apply)
      + content  = jsonencode(
            {
              + tags = {
                  + key = {
                      + enforced_for = {
                          + "@@assign" = "ec2:*"
                        }
                      + tag_key      = {
                          + "@@assign" = "key"
                        }
                      + tag_value    = {
                          + "@@assign" = "value"
                        }
                    }
                }
            }
        )
      + id       = (known after apply)
      + name     = "cb-test-policy"
      + tags_all = {
          + "account"     = "---"
          + "accountid"   = "---"
          + "environment" = "prod"
          + "owner"       = "devops"
          + "terraform"   = "true"
        }
      + type     = "TAG_POLICY"
    }
```

### AWS Provider v4.24.0

```zsh
terraform version
Terraform v1.2.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.24.0
```

```zsh
  # aws_organizations_policy.test_policy will be created
  + resource "aws_organizations_policy" "test_policy" {
      + arn      = (known after apply)
      + id       = (known after apply)
      + name     = "cb-test-policy"
      + tags_all = {
          + "account"     = "---"
          + "accountid"   = "---"
          + "environment" = "prod"
          + "owner"       = "devops"
          + "terraform"   = "true"
        }
      + type     = "TAG_POLICY"
    }
```

### Links

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/organizations_policy

**Comment by justinretzolk** [comment] 2022-08-22 17:49
Hey @erikrin 👋 Thanks for taking the time to submit this issue. It looks like this is a duplicate of #25977. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #25977.

**Closed by justinretzolk** 2022-08-22 17:49 UTC
Labels: service/organizations, needs-triage
