### ISSUE TITLE
aws_elasticache_cluster Malformed version: 6.x

### ISSUE THREAD

**Issue by lijok** [hashicorp/terraform-provider-aws#18015] opened 2021-03-10 10:40 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.14.6

### Affected Resource(s)

* aws_elasticache_cluster

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_elasticache_cluster" "this" {
  provider = aws.region

  cluster_id               = var.name
  engine                   = "redis"
  engine_version           = "6.x"
  maintenance_window       = "sun:00:00-sun:01:00"
  node_type                = "cache.t3.micro"
  num_cache_nodes          = 1
  parameter_group_name     = aws_elasticache_parameter_group.this.name
  port                     = 6379
  subnet_group_name        = aws_elasticache_subnet_group.this.name
  security_group_ids       = var.db_security_group_ids
  apply_immediately        = var.apply_immediately
  snapshot_window          = "05:00-06:00"
  snapshot_retention_limit = 0 # turned off
  tags                     = local.tags
}

resource "aws_elasticache_parameter_group" "this" {
  provider = aws.region

  name        = var.name
  description = local.description
  family      = "redis6.x"
}

resource "aws_elasticache_subnet_group" "this" {
  provider = aws.region

  name        = var.name
  description = local.description
  subnet_ids  = var.db_subnet_ids
}
```

### Expected Behavior

Nothing

### Actual Behavior

After deploying the redis instance with `terraform apply` succesfully,, re-running `terraform apply` results in:
```hcl
Error: Malformed version: 6.x

  on ../../../modules/aws/services/service/redis.tf line 1, in resource "aws_elasticache_cluster" "this":
   1: resource "aws_elasticache_cluster" "this" {
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

### References

* #0000

**Comment by lijok** [comment] 2021-03-10 10:49
Changing engine_version to 6.0.5 fixed this
It deployed just fine with 6.x however
Same for parameter group, it deployed fine with 6.x and has no complaints

**Comment by lijok** [comment] 2021-03-10 22:44
And looks like  you can't deploy it with engine_version set to 6.0.5
```hcl
Error: error creating Elasticache Cache Cluster: InvalidParameterValue: Specific version selection is not allowed for '6.0.5', please use '6.x'
	status code: 400, request id: 6a645304-14aa-4dbe-b675-d39bc0c1585f
```

So, the first deploy can only happen with version set to "6.x"
The subsequent deploys can only happen with version set to "6.0.5"

**Comment by gdavison** [comment] 2021-03-26 23:28
Thanks for reporting this, @lijok. It looks like this is a duplicate of #15625, so I'm going to close the issue. If this isn't the same problem, or this adds additional details, please open a new issue referencing #15625 and clarifying the differences.

**Closed by gdavison** 2021-03-26 23:28 UTC
Labels: service/elasticache
