### ISSUE TITLE
DOCUMENTDB : restore point in time parameter is needed

### ISSUE THREAD

**Issue by creazer-I** [hashicorp/terraform-provider-aws#35106] opened 2024-01-02 12:24 UTC
### Description

Since the cloning have been there in the aws document db we may need to have that included in terraform as well.

such as :

```terraform
resource "aws_docdb_cluster" "default" {
# other configs
  restore_to_point_in_time {
    source_cluster_identifier  = "example"
    restore_type               = "copy-on-write"
    use_latest_restorable_time = true
  }
}
```

### Potential Terraform Configuration

```terraform
resource "aws_docdb_cluster" "default" {
# other configs
  restore_to_point_in_time {
    source_cluster_identifier  = "example"
    restore_type               = "copy-on-write"
    use_latest_restorable_time = true
  }
}
```

### References

https://docs.aws.amazon.com/documentdb/latest/developerguide/db-cluster-cloning.html

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-01-11 17:39
Duplicate of #25914

**Closed by justinretzolk** 2024-01-11 17:39 UTC
Labels: enhancement, service/docdb, needs-triage
