### ISSUE TITLE
[Bug]: aws_organizations_organization does not honor org delegated administrator accounts

### ISSUE THREAD

**Issue by dbadrak** [hashicorp/terraform-provider-aws#31265] opened 2023-05-08 14:31 UTC
### Terraform Core Version

1.4.6

### AWS Provider Version

4.66.1

### Affected Resource(s)

* data.aws_organizations_organization

### Expected Behavior

When called in an account that has been configured as a delegated adminsitrator to the management account, I am expecting to get the same results as when called from the management account. The fields expected to be populated are empty lists or null sets, like accounts and roots.  I want to use the data source to perform mappings to share resources with RAM.

### Actual Behavior

The resultant object is missing vital information which is present in the org management account data resources.

### Relevant Error/Panic Output Snippet

Here is the result of the (redcated) data object in a delegated account:

```shell
> data.aws_organizations_organization.org
{
  "accounts" = tolist(null) /* of object */
  "arn" = "arn:aws-us-gov:organizations::123123123123:organization/o-abcde01234"
  "aws_service_access_principals" = toset([])
  "enabled_policy_types" = toset([])
  "feature_set" = "ALL"
  "id" = "o-abcde01234"
  "master_account_arn" = "arn:aws-us-gov:organizations::123123123123:account/o-abcde01234/123123123123"
  "master_account_email" = "email-address@domain.com"
  "master_account_id" = "123123123123"
  "non_master_accounts" = tolist(null) /* of object */
  "roots" = tolist(null) /* of object */
}
```

However, when looking at this data resource in the management account accounts, non_master_accounts, enabled_policy_types, aws_service_access_principals are all populated with the data as expected.

### Terraform Configuration Files

```terraform
data "aws_organizations_organization" "org" {}

output "org" {
  value = data.aws_organizations_organization.org
}
```

### Steps to Reproduce

1. delegate organization adminstrator to another account (with organizations List* and Describe*, as in the [example in the docs](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_delegate_policies_example_view_accts_orgs.html).
2. in the org management account, create a file with the data resource and output as listed above
3. in the delegated account, create a file with the data resource and output as listed above
4. examine the difference in output from each of the accounts
5. note that in the delegated admin account, this does not return the data as expected, but it does show up if you look usign the AWS CLI: aws organizations list-roots or list-accounts

### Important Factoids

It appears the problem is here:

https://github.com/hashicorp/terraform-provider-aws/blob/1afac8d8ea5a20e00859691f14636e9aa0bc15be/internal/service/organizations/organization_data_source.go#L164

That only returns the populated fields if the org management account returned by describe-organizations is the same as the caller.   This does not appear to support the delegated administration from AWS organizations.

Since you can delegate specific actions to other accounts [listed here](https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsorganizations.html) it seems that this code should try to return each of the fields and only return empty or null if no data come back or it returns an access failure.

### References

https://docs.aws.amazon.com/organizations/latest/userguide/orgs_delegate_policies.html

### Would you like to implement a fix?

None

**Comment by claer** [comment] 2023-06-13 11:35
This is a duplicate of https://github.com/hashicorp/terraform-provider-aws/issues/18590

**Closed** 2023-06-20 12:36 UTC
Labels: bug, service/organizations
