### ISSUE TITLE
[Bug]: aws_db_parameter_group ApplyMethod changes aren't applied

### ISSUE THREAD

**Issue by naruse666** [hashicorp/terraform-provider-aws#36419] opened 2024-03-16 00:09 UTC
### Terraform Core Version

1.7.5

### AWS Provider Version

5.41.0

### Affected Resource(s)

aws_db_parameter_group, aws_rds_cluster_parameter_group

### Expected Behavior

Don't generate differences.

### Actual Behavior

Continue to report differences even after apply.

### Terraform Configuration Files

```tf
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
       version = "= 5.41.0"
    }
  }
}

resource "aws_db_parameter_group" "default" {
  name   = "rds-pg"
  family = "postgres16"

  parameter {
    name  = "log_statement"
    value = "mod"
    apply_method = "immediate"
  }
}
```

### Steps to Reproduce

1. Apply the above terraform file.
2. Change `apply_method` to `pending-reboot` as follows.
```tf
  parameter {
    name  = "log_statement"
    value = "mod"
    apply_method = "pending-reboot"
  }
```
3. Apply the changes and confirm success.
```sh
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```
4. Running terraform plan will return the differences that should have been applied.
```sh
  # aws_db_parameter_group.default will be updated in-place
  ~ resource "aws_db_parameter_group" "default" {
      # ...
      - parameter {
          - apply_method = "immediate" -> null
          - name         = "log_statement" -> null
          - value        = "mod" -> null
        }
      + parameter {
          + apply_method = "pending-reboot"
          + name         = "log_statement"
          + value        = "mod"
        }
    }
```

### Debug Output

There seems to be a difference in the values of the variables.
https://github.com/hashicorp/terraform-provider-aws/blob/dbccf03ad2ecf74ac54987302ad3384a77481883/internal/service/rds/parameter_group.go#L237

***Log (Formatted)***
```sh
aws_db_parameter_group.default: Modifying... [id=rds-pg]
[DEBUG] o = &{0x10e30100 map[3018798939:map[apply_method:immediate name:log_statement value:mod]]
[DEBUG] n = &{0x10e30100 map[1029368019:map[apply_method:pending-reboot name:log_statement value:mod]] 
```

### Important Factoids

tfstate stores changes to `pending-reboot`.
```
"parameter": [                        
  {                                   
    "apply_method": "pending-reboot", 
    "name": "log_statement",          
    "value": "mod"                    
  }                                   
],                                    
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-03-20 19:44
Hey @naruse666 👋 Thank you for taking the time to raise this! I took a look over some of the related AWS documentation and noticed a note in the [`ModifyDBParameterGroup` documentation](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyDBParameterGroup.html) that leads me to believe this may be an eventual consistency issue. If you wait a few minute between the applies, does the issue persist?

**Comment by naruse666** [comment] 2024-03-20 20:27
Yes, differences will continue to be generated even after a period of time as stated in the documentation.

The change in apply_method was successful, and tfstate also appears to be correct, so I have not been able to identify the problem code.

**Comment by justinretzolk** [comment] 2024-03-21 17:50
@naruse666 In these cases, what do you see if you use [`describe-db-parameter-groups`](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/rds/describe-db-parameter-groups.html) to fetch information about the parameter group? Does the `apply_method` look correct?

**Comment by naruse666** [comment] 2024-03-22 23:48
@justinretzolk 
This is the command executed and the result.
```
aws rds describe-db-parameters --db-parameter-group-name rds-pg |jq -r '.Parameters[] | [.ParameterName, .ParameterValue, .ApplyMethod] '
```
```
[
  "deadlock_timeout",
  null,
...skipping...
  "log_statement",
  "mod",
  "immediate"
]
```

Why does this simple change cause a deadlock?
This may be due to my lack of AWS knowledge.

**Comment by justinretzolk** [comment] 2024-03-26 16:45
Hey @naruse666 👋 I took another look over this and noticed a callout note at the top of the [`aws_db_parameter_group` documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_parameter_group):

> After applying your changes, you may encounter a perpetual diff in your Terraform plan output for a `parameter` whose `value` remains unchanged but whose `apply_method` is changing (e.g., from `immediate` to `pending-reboot`, or `pending-reboot` to `immediate`). If only the apply method of a parameter is changing, the AWS API will not register this change. To change the `apply_method` of a parameter, its value must also change.

Since it looks like this is expected behavior caused by the way the upstream API behaves, I'll go ahead and close this issue as well.

**Closed by justinretzolk** 2024-03-26 16:45 UTC
Labels: bug, service/rds, needs-triage

**Comment by naruse666** [comment] 2024-03-27 22:24
@justinretzolk 
I completely missed it.
Thank you for teaching me so carefully!
