### ISSUE TITLE
resource/aws_route: route is not saved in the state when it fails to be available (in 2m) on creation

### ISSUE THREAD

**Issue by ialidzhikov** [hashicorp/terraform-provider-aws#21032] opened 2021-09-24 09:54 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform version - 0.12.31
provider-aws version - 3.54.0

### Affected Resource(s)

* aws_route

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "aws" {
  access_key = var.ACCESS_KEY_ID
  secret_key = var.SECRET_ACCESS_KEY
  region     = "eu-west-1"
}

resource "aws_vpc" "vpc" {
  cidr_block           = "10.222.0.0/16"
  enable_dns_support   = true
  enable_dns_hostnames = true
}

resource "aws_subnet" "public_utility_z0" {
  vpc_id            = aws_vpc.vpc.id
  cidr_block        = "10.222.96.0/26"
  availability_zone = "eu-west-1a"
}

resource "aws_eip" "eip_natgw_z0" {
  vpc = true
}

resource "aws_nat_gateway" "natgw_z0" {
  allocation_id = aws_eip.eip_natgw_z0.id
  subnet_id     = aws_subnet.public_utility_z0.id
}

resource "aws_route_table" "routetable_private_utility_z0" {
  vpc_id = aws_vpc.vpc.id
}

resource "aws_route" "private_utility_z0_nat" {
  route_table_id         = aws_route_table.routetable_private_utility_z0.id
  destination_cidr_block = "0.0.0.0/0"
  nat_gateway_id         = aws_nat_gateway.natgw_z0.id
}

```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

I would expect that terraform-provider-aws saves the route in the state and waits for it to get ready. And `terraform apply` fails when the route cannot be available (in 2m) but the route is saved in the state and no state is lost/leaked.
Or alternatively terraform-provider-aws does not save the route in the state but ensures that the corresponding route (that cannot be available in 2m) is deleted afterwards.
I don't have much experience with handling of such cases, just a rough idea from my side.

Most probably the other resources handle this already in a better way and something similar is probably applicable for the aws_route.

For example I compared the subnet and route creation. 

On subnet creation we call `d.SetId(subnetId)` (I think the part that ensures that the resources is saved in the state) right after the subnet create call and before the wait until the subnet gets ready. I think that with this handling we don't lose the subnet state if for example the subnet cannot get ready.

https://github.com/hashicorp/terraform-provider-aws/blob/9ff6122a9835dcad14bfc22828cb7a4cf1269b66/aws/resource_aws_subnet.go#L150-L176

On the other side, on route creation we call `d.SetId(tfec2.RouteCreateID(routeTableID, destination))` after the wait until the route gets available. So if the route does not get available, we don't save the resource state.

https://github.com/hashicorp/terraform-provider-aws/blob/9ff6122a9835dcad14bfc22828cb7a4cf1269b66/aws/resource_aws_route.go#L233-L253

### Actual Behavior

When applying the above partial terraform configuration, we notice that the `aws_route` is not saved in the state ("leaks") when the route fails to be available (in 2m) on creation.

The corresponding failure is:
```
error waiting for Route in Route Table (rtb-07269a2e5202b1234) with destination (0.0.0.0/0) to become available: timeout while waiting for state to become 'ready' (timeout: 2m0s)
  on tf/main.tf line 354, in resource "aws_route" "private_utility_z0_nat":
 354: resource "aws_route" "private_utility_z0_nat" {
```

Afterwards any subsequent `terraform appy` run fails with reason RouteAlreadyExists:

```
error creating Route in Route Table (rtb-07269a2e5202b1234) with destination (0.0.0.0/0): RouteAlreadyExists: The route identified by 0.0.0.0/0 already exists.
	status code: 400, request id: <omitted>
  on tf/main.tf line 354, in resource "aws_route" "private_utility_z0_nat":
 354: resource "aws_route" "private_utility_z0_nat" {
```

Background: we have a lot of automation on top of `terraform apply`. Such inconsistencies cause us troubles because `terraform apply` itself is not able to recover from such state where a resource is leaked and new one cannot be created because of it. And such cases require manual intervention to fix the terraform state and the state in the infrastructure.

### Steps to Reproduce

1. `terraform apply`

Ensure that the first `terraform apply` can potentially fail that the route cannot get available for 2m
```
error waiting for Route in Route Table (rtb-07269a2e5202b1234) with destination (0.0.0.0/0) to become available: timeout while waiting for state to become 'ready' (timeout: 2m0s)
  on tf/main.tf line 354, in resource "aws_route" "private_utility_z0_nat":
 354: resource "aws_route" "private_utility_z0_nat" {
```

2. Ensure that the corresponding route is leaked and any subsequent `terraform apply` fails with reason RouteAlreadyExists.

### Important Factoids

N/A

### References

* #0000

**Comment by ddvdozuki** [comment] 2021-09-25 11:17
I'm having this issue intermittently as well. I can't reliably reproduce it though.

**Comment by gtantachuco** [comment] 2021-10-04 22:51
I get the same error. However, when I run 'terraform apply' again, it works.

**Comment by dwyerk** [comment] 2021-10-06 20:44
I'm also seeing this in us-east-1 today. It's intermittent since most of the time AWS doesn't take 2 minutes to build a route.

@ialidzhikov - how does your team recover from this state besides manually deleting the routes that were ultimately created and trying to `apply` again?

**Comment by dwyerk** [comment] 2021-10-07 18:50
Good point @BrandonALXEllisSS - that may be a mitigation but as the OP points out, this is a bug because it leaves the state broken when the route creation times out.

**Comment by ccourtoyaxis** [comment] 2021-10-14 00:47
@ddvdozuki, it is quite the opposite, what I am saying is that this is the cause of the initial failure. The fact that it is unrecoverable is different problem.  But the root cause of the route creation which times out is the default timeout value which changed from 5 minutes to 2 minutes, which is too short. I have excluded provider aws 3.62.0 version (the version which contains the PR) and have not had the issue since. I only did 2 deployments so far, but this week it failed almost every time.

```terraform
terraform {
  required_version = ">= 1.0.0"
  backend "s3" {
    bucket = "tf-state-acs-portal"
    key    = "reservation.feature/terraform"
    region = "us-east-1"
    dynamodb_table = "acs-portal-tf-state"
    encrypt        = true
  }

  required_providers {
    aws = {
      "source"  = "hashicorp/aws"
      "version" = ">= 3.34.0, != 3.62.0"
    }
  }
}
```

This being said, this issue about the failue not being stored in the state is in fact a real problem. As mentionned in earlier comments, you must delete the routes manually, otherwise on a subsequent run you get the **ressource already exists** error. So this get the user in a catch 22.

**Comment by nevelis** [comment] 2021-11-10 18:30
Using latest release (3.64.2), seems timeout I specify is still being ignored & using default of 2m30, which requires manual intervention because it eventually succeeds, then complains it already exists.

**Comment by ialidzhikov** [comment] 2021-11-10 21:50
It seems that hashicorp/terraform-provider-aws#21161 (included in 3.62.0) makes the `RouteReady` func to use a configurable timeout - `TimeoutCreate`. `TimeoutCreate` still defaults to `2m` but the timeout at least is configurable now. 

https://github.com/hashicorp/terraform-provider-aws/blob/fce7062f70caa92a78bca629ffe441c088456418/aws/resource_aws_route.go#L247

Previously `RouteReady` was using a hard-coded timeout (`PropagationTimeout`, defaults to `2m`) which was not configurable.

To my understanding upgrading to terraform-provider-aws `>= 3.62.0` and specifying a high timeout should mitigate this issue:

```hcl
resource "aws_route" "foo" {
  // ...  

  timeouts {
    create = "5m"
  }
}
```

Of course, the general issue that route is not saved in the state when it fails to be available for the given timeout is still present.

**Comment by ialidzhikov** [comment] 2021-11-10 21:53
> Using latest release (3.64.2), seems timeout I specify is still being ignored & using default of 2m30, which requires manual intervention because it eventually succeeds, then complains it already exists.

@nevelis are you sure that you specify create timeout and you use terraform-provider-aws `>= 3.62.0`? I hope that https://github.com/hashicorp/terraform-provider-aws/issues/21032#issuecomment-965777108 helps you to mitigate the issue. If it doesn't, please share.

**Comment by cdancy** [comment] 2021-11-10 23:12
Hitting this issue as well and we're using 3.64.2 (latest release I believe).

**Comment by ialidzhikov** [comment] 2021-11-11 06:19
> Hitting this issue as well and we're using 3.64.2 (latest release I believe).

Do you specify a custom create timeout and what is its value?

**Comment by cdancy** [comment] 2021-11-11 12:07
@ialidzhikov the only timeout we specify is on our aws_vpc_endpoint like so:
```
resource "aws_vpc_endpoint" "dynamodb" {
  count             = length(module.vpc.private_route_table_ids) > 0 ? 1 : 0
  vpc_endpoint_type = "Gateway"
  vpc_id            = module.vpc.vpc_id
  service_name      = "com.amazonaws.${data.aws_region.current.name}.dynamodb"
  tags              = local.tags
  timeouts {
    create = "30m"
    update = "30m"
    delete = "30m"
  }
```

**Comment by dguendisch** [comment] 2021-11-11 12:27
@cdancy but then it's clear that you are hit (because route creation often takes longer than the default 2m timeout). Your vpc timeout is not related to the aws_route timeout, the latter can be configured since 3.62.0, you could try that.

**Comment by cdancy** [comment] 2021-11-11 19:26
@dguendisch @ialidzhikov  we're using latest vpc module 3.64.2 and have put together our terrafrom script as described in [THIS ISSUE](https://github.com/terraform-aws-modules/terraform-aws-vpc/issues/708). We should have the default 5m timeout at this point if I'm not mistaken. 

Is there a way to easily configure the route timeouts other than what is noted in that ISSUE (and below)?
```
resource "aws_default_route_table" "rtb-default" {
  default_route_table_id = module.vpc.default_vpc_main_route_table_id
  timeouts {
    create = "30m"
    update = "30m"
  }
}
```

**Comment by cdancy** [comment] 2021-11-12 02:16
Issue _may_ actually be solved when the release for this PR is made https://github.com/hashicorp/terraform-provider-aws/issues/21683

**Comment by justinretzolk** [comment] 2021-11-15 19:32
Hi all 👋 [This PR](https://github.com/hashicorp/terraform-provider-aws/pull/21710) made it in to the `3.65.0` release of the provider, and as @cdancy mentioned, I'm curious as to whether that PR may have resolved this issue as well. Can someone who was previously experiencing this test with this new provider version and see if that corrected the issue?

**Comment by benbense** [comment] 2021-11-15 22:39
@justinretzolk I can confirm transitioning to version 3.65.0 does in fact fix the issue for me.

**Comment by cdancy** [comment] 2021-11-16 13:39
@justinretzolk @benbense moving to latest and greatest did not solve the issue for us and it looks like at least for one other person as well

**Comment by benbense** [comment] 2021-11-16 13:43
@cdancy After checking with a colleague of mine seems like the issue wasn't fixed for him also, maybe it has to do with the Terraform version also? I'm running 1.0.11.
He's running an older version and will try to update it today.

**Comment by cdancy** [comment] 2021-11-16 13:46
@benbense ohhh ... yeah please respond back if that does fix things. We're on 1.0.8

**Comment by benbense** [comment] 2021-11-16 15:10
@cdancy unfortunately it didn't help

**Comment by sandyvanam** [comment] 2021-11-17 14:00
**Temporary Solution :** move to respective route table and delete the entry 0.0.0.0/0 and run terraform apply.

> ### Community Note
> * Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
> * Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
> * If you are interested in working on this issue or have submitted a pull request, please leave a comment
> 
> ### Terraform CLI and Terraform AWS Provider Version
> terraform version - 0.12.31 provider-aws version - 3.54.0
> 
> ### Affected Resource(s)
> * aws_route
> 
> ### Terraform Configuration Files
> Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.
> 
> ```terraform
> provider "aws" {
>   access_key = var.ACCESS_KEY_ID
>   secret_key = var.SECRET_ACCESS_KEY
>   region     = "eu-west-1"
> }
> 
> resource "aws_vpc" "vpc" {
>   cidr_block           = "10.222.0.0/16"
>   enable_dns_support   = true
>   enable_dns_hostnames = true
> }
> 
> resource "aws_subnet" "public_utility_z0" {
>   vpc_id            = aws_vpc.vpc.id
>   cidr_block        = "10.222.96.0/26"
>   availability_zone = "eu-west-1a"
> }
> 
> resource "aws_eip" "eip_natgw_z0" {
>   vpc = true
> }
> 
> resource "aws_nat_gateway" "natgw_z0" {
>   allocation_id = aws_eip.eip_natgw_z0.id
>   subnet_id     = aws_subnet.public_utility_z0.id
> }
> 
> resource "aws_route_table" "routetable_private_utility_z0" {
>   vpc_id = aws_vpc.vpc.id
> }
> 
> resource "aws_route" "private_utility_z0_nat" {
>   route_table_id         = aws_route_table.routetable_private_utility_z0.id
>   destination_cidr_block = "0.0.0.0/0"
>   nat_gateway_id         = aws_nat_gateway.natgw_z0.id
> }
> ```
> 
> ### Debug Output
> N/A
> 
> ### Panic Output
> N/A
> 
> ### Expected Behavior
> I would expect that terraform-provider-aws saves the route in the state and waits for it to get ready. And `terraform apply` fails when the route cannot be available (in 2m) but the route is saved in the state and no state is lost/leaked. Or alternatively terraform-provider-aws does not save the route in the state but ensures that the corresponding route (that cannot be available in 2m) is deleted afterwards. I don't have much experience with handling of such cases, just a rough idea from my side.
> 
> Most probably the other resources handle this already in a better way and something similar is probably applicable for the aws_route.
> 
> For example I compared the subnet and route creation.
> 
> On subnet creation we call `d.SetId(subnetId)` (I think the part that ensures that the resources is saved in the state) right after the subnet create call and before the wait until the subnet gets ready. I think that with this handling we don't lose the subnet state if for example the subnet cannot get ready.
> 
> https://github.com/hashicorp/terraform-provider-aws/blob/9ff6122a9835dcad14bfc22828cb7a4cf1269b66/aws/resource_aws_subnet.go#L150-L176
> 
> On the other side, on route creation we call `d.SetId(tfec2.RouteCreateID(routeTableID, destination))` after the wait until the route gets available. So if the route does not get available, we don't save the resource state.
> 
> https://github.com/hashicorp/terraform-provider-aws/blob/9ff6122a9835dcad14bfc22828cb7a4cf1269b66/aws/resource_aws_route.go#L233-L253
> 
> ### Actual Behavior
> When applying the above partial terraform configuration, we notice that the `aws_route` is not saved in the state ("leaks") when the route fails to be available (in 2m) on creation.
> 
> The corresponding failure is:
> 
> ```
> error waiting for Route in Route Table (rtb-07269a2e5202b1234) with destination (0.0.0.0/0) to become available: timeout while waiting for state to become 'ready' (timeout: 2m0s)
>   on tf/main.tf line 354, in resource "aws_route" "private_utility_z0_nat":
>  354: resource "aws_route" "private_utility_z0_nat" {
> ```
> 
> Afterwards any subsequent `terraform appy` run fails with reason RouteAlreadyExists:
> 
> ```
> error creating Route in Route Table (rtb-07269a2e5202b1234) with destination (0.0.0.0/0): RouteAlreadyExists: The route identified by 0.0.0.0/0 already exists.
> 	status code: 400, request id: <omitted>
>   on tf/main.tf line 354, in resource "aws_route" "private_utility_z0_nat":
>  354: resource "aws_route" "private_utility_z0_nat" {
> ```
> 
> Background: we have a lot of automation on top of `terraform apply`. Such inconsistencies cause us troubles because `terraform apply` itself is not able to recover from such state where a resource is leaked and new one cannot be created because of it. And such cases require manual intervention to fix the terraform state and the state in the infrastructure.
> 
> ### Steps to Reproduce
> 1. `terraform apply`
> 
> Ensure that the first `terraform apply` can potentially fail that the route cannot get available for 2m
> 
> ```
> error waiting for Route in Route Table (rtb-07269a2e5202b1234) with destination (0.0.0.0/0) to become available: timeout while waiting for state to become 'ready' (timeout: 2m0s)
>   on tf/main.tf line 354, in resource "aws_route" "private_utility_z0_nat":
>  354: resource "aws_route" "private_utility_z0_nat" {
> ```
> 
> 1. Ensure that the corresponding route is leaked and any subsequent `terraform apply` fails with reason RouteAlreadyExists.
> 
> ### Important Factoids
> N/A
> 
> ### References
> * #0

**Comment by cdancy** [comment] 2021-11-17 14:11
@sandyvanam what do you mean by "move to respective route table"?

**Comment by i-engy** [comment] 2021-11-29 13:51
Please make aws_route respect timeouts defined in configuration. its failing all the times after 2m30s. I have tried a dozen version combinations and still same result. 21 tries and 2m30s timeout.

**Comment by ialidzhikov** [comment] 2021-11-29 14:14
> Please make aws_route respect timeouts defined in configuration. its failing all the times after 2m30s. I have tried a dozen version combinations and still same result. 21 tries and 2m30s timeout.

Try out with 3.66.0 (ref https://github.com/hashicorp/terraform-provider-aws/pull/21831).

**Comment by cdancy** [comment] 2021-11-29 18:37
@ialidzhikov still failing for us:
```
10:23:17          	            	    - Error: "terraform apply -auto-approve -no-color -input=false plan.json" command failed with code 1
10:23:17          	            	               
10:23:17          	            	               Error: error reading Route Table Association (rtbassoc-0bf64424a72d7ab4f): empty result
10:23:17          	            	               
10:23:17          	            	                 with module.vpc.aws_route_table_association.public[2],
10:23:17          	            	                 on .terraform/modules/vpc/main.tf line 1204, in resource "aws_route_table_association" "public":
10:23:17          	            	               1204: resource "aws_route_table_association" "public" {
10:23:17          	            	               
10:23:17          	            	               
10:23:17          	            	               Error: error reading Route Table Association (rtbassoc-05f19b75d7e7b114a): empty result
10:23:17          	            	               
10:23:17          	            	                 with module.vpc.aws_route_table_association.public[1],
10:23:17          	            	                 on .terraform/modules/vpc/main.tf line 1204, in resource "aws_route_table_association" "public":
10:23:17          	            	               1204: resource "aws_route_table_association" "public" {
```
I'd be up for a screen-share to show you what we're doing to see if you can spot anything. Just let me know.

**Comment by i-engy** [comment] 2021-11-30 15:29
yes. I can confirm that v3.66 has fixed this issue after @ialidzhikov  changes. Big thanks to @ialidzhikov  for updating route retries to 1000. cheers.

**Closed** 2021-12-16 18:33 UTC
Labels: bug, service/ec2

**Comment by Riinkesh** [comment] 2022-03-23 15:54
This is still the issue even with 1001 retries. The issue is that terraform although creates the route, but doesn't update the state and keeps retrying until timeout and/or retries limit.
Terraform should be able to check the route status with every retry & therefore should update the state correctly.
