### ISSUE TITLE
"registry.terraform.io/hashicorp/aws" produced an invalid new value for .source_code_hash

### ISSUE THREAD

**Issue by GreatThane** [hashicorp/terraform-provider-aws#21913] opened 2021-11-26 01:00 UTC
While working with AWS Lambda functions, terraform creates an (inconsistent) error, located in the spoiler below.
Immediately rerunning the command finishes applying without error.

Based on the contents of the error message, I am assuming it relates to the following snippet:

```terraform
resource "local_file" "instance_data" {
  filename = "${path.module}/stop_server_event/instance_data.json"
  content = jsonencode({
    private_ip = aws_spot_instance_request.mc_server.private_ip
    id = aws_spot_instance_request.mc_server.spot_instance_id
    server_name = var.server_name
    rcon_port = var.rcon_port
    rcon_password = var.rcon_password
  })
}

data "archive_file" "stop_server_event_files" {
  type             = "zip"
  output_file_mode = "0666"
  output_path      = "${path.module}/dist/stop_server_event_files.zip"
  excludes         = ["README.md", "*.md", ".md"]
  depends_on = [local_file.instance_data]

  source_dir = "${path.module}/stop_server_event"
}

resource "aws_lambda_function" "stop_server_event" {
  filename         = data.archive_file.stop_server_event_files.output_path
  source_code_hash = filebase64sha256(data.archive_file.stop_server_event_files.output_path)
  function_name    = "mc_stop_event"
  role             = aws_iam_role.stop_server_event_role.arn
  handler          = "index.handler"
  runtime          = "nodejs14.x"
  timeout = 7
  vpc_config {
    security_group_ids = [aws_security_group.mc_server_security.id]
    subnet_ids         = [aws_subnet.minecraft_public_subset.id]
  }
}
```

Where source code of a lambda function is dependent on the attributes of other terraform resources.

I would attach the entirety of my source, but there is a lot (and it is messy). If that would be helpful anyway, I will upload it.

<details>
  <summary>Command Output</summary>
  
```
/usr/bin/terraform apply -auto-approve
aws_cloudwatch_event_rule.interruption_event_trigger: Refreshing state... [id=capture_spot_interruption_warning]
aws_vpc.mc_server_vpc: Refreshing state... [id=vpc-078115d7b9d2d87ad]
aws_iam_policy.LambdaVPCAccess: Refreshing state... [id=arn:aws:iam::565482055199:policy/LambdaVPCAccess]
aws_iam_role.stop_server_event_role: Refreshing state... [id=stop_server_event_role]
aws_iam_role_policy_attachment.connect_vpc_access_to_stop_server_role: Refreshing state... [id=stop_server_event_role-20211126000115114400000001]
aws_internet_gateway.mc_internet_gateway: Refreshing state... [id=igw-0c06a0de112fd0ca1]
aws_subnet.minecraft_public_subset: Refreshing state... [id=subnet-07d68d4b6aafc8caa]
aws_security_group.mc_server_security: Refreshing state... [id=sg-0ec6196e5fb1dc932]
aws_route.allow_internet: Refreshing state... [id=r-rtb-0d7a80d1a608aac731080289494]
aws_spot_instance_request.mc_server: Refreshing state... [id=sir-imspbptj]
aws_eip.server_elastic_ip: Refreshing state... [id=eipalloc-0f68702ed4a9ca449]
local_file.instance_data: Refreshing state... [id=9d445dea97bba619366f533e8e04a68d93d23d9e]
aws_lambda_function.stop_server_event: Refreshing state... [id=mc_stop_event]
aws_route53_record.server_subdomain_record: Refreshing state... [id=Z0628777126U61EWI4A6F_minecraft.sassyboy.net_A]
aws_lambda_permission.allow_cloudwatch: Refreshing state... [id=AllowExecutionFromCloudWatch]
aws_cloudwatch_event_target.stop_server_event_trigger_association: Refreshing state... [id=capture_spot_interruption_warning-terraform-20211126000538983900000001]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_spot_instance_request.mc_server has been changed
  ~ resource "aws_spot_instance_request" "mc_server" {
        id                              = "sir-imspbptj"
      ~ public_dns                      = "ec2-3-15-233-14.us-east-2.compute.amazonaws.com" -> "ec2-3-142-18-55.us-east-2.compute.amazonaws.com"
      ~ public_ip                       = "3.15.233.14" -> "3.142.18.55"
        tags                            = {
            "Name" = "mc_server"
        }
        # (28 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place
-/+ destroy and then create replacement
 <= read (data resources)

Terraform will perform the following actions:

  # data.archive_file.stop_server_event_files will be read during apply
  # (config refers to values not yet known)
 <= data "archive_file" "stop_server_event_files"  {
      ~ id                  = "5ba3e262151ecee0ff6acbe337ee4e16c0376117" -> (known after apply)
      ~ output_base64sha256 = "yCrksO8XzCYfiIIt0NqkHZmd8IVN1iea0Btz1e4AbO0=" -> (known after apply)
      ~ output_md5          = "a33d88ef698b8b0b87dcf80e74b50ec9" -> (known after apply)
      ~ output_sha          = "5ba3e262151ecee0ff6acbe337ee4e16c0376117" -> (known after apply)
      ~ output_size         = 3452 -> (known after apply)
        # (5 unchanged attributes hidden)
    }

  # aws_eip.server_elastic_ip will be updated in-place
  ~ resource "aws_eip" "server_elastic_ip" {
        id                   = "eipalloc-0f68702ed4a9ca449"
      ~ instance             = "i-06efc9bcc5ff31595" -> (known after apply)
        tags                 = {}
        # (12 unchanged attributes hidden)
    }

  # aws_lambda_function.stop_server_event will be updated in-place
  ~ resource "aws_lambda_function" "stop_server_event" {
        id                             = "mc_stop_event"
      ~ last_modified                  = "2021-11-26T00:39:48.000+0000" -> (known after apply)
      ~ source_code_hash               = "PGmsV7Tb12mEX1AeAMBxWKcCQ1ysnUph8ue3sYa56e8=" -> "yCrksO8XzCYfiIIt0NqkHZmd8IVN1iea0Btz1e4AbO0="
        tags                           = {}
        # (18 unchanged attributes hidden)


        # (2 unchanged blocks hidden)
    }

  # aws_spot_instance_request.mc_server must be replaced
-/+ resource "aws_spot_instance_request" "mc_server" {
      + arn                                  = (known after apply)
      + availability_zone                    = (known after apply)
      - block_duration_minutes               = 0 -> null
      + cpu_core_count                       = (known after apply)
      + cpu_threads_per_core                 = (known after apply)
      + disable_api_termination              = (known after apply)
      + ebs_optimized                        = (known after apply)
      + host_id                              = (known after apply)
      ~ id                                   = "sir-imspbptj" -> (known after apply)
      + instance_initiated_shutdown_behavior = (known after apply)
      ~ instance_interruption_behaviour      = "stop" -> (known after apply)
      + instance_state                       = (known after apply)
      ~ ipv6_address_count                   = 0 -> (known after apply)
      ~ ipv6_addresses                       = [] -> (known after apply)
      + monitoring                           = (known after apply)
      + outpost_arn                          = (known after apply)
      + password_data                        = (known after apply)
      + placement_group                      = (known after apply)
      + placement_partition_number           = (known after apply)
      ~ primary_network_interface_id         = "eni-01754fcd6cc7609a9" -> (known after apply)
      ~ private_dns                          = "ip-10-0-1-131.us-east-2.compute.internal" -> (known after apply)
      ~ private_ip                           = "10.0.1.131" -> (known after apply)
      ~ public_dns                           = "ec2-3-142-18-55.us-east-2.compute.amazonaws.com" -> (known after apply)
      ~ public_ip                            = "3.142.18.55" -> (known after apply)
      ~ secondary_private_ips                = [] -> (known after apply)
      ~ security_groups                      = [] -> (known after apply)
      ~ spot_bid_status                      = "fulfilled" -> (known after apply)
      ~ spot_instance_id                     = "i-06efc9bcc5ff31595" -> (known after apply)
      ~ spot_price                           = "0.186000" -> (known after apply)
      ~ spot_request_state                   = "active" -> (known after apply)
        tags                                 = {
            "Name" = "mc_server"
        }
      + tenancy                              = (known after apply)
      ~ user_data                            = "9d033a7a958040436d393568a5721f1ece68eb09" -> "35dcc57c3e256e467f6054f56307f0058005f7e6" # forces replacement
      + user_data_base64                     = (known after apply)
      ~ valid_from                           = "0001-01-01T00:00:00Z" -> (known after apply)
      ~ valid_until                          = "0001-01-01T00:00:00Z" -> (known after apply)
        # (12 unchanged attributes hidden)

      + capacity_reservation_specification {
          + capacity_reservation_preference = (known after apply)

          + capacity_reservation_target {
              + capacity_reservation_id = (known after apply)
            }
        }

      + ebs_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + snapshot_id           = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }

      + enclave_options {
          + enabled = (known after apply)
        }

      + ephemeral_block_device {
          + device_name  = (known after apply)
          + no_device    = (known after apply)
          + virtual_name = (known after apply)
        }

      + metadata_options {
          + http_endpoint               = (known after apply)
          + http_put_response_hop_limit = (known after apply)
          + http_tokens                 = (known after apply)
        }

      + network_interface {
          + delete_on_termination = (known after apply)
          + device_index          = (known after apply)
          + network_interface_id  = (known after apply)
        }

      ~ root_block_device {
          ~ delete_on_termination = true -> (known after apply)
          ~ device_name           = "/dev/xvda" -> (known after apply)
          ~ encrypted             = false -> (known after apply)
          ~ iops                  = 100 -> (known after apply)
          + kms_key_id            = (known after apply)
          ~ tags                  = {} -> (known after apply)
          ~ throughput            = 0 -> (known after apply)
          ~ volume_id             = "vol-0a577b59d17bf2554" -> (known after apply)
          ~ volume_size           = 8 -> (known after apply)
          ~ volume_type           = "gp2" -> (known after apply)
        }
    }

  # local_file.instance_data must be replaced
-/+ resource "local_file" "instance_data" {
      ~ content              = jsonencode(
            {
              - id            = "i-06efc9bcc5ff31595"
              - private_ip    = "10.0.1.131"
              - rcon_password = "minecraft"
              - rcon_port     = 25575
              - server_name   = "minecraft"
            }
        ) -> (known after apply) # forces replacement
      ~ id                   = "9d445dea97bba619366f533e8e04a68d93d23d9e" -> (known after apply)
        # (3 unchanged attributes hidden)
    }

Plan: 2 to add, 2 to change, 2 to destroy.

Changes to Outputs:
  ~ ec2_instance_id = "i-06efc9bcc5ff31595" -> (known after apply)
local_file.instance_data: Destroying... [id=9d445dea97bba619366f533e8e04a68d93d23d9e]
local_file.instance_data: Destruction complete after 0s
aws_spot_instance_request.mc_server: Destroying... [id=sir-imspbptj]
aws_spot_instance_request.mc_server: Still destroying... [id=sir-imspbptj, 10s elapsed]
aws_spot_instance_request.mc_server: Still destroying... [id=sir-imspbptj, 20s elapsed]
aws_spot_instance_request.mc_server: Still destroying... [id=sir-imspbptj, 30s elapsed]
aws_spot_instance_request.mc_server: Destruction complete after 30s
aws_spot_instance_request.mc_server: Creating...
aws_spot_instance_request.mc_server: Still creating... [10s elapsed]
aws_spot_instance_request.mc_server: Creation complete after 12s [id=sir-jwhy9j7g]
local_file.instance_data: Creating...
local_file.instance_data: Creation complete after 1s [id=a11a6bbcfd04cbc0ba9a316fca78a61e49b0446f]
aws_eip.server_elastic_ip: Modifying... [id=eipalloc-0f68702ed4a9ca449]
data.archive_file.stop_server_event_files: Reading... [id=5ba3e262151ecee0ff6acbe337ee4e16c0376117]
data.archive_file.stop_server_event_files: Read complete after 0s [id=12eaee6a2810abd0781867c3b06725db344dbaf2]
aws_eip.server_elastic_ip: Modifications complete after 1s [id=eipalloc-0f68702ed4a9ca449]
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for aws_lambda_function.stop_server_event to
│ include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for
│ .source_code_hash: was
│ cty.StringVal("yCrksO8XzCYfiIIt0NqkHZmd8IVN1iea0Btz1e4AbO0="), but now
│ cty.StringVal("3L3Yo3dgneoMVjd7sWSS5D1pF9cfSDn/g6Ih0LZ9kvU=").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```
</details>

**Comment by GreatThane** [comment] 2021-11-26 04:23
Upon further investigation, I believe that the `filebase64sha256` function is executing before the data archive resource can execute.

**Comment by justinretzolk** [comment] 2021-12-09 18:41
@GreatThane I believe that you're correct in that assessment, as the value for the data source (for the `archive_file`) will not be known until apply time ([more information here](https://www.terraform.io/docs/language/data-sources/index.html#data-resource-behavior)), which is likely the cause of the diff.

I did note that the `archive_file` data source has a `output_base64sha256` attribute, however. I haven't yet been able to test this myself, but I suspect if you update the `aws_lambda_function.stop_server_event.source_code_hash` argument to `data.archive_file.stop_server_event_files.output_base64sha256`, that may resolve the issue. Can you test that and see if that improves the behavior?

**Comment by Neogility** [comment] 2021-12-14 14:17
@justinretzolk Your solution does appear to resolve the issue.

**Comment by apparentlymart** [comment] 2022-04-21 17:49
Hi all,

Just wanted to confirm that indeed `archive_file` can cause problems like this, because it's technically a _misbehaving_ data source: data sources are not supposed to create or modify existing objects since the focus of that feature is to retrieve existing data.

This data source is designed the way it is as a concession to pragmatism -- other resource types that expect to consume zip files typically expect to read them directly from disk, rather than from e.g. a base64 string in memory -- but that does mean it must be used with extra care when compared to most other data sources, so that anything relying on its result doesn't do anything that exposes the leaky abstraction. Relying only on the data source's own output attributes directly is often a good start for that, because then Terraform's normal dependency mechanisms can make sure the side-effect happens at an appropriate time even though this data source shouldn't actually _have_ a side-effect.

It's unfortunate that this ends up getting blamed on the provider that consumed the value, but in this case Terraform was doing the best it can to guess what had happened based on its expectations about how the various participants ought to behave. The `archive_file` data source managed to "fool" Terraform Core by secretly changing the files on disk behind its back, causing `source_code_hash` to end up with a different value in a way that Terraform Core didn't have enough information to explain correctly.

**Comment by justinretzolk** [comment] 2022-04-21 18:34
Thank you for the additional details @apparentlymart! With that information and the aforementioned workaround in mind, we'll close this issue. If anyone comes across this issue in the future and has additional follow up questions, please feel free to open a new issue so that we can take another look.

**Closed by justinretzolk** 2022-04-21 18:34 UTC
Labels: bug, service/lambda, service/ec2
