### ISSUE TITLE
Suppor source_version for secondary in codebuild_project

### ISSUE THREAD

**Issue by pavel-trubitsyn** [hashicorp/terraform-provider-aws#21511] opened 2021-10-27 04:08 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, **aws_codebuild_project** does not allow to specify **source_version** for secondary sources.

### New or Affected Resource(s)
* aws_codebuild_project

### Potential Terraform Configuration

```hcl
resource "aws_codebuild_project" "example" {
  secondary_sources {
    source_version = ""
  }
}
```

### References
* https://docs.aws.amazon.com/codebuild/latest/userguide/sample-source-version.html
* https://docs.aws.amazon.com/codebuild/latest/APIReference/API_ProjectSourceVersion.html#CodeBuild-Type-ProjectSourceVersion-sourceVersion

**Comment by DrFaust92** [comment] 2021-12-25 14:43
Duplicate of #13241

**Closed by DrFaust92** 2021-12-25 14:43 UTC
Labels: enhancement, service/codebuild
