### ISSUE TITLE
[Bug]: TF reports continuously shows changes on sensitive field although the value didn't change.

### ISSUE THREAD

**Issue by bebold-jhr** [hashicorp/terraform-provider-aws#39442] opened 2024-09-23 08:44 UTC
### Terraform Core Version

1.9.5

### AWS Provider Version

5.68.0

### Affected Resource(s)

* aws_rolesanywhere_trust_anchor

### Expected Behavior

No changes.

```bash
Plan: 0 to add, 0 to change, 0 to destroy.
```

### Actual Behavior

Continuous diff with update in-place although the value didn't change.

```bash
# aws_rolesanywhere_trust_anchor.this will be updated in-place
  ~ resource "aws_rolesanywhere_trust_anchor" "this" {
        id       = "############"
        name     = "############"
        tags     = {}
        # (3 unchanged attributes hidden)
      ~ source {
            # (1 unchanged attribute hidden)
          ~ source_data {
              ~ x509_certificate_data = (sensitive value)
                # (1 unchanged attribute hidden)
            }
        }
        # (2 unchanged blocks hidden)
    }
```

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 1.5"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.67.0"
    }
    vault = {
      source  = "hashicorp/vault"
      version = "4.4.0"
    }
  }
}

data "vault_generic_secret" "this" {
  path = "####"
}

resource "aws_rolesanywhere_trust_anchor" "this" {
  name    = "####"
  enabled = true

  source {
    source_type = "CERTIFICATE_BUNDLE"

    source_data {
      x509_certificate_data = lookup(data.vault_generic_secret.ca.data, "certificate")
    }
  }
}
```

### Steps to Reproduce

* Apply once
* Run plan or apply

### Would you like to implement a fix?

None

**Comment by senilio** [comment] 2024-09-26 05:52
Likely due to the certificate data not containing a line break at the end. I ran into the same thing, and adding a newline after `----- END CERTIFICATE -----` fixed it for me.

**Comment by bebold-jhr** [comment] 2024-09-26 09:57
Hi @senilio ,
thank you so much! That really did the trick. I suspect that AWS adds a newline on their side causen a constant diff?

**Comment by justinretzolk** [comment] 2024-10-29 22:05
Thank you to both of you for taking the time to raise this, the suggestion of how to fix it, and following up to confirm that the issue was resolved! Since this doesn't appear to be something the AWS Provider team needs to make any modifications for, I'm going to close this out. If you run into any unexpected behavior in the future, please do let us know!

**Closed by justinretzolk** 2024-10-29 22:05 UTC
Labels: bug, needs-triage, service/rolesanywhere
