### ISSUE TITLE
Add support to update tags on 'aws_elasticache_replication_group' resource

### ISSUE THREAD

**Issue by chandniahuja** [hashicorp/terraform-provider-aws#22872] opened 2022-02-01 16:01 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support to update tags on 'aws_elasticache_replication_group' resource

### Affected Resource(s)

* aws_elasticache_replication_group

### More details about the initial problem:

* When a new elasticache replication group is created then it is possible to add tags to it via terraform because it is supported by AWS API behind the scenes (for reference: https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_CreateReplicationGroup.html )
* But when we modify tags on an existing replication group then this action is not supported by AWS API as we can see here (https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_ModifyReplicationGroup.htmll ) 
* I'm aware that this issue has been raised in past for eg: https://github.com/hashicorp/terraform-provider-aws/issues/5366  
But it has been closed saying "Terraform would not be able to support this as it is not supported by AWS."

### Suggested Solution:
I think terraform can still support this. There are two AWS APIs which support adding and removing tags explicitly from replication groups and clusters.
https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_AddTagsToResource.html
https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_RemoveTagsFromResource.html

Whenever there's a change in tags in replication-group or cluster then terraform can call these APIs to update the tags on the resource.

We use Terraform to manage our infrastructure and were facing issues to update tags on our multiple elasticache replication groups. We developed a custom python script by making use of 'AddTagsToResource' and 'RemoveTagsFromResource' APIs and successfully updated tags across all replication groups.

We expect Terraform to add this functionality to bridge the gap.

**Comment by justinretzolk** [comment] 2022-02-01 20:33
Hey @chandniahuja 👋 Thanks for taking the time to submit this issue. It looks like this is a duplicate of #18668. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #18668.

**Closed by justinretzolk** 2022-02-01 20:33 UTC
Labels: enhancement, service/elasticache, needs-triage
