### ISSUE TITLE
[Bug]: data ssm_parameter.value should not be sensitive

### ISSUE THREAD

**Issue by elduds** [hashicorp/terraform-provider-aws#31590] opened 2023-05-26 05:38 UTC
### Terraform Core Version

all

### AWS Provider Version

all

### Affected Resource(s)

aws_ssm_parameter

### Expected Behavior

the `value` attribute of https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ssm_parameter should not be marked as sensitive if the `type` of the parameter is `String`. 

If the `type` is set to `SecureString`, assume the value to be sensitive.

### Actual Behavior

This value is always marked as sensitive, regardless of type. 

This makes planning and debugging far more difficult than it should be for no corresponding value / increase in security.

### Relevant Error/Panic Output Snippet

```shell
❯ terraform plan
data.aws_ssm_parameter.not_sensitive: Reading...
data.aws_ssm_parameter.not_sensitive: Read complete after 1s [id=/parameter/that/is/not/sensitive]

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Output refers to sensitive values
│ 
│   on tf.tf line 5:
│    5: output "all" {
│ 
│ To reduce the risk of accidentally exporting sensitive data that was intended to be only internal, Terraform
│ requires that any root module output containing sensitive data be explicitly marked as sensitive, to confirm your
│ intent.
│ 
│ If you do intend to export this data, annotate the output value as sensitive by adding the following argument:
│     sensitive = true
```

### Terraform Configuration Files

```terraform
data "aws_ssm_parameter" "not_sensitive" {
  name = "/parameter/that/is/not/sensitive"
}

output "all" {
  value       = data.aws_ssm_parameter.not_sensitive.value
  sensitive   = false
  description = "My super-not-secret data"
}
```

### Steps to Reproduce

attempt to plan the above tf code

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ssm_parameter

### Would you like to implement a fix?

None

**Comment by ShathishWarmaS** [comment] 2023-05-26 08:29
output "all" {
  value = data.aws_ssm_parameter.not_sensitive.value
  sensitive = true
}

sensitive = true to the output definition, you confirm that the output contains sensitive data and that you intend to export it. This prevents accidental exposure of sensitive information in Terraform outputs.

**Comment by elduds** [comment] 2023-05-26 08:37
But the output does not contain sensitive data, nor is it ever likely to contain sensitive data. That's what `SecureString` type is for.

**Comment by ShathishWarmaS** [comment] 2023-05-26 08:42
output "all" {
  value          = data.aws_ssm_parameter.not_sensitive.value
  ignore_changes = true
}

gnore_changes = true, you inform Terraform to ignore any modifications to the output value during plan and apply operations. This can help bypass the sensitivity check if you are certain that the output doesn't contain sensitive information.

**Comment by justinretzolk** [comment] 2023-05-26 16:10
Hey @elduds 👋 Thank you for taking the time to raise this! In this case, the sensitivity is defined at the [resource schema level](https://github.com/hashicorp/terraform-provider-aws/blob/b9e8c729f2b6dacaa5a7a90e5fccdc8c9c59f4d2/internal/service/ssm/parameter_data_source.go#L35). This is something that the plugin SDK does not currently support toggling dynamically based on something like whether the `type` is a `String` or `SecureString`.

Interestingly, I've found a feature request on the plugin SDK repository (https://github.com/hashicorp/terraform-plugin-sdk/issues/736) for this exact thing (so much so that the example is precisely what you're calling out here). On that issue, a workaround is called out using the [`nonsensitive()` function](https://developer.hashicorp.com/terraform/language/functions/nonsensitive) to instruct Terraform to remove the sensitive flag.

Given that this is an upstream limitation, and not a bug within the provider, I'll close this issue for now. If you feel I've done this in error, please do let me know.

**Closed by justinretzolk** 2023-05-26 16:10 UTC
Labels: bug, service/ssm, needs-triage

**Comment by elduds** [comment] 2023-05-27 04:12
Awesome, thanks @justinretzolk . I was unaware of `nonsensitive()` so will definitely give that a go in the meantime -- sounds like it does exactly what I need.
