### ISSUE TITLE
[Bug]: aws_rds_cluster resource returns empty resource list when setting manage_master_user_password to true after cluster was created

### ISSUE THREAD

**Issue by anacronxinetd** [hashicorp/terraform-provider-aws#31557] opened 2023-05-24 15:19 UTC
### Terraform Core Version

1.2.9

### AWS Provider Version

4.64.0

### Affected Resource(s)

aws_rds_cluster resource

### Expected Behavior

When setting the manage_master_user_password option to true for the aws_rds_cluster resource resource to true, on initial run  an empty list is returned when configuring the the following attribute as output: aws_rds_cluster.default.master_user As mentioned in: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#secret_arn a list of the the following attributes should be returned:

[master_user_secret](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#master_user_secret)
The master_user_secret configuration block supports the following attributes:

[kms_key_id](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#kms_key_id) - The Amazon Web Services KMS key identifier that is used to encrypt the secret.
[secret_arn](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#secret_arn) - The Amazon Resource Name (ARN) of the secret.
[secret_status](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#secret_status) - The status of the secret. Valid Values: creating | active | rotating | impaired.

### Actual Behavior

An empty list is returned

### Terraform Configuration Files

resource "aws_rds_cluster" "default" {
  cluster_identifier = "aurora-cluster-demo"
  engine = "aurora-mysql"
  engine_version = "8.0.mysql_aurora.3.02.3"
  manage_master_user_password = true
  master_user_secret_kms_key_id = ""
  master_username = "foo"
  backup_retention_period = 5
  preferred_backup_window = "07:00-09:00"
  provider = aws.africa
  db_subnet_group_name = aws_db_subnet_group.default.name
  skip_final_snapshot = true

  serverlessv2_scaling_configuration {
    max_capacity = 12.0
    min_capacity = 0.5
  }
}

resource "aws_rds_cluster_instance" "default" {
  cluster_identifier = aws_rds_cluster.default.id
  instance_class = "db.serverless"
  engine = aws_rds_cluster.default.engine
  engine_version = aws_rds_cluster.default.engine_version
  db_subnet_group_name = aws_db_subnet_group.default.name
}

resource "aws_db_subnet_group" "default" {
  name = join("-",["rds", "sg"])
  subnet_ids = [ "subnet_ids"] --> Replace with list of subnets in VPC
}

output "arn_of_mater_password_secret" {
  value = aws_rds_cluster.default.master_secret.secret_arn"
}

### Steps to Reproduce

1. Deploy cluster with above mentioned template
2. Expected values are returned as output value
3. Update template and set manage_master_user_password to false after cluster has been created and provide a manual password
4. Update template again and set manage_master_user_password to true
5. Empty list returned as output value

### Debug Output

Unable to provide logs

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment] 2023-05-24 21:00
Duplicate of #31519

**Closed by justinretzolk** 2023-05-24 21:00 UTC
Labels: bug, service/rds, needs-triage
