### ISSUE TITLE
aws_cloudwatch_event_target does not trigger SNS topic until edited via AWS console

### ISSUE THREAD

**Issue by headlessme** [hashicorp/terraform-provider-aws#16080] opened 2020-11-08 11:49 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.14.1
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

* aws_cloudwatch_event_target

### Terraform Configuration Files

```hcl
resource "aws_cloudwatch_event_rule" "ecs-service-stopped" {
    name = "ecs-service-stopped"
    description = "Container state change notifications"
    event_pattern = <<PATTERN
    {
      "source": [
        "aws.ecs"
      ],
      "detail-type": [
        "ECS Task State Change",
        "ECS Container Instance State Change"
      ],
      "detail": {
        "clusterArn": [ "<redacted for github>" ],
        "lastStatus": [ "STOPPED" ]
      }
    }
    PATTERN
}

resource "aws_cloudwatch_event_target" "sns" {
    rule = aws_cloudwatch_event_rule.ecs-service-stopped.name
    arn = aws_sns_topic.events.arn
}

```

### Expected Behavior

The CloudWatch events should trigger the SNS topic

### Actual Behavior

SNS topic not triggered

### Steps to Reproduce

1. `terraform apply`
2. Subscribe to the SNS topic (e.g. verified email subscription)
3. Perform some action to trigger the cloud watch event (in the example above kill a task for the specified cluster)
4. Check if the SNS was triggered

### Important Factoids

If I go into the AWS console and edit the event setup (without making any changes) and save it, the SNS topic then works as expected.

**Comment by rafael-queiroz-cko** [comment] 2020-11-17 20:37
having the same issue

**Comment by andreas-venturini** [comment] 2021-05-02 18:28
This is a duplicate of GH-5946. The explanation is given there:

> When setting an SNS topic as a target of a cloudwatch event rule, a policy is needed to be added to the SNS topic in order for cloudwatch events to publish messages to the SNS topic.

**Closed** 2021-08-18 13:57 UTC
Labels: service/cloudwatchevents, service/eventbridge
