### ISSUE TITLE
[Enhancement]: SFN State Machine Addition of Timeouts Block

### ISSUE THREAD

**Issue by novekm** [hashicorp/terraform-provider-aws#29206] opened 2023-02-02 00:16 UTC
### Description

This enhancement would be to add support for the `timeouts` block for the `aws_sfn_state_machine` resource. Sometimes the deletion can take an extended period of time and this causes a timeout error when running `terraform destroy`. I've run into this issue fairly consistently, even for state machines with no running executions. The only solution I've found so far is to wait a while and try to destroy the resource again. 

### Affected Resource(s) and/or Data Source(s)

aws_sfn_state_machine

### Potential Terraform Configuration

```terraform
resource "aws_sfn_state_machine" "sfn_state_machine" {
  name     = "my-state-machine"
  role_arn = aws_iam_role.iam_for_sfn.arn
  
  timeouts {
    delete = "20m" 
  }

  definition = <<EOF
{
  "Comment": "A Hello World example of the Amazon States Language using an AWS Lambda Function",
  "StartAt": "HelloWorld",
  "States": {
    "HelloWorld": {
      "Type": "Task",
      "Resource": "${aws_lambda_function.lambda.arn}",
      "End": true
    }
  }
}
EOF
}
```

### Would you like to implement a fix?

None

**Comment by jasonarewhy** [comment] 2023-04-27 20:41
This appears to be a duplicate of: https://github.com/hashicorp/terraform-provider-aws/issues/27673

**Closed** 2023-05-02 21:20 UTC
Labels: enhancement, service/sfn, timeouts, partner
