### ISSUE TITLE
[Bug]: aws_workspaces_directory does not work in region il-central-1

### ISSUE THREAD

**Issue by meks96** [hashicorp/terraform-provider-aws#39277] opened 2024-09-11 20:25 UTC
### Terraform Core Version

1.9.5

### AWS Provider Version

5.66.0

### Affected Resource(s)

aws_workspaces_directory

### Expected Behavior

The resource must be created, the same code works in other regions

### Actual Behavior

I got an error when I try to create these resources in terraform, but through web ui I can do it.

### Relevant Error/Panic Output Snippet

```shell
Error: registering WorkSpaces Directory (d-*******): operation error WorkSpaces: RegisterWorkspaceDirectory, exceeded maximum number of
attempts, 25, https response error StatusCode: 0, RequestID: , request send failed, Post "https: //workspaces.il-central-1.amazonaws.com/": tl
s: failed to verify certificate: ×509: "workspaces.il-central-1.amazonaws.com" certificate is not standards compliant
```

### Terraform Configuration Files

```hcl
data "aws_availability_zones" "available" {}

provider "aws" {
  region = "il-central-1"

}

resource "aws_directory_service_directory" "example" {
  name     = "corp.example.com"
  password = "#S1ncerely"
  size     = "Small"
  type     = "MicrosoftAD"
  edition  = "Standard"
  vpc_settings {
    vpc_id     = module.vpc.vpc_id
    subnet_ids = module.vpc.public_subnets
  }
}

resource "aws_workspaces_directory" "example" {
  directory_id = aws_directory_service_directory.example.id
  subnet_ids   = module.vpc.public_subnets
  tags = {
    Example = true
  }

}
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 5.7"

  name = "test-vpc"
  cidr = "10.10.0.0/16"
  azs  = data.aws_availability_zones.available.names

  public_subnets      = [for k, v in data.aws_availability_zones.available.names : cidrsubnet("10.10.0.0/16", 8, k)]
  public_subnet_names = [for az in data.aws_availability_zones.available.names : "test-public-${az}"]

  map_public_ip_on_launch = true

  create_database_subnet_group    = false
  create_redshift_subnet_group    = false
  create_elasticache_subnet_group = false

  enable_nat_gateway   = false
  enable_dns_hostnames = true
  enable_dns_support   = true
}
```

### Steps to Reproduce

terraform init
terraform apply

### Would you like to implement a fix?

No

**Comment by meks96** [comment] 2024-09-12 11:23
resource aws_workspaces_workspace also has the same issue in region il-central-1
<img width="1441" alt="image" src="https://github.com/user-attachments/assets/7a9d1a41-17fd-4ef9-b253-ed072ffbdf01">

**Comment by justinretzolk** [comment] 2024-11-04 22:02
Hey @meks96 👋 Thank you for taking the time to raise this! The relevant part of the error message is:

```console
failed to verify certificate: ×509: "workspaces.il-central-1.amazonaws.com" certificate is not standards compliant
```

This tells me that the AWS Provider is attempting to connect to the upstream API, but is having troubles validating the certificate. I've seen this reported in a number of places, many of which seemed to indicate some changes to how certificates are validated on MacOS. Anecdotally, I ran into this error recently (not with Terraform, for what it's worth) with my work computer when one of our fleet management tools failed to load. If this wasn't being caused by a local machine issue, it would have to do with the certificate on the upstream server. Either way, it's not something that the AWS Provider team will need to make modifications to the provider to resolve. With that in mind, I'm going to close this issue. If you encounter any further unexpected behavior, please do let us know!

**Closed by justinretzolk** 2024-11-04 22:02 UTC
Labels: bug, service/ec2, service/workspaces, needs-triage, service/ds
