### ISSUE TITLE
Amazon Macie: Support bucketCriteria

### ISSUE THREAD

**Issue by DimitrisPr** [hashicorp/terraform-provider-aws#20162] opened 2021-07-13 11:02 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Macie2 support for terraform was released based on [this ticket](https://github.com/hashicorp/terraform-provider-aws/issues/13432). The official AWS documentation for Macie states that there are two was to select the S3 buckets that Macie will analyze: either with `bucketDefinitions`, which is currently supported by terraform as seen [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/macie2_classification_job#bucket_definitions) or with [S3BucketCriteriaForJob](https://docs.aws.amazon.com/macie/latest/APIReference/jobs.html#jobs-model-s3bucketcriteriaforjob). BucketCriteria were never added to the initial release.

BucketCriteria are important, for selected S3 buckets dynamically (e.g through Account ID).

### New or Affected Resource(s)

* aws_macie2_classification_job

### Potential Terraform Configuration

```hcl
resource "aws_macie2_account" "member" {}

resource "aws_macie2_classification_job" "member" {
  job_type = "ONE_TIME"
  name     = "S3 PHI Discovery default"
  s3_job_definition {
    bucket_criteria {
      includes {
        and {
          simple_criterion {
            comparator = <ENUM_VALUE> (e.g EQ, STARTS_WITH)
            key = <ENUM_VALUE> (e.g account_id)
            value = <STRING>
          }
        }

      }
    }
  }
  depends_on = [aws_macie2_account.member]
}
```

### References

* https://docs.aws.amazon.com/macie/latest/APIReference/jobs.html#jobs-model-simplecriterionforjob

**Comment by cacack** [comment] 2022-07-15 12:05
Duplicate of #19837

**Closed** 2022-08-08 13:57 UTC
Labels: enhancement, service/macie2
