### ISSUE TITLE
[Enhancement]: Add DNS Name Servers for AWS Database Migration Service (DMS) Replication Instance Resource

### ISSUE THREAD

**Issue by casperfrx** [hashicorp/terraform-provider-aws#37684] opened 2024-05-24 11:35 UTC
### Description

Replication Instances by default use Amazon-provided DNS for resolutions. However you can specificy custom DNS servers to the instance as well. See this Knowledge Center post: https://repost.aws/knowledge-center/dms-endpoint-connectivity-failures

The AWS CLI documentation also mentions this option: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/dms/create-replication-instance.html

Specifically:

> --dns-name-servers (string)
> 
> A list of custom DNS name servers supported for the replication instance to access your on-premise source or target database. This list overrides the default name servers supported by the replication instance. You can specify a comma-separated list of internet addresses for up to four on-premise DNS name servers. For example: "1.1.1.1,2.2.2.2,3.3.3.3,4.4.4.4"

As does the API Reference: https://docs.aws.amazon.com/dms/latest/APIReference/API_CreateReplicationInstance.html#DMS-CreateReplicationInstance-request-DnsNameServers

I've tested this CLI option and it works as expected. Custom DNS servers can be configured to a replication instance and they can then resolve DNS queries without the use of any extra AWS DNS service like Route53 Resolver to forward the DNS queries.

The Key/Value of the JSON returned by `aws dms describe-replication-instances` is `{ ..., "DnsNameServers": "1.1.1.1,2.2.2.2,3.3.3.3,4.4.4.4", ... }`.

Terraform does not yet provide this option. Kindly requesting to add as it would be a great feature to have.

### Affected Resource(s) and/or Data Source(s)

aws_dms_replication_instance

### Potential Terraform Configuration

```terraform
resource "aws_dms_replication_instance" "test" {
  allocated_storage            = 20
  apply_immediately            = true
  auto_minor_version_upgrade   = true
  availability_zone            = "us-west-2c"
  engine_version               = "3.1.4"
  kms_key_arn                  = "arn:aws:kms:us-east-1:123456789012:key/12345678-1234-1234-1234-123456789012"
  multi_az                     = false
  preferred_maintenance_window = "sun:10:30-sun:14:30"
  publicly_accessible          = true
  replication_instance_class   = "dms.t2.micro"
  replication_instance_id      = "test-dms-replication-instance-tf"
  replication_subnet_group_id  = aws_dms_replication_subnet_group.test-dms-replication-subnet-group-tf.id
  dns_name_servers             = "1.1.1.1,2.2.2.2,3.3.3.3,4.4.4.4"

  tags = {
    Name = "test"
  }

  vpc_security_group_ids = [
    "sg-12345678",
  ]

  depends_on = [
    aws_iam_role_policy_attachment.dms-access-for-endpoint-AmazonDMSRedshiftS3Role,
    aws_iam_role_policy_attachment.dms-cloudwatch-logs-role-AmazonDMSCloudWatchLogsRole,
    aws_iam_role_policy_attachment.dms-vpc-role-AmazonDMSVPCManagementRole
  ]
}
```

### References

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/dms/create-replication-instance.html

https://repost.aws/knowledge-center/dms-endpoint-connectivity-failures

https://awscli.amazonaws.com/v2/documentation/api/latest/reference/dms/describe-replication-instances.html

https://docs.aws.amazon.com/dms/latest/APIReference/API_CreateReplicationInstance.html

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-05-24 14:56
Hey @casperfrx 👋 Thanks for taking the time to submit this issue. It looks like this is a duplicate of #35914. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of that one.

**Comment by justinretzolk** [comment] 2024-05-24 14:57
Duplicate of #35914

**Closed by justinretzolk** 2024-05-24 14:57 UTC
Labels: enhancement, needs-triage, service/dms
