### ISSUE TITLE
aws_wafv2_web_acl apply fails when default action changes

### ISSUE THREAD

**Issue by jaypeng2015** [hashicorp/terraform-provider-aws#23423] opened 2022-03-01 06:25 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Related:
- #23390
- 👉 #23423
- #23936
- #23992
- #24386
- #27175
- #27273
- #27479
- #28191
- #28672
- #29012
- #29304
- #30858

### Terraform CLI and Terraform AWS Provider Version

Terraform Cloud runtime v1.1.6
Providers:
- "registry.terraform.io/hashicorp/archive" 2.2.0
- "registry.terraform.io/hashicorp/aws" 4.3.0
- "registry.terraform.io/hashicorp/random" 3.1.0

### Affected Resource(s)

* aws_wafv2_web_acl

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_wafv2_web_acl" "main" {
  count = var.enabled ? 1 : 0

  name  = var.name_prefix
  scope = var.scope

  default_action {
    dynamic "allow" {
      for_each = var.allow_default_action ? [1] : []
      content {}
    }

    dynamic "block" {
      for_each = var.allow_default_action ? [] : [1]
      content {}
    }
  }

  // other config
}
```

### Panic Output

- Plan output:

```
# module.wafv2-cloudfront.module.wafcf.aws_wafv2_web_acl.main[0] will be updated in-place
  ~ resource "aws_wafv2_web_acl" "main" {
        id         = "31fc351b-9585-4089-8c72-9f1742a1c9ee"
        name       = "dev-wafv2-cloudfront"
        tags       = {
            "Name" = "dev-wafv2-cloudfront"
        }
        # (5 unchanged attributes hidden)

      ~ default_action {
          - allow {
            }

          + block {
            }
        }


        # (5 unchanged blocks hidden)
    }
```

- Apply output:
https://gist.github.com/jaypeng2015/0577c4ee07bf314888914e5de75fd1fc

### Expected Behavior

The default action changed from allow to block.

### Actual Behavior

Apply errored.

```
Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ module.wafv2-cloudfront.module.wafcf.aws_wafv2_web_acl.main[0] to include
│ new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for
│ .rule: planned set element
``` 

```
This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Steps to Reproduce

1. `terraform apply`
2. change the variable allow_default_action from true to false
3. `terraform apply`

### Important Factoids

It only errors when configuration changes, if deploying from scratch, no matter the default action is true of false, it will success.

**Comment by rdubya** [comment] 2022-03-29 20:31
I'm seeing this same error when trying to add tags. Version: registry.terraform.io/hashicorp/aws 4.8.0 

Plan:

```
id : "****" # noop
name : "*****" # noop
tags : {  } # update
tags_all : { # create
  environment : "dev" # create
  terraform : "true" # create
}

... 5 unchanged attributes hidden

... 6 unchanged blocks hidden
```

**Comment by eg15** [comment] 2022-10-05 16:40
This is happening to me on the latest AWS provider version 4.33.0 with the latest Terraform 1.3.1.
Changing default_action alone always triggers 2MB long error output.

**Comment by mmaetzler** [comment] 2022-11-04 23:35
FYI: This issues with WAFv2 has been reported multiple times: 

- #23390
- #23423
- #23936
- #23992
- #24386
- #27175
- #27273
- #27479

**Comment by YakDriver** [comment] 2023-07-13 21:16
**NOTE:** I cannot reproduce this error after trying various configurations. _**Let us know**_ if this is still a problem! If we don't hear and can't reproduce, we plan to close this on or around **July 20, 2023**. The evidence suggests this is OBE (ie, fixed in the interim).

For more details see #23992 ([comment](https://github.com/hashicorp/terraform-provider-aws/issues/23992#issuecomment-1634920741)).

**Comment by justinretzolk** [comment] 2023-07-20 17:23
Hi all :wave: As was mentioned above, this issue appears to be fixed when using a minimum Terraform version of 1.4.2 and a minimum AWS Provider version of 4.67.0 (preferably Terraform 1.5.3 or later and AWS Provider 5.8.0 or later). If you experience additional unexpected behaviors with versions that meet these parameters, please open a new issue so that we can investigate further.

**Closed by justinretzolk** 2023-07-20 17:23 UTC
Labels: bug, waiting-response, service/wafv2
