### ISSUE TITLE
[Bug]: aws_rds_global_cluster and aws_rds_cluster resources cycle dependency error for source_db_cluster_identifier and global_cluster_identifier arguments

### ISSUE THREAD

**Issue by catcharbind** [hashicorp/terraform-provider-aws#34871] opened 2023-12-12 02:46 UTC
### Terraform Core Version

1.6.5

### AWS Provider Version

5.30.0

### Affected Resource(s)

aws_rds_global_cluster and aws_rds_cluster

### Expected Behavior

Based on the conditional expression, the _source_db_cluster_identifier_ argument for **aws_rds_global_cluster** resource and _global_cluster_identifier_ argument for **aws_rds_cluster** should be nullified to successfully create the resources while restoring an aurora cluster snapshot.

### Actual Behavior

Terraform throws Cycle dependency error during planning. The only workaround is to comment out the arguments appropriately based on the value of _snapshot_identifier_.

### Relevant Error/Panic Output Snippet

```shell
"cycle: module.aurora.aws_rds_global_cluster.<name> module.aurora.aws_rds_cluster.<name>" error
```

### Terraform Configuration Files

```
# Aurora Global DB 
resource "aws_rds_global_cluster" "globaldb" {
  count                     = var.setup_globaldb ? 1 : 0
  provider                  = aws.primary
  global_cluster_identifier = "${var.identifier}-globaldb"
  engine                    = (var.snapshot_identifier == "") ? var.engine : null
  engine_version            = (var.snapshot_identifier == "") ? (var.engine == "aurora-postgresql" ? var.engine_version_pg : var.engine_version_mysql) : null
  database_name             = (var.snapshot_identifier == "") ? var.database_name : null
  storage_encrypted         = var.storage_encrypted
  # Uncomment the following line for restoring cluster from snapshot. Conditionally specifying null for the argument still creating Terraform Cycle error.
  source_db_cluster_identifier = (var.snapshot_identifier == "") ? null : aws_rds_cluster.primary.arn
  force_destroy             = (var.snapshot_identifier == "") ? null : true

  lifecycle {
    ignore_changes = [source_db_cluster_identifier]
  }
}

resource "aws_rds_cluster" "primary" {
  provider                         = aws.primary
  # Comment the following line for restoring cluster from snapshot. Conditionally specifying null for the argument still creating Terraform Cycle error.
  global_cluster_identifier        = var.setup_globaldb && (var.snapshot_identifier == "") ? aws_rds_global_cluster.globaldb[0].id : null
  cluster_identifier               = "${var.identifier}-${var.region}"
  engine                           = var.engine
  engine_version                   = var.engine == "aurora-postgresql" ? var.engine_version_pg : var.engine_version_mysql
  allow_major_version_upgrade      = var.allow_major_version_upgrade
  availability_zones               = [data.aws_availability_zones.region_p.names[0], data.aws_availability_zones.region_p.names[1], data.aws_availability_zones.region_p.names[2]]
  db_subnet_group_name             = aws_db_subnet_group.private_p.name
  port                             = var.port == "" ? var.engine == "aurora-postgresql" ? "5432" : "3306" : var.port
  database_name                    = var.setup_as_secondary || (var.snapshot_identifier != "") ? null : var.database_name
  # Aurora global DB currently doesnt support master password manager with AWS Secrets Manager
  manage_master_user_password      = !var.setup_globaldb && var.manage_master_user_password ? var.manage_master_user_password : null
  master_user_secret_kms_key_id    = !var.setup_globaldb && var.manage_master_user_password ? aws_kms_key.kms_p[0].arn : null
  master_username                  = var.setup_as_secondary || (var.snapshot_identifier != "") ? null : var.username
  master_password                  = (var.setup_as_secondary || (var.snapshot_identifier != "")) || (!var.setup_globaldb && var.manage_master_user_password) ? null : (var.password == "" ? random_password.master_password.result : var.password)
  db_cluster_parameter_group_name  = aws_rds_cluster_parameter_group.aurora_cluster_parameter_group_p.id
  db_instance_parameter_group_name = var.allow_major_version_upgrade ? aws_db_parameter_group.aurora_db_parameter_group_p.id : null
  backup_retention_period          = var.backup_retention_period
  preferred_backup_window          = var.preferred_backup_window
  #tfsec:ignore:aws-rds-encrypt-cluster-storage-data
  storage_encrypted               = var.storage_encrypted
  kms_key_id                      = var.storage_encrypted ? aws_kms_key.kms_p[0].arn : null
  storage_type                    = var.storage_type
  apply_immediately               = true
  skip_final_snapshot             = var.skip_final_snapshot
  final_snapshot_identifier       = var.skip_final_snapshot ? null : "${var.final_snapshot_identifier_prefix}-${var.identifier}-${var.region}-${random_id.snapshot_id.hex}"
  snapshot_identifier             = var.snapshot_identifier != "" ? var.snapshot_identifier : null
  enabled_cloudwatch_logs_exports = local.logs_set
  tags                            = var.tags
  
  dynamic "serverlessv2_scaling_configuration" {
    for_each = var.instance_class == "db.serverless" ? [local.serverlessv2_scaling_configuration] : []

    content {
      max_capacity = serverlessv2_scaling_configuration.value.max_capacity
      min_capacity = serverlessv2_scaling_configuration.value.min_capacity
    }
  }

  depends_on = [
    # When this Aurora cluster is setup as a secondary, setting up the dependency makes sure to delete this cluster 1st before deleting current primary Cluster during terraform destroy
    # Comment out the following line if this cluster has changed role to be the primary Aurora cluster because of a failover for terraform destroy to work
    # aws_rds_cluster_instance.secondary,
  ]
  
  lifecycle {
    ignore_changes = [
      replication_source_identifier,
      global_cluster_identifier,
      snapshot_identifier,
      # Since Terraform doesn't allow to conditionally specify a lifecycle policy, this can't be done dynamically.
      # Uncomment the following line for Aurora Global Database to do major version upgrade as per https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_global_cluster
      engine_version,
    ]
  }
}

#tfsec:ignore:aws-rds-enable-performance-insights-encryption tfsec:ignore:aws-rds-enable-performance-insights
resource "aws_rds_cluster_instance" "primary" {
  count                        = var.primary_instance_count
  provider                     = aws.primary
  identifier                   = "${var.name}-${var.region}-${count.index + 1}"
  cluster_identifier           = aws_rds_cluster.primary.id
  engine                       = aws_rds_cluster.primary.engine
  engine_version               = var.engine == "aurora-postgresql" ? var.engine_version_pg : var.engine_version_mysql
  auto_minor_version_upgrade   = var.setup_globaldb ? false : var.auto_minor_version_upgrade
  instance_class               = var.instance_class
  db_subnet_group_name         = aws_db_subnet_group.private_p.name
  db_parameter_group_name      = aws_db_parameter_group.aurora_db_parameter_group_p.id
  performance_insights_enabled = true
  monitoring_interval          = var.monitoring_interval
  monitoring_role_arn          = aws_iam_role.rds_enhanced_monitoring.arn
  apply_immediately            = true
  tags                         = var.tags
}
```

### Steps to Reproduce

When _var.snapshot_identifier_ is an empty string "" the above throws a cycle error. When _var.snapshot_identifier_ is a valid snapshot ARN, then also the above throws a cycle error. _var.setup_globaldb_ is set to true in both the cases.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-01-23 22:10
Hey @catcharbind 👋 Thank you for taking the time to raise this! The AWS Provider isn't able to influence the dependency graph; that's handled by the Terraform Core, so you'd want to open an issue in [that repository](https://github.com/hashicorp/terraform) for things related to that.

I was able to make a simple reproduction (not involving the AWS Provider), which I'll leave below. With it, I'm almost certain this has to do with the order that Terraform evaluates the configuration in, so it may be worth asking in the [Terraform forum](https://discuss.hashicorp.com/c/terraform-core/27) before opening an issue in that repo. Since this isn't related to the AWS Provider itself, I'll be closing this issue.

```terraform
variable "boolean" {
  default = true
}

resource "random_pet" "one" {
  prefix = var.boolean ? "one" : random_pet.two.id
}

resource "random_pet" "two" {
  prefix = var.boolean ? random_pet.one.id : "two"
}

```

```console
$ terraform validate
│ Error: Cycle: random_pet.two, random_pet.one
```

**Closed by justinretzolk** 2024-01-23 22:10 UTC
Labels: bug, service/rds, needs-triage
