### ISSUE TITLE
terraform apply not deploying all the resources specified at the same time

### ISSUE THREAD

**Issue by Victor-Agali** [hashicorp/terraform-provider-aws#30386] opened 2023-03-31 18:45 UTC
### Description

Hi guys,

I am trying to deploy AWS Glue crawler with a role and two attached policies and glue database. While deploying it deploys the the role and policies only for the first time and it fails. During the second attempt, it deploys the crawler successfully. It should deploy all the resources ideally.

Please find the terraform below

**iam.tf**
```
resource aws_glue_crawler glue_crawler {
  database_name =  "database_name"
  name          =  "aws-crawler"
  role          =  aws_iam_role.iam_role.name
  configuration = jsonencode(
    {
      "Version"       = 1.0,
      "CrawlerOutput"   = {
        "Partitions"  = { "AddOrUpdateBehavior" = "InheritFromTable"}
      },

     Grouping          =     { TableLevelConfiguration = 6 }
    }
  )

  schema_change_policy {
    update_behavior   = var.update_behaviour
    delete_behavior   = var.delete_behaviour
  }

  s3_target {
    path = "s3://test-bucket"
  }

  recrawl_policy {
    recrawl_behavior  = var.recrawl_behaviour
  }
}

provider "aws" {
  region = "eu-west-1"
}

terraform {
  backend "s3" {
    aws = {
      source = "hashicorp/aws"
      version = "= 4.60.0"
    }
  }
  required_version = ">=1.0.0"
}

 IAM - Role
resource aws_iam_role iam_role {
  name               = "${var.environment}-iam-role"
  assume_role_policy = templatefile("templates/iam_role.json", {
    environment      = var.environment
  })
}

resource aws_iam_policy policy {
  name = "${var.environment}-iam-policy"
  policy = templatefile("templates/iam_policy.json", {
    environment   : var.environment
  })
}


# Lambda IAM - Policy Attachment
resource aws_iam_role_policy_attachment iam_policy_attachment_1 {
  role              = aws_iam_role.iam_role.name
  policy_arn        = aws_iam_policy.policy.arn
}

# Lambda IAM - Policy Attachment
resource aws_iam_role_policy_attachment iam_policy_attachment_2 {
  role              = aws_iam_role.iam_role.name
  policy_arn        = "arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole"
}
```

**main.tf**
```
module iam {
  source         = "./modules/iam"
  environment    = var.environment
  aws_account_id = local.aws_account_id
  s3_location    = var.s3_location
  kms_key        = data.aws_kms_key.lakehouse_landing_zone_key.arn
  glue_iam_role  = module.iam.glue_iam_role
}


module glue_database {
  source         = "./modules/database"
  environment    = var.environment
  glue_database  = var.glue_database_name
}

module aws_glue_crawler {
  source         = "./modules/iam"
  crawler_name   = "aws-crawler"
  database_name  = "module.glue_database.glue_database"
  environment    = var.environment
  glue_iam_role  = module.iam.glue_iam_role
  glue_iam_policy = module.iam.policy
  s3_location    = var.s3_location
  s3_target      = {
    path = "s3://test-bucket"
  }
}
```

**Terraform version**

➜ terraform --version
```
Terraform v1.4.2
on darwin_arm64
```

Expected behaviour
Apply complete! Resources: 6 added, 0 changed, 0 destroyed.

Actual behaviour
Failed with error

```
 Error: creating Glue Crawler (aws-crawler): InvalidInputException: Service is unable to assume provided role. Please verify role's TrustPolicy
│ 
│   with module.aws_glue_crawler.aws_glue_crawler.glue_crawler,
│   on .terraform/modules/aws_glue_crawler/modules/iam.tf line 1, in resource "aws_glue_crawler" "glue_crawler":
│    1: resource aws_glue_crawler glue_crawler {
│ 
╵
```

### Would you like to implement a fix?

None

**Comment by gdavison** [comment] 2023-05-11 21:06
Duplicate of #30389

**Closed by gdavison** 2023-05-11 21:06 UTC
Labels: service/iam, service/glue
