### ISSUE TITLE
[Bug]: No tags are printed in plan when one tag contains a value "known after apply"

### ISSUE THREAD

**Issue by ZeBidule** [hashicorp/terraform-provider-aws#36377] opened 2024-03-14 14:11 UTC
### Terraform Core Version

1.7.5

### AWS Provider Version

5.40.0

### Affected Resource(s)

all

### Expected Behavior

S3 bucket tags should be defined at plan, except for the one that use a resource defined at the apply (volumeUID in the log below). It is important to do code lint in the CI (like checkov) to verify the tag compliance.

```
Terraform will perform the following actions:

  # aws_s3_bucket.test will be created
  + resource "aws_s3_bucket" "test" {
      + acceleration_status         = (known after apply)
      + acl                         = (known after apply)
      + arn                         = (known after apply)
      + bucket                      = "gtp.testagu"
      + bucket_domain_name          = (known after apply)
      + bucket_prefix               = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = true
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + object_lock_enabled         = (known after apply)
      + policy                      = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + tags                        = {
          + "tag1"      = "tag1"
          + "tag2"      = "tag2"
          + "volumeUID" =  (known after apply)
        }
      + tags_all                    = {
          + "tag1"      = "tag1"
          + "tag2"      = "tag2"
          + "volumeUID" =  (known after apply)
        }
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)
    }

  # random_string.id will be created
  + resource "random_string" "id" {
      + id          = (known after apply)
      + length      = 12
      + lower       = true
      + min_lower   = 0
      + min_numeric = 0
      + min_special = 0
      + min_upper   = 0
      + number      = true
      + numeric     = true
      + result      = (known after apply)
      + special     = false
      + upper       = true
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + random_value = (known after apply)
  + volume_tag   = {
      + tag1      = "tag1"
      + tag2      = "tag2"
      + volumeUID = (known after apply)
    }
```

### Actual Behavior

S3 bucket tags are known after apply :

```
Terraform will perform the following actions:

  # aws_s3_bucket.test will be created
  + resource "aws_s3_bucket" "test" {
      + acceleration_status         = (known after apply)
      + acl                         = (known after apply)
      + arn                         = (known after apply)
      + bucket                      = "gtp.testagu"
      + bucket_domain_name          = (known after apply)
      + bucket_prefix               = (known after apply)
      + bucket_regional_domain_name = (known after apply)
      + force_destroy               = true
      + hosted_zone_id              = (known after apply)
      + id                          = (known after apply)
      + object_lock_enabled         = (known after apply)
      + policy                      = (known after apply)
      + region                      = (known after apply)
      + request_payer               = (known after apply)
      + tags                        = (known after apply)
      + tags_all                    = (known after apply)
      + website_domain              = (known after apply)
      + website_endpoint            = (known after apply)
    }

  # random_string.id will be created
  + resource "random_string" "id" {
      + id          = (known after apply)
      + length      = 12
      + lower       = true
      + min_lower   = 0
      + min_numeric = 0
      + min_special = 0
      + min_upper   = 0
      + number      = true
      + numeric     = true
      + result      = (known after apply)
      + special     = false
      + upper       = true
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + random_value = (known after apply)
  + volume_tag   = {
      + tag1      = "tag1"
      + tag2      = "tag2"
      + volumeUID = (known after apply)
    }
```

### Terraform Configuration Files

```terraform
resource "random_string" "id" {
  length  = 12
  special = false
}

locals {
  volumeID = random_string.id.result
  name     = "Name"
  id       = "id"
  tags = {
    tag1 = "tag1"
    tag2 = "tag2"
  }
}

output "random_value" {
  value = random_string.id.result
}

output "volume_tag" {
  value = merge(
    local.tags,
    {
      "volumeUID" = "${local.tags["tag1"]}-${local.id}-${local.volumeID}"
    }
  )
}

provider "aws" {
  region  = "eu-central-1"
  profile = "target"

  default_tags {
    tags = local.tags
  }
}

resource "aws_s3_bucket" "test" {
  bucket        = "gtp.testagu"
  force_destroy = true
  tags = merge(
    local.tags,
    {
      "volumeUID" = "${local.tags["tag1"]}-${local.id}-${local.volumeID}"
    }
  )
}
```

### Steps to Reproduce

terraform init
terraform plan

### Important Factoids

If you remove `-${local.volumeID}` from S3 bucket tags, the tags are printed correctly in plan output :
```
+ tags                        = {
          + "tag1"      = "tag1"
          + "tag2"      = "tag2"
          + "volumeUID" = "tag1-id-"
        }
      + tags_all                    = {
          + "tag1"      = "tag1"
          + "tag2"      = "tag2"
          + "volumeUID" = "tag1-id-"
        }
```

### Would you like to implement a fix?

No

**Comment by ZeBidule** [comment] 2024-03-15 07:54
For information, we have the same behavior for EBS and probably all other resources

**Comment by justinretzolk** [comment] 2024-03-20 21:14
Hey @ZeBidule 👋 Thank you for taking the time to raise this! I spoke with the team about this and determined that this is expected behavior. The gist of it is that fully known tags and computed tags are applied at different stages during an apply. Fully known tags are applied during the `create` handler and before any `update` to a resource. Computed tags are always applied after the the `create` or `update` because we need to know what their values. Tags are also applied on an all or nothing basis, so if one tag in the block is computed, all of them will be marked as `(known after apply)` as you saw, so they are applied at the same time. 

Since this is expected behavior and not something that we can further action, closing.

**Closed by justinretzolk** 2024-03-20 21:14 UTC
Labels: bug, service/s3, needs-triage
