### ISSUE TITLE
[New Data Source]][Kendra]: Only supports S3 and WebCrawler configuration, missing SHAREPOINT, TEMPLATE, ALFRESCO,... 

### ISSUE THREAD

**Issue by daniel-romera-clariant** [hashicorp/terraform-provider-aws#35767] opened 2024-02-12 14:58 UTC
### Description

According to the documentation:

We can have multiple kendra datasource types according to AWS documentation:

Valid Values: S3 | SHAREPOINT | DATABASE | SALESFORCE | ONEDRIVE | SERVICENOW | CUSTOM | CONFLUENCE | GOOGLEDRIVE | WEBCRAWLER | WORKDOCS | FSX | SLACK | BOX | QUIP | JIRA | GITHUB | ALFRESCO | TEMPLATE

But only 2 of them (S3 and WEBCRAWLER) are supported by the current resource:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kendra_data_source#configuration-block

### Requested Resource(s) and/or Data Source(s)

aws_kendra_data_source

### Potential Terraform Configuration

```terraform
resource "aws_kendra_data_source" "sharepoint" {
  index_id = "abcdefghi-01ab-12ab-34cd-f2g6u4214g752"
  name     = "Sharepoint-datasource"
  type     = "SHAREPOINT"
  configuration {
    # This block is not allowed right now 
    sharepoint_configuration {
      sharepoint_version  = "2"
      urls                = ["https://xxxxx.sharepoint.com/sites/Test"]
      secret_arn          = "arn:aws:eu-central-1:secret/Secret"
      authentication_type = "OAUTH2"
    }
  }
}
```

### References

https://docs.aws.amazon.com/kendra/latest/APIReference/API_CreateDataSource.html#API_CreateDataSource_RequestSyntax

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-02-12 20:59
Duplicate of #29922

**Closed by justinretzolk** 2024-02-12 20:59 UTC
Labels: needs-triage, service/kendra
