### ISSUE TITLE
[New]: 

### ISSUE THREAD

**Issue by meetreks** [hashicorp/terraform-provider-aws#30394] opened 2023-04-01 21:07 UTC
### Description

VPC Lattice was introduced my Amazon during re:Invent 2022 -- https://aws.amazon.com/about-aws/whats-new/2022/11/aws-announces-amazon-vpc-lattice-preview/

The service recently went GA in a couple of regions - https://aws.amazon.com/about-aws/whats-new/2023/03/general-availability-amazon-vpc-lattice/

This request is to enable terraform support for this new service. 

### Requested Resource(s) and/or Data Source(s)

<html>
<body>

**Resource**
--
aws_vpc_lattice_service
aws_vpc_lattice_service_network
awc_vpc_lattice_service_network_association
aws_vpc_lattice_network_vpc_association
aws_vpc_lattice_batch_update_rule
aws_vpc_lattice_access_log_subscription
aws_vpc_lattice_target_group
aws_vpc_lattice_listener
aws_vpc_lattice_listener_rule

**Data Resource**
aws_vpc_lattice_auth_policy
aws_vpc_lattice_access_log_subscription
aws_vpc_lattice_listeners
aws_vpc_lattice_resource_policy
aws_vpc_lattice_rules
aws_vpc_lattice_service
aws_vpc_lattice_service_networks
aws_vpc_lattice_service_network_associations
aws_vpc_lattice_service_network_vpc_associations

</body>
</html>

### Potential Terraform Configuration

```terraform
resource "aws_vpclattice_servicenetwork" "example" {
  auth_type 	= "AWS_IAM"
  client_token    = "svc_eng_1"
  name		= "example"

}

resource "aws_vpclattice_service" "example" {
  auth_type 		= "AWS_IAM"
  certificate_arn	      = "aws::arn::"
  client_token  	      = "svc_eng_1"
  custom_domain_name	= ""
  name			= "example"

}

resource "aws_vpclattice_networkservice_associations" "example" {
  client_token  		      = "svc_eng_1"
  service_identifier		= aws_vpclattice_service.example.id
  service_network_identifier	= aws_vpclattice_servicenetwork.example.id
  
}

resource "aws_vpclattice_networkservice_vpcassociations" "example" {
  client_token  		      = "svc_eng_1"
  security_group_ids		= [aws_security_group.test.id]
  service_network_identifier	= aws_vpclattice_servicenetwork.example.id
  vpc_identifier		      = aws_vpc.test.id
```

### References

https://aws.amazon.com/blogs/aws/simplify-service-to-service-connectivity-security-and-monitoring-with-amazon-vpc-lattice-now-generally-available/

### Would you like to implement a fix?

Yes

**Comment by mattburgess** [comment] 2023-04-03 11:19
Duplicate of #30380

**Closed by mattburgess** 2023-04-03 11:19 UTC
Labels: service/vpc
