### ISSUE TITLE
[Enhancement]: Error when retrieving policy for S3 bucket when the S3 bucket does not have a policy attached to it.

### ISSUE THREAD

**Issue by adipaulo** [hashicorp/terraform-provider-aws#35818] opened 2024-02-14 19:59 UTC
### Terraform Core Version

1.7.0

### AWS Provider Version

5.36.0

### Affected Resource(s)

data "aws_s3_bucket_policy"

### Expected Behavior

if no policy it should return empty but not error

### Actual Behavior

 Error: reading S3 Bucket (bucket) Policy: couldn't find resource

### Relevant Error/Panic Output Snippet

```shell
data "aws_s3_bucket_policy" "existing_bucket_policy" {
  bucket = var.s3_bucket_name
}

│ Error: reading S3 Bucket (bucket name) Policy: couldn't find resource
```

### Terraform Configuration Files

N/A

### Steps to Reproduce

Target S3 bucket should have NO policy attached to it to replicate this issue.

data "aws_s3_bucket_policy" "existing_bucket_policy" {
  bucket = var.s3_bucket_name
}

output "s3_bucket_existing_policies" {
  value = data.aws_s3_bucket_policy.existing_bucket_policy
}

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-02-14 20:24
Hey @adipaulo 👋 Thanks for taking the time to raise this! For now, I'd say that this is working as expected and is in line with how many other data sources within the AWS provider behave (the [`aws_instance` data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/instance), for example, errors if anything other than exactly one instance is returned). 

With that in mind, I'm going to swap the `bug` label for `enhancement`, since this is more of a request for a behavioral change. I'll leave this open, to gather community feedback until it can be [prioritized](https://hashicorp.github.io/terraform-provider-aws/prioritization/) and reviewed by someone on the team.

**Comment by justinretzolk** [comment] 2024-02-15 16:26
Hey @adipaulo 👋 I've discussed this with the team internally and verified that this is the expected behavior that we're not currently open to changing. With that in mind, we'll close this issue. If you have any future suggestions or problems with the provider, please do let us know!

**Closed by justinretzolk** 2024-02-15 16:26 UTC
Labels: enhancement, service/s3
