### ISSUE TITLE
[New]: aws_imagebuilder_lifecycle_policy

### ISSUE THREAD

**Issue by lvthillo** [hashicorp/terraform-provider-aws#34874] opened 2023-12-12 09:54 UTC
### Description

[AWS released the possibility to add lifecycle policies to manage AMIs/Container images created by AWS Image Builder](https://aws.amazon.com/about-aws/whats-new/2023/11/ec2-image-builder-lifecycle-management-deletion/).

It's also released in [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-imagebuilder-lifecyclepolicy.html) and the [Go SDK](https://docs.aws.amazon.com/sdk-for-go/api/service/imagebuilder/#Imagebuilder.CreateLifecyclePolicy)

### Requested Resource(s) and/or Data Source(s)

* aws_imagebuilder_lifecycle_policy (both resource and data source)

### Potential Terraform Configuration

```terraform
resource "aws_imagebuilder_lifecycle_policy" "example" {
  description    = "Your lifecycle policy description"
  execution_role = "arn:aws:iam::account-id:role/execution-role"
  name           = "YourLifecyclePolicyName"
  policy_details = [
    {
      "action"     = "action-name",
      "parameters" = {
        "param-key" = "param-value",
      },
    },
  ]
  resource_selection {
    include_expression {
      filters = {
        filter-name = "filter-value",
      }
    }
    tag_filter {
      key    = "tag-key"
      values = ["tag-value"]
    }
    variable_tags {
      key    = "variable-tag-key"
      values = ["variable-tag-value"]
    }
  }
  resource_type = "<AMI_IMAGE | CONTAINER_IMAGE>"
  status        = "ENABLED"
  tags          = {
    key = "value"
  }
}
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2023-12-12 20:33
Duplicate of #34854

**Closed by justinretzolk** 2023-12-12 20:33 UTC
Labels: needs-triage, service/imagebuilder
