### ISSUE TITLE
Add support for log delivery in aws_elasticache_replication_group resource

### ISSUE THREAD

**Issue by marcincuber** [hashicorp/terraform-provider-aws#19908] opened 2021-06-21 09:38 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for publishing Redis logs to Amazon CloudWatch Logs and Kinesis Data Firehose

### New or Affected Resource(s)

* aws_elasticache_replication_group

### Potential Terraform Configuration

Using CLI you would have `log-delivery-configurations` flag

```bash 
aws elasticache modify-replication-group \
    --replication-group-id test-slow-log \
    --apply-immediately \
    --log-delivery-configurations '
    {
      "LogType":"slow-log", 
      "DestinationType":"cloudwatch-logs", 
      "DestinationDetails":{ 
        "CloudWatchLogsDetails":{ 

          "LogGroup":"my-log-group"
        } 
      },
      "LogFormat":"json" 
    }'
```

### References

* https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Log_Delivery.html

**Comment by 0x91** [comment] 2022-01-13 01:31
dupe of #20023

**Closed** 2022-12-14 17:56 UTC
Labels: enhancement, service/elasticache
