### ISSUE TITLE
How do you enable RDS (PostgreSQL)cross-region automated backups when you launch the instance using Terraform ?

### ISSUE THREAD

**Issue by yedusurendran** [hashicorp/terraform-provider-aws#23399] opened 2022-02-26 12:48 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by yedusurendran** [comment] 2022-02-26 12:56
When this option will be available with resource aws_db_instance ?

**Comment by justinretzolk** [comment] 2022-03-15 20:25
Thanks for taking the time to submit this issue. It looks like this is a duplicate of #16708. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #16708. As a note, as noted in https://github.com/hashicorp/terraform-provider-aws/issues/16708#issuecomment-1029034480, this is on the roadmap for this quarter.

**Closed by justinretzolk** 2022-03-15 20:25 UTC
Labels: needs-triage
