### ISSUE TITLE
[Bug]: aws_transfer_user expect user to be provided conflicts with IdP type: AWS_LAMBDA

### ISSUE THREAD

**Issue by khvalov** [hashicorp/terraform-provider-aws#38435] opened 2024-07-19 17:40 UTC
### Terraform Core Version

v1.9.2

### AWS Provider Version

v4.67.0

### Affected Resource(s)

aws_transfer_user

### Expected Behavior

SFTP server should be created

### Actual Behavior

```console
Missing required argument │  │   on main.tf line 316, in resource "aws_transfer_user" "sftp_user": │  316: resource "aws_transfer_user" "sftp_user" { │  │ The argument "user_name" is required, but no definition was found.
```

### Relevant Error/Panic Output Snippet

```console
Missing required argument │  │   on main.tf line 316, in resource "aws_transfer_user" "sftp_user": │  316: resource "aws_transfer_user" "sftp_user" { │  │ The argument "user_name" is required, but no definition was found.
```

### Terraform Configuration Files

```hcl
resource "aws_transfer_user" "sftp_user" {
  server_id = aws_transfer_server.sftp_server.id
  role = aws_iam_role.sftp_transfer_role.arn
  #user_name = "fake" //NOT REQURED
  home_directory = "/${var.s3_bucket_name}/home"
}
```

### Steps to Reproduce

```hcl
resource "aws_transfer_user" "sftp_user" {
  server_id = aws_transfer_server.sftp_server.id
  role = aws_iam_role.sftp_transfer_role.arn
  home_directory = "/${var.s3_bucket_name}/home"
}
```

### Important Factoids

Creating SFTP endpoint with LAMBDA function as User Auth handler

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-07-24 16:32
Hey @khvalov 👋 Thank you for taking the time to raise this! In reviewing the documentation for `aws_transfer_user`, I noticed that the [`user_name` argument](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/transfer_user#user_name) is indeed marked as required. I went to verify this requirement with the [upstream API documentation](https://docs.aws.amazon.com/transfer/latest/userguide/API_CreateUser.html) and noticed the following note (emphasis mine):

> Creates a user and associates them with an existing file transfer protocol-enabled server. **You can only create and associate users with servers that have the `IdentityProviderType` set to `SERVICE_MANAGED`.**

With that information (and that the upstream API requires the `UserName` parameter), this seems to be working as expected, so I'm going to close this issue. If you experience unexpected behavior in the future, please do let us know!

**Closed by justinretzolk** 2024-07-24 16:32 UTC
Labels: bug, service/transfer, needs-triage
