### ISSUE TITLE
[Bug]: Kinesis analytics v2 application recreates after change of runtime_envrionment && ConcurrentModificationException

### ISSUE THREAD

**Issue by Sagoito** [hashicorp/terraform-provider-aws#37529] opened 2024-05-15 10:50 UTC
### Terraform Core Version

1.6.6

### AWS Provider Version

5.48.0

### Affected Resource(s)

* aws_kinesisanalyticsv2_application

### Expected Behavior

After the kinesis configuration runtime_environment is changed it should trigger an update for the existing kinesis application.

### Actual Behavior

Terraform deletes the kinesisanalitycsv2 application and creates a new one with the same name, which resolves in ConcurrentModificationException.

### Relevant Error/Panic Output Snippet

```shell
Error: creating Kinesis Analytics v2 Application (app_name): ConcurrentModificationException: Tags are already registered for this resource ARN: arn:aws:kinesisanalytics:region:accountid:application/app_name, please retry later. Or you can create without tags and then add tags using TagResource API after successful resource creation.
with aws_kinesisanalyticsv2_application.app,
on kinesisV2.tf line 14, in resource "aws_kinesisanalyticsv2_application" "app":
14: resource "aws_kinesisanalyticsv2_application" "app" {
```

### Terraform Configuration Files

```
provider "aws" {
  region  = "us-east-1"
  default_tags {
    tags = {
      TestTag = "test-tag"
    }
  }
}

resource "aws_kinesisanalyticsv2_application" "app" {
  name                   = "app_name"
  service_execution_role = aws_iam_role.kinesis_application.arn

  start_application   = true
  runtime_environment = "FLINK-1_15"

  application_configuration {
    run_configuration {
      flink_run_configuration {
        allow_non_restored_state = true
      }
    }
    application_code_configuration {
      code_content {
        s3_content_location {
          bucket_arn = aws_s3_bucket.kinesis_application_bucket.arn
          file_key   = aws_s3_object.kinesis_application_jar.key
        }
      }
      code_content_type = "ZIPFILE"
    }
    application_snapshot_configuration {
      snapshots_enabled = true
    }

    flink_application_configuration {
      parallelism_configuration {
        auto_scaling_enabled = true
        configuration_type   = "CUSTOM"
        parallelism          = 1
        parallelism_per_kpu  = 1
      }
    }
  }
}
```

### Steps to Reproduce

Create a terraform stack on aws with the kinesis analytics v2 application using runtime_environment = "FLINK-1_15".
Modify the Terraform file and change the version of runtime_environment to runtime_environment = "FLINK-1_18".
Run the plan and apply again.

### Important Factoids

The issue with ConcurrentModificationException is described in #31239, but the expected behavior is incorrect as it states that  "Terraform should delete the existing AWS Kinesis Analytics application and create a new application with the new runtime environment."
In case of changing runtime_environment the update of the application should be performed instead of recreating application. In aws-sdk-go-v2 application runtime environment update can be performed via [func (c *Client) UpdateApplication(ctx context.Context, params *UpdateApplicationInput, optFns ...func(*Options)) (*UpdateApplicationOutput, error)](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/kinesisanalyticsv2#Client.UpdateApplication)

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-05-24 15:33
Hey @Sagoito 👋 Thank you for taking the time to raise this! In this case, I'm going to mark this as a duplicate of #31239 and close this in favor of continuing the conversation there. My reasoning being that the `kinesisanalyticsv2` service has not yet been migrated to AWS Go SDKv2 (see #36176), and so the update behavior that you mentioned is not yet expected.

**Comment by justinretzolk** [comment] 2024-05-24 15:33
Duplicate of #31239

**Closed by justinretzolk** 2024-05-24 15:33 UTC
Labels: bug, service/kinesisanalyticsv2, needs-triage
