### ISSUE TITLE
[New Data Source]: aws_identitystore_users

### ISSUE THREAD

**Issue by miki725** [hashicorp/terraform-provider-aws#40016] opened 2024-11-05 18:05 UTC
### Description

Currently there is already `aws_identitystore_user` data source however it can only query for a specific user whereas AWS supports querying multiple users via list-users:

https://docs.aws.amazon.com/cli/latest/reference/identitystore/list-users.html

would be nice if same resource will be exposed in the aws provider

### Requested Resource(s) and/or Data Source(s)

* `aws_identitystore_users`

### Potential Terraform Configuration

```terraform
data "aws_ssoadmin_instances" "example" {}

data "aws_identitystore_users" "example" {
  identity_store_id = tolist(data.aws_ssoadmin_instances.example.identity_store_ids)[0]
}
```

it can then expose an attribute `users` which will have similar shape as attributes of `aws_identitystore_user` data source.

### References

https://docs.aws.amazon.com/cli/latest/reference/identitystore/list-users.html

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment] 2024-11-05 18:21
Hey @miki725  👋 Thanks for taking the time to submit this issue. It looks like this is a duplicate of #39859. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of that one.

**Comment by justinretzolk** [comment] 2024-11-05 18:21
Duplicate of #39859

**Comment by miki725** [comment] 2024-11-05 18:22
oh. I swear I tried looking for existing ticket but could not find one

**Closed by justinretzolk** 2024-11-05 18:21 UTC
Labels: needs-triage, service/identitystore, service/ssoadmin
