### ISSUE TITLE
Don't mark non SecureString SSM parameters as sensitive

### ISSUE THREAD

**Issue by tdmalone** [hashicorp/terraform-provider-aws#9090] opened 2019-06-22 02:55 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Plans including changes to `aws_ssm_parameter` values currently mask the changes, due to the `value` field being [defined as sensitive](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_ssm_parameter.go#L58).

SSM parameters support a `type` param to define whether a value is a `String` or a `SecureString`.

Would it be possible for `value` to only be considered sensitive if `type == "SecureString"`? This would make it easier to grok planned changes of non-secret configuration values without needing to manually verify the changes outside of Terraform.

### Terraform Version

```
Terraform v0.11.14
+ provider.aws v2.16.0
```

### Affected Resource(s)

* [aws_ssm_parameter](https://www.terraform.io/docs/providers/aws/r/ssm_parameter.html)

### Terraform Configuration Files

```hcl
resource "aws_ssm_parameter" "test_normal" {
  name  = "/test/normal"
  type  = "String"
  value = "public info"
}

resource "aws_ssm_parameter" "test_secure" {
  name  = "/test/secure"
  type  = "SecureString"
  value = "something really secret"
}
```

### Expected Behavior

```
Terraform will perform the following actions:

  ~ aws_ssm_parameter.test_normal
      value: "public information" => "public info"

  ~ aws_ssm_parameter.test_secure
      value: <sensitive> => <sensitive> (attribute changed)

Plan: 0 to add, 2 to change, 0 to destroy.
```

### Actual Behavior

```
Terraform will perform the following actions:

  ~ aws_ssm_parameter.test_normal
      value: <sensitive> => <sensitive> (attribute changed)

  ~ aws_ssm_parameter.test_secure
      value: <sensitive> => <sensitive> (attribute changed)

Plan: 0 to add, 2 to change, 0 to destroy.
```

### Steps to Reproduce

1. Set up the config as provided above
1. `terraform apply`
1. Make changes to the values in each parameter
1. `terraform plan`
1. Observe that the value for the `type = String` parameter is masked

**Comment by tdmalone** [comment] 2020-06-13 04:10
Possible workaround (won't be suitable for all circumstances): duplicate the value as a tag.

eg.
```
locals {
  test_normal_value = "public info"
}

resource "aws_ssm_parameter" "test_normal" {
  name  = "/test/normal"
  type  = "String"
  value = local.test_normal_value

 tags = {
    value = local.test_normal_value
 }
}
```

While `value` is still marked `<sensitive>` in the plan, `tags.value` is not, and thus you can still see the change you will be applying.

**Comment by mrwacky42** [comment] 2020-09-10 17:14
I see the `value` is unconditionally flagged as `Sensitive: true`. Is it possible to change the schema to have non-secret Parameters to `Sensitive: false`? I do not see anywhere in the provider where the value for `Sensitive` is conditional on other aspects of the schema.

https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_ssm_parameter.go#L63-L66

**Comment by izrobin** [comment] 2021-03-17 10:52
Bumping this, since it seems like nothing has happened for quite a while. I was surprised to see regular string parameters marked as "sensitive" today. They shouldn't be. The idea of parameter store is to store variables that are different per account, environment, or region. If you need to store secrets, it should be using `SecureString`

**Comment by zachwhaley** [comment] 2021-04-08 14:22
This is causing an error with Terraform 0.15

I have a "String" SSM parameter whose value is used in an output value.  With Terraform 0.14 this worked, but with Terraform 0.15 it fails with the following message: 

```
╷
│ Error: Output refers to sensitive values
│
│   on outputs.tf line 1:
│    1: output "deployment_color" {
│
│ Expressions used in outputs can only refer to sensitive values if the
│ sensitive attribute is true.
╵
```

**Comment by bflad** [comment] 2021-04-12 23:04
Hi @zachwhaley 👋  A fix to the `nonsensitive()` function has been merged upstream in Terraform CLI and will release with version 0.15.0 to fix this use case. You can bypass the sensitivity, when you know it is safe, by explicitly removing the value marking such as:

```terraform
output "example" {
  value = nonsensitive(aws_ssm_parameter.example.value)
}
```

**Comment by cilindrox** [comment] 2021-04-15 15:58
This also impacts the data source - had to flag the whole thing when reading a remote value, eg:

```terraform
data "aws_ssm_parameter" "users" {
  name     = "/foo/users"
}

locals {
    users = split(",", nonsensitive(data.aws_ssm_parameter.users.value))
}
```

was having some random `dynamic` blocks fail due to these being flagged as sensitive on 0.15

**Comment by igreg** [comment] 2021-05-16 11:39
Having looked into the code of the [aws provider plugin](https://github.com/hashicorp/terraform-provider-aws) and the [SDK module](https://github.com/hashicorp/terraform-plugin-sdk) it depends on, this is caused by a limitation of the SDK which does not allow data & resource attributes (like in our case, the _value_ attribute of both the data.aws_ssm_parameter and resource.aws_ssm_parameter) to be set dynamically.

So you can either have all the value treated as a sensitive value, or none of them. It is not possible to set sensitivity dynamically (e.g. depending on the type of the parameter). It would require the Terraform SDK to be modified to allow this which does not appear to be an easy task - otherwise it would have been done already.

**Comment by WhyNotHugo** [comment] 2021-05-16 13:10
How about having entirely different resources for SecretString and String?

While that may require a one-time refactor for most of us, it does allow to continue using SSM without so many hacks.

Keep in mind that AWS uses SSM for public information, like the ID of the AMI recommended for ECS. SSM is far from being all secrets: it's used to publish data too.

**Comment by igreg** [comment] 2021-05-19 11:55
Alternatively, I think we could also use a separate attribute (e.g. secure_value) when working with SSM parameters of the type SecureString. I think this would also work and avoid duplicating the entire code for data.aws_ssm_parameter and resource.aws_ssm_parameter.

**Comment by srinivas-vangari** [comment] 2021-09-24 18:38
Unnecessarily marking all ssm parameters as secure is giving me below error when I tried to use a complex structure containing ssm parameter as for_each expression for a module.

-------------------
Sensitive values, or values derived from sensitive values, cannot be used as for_each arguments. If used, the sensitive value could be exposed as a resource instance key.
-------------------

**Comment by WhyNotHugo** [comment] 2021-09-24 19:15
@srinivas-vangari You have to add `nonsensitive()` to **every single usage** of all SSM params.

This regression has been terrible, but I guess nobody has the expertise to do something no-that-complex like https://github.com/hashicorp/terraform-provider-aws/issues/9090#issuecomment-841815005.

**Comment by IrfanAnsari** [comment] 2021-09-30 18:19
Same issue as @srinivas-vangari and marking password as nonsensitive means it's part of plan and state, not acceptable to my TL.

**Closed** 2022-07-07 12:30 UTC
Labels: bug, service/ssm
