### ISSUE TITLE
Allow aws_ami to fetch AMIs from other AWS Regions than us-east-1

### ISSUE THREAD

**Issue by jeromegras** [hashicorp/terraform-provider-aws#39680] opened 2024-10-11 07:16 UTC
### Description

I am using coder (www.coder.com) to deploy dev environments on EC2 instances thanks to Terraform.
When searching for AMIs to deploy, the `data "aws_ami"` is looking into us-east-1 Region only.
Did I miss something or is this the actual behaviour? If so, could we consider adding a way to search for AMIs in other Regions?

### Affected Resource(s) and/or Data Source(s)

aws_ami

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-10-11 17:14
Hey @jeromegras 👋 Thank you for taking the time to raise this! I double checked and it [looks like](https://github.com/hashicorp/terraform-provider-aws/blob/1a99c391dbfb3a41eb60e13b3bd53dbf3a75ff58/internal/service/ec2/ec2_ami.go#L426) the region is pulled from whatever region you've [configured for the provider](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#region). Can you verify that updating your `region` setting has the desired effect?

**Comment by justinretzolk** [comment] 2024-11-11 18:20
Hey @jeromegras 👋 I wanted to follow up here to see if the information from my previous comment helped, or if you're still experiencing unexpected behavior.

**Comment by jungle-gecko** [comment] 2024-11-13 12:12
Hey Justin,
Thanks for the reminder.

In fact, the [provider configuration link](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#region) you provided was the key to success.
Indeed, **the default value of `data "coder_parameter" "region"` needs to be changed** to the AWS region where you have the AMIs registered.

```
data "coder_parameter" "region" {
  name         = "region"
  ...
  default      = "eu-west-3"
...
}
provider "aws" {
  region = data.coder_parameter.region.value
}
```

That also highlighted the fact that you need to **anticipate deployment in additional regions by replicating the AMIs where you want instances to be created**.

I guess we can close this issue, thanks a lot for your support!

**Closed** 2024-11-14 14:58 UTC
Labels: enhancement, service/ec2, needs-triage
