### ISSUE TITLE
Cannot creaste aws_wafregional_rule with "The referenced item does not exist"

### ISSUE THREAD

**Issue by oonisim** [hashicorp/terraform-provider-aws#12051] opened 2020-02-14 01:08 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.20

### Affected Resource(s)

aws_wafregional_rule

### Terraform Configuration Files

```
resource "aws_wafregional_rule" "example" {
  name = "example"
  metric_name = "example"

  predicate {
    type = "RegexMatch"
    negated = false
    data_id = aws_waf_regex_match_set.example.id
  }
}

resource "aws_waf_regex_match_set" "example" {
  name = "example"

  regex_match_tuple {
    field_to_match {
      data = "User-Agent"
      type = "HEADER"
    }

    regex_pattern_set_id = "${aws_waf_regex_pattern_set.example.id}"
    text_transformation  = "NONE"
  }
}

resource "aws_waf_regex_pattern_set" "example" {
  name                  = "example"
  regex_pattern_strings = ["one", "two"]
}
```

### Expected Behavior

WAF regional rule is created.

### Actual Behavior

```
aws_waf_regex_pattern_set.example: Creating...
aws_waf_regex_pattern_set.example: Creation complete after 6s [id=d221bfd0-91c4-43c9-b426-dd1573a789a5]
aws_waf_regex_match_set.example: Creating...
aws_waf_regex_match_set.example: Creation complete after 7s [id=8e68abe8-9715-4d78-9825-e7618f8680eb]
aws_wafregional_rule.example: Creating...

Error: Error Updating WAF Regional Rule: Error Updating WAF Rule: WAFNonexistentItemException: The referenced item does not exist.

  on waf2.tf line 1, in resource "aws_wafregional_rule" "example":
   1: resource "aws_wafregional_rule" "example" {

```

### Steps to Reproduce

 `terraform apply`

### References

* #0000

**Comment by ewbankkit** [comment] 2020-02-18 23:02
@oonisim Did you try running `terraform apply` again shortly after on the same configuration - This could be an AWS API "eventual consistency" issue.

**Comment by anGie44** [comment] 2020-09-02 00:36
I'm able to reproduce but if all the resources (not just the `rule`) are created with `wafregional` , the configuration succeeds during `apply`. I'm not too familiar with using these resources in practice, but is it possible to have the regex-related resources be created in the same region as the rule resource?

**Comment by bflad** [comment] 2021-01-22 16:48
It's been a long time since we heard from you here so we're going to close this out. If you're still having this problem, please feel free to reply with responses to the above questions.

**Closed by bflad** 2021-01-22 16:48 UTC
Labels: service/waf, waiting-response
