### ISSUE TITLE
Unable to ignore changes to RDS minor engine version

### ISSUE THREAD

**Issue by joshuaspence** [hashicorp/terraform-provider-aws#1198] opened 2017-07-20 23:36 UTC
We are using the `aws_db_instance` resource for managing RDS instances and I just came across an issue that arises from the use of `auto_minor_version_upgrade`. Basically, we have some Terraform configuration that looks like this:

```
resource "aws_db_instance" "master" {
  allocated_storage = 128
  engine            = "mysql"
  engine_version    = "5.7.10"
  instance_class    = "db.r3.large"
  storage_type      = "gp2"
  
  apply_immediately           = true
  auto_minor_version_upgrade  = true
  allow_major_version_upgrade = true

  # The other parameters are not relevant.
}
```

During one of our scheduled maintenance windows, Amazon have kindly upgrade this RDS instance from MySQL 5.7.10 to 5.7.17 (which is expected due to `auto_minor_version_upgrade`). As such, `terraform plan` now shows the following change to be applied:

```
~ aws_db_instance.master
    engine_version: "5.7.17" => "5.7.10"
```

I can workaround this by adding `engine_version` to `ignore_changes`, but doing so would prevent me from updating the major engine version. Ideally, I would be able to ignore changes only to the minor/patch version.

**Comment by Ninir** [comment] 2017-07-26 14:16
Hey @joshuaspence,

There is nothing Terraform can help on this specific topic: either you want AWS to upgrade your minor version and then you just need to update the `engine_version` to the one set by AWS, or you control everything on your own.

This is based on your needs here :-/

Why not setting `auto_minor_version_upgrade` to false?

**Comment by joshuaspence** [comment] 2017-07-27 03:13
I think my main problem here is that I wasn't expecting it to happen (although I'll admit that I wasn't sure what my expectation was when using `auto_minor_version_upgrade`). Generally I would expect that (assuming no changes to the resources had been applied out-of-band, such as manually through the AWS console) running `terraform plan` after `terraform apply` should never show changes to be applied (excluding potential issues with Terraform itself). It seems that this assumption doesn't hold valid when using `auto_minor_version_upgrade`.

One way that Terraform could better handle this is to allow functions to be used in `ignore_changes`, so that I could ignore changes to the patch version but not the major-minor vengine version. For example, `ignore_changes = ["${join(".", slice(split(".", self.engine_version), 0, 2))}"]`

**Comment by radeksimko** [comment] 2017-07-27 07:25
I'm more inclined to @Ninir here in the sense that Terraform kind of works as expected here (without context of the resource/field). You have specified `engine_version` and because "something/someone else" has changed that (for better or worse) Terraform wants to keep it in line with what's in the config.

That said it's a common enough problem (AFAIK) that it's worth thinking about solution.
In theory the easiest solution would be to use `DiffSuppressFunc` which suppresses the diff of `engine_version` only if:

1. the difference only involves minor versions, **and**
2. the new version is higher (i.e. we should still display downgrades as anomaly in the diff), **and**
3. `auto_minor_version_upgrade` is set to `true`

Let me know what you think - and sorry for the re-labelling spam as I was thinking through the problem 🙈

**Comment by joshuaspence** [comment] 2017-07-27 09:50
I think that the solution that you proposed seems reasonable to me.

**Comment by simonvanderveldt** [comment] 2018-02-28 12:56
Would it be possible to support defining the versions as `x.y` which and don't car about the patch (here called minor for some reason) version when defining it? Terraform would then pick the highest available version and in case `auto_minor_version_upgrade` is enabled AWS would do the upgrades and there would be no delta on the Terraform side.

I.e. one would have
```
resource "aws_db_instance" "somedb" {
  ...
  engine            = "postgres"
  engine_version    = "9.6" (or "9.6.*)
  auto_minor_version_upgrade = true
  ...
```

**Comment by bflad** [comment] 2018-02-28 15:47
Maybe this would be a good use case for a `CustomizeDiff` function? In psuedo-code:
```go
if d.HasChange("engine_version") && d.Get("auto_minor_version_upgrade").(bool) {
  oldVersion, NewVersion := d.GetChange("engine_version")
  if /* logic to correctly determine non-major version changes */ {
    d.Clear("engine_version")
  }
}
```

**Comment by JohannesEbke** [comment] 2018-11-27 17:15
This is now documented in the published docs, as per the pull request, but does not seem to work for me in aws-provider 1.46.0. I'm seeing the DEBUG statement from 
2018-11-27T18:13:46.027+0100 [DEBUG] plugin.terraform-provider-aws_v1.46.0_x4: 2018/11/27 18:13:46 [DEBUG] Ignoring minor version diff
2018/11/27 18:13:46 [DEBUG] Removing 'id' diff and setting Destroy to false because after ignore_changes, this diff no longer requires replacement
...but the diff is still shown on apply.

**Comment by JohannesEbke** [comment] 2018-12-07 07:41
It seems fixed in 1.51. Thanks!

**Comment by lowjoel** [comment] 2019-02-18 04:21
@bflad was DiffSuppressFunc supposed to prevent this from occurring? I'm experiencing the same issue as @JohannesEbke with 1.59. If it was meant to be a `CustomizeDiff` change instead, I can try submitting a PR to fix it.

**Comment by kivagant-ba** [comment] 2019-03-06 13:09
https://www.terraform.io/docs/providers/aws/r/db_instance.html#engine_version
```
engine_version - (Optional) The engine version to use. If auto_minor_version_upgrade is enabled, you can provide a prefix of the version such as 5.7 (for 5.7.10) and this attribute will ignore differences in the patch version automatically (e.g. 5.7.17). For supported values, see the EngineVersion parameter in API action CreateDBInstance. Note that for Amazon Aurora instances the engine version must match the DB cluster's engine version'.
```

Looks like the problem doesn't exist anymore and the solution is documented.

**Comment by noteits** [comment] 2019-04-04 20:17
It still shows the difference.

**Comment by bill-rich** [comment] 2021-03-10 19:24
This issue should be fixed since the `DiffSuppressFunc` was added. I did some testing and was not able to reproduce the with the latest version of the provider. If anyone is still running into this problem, please post an example configuration with steps to reproduce and I'll look more into it.

**Closed by bill-rich** 2021-03-10 19:24 UTC
Labels: enhancement, service/rds
