### ISSUE TITLE
Problem when i create a bucket with prefix 

### ISSUE THREAD

**Issue by mickleissa** [hashicorp/terraform-provider-aws#20901] opened 2021-09-14 16:33 UTC
resource "aws_s3_bucket" "s3_data_in_bucket" {
  count             = var.s3_data_in_bucket ? 1 : 0 # this one is working
  bucket_prefix     = var.logging_bucket
  force_destroy     = var.force_destroy
  policy            = data.aws_iam_policy_document.logging.json
  tags              = var.tags
   #tfsec:ignore:AWS002

  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = "AES256"
      }
    }
  }

  versioning {
    enabled = true
  }
}

resource "aws_s3_bucket_public_access_block" "default" {
  count                            = var.s3_data_in_bucket ? 1 : 0
  bucket_prefix               = aws_s3_bucket.s3_data_in_bucket[0].id
  block_public_acls        = true
  block_public_policy    = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

data "aws_redshift_service_account" "main" {}

data "aws_iam_policy_document" "logging" {
  statement {
    sid = "Put bucket policy needed for Redshift audit logging"
    actions = [
      "s3:PutObject"
    ]
    resources = [
      "arn:aws:s3:::${var.logging_bucket}/*"
    ]
    principals {
      type        = "AWS"
      identifiers = [data.aws_redshift_service_account.main.arn]
    }
  }

  statement {
    sid = "Get ACL bucket policy needed for Redshift audit logging"
    actions = [
      "s3:GetBucketAcl"
    ]
    resources = [
      "arn:aws:s3:::${var.logging_bucket}"
    ]
    principals {
      type        = "AWS"
      identifiers = [data.aws_redshift_service_account.main.arn]
    }
  }
}

# I got this error

 Error: Error putting S3 policy: MalformedPolicy: Policy has invalid resource
│       status code: 400, request id: GQTVA4VD99HCJM7J, host id: 
                tT4ZtAyp7Dr5I+O5dLF+uLFrK5BN2knjY7OTWAE/Do7ZCdbSeW8T6nFNVtyvO6wMjUAevkkCR1Y=
│
│   with module.s3_bucket.aws_s3_bucket.s3_data_in_bucket[0],
│   on ..\modules\s3\main.tf line 1, in resource "aws_s3_bucket" "s3_data_in_bucket":
│    1: resource "aws_s3_bucket" "s3_data_in_bucket" {

**Comment by justinretzolk** [comment] 2021-09-14 21:44
Hey @mickleissa 👋 Thanks for submitting this issue! As a heads up, we generally need the issues template to be filled out in order to ensure we're able to effectively address any incoming issues. That said, in reviewing this issue, I think I may have an idea of what's going on. 

When using the `bucket_prefix` argument for `aws_s3_bucket` resources, the exact string provided is not what's used - rather, the prefix is used to generate a bucket name using the prefix (if you're interested, the code for which may be found [here](https://github.com/hashicorp/terraform-provider-aws/blob/118137cad03ab6521b5de6e44aaa8f35b89b7b0a/aws/resource_aws_s3_bucket.go#L636-L637)). Looking at your code sample, you're defining the S3 bucket by:

`aws_s3_bucket.s3_data_in_bucket`:

```
bucket_prefix = var.logging_bucket
...
policy = data.aws_iam_policy_document.logging.json
```

Later, when defining the policy that is used by the bucket, you've defined:

`data.aws_iam_policy_document.logging`:

```
"arn:aws:s3:::${var.logging_bucket}"
```

However, given that you're using the `bucket_prefix` argument for the S3 bucket resource rather than the `bucket` argument (which defines an explicit name), `var.logging_bucket` will _not_ match the name of the S3 bucket that is created by the `aws_s3_bucket.s3_data_in_bucket` resource, causing the policy to be invalid and causing the `Error putting S3 policy: MalformedPolicy: Policy has invalid resource` error.

Since this issue seems to be caused by the configuration and not an issue with the provider itself, I'm going to go ahead and close this issue. If you feel that I've done this in error, please do let me know.

**Closed by justinretzolk** 2021-09-14 21:44 UTC
Labels: service/s3
