### ISSUE TITLE
Handle ThrottlingException in FindAccountAssignment

### ISSUE THREAD

**Issue by glenthomas** [hashicorp/terraform-provider-aws#25942] opened 2022-07-22 13:29 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.2.5
AWS provider v4.22.0

### Affected Resource(s)

* aws_ssoadmin_account_assignment

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Panic Output

```
Error: error reading SSO Account Assignment for Principal (kjasduo31-b2318e4f-884f-41f7-81b8): not found
  with module.something.aws_ssoadmin_account_assignment.assignment["blah_blah"],
  on ../_modules/account_assignments/main.tf line 37, in resource "aws_ssoadmin_account_assignment" "assignment":
  37: resource "aws_ssoadmin_account_assignment" "assignment" {
Error: error reading SSO Account Assignment for Principal (kjasduo31-b2318e4f-884f-41f7-81b8): not found
  with module.something.aws_ssoadmin_account_assignment.assignment["blah_blah2"],
  on ../_modules/account_assignments/main.tf line 37, in resource "aws_ssoadmin_account_assignment" "assignment":
  37: resource "aws_ssoadmin_account_assignment" "assignment" {

```

### Expected Behavior

AWS provider handles any throttling exception with some retries.
If API operation is still resulting in ThrottlingException then print an appropriate message instead of 'not found'

### Actual Behavior

AWS provider fails with 'not found' error.

### Steps to Reproduce

Add 8 new `aws_ssoadmin_account_assignment` resources and have a number of existing ones.

1. `terraform apply`

### References

* #0000

**Comment by glenthomas** [comment] 2022-07-25 10:18
duplicate of #24858

**Comment by justinretzolk** [comment] 2022-07-25 17:37
Hey @glenthomas 👋 Thanks for taking the time to submit this issue. As you mentioned, it looks like this is a duplicate of #24858. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #24858.

**Closed by justinretzolk** 2022-07-25 17:37 UTC
Labels: needs-triage, service/ssoadmin
