### ISSUE TITLE
[Bug]: Cost category rules should be ordered

### ISSUE THREAD

**Issue by rwolfson** [hashicorp/terraform-provider-aws#29240] opened 2023-02-03 17:15 UTC
### Terraform Core Version

0.12.31

### AWS Provider Version

4.16.0,4.52.0

### Affected Resource(s)

aws_cost_category

### Expected Behavior

AWS cost category rules are ordered, and are systematically edited via an ordered JSON list when using the AWS CLI/console. It should be expected that each rule block specified in a Terraform Cost Category resource would be mirrored in the AWS rule list, in the respective order

### Actual Behavior

It looks like Terraform is treating the cost category as an unordered set of rules. It correctly removes and adds rules when they are not there, but not in the order specified in the configuration file.

### Terraform Configuration Files

This is a toy example where order could matter - the more specific precedence of a tag would take precedence over account number. This might work at first, but order would not be maintained if more "exceptions" were added early in the rule list.

```
resource "aws_ce_cost_category" "Final-Allocation" {
  name         = "FinalAllocation"
  rule_version = "CostCategoryExpression.v1"

  rule {
    value = "AllocationA"
    type  = "REGULAR"
    rule {
      tags {
        key           = "Project"
        values        = ["SpecialProject"]
        match_options = ["EQUALS"]
      }
    }
  }

  rule {
    value = "AllocationB"
    type  = "REGULAR"
    rule {
      dimension {
        key           = "LINKED_ACCOUNT"
        values        = ["111122223333"]
        match_options = ["EQUALS"]
      }
    }
  }
  
  rule {
    value = "AllocationC"
    type  = "REGULAR"
    rule {
      dimension {
        key           = "LINKED_ACCOUNT"
        values        = ["444455556666"]
        match_options = ["EQUALS"]
      }
    }
  }
}
```

### Steps to Reproduce

1. Have a defined cost category rule set in Terraform
1. Make incremental changes that are beyond appending rules to the end (e.g., inserting early rules)

### References

I am not that familiar with Terraform source, but I am wondering if the fix may be a change in the rule block type from TypeSet to TypeList in https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ce/cost_category.go#L61, kind of the opposite of https://github.com/hashicorp/terraform-provider-azurerm/issues/6896

The AWS documents mention the rule ordering:
https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/create-cost-categories.html
https://docs.aws.amazon.com/cli/latest/reference/ce/update-cost-category-definition.html

> Rules are processed in order. If there are multiple rules that match the line item, then the first rule to match is used to determine that Cost Category value.

I put in "no" for implementing a fix as I don't think I would be able to commit time to writing tests around it, but if it's a simple one-line change, I could submit that.

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment] 2023-02-06 21:32
Hey @rwolfson 👋 Thanks for taking the time to submit this issue. It looks like this is a duplicate of #26774. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of that one. Regarding the change, I suspect this would need more than just the one line, to include additional tests, etc.

Duplicate #26774

**Closed by justinretzolk** 2023-02-06 21:32 UTC
Labels: bug, service/ce
