### ISSUE TITLE
new AWS provider 3.35 can't set aws_ssm_parameter with tags and overwrite

### ISSUE THREAD

**Issue by djsuszi** [hashicorp/terraform-provider-aws#18550] opened 2021-04-02 12:56 UTC
```
provider "aws" {
  version = "3.35"
}
```
Plan:

```
  # module.service.aws_ssm_parameter.properties[70] will be created
   resource "aws_ssm_parameter" "properties" {
        arn       = (known after apply)
        data_type = (known after apply)
        id        = (known after apply)
        key_id    = (known after apply)
        name      = "/xxxx"
        overwrite = true
        tags      = {
            "Environment" = "xxx"
        }
        tier      = "Standard"
        type      = "String"
        value     = (sensitive value)
        version   = (known after apply)
    }
```

is giving error:
```
Error: error creating SSM parameter: ValidationException: Invalid request: tags and overwrite can't be used together. To create a parameter with tags, please remove overwrite flag. To update tags for an existing parameter, please use AddTagsToResource or RemoveTagsFromResource.
                status code: 400, request id: xxxxx
```

when I force old provider (version = "3.34") same code it's working fine

### Terraform CLI and Terraform AWS Provider Version

terraform version: 0.12.29
hashicorp/aws 3.35.0

### Affected Resource(s)

aws_ssm_parameter

### Expected Behavior

it should work like in 3.34

### Steps to Reproduce

try to use resource "aws_ssm_parameter" with overwrite and tags

**Comment by ewbankkit** [comment] 2021-04-02 14:04
@djsuszi Thanks for raising this issue.
Which AWS region is the `aws_ssm_parameter` resource being created in?

Related:

* #17819
* #17830

**Comment by djsuszi** [comment] 2021-04-02 14:10
Ireland eu-west-1

**Comment by yrral86** [comment] 2021-04-02 14:39
I'm seeing the same issue with 3.35, fixed with locking to 3.34.  us-gov-west-1 region

**Comment by loreleimccollum-work** [comment] 2021-04-02 14:57
We are seeing the same thing as well

**Comment by mxns-nicolas** [comment] 2021-04-02 15:09
Same here with 3.35. Fixed using 3.34.0

**Comment by edli2** [comment] 2021-04-02 19:16
Same issue with v3.35 here:

`Error: error creating SSM parameter: ValidationException: Invalid request: tags and overwrite can't be used together. To create a parameter with tags, please remove overwrite flag. To update tags for an existing parameter, please use AddTagsToResource or RemoveTagsFromResource.`

**Comment by michaelplemmons** [comment] 2021-04-05 14:54
I +1 the submission but wanted to call out that I am seeing this in us-east-1.

**Comment by gchristidis** [comment] 2021-04-06 07:08
This has also broken my deployments as all my ssm_parameter resources have tags set and overwrite=true.  
In the short term i have updated the version constraint for the aws provider to exclude 3.35 or greater.  
The question i have then is this a bug or new expected behavior, if a bug then i will leave the version constraint in there until a fix is released, otherwise i will have to update all my ssm parameters to have overwrite=false.

**Comment by e-moshaya** [comment] 2021-04-06 23:41
I've also had to roll back to version 3.34.0 due to this breaking all our pipelines. It seems that even after setting overwrite to false and creating the resource is not idempotent and wants to add the tags the second terraform plan run fails because overwrite is set to false.

```
 Error: error creating SSM parameter: ParameterAlreadyExists: The parameter already exists. To overwrite this value, set the overwrite option in the request to true.
```

**Closed** 2021-04-08 23:20 UTC
Labels: bug, regression, service/ssm
