### ISSUE TITLE
[Bug]: aws_inspector2_enabler does not work in ca-central-1 region

### ISSUE THREAD

**Issue by nwalters512** [hashicorp/terraform-provider-aws#34039] opened 2023-10-20 20:41 UTC
### Terraform Core Version

1.6.2

### AWS Provider Version

5.22.0

### Affected Resource(s)

- `aws_inspector2_enabler`

### Expected Behavior

I would expect `aws_inspector2_enabler` to work in the `ca-central-1` region.

### Actual Behavior

`aws_inspector2_enabler` does not work in the `ca-central-1` region.

### Relevant Error/Panic Output Snippet

```shell
Error: updating Amazon Inspector Enabler (769954110362-EC2): operation error Inspector2: Disable, https response error StatusCode: 403, RequestID: dfeb4791-b3c3-4ceb-ada4-8021518def55, AccessDeniedException: Lambda code scanning is not supported in ca-central-1
```

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "ca-central-1"
}

resource "aws_inspector2_enabler" "ca-central-1" {
  account_ids    = ["XXXXX"]
  resource_types = ["EC2"]
}
```

### Steps to Reproduce

Try to `terraform apply` the above Terraform configuration and observe that it errors.

### References

The following page documents the regions where Inspector Lambda code scanning is supported: https://docs.aws.amazon.com/inspector/latest/user/inspector_regions.html#ins-regional-feature-availability. This does not include `ca-central-1` and many other regions.

### Would you like to implement a fix?

None

**Comment by rbchasesc** [comment] 2023-11-02 15:07
This same issue also occurs with provider version 5.23.1 for the `us-west-1` region, which also [does not support LAMBDA](https://docs.aws.amazon.com/inspector/latest/user/inspector_regions.html#ins-regional-feature-availability). From this resource:
```
resource "aws_inspector2_enabler" "inspector_usw1" {
  count          = local.enabled_usw1 ? 1 : 0
  provider       = aws.usw1
  account_ids    = [data.aws_caller_identity.current.account_id]
  resource_types = ["ECR", "EC2"] 
}
```
We get this error (obfuscated values with `*`):
```
Error: updating Amazon Inspector Enabler (*********-EC2:ECR): operation error Inspector2: Disable, https response error StatusCode: 403, RequestID: ********-****-*****-****-************, AccessDeniedException: Lambda code scanning is not supported in us-west-1
```

**Comment by jdstuart** [comment] 2023-11-05 23:09
Also happens with provider v `5.24.0`.

The following is the only terraform resources we're trying to deploy
```
data "aws_caller_identity" "default" {
  provider = aws.ca-central-1
}

resource "aws_inspector2_enabler" "ca-central-1" {
  provider = aws.ca-central-1

  account_ids    = [data.aws_caller_identity.default.account_id]
  resource_types = ["EC2"]
}
```

Terraform apply output
```
Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Reusing previous version of hashicorp/aws from the dependency lock file
- Using previously-installed hashicorp/aws v5.24.0

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
terraform apply tfplan
aws_inspector2_enabler.ca-central-1: Creating...
aws_inspector2_enabler.ca-central-1: Still creating... [10s elapsed]
╷
│ Error: updating Amazon Inspector Enabler (XXXXXXXXXXXX-EC2): operation error Inspector2: Disable, https response error StatusCode: 403, RequestID: 30362957-XXXX-XXXX-XXXX-c394218e6013, AccessDeniedException: Lambda code scanning is not supported in ca-central-1
│
│   with aws_inspector2_enabler.ca-central-1,
│   on main.tf line 30, in resource "aws_inspector2_enabler" "ca-central-1":
│   30: resource "aws_inspector2_enabler" "ca-central-1" {
│
```

**Comment by abezzub** [comment] 2024-02-20 21:50
This issue still happens. `aws_inspector2_enabler` should be aware of what resources are available for a region and not call `delete` for a resource that is not available.

**Comment by stefano-franco** [comment] 2024-03-02 20:54
AWS provider version 5.5 was the last provider where `aws_inspector2_enabler` could be provisioned in a region that does not support `LAMBDA_CODE`.

The resource `aws_inspector2_enabler` first activates inspector2 with the defined resource_types (e.g. `ECR`, `EC2` & `LAMBDA`.
As soon as inspector is enabled, a second step is performed in which all missing resource types are explicitly disabled (e.g. `LAMBDA_CODE`). Since `LAMBDA_CODE` is not supported in some regions, this action will cause an error.

This behavior can be reproduced with the following steps:
1. use aws provider with a region that doesn't support LAMBDA_CODE e.g. `eu-central-2`
2. terraform apply with aws provider 5.5 -> success
3. terraform destroy and update aws provider
4. terraform apply with aws provider > 5.5 -> failure
```terraform
terraform {
  required_version = "1.7.0"

  required_providers {
    aws = {
      source                = "hashicorp/aws"
      version               = "5.5"
      # version               = "> 5.5"
      configuration_aliases = []
    }
  }
}

provider "aws" {
  region = "eu-central-2"
}

data "aws_caller_identity" "current" {}

resource "aws_inspector2_enabler" "example" {
  account_ids    = [data.aws_caller_identity.current.account_id]
  resource_types = ["ECR", "EC2", "LAMBDA"]
}
```

This will affect regions not listed under "Lambda code scanning Regions":
https://docs.aws.amazon.com/inspector/latest/user/inspector_regions.html#ins-regional-feature-availability

This issue could be avoided by not deactivating resource types that are already deactivated by default.
Example response of enabling inspector:
```json
{
    "accounts": [
        {
            "accountId": "111111111111",
            "resourceState": {
                "ec2": {
                    "status": "ENABLED"
                },
                "ecr": {
                    "status": "ENABLED"
                },
                "lambda": {
                    "status": "ENABLED"
                },
                "lambdaCode": {
                    "status": "DISABLED" # LAMBDA_CODE is already disabled -> DO NOT DISABLE AGAIN
                }
            },
            "state": {
                "status": "ENABLED"
            }
        }
    ],
    "failedAccounts": []
}
```

**Comment by githubkannadhasan** [comment] 2024-05-03 09:09
Any update on this issue on the latest aws provider also 5.47.0 for ex.

**Comment by githubkannadhasan** [comment] 2024-05-15 04:27
The workaround from @stefano-franco is not applicable if the inspector2 is enabled in the region earlier with other provider, and not disabling with latest providers. Need support on this.

**Comment by DhilipkumarGnanamurthy** [comment] 2024-05-29 05:06
This issues only works with 5.5 provider, but it's not with latest version of provider. When it will be fixed and closed any deadline or plan. Kindly share it will be helpful.

**Comment by Maxi3315** [comment] 2024-07-10 14:23
Hello, I have same problem in eu-west-3 region. Only works with 5.5.0 AWS Provider and not with last version at this time (5.56.1).

Could you provide soon a quick fix ? That is very impacting in our production deployment.

**Comment by ItgixSupport** [comment] 2024-08-23 08:49
same issue on ap-south-1
`
  # module.amazon_inspector[0].aws_inspector2_enabler.itgix_primary[0] will be created
  + resource "aws_inspector2_enabler" "itgix_primary" {
      + account_ids    = [
          + "296062573670",
        ]
      + id             = (known after apply)
      + resource_types = [
          + "EC2",
          + "ECR",
        ]
    }

Plan: 1 to add, 0 to change, 0 to destroy.`

╷
│ Error: updating AWS Inspector Enabler (296062573670-EC2:ECR): operation error Inspector2: Disable, https response error StatusCode: 403, RequestID: 3ecff391-85ea-42d2-b4cf-3dfb85ed72d6, AccessDeniedException: Lambda code scanning is not supported in ap-south-1
│
│   with module.amazon_inspector[0].aws_inspector2_enabler.itgix_primary[0],
│   on .terraform/modules/amazon_inspector/main.tf line 6, in resource "aws_inspector2_enabler" "itgix_primary":
│    6: resource "aws_inspector2_enabler" "itgix_primary" {
│

**Comment by burizz** [comment] 2024-08-23 08:51
same issue in ap-south-1 for me, trying to enable only EC2 and ECR scanning and failing that Lambda scanning is not supported in there gion 

```
  # module.amazon_inspector[0].aws_inspector2_enabler.itgix_primary[0] will be created
  + resource "aws_inspector2_enabler" "itgix_primary" {
      + account_ids    = [
          + "296062573670",
        ]
      + id             = (known after apply)
      + resource_types = [
          + "EC2",
          + "ECR",
        ]
    }
```

error
```
╷
│ Error: updating AWS Inspector Enabler (296062573670-EC2:ECR): operation error Inspector2: Disable, https response error StatusCode: 403, RequestID: 3ecff391-85ea-42d2-b4cf-3dfb85ed72d6, AccessDeniedException: Lambda code scanning is not supported in ap-south-1
│
│   with module.amazon_inspector[0].aws_inspector2_enabler.itgix_primary[0],
│   on .terraform/modules/amazon_inspector/main.tf line 6, in resource "aws_inspector2_enabler" "itgix_primary":
│    6: resource "aws_inspector2_enabler" "itgix_primary" {
```

**Comment by michalz-rely** [comment] 2024-09-25 13:04
Any progress on that? I'm encountering similar issue in the following regions:

- ap-northeast-2
- sa-east-1
- ca-central-1
- ap-south-1
- ap-northeast-3
- us-west-1
- eu-west-3

**Closed** 2024-09-25 15:53 UTC
Labels: bug, service/inspector2
