### ISSUE TITLE
aws_wafv2_rule_group to support rate_based_statement

### ISSUE THREAD

**Issue by farside5** [hashicorp/terraform-provider-aws#18573] opened 2021-04-05 19:59 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```hcl
# terraform -v 
# Terraform v0.14.9
# provider registry.terraform.io/hashicorp/aws v3.35.0
```

### Description

aws_wafv2_rule_group currently doesn't support rate_based_statement.  

Terraform currently does not support rate_based_statement in [aws_wafv2_rule_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_rule_group#statement).  AWS rule statements currently includes [rate_based_statement](https://docs.aws.amazon.com/waf/latest/developerguide/waf-rule-statement-type-rate-based.html).

Please include support to [rate_based_statement](https://docs.aws.amazon.com/waf/latest/developerguide/waf-rule-statement-type-rate-based.html) and [manage_rule_group_statement](https://docs.aws.amazon.com/waf/latest/developerguide/waf-rule-statement-type-managed-rule-group.html).

```hcl
# Error: Unsupported block type

#   on main.tf line 20, in resource "aws_wafv2_rule_group" "example":
#   20:       rate_based_statement {

# Blocks of type "rate_based_statement" are not expected here.
```

### New or Affected Resource(s)

* aws_wafv2_rule_group

### Terraform Configuration

```hcl
# resource "aws_wafv2_rule_group" "example" {
#  name     = "example-rule"
#  scope    = "REGIONAL"
#  capacity = 2
#
#  rule {
#    name     = "HTTPGetFloodPProtection"
#    priority = 0
#
#    action {
#      block {}
#    }
#
#    statement {
#      rate_based_statement {
#        limit              = 10000
#        aggregate_key_type = "IP"
#
#        scope_down_statement {
#          byte_match_statement {
#            search_string = "get"
#            field_to_match {
#             method {}
#            }
#            text_transformation {
#              priority = 0
#              type = "LOWERCASE"
#            }
#            positional_constraint = "EXACTLY"
#          }
#        }
#      }
#    }
#
#    visibility_config {
#      cloudwatch_metrics_enabled = true
#      metric_name                = "GetRateBased"
#      sampled_requests_enabled   = true
#    }
#  }
#}
```

### Expected Behavior
rate_based_statement is supported.

### Actual Behavior
rate_based_statement is not supported.

### Steps to Reproduce

```hcl
# terraform apply
```

### References

* #0000

**Comment by anGie44** [comment] 2021-04-05 20:29
Hi @farside5 , thank you for raising this issue. Back in July we came across a similar issue https://github.com/hashicorp/terraform-provider-aws/issues/14326 and we found the WAFv2 service does not support the Rate Based Statement type as seen in this reply from AWS support https://github.com/aws/aws-sdk-go/issues/3481#issuecomment-675107935. Of course, sometime has passed since then, so I'd have to verify if it's still unsupported and report back.

**Comment by farside5** [comment] 2021-04-05 20:52
Thanks @anGie44.  Looks like AWS still [doesn't allow rate_based_statement](https://docs.aws.amazon.com/waf/latest/developerguide/waf-rule-groups.html) in rule groups.

**Comment by anGie44** [comment] 2021-04-05 21:29
Nice find @farside5 ! Also confirmed by trying to make a rule group with one rate based statement which returned
```
     Error: Error creating WAFv2 RuleGroup: WAFInvalidParameterException: Error reason: A reference in your rule statement is not valid., field: RATE_BASED_STATEMENT, parameter: RateBasedStatement
        {
          RespMetadata: {
            StatusCode: 400,
            RequestID: "1cc525d6-6506-408c-a9c8-d6bca2a67d0d"
          },
          Field: "RATE_BASED_STATEMENT",
          Message_: "Error reason: A reference in your rule statement is not valid., field: RATE_BASED_STATEMENT, parameter: RateBasedStatement",
          Parameter: "RateBasedStatement",
          Reason: "A reference in your rule statement is not valid."
        }

          on terraform_plugin_test.tf line 2, in resource "aws_wafv2_rule_group" "test":
           2: resource "aws_wafv2_rule_group" "test" {
```
Will close this issue for now but feel free to request the enhancement if you find the service has been updated in the future👍

**Closed by anGie44** 2021-04-05 21:29 UTC
Labels: enhancement, service/wafv2, thinking
