### ISSUE TITLE
Way to switch billing mode of DynamoDB conveniently from PAY_PER_REQUEST to PROVISIONED

### ISSUE THREAD

**Issue by Yamitama** [hashicorp/terraform-provider-aws#14155] opened 2020-07-13 10:15 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Like many of you, I create dynamodbs with autoscalings.
In order to let the read / write capacities fly without being modified every time I type `terraform apply`,
I make use of the `ignore_changes` lifecycle, so the code below is what I get.

```hcl
provider "aws" {
  version = "2.70.0"
  region = "us-west-2"
}

resource "aws_dynamodb_table" "default" {
  name             = "billing_mode_test"
  billing_mode     = "PROVISIONED"
  read_capacity    = 10
  write_capacity   = 10
  hash_key         = "test_hash_key"

  lifecycle {
    ignore_changes = [
      read_capacity,
      write_capacity
    ]
  }

  attribute {
    name = "test_hash_key"
    type = "S"
  }
}

resource "aws_appautoscaling_target" "read_target" {
  count              = aws_dynamodb_table.default.billing_mode == "PROVISIONED" ? 1 : 0
  max_capacity       = 10
  min_capacity       = 1
  resource_id        = "table/${aws_dynamodb_table.default.name}"
  scalable_dimension = "dynamodb:table:ReadCapacityUnits"
  service_namespace  = "dynamodb"

  depends_on = [aws_dynamodb_table.default]
}

resource "aws_appautoscaling_policy" "read_policy" {
  count              = aws_dynamodb_table.default.billing_mode == "PROVISIONED" ? 1 : 0
  name               = "DynamoDBReadCapacityUtilization:${aws_appautoscaling_target.read_target[0].resource_id}"
  policy_type        = "TargetTrackingScaling"
  resource_id        = aws_appautoscaling_target.read_target[0].resource_id
  scalable_dimension = aws_appautoscaling_target.read_target[0].scalable_dimension
  service_namespace  = aws_appautoscaling_target.read_target[0].service_namespace

  target_tracking_scaling_policy_configuration {
    predefined_metric_specification {
      predefined_metric_type = "DynamoDBReadCapacityUtilization"
    }

    target_value = 50
  }

  depends_on = [aws_appautoscaling_target.read_target]
}

resource "aws_appautoscaling_target" "write_target" {
  count              = aws_dynamodb_table.default.billing_mode == "PROVISIONED" ? 1 : 0
  max_capacity       = 10
  min_capacity       = 1
  resource_id        = "table/${aws_dynamodb_table.default.name}"
  scalable_dimension = "dynamodb:table:WriteCapacityUnits"
  service_namespace  = "dynamodb"

  depends_on = [aws_dynamodb_table.default]
}

resource "aws_appautoscaling_policy" "write_policy" {
  count              = aws_dynamodb_table.default.billing_mode == "PROVISIONED" ? 1 : 0
  name               = "DynamoDBWriteCapacityUtilization:${aws_appautoscaling_target.write_target[0].resource_id}"
  policy_type        = "TargetTrackingScaling"
  resource_id        = aws_appautoscaling_target.write_target[0].resource_id
  scalable_dimension = aws_appautoscaling_target.write_target[0].scalable_dimension
  service_namespace  = aws_appautoscaling_target.write_target[0].service_namespace

  target_tracking_scaling_policy_configuration {
    predefined_metric_specification {
      predefined_metric_type = "DynamoDBWriteCapacityUtilization"
    }

    target_value = 50
  }

  depends_on = [aws_appautoscaling_target.write_target]
}
```  

※This is a sample code. In my real environment, I make this a terraform module so as to make the creation of bunch of tables easier, which make things more complicated.

In many cases, I would like to switch the table to on-demand, in order to find out the best range for autoscaling, by fixing only the line like below.

```hcl
billing_mode     = "PAY_PER_REQUEST"
```

However, when I finished the test and change the line above back, I will get an error like below.
```
aws_dynamodb_table.default: Modifying... [id=billing_mode_test]

Error: Write capacity must be > 0 when billing mode is PROVISIONED

  on dynamodb.tf line 6, in resource "aws_dynamodb_table" "default":
   6: resource "aws_dynamodb_table" "default" {
```

This is because setting the `billing_mode` to `PAY_PER_REQUEST` will set the read / write capacities to 0,
and the `ignore_changes` lifecycle simply ignore my capacity settings.

How I work it around is to delete the lifecycle settings each time and then add it back after the apply,
which becomes very bothersome since I need to manage many DynamoDB tables.

Therefore, I'm wondering if we can fix something to let it easier to switch from PAY_PER_REQUEST to PROVISIONED.

### New or Affected Resource(s)

* aws_dynamodb_table

### Potential Terraform Configuration

It would be cool if I can just do nothing to the code above. This may be implemented by automatically setting the read / write capacities to min_capacity if the value is smaller than that.
If it is not going to work, adding a field like "default capacity" is also cool.

**Comment by breathingdust** [comment] 2020-07-13 20:31
Potential duplicate of #13693

**Closed** 2022-01-18 21:40 UTC
Labels: enhancement, service/applicationautoscaling, service/dynamodb
