### ISSUE TITLE
KMS resource Key Policy propagation consistent fail

### ISSUE THREAD

**Issue by AshMenhennett** [hashicorp/terraform-provider-aws#21225] opened 2021-10-09 08:39 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraforn Core: `1.0.5`
AWS Provider: `3.62.0`

### Affected Resource(s)

* aws_kms_key

### Terraform Configuration Files

Same as per #20588 which isn't resolved in latest provider.

Workaround is to roll back to 3.52 which allows to create a key with policy having multiple statements.

Note: providing a policy that is equivalent to the default (non lock out) policy will create successfully, when adding an additional statement, provisioning will fail.

There are new comments on  #20588 that provide additional detail.

Thanks for helping resolve.

### Expected Behavior

I should be able to create a CMK key with a custom policy.

### Actual Behavior

Provisioning fails with failure to propagate key policy.

### Steps to Reproduce

Create a aws_key_resource with the policy attribute set to a policy with multiple statements.

### References

* #20588

**Comment by ewbankkit** [comment] 2021-10-09 11:55
https://github.com/hashicorp/terraform-provider-aws/blob/040f37e8d6a1b13fe796c5cdbfebbebb833ae90a/aws/internal/service/kms/waiter/waiter.go#L96-L122

Potentially caused by `awspolicy.PoliciesAreEquivalent` incorrectly returning `false`?

**Comment by ellaqezi** [comment] 2021-11-30 13:46
Thanks to @CrawX pointer, we also fixed our issue and now use `hashicorp/aws v3.67.0`. Here's the summary, instead of using 
```
    principals {
      identifiers = [data.aws_caller_identity.current.user_id]
      type        = "AWS"
    }
```
we now use
```
    principals {
      identifiers = [data.aws_caller_identity.current.arn]
      type        = "AWS"
    }
```
which allows us to avoid updates-in-place related to the principals block of our key policies like the one below.
```
~ Principal = {
        ~ AWS = "arn:aws:iam::***:user/foobar" -> "AY6MGURNFAFDLAID2CBNV"
}
```

So it looks like the validation between user_id and arn are not working atm.

**Comment by Zambonilli** [comment] 2021-12-03 21:17
As @CrawX mentioned study your plan differences closely on your key policy and try to remove them. We ended up having defined our KMS key policy with 2 AWS principal fields instead of a single AWS field as an array.

**Comment by ewbankkit** [comment] 2021-12-07 15:23
The failure to converge with a `Condition` with a non-quoted boolean has been addressed in hashicorp/awspolicyequivalence@1.4.0 merged via #2206.
I have added an acceptance test for this case.

**Closed** 2021-12-07 17:35 UTC
Labels: bug, regression, service/kms

**Comment by trallnag** [comment] 2022-02-24 12:50
Still occurring for me

**Comment by mijndert** [comment] 2022-02-28 07:10
Same.

**Comment by mijndert** [comment] 2022-03-07 10:54
Any update @ewbankkit?

```
resource "aws_ses_domain_identity" "this" {
  for_each      = toset(var.ses_domains)
  domain        = each.value
}

resource "aws_ses_domain_mail_from" "this" {
  for_each         = toset(var.ses_domains)
  domain           = each.value
  mail_from_domain = "aws.${each.value}"
}

resource "aws_kms_key" "mail-bounces" {
  description = "KMS key for SNS topic mail-bounces"
  enable_key_rotation = true
  policy = <<EOT
{
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "ses.amazonaws.com"
      },
      "Action": [
        "kms:GenerateDataKey*",
        "kms:Decrypt"
      ],
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Principal": { "AWS": "arn:aws:iam::${data.aws_caller_identity.current.account_id}:root" },
      "Action": [
        "kms:Create*",
        "kms:Describe*",
        "kms:Enable*",
        "kms:List*",
        "kms:Put*",
        "kms:Update*",
        "kms:Revoke*",
        "kms:Disable*",
        "kms:Get*",
        "kms:Delete*",
        "kms:ScheduleKeyDeletion",
        "kms:CancelKeyDeletion"
      ],
      "Resource": "*"
    }
  ]
}
EOT
}
resource "aws_sns_topic" "bounces" {
  name              = "mail-bounces"
  kms_master_key_id = aws_kms_key.mail-bounces.key_id
}

resource "aws_ses_identity_notification_topic" "bounces" {
  for_each                 = toset(var.ses_domains)
  identity                 = each.value
  topic_arn                = aws_sns_topic.bounces.arn
  notification_type        = "Bounce"
  include_original_headers = true
}
```

Error:

```
╷
│ Error: error waiting for KMS Key (21b3e2f2-86b6-413c-b56c-cdc16eb8f71b) policy propagation: timeout while waiting for state to become 'TRUE' (last state: 'FALSE', timeout: 5m0s)
│ 
│   with module.ses.aws_kms_key.mail-bounces,
│   on ../../../modules/ses/main.tf line 13, in resource "aws_kms_key" "mail-bounces":
│   13: resource "aws_kms_key" "mail-bounces" {
│ 
╵
```

**Comment by lsacco-nutreense** [comment] 2022-03-15 23:13
Same for me to on v3.74.0.

**Comment by homer6** [comment] 2022-04-12 16:55
Still occurs for me at v3.75.1

**Comment by jkmerriam** [comment] 2022-04-18 15:38
This is also occurring for me on hashicorp/aws v4.1
