### ISSUE TITLE
[Bug]: Error trying to get ENI IPs

### ISSUE THREAD

**Issue by shriyo101** [hashicorp/terraform-provider-aws#38148] opened 2024-06-27 05:49 UTC
### Terraform Core Version

1.9.0

### AWS Provider Version

>=4.0

### Affected Resource(s)

data "aws_network_interface",   data "aws_vpc_endpoint" 

### Expected Behavior

Should be able to get the Private IPv4 IPs and pass it to security group CIDR.

My requirement:
create a VPC Interface Endpoint. and get the IPs for the ENIs created. Pass the IP with security group of another resource as inbound allow with 443 TCP protocol. I am creating the Endpoint in 3 subnets/AZ's so 3 IPs are expected.

### Actual Behavior

Error using the data source constantly, tried multiple ways to get the values but no luck.

using for_each or no loops both result in same error that the resource is not there yet and cant proceed further error as provided in this case.

### Relevant Error/Panic Output Snippet

```console
├────────────────
│     │ data.aws_vpc_endpoint.sns.network_interface_ids is a set of string, known only after apply
│
│ The "for_each" set includes values derived from resource attributes that
│ cannot be determined until apply, and so Terraform cannot determine the
│ full set of keys that will identify the instances of this resource.
│
│ When working with unknown values in for_each, it's better to use a map
│ value where the keys are defined statically in your configuration and where
│ only the values contain apply-time results.
│
│ Alternatively, you could use the -target planning option to first apply
│ only the resources that the for_each value depends on, and then apply a
│ second time to fully converge.
╵
Operation failed: failed running terraform plan (exit 1)
```

### Terraform Configuration Files

```hcl
#Interface Endpoint for KMS for Application use
resource "aws_vpc_endpoint" "kms" {
  vpc_id            = module.vpc.vpc_id
  service_name      = "com.amazonaws.${var.region}.kms"
  vpc_endpoint_type = "Interface"
  subnet_ids          = local.app_subnets
  security_group_ids = [
    aws_security_group.kms_int_ep_sg.id,
  ]

  private_dns_enabled = true
  tags                = { 
    Name = "${local.prefix}-ep" 
    }
}

resource "aws_security_group" "kms_int_ep_sg" {
  name        = "${local.prefix}-kms-int-ep-sg"
  description = "Security group for KMS VPC endpoint"
  vpc_id      = module.vpc.vpc_id

  tags = {
    Name = "${local.prefix}-kms-int-ep-sg"
  }
}

# Retrieve network interfaces for KMS
  data "aws_vpc_endpoint" "kms" {
    vpc_id       = module.vpc.vpc_id
    service_name = "com.amazonaws.${var.region}.kms"

    depends_on = [ aws_vpc_endpoint.kms ]
  }

attempt1:
data "aws_network_interface" "kms_interfaces" {
  for_each = data.aws_vpc_endpoint.kms.network_interface_ids
  id = each.value

  depends_on = [data.aws_vpc_endpoint.kms]
}

attempt2:
data "aws_network_interface" "kms_enis" {
  for_each = toset(data.aws_vpc_endpoint.kms.network_interface_ids)
  id       = each.value
}


attemp3:
data "aws_network_interfaces" "kms_interfaces" {
   count = length(local.app_subnets)
   id =  flatten(aws_vpc_endpoint.kms.*.network_interface_ids)[count.index]
  for_each = data.aws_vpc_endpoint.kms.network_interface_ids
  id = each.value

  depends_on = [data.aws_vpc_endpoint.kms]
}

output "endpoints_private_ips_kms" {
  value = formatlist("%s", [for eni in data.aws_network_interface.kms_eni : eni.private_ip])
}

# Create Lambda Security Group
resource "aws_security_group" "async_kms_rot_lambda_sg" {
  name   = "lambda-sg"
  vpc_id = module.vpc.vpc_id
tags = {
    Name = "lambda-sg"
  }
}

attempt1:
resource "aws_security_group_rule" "lambda_egress_kms" {
  type              = "ingress"
  from_port         = 443
  to_port           = 443
  protocol          = "tcp"
  security_group_id = aws_security_group.async_kms_rot_lambda_sg.id
  cidr_blocks       = [for eni_id, ip in local.eni_ip_map : ip]
}

attempt2:
resource "aws_security_group_rule" "lambda_egress_kms" {
for_each = data.aws_network_interface.kms_eni
  type               = "egress"
  from_port          = 443
  to_port            = 443
  protocol           = "tcp"
  cidr_blocks        = each.value.private_ip
  security_group_id  = aws_security_group.async_kms_rot_lambda_sg.id

  depends_on = [aws_vpc_endpoint.kms]
}

attempt3:
resource "aws_security_group_rule" "lambda_egress_kms" {
 for_each           = data.aws_network_interface.kms_interfaces.*.private_ips
  type               = "egress"
  from_port          = 443
  to_port            = 443
  protocol           = "tcp"
  cidr_blocks        = each.value
  security_group_id  = aws_security_group.async_kms_rot_lambda_sg.id

  depends_on = [aws_vpc_endpoint.kms]
}

attemp4:
resource "aws_security_group_rule" "lambda_egress_kms" {
  for_each           = toset(flatten([data.aws_network_interface.sns_interfaces[*].private_ips]))
    type               = "egress"
    from_port          = 443
    to_port            = 443
    protocol           = "tcp"
    cidr_blocks        = each.value
    security_group_id  = aws_security_group.async_kms_rot_lambda_sg.id

    depends_on = [ aws_vpc_endpoint.sns ]
  }
```

### Steps to Reproduce

1. create the VPC interface endpoint.
2. try getting the IPs for the ENIs trying to create and pass the value to a security group.

do this all in one flow, and NOT by creating the EP 1st and then doing a second apply to get the IPs.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-06-27 14:44
Hey @shriyo101 👋 Thank you for taking the time to raise this! This is the relevant line of the error message:

```console
│     │ data.aws_vpc_endpoint.sns.network_interface_ids is a set of string, known only after apply
```

This is a result of a [limitation of the `for_each` meta-argument](https://developer.hashicorp.com/terraform/language/meta-arguments/for_each#limitations-on-values-used-in-for_each):

> The keys of the map (or all the values in the case of a set of strings) must be known values, or you will get an error message that `for_each` has dependencies that cannot be determined before apply, and a `-target` may be needed.

Since this is a limitation of Terraform Core itself, and not something that the AWS Provider team will need to address, I'm going to close this issue. If you run into unexpected behavior in the future, please do let us know!

**Closed by justinretzolk** 2024-06-27 14:44 UTC
Labels: bug, needs-triage, service/vpc

**Comment by shriyo101** [comment] 2024-06-28 07:24
ok, I understand. And if you still are reading this comment. How can I work around to get the IPs. Is there any solution you can help me with? Really would appreciate your help on this.
