### ISSUE TITLE
[Enhancement]: Add support for the ManageMasterUserPassword and MasterUserSecret properties as arguments for the resource: aws_rds_cluster

### ISSUE THREAD

**Issue by aminutolo** [hashicorp/terraform-provider-aws#30010] opened 2023-03-14 23:09 UTC
### Description

Aurora supports the management of the master user password with AWS Secrets Manager. It leverages two properties in CloudFormation.

ManageMasterUserPassword

- A value that indicates whether to manage the master user password with AWS Secrets Manager.
- Constraints: Can't manage the master user password with AWS Secrets Manager if MasterUserPassword is specified.
- Valid for: Aurora DB clusters and Multi-AZ DB clusters
- Required: No
- Type: Boolean
- Update requires: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)

MasterUserSecret

- Contains the secret managed by RDS in AWS Secrets Manager for the master user password.
- Required: No
- Type: [MasterUserSecret](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-dbcluster-masterusersecret.html)
- Update requires: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)
- Update requires: [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt)

### Affected Resource(s) and/or Data Source(s)

* aws_rds_cluster

### Potential Terraform Configuration

```terraform
resource "aws_rds_cluster" "auroramysql" {
  manage_master_user_password = Boolean
  master_user_secret = {
    kms_key_id = String(Optional)
    secret_arn = String(Optional)
  }
```

### References

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-masterusersecret
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-managemasteruserpassword
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-rds-dbcluster-masterusersecret.html

### Would you like to implement a fix?

None

**Comment by AdamTylerLynch** [comment] 2023-03-17 16:29
Duplicate of #28538

**Comment by AdamTylerLynch** [comment] 2023-03-17 16:30
In progress pull request here: #28848

**Closed by AdamTylerLynch** 2023-03-17 16:29 UTC
Labels: enhancement, service/rds, needs-triage
