### ISSUE TITLE
[Bug]: aws_rds_reserved_instance must be replaced

### ISSUE THREAD

**Issue by ericrichtert** [hashicorp/terraform-provider-aws#37530] opened 2024-05-15 12:44 UTC
### Terraform Core Version

1.8.2

### AWS Provider Version

5.49.0

### Affected Resource(s)

* data aws_rds_reserved_instance_offering
* resource aws_rds_reserved_instance
* resource aws_db_instance

When we do a little change on the aws_db_instance (for example bump the version of posgres from 15.6 to 15.7), the aws_rds_reserved_instance_offering is renewed, and that causes everything to fail

### Expected Behavior

No change to the data aws_rds_reserved_instance_offering and the resource aws_rds_reserved_instance

### Actual Behavior

data aws_rds_reserved_instance_offering will be renewed, so the offering_id is not known, what causes the resource aws_rds_reserved_instance to be replaced. And that's not possible, the resource is deleted from the state, but can not be recreated as the reserved instance already exists in AWS.

### Relevant Error/Panic Output Snippet

```console
Terraform will perform the following actions:
  # data.aws_rds_reserved_instance_offering.tf-rds-reserved-instance-offering will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "aws_rds_reserved_instance_offering" "tf-rds-reserved-instance-offering" {
      + currency_code       = (known after apply)
      + db_instance_class   = "db.m6i.large"
      + duration            = 31536000
      + fixed_price         = (known after apply)
      + id                  = (known after apply)
      + multi_az            = true
      + offering_id         = (known after apply)
      + offering_type       = "All Upfront"
      + product_description = "postgresql"
    }
  # aws_db_instance.tf-postgres-xxx-xxxx will be updated in-place
  ~ resource "aws_db_instance" "tf-postgres-xxx-xxxx" {
      ~ engine_version                        = "15.6" -> "15.7"
        id                                    = "db-xxxxxx"
        # (70 unchanged attributes hidden)
    }

  # aws_rds_reserved_instance.tf-rds-reserved-instance must be replaced
-/+ resource "aws_rds_reserved_instance" "tf-rds-reserved-instance" {
      ~ arn                 = "arn:aws:rds:eu-west-1:xxx:ri:tf-postgres-xxx-xxxx" -> (known after apply)
      ~ currency_code       = "USD" -> (known after apply)
      ~ db_instance_class   = "db.m6i.large" -> (known after apply)
      ~ duration            = 31536000 -> (known after apply)
      ~ fixed_price         = 2266 -> (known after apply)
      ~ id                  = "tf-postgres-xxx-xxxx" -> (known after apply)
      ~ lease_id            = "9b82a584-xxxx-xxxx-bd09-ca12442090e2" -> (known after apply)
      ~ multi_az            = true -> (known after apply)
      ~ offering_id         = "a249c8ac-xxxx-xxxx-9045-bae473a0b703" # forces replacement -> (known after apply) # forces replacement
      ~ offering_type       = "All Upfront" -> (known after apply)
      ~ product_description = "postgresql" -> (known after apply)
      ~ recurring_charges   = [
          - {
              - recurring_charge_amount    = 0
              - recurring_charge_frequency = "Hourly"
            },
        ] -> (known after apply)
      ~ start_time          = "2023-06-20T11:07:03Z" -> (known after apply)
      ~ state               = "active" -> (known after apply)
      - tags                = {} -> null
      ~ usage_price         = 0 -> (known after apply)
        # (3 unchanged attributes hidden)
    }
```

### Terraform Configuration Files

```hcl
resource "aws_db_instance" "tf-postgres-xxx-xxxx" {
  identifier              = "tf-postgres-xxx-xxxx"
  allocated_storage       = "40"
  max_allocated_storage   = "1000"
  storage_type            = "gp3"
  instance_class          = "db.m6i.large"
  engine                  = "postgres"
  engine_version          = "15.7"
  #removed the rest
}

data "aws_rds_reserved_instance_offering" "tf-rds-reserved-instance-offering" {
  db_instance_class   = aws_db_instance.tf-postgres-xxx-xxxx.instance_class
  duration            = 31536000 #this is 1 year
  multi_az            = aws_db_instance.tf-postgres-xxx-xxxx.multi_az
  offering_type       = "All Upfront"
  product_description = "postgresql"
}

resource "aws_rds_reserved_instance" "tf-rds-reserved-instance" {
  offering_id    = data.aws_rds_reserved_instance_offering.tf-rds-reserved-instance-offering.offering_id
  reservation_id = lower(aws_db_instance.tf-postgres-xxx-xxxx.identifier)
  instance_count = 1
}
```

### Steps to Reproduce

Make little change on the aws_db_instance (we updated the version from 15.6 to 15.7) and do an apply

### Debug Output

Not sure if this is a bug or "works as designed", if you need some debug logging, I can create it.

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment] 2024-07-08 17:58
Hey @ericrichtert 👋 Thank you for taking the time to raise this! In this case, Terraform is behaving as I would expect it to. There are a few hints in the logs you provided that helped guide me to that conclusion:

```console
  # data.aws_rds_reserved_instance_offering.tf-rds-reserved-instance-offering will be read during apply
  # (depends on a resource or a module with changes pending)
```

Since the data source is dependent on the `aws_db_instance` instance, it's [unable to be read during plan time](https://developer.hashicorp.com/terraform/language/data-sources#data-resource-behavior). This means that its values won't be known until plan time, which leads to the next clue:

```console
       ~ offering_id         = "a249c8ac-xxxx-xxxx-9045-bae473a0b703" # forces replacement -> (known after apply) # forces replacement
```

Since the value of `data.aws_rds_reserved_instance_offering.tf-rds-reserved-instance-offering.offering_id` is not known until apply time, Terraform sees this as a diff. The `offering_id` is a type of argument that requires that the resource be replaced on changes (usually indicative that the upstream API doesn't offer functionality to update that value directly), so the resource is marked for replacement.

With that in mind, I'm going to close this issue. If you run into unexpected behavior again in the future, please do let us know!

**Closed by justinretzolk** 2024-07-08 17:58 UTC
Labels: bug, service/rds, needs-triage
