### ISSUE TITLE
[Bug]: Unable to destroy appmesh virtual node and update appmesh route in apply

### ISSUE THREAD

**Issue by dhrkumar** [hashicorp/terraform-provider-aws#38444] opened 2024-07-20 12:45 UTC
### Terraform Core Version

1.9.2

### AWS Provider Version

5.59.0

### Affected Resource(s)

* aws_appmesh_virtual_node
* aws_appmesh_route

### Expected Behavior

Apply command should have update route to remove virtual node reference followed by destroying virtual node.

### Actual Behavior

Terraform attempted to destroy virtual node while route was still having referencing the virtual node as one of the targets.

### Relevant Error/Panic Output Snippet

```shell
aws_appmesh_virtual_node.node: Destroying... [id=f85c92ea-e5c6-43a7-b137-d62607a7fe39]
╷
│ Error: deleting App Mesh Virtual Node (f85c92ea-e5c6-43a7-b137-d62607a7fe39): ResourceInUseException: VirtualNode with name node cannot be deleted because it is the target of one or more routes.
```

### Terraform Configuration Files

```hcl
resource "aws_appmesh_mesh" "mesh" {
  name = "mesh"
}

resource "aws_vpc" "vpc" {
  cidr_block           = "10.0.0.0/16"
  enable_dns_support   = true
  enable_dns_hostnames = true
}

resource "aws_service_discovery_private_dns_namespace" "namespace" {
  name        = "example.terraform.local"
  description = "example"
  vpc         = aws_vpc.vpc.id
}

resource "aws_service_discovery_service" "service" {
  name = "service"
  dns_config {
    namespace_id = aws_service_discovery_private_dns_namespace.namespace.id
    dns_records {
      ttl  = 10
      type = "A"
    }
    routing_policy = "MULTIVALUE"
  }
}

resource "aws_appmesh_virtual_node" "node" {
  mesh_name = aws_appmesh_mesh.mesh.name
  name      = "node"
  spec {
    service_discovery {
      aws_cloud_map {
        namespace_name = aws_service_discovery_private_dns_namespace.namespace.name
        service_name   = "service"
      }
    }
    listener {
      port_mapping {
        port     = 80
        protocol = "http"
      }
    }
  }
}

resource "aws_appmesh_virtual_router" "router" {
  mesh_name = aws_appmesh_mesh.mesh.name
  name      = "router"
  spec {
    listener {
      port_mapping {
        port     = 80
        protocol = "http"
      }
    }
  }
}

resource "aws_appmesh_route" "route" {
  mesh_name           = aws_appmesh_mesh.mesh.name
  name                = "route"
  virtual_router_name = aws_appmesh_virtual_router.router.name
  spec {
    priority = 1000
    http_route {
      match {
        prefix = "/"
        port   = 80
      }
      action {
        weighted_target {
          virtual_node = aws_appmesh_virtual_node.node.name
          weight       = 100
          port         = 80
        }
      }
    }
  }
}
```

### Steps to Reproduce

1. `terraform apply`
2. Comment/remove resource `aws_appmesh_virtual_node.node` and block `aws_appmesh_route.route.spec.http_route`
```hcl
resource "aws_appmesh_mesh" "mesh" {
  name = "mesh"
}

resource "aws_vpc" "vpc" {
  cidr_block           = "10.0.0.0/16"
  enable_dns_support   = true
  enable_dns_hostnames = true
}

resource "aws_service_discovery_private_dns_namespace" "namespace" {
  name        = "example.terraform.local"
  description = "example"
  vpc         = aws_vpc.vpc.id
}

resource "aws_service_discovery_service" "service" {
  name = "service"
  dns_config {
    namespace_id = aws_service_discovery_private_dns_namespace.namespace.id
    dns_records {
      ttl  = 10
      type = "A"
    }
    routing_policy = "MULTIVALUE"
  }
}

# resource "aws_appmesh_virtual_node" "node" {
#   mesh_name = aws_appmesh_mesh.mesh.name
#   name      = "node"
#   spec {
#     service_discovery {
#       aws_cloud_map {
#         namespace_name = aws_service_discovery_private_dns_namespace.namespace.name
#         service_name   = "service"
#       }
#     }
#     listener {
#       port_mapping {
#         port     = 80
#         protocol = "http"
#       }
#     }
#   }
# }

resource "aws_appmesh_virtual_router" "router" {
  mesh_name = aws_appmesh_mesh.mesh.name
  name      = "router"
  spec {
    listener {
      port_mapping {
        port     = 80
        protocol = "http"
      }
    }
  }
}

resource "aws_appmesh_route" "route" {
  mesh_name           = aws_appmesh_mesh.mesh.name
  name                = "route"
  virtual_router_name = aws_appmesh_virtual_router.router.name
  spec {
    priority = 1000
#     http_route {
#       match {
#         prefix = "/"
#         port   = 80
#       }
#       action {
#         weighted_target {
#           virtual_node = aws_appmesh_virtual_node.node.name
#           weight       = 100
#           port         = 80
#         }
#       }
#     }
  }
}
```
3. `terraform apply`

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-07-24 16:40
Hey @dhrkumar 👋 Thank you for taking the time to raise this! Terraform Core builds the resource graph and determines the order of operations. With that in mind, you'll want to open an issue in the [Terraform Core repository](https://github.com/hashicorp/terraform) in order to have this properly addressed.

Since there's no action for the AWS Provider team to take on this particular issue, I'm going to close it, but if you do experience unexpected behavior with the provider in the future, please do let us know!

**Closed by justinretzolk** 2024-07-24 16:40 UTC
Labels: bug, service/servicediscovery, service/appmesh, needs-triage, service/vpc
