### ISSUE TITLE
aws_api_gateway_rest_api_policy after adding VPC endpoint policy deployment not working

### ISSUE THREAD

**Issue by PrabaharD** [hashicorp/terraform-provider-aws#16463] opened 2020-11-27 12:30 UTC
aws_api_gateway_rest_api_policy after adding VPC endpoint policy deployment not working. 
I have added VPC endpoint to my private API gateway, applied policy using this new resource aws_api_gateway_rest_api_policy. Terraform deployment went well, however I kept getting message forbidden.
For the same policy, I manually edit (just removing a char, save it and put that char back) without any change, now its working. Don't know what is causing this glitch. Since this is just a week old resource, don't see much help around. Any help appreciated.

**Comment by ewbankkit** [comment] 2020-11-27 12:55
Related:

* https://github.com/hashicorp/terraform-provider-aws/pull/13619

**Comment by DrFaust92** [comment] 2020-11-27 12:59
Hi @PrabaharD,

can you share the config you are using to be able to help you debug the issue? a few issues from the top of my head that i know fro experience: 1. AWS is not sensitive enough sometimes to policies being valid and take them as is. 2. using API Gateway rest api resource with an Open API/Swagger Spec overwrites some resources definitions.

**Comment by PrabaharD** [comment] 2020-11-27 15:46
@DrFaust92 Right we are using Swagger to define API. Hence the resource policy was not working even though deployed it perfectly. So we later moved resource policy into the Swagger file itself and its working right after the deployment.

When you ask about the config, could you please specific which config you need it? My TF environment has multiple module layers, so need to remove certain info before sharing.

**Comment by PrabaharD** [comment] 2020-11-27 16:13
One more thing we identified, during terraform deployment using aws_api_gateway_rest_api_policy resource, the api gateway deployment id was not getting changed to the latest one. It was trying to pick up some old id. For example:

When the output is like below, changing one id to another in stage, having this problem. Somehow when we used the resource policy, stage id is not getting proper update. Just my thoughts.. 
~ resource "aws_api_gateway_stage" "this" {
14:59:51          arn                   = "arn:aws:apigateway:**********::***********************"
14:59:51          cache_cluster_enabled = false
14:59:51          cache_cluster_size    = "0.5"
14:59:51        ~ deployment_id         = "448iod" -> "2ef103"

When stage gets this out deployment_id known after apply, no issues at all. (This output using policy attached to the Swagger)
~ resource "aws_api_gateway_stage" "this" {
15:45:22          arn                   = "arn:aws:apigateway:us-***::/restapis/*********/stages/*****"
15:45:22          cache_cluster_enabled = false
15:45:22          cache_cluster_size    = "0.5"
15:45:22        ~ deployment_id         = "h24nal" -> (known after apply)

**Comment by bflad** [comment] 2021-01-21 08:33
There are some fixes in the `aws_api_gateway_rest_api` resource releasing later today with version 3.25.0 of the Terraform AWS Provider with respect to OpenAPI specification handling that should help with any inline `body` and `policy` argument usage within the `aws_api_gateway_rest_api` resource itself (where the `policy` argument will now correctly be applied after the OpenAPI import, which always overwrites the configuration of the API). Using the separate `aws_api_gateway_rest_api_policy` resource may not work as expected since it would not know about the OpenAPI updates occurring in the `aws_api_gateway_rest_api` resource.

Given the information you provided it is not immediately clear to me how to best help further. For example we will need to know the Terraform CLI and Terraform AWS Provider versions used, the configuration, and likely the output from debug logging of the API requests. I am going to close this issue and encourage you to open a new issue using the [Bug Report](https://github.com/hashicorp/terraform-provider-aws/issues/new?template=Bug_Report.md) template so that the maintainers can get a better understanding of the issue(s) and potentially try to reproduce the behavior. 

If you are not sure if you are running into a Terraform AWS Provider bug and would like some guidance to determine that, you may want to visit the [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers) to start.

**Closed by bflad** 2021-01-21 08:33 UTC
Labels: service/apigateway
