### ISSUE TITLE
Support Session Manager Preferences

### ISSUE THREAD

**Issue by myoung34** [hashicorp/terraform-provider-aws#6121] opened 2018-10-11 12:04 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The new [session manager](https://aws.amazon.com/about-aws/whats-new/2018/09/introducing-aws-systems-manager-session-manager/) has some settings that could be supported.

### New or Affected Resource(s)

* aws_systems_manager_session

### Potential Terraform Configuration

```hcl
resource "aws_systems_manager_session" "default" {
  s3_storage_bucket = "..."
  cloudwatch_log_stream = "..."
}
```

### References

n/a

**Comment by tdmalone** [comment] 2019-04-26 07:16
As much as I would love to see this in Terraform, I've just had a good hunt around for another way to do it and I can't find it in the SDKs or CLI so it looks like it might not be programmatically configurable yet. Hopefully I'm just not looking in the right place though!

**Comment by tdmalone** [comment] 2019-04-26 07:51
Someone cleverer than me pointed out this is _already_ possible via [aws_ssm_document](https://www.terraform.io/docs/providers/aws/r/ssm_document.html) - yay!

See [here](https://github.com/gazoakley/terraform-aws-session-manager-settings/blob/master/main.tf) for an example implementation, and also available is details on [creating](https://docs.aws.amazon.com/systems-manager/latest/userguide/getting-started-create-preferences-cli.html) and [updating](https://docs.aws.amazon.com/systems-manager/latest/userguide/getting-started-configure-preferences-cli.html) via the AWS CLI.

Given this is already possible in Terraform, and matching the existing API implementation offered by AWS (even if it is not where we probably would have expected to find it), I'd suggest this issue could probably now be closed.

**Comment by poflynn** [comment] 2020-08-10 19:45
Maybe I'm not understanding SSM documents but I don't understand how creating a document has anything to do with the SSM preferences for the account/region which your original issue was asking to set?

**Comment by tdmalone** [comment] 2020-08-11 06:12
@poflynn Rather than a separate API being exposed for them, the Session Manager preferences are implemented via an SSM document with a known name (and all the console does is save these to the document, or something like that, behind-the-scenes).

I have mixed feelings on this approach - which I have provided to the Session Manager product manager - it made it more difficult to discover, but once you know where it is, it means you can easily update it as new settings are released without having to wait for Terraform et al to add support for new options.

Here's a good example of how how to format the document:
https://github.com/gazoakley/terraform-aws-session-manager-settings/blob/master/main.tf

And it works well, _except_ that drift detection does not appear to be supported (at least, last time I tested it) if you change the values directly in the console.

**Comment by poflynn** [comment] 2020-08-11 23:40
Thx for the reply @tdmalone . The bit I was missing was the requirement that it be named `SSM-SessionManagerRunShell`. A couple of additional points:

1. In some (but not all) regions I found that a document with this name already existed. I can guarantee you nobody manually created this document, I suspect it got created in the background as you described above (altho in some of these regions I would have bet no one ever went neat session mngr prefs or anything else, odd). To get around this I had to do an import on the existing doc and then an apply
2. I needed to have `true` vs `"true"` in my doc definition for it to work, FYI
3. I think I created invalid docs at some point (maybe because of point 2 above?) because I broke everything. By 'everything' I mean when I tried to start a session I'd get a blank screen and no prompt. Plus when I tried to manually edit the prefs via the console I got a garbled screen back (which I would argue is a bug but anyway). Just an FYI to anyone else who might see this stuff.

Paul

**Comment by WCMinor** [comment] 2022-01-14 16:02
I can confirm that @tdmalone solution worked for me, I had to add a log group name in order to enable cloudwatch logs. Also, as pointed by @poflynn the document already existed, so I had to do a terraform import. My approach to avoid an invalid document was to copy and paste the original json into my terraform template and then substitute a couple of values, this was the final snippet:
```
resource "aws_ssm_document" "session_manager_prefs" {
  name            = "SSM-SessionManagerRunShell"
  document_type   = "Session"
  document_format = "JSON"

  content = <<DOC
{
  "schemaVersion": "1.0",
  "description": "Document to hold regional settings for Session Manager",
  "sessionType": "Standard_Stream",
  "inputs": {
    "s3BucketName": "",
    "s3KeyPrefix": "",
    "s3EncryptionEnabled": true,
    "cloudWatchLogGroupName": "${var.ssm_cloudwatch_log_group_name}",
    "cloudWatchEncryptionEnabled": ${var.ssm_cloudwatch_encryption_enabled ? "true" : "false"},
    "cloudWatchStreamingEnabled": true,
    "idleSessionTimeout": "20",
    "maxSessionDuration": "",
    "kmsKeyId": "",
    "runAsEnabled": false,
    "runAsDefaultUser": "",
    "shellProfile": {
      "windows": "",
      "linux": ""
    }
  }
}
DOC
}
```

**Comment by DrFaust92** [comment] 2022-02-12 22:42
Closing based on @tdmalone answer.

**Closed by DrFaust92** 2022-02-12 22:42 UTC
