### ISSUE TITLE
Error: Provider produced inconsistent final plan - tags_all error when using default_tags block (tag to resource aws_vpc_peering_connection_accepter)

### ISSUE THREAD

**Issue by dyshin777** [hashicorp/terraform-provider-aws#25067] opened 2022-05-26 11:59 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Provideer Version like this :

terraform {
  required_version = ">= 1.1.6"

  required_providers {
    aws = {
      source                = "hashicorp/aws"
      version               = "> 4.0.0, <= 4.9.0"
      //configuration_aliases = [aws.northeast]
    }
  }
}

### Affected Resource(s)

resource  aws_vpc_peering_connection_accepter

### Terraform Configuration Files

# Accepter's side of the connection.
resource "aws_vpc_peering_connection_accepter" "peer" {
  vpc_peering_connection_id = data.aws_vpc_peering_connection.peer.id
  auto_accept               = true

  accepter {
    allow_remote_vpc_dns_resolution = true
  }

  tags = {
    Name          = "vpc-peer-${local.default_tag}"
    VPC_Peer_Info = "${data.aws_vpc_peering_connection.peer.peer_vpc_id}-peer-${var.requester_vpc_id}-accepter"
  }
}

data "aws_vpc_peering_connection" "peer" {
  vpc_id      = var.requester_vpc_id
  region      = var.requester_region
  cidr_block  = var.requester_cidr_block
}

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/97525862/170483169-bf2f3ca6-c47e-45d8-ab60-d4a0c3c11ef1.png">

### Expected Behavior

I try to change subnet ip range from auto.tfvars which is declared as a string value for subnet name, subnet ip range, subnet availability zone name.

### Actual Behavior

Error appear and Operation failed: failed running terraform apply (exit 1)

### Steps to Reproduce

We use Terraform Cloud with Enterprise Organization.

1. git push origin branch
2. git push success
3. TFC Workspace plan Success
4. Confirm apply 
5. Bug Error happened

### Important Factoids

No, we don't use EC2 Classic

### References

No i couldn't find any other related issue something like this.

**Comment by dyshin777** [comment] 2022-05-26 12:17
Please let me know if you need more detail code.
I will add code after get permission from my team leader.

@Great-Stone

**Comment by justinretzolk** [comment] 2022-06-06 21:54
Hey @dyshin777 👋 Thank you for taking the time to raise this! It looks like this is a duplicate of #19583. We like to try to keep conversations in the same place where possible, so we'll close this issue in favor of #19583.

**Closed by justinretzolk** 2022-06-06 21:54 UTC
Labels: needs-triage, service/vpc
