### ISSUE TITLE
Cannot update Already Created Cloudfront Distribution with forward_values to replace with cache_policy_id

### ISSUE THREAD

**Issue by M-A-N-I-S-H-K** [hashicorp/terraform-provider-aws#17662] opened 2021-02-17 17:20 UTC
**PS: Please correct the report as this is my first time**

Hy team,

I have a previously created cloudfront distribution with forwarded_values values enabled.

    forwarded_values {
      query_string = true

      cookies {
        forward = "none"
      }
    }

Now when I try to implement cache_policy_id = xxxxx to be distribution by setting

    forwarded_values {
      query_string = none
      headers = null

      cookies {
        forward = "none"
      }
    }

Once I apply this, I get the following error.
```
Warning: Applied changes may be incomplete

The plan was created with the -target option in effect, so some changes
requested in the configuration may have been ignored and the output values may
not be fully updated. Run the following command to verify that no other
changes are pending:                                                               
    terraform plan                                                                 

Note that the -target option is not suitable for routine use, and is provided
only for exceptional situations such as recovering from errors or mistakes, or
when Terraform specifically suggests to use it as part of an error message.


Error: error updating CloudFront Distribution (EQ3US9107CM6F): InvalidArgument: The parameter ForwardedValues cannot be used when a cache policy is associated to the cache behavior.
        status code: 400, request id: 05af011a-723d-40db-b3b1-94a0cf6881f6
```

But when I create new distribution with only `cache_policy_id = xxxxx` it works fine.

Is there a way to implement `cache_policy_id = xxxxx` id on the previously created cloudfront distribution by disabling `forwarded_values` ??

**Comment by ewbankkit** [comment] 2021-02-17 21:50
Related:

* https://github.com/hashicorp/terraform-provider-aws/issues/14373

**Comment by billy-reilly** [comment] 2021-02-17 22:13
this is a duplicate of https://github.com/hashicorp/terraform-provider-aws/issues/17626

**Comment by ewbankkit** [comment] 2021-02-17 22:30
@M-A-N-I-S-H-K Thanks for raising this issue.
It has already been noticed in #17626. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Closed by ewbankkit** 2021-02-17 22:30 UTC
Labels: bug, needs-triage, service/cloudfront
