### ISSUE TITLE
Lex resources are not tagged

### ISSUE THREAD

**Issue by johnboy007** [hashicorp/terraform-provider-aws#16378] opened 2020-11-23 15:05 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It looks like the resource tags for Lex are not there

### New or Affected Resource(s)

* aws_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by bflad** [comment] 2020-11-24 21:46
Hi @johnboy007 👋  Thank you for submitting this feature request. This appears to be a duplicate of https://github.com/hashicorp/terraform-provider-aws/issues/15393, so to consolidate discussions and efforts, I'm going to close this issue in preference of the existing one. Please feel free to 👍  react and subscribe there for further updates.

**Closed by bflad** 2020-11-24 21:46 UTC
Labels: enhancement, needs-triage
