### ISSUE TITLE
data resource: aws_s3_bucket support filters

### ISSUE THREAD

**Issue by KVInventoR** [hashicorp/terraform-provider-aws#22790] opened 2022-01-27 08:04 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to have specific filter inside data resource for data resource: aws_s3_bucket to select group of s3 buckets and apply some changes to all of them. It's similar to which we have right now for data. aws_vpc where we can select required vpc over filter

### New or Affected Resource(s)

* data.aws_s3_bucket

### Potential Terraform Configuration

```hcl
data "aws_s3_bucket" "buckets" {
  filter {
    name   = "tag:Name"
    values = "data_users-*"
  }
}


```

**Comment by justinretzolk** [comment] 2022-01-27 20:12
Hey @KVInventoR 👋 Thanks for taking the time to submit this issue. It looks like this is a duplicate of #15544. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #15544.

**Closed by justinretzolk** 2022-01-27 20:12 UTC
Labels: enhancement, service/s3, needs-triage
