### ISSUE TITLE
aws_api_gateway_integration_response selection pattern "-" is not saved in the tfstate

### ISSUE THREAD

**Issue by Robinspecteur** [hashicorp/terraform-provider-aws#14204] opened 2020-07-16 11:01 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When defining a default integration response in AWS API Gateway, it is mentioned in the docs that the `selection_pattern` should be `-`. 

But every time a plan is applied, this change appears:

```
 Terraform will perform the following actions:
  # aws_api_gateway_integration_response.response_200 will be updated in-place
  ~ resource "aws_api_gateway_integration_response" "response_200" {
    ...
      + selection_pattern   = "-"
    ...
    }
```
Even though the resource was not modified. With `terraform show`, we can see that this `aws_api_gateway_integration_response` property is never saved in the actual terraform state.

To avoid this issue, setting `selection_pattern = ""` or even not setting this property makes the response the default one. 

In the [AWS API Documents for the Selection Pattern](https://docs.aws.amazon.com/apigateway/api-reference/resource/integration-response/#selectionPattern) parameter there's no mention of being able to pass in a `-` to reset the pattern to default (what if our regex is a hyphen?).

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.12.25
+ provider.aws v2.58.0
```

### Affected Resource(s)

* aws_api_gateway_integration_response

**Comment by tierra** [comment] 2021-01-11 23:50
This is a duplicate of #10222

**Closed** 2021-01-21 19:59 UTC
Labels: documentation, service/apigateway

**Comment by bflad** [comment] 2021-01-21 20:03
The `aws_api_gateway_integration_response` documentation has been updated to remove the `"-"` mention for the `selection_pattern` argument, especially since that is not documented by AWS. To specify the resource as the default, simply do not set `selection_pattern` in the resource configuration (or set it equal to `null` in a conditional). 👍
