### ISSUE TITLE
aws_sagemaker_user_profile is not created with same way as web

### ISSUE THREAD

**Issue by xelite** [hashicorp/terraform-provider-aws#26570] opened 2022-08-31 12:47 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform 1.1.9
aws 4.18.0

### Affected Resource(s)

* aws_sagemaker_user_profile

### Terraform Configuration Files

```hcl
resource "aws_sagemaker_user_profile" "profile" {
  for_each                  = toset(var.members)
  domain_id                 = aws_sagemaker_domain.domain.id
  single_sign_on_user_value = each.value
  user_profile_name              = replace(each.value, "/@|\\./", "-")
  single_sign_on_user_identifier = "UserName"
}

resource "aws_sagemaker_domain" "domain" {
  domain_name = var.domain_name
  auth_mode   = "SSO"
  subnet_ids  = var.subnet_ids
  vpc_id      = var.vpc_id

  default_user_settings {
    execution_role = aws_iam_role.default.arn
  }
}

resource "aws_iam_role" "default" {
  name               = var.execution_role_name
  path               = "/"
  assume_role_policy = data.aws_iam_policy_document.default.json
  managed_policy_arns = [
    "arn:aws:iam::aws:policy/job-function/DataScientist",
    "arn:aws:iam::aws:policy/AWSCodeCommitPowerUser",
  ]
}

data "aws_iam_policy_document" "default" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["sagemaker.amazonaws.com"]
    }
  }
}

resource "aws_sagemaker_app" "app" {
  for_each          = toset(var.members)
  domain_id         = aws_sagemaker_domain.domain.id
  user_profile_name = aws_sagemaker_user_profile.profile[each.value].user_profile_name
  app_name          = "default"
  app_type          = "JupyterServer"
}

variable "members" {
  description = "Users from domain allowed to use SageMaker with SSO"
  type        = list(string)
  default     = [
    "user@corp",
  ]
}

```

### Actual Behavior

Apply ends with success but user have no access to lanch app (studio).
```
Access Denied. Please check if user is assigned to Studio Domain [d-6e8cv4cx4llj] and SSO Application [Amazon SageMaker Studio (d-6e8cv4cx4llj)] is Active.
```
When user is added from web console (Sagemaker → Control panel → Assign users and groups) lanch app (studio) works.

**Comment by daipra** [comment] 2022-10-07 09:41
Something is missing from the resource. If I add any number of User Profiles with Terraform, the users appear in the UI, but are not functional, as mentioned by @xelite 
Yet, if I add one <user-X> via UI, all those users that were added by Terraform, suddenly become available. Later I can remove <user-X> and the Terraform-added users are still functional.

It looks the Terraform way does not invoke some kind of sync between Sagemaker Domain and AWS SSO, which is only simulated by manually adding a user in the UI.

**Comment by daipra** [comment] 2022-10-10 10:15
Here is a similar issue with Cloud Formation: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1128 

It seems like `AssociateProfile` API is not being called.

**Comment by DrFaust92** [comment] 2022-11-26 20:12
@daipra can you share where are the docs for AssociateProfile? i dont not see such an api in sagemaker docs

**Comment by daipra** [comment] 2022-11-28 21:19
@DrFaust92 It's the first line here: https://docs.aws.amazon.com/singlesignon/latest/userguide/security-authorization.html
But it seems it was renamed to `CreateAccountAssignment`: https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_CreateAccountAssignment.html

...however in CloudTrail, it's still seen as `AssociateProfile`. 
I have to admit, it's not very clearly documented.

**Comment by mmandada** [comment] 2022-12-01 08:48
We have similar issue, where users getting added with terraform wouldn't see the SSO sagemaker tile. Whereas adding them from console works fine.

**Comment by DrFaust92** [comment] 2022-12-01 09:40
From what i gather from [daipra](https://github.com/daipra) comment this is not an issue with the resource. if the UI does a trick and calls another API (for a different service even) this should also be done in TF. [aws_ssoadmin_account_assignment](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssoadmin_account_assignment) is an existing resource and can be used here if needed

**Comment by DrFaust92** [comment] 2022-12-01 09:42
removing bug label for now as it seems like UI magic

**Comment by daipra** [comment] 2022-12-01 11:29
@DrFaust92 it's probably true. The same behavior can be reproduced using boto3 (https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker.html#SageMaker.Client.create_user_profile), so the problem is not confined to Terraform.

**Comment by DrFaust92** [comment] 2022-12-03 18:03
Im option to close this issue as there is no issue in the provider, if there is an action for provider please open a new issue with details as possible resolution is given above.

**Closed by DrFaust92** 2022-12-03 18:03 UTC
Labels: upstream, service/sagemaker
