### ISSUE TITLE
aws_launch_configuration public IP address association issue with provider version 4.18

### ISSUE THREAD

**Issue by antonioned** [hashicorp/terraform-provider-aws#25324] opened 2022-06-14 13:27 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.2.2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v4.18.0
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.3.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/time v0.7.2

### Affected Resource(s)

* aws_launch_configuration

### Terraform Configuration Files

```hcl
resource "aws_launch_configuration" "rabbitmq" {
  name_prefix          = "${var.name}-"
  image_id             = var.instance_ami_image_id
  instance_type        = var.instance_type
  key_name             = var.instance_key_name
  security_groups      = concat([aws_security_group.rabbitmq_nodes.id], var.nodes_additional_security_group_ids)
  iam_instance_profile = aws_iam_instance_profile.asg.id
  user_data            = local.user_data
  ebs_optimized        = true

  root_block_device {
    volume_type           = var.instance_volume_type
    volume_size           = var.instance_volume_size
    iops                  = var.instance_volume_iops
    delete_on_termination = true
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_autoscaling_group" "asg" {
  name = var.name

  depends_on = [
    aws_iam_role_policy.asg
  ]

  min_size                  = var.cluster_size
  desired_capacity          = var.cluster_size
  max_size                  = var.cluster_size
  health_check_grace_period = 300
  health_check_type         = "ELB"
  force_delete              = true
  launch_configuration      = aws_launch_configuration.rabbitmq.name
  load_balancers            = [aws_elb.elb.name]
  vpc_zone_identifier       = var.subnet_ids
  default_cooldown          = 300
  termination_policies      = ["OldestInstance", "OldestLaunchConfiguration"]

  lifecycle {
    create_before_destroy = true
  }
}

module "rabbitmq-ephemeral" {
  source = "./modules/rabbitmq"
  .
  .
  .
  subnet_ids                          = module.vpc.subnet-ids-public
  .
  .
}

output "subnet-ids-public" {
  value = aws_subnet.public[*].id
}

resource "aws_subnet" "public" {
  count = length(local.azs)

  availability_zone = element(local.azs, count.index)
  cidr_block        = cidrsubnet(var.cidr, 4, count.index)
  vpc_id            = aws_vpc.main.id

  map_public_ip_on_launch = "true"
}
```

### Expected Behavior

Applying the code using aws provider version `3.75.2` sets the `IP address type` to default, meaning it will use the setting from the subnet, which is associate a public IP (public subnet)
 
<img width="789" alt="provider-3 75 2" src="https://user-images.githubusercontent.com/33669423/173588235-59b3f915-0f12-4c9b-9572-501878cd1b53.png">

### Actual Behavior

Applying the same code with provider version `4.18` sets this parameter to `false`, meaning it does not associate a public IP address to the instances

<img width="871" alt="provider-4 18" src="https://user-images.githubusercontent.com/33669423/173588443-569a8352-4922-4278-a6a3-890c597d31d1.png">

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by justinretzolk** [comment] 2022-06-16 19:59
Hey @antonioned 👋 Thanks for taking the time to submit this issue. It looks like this is a duplicate of #25244. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #25244.

**Closed by justinretzolk** 2022-06-16 19:59 UTC
Labels: service/autoscaling, needs-triage, service/vpc
