### ISSUE TITLE
[Bug]: Error: Invalid AWS Region: ap-south-2 when using terraform s3 backend with ap-south-2 region bucket and dynamodb table

### ISSUE THREAD

**Issue by amoldesai1993** [hashicorp/terraform-provider-aws#32374] opened 2023-07-05 09:15 UTC
### Terraform Core Version

1.4.6

### AWS Provider Version

4.65.0

### Affected Resource(s)

 backend "s3" {
    bucket = "exampl-hyd"
    key    = "example/terraform.tf_state"
    region = "ap-south-2"
  }

### Expected Behavior

Initializing provider plugins...
- Finding hashicorp/aws versions matching "4.65.0"...
- Installing hashicorp/aws v4.65.0...
- Installed hashicorp/aws v4.65.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

### Actual Behavior

terraform init --reconfigure

Initializing the backend...
Initializing modules...
╷
│ Error: Invalid AWS Region: ap-south-2
│
│
╵

### Terraform Configuration Files

NA

### Steps to Reproduce

NA

### Would you like to implement a fix?

None

**Comment by shivtarevikram** [comment] 2023-07-05 09:58
@hashicorp-cloud - I am also facing the same issue. Please help in resolving the same.

**Comment by justinretzolk** [comment] 2023-07-05 21:09
Hey @amoldesai1993 and @shivtarevikram 👋 Thank you for taking the time to report this. Since this relates to the S3 Backend of Terraform, this issue will need to be raised in the Terraform Core repository. I was, however, able to locate an issue that was already raised in that repository (https://github.com/hashicorp/terraform/issues/33349). Since this is a duplicate of that issue, I'll close this one out. Please feel free to react to that issue with the 👍 emoji to aid in prioritization.

**Closed by justinretzolk** 2023-07-05 21:09 UTC
Labels: bug, needs-triage
