### ISSUE TITLE
[Enhancement]: Service Account Resource for Managed Grafana

### ISSUE THREAD

**Issue by lorrrrrrrenzo** [hashicorp/terraform-provider-aws#37808] opened 2024-06-03 13:59 UTC
### Description

The [recent release of Managed Grafana 10](https://aws.amazon.com/blogs/mt/amazon-managed-grafana-announces-support-for-grafana-version-10-4/) introduces the ability to use Grafana Service Accounts and Service Account Tokens for improved authn/z. I am proposing that support for this new authentication method be added to the AWS provider, with an eye towards making sure it integrates well with the [Grafana provider](https://registry.terraform.io/providers/grafana/grafana/latest/docs), which according to its documentation, already supports authentication with Service Account Tokens. 

### Affected Resource(s) and/or Data Source(s)

* `aws_grafana_workspace`
* `aws_grafana_service_account` (new)

### Potential Terraform Configuration

```terraform
resource "aws_grafana_workspace" "example" {
  account_access_type      = "CURRENT_ACCOUNT"
  authentication_providers = ["SAML"]
  permission_type          = "SERVICE_MANAGED"
  role_arn                 = aws_iam_role.assume.arn
}

resource "aws_grafana_service_account" "example_admin" {
  workspace_id = aws_grafana_workspace.example.id
  role = "ADMIN"
}

// service account tokens can be created programmatically as needed with 
// aws grafana create-workspace-service-account-token, as part of CI
```

### References

https://registry.terraform.io/providers/grafana/grafana/latest/docs

https://aws.amazon.com/blogs/mt/amazon-managed-grafana-announces-support-for-grafana-version-10-4
(Look at the section "Service Accounts and new APIs" for an example of the new authentication flow)

https://grafana.com/docs/grafana/v10.4/administration/service-accounts/

### Would you like to implement a fix?

None

**Comment by aristosvo** [comment] 2024-06-03 20:22
I'll try to pick this up. This requires a move to SDK v2, I'll pick that up first.

**Comment by aristosvo** [comment] 2024-06-04 16:59
Hi @lorrrrrrrenzo 👋 

The reason is [explained in this issue](https://github.com/hashicorp/terraform-provider-aws/issues/32917), new resources are not accepted when using the old SDK.

**Comment by aristosvo** [comment] 2024-06-06 06:51
Hi @lorrrrrrrenzo!

I think this one can be closed, as https://github.com/hashicorp/terraform-provider-aws/issues/37645 is an extended duplicate of this one.

In the meantime the AWS SDK Go PR is ready for review, so things are in progress 👍🏽

**Closed as not planned** 2024-06-06 07:39 UTC
Labels: enhancement, service/grafana
