### ISSUE TITLE
aws macie2 classification job to support bucket_criteria

### ISSUE THREAD

**Issue by albert-salman** [hashicorp/terraform-provider-aws#21979] opened 2021-12-01 08:23 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS provider aws_macie2_classification_job do not support bucket_criteria
https://docs.aws.amazon.com/macie/latest/APIReference/jobs.html#jobs-prop-s3jobdefinition-bucketcriteria

which is a handful way to manage classification jobs

### New or Affected Resource(s)

aws_macie2_classification_job

### Potential Terraform Configuration

Cfg is very same as aws_macie2_classification_job -> s3_job_definition -> scoping, which is already supported

### References

https://docs.aws.amazon.com/macie/latest/APIReference/jobs.html#jobs-prop-s3jobdefinition-bucketcriteria

**Comment by cacack** [comment] 2022-07-15 12:08
Duplicate of #19837

**Closed** 2022-08-08 13:57 UTC
Labels: enhancement, service/macie2
