### ISSUE TITLE
[Bug]: Unable to update storage gateway SMB acl_enabled  flag 

### ISSUE THREAD

**Issue by johnlister** [hashicorp/terraform-provider-aws#36385] opened 2024-03-14 20:49 UTC
### Terraform Core Version

1.6.3

### AWS Provider Version

5.40.0

### Affected Resource(s)

aws_storagegateway_smb_file_share

### Expected Behavior

changing the value of the **smb_acl_enabled** flag should update the resource

### Actual Behavior

provider crashes

### Relevant Error/Panic Output Snippet

```shell
│ Error: Request cancelled
│
│   with aws_storagegateway_smb_file_share.etl_bucket_smb[0],
│   on fileshares.tf line 75, in resource "aws_storagegateway_smb_file_share" "etl_bucket_smb":
│   75: resource "aws_storagegateway_smb_file_share" "etl_bucket_smb" {
│
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-aws_v5.40.0_x5 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 113 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/storagegateway.resourceSMBFileShareUpdate({0x12c75828, 0xc0040d6d80}, 0xc003cfc700, {0x111f4e20?, 0xc003839180?})
        github.com/hashicorp/terraform-provider-aws/internal/service/storagegateway/smb_file_share.go:386 +0x152f
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).Update.interceptedHandler[...].func10(0x0?, {0x111f4e20?, 0xc003839180?})
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:112 +0x283
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x12c75828?, {0x12c75828?, 0xc003f8cdb0?}, 0xd?, {0x111f4e20?, 0xc003839180?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:807 +0x7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc001b36700, {0x12c75828, 0xc003f8cdb0}, 0xc003b040d0, 0xc003cfc400, {0x111f4e20, 0xc003839180})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:919 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0038480d8, {0x12c75828?, 0xc003f8ccc0?}, 0xc000a93400)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/grpc_provider.go:1078 +0xdbc
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0x12c75860?, {0x12c75828?, 0xc003f8c9c0?}, 0xc000a93400)
        github.com/hashicorp/terraform-plugin-mux@v0.15.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001b3aa00, {0x12c75828?, 0xc004194210?}, 0xc0008d8070)
        github.com/hashicorp/terraform-plugin-go@v0.22.0/tfprotov5/tf5server/server.go:846 +0x3d0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x10fa0000?, 0xc001b3aa00}, {0x12c75828, 0xc004194210}, 0xc0041c8000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.22.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:518 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc001582a00, {0x12c75828, 0xc004194180}, {0x12cab618, 0xc003980680}, 0xc0041ac000, 0xc0038e3830, 0x1acd67b8, 0x0)
        google.golang.org/grpc@v1.62.0/server.go:1383 +0xe03
google.golang.org/grpc.(*Server).handleStream(0xc001582a00, {0x12cab618, 0xc003980680}, 0xc0041ac000)
        google.golang.org/grpc@v1.62.0/server.go:1794 +0x100c
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.62.0/server.go:1027 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 42
        google.golang.org/grpc@v1.62.0/server.go:1038 +0x135

Error: The terraform-provider-aws_v5.40.0_x5 plugin crashed!
```

### Terraform Configuration Files

```terraform
resource "aws_storagegateway_smb_file_share" "etl_bucket_smb" {
  count = contains(local.shared_buckets, lower("cpp-${var.environment}-india-etl")) ? 1 : 0

  authentication        = "ActiveDirectory"
  gateway_arn           = "arn:aws:storagegateway:${data.aws_region.current.name}:${data.aws_caller_identity.current.id}:gateway/${var.storage_gateway_id}"
  location_arn          = lower("arn:aws:s3:::cpp-${var.environment}-india-etl")
  role_arn              = local.fileshare_role.arn
  vpc_endpoint_dns_name = var.s3_interface_dns_name
  bucket_region         = data.aws_region.current.name
  audit_destination_arn = local.audit_log_group_arn
  file_share_name       = lower("${var.environment}-etl")
  smb_acl_enabled       = true

  # authentication
  admin_user_list = lookup(var.share_admin_roles, lower("cpp-${var.environment}-india-etl"), null)
  valid_user_list = concat(
    lookup(var.authorised_gateway_users, lower("cpp-${var.environment}-india-etl"), []),
    [for group in lookup(var.authorised_gateway_groups, lower("cpp-${var.environment}-india-etl"), []) : "@${group}"]
  )
  invalid_user_list = concat(
    lookup(var.denied_gateway_users, lower("cpp-${var.environment}-india-etl"), []),
    [for group in lookup(var.denied_gateway_groups, lower("cpp-${var.environment}-india-etl"), []) : "@${group}"]
  )

  tags = merge(
    {
      Name = "${var.environment} ETL Bucket Share"
    },
    local.common_tags
  )
}
```

### Steps to Reproduce

run the terraform and change the value from false to true

### Would you like to implement a fix?

None

**Comment by acwwat** [comment] 2024-05-20 17:33
I believe the crash is actually not caused by changing `smb_acl_enabled`, but caused by removing the `cache_attributes` block in an update scenario. I've checked in a fix for the crash, however there is still another issue where the previously set `cache_attributes` value will not be removed on the AWS resource even if you remove the block from the Terraform configuration. That's more of an AWS-side issue and should be separately addressed.

**Closed** 2024-05-22 15:30 UTC
Labels: bug, crash, service/storagegateway
