### ISSUE TITLE
Add aws_elasticache_replication_group.reader_endpoint_address

### ISSUE THREAD

**Issue by rquadling** [hashicorp/terraform-provider-aws#15513] opened 2020-10-06 11:50 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I want to provide read only access to the AWS Elasticache cluster in a way that I can already do for RDS. Get the "reader" endpoint, attach it to the DNS and job done. More or less.

With the current provider, the reader endpoint is not accessible.

`aws describe-replication-groups --query='ReplicationGroups[0].NodeGroups[0].ReaderEndpoint.Address'` is the current data that I want to get to.

### New or Affected Resource(s)

* aws_elasticache_replication_group (resource)
* aws_elasticache_replication_group (data source)

### Potential Terraform Configuration

Unsure what to put here.

### References

* #15515

**Comment by rquadling** [comment] 2020-10-23 16:26
@anGie44 Is there a way to get some more eyes on this and get it merged/released? Happy to do more work on it if it is required.

**Comment by gdavison** [comment] 2021-01-05 23:41
This is a duplicate of #10519, which was resolved with PR #9979

**Closed by gdavison** 2021-01-05 23:41 UTC
Labels: enhancement, service/elasticache
