### ISSUE TITLE
Resource: aws_ecs_cluster execute_command_configuration needs at least kms_key_id (needs docu update)

### ISSUE THREAD

**Issue by eocern** [hashicorp/terraform-provider-aws#22400] opened 2022-01-04 12:32 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
terraform -v
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/archive v2.0.0
+ provider registry.terraform.io/hashicorp/aws v3.70.0
+ provider registry.terraform.io/hashicorp/random v3.0.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.0.0
+ provider registry.terraform.io/vancluever/acme v2.4.0

From  aws_ecs_cluster terraform documentation https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_cluster
I just added 
```
resource "aws_ecs_cluster" "ecs-cluster" {
  name = "example"

  configuration {
    execute_command_configuration {
 
    }
  }
}

```
and terraform apply crashed with `"panic: interface conversion: interface {} is nil, not map[string]interface {}"`

It looks that at least "kms_key_id" needs to be added while on the documentation page it states that this is optional. 
So now the following works fine 

```
resource "aws_ecs_cluster" "ecs-cluster" {
  name = "example"

  configuration {
    execute_command_configuration {
       kms_key_id = aws_kms_key.example.arn 
    }
  }
}
```

**Comment by justinretzolk** [comment] 2022-01-12 19:43
Hey @eocern 👋 Thank you for taking the time to file this. In this case, the error is caused by effectively setting `aws_ecs_cluster.example.configuration.execute_command_configuration` to a `nil` value (`{}`), rather than a need to have `kms_key_id` set. For example, the following configuration applies without issue:

```hcl
resource "aws_ecs_cluster" "ecs-cluster" {
  name = "example"

  configuration {
    execute_command_configuration {
      logging    = "NONE"
    }
  }
}
```

If you're not looking to configure any part of the `configuration.execute_command_configuration`, it can be omitted from the configuration entirely, for example:

```hcl
resource "aws_ecs_cluster" "ecs-cluster" {
  name = "example"
}
```

In this case, I believe the documentation is accurate, so we'll close this issue. If you feel we've done this in error, please do let us know.

**Closed by justinretzolk** 2022-01-12 19:43 UTC
Labels: bug, crash, service/ecs, needs-triage
