### ISSUE TITLE
transport connection broken: too many transfer encodings["chunked" "chunked"]

### ISSUE THREAD

**Issue by m-wynn** [hashicorp/terraform-provider-aws#17010] opened 2021-01-07 20:15 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -v
Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/aws v3.22.0
```

### Affected Resource(s)

* aws_db_proxy

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_db_proxy" "my_proxy" {
  name                   = "my-proxy"
  debug_logging          = true
  engine_family          = "MYSQL"
  idle_client_timeout    = 1800
  require_tls            = false
  role_arn               = var.role_arn
  vpc_security_group_ids = var.proxy_security_group_ids
  vpc_subnet_ids         = var.db_subnet_ids
  auth {
    auth_scheme = "SECRETS"
    description = "example"
    iam_auth    = "DISABLED"
    secret_arn  = var.secret_arn
  }
}
```

### Debug Output

https://gist.github.com/m-wynn/87aa1417f17ad36b1b165f70678c6874
The important part is `2021-01-07T12:03:25.362-0800 [DEBUG] plugin.terraform-provider-aws_v3.22.0_x5: caused by: Post "https://rds.us-east-1.amazonaws.com/": net/http: HTTP/1.x transport connection broken: too many transfer encodings: ["chunked" "chunked"]`

### Expected Behavior

The resource should be read.  I can easily read this resource with aws-cli, e.g. `aws rds describe-db-proxies --db-proxy-name my-proxy `

### Actual Behavior

The module hangs on trying to describe DB Proxies

### Steps to Reproduce

 I am unable to find the exact steps that led to the encodings being ["chunked" "chunked"]

--->

**Comment by bflad** [comment] 2021-01-07 20:54
Briefly, this behavior is reproducible with our acceptance testing against `us-west-2`:

```
=== CONT  TestAccAWSDBProxy_basic
resource_aws_db_proxy_test.go:480: unexpected PreCheck error: RequestError: send request failed
caused by: Post "https://rds.us-west-2.amazonaws.com/": net/http: HTTP/1.x transport connection broken: too many transfer encodings: ["chunked" "chunked"]
--- FAIL: TestAccAWSDBProxy_basic (3096.76s)
```

Here's the debug logging from the first invocation there:

```
2021/01/07 07:18:47 [DEBUG] [aws-sdk-go] DEBUG: Request rds/DescribeDBProxies Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: rds.us-west-2.amazonaws.com
User-Agent: aws-sdk-go/1.36.19 (go1.15.5; linux; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.11+compatible (+https://www.terraform.io)
Content-Length: 43
Authorization: AWS4-HMAC-SHA256 Credential=AKIAS--OMITTED--/20210107/us-west-2/rds/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date, Signature=--OMITTED--
Content-Type: application/x-www-form-urlencoded; charset=utf-8
X-Amz-Date: 20210107T071847Z
Accept-Encoding: gzip

Action=DescribeDBProxies&Version=2014-10-31
-----------------------------------------------------
2021/01/07 07:18:47 [DEBUG] [aws-sdk-go] DEBUG: Send Request rds/DescribeDBProxies failed, attempt 0/25, error RequestError: send request failed
caused by: Post "https://rds.us-west-2.amazonaws.com/": net/http: HTTP/1.x transport connection broken: too many transfer encodings: ["chunked" "chunked"]
2021/01/07 07:18:47 [DEBUG] [aws-sdk-go] DEBUG: Retrying Request rds/DescribeDBProxies, attempt 1
```

We don't do anything special in the `aws_db_proxy` resource as compared to other resources with regards to initializing or calling the AWS Go SDK receiver methods, and this has previously worked fine, so it may either be:

* An issue with this particular AWS API after an API update
* An issue that actually exists for all AWS Go SDK calls through the Terraform AWS Provider, but other AWS APIs ignore it and this API's update now catches it

**Comment by bflad** [comment] 2021-01-07 21:13
Given the `Transfer-Encoding` HTTP header is not showing up in the request logging, it likely would be part of the HTTP response from the RDS API. What's interesting is that AWS CLI debug logging does not contain the header, but oddly does seem to contain a duplicate request IDs in that header (which could potentially indicate some sort of duplicate handling happening on the API side):

```console
$ aws --debug rds describe-db-proxies
2021-01-07 16:07:32,085 - MainThread - botocore.parsers - DEBUG - Response headers: {'x-amzn-RequestId': 'd37dc89d-dc04-44ac-85b0-9629c53a216e, d37dc89d-dc04-44ac-85b0-9629c53a216e', 'Date': 'Thu, 07 Jan 2021 21:07:32 GMT', 'Connection': 'keep-alive', 'Content-Type': 'text/xml', 'Content-Length': '287'}
```

Per [RFC 7230](https://tools.ietf.org/html/rfc7230#section-3.3.1):

> A sender MUST NOT apply chunked more than once to a message body (i.e., chunking an already chunked message is not allowed).

Go's `net/http` library implements logic around only allowing a single `Transfer-Encoding` header here, which is where the error is being generated:

https://github.com/golang/go/blob/fa90aaca7d523eaf81c02b48a412cad4ebc57817/src/net/http/transfer.go#L634-L643

It might be best to open an AWS Support case here.

**Comment by m-wynn** [comment] 2021-01-08 18:30
This morning I noticed that the error only happens on the latest versions of the terraform-provider-aws (3.22 and 3.23).  I was unable to reproduce it with 3.20 and 3.21.

**Comment by bflad** [comment] 2021-01-08 19:13
@m-wynn thank you for that additional information. We did update the provider build process from Go 1.14.5 to Go 1.15.5 between those releases: https://github.com/hashicorp/terraform-provider-aws/compare/v3.21.0...v3.22.0#diff-69c69535f549f1e70ce037415e46a2894f04d4147c7929de6ef1db8f72a0a136

Buried in the [Go 1.15 release notes](https://golang.org/doc/go1.15#net/http) is this:

> Parsing is now stricter as a hardening measure against request smuggling attacks: non-ASCII white space is no longer trimmed like SP and HTAB, and support for the "identity" Transfer-Encoding was dropped.

I'm not sure we would necessarily revert back Go releases as 1.14 will be falling out of its support period in the coming months and the standard library fix seems to be security related.

**Comment by bflad** [comment] 2021-01-12 03:18
Hi @m-wynn 👋  This appears to be working as expected now in `us-east-1` and `us-west-2` regions. Can you confirm it is working correctly in your environment?

**Comment by m-wynn** [comment] 2021-01-12 19:36
Hey @bflad, I am still seeing this issue in `us-east-1`, unfortunately.

**Comment by bflad** [comment] 2021-01-12 19:44
@m-wynn I'd suggest opening an AWS Support case with the request ID then -- given its intermittency it could just be there are some incorrectly deployed API servers they need to fix.

**Comment by cdobbyn** [comment] 2021-01-19 07:08
I'm also seeing this with 3.24.1, going to try rolling back to 3.21 and see if the problem is till present. It's the exact same request location as well.
```
2021-01-18T23:04:51.141-0800 [INFO]  plugin.terraform-provider-aws_v3.24.1_x5: 2021/01/18 23:04:51 [DEBUG] [aws-sdk-go] DEBUG: Send Request rds/DescribeDBProxies failed, attempt 13/25, error RequestError: send request failed
caused by: Post "https://rds.us-east-1.amazonaws.com/": net/http: HTTP/1.x transport connection broken: too many transfer encodings: ["chunked" "chunked"]: timestamp=2021-01-18T23:04:51.141-0800
```

**Comment by cdobbyn** [comment] 2021-01-19 07:11
I can confirm rolling back to 3.21 has fixed the problem.

**Comment by cdobbyn** [comment] 2021-01-19 07:19
I can also confirm that rolling forward to 3.24.1 has re-introduced the problem. It looks like as long as I'm targetting a DB proxy or just trying to plan against the whole state it'll cause this problem.

**Comment by cdobbyn** [comment] 2021-01-19 09:00
To add some more context to this, it's happening to a db proxy with a large number of "auth" blocks (25 of them) and it's happening 100% of the time (not intermittent). @m-wynn is your's like that too? I've got one more over in `us-west-2` but it only has 2 auths. I'll spin up one in us-east-1 tomorrow with 1 auth and see what happens.

If I do this query using the CLI (`aws-cli/2.0.47`), the "DBProxies" maps are returned quite differently between my `us-east-1` instance and my `us-west-2` instance. There's are two different auth sections in the `us-east-1` at different levels of the json. Very weird.
```
aws rds describe-db-proxies --db-proxy-name <my-us-east-1-proxy>
```

**Comment by m-wynn** [comment] 2021-01-19 19:42
@cdobbyn I only have RDS proxies with 3 auths (in us-east-1), and am seeing this problem with those.

I have had an AWS Support ticket open since the 7th, but unfortunately not a lot of progress on it.

**Comment by cdobbyn** [comment] 2021-01-25 06:50
@m-wynn @bflad It looks like this is an issue between aws go sdk and the aws api. It also appears to be only happening in several specific regions (us-east-1). We were able to replicate the issue on both an old db proxy and a brand new one. I have a support ticket open for this. If I hear about any update to aws go sdk update to fix this I'll post it here.

**Comment by willhughes-au** [comment] 2021-01-27 23:01
Can confirm I'm encountering this also in ap-southeast-2. 

Terraform version: 0.13.5
Terraform AWS Module version 3.24.1

**Comment by bgaillard** [comment] 2021-02-16 11:48
We also encounter this problem on region `eu-west-1`.

Terraform version: 0.14.2
Terraform AWS Module version 3.28.0

**Comment by Simonl9l** [comment] 2021-02-17 02:11
same in west-us-2, reverted to 3.21.0 per @bgaillard above would be good to get an authoritative response on a plan to fix this issue, as were quite a way behind with this versions...

**Comment by willthames** [comment] 2021-03-02 06:49
This happens when the response from the DescribeDbProxyTargetInputs is too long (I think it's somewhere in the region of 3 or more targets, might be 4 or more)

I have raised this with AWS too, no progress so far. 

A go test case is

```
package main

import (
	"fmt"
	"os"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/rds"
)

func main() {
	sess, err := session.NewSession()
	if err != nil {
		fmt.Println("Error creating session ", err)
		return
	}
	svc := rds.New(sess)
	putInput := &rds.DescribeDBProxyTargetsInput{
		DBProxyName:     aws.String(os.Args[1]),
		TargetGroupName: aws.String("default"),
	}

	out, err := svc.DescribeDBProxyTargets(putInput)
	if err != nil {
		fmt.Println("Error describing db proxy targets ", err)
		return
	}

	fmt.Printf("%v\n", out)
}
```

I'm not sure what the options are for the provider though - you can't set MaxRecords to 1 as there is a minimum value of 20. Basically the bug needs to be fixed by AWS or go (or the whole of terraform downgrades go version)

It's definitely frustrating, I want to use node14 lambdas but can't because they're not supported by v3.21.0 which we're now pinned to until this problem is solved.

**Comment by so-development** [comment] 2021-03-02 07:58
I'm facing the same issue in `eu-central-1` with 7 auth blocks.

**Comment by JamesAwesome** [comment] 2021-03-03 22:55
reproducing in `us-east-2` with 5 auth blocks, downgrading to `3.21.0` allowed me to bypass but was a massive pain as i had to re-import some resources that had breaking changes

```
Error: Invalid resource instance data in state

  on ../modules/proxy_resources/iam.tf line 5:
   5: resource "aws_iam_role" "rds_proxy" {

Instance module.analytics_rds_proxy_resources.aws_iam_role.rds_proxy data
could not be decoded from the state: unsupported attribute "inline_policy".
```

the IAM role also used `name_prefix` so I had to manually modify the terraform state as per https://github.com/hashicorp/terraform-provider-aws/issues/3206

Probably the worst experience i've had with terraform since the 0.11 -> 0.12 upgrade

**Comment by harsimranmaan** [comment] 2021-03-20 00:16
Is there a corresponding issue open with the go team?

**Comment by arkirchner** [comment] 2021-04-08 09:31
Can confirm I'm encountering this also in ap-northeast-1.

Terraform version: 0.13.4
Terraform AWS Module version 3.35.0

**Comment by sammaritan12** [comment] 2021-04-14 04:56
Hey all, I have chatted to AWS Support about this and they have informed me that they have fixed this.

I have checked it on my end and I can now create an RDS Proxy via terraform using multiple auth blocks.

**Comment by bflad** [comment] 2021-04-14 14:43
Thanks @sammaritan12 👍  Looking at our daily acceptance testing which was constantly running into this issue, the test failures also stopped for us as well earlier this week. Given that this is an API fix and that it is being rolled out, I'm going to close this issue.

For anyone who might be running into lingering `too many transfer encodings: ["chunked" "chunked"]` errors with RDS DB Proxies, our suggestion would be to reach out to AWS Support to clarify when the API fix will be rolled out.

**Closed by bflad** 2021-04-14 14:43 UTC
Labels: service/rds, upstream
