### ISSUE TITLE
Acceptance Tests: `TestAccAWSCloudWatchEventTarget_` has intermittent test failures

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#15652] opened 2020-10-14 21:15 UTC
Various `aws_cloudwatch_event_target` acceptance tests have intermittent failures when deleting Rules, especially `TestAccAWSCloudWatchEventTarget_ecs` and `TestAccAWSCloudWatchEventTarget_ecsWithBlankTaskCount` due to eventual consistency

### Affected Resource

* aws_cloudwatch_event_target

**Comment by gdavison** [comment] 2020-10-14 21:23
Might be related to #15376

**Comment by ewbankkit** [comment] 2021-05-05 12:04
This is a duplicate of #18601 and #15668.

**Closed by ewbankkit** 2021-05-05 12:05 UTC
Labels: service/cloudwatchevents, service/eventbridge
