### ISSUE TITLE
[Enhancement]: Add examples for RDS Custom for Oracle

### ISSUE THREAD

**Issue by AdamTylerLynch** [hashicorp/terraform-provider-aws#31114] opened 2023-05-02 17:12 UTC
### Description

Please add examples for RDS Custom for Oracle. Would appreciate Primary and Replica examples.

### Affected Resource(s) and/or Data Source(s)

* aws_db_instance

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment] 2023-05-03 16:47
Duplicate of #31093

**Closed by justinretzolk** 2023-05-03 16:47 UTC
Labels: enhancement, service/rds, needs-triage
