### ISSUE TITLE
[Repo]: 5.18.0 release not published in registry.terraform.io

### ISSUE THREAD

**Issue by n1ngu** [hashicorp/terraform-provider-aws#33622] opened 2023-09-26 09:00 UTC
### Description

5.18.0 was released on Sep 21th but the registry only shows 5.17.0 since Sep 14th.

Is there a problem with the registry integration?

### References

- Latest registry release: https://registry.terraform.io/providers/hashicorp/aws/latest
- 5.18 github release: https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.18.0

### Would you like to implement a fix?

No

**Comment by morremeyer** [comment] 2023-09-26 10:40
@n1ngu This is a duplicate of #33588.

**Closed** 2023-09-26 11:58 UTC
Labels: bug, provider
