### ISSUE TITLE
S3 bucket issue: Can't configure a value for "versioning": its value will be decided automatically based on the result of applying this configuration.

### ISSUE THREAD

**Issue by amamidwar** [hashicorp/terraform-provider-aws#23125] opened 2022-02-11 07:51 UTC
### Terraform CLI and Terraform AWS Provider Version

terraform script is failing with below error which is running in the provider version : 3.74.1. I have done no change in code base since last 1 year. Facing issue with new release version 4.0.0

### Affected Resource(s)

* aws_s3_bucket

### Terraform Configuration Files

Code:
```
resource "aws_s3_bucket" "secondarybucket" {
  bucket    = "${var.tId}.replicated.${var.Name}"
  provider  = aws.secondary
  force_destroy = true

  versioning {
    enabled = true
  }
```

### Panic Output

```
 Error: Value for unconfigurable attribute
│
│   with module.buckets.aws_s3_bucket.secondarybucket,
│   on ../modules/terraform-aws-s3buckets/main.tf line 100, in resource "aws_s3_bucket" "secondarybucket":
│  100: resource "aws_s3_bucket" "secondarybucket" {
│
│ Can't configure a value for "versioning": its value will be decided automatically based on the result of applying this configuration.
```

### Actual Behavior

Terraform applies policy successfully.  And create s3 buckets. 

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ksemtinimahmoud** [comment] 2022-02-11 09:13
The versioning argument is read-only as of version 4.0 of the Terraform AWS Provider. See the [aws_s3_bucket_versioning resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_versioning) for configuration details.

**Comment by diseku** [comment] 2022-02-11 09:24
is there any kind of pre-release mailing list in order not to get the surprises like this? 
i understand, that the other option would be to pin the provider version, but for most of the users it is combined with a lot of overhead

**Comment by scott-doyland-burrows** [comment] 2022-02-11 09:44
I am getting multiple errors:

```
Error: Value for unconfigurable attribute
│
│   with aws_s3_bucket.aws_s3_bucket,
│   on main.tf line 1, in resource "aws_s3_bucket" "aws_s3_bucket":
│    1: resource "aws_s3_bucket" "aws_s3_bucket" {
│
│ Can't configure a value for "versioning": its value will be decided automatically based on the result of applying this configuration.
╵
╷
│ Error: Value for unconfigurable attribute
│
│   with aws_s3_bucket.aws_s3_bucket,
│   on main.tf line 1, in resource "aws_s3_bucket" "aws_s3_bucket":
│    1: resource "aws_s3_bucket" "aws_s3_bucket" {
│
│ Can't configure a value for "server_side_encryption_configuration": its value will be decided automatically based on the result of applying this configuration.
╵
╷
│ Error: Value for unconfigurable attribute
│
│   with aws_s3_bucket.aws_s3_bucket,
│   on main.tf line 4, in resource "aws_s3_bucket" "aws_s3_bucket":
│    4:   acl           = var.s3bucket_acl
│
│ Can't configure a value for "acl": its value will be decided automatically based on the result of applying this configuration.
```

**Comment by tarunptala** [comment] 2022-02-11 11:34
yes we also experiencing this ...looks like it started post release version 4.0.0

**Comment by diseku** [comment] 2022-02-11 12:44
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-4-upgrade#s3-bucket-refactor

**Comment by erikpaasonen** [comment] 2022-02-11 13:57
for anyone impacted by this, it might be worth upvoting this issue: https://github.com/hashicorp/terraform-provider-aws/issues/23106 👍

**Comment by jwyoungpm** [comment] 2022-02-11 14:34
Saying "use terraform import" puts those with hundreds of buckets in a tough spot.

**Comment by tarunptala** [comment] 2022-02-11 16:54
we were able to temporary fix this by pinning module to exact last working version of provider.

```
required_providers {
    aws = "~> 3.74"
  }
```

**Comment by spanktar** [comment] 2022-02-11 20:17
Holy carp, they can't seriously think that this is an acceptable path forward.

**Comment by UdhavPawar** [comment] 2022-02-13 20:59
> we were able to temporary fix this by pinning module to exact last working version of provider.
> 
> ```
> required_providers {
>     aws = "~> 3.74"
>   }
> ```

Props to @tarunptala for this one. Verified work-around works great till this issue is fixed.

**Comment by justinretzolk** [comment] 2022-02-14 22:56
Hey y'all 👋 Thank you for taking the time to raise this, and for the discussion around it. It looks like this is a duplicate (to some degree; it's slightly different, but has the same root cause) of #23106. We like to keep discussions centralized where possible, so we'll close this one in favor of #23106 for now. If you feel we've done this in error, please do let us know.

**Closed by justinretzolk** 2022-02-14 22:56 UTC
Labels: service/s3, needs-triage

**Comment by panchamsheoran77** [comment] 2022-03-29 18:44
Since versioning is now read only, update your configuration to use the aws_s3_bucket_versioning resource and remove versioning and its nested arguments in the aws_s3_bucket resource:
like this : 
```
resource "aws_s3_bucket" "example" {
  bucket = "yournamehere"

   ... other configuration ...
}

resource "aws_s3_bucket_versioning" "example" {
  bucket = aws_s3_bucket.example.id
  versioning_configuration {
    status = "Enabled"
  }
}
```
