### ISSUE TITLE
aws_acm_certificate subject_alternative_names list modification fails with "invalid index" exception

### ISSUE THREAD

**Issue by fomichevmi** [hashicorp/terraform-provider-aws#15092] opened 2020-09-09 17:07 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.20
* provider.aws: version = "~> 3.5"

### Affected Resource(s)

* aws_acm_certificate
* aws_acm_certificate_validation
* aws_route53_record

### Terraform Configuration Files

tf_v1.tf

```hcl
data "aws_route53_zone" "my_domain_com" {
  name                       = "my.domain.com"
}

resource "aws_acm_certificate" "certificate_1" {
  domain_name                = "my.domian.com"
  options                    {
    certificate_transparency_logging_preference = "DISABLED"
  }
  subject_alternative_names  = [
    "url2.my.domian.com"
  ]
  validation_method          = "DNS"
}

resource "aws_acm_certificate_validation" "certificate_validation_1" {
  certificate_arn         = aws_acm_certificate.certificate_1.arn
  validation_record_fqdns = [
    aws_route53_record.primary_dns.fqdn,
    aws_route53_record.secondary_dns.fqdn
  ]
}

resource "aws_route53_record" "primary_dns" {
  allow_overwrite         = true
  name                    = aws_acm_certificate.certificate_1.domain_validation_options[0].resource_record_name
  records                 = [
    aws_acm_certificate.certificate_1.domain_validation_options[0].resource_record_value
  ] 
  ttl                     = 60
  type                    = aws_acm_certificate.certificate_1.domain_validation_options[0].resource_record_type
  zone_id                 = data.aws_route53_zone.my_domain_com.id
}

resource "aws_route53_record" "secondary_dns" {
  allow_overwrite         = true
  name                    = aws_acm_certificate.certificate_1.domain_validation_options[1].resource_record_name
  records                 = [
    aws_acm_certificate.certificate_1.domain_validation_options[1].resource_record_value
  ]
  ttl                     = 60
  type                    = aws_acm_certificate.certificate_1.domain_validation_options[1].resource_record_type
  zone_id                 = data.aws_route53_zone.my_domain_com.id
}


```

tf_v2.tf

```hcl
data "aws_route53_zone" "my_domain_com" {
  name                       = "my.domain.com"
}

resource "aws_acm_certificate" "certificate_1" {
  domain_name                = "my.domian.com"
  options                    {
    certificate_transparency_logging_preference = "DISABLED"
  }
  subject_alternative_names  = [
    "url2.my.domian.com",
    "url3.my.domian.com"
  ]
  validation_method          = "DNS"
}

resource "aws_acm_certificate_validation" "certificate_validation_1" {
  certificate_arn         = aws_acm_certificate.certificate_1.arn
  validation_record_fqdns = [
    aws_route53_record.primary_dns.fqdn,
    aws_route53_record.secondary_dns.fqdn,
    aws_route53_record.additional_dns.fqdn
  ]
}

resource "aws_route53_record" "primary_dns" {
  allow_overwrite         = true
  name                    = aws_acm_certificate.certificate_1.domain_validation_options[0].resource_record_name
  records                 = [
    aws_acm_certificate.certificate_1.domain_validation_options[0].resource_record_value
  ] 
  ttl                     = 60
  type                    = aws_acm_certificate.certificate_1.domain_validation_options[0].resource_record_type
  zone_id                 = data.aws_route53_zone.my_domain_com.id
}

resource "aws_route53_record" "secondary_dns" {
  allow_overwrite         = true
  name                    = aws_acm_certificate.certificate_1.domain_validation_options[1].resource_record_name
  records                 = [
    aws_acm_certificate.certificate_1.domain_validation_options[1].resource_record_value
  ]
  ttl                     = 60
  type                    = aws_acm_certificate.certificate_1.domain_validation_options[1].resource_record_type
  zone_id                 = data.aws_route53_zone.my_domain_com.id
}

 resource "aws_route53_record" "additional_dns" {
   allow_overwrite         = true
   name                    = aws_acm_certificate.certificate_1.domain_validation_options[2].resource_record_name
   records                 = [
     aws_acm_certificate.certificate_1.domain_validation_options[2].resource_record_value
   ]
   ttl                     = 60
   type                    = aws_acm_certificate.certificate_1.domain_validation_options[2].resource_record_type
   zone_id                 = data.aws_route53_zone.my_domain_com.id
}

```

### Expected Behavior

Certificate should be modified to support 2nd alternative name

### Actual Behavior

fails with following error:
```
Error: Invalid index

  on tf_v2.tf line 55, in resource "aws_route53_record" "additional_dns":
  55:    name                    = aws_acm_certificate.certificate_1.domain_validation_options[2].resource_record_name
    |----------------
    | aws_acm_certificate.certificate_1.domain_validation_options is list of object with 2 elements

The given key does not identify an element in this collection value.
```

### Steps to Reproduce

1. run `terraform apply` command for tf_v1.tf
2. run `terraform apply` command for tf_v2.tf

* #0000

**Comment by bflad** [comment] 2020-09-11 01:26
Hi @fomichevmi 👋  Thank you for submitting this and sorry you ran into trouble here. It looks like there could be two separate things happening here.

Due to changes in Terraform AWS Provider version 3, the [`domain_validation_options` attribute of the `aws_acm_certificate` resource is no longer an indexable list, but an un-indexable set](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade#domain_validation_options-changed-from-list-to-set) due to a large number of reports about AWS having inconsistent ordering of the API response (https://github.com/terraform-providers/terraform-provider-aws/issues/8531). This means that references such as `[0]` should no longer directly work. It is unclear why this configuration error is not showing up first, but I guess theoretically that could happen if the configuration and the provider were updated at the same time.

That said, a change to `subject_alternative_names` should be triggering the `aws_acm_certificate` resource to recreate and the `domain_validation_options` value to be recomputed before references see its value. It is possible that the `CustomizeDiff` behavior introduced into the `aws_acm_certificate` resource is not receiving the updated SANs appropriately in this situation, but it will take some additional troubleshooting information (e.g. trace logs from Terraform) to determine if that is a real problem or just a symptom from the first issue above.

It may be worth ensuring the first configuration works (errors in this case) appropriately on one of the latest Terraform CLI versions (0.12.29 or 0.13.2) and Terraform AWS Provider version (3.5.0 or 3.6.0 just off the presses). If not, I think we will want to explore that issue first.

**Comment by bflad** [comment] 2021-01-22 17:32
It's been a long time since we heard from you here so we're going to close this out. If you're still having this problem, please feel free to open a new issue and complete all of the information requested in the [Bug Report template](https://github.com/hashicorp/terraform-provider-aws/issues/new?template=Bug_Report.md) so that we can attempt to understand and reproduce the problem.

**Closed by bflad** 2021-01-22 17:32 UTC
Labels: service/acm, service/route53, waiting-response
