### ISSUE TITLE
Resource: aws_cloudformation_stack_set_instance does not support OU deployment target.

### ISSUE THREAD

**Issue by hopkinsnji** [hashicorp/terraform-provider-aws#16988] opened 2021-01-06 02:32 UTC
Resource: aws_cloudformation_stack_set_instance only supports account  id, but the api supports deployment targets:
`[Service-managed permissions] The AWS Organizations accounts for which to create stack instances in the specified Regions.

You can specify Accounts or DeploymentTargets , but not both.`

It would be nice to have terraform support Ous

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by bflad** [comment] 2021-01-06 16:17
Hi @hopkinsnji :wave: This appears to be a duplicate of https://github.com/hashicorp/terraform-provider-aws/issues/12425, so to consolidate discussions and efforts, I'm going to close this issue in preference of the linked one. Please :+1: react and subscribe to that issue for further updates. Thanks.

**Closed by bflad** 2021-01-06 16:17 UTC
Labels: enhancement, needs-triage
