### ISSUE TITLE
Since v3.68.0 `aws_launch_template` no longer reports `latest_version` until after changes are applied

### ISSUE THREAD

**Issue by mgreen-sm** [hashicorp/terraform-provider-aws#22015] opened 2021-12-02 16:54 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/aws v3.68.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

```
### Affected Resource(s)

* aws_launch_template

### Expected Behavior

Expect `aws_launch_template.<resource_name>.latest_version` to update during apply stages.

### Actual Behavior

`aws_launch_template.<resource_name>.latest_version` does not update during apply stages.

### Steps to Reproduce

```hcl
resource "random_pet" "asg_name" {
  separator = "-"
  length    = 2

  keepers = {
    # Generate a new pet name each time we switch the launch template
    lt_name = "${aws_launch_template.this.name}+${aws_launch_template.this.latest_version}"
  }
}
```
Using AWS Provider v3.67.0, this resulted in:

```
+/- resource "random_pet" "asg_name" {
      ~ id        = "key-dove" -> (known after apply)
      ~ keepers   = {
          - "lt_name" = "example-launch-template-20200311171713363100000001+267"
        } -> (known after apply) # forces replacement
        # (2 unchanged attributes hidden)
    }
```

With AWS Provider v3.68.0, the resource is not updated until a 2nd run with `terrafrom apply`.

**Comment by ewbankkit** [comment] 2021-12-03 12:59
My guess here is that it's the interaction of the `CustomizeDiff` function for `latest_version`

https://github.com/hashicorp/terraform-provider-aws/blob/3540d70dcd51f60f0bd544c311d58cce4b65fd78/internal/service/ec2/launch_template.go#L650-L660

and https://github.com/hashicorp/terraform-plugin-sdk/pull/716 which was merged with [`terraform-plugin-sdk` v2.9.0](https://github.com/hashicorp/terraform-provider-aws/pull/21858).

**Comment by fokion** [comment] 2021-12-03 15:59
We have the same issue 
```
Error: Provider produced inconsistent final plan   
When expanding the plan for module.asg.aws_autoscaling_group.asg to include 
new values learned so far during apply, provider 
"registry.terraform.io/hashicorp/aws" produced an invalid new value for 
.launch_template[0].version: was cty.StringVal("13"), but now 
cty.StringVal("14"). 
This is a bug in the provider, which should be reported in the provider's own 
issue tracker.  
```

**Comment by ewbankkit** [comment] 2021-12-03 16:44
Maybe change the logic to use `diff.HasChange()` on the keys we are looking for?

**Comment by jensenak** [comment] 2021-12-03 17:35
Slightly easier way to replicate this is just to output `latest_version`. When you update the launch template resource, the output value does not change. A subsequent apply (with no code changes) then causes the output to be updated.

**Comment by ewbankkit** [comment] 2021-12-03 19:09
We currently have a failing acceptance test that is showing this behavior:

```
=== RUN   TestAccEC2LaunchTemplate_update
=== PAUSE TestAccEC2LaunchTemplate_update
=== CONT  TestAccEC2LaunchTemplate_update
    launch_template_test.go:468: Step 3/3 error: Check failed: Check 5/5 error: aws_autoscaling_group.test: Attribute 'launch_template.0.version' expected "2", got "1"
--- FAIL: TestAccEC2LaunchTemplate_update (76.20s)
```

**Comment by ericrichtert** [comment] 2021-12-08 14:32
When will this be fixed?

**Comment by dacut** [comment] 2021-12-08 23:28
Perhaps a silly question: Would it make sense for `aws_launch_template` to return a `version` attribute (equal to the version that Terraform deployed)? Normally, `latest_version` _should_ equal `version`, but race conditions with something else touching the launch template.

Won't happen if Terraform is the only thing touching the launch template (best practice), but... yeah.

**Comment by mgreen-sm** [comment] 2021-12-09 10:22
> When will this be fixed?

@ewbankkit is working on it. See https://github.com/hashicorp/terraform-plugin-sdk/pull/829. 

In meantime you could pin the AWS Provider version to v3.67.0. In our case, we just needed the `latest_version` as an indicator that the launch template has changed (not necessarily the latest), so we've replaced `latest_version` with the `sha256()` function on the launch template's `user_data` (which for us will always change when the version changes).

**Comment by chriscatuk** [comment] 2021-12-10 11:30
I had excluded provider version `3.68.0` but with `3.69.0` I got the error back. I will keep my production using `< 3.68.0` until it is fixed

```
required_providers {
-    aws = "> 3.26, != 3.68.0"
+    aws = "> 3.26, < 3.68.0"
}
```

**Comment by kostya-alarstudios** [comment] 2021-12-11 10:41
In version 3.69.0 aws provider works for me:

```
module.eks.module.node_groups[0].aws_launch_template.bottlerocket: Modifying... [id=lt-xxxxxxxxxxxxxxx]
module.eks.module.node_groups[0].aws_launch_template.bottlerocket: Modifications complete after 1s [id=lt-xxxxxxxxxxxxx]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

```

```
# terraform -v
Terraform v1.0.3
on linux_amd64

```

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.69"
    }
  }
}
```

**Comment by patrickshan** [comment] 2021-12-13 10:20
Just did a test with 3.69.0 provider and found the `latest_version` issue still exists

**Comment by benzaam** [comment] 2021-12-16 14:57
we are facing the same issue since we upgraded to 3.68.0

**Closed** 2021-12-17 21:51 UTC
Labels: bug, regression, service/ec2

**Comment by fokion** [comment] 2021-12-21 13:54
> we are facing the same issue since we upgraded to 3.68.0

we found out that we had to destroy and rebuild with pinned version of aws provider , we are using 3.67.0

**Comment by vikas027** [comment] 2022-01-07 04:37
I can confirm that v3.71.0 fixes the issue.
