### ISSUE TITLE
Unable to import route53 records with _ in the record name

### ISSUE THREAD

**Issue by harinireddy3** [hashicorp/terraform-provider-aws#21221] opened 2021-10-08 17:15 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

$ terraform -version
Terraform v0.12.31
+ provider.aws v3.62.0

### Affected Resource(s)

* aws_route53_record

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_route53_record" "record_with_underscore" {

}
```

### Expected Behavior

Terraform should be able to import the resource successfullly
### Actual Behavior

Terraform import commands throws below error
```
 InvalidInput: 1 validation error detected: Value 'domainkey.example.com.' at 'startRecordType' failed to satisfy constraint: Member must satisfy enum value set: [AAAA, A, CAA, NS, SOA, SPF, MX, PTR, CNAME, DS, TXT, SRV, NAPTR]
        status code: 400, request id: xxxx-xxx-...
```

### Steps to Reproduce

1. `terraform import aws_route53_record.record_with_underscore YUIOPT678_smtp._domainkey.example.com._TXT`

### References

* #0000

**Comment by justinretzolk** [comment] 2021-10-08 18:50
Hey @harinireddy3 👋 Thanks for taking the time to submit this issue. It looks like this is a duplicate of #16213. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #16213.

**Closed by justinretzolk** 2021-10-08 18:50 UTC
Labels: service/route53, needs-triage
