### ISSUE TITLE
[Bug]: aws_eks_node_group AsgInstanceLaunchFailures:

### ISSUE THREAD

**Issue by MNLOPS** [hashicorp/terraform-provider-aws#39904] opened 2024-10-28 01:35 UTC
### Terraform Core Version

1.9.8

### AWS Provider Version

5.73.0

### Affected Resource(s)

aws_eks_node_group

### Expected Behavior

The aws_eks_node_group resource should have been created successfully, establishing a node group associated with the specified EKS cluster without any errors.

### Actual Behavior

When running terraform apply, an error occurs and the aws_eks_node_group is not created. The process fails with an error message related to the KMS key being in an incorrect state.

### Relevant Error/Panic Output Snippet

```shell
Error: waiting for EKS Node Group (terraform-Cluster:terraform-nodeGroup) create: unexpected state 'CREATE_FAILED', wanted target 'ACTIVE'. last error: eks-terraform-nodeGroup-1ac96815-c130-66de-ac5f-e705e77b45df: AsgInstanceLaunchFailures: Instance became unhealthy while waiting for instance to be in InService state. Termination Reason: Client.InvalidKMSKey.InvalidState: The KMS key provided is in an incorrect state
i-0064c5a4ad0536e59, i-00e61413f732e2188, i-0234fcdd401c5c170, i-0256af9059fc3c8ae, i-03753806851e16279, i-03d1ec5a8657587d1, i-057bb5c68ad9abf22, i-06bae0d2379a22e69, i-07c7436f851aa23fb, i-086b138ef5091496c, i-0a300871bddc2ecbe, i-0bb16355beec59be6, i-0c2dd25b88b0a02ba, i-0ce88d815d05b99f7, i-0faa17fae2ffc5e75: NodeCreationFailure: Instances failed to join the kubernetes cluster

  with module.eks.aws_eks_node_group.eks-ng,
  on modules/eks/eks_cluster.tf line 21, in resource "aws_eks_node_group" "eks-ng":
  21: resource "aws_eks_node_group" "eks-ng" {
```

### Terraform Configuration Files

# EKS Cluster Definition
```hcl
resource "aws_eks_cluster" "eks_cluster" {
  name                      = "${var.name_prefix}-Cluster"
  role_arn                  = aws_iam_role.cluster.arn
  enabled_cluster_log_types = var.cluster_log_types
  version                   = var.cluster_version
  tags                      = merge(var.project_tags, { Name = "${var.name_prefix}-cluster" })

  vpc_config {
    endpoint_public_access  = false
    endpoint_private_access = true
    subnet_ids              = var.private_subnets
    security_group_ids      = [aws_security_group.EKS_SG.id]
  }

  depends_on = [
    aws_iam_role.cluster,
  ]
}
```
```hcl
# Node Group
resource "aws_eks_node_group" "eks-ng" {
  cluster_name    = aws_eks_cluster.eks_cluster.name
  node_group_name = "${var.name_prefix}-nodeGroup"
  node_role_arn   = aws_iam_role.node.arn
  subnet_ids      = var.private_subnets
  instance_types  = [var.instance_type]

  tags = merge(var.project_tags, { Name = "${var.name_prefix}-nodeGroup" })

  scaling_config {
    desired_size = var.eks_asg["desired_size"]
    max_size     = var.eks_asg["max_size"]
    min_size     = var.eks_asg["min_size"]
  }

  depends_on = [
    aws_iam_role.cluster,
  ]
}
```
```hcl
# IAM Policy Documents
data "aws_iam_policy_document" "ec2" {
  statement {
    sid    = "EC2AssumeRole"
    effect = "Allow"
    principals {
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }
    actions = ["sts:AssumeRole"]
  }
}

data "aws_iam_policy_document" "eks" {
  statement {
    sid    = "EKSAssumeRole"
    effect = "Allow"
    principals {
      type        = "Service"
      identifiers = ["eks.amazonaws.com"]
    }
    actions = ["sts:AssumeRole"]
  }
}
```
```hcl
# IAM Roles
resource "aws_iam_role" "cluster" {
  name               = "${var.name_prefix}-EksCluster-Role"
  assume_role_policy = data.aws_iam_policy_document.eks.json

  managed_policy_arns = [
    "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy",
    "arn:aws:iam::aws:policy/AmazonEKSVPCResourceController"
  ]

  tags = { Name = "${var.name_prefix}-EksCluster-Role" }
}

resource "aws_iam_role" "node" {
  name               = "${var.name_prefix}-NodeGroup-Role"
  assume_role_policy = data.aws_iam_policy_document.ec2.json

  managed_policy_arns = [
    "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy",
    "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy",
    "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly",
    "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore",
  ]

  tags = { Name = "${var.name_prefix}-NodeGroup-Role" }
}
```
```hcl
# Security Group
resource "aws_security_group" "EKS_SG" {
  name        = "${var.name_prefix}-sg-eks"
  description = "${var.name_prefix}-sg-eks"
  vpc_id      = var.vpc_id

  dynamic "ingress" {
    for_each = var.sg_ports_list
    content {
      from_port   = ingress.value["port"]
      to_port     = ingress.value["port"]
      protocol    = ingress.value["protocol"]
      cidr_blocks = ingress.value["cidr"]
    }
  }

  egress {
    description      = "Allow Internet Out"
    from_port        = 0
    to_port          = 0
    protocol         = "-1"
    cidr_blocks      = ["0.0.0.0/0"]
    ipv6_cidr_blocks = ["::/0"]
  }
}
```
# Variables
```hcl
## Required Configuration Variables
variable "name_prefix" {
  description = "[REQUIRED] Prefix for resource names"
  type        = string
}

variable "vpc_id" {
  description = "[REQUIRED] VPC ID for the deployment"
  type        = string
}

variable "private_subnets" {
  description = "[REQUIRED] List of private subnet IDs"
  type        = list(string)
  default     = []
}

## EKS Cluster Configuration Variables
variable "cluster_version" {
  description = "[REQUIRED] Kubernetes version supported by EKS."
  type        = string
}

variable "instance_type" {
  description = "[REQUIRED] EC2 instance type for the nodes"
  type        = string
}

variable "logs_retention" {
  description = "[REQUIRED] Number of days to retain logs in CloudWatch."
  type        = string
}

variable "cluster_log_types" {
  description = "[REQUIRED] List of log types to enable for the EKS cluster"
  type        = list(string)
  default     = []
}

## Security Configuration Variables
variable "sg_ports_list" {
  description = "[REQUIRED] List of security group rules for ports"
  type = list(object({
    port     = number
    protocol = string
    cidr     = list(string)
  }))
}

## Auto-Scaling Configuration Variables
variable "eks_asg" {
  description = "[REQUIRED] Auto-scaling configuration for EKS node group"
  type        = map(string)
  default     = {}
}

## Project Tags
variable "project_tags" {
  description = "[REQUIRED] Tags to apply to the project resources"
  type        = map(string)
  default     = {}
}
```

### Steps to Reproduce

Define the aws_eks_node_group resource as shown in the configuration above.
Ensure all variables (var.*) and referenced resources are properly defined and contain valid values.
Run terraform init to initialize the project.
Run terraform plan to verify the deployment plan.
Run terraform apply to apply the changes.
Observe the error that occurs during the creation of the node group.

### Important Factoids

The error indicates that the KMS key provided is in an incorrect state (Client.InvalidKMSKey.InvalidState).

### Would you like to implement a fix?

None

**Comment by bryantbiggs** [comment] 2024-10-30 19:39
> Termination Reason: Client.InvalidKMSKey.InvalidState: The KMS key provided is in an incorrect state

Looks like you might have enabled https://docs.aws.amazon.com/ebs/latest/userguide/encryption-by-default.html which is not configured correctly for EKS

However, this issue isn't related to the provider but looks to be related to your account/environment

**Comment by justinretzolk** [comment] 2024-10-31 17:19
Thank you for taking the time to raise this! As mentioned above, it looks like this is related to your environment rather than a bug with the provider itself. With that in mind, I'm going to close this issue. If you run into unexpected behavior in the future, please do let us know!

**Closed by justinretzolk** 2024-10-31 17:19 UTC
Labels: bug, service/iam, service/eks, needs-triage, service/vpc
