### ISSUE TITLE
Regression with aws_eip tags not being created

### ISSUE THREAD

**Issue by mfilipiak-ccg** [hashicorp/terraform-provider-aws#18847] opened 2021-04-14 01:19 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```sh
Terraform v0.14.3                                      
+ provider registry.terraform.io/hashicorp/aws v3.36.0 
```

### Affected Resource(s)

* aws_3.26.0

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "3.36.0"
    }
  }
}

resource "aws_eip" "elastic_ip" {
  tags = {
    Name = "test1"
  }
}
```

### Expected Behavior

Tags defined in the resource section should be reflected in the tags on AWS. In this case, the name should also show up as the name in the EIP listing.

### Actual Behavior

No tags are applied to the resource when created.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Reverting the provider version to `3.35.0` works fine.

### References

Suspecting this issue is in play, but have not investigated further.

* https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#3360-april-09-2021
* https://github.com/hashicorp/terraform-provider-aws/pull/17612

**Comment by bflad** [comment] 2021-04-14 14:50
Related: #18756 

@mfilipiak-ccg which AWS region is this configuration running in?

**Comment by mfilipiak-ccg** [comment] 2021-04-14 14:58
Without looking too closely, it appears the `Ec2CreateTags` call was removed and feels important. There may be alternative ways to accomplish this, but maybe just a mistake.

https://github.com/hashicorp/terraform-provider-aws/pull/17612/files#diff-5cc53a93a886b4b2474bd02b135f8aabd7f4aeb82d77e8ac0378386eaa01ae84L186

**Comment by YakDriver** [comment] 2021-04-15 21:27
> Without looking too closely, it appears the `Ec2CreateTags` call was removed and feels important. There may be alternative ways to accomplish this, but maybe just a mistake.
> 
> https://github.com/hashicorp/terraform-provider-aws/pull/17612/files#diff-5cc53a93a886b4b2474bd02b135f8aabd7f4aeb82d77e8ac0378386eaa01ae84L186

@mfilipiak-ccg Absolutely right. It looks like the idea was to use `ec2TagSpecificationsFromMap()` for VPC EIPs but then left all other EIPs without tags.

**Comment by rick-masters** [comment] 2021-04-15 21:53
You should be able to move forward by adding `vpc = true` to your eip configuration. This is the right setting and should fix the problem. However, it should not be required so this is a regression and a fix is forthcoming. Please see the discussion in https://github.com/hashicorp/terraform-provider-aws/issues/18756. I recommend this issue be marked as a duplicate of that one.

**Comment by YakDriver** [comment] 2021-04-15 21:58
Duplicate of #18756.

**Closed by YakDriver** 2021-04-15 21:58 UTC
Labels: service/ec2
