### ISSUE TITLE
[Bug]: terraform apply is always changing the aws_route_table.

### ISSUE THREAD

**Issue by Mahesh-008** [hashicorp/terraform-provider-aws#27007] opened 2022-09-28 06:58 UTC
### Terraform Core Version

Terraform v1.3.0

### AWS Provider Version

aws v4.32.0

### Affected Resource(s)

```hcl
resource "aws_network_interface" "nat_network_interface" {
  subnet_id         = local.pri_sub_ids[0]
  source_dest_check = false
  security_groups   = [aws_security_group.nat-sg.id]

  tags = {
    Name = "${local.environment}-nat_instance_network_interface"
  }
}

resource "aws_route_table" "dev-vpc-private-rt" {
  vpc_id = aws_vpc.dev-vpc.id

  route {
    cidr_block = "0.0.0.0/0"
    #nat_gateway_id = aws_nat_gateway.dev-vpc-nat-gw.id
    network_interface_id = aws_network_interface.nat_network_interface.id
  }

  tags = {
    Name = "${local.environment}-Private-Route-Table"
  }
}
```

### Expected Behavior

it should say no changes.

### Actual Behavior

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_route_table.dev-vpc-private-rt will be updated in-place
  ~ resource "aws_route_table" "dev-vpc-private-rt" {
        id               = "rtb-0483528a4c0b5cf2f"
      ~ route            = [
          + {
              + carrier_gateway_id         = ""
              + cidr_block                 = "0.0.0.0/0"
              + core_network_arn           = ""
              + destination_prefix_list_id = ""
              + egress_only_gateway_id     = ""
              + gateway_id                 = ""
              + instance_id                = ""
              + ipv6_cidr_block            = ""
              + local_gateway_id           = ""
              + nat_gateway_id             = ""
              + network_interface_id       = "eni-019e42a1babbffe7e"
              + transit_gateway_id         = ""
              + vpc_endpoint_id            = ""
              + vpc_peering_connection_id  = ""
            },
          - {
              - carrier_gateway_id         = ""
              - cidr_block                 = "0.0.0.0/0"
              - core_network_arn           = ""
              - destination_prefix_list_id = ""
              - egress_only_gateway_id     = ""
              - gateway_id                 = ""
              - instance_id                = "i-066a7f52283db0dee"
              - ipv6_cidr_block            = ""
              - local_gateway_id           = ""
              - nat_gateway_id             = ""
              - network_interface_id       = "eni-019e42a1babbffe7e"
              - transit_gateway_id         = ""
              - vpc_endpoint_id            = ""
              - vpc_peering_connection_id  = ""
            },
        ]
        tags             = {
            "Name" = "DEV-VPC-Private-Route-Table"
        }
        # (5 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
aws_route_table.dev-vpc-private-rt: Modifying... [id=rtb-0483528a4c0b5cf2f]
aws_route_table.dev-vpc-private-rt: Modifications complete after 1s [id=rtb-0483528a4c0b5cf2f]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

### Relevant Error/Panic Output Snippet

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_route_table.dev-vpc-private-rt will be updated in-place
  ~ resource "aws_route_table" "dev-vpc-private-rt" {
        id               = "rtb-0483528a4c0b5cf2f"
      ~ route            = [
          + {
              + carrier_gateway_id         = ""
              + cidr_block                 = "0.0.0.0/0"
              + core_network_arn           = ""
              + destination_prefix_list_id = ""
              + egress_only_gateway_id     = ""
              + gateway_id                 = ""
              + instance_id                = ""
              + ipv6_cidr_block            = ""
              + local_gateway_id           = ""
              + nat_gateway_id             = ""
              + network_interface_id       = "eni-019e42a1babbffe7e"
              + transit_gateway_id         = ""
              + vpc_endpoint_id            = ""
              + vpc_peering_connection_id  = ""
            },
          - {
              - carrier_gateway_id         = ""
              - cidr_block                 = "0.0.0.0/0"
              - core_network_arn           = ""
              - destination_prefix_list_id = ""
              - egress_only_gateway_id     = ""
              - gateway_id                 = ""
              - instance_id                = "i-066a7f52283db0dee"
              - ipv6_cidr_block            = ""
              - local_gateway_id           = ""
              - nat_gateway_id             = ""
              - network_interface_id       = "eni-019e42a1babbffe7e"
              - transit_gateway_id         = ""
              - vpc_endpoint_id            = ""
              - vpc_peering_connection_id  = ""
            },
        ]
        tags             = {
            "Name" = "DEV-VPC-Private-Route-Table"
        }
        # (5 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
aws_route_table.dev-vpc-private-rt: Modifying... [id=rtb-0483528a4c0b5cf2f]
aws_route_table.dev-vpc-private-rt: Modifications complete after 1s [id=rtb-0483528a4c0b5cf2f]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

### Terraform Configuration Files

```hcl
resource "aws_network_interface" "nat_network_interface" {
  subnet_id         = local.pri_sub_ids[0]
  source_dest_check = false
  security_groups   = [aws_security_group.nat-sg.id]

  tags = {
    Name = "${local.environment}-nat_instance_network_interface"
  }
}

resource "aws_route_table" "dev-vpc-private-rt" {
  vpc_id = aws_vpc.dev-vpc.id

  route {
    cidr_block = "0.0.0.0/0"
    #nat_gateway_id = aws_nat_gateway.dev-vpc-nat-gw.id
    network_interface_id = aws_network_interface.nat_network_interface.id
  }

  tags = {
    Name = "${local.environment}-Private-Route-Table"
  }
}
```

### Steps to Reproduce

1. terraform init.
2. terraform plan (without making the any changes)

**Comment by ewbankkit** [comment] 2022-09-28 11:25
Relates https://github.com/hashicorp/terraform-provider-aws/issues/1426.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/14197.

**Comment by ewbankkit** [comment] 2022-09-28 11:25
I'm going to close this issue as a duplicate of #1426 so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Closed by ewbankkit** 2022-09-28 11:25 UTC
Labels: bug, service/vpc
