### ISSUE TITLE
[Bug]: #32 aws_spot_instance_request tags won't apply to instance

### ISSUE THREAD

**Issue by asaf400** [hashicorp/terraform-provider-aws#38821] opened 2024-08-12 12:00 UTC
### Terraform Core Version

1.9.0

### AWS Provider Version

5.62.0

### Affected Resource(s)

aws_spot_instance_request

### Expected Behavior

Reopening of #32

Tags specified on the aws_spot_instance_request via the `terraform-aws-modules/ec2-instance/aws` module are not propagated to the created spot instances, and they have no tags, including Name tag.

### Actual Behavior

The original issue was automatically closed, but it's not resolved,
there was only workarounds in the discussions, but no terraform provider solutions

### Terraform Configuration Files

.

### Steps to Reproduce

.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-08-12 21:26
Hey @asaf400 👋 Thank you for taking the time to raise this! This is an upstream limitation. From the [AWS documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-requests.html#concepts-spot-instances-request-tags):

> When you tag a Spot Instance request, the instances and volumes that are launched by the Spot Instance request are not automatically tagged. You need to explicitly tag the instances and volumes launched by the Spot Instance request. You can assign a tag to a Spot Instance and volumes during launch, or afterward.

We also mention this in the [`tags` documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/spot_instance_request#tags) in the `aws_spot_instance_request` documentation:

> A map of tags to assign to the Spot Instance Request. These tags are not automatically applied to the launched Instance.

One of our engineers [left a comment](https://github.com/hashicorp/terraform-provider-aws/issues/32#issuecomment-675716812) on #32 with a workaround that utilizes the [`aws_ec2_tag` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_tag) as a way of getting around this limitation.

Since this is a limitation of the AWS API itself that we've documented, there's nothing more that the provider team can do at this time. If the upstream API changes in the future, we'd be happy to take another look. Until then, I'm going to close this issue. If you run into any other unexpected behavior, please do let us know!

**Closed by justinretzolk** 2024-08-12 21:26 UTC
Labels: bug, needs-triage
