### ISSUE TITLE
aws_instance metadata_options http_endpoint not optional if http_tokens specified

### ISSUE THREAD

**Issue by louisth** [hashicorp/terraform-provider-aws#25547] opened 2022-06-23 17:16 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.9, hashicorp/aws v3.75.2

### Affected Resource(s)

* aws_instance

### Terraform Configuration Files

```hcl
  metadata_options {
    http_tokens = "required"
  }
```

### Expected Behavior

Documentation https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#metadata-options says that http_endpoint is optional.

### Actual Behavior
```
Error: Error launching source instance: InvalidParameterValue: A value of '' is not valid for HttpEndpoint. Specify either 'enabled' or 'disabled' and try again.
	status code: 400, request id: xxxxxxx

  with aws_instance.some_name[0],
  on some_name.tf line 206, in resource "aws_instance" "some_name":
 206: resource "aws_instance" "some_name" {
```

Documentation should say that http_endpoint is required when http_tokens is specified (or provider should fill in documented default)

**Comment by justinretzolk** [comment] 2022-07-25 19:29
Hey @louisth 👋 Thanks for taking the time to submit this issue. It looks like this is a duplicate of #16781. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #16781.

**Closed by justinretzolk** 2022-07-25 19:29 UTC
Labels: service/ec2, needs-triage
