### ISSUE TITLE
Error expanding plan for AWS Lambda Provisioned Concurrency

### ISSUE THREAD

**Issue by OleksandrMykytenko** [hashicorp/terraform-provider-aws#14267] opened 2020-07-21 07:57 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.20
+ provider.aws v2.70.0

### Affected Resource(s)

* aws_lambda_provisioned_concurrency_config

### Terraform Configuration Files

```hcl
resource "aws_lambda_function" "function" {
  function_name = "${local.name_prefix}-${var.lambda_name_uniq_part}"
  handler       = var.lambda_handler
  role          = aws_iam_role.lambda_execution_role.arn
  runtime       = var.lambda_runtime

  memory_size = var.lambda_memory_size
  timeout     = var.lambda_execution_timeout
  filename    = var.lambda_filename

  source_code_hash = filebase64sha256(var.lambda_filename)

  environment {
    variables = var.lambda_env_vars
  }

  vpc_config {
    security_group_ids = var.lambda_sg_ids
    subnet_ids         = var.lambda_subnet_ids
  }

  reserved_concurrent_executions = 50

  depends_on = [aws_cloudwatch_log_group.lambda_logs, aws_iam_role_policy.lambda_log_policy]

  publish = true

  tags = local.common_tags
}

resource "aws_lambda_provisioned_concurrency_config" "lambda_config" {
  count = 1
  function_name                     = aws_lambda_function.function.function_name
  provisioned_concurrent_executions = 5
  qualifier                         = aws_lambda_function.function.version
}
```

### Expected Behavior

New version of Lambda function should be published and provisioned concurrency config should be created and pointed to the published Lambda function version.

### Actual Behavior

I see the following message:
```
When expanding the plan for
module.my_lambda.aws_lambda_provisioned_concurrency_config.lambda_config[0]
to include new values learned so far during apply, provider
"registry.terraform.io/-/aws" produced an invalid new value for .qualifier:
was cty.StringVal("$LATEST"), but now cty.StringVal("1").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I was able to apply this code during the next (second) run w/o any issues. Seems Lambda is published during the first run and config is not, on the second run config is able to refer published Lambda version and everything is fine.

Plan operation is ok during the both runs.

**Comment by samuelwcm** [comment] 2020-07-24 12:05
I am also experiencing this:

```
Error: Provider produced inconsistent final plan
--
 
When expanding the plan for aws_lambda_provisioned_concurrency_config.download
to include new values learned so far during apply, provider
"registry.terraform.io/-/aws" produced an invalid new value for .qualifier:
was cty.StringVal("13"), but now cty.StringVal("14").
 
This is a bug in the provider, which should be reported in the provider's own
issue tracker.


Error: Provider produced inconsistent final plan
 
When expanding the plan for aws_lambda_provisioned_concurrency_config.extract
to include new values learned so far during apply, provider
"registry.terraform.io/-/aws" produced an invalid new value for .qualifier:
was cty.StringVal("13"), but now cty.StringVal("14").
 
This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

Config as follows:

```terraform
resource "aws_lambda_function" "download" {
  filename = data.archive_file.lambda_source.output_path
  source_code_hash = data.archive_file.lambda_source.output_base64sha256
  function_name = "download"
  handler = "functions.download_event_handler"
  role = "..."
  runtime = "python3.8"
  layers = [aws_lambda_layer_version.dependencies.arn]
  timeout = 5 * 60
  memory_size = 1024
  publish = true
  vpc_config {
    security_group_ids = [
      "..."
    ]
    subnet_ids = [
      "...",
      "..."
    ]
  }
}

resource "aws_lambda_function" "extract" {
  filename = data.archive_file.lambda_source.output_path
  source_code_hash = data.archive_file.lambda_source.output_base64sha256
  function_name = "extract"
  handler = "functions.extract_event_handler"
  role = "..."
  runtime = "python3.8"
  layers = [aws_lambda_layer_version.dependencies.arn]
  timeout = 5 * 60
  memory_size = 1024
  publish = true
  vpc_config {
    security_group_ids = [
      "..."
    ]
    subnet_ids = [
      "...",
      "..."
    ]
  }
}

resource "aws_lambda_provisioned_concurrency_config" "download" {
  function_name = aws_lambda_function.download.function_name
  provisioned_concurrent_executions = 1
  qualifier = aws_lambda_function.download.version
}

resource "aws_lambda_provisioned_concurrency_config" "extract" {
  function_name = aws_lambda_function.extract.function_name
  provisioned_concurrent_executions = 1
  qualifier = aws_lambda_function.extract.version
}
```

**Comment by terlar** [comment] 2020-07-30 13:42
I have seen this as well, but for the `aws_lambda_alias` resource, which is using a lambda function resource in the same way as the `aws_lambda_provisioned_concurrency_config` is doing.
```
Error: Provider produced inconsistent final plan

When expanding the plan for aws_lambda_alias.rest_lambda to include new values
learned so far during apply, provider "registry.terraform.io/-/aws" produced
an invalid new value for .function_version: was cty.StringVal("6"), but now
cty.StringVal("7").
This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

Could it be a race-condition with the lambda creation and the resources depending on them?

**Comment by TomH-TRT** [comment] 2020-08-13 07:29
Any work around guys?

**Comment by terlar** [comment] 2020-08-13 08:55
Nope, it fails daily for me, my "workaround" is just keep trying and eventually it will work. Usually the second time, but sometimes the 3rd of 4th

**Comment by giom-l** [comment] 2020-10-13 10:43
Same here but with `aws_lambda_layer_version`
```
Error: Provider produced inconsistent final plan

When expanding the plan for aws_lambda_layer_version.flows_checker to include
new values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" produced an invalid new value for
.source_code_hash: was
cty.StringVal("R7yhLmrzuB1/KsL1oMNbt3G+BaGuD9RZaH2T3TJ5doI="), but now
cty.StringVal("0W2MJeRin7GFDAzyj9De38nHQkZZH2Cwf8djXFIL3mM=").

```

A second apply did work.

Using terraform `0.13.4` and aws provider `3.10.0`

**Comment by dmitrijslotko** [comment] 2020-11-25 23:27
> Same here but with `aws_lambda_layer_version`
> 
> ```
> Error: Provider produced inconsistent final plan
> 
> When expanding the plan for aws_lambda_layer_version.flows_checker to include
> new values learned so far during apply, provider
> "registry.terraform.io/hashicorp/aws" produced an invalid new value for
> .source_code_hash: was
> cty.StringVal("R7yhLmrzuB1/KsL1oMNbt3G+BaGuD9RZaH2T3TJ5doI="), but now
> cty.StringVal("0W2MJeRin7GFDAzyj9De38nHQkZZH2Cwf8djXFIL3mM=").
> ```
> 
> A second apply did work.
> 
> Using terraform `0.13.4` and aws provider `3.10.0`

I have the same when I change something in the layer. Usually the second works but still annoying.

**Comment by GeertWille** [comment] 2021-07-26 07:57
Having the same issue. Anything news on this?

**Comment by julian-berks** [comment] 2021-08-23 09:05
Also having this issue - workaround appears to not use source_code_hash which isn't ideal.
Been over a year since it was reported - any chance of a fix or at least a response?

**Comment by jcollum** [comment] 2021-09-14 23:34
Same here in tf 1.0.6, hashicorp/aws 3.57.0.  

Fails more often than it works.

**Comment by okgolove** [comment] 2021-10-08 14:20
Still happens, hashicorp/aws 3.62.0

**Comment by gilesvessey** [comment] 2022-04-22 16:27
Still happens, hashicorp/aws 3.72.2 / terraform 1.1.7 . Nine attempts with the same error.

**Comment by defyjoy** [comment] 2022-06-29 12:09
```
Terraform v1.2.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.20.1
```

Happens with this as well

**Comment by daftkid** [comment] 2022-10-25 18:36
@jar-b Hi Jared, I'm afraid I cannot confirm or deny that as I'm not working on this particular infrastructure anymore and cannot say if that's true, maybe someone else is able to test it.

**Comment by jar-b** [comment] 2022-10-26 20:26
No worries, thanks for the quick response @daftkid.

To allow time for feedback on the reproduction, we're going to leave this issue open for now. If no objections are received we will close this as completed (via #14578) in the near future.

**Comment by breathingdust** [comment] 2022-11-15 16:28
Closing give lack of response to reproductions. Completed via #14578

**Closed by breathingdust** 2022-11-15 16:28 UTC
Labels: bug, waiting-response, service/lambda
