### ISSUE TITLE
aws_s3_bucket resources with same name are not emitting "bucket already exists" errors

### ISSUE THREAD

**Issue by rnikoopour** [hashicorp/terraform-provider-aws#25622] opened 2022-06-29 22:05 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
 % terraform -v                                                                                                                                                              
Terraform v1.2.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.20.1
```

### Affected Resource(s)

* aws_s3_bucket resource

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_s3_bucket" "first" {
  name = "my_new_s3_bucket_12345"
}

// The bucket name is deliberately the same
resource "aws_s3_bucket" "second" {
  name = "my_new_s3_bucket_12345"
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

I start off by only having resource "first" in the file and run a terraform apply.  After this successfully runs, I add resource "second" to the file with the same exact bucket name.  Then I run a terraform apply.  This should fail with a bucket name already exists error.

### Actual Behavior

After adding resource "second" to the file and running a terraform apply, it runs to completion saying that it created resource "second" even though the bucket already existed and was deployed through resource "first".

### Steps to Reproduce

1. Create the following bucket:
```hcl
resource "aws_s3_bucket" "first" {
  name = "my_new_s3_bucket_12345"
}
```
2. Run `terraform apply`
3. Update the terraform file to add the second bucket with the same name:
```hcl
resource "aws_s3_bucket" "first" {
  name = "my_new_s3_bucket_12345"
}

resource "aws_s3_bucket" "second" {
  name = "my_new_s3_bucket_12345"
}
```
4. Run `terraform apply`

### Important Factoids

N/A

### References

N/A

**Comment by gdavison** [comment] 2022-07-27 17:34
This is a duplicate of #13587

**Closed by gdavison** 2022-07-27 17:34 UTC
Labels: bug, service/s3
