### ISSUE TITLE
[Enhancement]: Support 0 rule blocks for aws_s3_bucket_object_lock_configuration

### ISSUE THREAD

**Issue by akloss-cibo** [hashicorp/terraform-provider-aws#31790] opened 2023-06-06 13:27 UTC
### Description

The `aws_s3_bucket_object_lock_configuration` resource currently requires a `rule` block.  S3 itself does not require this, and it is a useful configuration to be able to configure object lock capabilities on a bucket without enabling object lock by default.

### Affected Resource(s) and/or Data Source(s)

* aws_s3_object_lock_configuration

### Potential Terraform Configuration

```terraform
resource "aws_s3_bucket_object_lock_configuration" "bucket" {
  bucket = aws_s3_bucket_versioning.bucket.id
  token = "TOKEN"
}
```

### References

Here is an extract from a plan showing that the rule isn't configured on the object lock configuration, and that terraform would like to create it:
```
  ~ resource "aws_s3_bucket_object_lock_configuration" "bucket" {
        id                  = "redacted"
        # (3 unchanged attributes hidden)

      + rule {
          + default_retention {
              + days = 45
              + mode = "COMPLIANCE"
            }
        }
    }
  ```
  
  If you try to remove the `rule` from the configuration, terraform errors:
  
  ```
  │ Error: Insufficient rule blocks
  ```

### Would you like to implement a fix?

None

**Comment by trevorrea** [comment] 2023-06-07 12:54
Duplicate of https://github.com/hashicorp/terraform-provider-aws/pull/26520/files 

You need to upgrade to at least 4.30.0 (which in itself is very old).

See https://github.com/hashicorp/terraform-provider-aws/blob/release/4.x/CHANGELOG.md#4300-september--9-2022

**Closed as completed** 2023-06-07 13:00 UTC
Labels: enhancement, service/s3
