### ISSUE TITLE
[Enhancement]: RDS native secret manager integration

### ISSUE THREAD

**Issue by pdeva** [hashicorp/terraform-provider-aws#28781] opened 2023-01-10 05:33 UTC
### Description

Please add support for recently released native Secret Manager integration for RDS in rds terraform resource 

### Affected Resource(s) and/or Data Source(s)

aws_rds_cluster

### References

https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-rds-integration-aws-secrets-manager/

### Would you like to implement a fix?

None

**Comment by tmccombs** [comment] 2023-01-27 20:33
This looks like a duplicate of #28538

**Comment by AdamTylerLynch** [comment] 2023-03-23 11:52
Duplicate of #28848

**Comment by AdamTylerLynch** [comment] 2023-03-23 11:53
Duplicate

**Closed by AdamTylerLynch** 2023-03-23 11:53 UTC
Labels: enhancement, service/rds
