### ISSUE TITLE
Allow "auto-import" for AWS resources that have a distinct / unique attribute

### ISSUE THREAD

**Issue by brettcave** [hashicorp/terraform-provider-aws#20635] opened 2021-08-20 12:19 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There are a few AWS resources that have a unique name (or possibly some other attribute) constraint - as examples, cloudwatch log group or route 53 records come to mind. With non-distinct resources, if a resource is created manually in AWS / is not in state, and TF is run, a new resource will get created. For distinctly attributed resources, it would be great to be able to acknowledge this and have the resource imported into the state automatically. 

e.g. for cloudwatch_log_group, instead of needing to run `terraform import aws_cloudwatch_log_group.this <ref>` manually, it be really useful to be able to set `import_resource_if_present = true` on the resource. 

Not quite how this feature would work, or if it would be possible to implement - during state refresh, resources listed in the state are queried, but items not in the state are not. To get this available, it might require another step of collecting all "auto_import_resource_if_exists" resources and querying AWS API to determine if it needs a create or import...  or alternatively, when provisioning the resource if it is marked for creation, when the create call is made, first do a lookup and if AWS API returns, then do the import.

### New or Affected Resource(s)

Any distinctly attributed resource, e.g.
* aws_cloudwatch_log_group
* aws_route53_record
* aws_route53_domain

### Potential Terraform Configuration

```hcl
resource "aws_cloudwatch_log_group" "this" {
    name = "yada"
    auto_import_if_exists = true
}
```

**Comment by ewbankkit** [comment] 2021-08-20 12:34
Hi @brettcave 👋  Thank you for submitting this and this is an excellent use case of somewhere that Terraform and the Terraform AWS Provider could be much more helpful since in many cases they have enough information to return an error upfront during planning instead of unexpected behavior during apply.

I believe this falls under the provider-wide enhancement proposal of https://github.com/terraform-providers/terraform-provider-aws/issues/14394, so by adding this link here it will add a reference to that issue so we can include it as a use case when thinking about the implementation details. Since this is likely something we will want more broadly across many resources, I'm going to close this particular issue to consolidate discussions, efforts, and prioritization on the topic while the reference would serve as the cue to make this specific resource one of the initial implementations. I would suggest those 👍  upvoting and subscribing here to do so on #14394 so we can appropriately gauge interest. Please feel free to provide feedback there.

**Closed** 2021-08-20 12:35 UTC
Labels: enhancement, provider

**Comment by brettcave** [comment] 2021-08-20 13:42
ah - great - thanks @ewbankkit - heading over to 14394 to vote :)
