### ISSUE TITLE
AWS EC2 instance public IP address is not updated on instance type change

### ISSUE THREAD

**Issue by speller** [hashicorp/terraform-provider-aws#20651] opened 2021-08-22 06:21 UTC
I have the following piece of the configuration:

```
resource "aws_instance" "control" {
  ami = data.aws_ami.control.id
  instance_type = "t2.micro"
  subnet_id = module.vpc.public1_subnet_id
  associate_public_ip_address = true
  vpc_security_group_ids = [
    aws_security_group.control.id
  ]
}

resource "aws_route53_record" "control" {
  name = "control"
  type = "A"
  zone_id = data.aws_route53_zone.tld.id
  records = [aws_instance.control.public_ip]
  ttl = 300
}
```

The idea here is that the record must have the instance's public IP address. And it worked well. Then I changed the instance type to `t2.nano` and Terraform has created the following plan:

```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place
Terraform will perform the following actions:
  # aws_instance.control will be updated in-place
  ~ resource "aws_instance" "control" {
        id                                   = "i-0f0cca024bef87452"
      ~ instance_type                        = "t2.micro" -> "t2.nano"
        # (28 unchanged attributes hidden)
        # (5 unchanged blocks hidden)
    }
Plan: 0 to add, 1 to change, 0 to destroy.
```

You may see here that TF has changed the instance instead of replacing it. In the reality, the instance is replaced and gets a new public IP address. But this change is not reflected in the plan and after executing, the infrastructure becomes broken because the DNS record remains to have an old invalid IP address.

### Terraform Version
1.0.3 Docker

### Expected Behavior
EC2 instance is replaced in TF state.
Route 53 record is updated with the new instance's IP address.

### Actual Behavior
EC2 instance is not replaced in TF state.
Route 53 record is not updated with the new instance's IP address.

**Comment by joelatrr** [comment] 2021-12-02 22:27
Can confirm same behavior on t3 instance types.

**Comment by speller** [comment] 2022-07-21 13:40
Facing the same issue on every operation that requires instance shutdown. For example, updating the user metadata. The instance is updated but TF doesn't care about the changed IP address so any code that is relying on it will fail or produce broken infrastructure. Why this severe bug is not being fixed?

**Comment by jwoytek** [comment] 2022-08-19 20:23
Jumping on the bandwagon here, can confirm this is still the behavior under terraform 1.2.6 with aws provider 4.27.0.

**Comment by nobitran** [comment] 2022-10-08 10:09
I still got this issue. May I know how to fix it?

**Comment by jwoytek** [comment] 2022-10-11 14:46
> I still got this issue. May I know how to fix it?

In many cases, a workaround is to run the apply again, which will see the updated IP and update dependent resources/outputs/etc.

**Comment by ForbiddenEra** [comment] 2022-10-13 13:22
+1 using cf provider for dns

**Comment by ArkadyDR** [comment] 2022-10-13 13:22
This issue seems to be a duplicate of #6781.

**Comment by jwoytek** [comment] 2022-10-13 13:43
The workaround using an intermediate `data` source posted in #6781 here (https://github.com/hashicorp/terraform-provider-aws/issues/6781#issuecomment-607839534) seems to work for this particular issue. That same user later posted a staged workaround that would also work, and could be needed if one has other issues. The run-apply-twice is simple, but one must remember to do it.

**Comment by speller** [comment] 2022-12-26 07:11
@ArkadyDR 
Yes, this is a duplicate. But who cares?

@jwoytek 
Can't test it right now, but changes in instance metadata still don't trigger the instance IP address change in Terraform.

**Comment by enobayram** [comment] 2024-06-07 13:06
Still affected by this bug 3 years after it was reported.

**Closed** 2024-12-30 22:04 UTC
Labels: bug, service/ec2, service/route53
