### ISSUE TITLE
[Bug]: Error: Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by speller** [hashicorp/terraform-provider-aws#29012] opened 2023-01-20 15:49 UTC
Related:
- #23390
- #23423
- #23936
- #23992
- #24386
- #27175
- #27273
- #27479
- #28191
- #28672
- 👉 #29012
- #29304
- #30858

### Terraform Core Version

1.3.1

### AWS Provider Version

4.51.0

### Affected Resource(s)

I've got the following set of errors recently on two separate deployments:

```
module.db.aws_db_instance.app-db[0]: Creation complete after 10m47s [id=dev-local-alex20230120152722403400000001]
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" changed the planned action from Update to DeleteThenCreate.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .cpu_core_count: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .id: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .outpost_arn: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .password_data: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .private_dns: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .primary_network_interface_id: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .private_ip: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .disable_api_termination: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .ipv6_address_count: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .user_data: was null, but now cty.UnknownVal(cty.String).
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .host_id: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .host_resource_group_arn: was null, but now cty.UnknownVal(cty.String).
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .public_ip: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .secondary_private_ips: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .security_groups: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .instance_initiated_shutdown_behavior: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .monitoring: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .placement_group: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .public_dns: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tenancy: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .cpu_threads_per_core: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .arn: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .availability_zone: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .instance_state: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .disable_api_stop: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .ipv6_addresses: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .key_name: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .ebs_optimized: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .hibernation: was cty.False, but now null.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.app-admin.aws_instance.instance to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .placement_partition_number: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
````
What does it mean?

### Expected Behavior

Successful apply

### Actual Behavior

Error. Retrying on the same state succeeds.

### Terraform Configuration Files

I can't share right now

### Steps to Reproduce

Unknown

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2023-01-20 20:01
Hey @speller 👋 Thank you for taking the time to raise this! Without any additional information around the configuration or debug logging, it'll be hard to give a more clear answer as to what happened in this case. I notice that you mentioned you're not able to share the configuration at this time -- is that, along with any changes being made, something you'll be able to supply at a later time?

**Comment by a6patch** [comment] 2023-01-23 16:50
I can say this is effecting us as well.  We've had to go through and pin everything on version 4.50 (which does solve the issue).  I noticed two behaviors long with the broader issue.  When the plan file was saved, then used to apply it, the inconsistency issue arose.  When I just did a direct "terraform apply", the problem didn't occur.  We also were getting a situation where every single aws_api_gateway_integration wanted to update to add `connection_type="INTERNET"` whereas we were just depending on it being set already by default.  Some sort of internal representation seemed to have changed.

**Comment by justinretzolk** [comment] 2023-01-23 17:39
Hey @a6patch 👋 Thank you for that additional information. Are you able to provide an example Terraform configuration that can reproduce the issue?

**Comment by a6patch** [comment] 2023-01-23 17:46
Sorry, its hard to sanitize and post something thats still useful.  But the clear behavior is the `connection_type="INTERNET"` thing.  We have api gateways with hundreds and hundreds of aws_api_gateway_integration resources.  If I run the plan with version 4.50, I get a clean run without anything to apply.  If I run it with the only change being 4.51, then I get hundreds of "update aws_api_gateway_integration" for `+ connection_type="INTERNET"`

**Comment by njdister** [comment] 2023-01-23 18:10
> aws_api_gateway_integration

We are also running into this issue with our `aws_api_gateway_integration` resources.

**Comment by xblitz** [comment] 2023-01-23 18:28
seems like the issue in #28997 that should be fixed by #29016

**Comment by fraserc182** [comment] 2023-01-24 11:35
I am also having this issue with the provider version `4.51.0` reverting to `4.50.0` has sorted it in the meantime.

**Comment by justinretzolk** [comment] 2023-01-24 16:21
Hi all 👋 The "Provider produced inconsistent final plan" is a fairly generic message that can apply to any resource. In the case of the `aws_api_gateway_integration` resource where this error was reported on the `connection_type` argument, the fix for that regression has been fixed (as @xblitz called out above) and will be released with version 4.52.0 of the provider later this week.

When @speller initially posted this issue, they were experiencing the issue with `aws_db_instance` resources, so I'd like to maintain focus in on that resource in particular with this issue.

**Comment by SanB16** [comment] 2023-01-25 02:42
Hi @justinretzolk - same behaviour was seen with `aws_wafv2_web_acl` & `aws_kinesis_firehose_delivery_stream` resources

**Comment by speller** [comment] 2023-02-14 02:22
I just faced this issue again.
```none
Terraform v1.3.7
on linux_amd64
- Using hashicorp/aws v4.53.0 from the shared cache directory
```

I was applying changes to RDS instance and then its credentials had to be applied to an EC2 instance metadata. The result is the following:

```none
module.magento-db.aws_db_instance.app-db: Still creating... [15m10s elapsed]
module.magento-db.aws_db_instance.app-db: Still creating... [15m20s elapsed]
module.magento-db.aws_db_instance.app-db: Still creating... [15m30s elapsed]
module.magento-db.aws_db_instance.app-db: Still creating... [15m40s elapsed]
module.magento-db.aws_db_instance.app-db: Creation complete after 15m47s [id=dev-local-alex20230214015537803000000002]
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.service-magento2.module.graphql_provision.aws_instance.instance_no_cbd[0] to include new values learned so far
│ during apply, provider "registry.terraform.io/hashicorp/aws" changed the planned action from Update to DeleteThenCreate.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.service-magento2.module.graphql_provision.aws_instance.instance_no_cbd[0] to include new values learned so far
│ during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .ebs_optimized: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.service-magento2.module.graphql_provision.aws_instance.instance_no_cbd[0] to include new values learned so far
│ during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .private_ip: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.service-magento2.module.graphql_provision.aws_instance.instance_no_cbd[0] to include new values learned so far
│ during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .disable_api_termination: was known, but now
│ unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.service-magento2.module.graphql_provision.aws_instance.instance_no_cbd[0] to include new values learned so far
│ during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .public_ip: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.service-magento2.module.graphql_provision.aws_instance.instance_no_cbd[0] to include new values learned so far
│ during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .security_groups: was known, but now unknown.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

The error log lists (almost) all EC2 instance fields and claims an invalid value for them.

**Comment by speller** [comment] 2023-02-14 02:54
The instance in my case was deleted due to `create_before_destroy = false` and `user_data_replace_on_change = true`. Can it be related to #20651 when the AWS provider misses EC2 instance changes? It seems like these issues can be related. The plan above says that the instance should be updated in place, but it's replaced instead. On the next `apply` without configuration changes, the plan for the instance mentioned above was different and finished successfully:

```none
  # module.service-magento2.module.graphql_provision.aws_instance.instance_no_cbd[0] must be replaced
+/- resource "aws_instance" "instance_no_cbd" {
      ~ arn                                  = "arn:aws:ec2:ap-northeast-1:del:instance/i-0dade7f3fa0fe02d8" -> (known after apply)
      ~ availability_zone                    = "ap-northeast-1d" -> (known after apply)
      ~ cpu_core_count                       = 1 -> (known after apply)
      ~ cpu_threads_per_core                 = 2 -> (known after apply)
      ~ disable_api_stop                     = false -> (known after apply)
      ~ disable_api_termination              = false -> (known after apply)
      ~ ebs_optimized                        = false -> (known after apply)
...

Plan: 12 to add, 10 to change, 11 to destroy.

Changes to Outputs:
  ~ admin_instance_id = "i-0e1337c8c15061af9" -> (known after apply)
  ~ admin_public_ip   = "43.206.113.243" -> (known after apply)
module.es.aws_elasticsearch_domain.app: Modifying... [id=arn:aws:es:ap-northeast-1:del:domain/dev-local-alex]
module.es.aws_elasticsearch_domain.app: Modifications complete after 0s [id=arn:aws:es:ap-northeast-1:del:domain/dev-local-alex]
module.service-magento2.module.graphql_provision.aws_instance.instance_no_cbd[0]: Creating...
```

Also, you may see that the instance was not deleted in the second `apply`. But there was NO log record about this instance deletion in the first run as well, and I didn't edit the infra manually. So it looks like TF really misses underlying changes made by the provider.

**Comment by George-Alcd** [comment] 2023-02-14 07:03
For everyone who encounters something like this,
update your terraform aws provider to this:
It worked for me, give it a try. 

```
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.50.0"
    }
  }
```

**Comment by speller** [comment] 2023-02-21 12:25
Today faced the issue again:

```none
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.app-admin.aws_instance.instance to
│ include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" changed the planned action from
│ Update to DeleteThenCreate.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
...
```

A lot of messages on the `aws_instance` resource.

The following changes for the instance were in the plan:

```none
  # module.app-admin.aws_instance.instance will be updated in-place
  ~ resource "aws_instance" "instance" {
        id                                   = "i-01e9cfa7850822efb"
        tags                                 = {
            "cost:env" = "review"
        }
      ~ user_data=(sensitive)
        # (32 unchanged attributes hidden)
        # (7 unchanged blocks hidden)
    }
```

This change makes the instance to be stopped and started again. 

On the next run without changes in the configuration, it works well but the plan for the instance is different:

```none
  # module.app-admin.aws_instance.instance must be replaced
+/- resource "aws_instance" "instance" {
      ~ arn                                  = "arn:aws:ec2:ap-northeast-1:acc:instance/i-09db6d84907737075" -> (known after apply)
      ~ availability_zone                    = "ap-northeast-1a" -> (known after apply)
      ~ cpu_core_count                       = 1 -> (known after apply)
      ~ cpu_threads_per_core                 = 2 -> (known after apply)
      ~ disable_api_stop                     = false -> (known after apply)
      ~ disable_api_termination              = false -> (known after apply)
      ~ ebs_optimized                        = false -> (known after apply)
      - hibernation                          = false -> null
      + host_id                              = (known after apply)
      + host_resource_group_arn              = (known after apply)
      ~ id                                   = "i-09db6d84907737075" -> (known after apply)
      ~ instance_initiated_shutdown_behavior = "stop" -> (known after apply)
      ~ instance_state                       = "running" -> (known after apply)
      ~ ipv6_address_count                   = 0 -> (known after apply)
      ~ ipv6_addresses                       = [] -> (known after apply)
      + key=(sensitive)
      ~ monitoring                           = false -> (known after apply)
      + outpost_arn                          = (known after apply)
      + password=(sensitive)
      + placement_group                      = (known after apply)
      ~ placement_partition_number           = 0 -> (known after apply)
      ~ primary_network_interface_id         = "eni-02122ec8dfc3c8a17" -> (known after apply)
      ~ private_dns                          = "ip-10-0-2-38.ap-northeast-1.compute.internal" -> (known after apply)
      ~ private_ip                           = "10.0.2.38" -> (known after apply)
      ~ public_dns                           = "ec2-54-178-14-179.ap-northeast-1.compute.amazonaws.com" -> (known after apply)
      ~ public_ip                            = "54.178.14.179" -> (known after apply)
      ~ secondary_private_ips                = [] -> (known after apply)
      ~ security_groups                      = [] -> (known after apply)
        tags                                 = {
            "cost:env" = "review"
        }
      ~ tenancy                              = "default" -> (known after apply)
      + user_data=(sensitive)
      ~ user_data=(sensitive)
        # (10 unchanged attributes hidden)
      ~ capacity_reservation_specification {
          ~ capacity_reservation_preference = "open" -> (known after apply)
          + capacity_reservation_target {
              + capacity_reservation_id                 = (known after apply)
              + capacity_reservation_resource_group_arn = (known after apply)
            }
        }
      + ebs_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key=(sensitive)
          + snapshot_id           = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }
      ~ enclave_options {
          ~ enabled = false -> (known after apply)
        }
      + ephemeral_block_device {
          + device_name  = (known after apply)
          + no_device    = (known after apply)
          + virtual_name = (known after apply)
        }
      ~ maintenance_options {
          ~ auto_recovery = "default" -> (known after apply)
        }
      ~ metadata_options {
          ~ http_endpoint               = "enabled" -> (known after apply)
          ~ http_put_response_hop_limit = 1 -> (known after apply)
          ~ http_token=(sensitive)
          ~ instance_metadata_tags      = "disabled" -> (known after apply)
        }
      + network_interface {
          + delete_on_termination = (known after apply)
          + device_index          = (known after apply)
          + network_card_index    = (known after apply)
          + network_interface_id  = (known after apply)
        }
      ~ private_dns_name_options {
          ~ enable_resource_name_dns_a_record    = false -> (known after apply)
          ~ enable_resource_name_dns_aaaa_record = false -> (known after apply)
          ~ hostname_type                        = "ip-name" -> (known after apply)
        }
      ~ root_block_device {
          ~ delete_on_termination = true -> (known after apply)
          ~ device_name           = "/dev/xvda" -> (known after apply)
          ~ encrypted             = false -> (known after apply)
          ~ iops                  = 100 -> (known after apply)
          + kms_key=(sensitive)
          ~ tags                  = {} -> (known after apply)
          ~ throughput            = 0 -> (known after apply)
          ~ volume_id             = "vol-03b07ff84ffdd1b1f" -> (known after apply)
          ~ volume_size           = 8 -> (known after apply)
          ~ volume_type           = "gp2" -> (known after apply)
        }
        # (1 unchanged block hidden)
    }
```

On the second run, the log again contains the following lines:

```none
module.app-admin.aws_instance.instance: Creating...
module.app-admin.aws_instance.instance: Still creating... [10s elapsed]
module.app-admin.aws_instance.instance: Creation complete after 12s [id=i-0f8a52b7fab32b38c]
```

Again, there were NO log lines about the instance stopping or destruction on both runs. I again suppose that the issue is that the provider misses the actual resource due to #20651 or any other reason (i.e. already deleted).

**Comment by speller** [comment] 2023-03-04 16:32
I have a state and plan that produced this error. How can I share them with the team securely?

**Comment by speller** [comment] 2023-03-05 08:38
Faced it again. And again while the instance is configured to be replaced on userdata change (`user_data_replace_on_change = true`), the plan ignores this setting and plans to update it in-place:

```none
# module.service-magi.module.magi.aws_instance.instance[0] will be updated in-place
  ~ resource "aws_instance" "instance" {
      - host_id                              = "" -> null
        id                                   = "i-0089a2153bad206be"
      - key=(sensitive)
      - outpost_arn                          = "" -> null
      - password=(sensitive)
      - placement_group                      = "" -> null
        tags                                 = {
            "Name"            = "rev-main-mg-docker"
            "cost:app"        = "rhd-magi"
            "cost:delete_in"  = "1d"
            "cost:deployment" = "review"
            "cost:env"        = "review"
            "cost:infra_name" = "rev_main-mg"
        }
      # Warning: this attribute value will no longer be marked as sensitive
      # after applying this change.
      ~ user_data=(sensitive)
        # (32 unchanged attributes hidden)
        # (7 unchanged blocks hidden)
    }
```
@justinretzolk

**Comment by speller** [comment] 2023-03-07 14:06
The issue is happening regularly in our deployments. Any plans to work on it?

**Comment by justinretzolk** [comment] 2023-03-07 17:11
Hey @speller 👋 Thank you for the detailed description! As far as prioritizing working on this issue, we outline how we do so in our [prioritization guide](https://hashicorp.github.io/terraform-provider-aws/prioritization/). For sharing data with us securely, you can upload files directly on the issue here after encrypting them with our [GPG public key](https://keybase.io/hashicorp).

**Comment by speller** [comment] 2023-03-13 12:05
@justinretzolk 
[Inconsistent plan.zip.gpg.zip](https://github.com/hashicorp/terraform-provider-aws/files/10957106/Inconsistent.plan.zip.gpg.zip)
I've added the zip extension to the gpg file to make it uploaded to github.

**Comment by a0s** [comment] 2023-03-29 10:46
Start getting same issue after enable `user_data_replace_on_change`
Luckily this is solved by restarting tf apply

**Comment by gtebbutt** [comment] 2023-05-13 12:12
I've just run into this one - as far as I can see, the root cause is having `user_data_replace_on_change = true` while the `user_data` itself depends on values from resources that will not be known until after apply. I'd assume there's some kind of inequality check to trigger `user_data_replace_on_change`, but that's in a "maybe" state while the new `user_data` is unknown, which is causing the incorrect "will be updated in-place" output. 

Once the apply is in progress and the new `user_data` value is known by terraform, it flips from "maybe" to "not equal", and that in turn triggers `user_data_replace_on_change` as expected - except this is happing in real time during the apply process, rather than at the planning stage, which causes the errors.

**Comment by YakDriver** [comment] 2023-07-13 21:20
**NOTE:** I cannot reproduce this error after trying various configurations. _**Let us know**_ if this is still a problem! If we don't hear and can't reproduce, we plan to close this on or around **July 20, 2023**. The evidence suggests this is OBE (ie, fixed in the interim).

For more details see #23992 ([comment](https://github.com/hashicorp/terraform-provider-aws/issues/23992#issuecomment-1634920741)).

**Comment by justinretzolk** [comment] 2023-07-20 17:24
Hi all :wave: As was mentioned above, this issue appears to be fixed when using a minimum Terraform version of 1.4.2 and a minimum AWS Provider version of 4.67.0 (preferably Terraform 1.5.3 or later and AWS Provider 5.8.0 or later). If you experience additional unexpected behaviors with versions that meet these parameters, please open a new issue so that we can investigate further.

**Closed by justinretzolk** 2023-07-20 17:24 UTC
Labels: bug, waiting-response, service/rds

**Comment by speller** [comment] 2023-08-03 11:21
I still have this issue on TF 1.5.0 and AWS provider 4.67.0

**Comment by justinretzolk** [comment] 2023-08-03 16:44
Hey @speller 👋 Are you able to test with Terraform 1.5.3 and AWS Provider 5.8.0 to see if that corrects the issue for you? If you're still experiencing it with those versions, I'd recommend opening a new issue so that we can get it triaged appropriately.
