### ISSUE TITLE
Organization accounts attribute is null for data source: aws_organizations_organization while using child AWS account for AWS provider

### ISSUE THREAD

**Issue by marshall7m** [hashicorp/terraform-provider-aws#18590] opened 2021-04-06 15:57 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform: 0.14.8
AWS-Provider: 3.35.0

### Affected Resource(s)

* aws_organizations_organization

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
data "aws_organizations_organization" "this" {}

output "data_org" {
  value = data.aws_organizations_organization.this.accounts[*].id
}
```

### Expected Behavior

```
data_org = {
  "accounts" = [
      {
          arn = "arn:aws:organizations::111111111111:account/o-1234567/22222222222"
          email = "baz@bar.com"
          id = "22222222222"
          name = "child_account"
      }
  ]
  "arn" = "arn:aws:organizations::111111111111:organization/o-1234567"
  "aws_service_access_principals" = toset([])
  "enabled_policy_types" = toset([])
  "feature_set" = "ALL"
  "id" = "o-1234567"
  "master_account_arn" = "arn:aws:organizations::111111111111:account/o-1234567/111111111111"
  "master_account_email" = "foo@bar.com"
  "master_account_id" = "111111111111"
  "non_master_accounts" = tolist(null) /* of object */
  "roots" = tolist(null) /* of object */
}
```

### Actual Behavior
```
Outputs:

data_org = {
  "accounts" = tolist(null) /* of object */
  "arn" = "arn:aws:organizations::111111111111:organization/o-1234567"
  "aws_service_access_principals" = toset([])
  "enabled_policy_types" = toset([])
  "feature_set" = "ALL"
  "id" = "o-1234567"
  "master_account_arn" = "arn:aws:organizations::111111111111:account/o-1234567/111111111111"
  "master_account_email" = "foo@bar.com"
  "master_account_id" = "111111111111"
  "non_master_accounts" = tolist(null) /* of object */
  "roots" = tolist(null) /* of object */
}
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

- Verified that there's an AWS organization defined in the management AWS account via the AWS console
- 
UPDATE:
- Tried using the child AWS account for the AWS provider but resulted in the output defined under `Actual Behavior`
- Tried using the master AWS account that hosts the organization and it works as defined under `Expected Behavior`

**Comment by bill-rich** [comment] 2021-04-07 23:18
Hi @marshall7m! I tried to reproduce this issue, but was not able to when using the account that owns the organization. Can you provide an organization config that would reproduce the issue?

**Comment by marshall7m** [comment] 2021-04-13 15:25
> Hi @marshall7m! I tried to reproduce this issue, but was not able to when using the account that owns the organization. Can you provide an organization config that would reproduce the issue?

Hi @bill-rich! I'm not sure what attributes you're looking for from the organization config, but here's a redacted output from running `aws organizations describe-organization`

```
{
    "Organization": {
        "Id": "o-1234567",
        "Arn": "arn:aws:organizations::111111111111:organization/o-1234567",
        "FeatureSet": "ALL",
        "MasterAccountArn": "arn:aws:organizations::111111111111:account/o-1234567/111111111111",
        "MasterAccountId": "111111111111",
        "MasterAccountEmail": "mastermail@private.com",
        "AvailablePolicyTypes": [
            {
                "Type": "SERVICE_CONTROL_POLICY",
                "Status": "ENABLED"
            }
        ]
    }
}
```

**Comment by cmd-werner** [comment] 2021-06-29 06:51
Hello,

While using child/member AWS account from my organization I have the same issue:

- Terraform: 0.15.0
- Provider : hashicorp/aws v3.47.0

```
data "aws_organizations_organization" "org" {}

output "org" {
  value = data.aws_organizations_organization.org
}
```


```
$terraform apply
Acquiring state lock. This may take a few moments...

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:

Terraform will perform the following actions:

Plan: 0 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + org = {
      + accounts                      = null
      + arn                           = "arn:aws:organizations::12345678910:organization/o-myorgId"
      + aws_service_access_principals = []
      + enabled_policy_types          = []
      + feature_set                   = "ALL"
      + id                            = "o-myorgId"
      + master_account_arn            = "arn:aws:organizations::12345678910:account/o-myorgId/12345678910"
      + master_account_email          = "master_account_email@example.com"
      + master_account_id             = "12345678910"
      + non_master_accounts           = null
      + roots                         = null
    }
```

Note that this works if the execution is performed in the organization master account. If this is the expected behaviour, it would be great to update the documentation to highlight it.

**Comment by cob16** [comment] 2021-08-13 14:52
looks like it will always be null unless run in the root AWS account due to this if statement
https://github.com/hashicorp/terraform-provider-aws/blob/915f5f5dc3073de0f25ed216dca421bf76e114b9/aws/resource_aws_organizations_organization.go#L293

I Don't understand why this condition is here, perhaps in the past this was an API limitation

**Comment by cob16** [comment] 2021-09-02 09:09
[After writing up this pr](https://github.com/hashicorp/terraform-provider-aws/pull/20762) to remove the check from the code I realised that this could be a braking change for those who are using this data resource to get other attributes such as `master_account_id` etc. 

It would be good to get some feedback from the maintainers on how this should be fixed. i.e with an argument to override the check or by moving this API call to a new data source entirely :shrug:

**Comment by cob16** [comment] 2022-09-09 08:14
Given it has been a year now @rnikoopour and there are no dissenting opinions it does seem that way! :smile: I think It might just be worth seeing what we can get merged :shrug:

**Comment by ravenium** [comment] 2022-09-28 23:06
Just stumbled into this today when writing PermissionSet assignments. I can get around it by explicitly writing every last mapping but would be a nice shortcut to iterate upon.

**Comment by danowensdaylight** [comment] 2023-03-09 15:48
You can use the `aws_organizations_organizational_unit_descendant_accounts` resource to list all the descendant accounts of the root account.

**Comment by gilbert-hsu** [comment] 2023-04-01 04:02
> You can use the `aws_organizations_organizational_unit_descendant_accounts` [data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/organizations_organizational_unit_descendant_accounts#parent_id) to list all the descendant accounts of the root account.

`aws_organizations_organizational_unit_descendant_accounts` need OU id, which chlid account can't get from `aws_organizations_organization`

Does any data source's ouput  has OU id ?

**Comment by maunzCache** [comment] 2023-04-19 10:35
> > You can use the `aws_organizations_organizational_unit_descendant_accounts` [data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/organizations_organizational_unit_descendant_accounts#parent_id) to list all the descendant accounts of the root account.
> 
> `aws_organizations_organizational_unit_descendant_accounts` need OU id, which chlid account can't get from `aws_organizations_organization`
> 
> Does any data source's ouput has OU id ?

Not as of 4.63.0 . I have at least not found any in the organizations "package". I tried them all today with `terragrunt plan` and none seemed to work as i get the following error:

```
ERROR: listing Organizations Account for Parent (xxxxxxxxxxxx): InvalidInputException: You provided a value that does not match the required pattern.
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "..."
  },
  Message_: "You provided a value that does not match required pattern.",
  Reason: "INVALID_PATTERN:PARENT_ID"
}
```

**Comment by maunzCache** [comment] 2023-04-19 11:42
> Given it has been a year now @rnikoopour and there are no dissenting opinions it does seem that a new resource is the way to go. 😄 I think It might just be worth seeing what we can get merged 🤷

Actually i don't think that a new resource is necessary. From what @cob16 wrote this is a bug in the way that the resource does not check if the account is a delegated administrator. So to make this resource backwards compatible adding the additional check would be sufficient.

**Comment by obeliskm** [comment] 2023-05-10 01:33
for others caught out by not being able to enumerate a list of org accounts in a delegated admin account, I've ended up doing this to work around it:

in CI, before tf is run:
```
aws organizations list-accounts | jq 'walk(if type=="object" then with_entries(.key|=ascii_downcase) else . end)' > /tmp/aws-org-list-accounts
aws organizations list-roots    | jq 'walk(if type=="object" then with_entries(.key|=ascii_downcase) else . end)' > /tmp/aws-org-list-roots
```
then in tf
```
locals {
  account_list = jsondecode(file("/tmp/aws-org-list-accounts")).accounts
  parent_id     = jsondecode(file("/tmp/aws-org-list-roots")).roots[0].id
}
```
it's a bit of pain having to call out to the CLI, hopefully this will get resolved in some fashion soon.

**Closed** 2023-06-20 12:36 UTC
Labels: bug, service/organizations
