### ISSUE TITLE
The terraform-provider-aws_v3.75.1_x5.exe plugin plugin crashed!

### ISSUE THREAD

**Issue by prashant-eppalpalli** [hashicorp/terraform-provider-aws#24181] opened 2022-04-11 16:02 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.1
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v3.75.1
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.10.0
+ provider registry.terraform.io/hashicorp/local v2.2.2
+ provider registry.terraform.io/hashicorp/random v3.1.2
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

Error: Plugin did not respond
│
│   with aws_iam_instance_profile.bastion_host_iam_profile,
│   on main.tf line 235, in resource "aws_iam_instance_profile" "bastion_host_iam_profile":
│  235: resource "aws_iam_instance_profile" "bastion_host_iam_profile" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain   
│ more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.eks.aws_launch_template.default,
│   on ..\modules\k8s\main.tf line 45, in resource "aws_launch_template" "default":
│   45: resource "aws_launch_template" "default" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain   
│ more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.eks.module.eks.aws_iam_role_policy_attachment.workers_AmazonEKS_CNI_Policy[0],
│   on .terraform\modules\eks.eks\workers.tf line 514, in resource "aws_iam_role_policy_attachment" "workers_AmazonEKS_CNI_Policy":
│  514: resource "aws_iam_role_policy_attachment" "workers_AmazonEKS_CNI_Policy" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain   
│ more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.vpc.module.vpc.aws_internet_gateway.this[0],
│   on .terraform\modules\vpc.vpc\main.tf line 120, in resource "aws_internet_gateway" "this":
│  120: resource "aws_internet_gateway" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain   
│ more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.vpc.module.vpc.aws_route_table.private[0],
│   on .terraform\modules\vpc.vpc\main.tf line 226, in resource "aws_route_table" "private":
│  226: resource "aws_route_table" "private" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain   
│ more details.
╵
╷
│ Error: Request cancelled
│
│   with module.vpc.module.vpc.aws_subnet.public[1],
│   on .terraform\modules\vpc.vpc\main.tf line 352, in resource "aws_subnet" "public":
│  352: resource "aws_subnet" "public" {
│
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│
│   with module.vpc.module.vpc.aws_subnet.public[2],
│   on .terraform\modules\vpc.vpc\main.tf line 352, in resource "aws_subnet" "public":
│  352: resource "aws_subnet" "public" {
│
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Plugin did not respond
│
│   with module.vpc.module.vpc.aws_subnet.public[0],
│   on .terraform\modules\vpc.vpc\main.tf line 352, in resource "aws_subnet" "public":
│  352: resource "aws_subnet" "public" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain   
│ more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.vpc.module.vpc.aws_subnet.database[0],
│   on .terraform\modules\vpc.vpc\main.tf line 435, in resource "aws_subnet" "database":
│  435: resource "aws_subnet" "database" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain   
│ more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.vpc.module.vpc.aws_subnet.database[1],
│   on .terraform\modules\vpc.vpc\main.tf line 435, in resource "aws_subnet" "database":
│  435: resource "aws_subnet" "database" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain   
│ more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.vpc.module.vpc.aws_eip.nat[0],
│   on .terraform\modules\vpc.vpc\main.tf line 1001, in resource "aws_eip" "nat":
│ 1001: resource "aws_eip" "nat" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).UpgradeResourceState call. The plugin logs may contain   
│ more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.eks.module.eks.module.node_groups.aws_eks_node_group.workers["example"],
│   on .terraform\modules\eks.eks\modules\node_groups\main.tf line 1, in resource "aws_eks_node_group" "workers":
│    1: resource "aws_eks_node_group" "workers" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more      
│ details.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-aws_v3.75.1_x5.exe plugin:

panic: interface conversion: interface {} is nil, not *conns.AWSClient

goroutine 130 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/eks.resourceNodeGroupRead(0xaab30a8, 0xc0013f8ea0, 0xc001885480, 0x0, 0x0, 0xc001b3ab10, 0xc001c29878, 0x69e8ff)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/eks/node_group.go:374 +0x203fgithub.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000893dc0, 0xaab3038, 0xc001ab4f40, 0xc001885480, 0x0, 0x0, 0x0, 
0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:358 +0x18a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000893dc0, 0xaab3038, 0xc001ab4f40, 0xc0015b3ee0, 0x0, 0x0, 0xc000760c50, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:635 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00019c2b8, 0xaab3038, 0xc001ab4f40, 0xc001ac0980, 0x9b2a6f3, 0x12, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:576 +0x49b
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc000244980, 0xaab30e0, 0xc001ab4f40, 0xc0013715c0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:553 +0x322
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x988c6c0, 0xc000244980, 0xaab30e0, 0xc001970f00, 0xc001371560, 0x0, 0xaab30e0, 0xc001970f00, 0xc0010faa00, 0x64b)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x222
google.golang.org/grpc.(*Server).processUnaryRPC(0xc001076700, 0xaae04f8, 0xc000748180, 0xc00280ca00, 0xc001a1cb40, 0xf6fcc10, 0x0, 0x0, 0x0)   
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc001076700, 0xaae04f8, 0xc000748180, 0xc00280ca00, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc001a1a130, 0xc001076700, 0xaae04f8, 0xc000748180, 0xc00280ca00)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xb2
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

**Error: The terraform-provider-aws_v3.75.1_x5.exe plugin crashed!**

### Panic Output

panic: interface conversion: interface {} is nil, not *conns.AWSClient

### Steps to Reproduce

- While applying new changes and destroying environment facing this crashed issue with the provider 

### References

* #0000

**Comment by justinretzolk** [comment] 2022-04-11 18:09
Hey @prashant-eppalpalli 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to investigate this, can you update the issue description to include the Terraform configuration as well?

**Comment by ajmoore001** [comment] 2022-04-12 18:33
Initializing provider plugins...
- Finding hashicorp/random versions matching ">= 3.1.0"...
- Finding hashicorp/aws versions matching ">= 3.62.0, ~> 3.74.3, >= 4.0.0"...
- Installing hashicorp/random v3.1.2...
- Installed hashicorp/random v3.1.2 (signed by HashiCorp)
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/aws: no available releases match the given constraints >= 3.62.0, ~> 3.74.3, >= 4.0.0

**Comment by justinretzolk** [comment] 2022-04-12 19:06
Hey @ajmoore001 👋 It looks like you're running into a bit of a different issue due to the [version constraints](https://www.terraform.io/language/expressions/version-constraints) defined. If you run the command `terraform providers` then it should tell you the individual provider requirements for each module in your configuration, which should hopefully help to determine which module(s) have those version constraints defined to help determine where you may need to make a change. If you're still running into issues after that, I'd recommend opening a new issue within this repository so that we can look at it (so that we're not getting away from the root issue here).

**Comment by justinretzolk** [comment] 2022-05-13 16:23
Hey @jeraldsm 👋 Are you able to provide additional information around what you're experiencing? Without the information requested in my [above comment](https://github.com/hashicorp/terraform-provider-aws/issues/24181#issuecomment-1095375650), we're unable to investigate this issue further.

**Comment by PatriQ1414** [comment] 2022-08-12 13:38
Hey, I started having the same issue on a code set that worked perfectly days ago.
Did we ever come up with any resolution for this?

Error: The terraform-provider-aws_v4.25.0_x5.exe plugin crashed!

**Comment by mattburgess** [comment] 2022-11-19 12:55
@prashant-eppalpalli  @jeraldsm and @PatriQ1414 - are any of you able to reproduce the crash with the latest version of the AWS provider plugin? If so, the EKS related bits of your Terraform configuration would be really useful so that we can try to reproduce and fix the problem. Thanks!

**Comment by gdavison** [comment] 2023-07-05 22:19
Since we haven't received any responses including a Terraform configuration that causes this error, I'm going to close this issue. If you are still encountering it, please open a new issue and include the Terraform configuration that causes this error.

**Closed by gdavison** 2023-07-05 22:19 UTC
Labels: bug, crash, waiting-response, service/iam, service/ec2, service/eks
