### ISSUE TITLE
Invalid checksum for linux_amd64 for release v4.18.0

### ISSUE THREAD

**Issue by erikpaasonen** [hashicorp/terraform-provider-aws#25270] opened 2022-06-10 15:07 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```bash
> terraform -v
Terraform v1.2.1
on darwin_amd64
```

### Affected Resource(s)

* none specifically/can reproduce with any valid resource

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

can be reproduced with any valid HCL.

### Expected Behavior

providers for `darwin_amd64` and `linux_amd64` successfully downloaded and checksum'ed. lockfile properly created/updated.

### Actual Behavior

```
- Fetching hashicorp/aws 4.18.0 for darwin_amd64...
- Obtained hashicorp/aws checksums for darwin_amd64 (signed by HashiCorp)
- Fetching hashicorp/aws 4.18.0 for linux_amd64...

╷
│ Error: Could not retrieve providers for locking
│
│ Terraform failed to fetch the requested providers for linux_amd64 in order to calculate their checksums: some providers could not be installed:
│ - registry.terraform.io/hashicorp/aws: the current package for registry.terraform.io/hashicorp/aws 4.18.0 doesn't match any of the checksums previously recorded in the dependency lock
│ file.
╵
```

### Steps to Reproduce

1. `terraform providers lock -platform=darwin_amd64 -platform=linux_amd64`

### Important Factoids

v4.18.0 was released just a few hours ago.

am able to reproduce this from a Linux system (AWS CodeBuild environment) in addition to pulling the linux_amd64 checksum from a native darwin_amd64 environment; same error message.

**Comment by erikpaasonen** [comment] 2022-06-10 17:52
to clarify a bit, from what I can tell the `terraform providers lock` command appears to be [the proper mechanism for updating](https://www.terraform.io/language/files/dependency-lock#new-provider-package-checksums) the `.terraform.lock.hcl` file. but this command errors out because the new hashes aren't in the existing `.terraform.lock.hcl` that already exists, instead of adding the new hashes into the file. so I seem to have no way other than manual editing to update the hashes in the lock file.

UPDATE: this began to work around 12:48pm central time.
```bash
> terraform providers lock -platform=linux_arm64 -platform=windows_amd64 -platform=darwin_amd64 -platform=linux_amd64
- Fetching hashicorp/local 2.2.3 for linux_arm64...
- Obtained hashicorp/local checksums for linux_arm64 (signed by HashiCorp)
- Fetching hashicorp/aws 4.18.0 for linux_arm64...
- Obtained hashicorp/aws checksums for linux_arm64 (signed by HashiCorp)
- Fetching hashicorp/local 2.2.3 for windows_amd64...
- Obtained hashicorp/local checksums for windows_amd64 (signed by HashiCorp)
- Fetching hashicorp/aws 4.18.0 for windows_amd64...
- Obtained hashicorp/aws checksums for windows_amd64 (signed by HashiCorp)
- Fetching hashicorp/aws 4.18.0 for darwin_amd64...
- Obtained hashicorp/aws checksums for darwin_amd64 (signed by HashiCorp)
- Fetching hashicorp/local 2.2.3 for darwin_amd64...
- Obtained hashicorp/local checksums for darwin_amd64 (signed by HashiCorp)
- Fetching hashicorp/local 2.2.3 for linux_amd64...
- Obtained hashicorp/local checksums for linux_amd64 (signed by HashiCorp)
- Fetching hashicorp/aws 4.18.0 for linux_amd64...
- Obtained hashicorp/aws checksums for linux_amd64 (signed by HashiCorp)

Success! Terraform has updated the lock file.

Review the changes in .terraform.lock.hcl and then commit to your
version control system to retain the new checksums.
```

**Comment by justinretzolk** [comment] 2022-06-10 22:37
Hey @erikpaasonen 👋 Thank you for taking the time to report this, and for coming back to let us know it seems resolved! I just ran a quick test and verified that the issue is resolved now as well, so I'll close this issue out. If you feel I've done this in error, please do let me know.

**Closed by justinretzolk** 2022-06-10 22:37 UTC
Labels: needs-triage
