### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by moravas** [hashicorp/terraform-provider-aws#30902] opened 2023-04-24 04:36 UTC
### Terraform Core Version

1.4.5

### AWS Provider Version

4.64.0

### Expected Behavior

Run terraform with the configuration

### Actual Behavior

Throws error, cannot execute terraform plan or terraform apply

### Relevant Error/Panic Output Snippet

```shell
Plan: 12 to add, 0 to change, 0 to destroy.
╷
│ Error: Invalid provider configuration
│ 
│ Provider "registry.terraform.io/hashicorp/aws" requires explicit configuration. Add a provider block to the root module and configure the provider's required arguments as described in the provider
│ documentation.
│ 
╵
╷
│ Error: configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
│ 
│ Please see https://registry.terraform.io/providers/hashicorp/aws
│ for more information about providing credentials.
│ 
│ AWS Error: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, request canceled, context deadline exceeded
│ 
│ 
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on <empty> line 0:
│   (source code not available)
│ 
╵
```

### Terraform Configuration Files

/main.tf:

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.64.0"
    }
  }
}

#provider "aws" {
#  profile = "live"
#  region  = "us-east-1"
#}

provider "aws" {
  alias   = "dev"
  profile = "dev"
  region  = "us-east-1"
}

provider "aws" {
  alias   = "live"
  profile = "live"
  region  = "us-east-1"
}

module "live_state" {
  source = "./state"

  providers = {
    aws = aws.live
  }
}

module "dev_state" {
  source = "./state"

  providers = {
    aws = aws.dev
  }
}
```

/state/state.tf

```terraform
resource "aws_s3_bucket" "shared_state" {
  bucket = "states"

  lifecycle {
    prevent_destroy = true
  }
}
```

### Steps to Reproduce

run terraform plan

### Important Factoids

Sorry, but this form confuse me a lot, so let me describe my problem here:
I want to manage multiple AWS accounts and deploy same configuration into all of them. The reference above I only pasted S3 resources, but there are others in my script.

So as I learned, I can apply 'alias' on same provider configurations, and I wanted to omit the default provider configuration due to its 'hidden' nature.

If I add a third, default aws provider configuration without alias, it seems, to work, but as in our company, we don't have 'default', we have dedicated and named environments.

But when I run terraform plan, the error message displayed and I cannot proceed,

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2023-04-25 17:30
Hey @moravas 👋 Thank you for taking the time to raise this! This behavior is outlined in the Provider Configuration documentation under the [Default Provider Configuration](https://developer.hashicorp.com/terraform/language/providers/configuration#default-provider-configurations) header. In that document, it calls out:

> If every explicit configuration of a provider has an alias, Terraform uses the implied empty configuration as that provider's default configuration. (If the provider has any required configuration arguments, Terraform will raise an error when resources default to the empty configuration.)

In the case of the AWS provider, there _are_ required configuration arguments, which is why you're receiving the error.

**Comment by moravas** [comment] 2023-04-26 06:58
Hi,

it seems that I could manage to solve the issue. For the future:
originally, this repository relied on the [default] profile  and read out that from the credentials file.
As our business has been developed, we has additional AWS account and I went to manage both from this repository:

1. name every account based on their intention
2. run terraform

but it seems, that terraform won't recognize, 

1. that the original, default provider gone (basically renamed in the .aws/credentails file) 
2. the default provider and the corresponding default the provider configuration got an alias
3. so the already managed resources are there, but should be seen via an another provider configuration

**Comment by justinretzolk** [comment] 2023-05-17 18:19
Hey @moravas 👋 Thank you for coming back with an update! With that in mind, are you comfortable with us closing this issue?

**Comment by vishwa-trulioo** [comment] 2023-05-23 17:16
I can confirm that, The provider `4.67` is definitely having this bug. When I pin it to `4.66` it works. Looks like there has been some change in the provider code that produces this.

**Comment by justinretzolk** [comment] 2023-05-23 18:12
Hey @vishwa-trulioo 👋 The cause of the initial report here was a situation where there were not credentials provided for the default provider (all instances of the provider were aliased), so was a configuration issue rather than an actual bug. Can you give me an idea of what your configuration looks like? I don't expect that this is a bug, but am happy to review again to confirm.

**Comment by porn** [comment] 2023-09-04 10:26
Just hit the same issue!

Fixed by adding a `provider.tf` file:
```
$ cat provider.tf 
provider "aws" {
  region  = "eu-central-1"
  profile = "my-project"
}
```

**Comment by rollovd** [comment] 2023-09-25 11:42
> Just hit the same issue!
> 
> Fixed by adding a `provider.tf` file:
> 
> ```
> $ cat provider.tf 
> provider "aws" {
>   region  = "eu-central-1"
>   profile = "my-project"
> }
> ```

Hey! Could you prompt me, where I need to add this file? What folder? 
Here?

```
denis@denis-TM1703:~/PycharmProjects/terraform-aws-metaflow/examples/eks_argo$ tree .
.
├── argo_events.tf
├── argo.tf
├── eks.tf
├── iam-ecs-execution.tf
├── metaflow_config.tf
├── metaflow.tf
├── outputs.tf
├── provider.tf # <------------------- this one 
├── README.md
├── versions.tf
└── vpc.tf
```

Thanks!

**Comment by porn** [comment] 2023-09-25 12:10
> > Just hit the same issue!
> > Fixed by adding a `provider.tf` file:
> > ```
> > $ cat provider.tf 
> > provider "aws" {
> >   region  = "eu-central-1"
> >   profile = "my-project"
> > }
> > ```
> 
> Hey! Could you prompt me, where I need to add this file? What folder? Here?
> 
> ```
> denis@denis-TM1703:~/PycharmProjects/terraform-aws-metaflow/examples/eks_argo$ tree .
> .
> ├── argo_events.tf
> ├── argo.tf
> ├── eks.tf
> ├── iam-ecs-execution.tf
> ├── metaflow_config.tf
> ├── metaflow.tf
> ├── outputs.tf
> ├── provider.tf # <------------------- this one 
> ├── README.md
> ├── versions.tf
> └── vpc.tf
> ```
> 
> Thanks!

yup, should be the file. Though we stopped using hard-coding profile name.

**Comment by DenisBY** [comment] 2023-10-17 15:08
My issue was because I created a KMS Key first without `resource "aws_kms_replica_key"` and then later I added all that stuff with `configuration_aliases` etc. After reverting all changes, destroying a key, adding `configuration_aliases` etc., and applying everything from scratch, the error is gone.

**Comment by deepak-tiwari-newscorp** [comment] 2024-02-09 14:18
I must insint there should be a way to give providers dynamically in root/calling module. Consider the case when same set of resources must be created in multiple regions

**Comment by justinretzolk** [comment] 2024-03-21 18:42
Since it looks like this came down to a configuration issue, I'm going to close this issue out. As far as ☝️ , I think that'd be great, but it would need to be a feature request at the [Terraform Core](https://github.com/hashicorp/terraform) level 🙂

**Closed by justinretzolk** 2024-03-21 18:42 UTC
Labels: upstream-terraform, authentication
