### ISSUE TITLE
aws_redshiftserverless_namespace iam_roles updates on every plan/apply

### ISSUE THREAD

**Issue by mrobinson1022** [hashicorp/terraform-provider-aws#26624] opened 2022-09-02 13:53 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.2.8
on darwin_amd64

### Affected Resource(s)

* aws_redshiftserverless_namespace

### Terraform Configuration Files

```hcl
resource "aws_redshiftserverless_namespace" "redshift_serverless" {
  namespace_name       = "${terraform.workspace}-${var.project_name}-redshift"
  admin_username       = "xxxxxxx"
  admin_user_password  = "xxxxxx"
  db_name              = "${terraform.workspace}_${var.project_name}_db"
  default_iam_role_arn = aws_iam_role.redshift_serverless.arn
  iam_roles            = [aws_iam_role.redshift_serverless.arn]
  kms_key_id           = aws_kms_key.kms["redshift"].arn
  log_exports          = ["userlog", "connectionlog", "useractivitylog"]
}
```

### Debug Output

```hcl
  ~ resource "aws_redshiftserverless_namespace" "redshift_serverless" {
      ~ iam_roles            = [
          - "IamRole(applyStatus=in-sync, iamRoleArn=arn:aws:iam::xxxxxxxxxx:role/dev-redshift)",
          + "arn:aws:iam::xxxxxxxxxx:role/dev-redshift",
        ]
        id                   = "dev-redshift"
        tags                 = {}
        # (10 unchanged attributes hidden)
    }
```

### Expected Behavior

No changes have been made to the resource since the last apply, the plan should not include a change to this resource. 

### Actual Behavior

Terraform recognizes a change in the iam_roles where the default role shows an `applyStatus=in-sync` and attempts to revert back to just the arn for the given role. 

### Steps to Reproduce

1. `terraform apply` or `terraform plan`

### Important Factoids

none.

**Comment by DrFaust92** [comment] 2022-09-05 20:09
Hi @mrobinson1022, thanks for opening this issue.

this is super strange behaviour on AWS side. as the field is a list of strings and not a complex type. i would strongly advice talking to support and escalate this. we can do some kind of workaround on the provider side but the server side is not really respecting the schema  here and any "check" can easily break.

**Comment by rv-gbell** [comment] 2022-09-30 21:14
@DrFaust92 , This bug appears to be causing additional unintended consequences.  If an update is attempted that solely affects `workgroup`, `apply` will fail, because TF believe multiple configurations are being updated simultaneously.  This is now blocking our ability to make any changes to our serverless workgroup. Please see below.

### Plan
```
Terraform will perform the following actions:
 
 # aws_redshiftserverless_namespace.redshift_serverless_namespace will be updated in-place
!   resource "aws_redshiftserverless_namespace" "redshift_serverless_namespace" {
!       iam_roles            = [
-           "IamRole(applyStatus=in-sync, iamRoleArn=arn:aws:iam::xxxxxxxxxxxx:role/xxxxx)",
-           "IamRole(applyStatus=in-sync, iamRoleArn=arn:aws:iam::xxxxxxxxxxxx:role/xxxxx)",
-           "IamRole(applyStatus=in-sync, iamRoleArn=arn:aws:iam::xxxxxxxxxxxx:role/xxxxx)",
+           "arn:aws:iam::xxxxxxxxxxxx:role/xxxxx",
+           "arn:aws:iam::xxxxxxxxxxxx:role/xxxxx",
+           "arn:aws:iam::xxxxxxxxxxxx:role/xxxxx",
        ]
        id                   = "xxxx-namespace"
        tags                 = {}
        # (10 unchanged attributes hidden)
    }

  # aws_redshiftserverless_workgroup.redshift_serverless_workgroup will be updated in-place
!   resource "aws_redshiftserverless_workgroup" "redshift_serverless_workgroup" {
!       enhanced_vpc_routing = true -> false
        id                   = "xxxx-workgroup"
        tags                 = {}
        # (10 unchanged attributes hidden)

        # (5 unchanged blocks hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.
```

### Apply
```
aws_redshiftserverless_namespace.redshift_serverless_namespace: Modifying... [id=xxxx-namespace]
aws_redshiftserverless_namespace.redshift_serverless_namespace: Modifications complete after 1s [id=xxxx-namespace]
aws_redshiftserverless_workgroup.redshift_serverless_workgroup: Modifying... [id=xxxx-workgroup]

Error: error updating Redshift Serverless Workgroup (xxxx-workgroup): ValidationException: Can't update multiple configurations at the same time for workgroup xxxx-workgroup.
```

**Comment by mtonxbjss** [comment] 2022-10-14 10:49
I have the same issue. As a short term workaround you can add 
```
  lifecycle {
    ignore_changes = [
      iam_roles
    ]
  }
```
as long as you don't need to actually change the IAM roles.

**Comment by ZMarouani** [comment] 2022-12-15 10:06
Has this been resolved ? I have a similar issue when changing admin_username and admin_user_password in  resource "aws_redshiftserverless_namespace" : `Error: updating Redshift Serverless Namespace (xxxxx): ValidationException: Amazon Redshift Serverless can't update multiple configurations at the same time for namespace xxxxx.`

**Comment by lukevers** [comment] 2023-01-25 14:41
Seeing the same problem on my end. Adding the lifecycle change works fine for now..but clearly isn't a great solution.

It might also be interesting to note that I actually have the same problem here if I try and change `security_group_ids` on `aws_redshiftserverless_workgroup` from nothing (default sg) to a generated sg.

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # xxxxxxxxxx will be updated in-place
  ~ resource "aws_redshiftserverless_workgroup" "main" {
        id                   = "xxxxxxxxxx"
      ~ security_group_ids   = [
          + "sg-0000000000000new",
          - "sg-00000000000default",
        ]
        tags                 = {
            "Environment" = "production"
            "Terraform"   = "true"
        }
        # (10 unchanged attributes hidden)

        # (7 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

```
Error: error updating Redshift Serverless Workgroup (xxxxxxxxxx): ValidationException: Can't update multiple configurations at the same time for workgroup xxxxxxxxxx.
```

**Comment by DrFaust92** [comment] 2023-03-07 21:03
[pedropperez](https://github.com/pedropperez), when you say per AWS. who do you mean? https://docs.aws.amazon.com/redshift-serverless/latest/APIReference/API_CreateNamespace.html#redshiftserverless-CreateNamespace-request-iamRoles say otherwise

**Comment by pedropperez** [comment] 2023-03-08 01:33
> [pedropperez](https://github.com/pedropperez), when you say per AWS. who do you mean? https://docs.aws.amazon.com/redshift-serverless/latest/APIReference/API_CreateNamespace.html#redshiftserverless-CreateNamespace-request-iamRoles say otherwise

I asked the question to a couple of aws enginners. yes, creating the namespace we only provide the role's arns; but the get command returns it as a list of pairs (status and role). I'll reach out again and get more specifics

**Comment by kravvcu** [comment] 2023-03-08 19:07
`aws redshift-serverless list-namespaces` and `get-namespace` returns what Terraform actually shows - the information on the role being in 'in-sync' status. The question is whether this is the correct format (I can't find it in the API definition) or maybe just a bug in AWS (object.to_string instead of the .arn attribute returned? ;)) and whether this is an issue within the service itself (this 'in-sync' status kind of bothers me; does it mean it 'is synchronising' or 'is synced'? :)).

**Comment by pedropperez** [comment] 2023-03-08 19:49
> `aws redshift-serverless list-namespaces` and `get-namespace` returns what Terraform actually shows - the information on the role being in 'in-sync' status. The question is whether this is the correct format (I can't find it in the API definition) or maybe just a bug in AWS (object.to_string instead of the .arn attribute returned? ;)) and whether this is an issue within the service itself (this 'in-sync' status kind of bothers me; does it mean it 'is synchronising' or 'is synced'? :)).

From what I was told, it means that it is synced. Never seen a value such a syncing.

**Comment by JamesWhyley** [comment] 2023-04-11 16:38
Minor note on this. If you only require the default role you can specify that without the `iam_roles` and it'll stop the unexpected behaviour. 

Obviously this doesn't help in more complicated use cases but until the broader issue is resolved, it's worth noting.

**Comment by JamesWhyley** [comment] 2023-04-11 17:08
Hmm. Not my initial experience but I may have missed something. Will give it another test when I get a few minutes.

**Comment by christoph-buente** [comment] 2023-04-19 15:58
Same problem here. Setting the role via ARN but on terraform plan it fetches a longer string with the status. Couldn't that be fixed by parsing the AWS response in the terraform provider? Would be good to get that fixed.

**Comment by barsilver** [comment] 2023-05-04 08:05
+1 
Trying to change the value of `enhanced_vpc_routing` for the workgroup. This is the only resource that seems to be updated in the `terraform plan` but it fails on the same error.
`Error: updating Redshift Serverless Workgroup (xxxxxxxxx): ValidationException: Can't update multiple configurations at the same time for workgroup xxxxxxxxx.`

**Comment by pedropperez** [comment] 2023-05-04 13:19
I think this is related to issue https://github.com/hashicorp/terraform-provider-aws/issues/26624
There may be another update trying to take place on the worksgroup configuration

**Comment by gmarmstrong** [comment] 2023-05-04 13:53
> I think this is related to issue #26624 There may be another update trying to take place on the worksgroup configuration

This issue is #26624. Did you perhaps mean #29962?

**Comment by pedropperez** [comment] 2023-05-04 14:51
My mistake, I meant https://github.com/hashicorp/terraform-provider-aws/issues/27973

I have both in an support ticket with hashicorp. 

I was not aware of https://github.com/hashicorp/terraform-provider-aws/issues/29962. I had not tried to delete workspace yet

**Closed** 2023-06-02 21:58 UTC
Labels: bug, upstream, service/redshiftserverless
