### ISSUE TITLE
Defining multiple aws_cognito_resource_server.scope's broken in new version

### ISSUE THREAD

**Issue by LUS1N** [hashicorp/terraform-provider-aws#10159] opened 2019-09-19 11:05 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.9
+ provider.aws v2.28.1

### Affected Resource(s)

aws_cognito_resource_server

* aws v2.28.1

### Terraform Configuration Files

```hcl
resource "aws_cognito_resource_server" "global" {
  user_pool_id = "${aws_cognito_user_pool.my_pool.id}"

  identifier = "${lower(var.environment)}-internalarchitecture"
  name       = "${var.environment}-InternalArchitecture"

  scope = [
    {
      scope_name        = "biscrapper"
      scope_description = "Scope for BI Scrapper"
    },
    {
      scope_name        = "timeentryservice"
      scope_description = "Scope"
    }
   ]
}

```

### Expected Behavior

In the previous version of terraform (0.11) and aws provider (1.26) this was running fine and creating all the defined resource server scope identifiers. [Documentation](https://www.terraform.io/docs/providers/aws/r/cognito_resource_server.html#authorization_scope) for `aws_cognito_resource_server` also specified that `scope` is a list of identifiers. So I expect to be able to define multiple resource server scopes.

### Actual Behavior
```
Error: Unsupported argument

  on resource_servers.tf line 7, in resource "aws_cognito_resource_server" "global":
   7:   scope = [

An argument named "scope" is not expected here. Did you mean to define a block
of type "scope"?
```

I tried adding multiple `scope` blocks, like such

```
scope {<..>}
scope {<..>}
```

but then i get the output that only 1 `scope` block can be defined. 

How do I apply the list of scopes now?

### Steps to Reproduce

1. `terraform apply`

**Comment by jgournet** [comment] 2019-10-09 04:45
For anyone stuck on this, here is how we managed to get several scopes:
`
variable "scopes" {
  type = "map"
  default = {
    scope1 = {
      "scope_name": "Hello"
      "scope_description": "description"
    },
    scope2 = {
      "scope_name": "Hello2"
      "scope_description": "description"
    }
  }
}

resource "aws_cognito_resource_server" "resource_server" {
  identifier = var.name
  name       = var.name

  dynamic "scope" {
    for_each = [for key, value in var.scopes: {
      scope_name     = value.scope_name
      scope_description     = value.scope_description
    }]

    content {
      scope_name     = scope.value.scope_name
      scope_description = scope.value.scope_description
    }
  }

  user_pool_id = var.pool_id
}
`

**Comment by gjsduarte** [comment] 2020-12-03 16:51
This now seems to work properly with version 3.15.0 of the was provider and terraform 0.14.0

**Comment by kyle-thedelta** [comment] 2021-02-06 17:54
I reproduced this issue on terraform 0.14.0 and aws provider 3.20.0

**Comment by kyle-thedelta** [comment] 2021-03-09 12:19
Also I can only do maximum 2 scopes using the above workaround

**Comment by kyle-thedelta** [comment] 2021-03-09 12:36
Discovered that you have to apply the scopes in one "apply" and then reference them in the next "apply"

**Comment by tillkuhn** [comment] 2021-04-08 16:44
For anyone with a recent provider version (I tried with 3.35.0) who is confused whether to use the "dynamic" workaround, the original poster's syntax, or something else: This snippet works for 2 or more scopes - no further workarounds required:

```
resource "aws_cognito_resource_server" "main" {
  user_pool_id = aws_cognito_user_pool.main.id

  identifier = "${var.appid}-resources"
  name = "${var.appid} resources"

  scope {
    scope_name = "read"
    scope_description = "..."
  }

  scope {
    scope_name = "write"
    scope_description = "..."
  }

  scope {
    scope_name = "make-it-three"
    scope_description = "..."
  }

}
```

**Comment by kyle-thedelta** [comment] 2021-04-09 09:50
Yes, also just confirming that the above works fine on aws provider 3.26.0

**Comment by Nimsgs** [comment] 2021-06-07 03:59
How can I pass the scopes if aws_cognito_resource_server is created in a module and we have to pass the scopes to that module.
eg:
I created a module for creating the cognito resources and I have to pass the scopes to that module. Tried passing the scope as a variable but it doesn't recognize the scope name and description in the module.

variable "application-scopes" {
  type = map(string)
  default = {
    scope1 = {
      "scope_name" : "get"
      "scope_description" : "can make get request"
    },
    scope2 = {
      "scope_name" : "post"
      "scope_description" : "can make post request "
    }
  }
}

module "cognito" {
source = "./cognito"
scopes = var.application-scopes
}


resource "aws_cognito_resource_server" "application-resource-server" {
  identifier   = var.cognito_rs_id
  name         = var.cognito_rs_name
  user_pool_id = aws_cognito_user_pool.application-pool.id

  dynamic "scope" {
    for_each = [for key, value in var.scopes : {
      **_scope_name        = value.scope_name
      scope_description = value.scope_description_**
    }]

    content {
      scope_name        = scope.value.scope_name
      scope_description = scope.value.scope_description
    }
  }
}

**Comment by justinretzolk** [comment] 2021-12-09 21:25
Hey y'all 👋 Thank you for taking the time to file this issue and for the continued discussion! Given that there's been a number of AWS provider releases since it was initially filed, can anyone confirm whether you're still experiencing this behavior?

**Comment by tillkuhn** [comment] 2021-12-10 09:48
@justinretzolk: I can confirm that the code from my https://github.com/hashicorp/terraform-provider-aws/issues/10159#issuecomment-815976453 which uses the `scope` argument multiple times is still working within recent versions of Terraform and AWS Provider. This seems to be in accordance with the [official docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_resource_server#argument-reference) that describe scope as 

> scope - (Optional) A list of Authorization Scope.

Versions:
```
Terraform v1.1.0 on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.68.0
```

**Comment by kyle-thedelta** [comment] 2021-12-10 10:08
@tillkuhn i havent tested my side but is it not neccesary to add the scopes and use the scopes in two different "apply"s?

**Comment by codezninja** [comment] 2022-05-07 02:04
I'm having the following issue. I'm able to create multiple scopes using `dynamic` but the attribute `scope_identifiers` is an empty list event the `scope` attribute shows all the scopes that have been created.

**Comment by santrancisco** [comment] 2023-01-23 14:12
I can confirm  that using multiple scopes under aws_cognito_resource_server will create the custom scopes correctly

This is tested with the latest aws provider (4.51.0) and latest terraform version (v1.3.7). This issue can be closed imo.
Screenshot below.
![CleanShot 2023-01-23 at 21 08 25](https://user-images.githubusercontent.com/3240146/214060391-b2843b6c-904e-4ab8-97c0-57cdfbb5188d.png)

**Comment by justinretzolk** [comment] 2023-01-23 17:45
Hey all 👋 Given the feedback that this issue seems to be resolved, we'll close this issue out. If you experience this issue again with new versions of the AWS Provider, please open a new issue so that we can take another look.

@codezninja 👋 It sounds like you may be having a slightly different issue. I'd recommend taking a quick look over the documentation on [references to values](https://developer.hashicorp.com/terraform/language/expressions/references#references-to-resource-attributes); particularly the section on using `for_each`. If that doesn't help, please feel free to open a new issue or open a discussion on the [AWS Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33).

**Closed by justinretzolk** 2023-01-23 17:45 UTC
