### ISSUE TITLE
[Bug]: terraform plan succeeds when it shouldn't with NLB listener and an ALB as a target group

### ISSUE THREAD

**Issue by mattlorimor** [hashicorp/terraform-provider-aws#39349] opened 2024-09-16 19:11 UTC
### Terraform Core Version

v1.9.5

### AWS Provider Version

v5.67.0

### Affected Resource(s)

* `aws_lb_listener`
  * `protocol`
* `aws_lb_target_group`
  * `target_type`

### Expected Behavior

A `terraform plan` should fail with an error stating that the `protocol` for an `aws_lb_listener` _must be_ `TCP` when the `aws_lb_target_group` `type` is `alb`.

### Actual Behavior

A successful `terraform plan` ran for an incorrectly configured AWS load balancer listener. It wasn't known there was a misconfiguration until the `terraform apply` was attempted and the AWS API errored.

### Relevant Error/Panic Output Snippet

```shell
Error: creating ELBv2 Listener (arn:aws:elasticloadbalancing:us-east-1:ACCOUNT_NUMBER:loadbalancer/net/NLB_NAME/NLB_ID): operation error Elastic Load Balancing v2: CreateListener, https response error StatusCode: 400, RequestID: REQUEST_ID, InvalidLoadBalancerAction: Listener protocol 'TLS' is not supported with a target group with the target-type 'ALB'
```

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "= 5.67.0"
    }
  }
  required_version = "= 1.9.5"
}

provider "aws" {
  skip_credentials_validation = true
  skip_requesting_account_id  = true
  max_retries                 = 1
  skip_metadata_api_check     = true
  access_key                  = "a"
  secret_key                  = "a"
  region                      = "us-west-2"

  endpoints {
    ec2 = "http://127.0.0.1:5000/"
  }
}

resource "aws_lb" "test-nlb" {
  name               = "test-nlb"
  internal           = true
  load_balancer_type = "network"
  subnet_mapping {
    subnet_id            = "TEST-SUBNET-ID"
    private_ipv4_address = "10.0.1.15"
  }
}

resource "aws_lb_target_group" "test-nlb-tg" {
  name        = "test-nlb-tg"
  port        = 443
  protocol    = "TCP"
  vpc_id      = "vpc-TEST-VPC"
  target_type = "alb"
}

resource "aws_lb_target_group_attachment" "test-nlb-tg-attachment" {
  target_group_arn = aws_lb_target_group.test-nlb-tg.arn
  target_id        = "TEST-ALB.arn"
  port             = 443
}

resource "aws_lb_listener" "test-nlb-listener" {
  load_balancer_arn = aws_lb.test-nlb.arn
  port              = "443"
  protocol          = "TLS"
  ssl_policy        = "ELBSecurityPolicy-TLS-1-2-2017-01"

  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.test-nlb-tg.arn
  }
}
```

### Steps to Reproduce

The above HCL was written with the intent of being able to perform a `terraform plan` without contacting actual AWS since my goal was to see what plan-time validation the AWS provider would do. You should just be able to run `terraform plan` against the provided HCL and see that it will plan out without any complaints even though the [AWS documentation states](https://docs.aws.amazon.com/elasticloadbalancing/latest/network/application-load-balancer-target.html) that a listener protocol of `TCP` is the only valid value for an NLB listener when the target group is an ALB.

> 7. Listeners and routing
>   a. The default is a listener that accepts TCP traffic on port 80. Only TCP listeners can forward traffic to an Application Load Balancer target group. You must keep Protocol as TCP, but you can modify Port as needed.
     With this configuration, you can use HTTPS listeners on the Application Load Balancer to terminate TLS traffic.

It's only when you actually go to `terraform apply` that you will encounter the AWS API error message informing you that you have the listener protocol set incorrectly for the configured target group target type.

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment] 2024-11-04 17:32
Hey @mattlorimor 👋 Thank you for taking the time to raise this! Terraform resources aren't able to perform validations across different resource types in the way that you're looking for with this report, since the resources are (at the provider level) entirely self-contained, and don't have awareness of other resources defined in a configuration.

That said, Terraform `1.2.0` and later has a feature called [preconditions](https://developer.hashicorp.com/terraform/language/expressions/custom-conditions#preconditions-and-postconditions) that you can leverage in order to perform a check like this. Those checks will happen as early as possible, so should catch this type of configuration mishap during the plan phase.

With that information in mind, since there's no action for the AWS Provider team to take at this time, I'm going to close this issue. If you encounter any other unexpected behavior, please do let us know!

**Closed by justinretzolk** 2024-11-04 17:32 UTC
Labels: bug, service/elbv2, needs-triage
