### ISSUE TITLE
[Bug]: AWS Data Lifecycle Manager Policy doesn't support multiple targets with same tag key but different value

### ISSUE THREAD

**Issue by bjammal** [hashicorp/terraform-provider-aws#34176] opened 2023-10-31 10:32 UTC
### Terraform Core Version

1.6.2

### AWS Provider Version

5.15.0

### Affected Resource(s)

* aws_dlm_lifecycle_policy

### Expected Behavior

targetting multiple resources with the **same tag key** but different tag value must be possible. It can be done via the Console by simply adding multiple tags. For example, I could target volumes with Name=Value1 and Name=Value2.

### Actual Behavior

When I add multiple target tag with the same tag key to the `policy_details` block of `aws_dlm_lifecycle_policy`, only the last one is considered. 

For example:

```
    target_tags = {
      Name = "value1"
      Name = "value2"
      Name = "value3"
    }
```

gives a terraform plan that only target resources with Name = "value3", as follows:
```
  + resource "aws_dlm_lifecycle_policy" "dlm" {
      + arn                = (known after apply)
      + description        = "DLM lifecycle policy"
      + execution_role_arn = "arn:aws:iam::accound-id:role/iamr-dlm-lifecycle-role"
      + id                 = (known after apply)
      + state              = "ENABLED"

      + policy_details {
          + policy_type        = "EBS_SNAPSHOT_MANAGEMENT"
          + resource_locations = (known after apply)
          + resource_types     = [
              + "VOLUME",
            ]
          + target_tags        = {
              + "Name" = "value3"
            }

          + schedule {
              + copy_tags   = true
              + name        = "1 month of daily snapshots"
              + tags_to_add = {
                  + "SnapshotCreator" = "DLM"
                }

              + create_rule {
                  + interval      = 24
                  + interval_unit = "HOURS"
                  + location      = (known after apply)
                  + times         = [
                      + "00:00",
                    ]
                }

              + retain_rule {
                  + count = 30
                }
            }
        }
    }
```

A workaround is to implement separate policy for each target tag, but this would create repetitive code.

### Terraform Configuration Files

```
resource "aws_dlm_lifecycle_policy" "dlm" {
  description        = "DLM lifecycle policy"
  execution_role_arn = aws_iam_role.dlm_lifecycle_role.arn
  state              = "ENABLED"

  policy_details {
    resource_types = ["VOLUME"]

    schedule {
      name = "1 month of daily snapshots"

      create_rule {
        interval      = 24
        interval_unit = "HOURS"
        times         = ["00:00"]
      }

      retain_rule {
        count = 30
      }

      tags_to_add = {
        SnapshotCreator = "DLM"
      }

      copy_tags = true
    }

    target_tags = {
      Name = "value1"
      Name = "value2"
      Name = "value3"
    }
  }
}
```

### Steps to Reproduce

Create a `aws_dlm_lifecycle_policy` with several target_tags of the same tag key but different values similar to the configuration file provided above.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2023-11-02 21:31
Hey @bjammal 👋 Thank you for taking the time to raise this! It looks like this is a duplicate of #8120. We try to keep conversations around the same issue isolated to a single GitHub issue in an effort to keep things tidy. With that in mind, we'll be closing this issue out and continuing the conversation over on #8120.

**Comment by justinretzolk** [comment] 2023-11-02 21:31
Duplicate of #8120

**Closed by justinretzolk** 2023-11-02 21:31 UTC
Labels: bug, service/dlm, needs-triage
