### ISSUE TITLE
Plugin Crash during Terraform plan

### ISSUE THREAD

**Issue by JTP3XP** [hashicorp/terraform-provider-aws#19779] opened 2021-06-11 21:17 UTC
The plans in one of my workspaces (and only one - even though I have others which use the same modules and look extremely similar) is failing with a message about the aws plugin crashing. I reverted my plan back to a known good plan which ran successfully 3 days ago, but this also fails.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Originally I was using terraform 0.14.4 and aws provider 3.27 and having the issue, but see the error in terraform 1.0.0 and aws provider 3.45 as well. The error messages look a little different, but no version seems to run.

### Affected Resource(s)

I can't tell what resource is affected.

### Terraform Configuration Files
To keep things brief I am just including one of several calls to the "ec2" module. This configuration just runs a bunch of very similar calls to this module to create several similar ec2 instances.

```hcl
terraform {
	required_providers {
		aws = {
			source = "hashicorp/aws"
			version = "3.45.0"
		}
	}
	
	backend "remote" {
		organization = "PotomacEconomics"

		workspaces {
			name = "compute-prod-pe-us-east-1"
		}
	}
}

provider "aws" {
	region = "us-east-1"
}


#
# Get information needed for configuration
#

data "aws_security_group" "default_security_group" {
  tags = {
		Name = "sgroup-${var.environment_type}-${var.environment_name}-default"
		Terraform = "true"
		Environment_Name = var.environment_name
		Environment_Type = var.environment_type
	}
}

data "aws_security_group" "windows_security_group" {
  tags = {
		Name = "sgroup-${var.environment_type}-${var.environment_name}-windows"
		Terraform = "true"
		Environment_Name = var.environment_name
		Environment_Type = var.environment_type
	}
}

data "aws_security_group" "dc_security_group" {
  tags = {
		Name = "sgroup-${var.environment_type}-${var.environment_name}-dc"
		Terraform = "true"
		Environment_Name = var.environment_name
		Environment_Type = var.environment_type
	}
}

data "aws_security_group" "commonfileserver_security_group" {
  tags = {
		Name = "sgroup-${var.environment_type}-${var.environment_name}-commonfileserver"
		Terraform = "true"
		Environment_Name = var.environment_name
		Environment_Type = var.environment_type
	}
}

data "aws_security_group" "securityserver_security_group" {
  tags = {
		Name = "sgroup-${var.environment_type}-${var.environment_name}-securityserver"
		Terraform = "true"
		Environment_Name = var.environment_name
		Environment_Type = var.environment_type
	}
}

#
# APP1
#

module "ec2_app1" {
	source  = "app.terraform.io/PotomacEconomics/ec2/aws"
	version = "1.0.30"

	environment_name = var.environment_name
	environment_type = var.environment_type
	instance_suffix = "app1"
	availability_zone_number = "1"
	
	instance_type = "t3.2xlarge"
	ami_id = "ami-xxx"
	root_volume_size = 150
	secondary_volume_size = 1
	iam_instance_profile = "Windows-Server-Role"
	
	private_ip = "x.x.x.x"
	vpc_security_group_ids = [
		data.aws_security_group.default_security_group.id,
		data.aws_security_group.windows_security_group.id
	]
	
	backup_plan = "${var.environment_name}_daily"
}
```

### Debug Output
https://gist.github.com/JTP3XP/deb5db6a0201ff5f68a542c2100ee69f

### Panic Output
I'm running this in Terraform Cloud, so I don't know how to get the crash.log

### Expected Behavior
Plan runs as it did before

### Actual Behavior
Terraform crashes and blames the aws plugin

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by anGie44** [comment] 2021-06-11 23:58
Possibly duplicate of https://github.com/hashicorp/terraform-provider-aws/issues/17284 (and related to issues linked in there)

**Comment by ewbankkit** [comment] 2021-06-14 13:03
```
panic: interface conversion: interface {} is nil, not []map[string]interface {}

goroutine 1224 [running]:
github.com/terraform-providers/terraform-provider-aws/aws.readBlockDevices(0xc001ec5c00, 0xc001e02d80, 0xc0013f65f0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_instance.go:1781 +0x799
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsInstanceRead(0xc001ec5c00, 0x63161c0, 0xc000a2a000, 0xb41f4c0, 0xc000425400)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/aws/resource_aws_instance.go:994 +0x19c6
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000a41500, 0x7c5a368, 0xc00154b9c0, 0xc001ec5c00, 0x63161c0, 0xc000a2a000, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000a41500, 0x7c5a368, 0xc00154b9c0, 0xc000b1da40, 0x63161c0, 0xc000a2a000, 0xc001ad47a0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000288f18, 0x7c5a368, 0xc00154b9c0, 0xc00154ba00, 0xc00154b9c0, 0x40b965, 0x6c20b20)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.6.1/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc000dea520, 0x7c5a410, 0xc00154b9c0, 0xc001160fc0, 0xc000dea520, 0xc0019c7350, 0xc0013e6ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x6ef0f20, 0xc000dea520, 0x7c5a410, 0xc0019c7350, 0xc001160f60, 0x0, 0x7c5a410, 0xc0019c7350, 0xc000a02000, 0x8e4)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00017f340, 0x7c7bed8, 0xc0011d4600, 0xc001afec00, 0xc000c6b0e0, 0xb3de810, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00017f340, 0x7c7bed8, 0xc0011d4600, 0xc001afec00, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00110c170, 0xc00017f340, 0x7c7bed8, 0xc0011d4600, 0xc001afec00)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
```

**Closed** 2022-01-25 13:23 UTC
Labels: bug, crash, service/ec2
