### ISSUE TITLE
[Bug]: Cognito User Pool: can't add new custom attribute after having created an attribute with empty string_attribute_constraints

### ISSUE THREAD

**Issue by dtsomp** [hashicorp/terraform-provider-aws#37687] opened 2024-05-24 14:33 UTC
### Terraform Core Version

v1.5.7,v1.3.9

### AWS Provider Version

v5.9.0

### Affected Resource(s)

* aws_cognito_user_pool

### Expected Behavior

The new custom attribute should have been created. 

### Actual Behavior

```
│ Error: updating Cognito User Pool (us-east-1_XXXXXXX): cannot modify or remove schema items
```
New attribute has **not** been created. 

I can however create the new custom attribute just fine via the AWS console and start using it immediately. Also, any further terraform runs will show "0 changes".

### Terraform Configuration Files

 ```
resource "aws_cognito_user_pool" "pool" {
    name = local.full_project_name
    tags = var.app_tags
   
    schema {
      attribute_data_type      = "String"
      developer_only_attribute = false
      mutable                  = true
      name                     = "org"
      required                 = false
     string_attribute_constraints {
     }
   }

## Uncomment the following for the second terraform run
#   schema {
#     attribute_data_type      = "String"
#     developer_only_attribute = false
#     mutable                  = true
#     name                     = "memberof"
#     required                 = false
#     string_attribute_constraints {
#       max_length = 2048
#       min_length = 1
#     }
#  }
}
```

### Steps to Reproduce

1. Create a user pool with a custom attribute that has empty `string_attribute_constraints`
2. Add another schema block for a second custom attribute (see commented block) and run `terraform apply` again.

### References

It seems that [accrisoftteam](https://github.com/accrisoftteam) was right on spot here: https://github.com/hashicorp/terraform-provider-aws/issues/21654#issuecomment-1061000186

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment] 2024-05-28 20:06
Hey @dtsomp 👋 Thanks for taking the time to submit this issue. It looks like this is a duplicate of #20276. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of that one.

**Comment by justinretzolk** [comment] 2024-05-28 20:07
Duplicate of #20276

**Closed by justinretzolk** 2024-05-28 20:07 UTC
Labels: bug, service/cognitoidp
