### ISSUE TITLE
transit-gateway-cross-account-peering-attachment example is not working

### ISSUE THREAD

**Issue by buryaleksey** [hashicorp/terraform-provider-aws#25617] opened 2022-06-29 12:56 UTC
Code provided in https://github.com/hashicorp/terraform-provider-aws/blob/main/examples/transit-gateway-cross-account-peering-attachment/main.tf#L57 doesn't work.

`Error: error accepting EC2 Transit Gateway Peering Attachment: InvalidParameterValue: Cannot accept tgw-attach-<id> as the source of the peering request.`

It points to a peering attachment ID in the second account. While TF resources states "[transit_gateway_attachment_id] - The ID of the EC2 Transit Gateway Peering Attachment to manage."
So it needs to be an ID of an attachment in the first account, not second.

**Comment by justinretzolk** [comment] 2022-07-08 19:43
Hey @buryaleksey 👋 Thanks for taking the time to submit this issue. It looks like this is a duplicate of #24677. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #24677.

**Closed by justinretzolk** 2022-07-08 19:43 UTC
Labels: needs-triage
