### ISSUE TITLE
[Enhancement]: Add source_resource to aws_vpc_ipam_pool

### ISSUE THREAD

**Issue by eewoolley** [hashicorp/terraform-provider-aws#35033] opened 2023-12-21 19:00 UTC
### Description

AWS has added a "Resource planning" feature to AWS IPAM.  When creating an IPAM pool a new option to either "Plan IP space within the scope" or "Plan IP space within a VPC" been added in the UI.  

If selected, "Plan IP space within a VPC" allows you to select a VPC (and CIDR) as the parent pool.  Once this VPC child pool is created, subnets can be created by simply requesting a subnet size and address space is automatically allocated from IPAM.

This attribute has been added to the AWS Cli as "--source-resource" and is documented here: https://docs.aws.amazon.com/cli/latest/reference/ec2/create-ipam-pool.html

Once the new attribute is supported within aws_vpc_ipam_pool new "ip_allocated" and "netmask_length" attributes will need to be added to aws_subnet to allow the creation of subnets using aws_vpc_ipam allocations.

### Affected Resource(s) and/or Data Source(s)

aws_vpc_ipam_pool
aws_subnet

### Potential Terraform Configuration

```terraform
resource "aws_vpc_ipam_pool" "example" {
  address_family  = "ipv4"
  ipam_scope_id   = aws_vpc_ipam.example.private_default_scope_id
  locale          = data.aws_region.current.name
  source_resource = aws_vpc.example.id
}

resource "aws_subnet" "example" {
  vpc_id              = aws_vpc.example.id
  ipv4_ipam_pool_id   = aws_vpc_ipam_pool.example.id
  ipv4_netmask_length = var.ipv4_netmask_length
}
```

### References
AWS Cli Command Reference:
https://docs.aws.amazon.com/cli/latest/reference/ec2/create-ipam-pool.html?highlight=source-resource
https://docs.aws.amazon.com/cli/latest/reference/ec2/create-subnet.html?highlight=ipv4-netmask-length

### Would you like to implement a fix?

No

**Comment by drewmullen** [comment] 2024-01-11 14:11
Thank you for opening this issue. This is a duplicate of: https://github.com/hashicorp/terraform-provider-aws/issues/34615

**Closed by drewmullen** 2024-01-11 14:11 UTC
Labels: enhancement, needs-triage, service/ipam, service/vpc
