### ISSUE TITLE
produced an invalid new value for in aws_lambda_function 

### ISSUE THREAD

**Issue by mgzenitech** [hashicorp/terraform-provider-aws#15006] opened 2020-09-03 10:06 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/aws v3.2.0
```

### Affected Resource(s)

* aws_lambda_function

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Actual Behavior

```
When expanding the plan for
module.audio_encoder_media_files.module.lambda_function_pipeline_trigger.aws_lambda_function.lambda
to include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" produced an invalid new value for
.environment[0].variables["OUTPUTS"]: was
cty.StringVal("{\"flac\":\"1351620000001-300110\",\"mp3\":\"1598599462852-42j71a\",\"ogg\":\"1598599460431-ioqehk\",\"wav\":\"1351620000001-300300\"}"),
but now
cty.StringVal("{\"flac\":\"1351620000001-300110\",\"mp3\":\"1598599462852-42j71a\",\"mp4\":\"1598599460050-gtjtkk\",\"ogg\":\"1598599460431-ioqehk\",\"wav\":\"1351620000001-300300\"}").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Steps to Reproduce

1. Create lambda function with some environment variable value
2. Change value of the previous env var
3. Apply

### References

* #0000

**Comment by gdavison** [comment] 2020-09-03 19:32
Hi @mgzenitech. Could you provide a sample Terraform configuration that causes this error, please?

**Comment by bflad** [comment] 2021-01-22 17:26
It's been a long time since we heard from you here so we're going to close this out. If you're still having this problem, please feel free to open a new issue and complete all of the information requested in the [Bug Report template](https://github.com/hashicorp/terraform-provider-aws/issues/new?template=Bug_Report.md) so that we can attempt to understand and reproduce the problem.

**Closed by bflad** 2021-01-22 17:26 UTC
Labels: service/lambda, waiting-response
