### ISSUE TITLE
efs_volume_configuration transit_encryption_port causing replace of task definition 

### ISSUE THREAD

**Issue by InbarRose** [hashicorp/terraform-provider-aws#23541] opened 2022-03-07 09:37 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

$ terraform -v
Terraform v1.1.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.74.3
+ provider registry.terraform.io/hashicorp/external v2.2.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

aws_ecs_task_definition -> volume - > efs_volume_configuration -> transit_encryption_port

relevant code: https://github.com/hashicorp/terraform-provider-aws/blob/de6e94dea7b75ab5cf89626386da1747ed50d4b8/internal/service/ecs/task_definition.go#L355

reference: https://www.reddit.com/r/Terraform/comments/px60pb/terraform_constantly_reattaches_volumes_when/

* aws_XXXXX

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
volume {
    name = var.efs_volume_name
    efs_volume_configuration {
      file_system_id     = data.aws_efs_file_system.shared_fs.id
      root_directory     = "/"
      transit_encryption = "DISABLED"
      authorization_config {
        iam = "DISABLED"
      }
    }
  }
```

### Expected Behavior

no change

### Actual Behavior

it wants to replace

      - volume {
          - name = "efs" -> null
          - efs_volume_configuration {
              - file_system_id          = "fs-07d0e24a8153ed93c" -> null
              - root_directory          = "/" -> null
              - transit_encryption      = "DISABLED" -> null
              - transit_encryption_port = 0 -> null
              - authorization_config {
                  - iam = "DISABLED" -> null
                }
            }
        }
      + volume {
          + name = "efs"
          + efs_volume_configuration {
              + file_system_id     = "fs-07d0e24a8153ed93c"
              + root_directory     = "/"
              + transit_encryption = "DISABLED"
              + authorization_config {
                  + iam = "DISABLED"
                }
            }
        }

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by InbarRose** [comment] 2022-03-31 19:59
any movement on this?

**Comment by markbaird** [comment] 2022-04-21 13:50
I'm also seeing this. I would add that you can't set the transit encryption port value to `0` in Terraform. It seems to store it as `0` internally when the value is `null` or unset, but Terraform doesn't handle that well and results in this perpetual diff.

**Comment by amh-mw** [comment] 2022-05-13 13:32
Duplicate of #19549?

**Comment by dsoprea** [comment] 2022-11-01 22:27
So annoying. Every time.

![image](https://user-images.githubusercontent.com/715626/199353717-4a4724e0-8622-4b1a-a833-c2fb7decc7ec.png)

**Comment by ragumix** [comment] 2023-01-10 10:42
Try to explicitly specify transit_encryption_port = null.

**Comment by dsoprea** [comment] 2023-01-10 20:26
> Try to explicitly specify transit_encryption_port = null.

Mentioned earlier in 2022, above.

https://github.com/hashicorp/terraform-provider-aws/issues/23541#issuecomment-1105236380

**Comment by bpmb82** [comment] 2023-02-23 08:05
Has anyone found a workaround for this? I tried adding transit_encryption_port as a lifecycle ignore but then it starts complaining about it not being set. I can try setting it to some random value I suppose, anyone tried that?

**Comment by sethjeffery** [comment] 2023-08-25 20:17
The following works for me and does not recreate it on next apply:

```terraform
  volume {
    name = "efs"
    efs_volume_configuration {
      file_system_id = data.aws_efs_file_system.efs.file_system_id
      transit_encryption_port = null
      transit_encryption = "DISABLED"
      root_directory = "/"
    }
  }
```

**Comment by markbaird** [comment] 2023-08-25 21:55
> The following works for me and does not recreate it on next apply:
> 
> ```terraform
>   volume {
>     name = "efs"
>     efs_volume_configuration {
>       file_system_id = data.aws_efs_file_system.efs.file_system_id
>       transit_encryption_port = null
>       transit_encryption = "DISABLED"
>       root_directory = "/"
>     }
>   }
> ```

It makes sense that disabling encryption would fix the issue with the encryption port. However, those of us that need to keep encryption enabled can't use this as a solution.

**Closed** 2023-10-20 16:46 UTC
Labels: bug, service/ecs
