### ISSUE TITLE
Random failures during terraform plan/apply on M1 +  Rosetta (darwin_amd64)

### ISSUE THREAD

**Issue by KhimairaCrypto** [hashicorp/terraform-provider-aws#22582] opened 2022-01-13 20:56 UTC
I am not able to find out why executing `terraform plan/apply` will fail on the random bases. This behaviour happen regardless of the complexity of the project. I tried using local and S3 backends and same result. 

**I installed terraform and aws cli using `brew`**, I even run `brew doctor` to verify if something was broken and no issues. 

I originally raised a [Terraform CLI BUG](https://github.com/hashicorp/terraform/issues/30351), [But  seems like this bug is most likely related to the AWS provider](https://github.com/hashicorp/terraform/issues/30351#issuecomment-1012233089). 

### Terraform Version

```
Terraform v1.1.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.73.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### AWS  CLI Version

```                                                        
aws-cli/2.4.12 Python/3.9.10 Darwin/21.2.0 source/x86_64 prompt/off
```
### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">=3.70.0"
    }
  }
}

provider "aws" {
  profile = var.aws_iam_profile
  region  = var.deployment_region
}

resource "aws_s3_bucket" "prod_web" {
  bucket = "superman-batman-yoyo"
  acl    = "private"

  versioning {
    enabled = true
  }
  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = "AES256"
      }
    }
  }
}

resource "aws_s3_bucket_public_access_block" "prod_web" {
  bucket = aws_s3_bucket.prod_web.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}
```

### Debug Output
```
2022-01-12T15:24:29.056+1100 [ERROR] plugin.(*GRPCProvider).ValidateProviderConfig: error="rpc error: code = Canceled desc = context canceled"
2022-01-12T15:24:29.057+1100 [ERROR] vertex "provider[\"registry.terraform.io/hashicorp/aws\"]" error: Request cancelled
2022-01-13T11:03:10.772+1100 [ERROR] vertex "provider[\"registry.terraform.io/hashicorp/aws\"]" error: Unrecognized remote plugin message: 

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.
```

### Expected Behavior
Stop crashing!

### Actual Behavior
Need to run multiple times terraform plan/terraform apply to deploy the infrastructure :-/

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`

**Comment by KhimairaCrypto** [comment] 2022-01-16 00:45
Any idea guys?

**Comment by kimeirik-crayon** [comment] 2022-01-18 10:07
Can confirm that i am having the same problem on M1 Macbook Pro.
Need up to 10 tries or more to successfully run an apply.
More complex modules seems to have an higher error rate, and the problem normally occurs when it tries to fetch remote state.

**Comment by kimeirik-crayon** [comment] 2022-01-18 11:04
Looks like i was actually running the amd64 version of Terraform, not the arm64.
Installed arm64 version and ran a new terraform init, have not seen issues since.

```➜  ~ tfenv uninstall 1.1.3
Uninstall Terraform v1.1.3
Terraform v1.1.3 is successfully uninstalled
➜  ~ TFENV_ARCH=arm64 tfenv install 1.1.3
Installing Terraform v1.1.3
Installation of terraform v1.1.3 successful. To make this your default version, run 'tfenv use 1.1.3'
➜  ~ terraform --version
Terraform v1.1.3
on darwin_arm64```

Could be an issue with rosetta / go.

**Comment by KhimairaCrypto** [comment] 2022-01-18 11:08
@kimeirik-crayon I am using the amd version, the reason why is because I use brew to manage all my packages. Some of the packages that I use are not yet supported on arm. Not sure if the issue is related to rosetta

**Comment by kimeirik-crayon** [comment] 2022-01-18 11:12
@KhimairaCrypto i would recommend doing `brew install tfenv` instead of installing terraform directly, as you will encounter projects with different terraform versions pinned, and tfenv supports dynamically selecting the correct version based on the `.terraform-version` file in the module directory

**Comment by KhimairaCrypto** [comment] 2022-01-18 11:15
@kimeirik-crayon according to [Terraform official way](https://www.terraform.io/downloads) is 
```bash
brew tap hashicorp/tap
brew install hashicorp/tap/terraform
```

The question is it fully supported on Rosetta?

**Comment by pmoranga** [comment] 2022-01-19 16:22
I see this happening quite frequently as well. Are there M1x users reporting the same issue ?

**Comment by motilevy** [comment] 2022-01-19 19:26
I am on 
```
 Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,2
  Chip:	Apple M1 Max
``` 
and can confirm this happens very often with  `hashicorp/aws v3.70.0` and `hashicorp/aws v3.63.0`

**Comment by DrFaust92** [comment] 2022-01-19 22:42
I can confirm im also getting this on M1 Pro

**Comment by KhimairaCrypto** [comment] 2022-01-19 23:02
@DrFaust92 and @motilevy  are you guys used `brew` to install `terraform` on Rosetta ?

**Comment by kimeirik-crayon** [comment] 2022-01-20 08:53
Can confirm that i'm also getting these issues when using the darwin_**amd64** version on M1 Max

**Comment by KhimairaCrypto** [comment] 2022-01-21 07:00
Today I update terraform, aws plugin, and aws to the latest versions. No change :-/!
### Terraform Version


```
Terraform v1.1.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.73.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### AWS  CLI Version

```                                                        
aws-cli/2.4.12 Python/3.9.10 Darwin/21.2.0 source/x86_64 prompt/off
```

**Comment by blx** [comment] 2022-01-21 10:20
I had this issue on an M1 Air as well for the past week, and switching from the amd64 to arm64 version exactly as described above [here](https://github.com/hashicorp/terraform-provider-aws/issues/22582#issuecomment-1015302978) has resolved it for me.

```
❯ terraform -version
Terraform v1.1.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v3.72.0

**Comment by itsvikrams** [comment] 2022-01-25 10:50
@KhimairaCrypto  I'm not able to uninstall amd version and install arm can you please help me on how to do that?
I'm new to mac.
I ran the below commands.but still amd version is not getting removed.
➜  ~ terraform --version
Terraform v1.1.3
on darwin_amd64
➜  ~ tfenv uninstall 1.1.3
Uninstall Terraform v1.1.3

**Comment by KhimairaCrypto** [comment] 2022-01-25 11:14
If you installed using brew using. Rosetta terminal. Brew will install all the packages using amd64. As far as I know you can not have dual brew (amd64. Arm) :/(. Most Likely you need to uninstall brew and all the existent packages, then install brew using a non Rosetta terminal.

> @KhimairaCrypto  I'm not able to 
 amd version and install arm can you please help me on how to do that?
> 
> I'm new to mac.
> 
> I ran the below commands.but still amd version is not getting removed.
> 
> ➜  ~ terraform --version
> 
> Terraform v1.1.3
> 
> on darwin_amd64
> 
> ➜  ~ tfenv uninstall 1.1.3
> 
> Uninstall Terraform v1.1.3

**Comment by itsvikrams** [comment] 2022-01-25 12:09
@KhimairaCrypto  removed brew still terraform --version shows amd version. any other option to overcome this?

**Comment by KhimairaCrypto** [comment] 2022-01-25 12:28
Did you uninstalled terraform and all the packages that were installed with the brew amg64 version? Did you reinstalled brew using a non Rosetta terminal, as well as therraform?

> @  removed brew still terraform --version shows amd version. any other option to overcome this?
> 
>

**Comment by itsvikrams** [comment] 2022-01-25 12:46
How do I uninstall terraform?any pointers is appreciated thanks in advance

**Comment by KhimairaCrypto** [comment] 2022-01-25 13:18
All your questions are brew specific! This is nothing to do with terraform.

I recommend to go to brew website and understand how to install /uninstall packages .


brew uninstall package-name

> How do I uninstall terraform?any pointers is appreciated thanks in advance

**Comment by DrFaust92** [comment] 2022-01-25 13:29
Im closing this, as there is a resolution to the issue (can confirm it works for me as well) is to install a terraform binary that fits the architecture of you workstation. both tfenv and brew have relevant flags for this, feel free to look at their docs.

**Closed by DrFaust92** 2022-01-25 13:29 UTC
Labels: bug, provider

**Comment by itsvikrams** [comment] 2022-01-25 15:05
https://faun.pub/building-terraform-from-source-with-a-patch-7050bdc4576c This link helped me clearing the terraform and install ARM version

**Comment by KhimairaCrypto** [comment] 2022-01-26 10:13
@DrFaust92 that is called workaround! Will be nice if you guys include this as a know issue for future reference!
