### ISSUE TITLE
aws_sns_platform_application Token authentication method for GCM

### ISSUE THREAD

**Issue by keshavsharma-github** [hashicorp/terraform-provider-aws#35721] opened 2024-02-08 14:22 UTC
### Description

We are using AWS SNS with Firebase for Push Notification.
I need help on how we can configure the
aws_sns_platform_application Authorization Type Token including the Service JSON as per Firebase recommendation.

AWS started supporting the recommended Google Firebase Authorization type on Jan 18, 2024.
https://aws.amazon.com/about-aws/whats-new/2024/01/amazon-sns-fcm-http-v1-api-mobile-notifications/

<img width="587" alt="SNS_FCM_Authentication_Type_Token" src="https://github.com/hashicorp/terraform-provider-aws/assets/56992839/f679f322-fd74-49d2-a04a-7e0ae28a0192">

### Would you like to implement a fix?

None

**Comment by eaterm** [comment] 2024-04-15 12:48
We were investigating this as well as we also need to switch to token based configuration.

Just passing the token file (json file) to platform_credential instead of the api key seems to do the trick. 
As it will apply like normal and the console shows it is switched to token authentication.

**Comment by jaska27** [comment] 2024-04-16 07:50
> We were investigating this as well as we also need to switch to token based configuration.
> 
> Just passing the token file (json file) to platform_credential instead of the api key seems to do the trick. As it will apply like normal and the console shows it is switched to token authentication.

Yes, the same works for us as well!

**Comment by natebrunettixcel** [comment] 2024-04-24 18:01
How id you pass the (json file)? Using the `file()` in Terraform?

**Comment by natebrunettixcel** [comment] 2024-04-24 18:08
> We were investigating this as well as we also need to switch to token based configuration.
> 
> Just passing the token file (json file) to platform_credential instead of the api key seems to do the trick. As it will apply like normal and the console shows it is switched to token authentication.

How did you pass the (json file)? Using the file() in Terraform?

**Comment by jaska27** [comment] 2024-04-25 06:21
We use AWS Systems Manager Parameter Store to store the json content. Then in TF file:
`data "aws_ssm_parameter" "android_service_file_key" {
  name = "sns_android_service_file_key"
}

resource "aws_sns_platform_application" "sns_application_android" {
  name                         = "app-android"
  platform                     = "GCM"
  platform_credential          = data.aws_ssm_parameter.android_service_file_key.value
}`

**Comment by eaterm** [comment] 2024-04-25 07:01
> How did you pass the (json file)? Using the file() in Terraform?

For testing we made a simple terraform project. This was something like. But using file command also should work.
test.tf
```
variable "test" {
  discription = "test token"
}
resource "aws_sns_platform_application" "test" {
  name                 = "test"
  platform             = "GCM"
  platform_credential  = var.test
}
```
terraform.tfvars
```
test = <<EOF
<token file>
EOF
```

**Comment by natebrunettixcel** [comment] 2024-04-25 16:04
> We use AWS Systems Manager Parameter Store to store the json content. Then in TF file:
> 
> ```
> data "aws_ssm_parameter" "android_service_file_key" {
>   name = "sns_android_service_file_key"
> }
> resource "aws_sns_platform_application" "sns_application_android" {
>   name                         = "app-android"
>   platform                     = "GCM"
>   platform_credential          = data.aws_ssm_parameter.android_service_file_key.value
> }
> ```

Thanks for this! I'm going to try the file option but might need to switch to the Parameter Store.

**Comment by natebrunettixcel** [comment] 2024-04-25 19:30
My attempt didn't work.

sns_platform_application.tf
```
resource "aws_sns_platform_application" "ios_application" {
  name     = "ios-platform-application"
  platform = "GCM"
  platform_credential = file("${path.module}/service.json")
}
```

`service.json` is in the root. The error that Terraform returned says this:
`Error updating SNS platform application: InvalidParameter: Invalid parameter: Attributes Reason: Invalid value for attribute: SuccessFeedbackSampleRate: value provided is not an integer between 0-100`

**Comment by natebrunettixcel** [comment] 2024-04-25 20:06
> > How did you pass the (json file)? Using the file() in Terraform?
> 
> For testing we made a simple terraform project. This was something like. But using file command also should work. test.tf
> 
> ```
> variable "test" {
>   discription = "test token"
> }
> resource "aws_sns_platform_application" "test" {
>   name                 = "test"
>   platform             = "GCM"
>   platform_credential  = var.test
> }
> ```
> 
> terraform.tfvars
> 
> ```
> test = <<EOF
> <token file>
> EOF
> ```

With this test you were using the `.json` token file and not the `key` right?

**Comment by natebrunettixcel** [comment] 2024-04-26 15:26
> Yes, you have to use the json file. But the error is about missing `success_feedback_sample_rate` in the `aws_sns_platform_application `. It's an optional parameter so I'm not sure why it complains about it but I'd add it and try again.

Yes, I realized that now. Moving too fast. I did try adding the `succes_feedback_smaple_rate` argument even though its optional but it didn't update the Authentication method to `token`. I'm wondering if it's because the resource already existed. Going to try one more time creating a new resource.

**Comment by jaska27** [comment] 2024-04-29 08:40
It shouldn't really matter. I was also updating existing resources and no issue.

**Comment by aristosvo** [comment] 2024-05-28 18:16
@keshavsharma-github Is this issue solved based on the provided answers? 

Is there anything you'd expect on the provider side to be changed? I'd be happy to help you out a bit more if needed, but it seems the issue is resolved.

**Comment by keshavsharma-github** [comment] 2024-05-30 08:43
> We were investigating this as well as we also need to switch to token based configuration.
> 
> Just passing the token file (json file) to platform_credential instead of the api key seems to do the trick. As it will apply like normal and the console shows it is switched to token authentication.

Thanks it worked.

**Comment by breathingdust** [comment] 2024-10-22 20:13
Closing as this appears to be resolved based on the above comments.

**Closed by breathingdust** 2024-10-22 20:13 UTC
Labels: enhancement, service/sns
