### ISSUE TITLE
[Bug]: Python3.13 Support for AWS Lambda and AWS Lambda Layer

### ISSUE THREAD

**Issue by donnyDonowitz** [hashicorp/terraform-provider-aws#40107] opened 2024-11-13 00:02 UTC
### Terraform Core Version

1.9.8

### AWS Provider Version

5.75.1

### Affected Resource(s)

aws_lambda_function
aws_lambda_layer_version

### Expected Behavior

Provider allows to create python3.13 resources with AWS Lambda

### Actual Behavior

The resource creation fails with the following error:

```sh
Error: expected compatible_runtimes to be one of ["nodejs" "nodejs4.3" "nodejs6.10" "nodejs8.10" "nodejs10.x" "nodejs12.x" "nodejs14.x" "nodejs16.x" "java8" "java8.al2" "java11" "python2.7" "python3.6" "python3.7" "python3.8" "python3.9" "dotnetcore1.0" "dotnetcore2.0" "dotnetcore2.1" "dotnetcore3.1" "dotnet6" "dotnet8" "nodejs4.3-edge" "go1.x" "ruby2.5" "ruby2.7" "provided" "provided.al2" "nodejs18.x" "python3.10" "java17" "ruby3.2" "ruby3.3" "python3.11" "nodejs20.x" "provided.al2023" "python3.12" "java21"], got python3.13
```

### Terraform Configuration Files

```hcl
data "aws_iam_policy_document" "assume_role" {
  statement {
    effect = "Allow"

    principals {
      type        = "Service"
      identifiers = ["lambda.amazonaws.com"]
    }

    actions = ["sts:AssumeRole"]
  }
}

resource "aws_iam_role" "iam_for_lambda" {
  name               = "iam_for_lambda"
  assume_role_policy = data.aws_iam_policy_document.assume_role.json
}

data "archive_file" "lambda" {
  type        = "zip"
  source_file = "lambda.js"
  output_path = "lambda_function_payload.zip"
}

resource "aws_lambda_function" "test_lambda" {
  # If the file is not in the current working directory you will need to include a
  # path.module in the filename.
  filename      = "lambda_function_payload.zip"
  function_name = "lambda_function_name"
  role          = aws_iam_role.iam_for_lambda.arn
  handler       = "index.test"

  source_code_hash = data.archive_file.lambda.output_base64sha256

  runtime = "python3.13"

  environment {
    variables = {
      foo = "bar"
    }
  }
}
```

### Steps to Reproduce

1. define a aws_lambda_function or aws_lambda_layer_version in HCL
2. specify python3.13 as runtime
3. hit terraform apply

### Would you like to implement a fix?

None

**Comment by donnyDonowitz** [comment] 2024-11-13 00:14
https://github.com/aws/aws-sdk-go-v2/blob/service/lambda/v1.66.0/service/lambda/types/enums.go#L416

Go SDK is already updated

**Comment by aristosvo** [comment] 2024-11-13 13:51
This will be available in the next release due to the upgrade in #40097

**Comment by justinretzolk** [comment] 2024-11-14 16:54
Hey @donnyDonowitz 👋 Thank you for taking the time to raise this! As mentioned above, this will be available in the next release, which is currently processing, and should be available in the Registry in the next hour or so. With that in mind, I'm going to close this issue. If you encounter any other unexpected behavior, please do let us know!

**Closed by justinretzolk** 2024-11-14 16:54 UTC
Labels: bug, service/lambda, service/iam, needs-triage

**Comment by pawanlocalun** [comment] 2024-11-18 13:40
Is It new Terraform release ? if yes then expected date  ?

**Comment by pawanlocalun** [comment] 2024-11-18 13:41
> Is It new Terraform release ? if yes then expected date ?

Is It new Terraform release ? if yes then expected date ?

**Comment by pawanlocalun** [comment] 2024-11-18 13:42
> This will be available in the next release due to the upgrade in #40097

Is It new Terraform release ? if yes then expected date ?

**Comment by donnyDonowitz** [comment] 2024-11-18 13:50
@pawanlocalun  it is already working in the latest release of the aws provider https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.76.0.

**Comment by aristosvo** [comment] 2024-11-18 13:50
> > This will be available in the next release due to the upgrade in #40097
> 
> 
> 
> Is It new Terraform release ? if yes then expected date ?

> which is currently processing, and should be available in the Registry in the next hour or so.

Terraform Provider for AWS, and this is already in the latest release.
