### ISSUE TITLE
Launch template version changes during each plan

### ISSUE THREAD

**Issue by rangarb885** [hashicorp/terraform-provider-aws#21024] opened 2021-09-24 04:26 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.15.3
hashicorp/aws 3.58.0

### Affected Resource(s)

* aws_launch_template

### Terraform Configuration Files

```hcl
resource "aws_launch_template" "default" {
  name_prefix            = "${var.eks.cluster_name}-"
  description            = "Default Launch-Template"
  update_default_version = true
  block_device_mappings {
    device_name = "/dev/xvda"
    ebs {
      volume_size           = 800
      volume_type           = "gp2"
      delete_on_termination = true
      encrypted             = true
      kms_key_id = aws_kms_key.worker_ebs_kms.arn
    }
  }
  monitoring {
    enabled = true
  }
  network_interfaces {
    associate_public_ip_address = false
    delete_on_termination       = true
    security_groups             = [module.eks.cluster_primary_security_group_id]
  }
  instance_type = var.eks.instance_type
  image_id = data.aws_ami.ami.id
  user_data = base64encode(data.template_file.launch_template_userdata.rendered)
  tag_specifications {
    resource_type = "instance"

    tags = {
      "kubernetes.io/cluster/${var.eks.cluster_name}"     = "owned"
      "k8s.io/cluster-autoscaler/enabled"                 = "true"
      "k8s.io/cluster-autoscaler/${var.eks.cluster_name}" = "owned"
      "Name"                                              = "${var.eks.cluster_name}-worker"
    }
  }
  tags = {
    cluster_name = "${var.eks.cluster_name}"
  }
  lifecycle {
    create_before_destroy = true
    ignore_changes = [
      tags,
    ]
  }
}
```

### Debug Output
```
 ~ resource "aws_launch_template" "default" {
        arn                     = "arn:aws:ec2:us-west-2:<REDACTED>:launch-template/lt-02f6ff37098aa1ede"
      ~ default_version         = 7 -> (known after apply)
        description             = "Default Launch-Template"
        disable_api_termination = false
        id                      = "lt-02f6ff37098aa1ede"
        image_id                = "ami-0cc6a79f1a5e29c75"
        instance_type           = "m5.2xlarge"
      ~ latest_version          = 7 -> (known after apply)
        name                    = "perf-test-20210902183818128500000001"
        name_prefix             = "perf-test-"
        security_group_names    = []
        tags                    = {
            "cluster_name"     = "perf-test"
        }
        tags_all                = {
            "cluster_name"     = "perf-test"
        }
        update_default_version  = true
        user_data               = <REDACTED>
        vpc_security_group_ids  = []

        block_device_mappings {
            device_name = "/dev/xvda"

            ebs {
                delete_on_termination = "true"
                encrypted             = "true"
                iops                  = 0
                kms_key_id            = "arn:aws:kms:us-west-2:<REDACTED>:key/db9f0746-d21a-4d87-8964-98b5bb69bc14"
                throughput            = 0
                volume_size           = 800
                volume_type           = "gp2"
            }
        }

        monitoring {
            enabled = true
        }

        network_interfaces {
            associate_public_ip_address = "false"
            delete_on_termination       = "true"
            device_index                = 0
            ipv4_address_count          = 0
            ipv4_addresses              = []
            ipv6_address_count          = 0
            ipv6_addresses              = []
            security_groups             = [
                "sg-022ad8560466d1600",
            ]
        }

        tag_specifications {
            resource_type = "instance"
            tags          = {
                "Name"                                     = "perf-test-worker"
                "k8s.io/cluster-autoscaler/enabled"        = "true"
                "k8s.io/cluster-autoscaler/fiaa-perf-test" = "owned"
                "kubernetes.io/cluster/fiaa-perf-test"     = "owned"
            }
        }
    }
```
### Expected Behavior

As i verify that the LT latest and default version are 7 on AWS (at the moment when i ran this), Ideally the TF should not see any difference and leave the Launch template unchanged. 

### Actual Behavior

TF tries to create new version of LT which has no change (not even tags!)
This causes larger impact on EKS management as each time terraform tries to recycle the nodes (100+) created by the launch template.

### Steps to Reproduce
On an existing Launch template, try to run :
1. terraform init
2. terraform plan

### Important Factoids

This was identified when LT is created as part of [terraform-aws-modules](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/examples/launch_templates_with_managed_node_groups/launchtemplate.tf) based setup.

### References

I have opened the case with terraform-aws-modules module provider as well. [1597](https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1597)

**Comment by justinretzolk** [comment] 2021-09-24 17:43
Thanks for taking the time to submit this issue. It looks like this is a duplicate of #19411. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #19411.

**Closed by justinretzolk** 2021-09-24 17:43 UTC
Labels: service/ec2, needs-triage
