### ISSUE TITLE
Terraform aws_appstream_fleet_stack_association resource bug

### ISSUE THREAD

**Issue by pabsmartin** [hashicorp/terraform-provider-aws#23072] opened 2022-02-09 16:06 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)
* aws_appstream_fleet_stack_association

### Terraform Configuration Files

Create an aws_appstream_fleet and an aws_appstream_stack. Then reference them in an aws_appstream_fleet_stack_association resource. The code below was extracted from the [terraform registry docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appstream_fleet_stack_association).

```hcl

resource "aws_appstream_fleet_stack_association" "fleet_stack_association" {
  fleet_name = aws_appstream_fleet.fleet.name  <-- value: XXXX
  stack_name = aws_appstream_stack.stack.name <-- value: YYYY
}

```
### Expected Behavior

The fleet should have been associated to the stack.

### Actual Behavior

**Error: error reading AppStream Fleet Stack Association (YYYY/XXXX): No stack "XXXX" associated with fleet "YYYY".**

NOTE: It seems that the resource is doing a cross-reference between the attributes' values, so I changed them in another execution. The result was having a **_ResourceNotFoundException_** after 15 minutes of processing telling me that a fleet named "YYYY" didn't exist. (that is obvious, because the fleet's name is "XXXX")

### Steps to Reproduce

1. `terraform apply` ( I actually executed _terragrunt run-all apply_ )

**Comment by zulizzi-cfg** [comment] 2022-02-10 05:29
The bug seems to be caused by this line:
https://github.com/hashicorp/terraform-provider-aws/blob/60bd245a93893c6eefae9a84f72f3a22ed7c2305/internal/service/appstream/fleet_stack_association.go#L69

Where the arguments to `EncodeStackFleetID` are not in the right order.

**Comment by justinretzolk** [comment] 2022-02-16 21:33
Hey @pabsmartin 👋 Thanks for taking the time to submit this issue. It looks like this is a duplicate of #22625. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #22625.

**Closed by justinretzolk** 2022-02-16 21:33 UTC
Labels: bug, service/appstream
