### ISSUE TITLE
tags in root_block_device are applied, but not written into state file

### ISSUE THREAD

**Issue by decayofmind** [hashicorp/terraform-provider-aws#17187] opened 2021-01-20 14:30 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/aws v3.24.1

### Affected Resource(s)

* aws_instance

### Expected Behavior

After adding `tags` to `root_block_device` tags should be applied to the root EBS volume and written to a state file.

### Actual Behavior

Tags are applied, but not written to the state file, which leads those changes to be aplied over and over.

### Steps to Reproduce

1.  Add `tags` to `root_block_device` of an `aws_instance` resource.
2. Run `terraform apply` and see tags applied
3. Run `terraform state pull` and observe:

```
            "root_block_device": [
              {
                "delete_on_termination": true,
                "device_name": "/dev/sda1",
                "encrypted": true,
                "iops": 100,
                "kms_key_id": "arn:aws:kms:hidden",
                "tags": {},
                "throughput": 0,
                "volume_id": "vol-hidden",
                "volume_size": 20,
                "volume_type": "gp2"
              }
            ],
```

4. Run `terraform apply` and see same changes to tags to be applied again.

**Comment by shuheiktgw** [comment] 2021-01-25 00:59
Cannot reproduce this behavior from the current acc tests... Terraform: v0.14.5, terraform-aws-provider: main, region: ap-northeast-1. 

```
make testacc TESTARGS='-run=TestAccAWSInstance_blockDeviceTags_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSInstance_blockDeviceTags_ -timeout 120m
=== RUN   TestAccAWSInstance_blockDeviceTags_volumeTags
=== PAUSE TestAccAWSInstance_blockDeviceTags_volumeTags
=== RUN   TestAccAWSInstance_blockDeviceTags_withAttachedVolume
=== PAUSE TestAccAWSInstance_blockDeviceTags_withAttachedVolume
=== RUN   TestAccAWSInstance_blockDeviceTags_ebsAndRoot
=== PAUSE TestAccAWSInstance_blockDeviceTags_ebsAndRoot
=== CONT  TestAccAWSInstance_blockDeviceTags_volumeTags
=== CONT  TestAccAWSInstance_blockDeviceTags_ebsAndRoot
=== CONT  TestAccAWSInstance_blockDeviceTags_withAttachedVolume
--- PASS: TestAccAWSInstance_blockDeviceTags_ebsAndRoot (215.22s)
--- PASS: TestAccAWSInstance_blockDeviceTags_withAttachedVolume (235.89s)
--- PASS: TestAccAWSInstance_blockDeviceTags_volumeTags (277.58s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	279.587s
```

**Comment by pmason56** [comment] 2021-08-02 12:19
+1 on this issue. However, when creating a new ec2 instance to try and replicate the issue it does not seem to appear.

**Comment by pmason56** [comment] 2021-08-02 12:44
I was experiencing a similar error the route cause was due to volume_tags being ignored by a lifecycle rule. This meant that the root_block_device device tags were not being added into the remote state.

The solution to this was to remove the lifecycle rule on the volume_tags and allow terraform to delete, them adding the root_block_device tags in.

**Comment by justinretzolk** [comment] 2023-11-02 21:18
Given that this hasn't been able to be reproduced, and given the major updates to tags in version 5 of the provider, we're going to close this issue. If you experience this again in newer versions of the provider, please open a new issue so that we can more effectively triage it. Feel free to link to this issue for additional context if you'd like.

**Closed by justinretzolk** 2023-11-02 21:18 UTC
Labels: bug, service/ec2
