### ISSUE TITLE
[Bug]: It is not clear which values could be used for paramter_group_name of aws_elasticache_subnet_group

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/terraform-provider-aws#39933] opened 2024-10-29 19:13 UTC
### Terraform Core Version

N/A

### AWS Provider Version

N/A

### Affected Resource(s)

* aws_elasticache_subnet_group

### Expected Behavior

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_replication_group#parameter_group_name

It should be listed which values are allowed and what does this means `"default.redis3.2.cluster.on"`

### Actual Behavior

It is not clear how to write correct names

### Terraform Configuration Files

N/a

### Steps to Reproduce

N/A

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-10-29 19:57
Hey @EugenKon 👋 Thanks for taking the time to raise this! In this particular case, I don't think it would be possible to list all of the available options, as there seems to be [quite a few](https://docs.aws.amazon.com/AmazonElastiCache/latest/dg/ParameterGroups.ListingGroups.html), and what's acceptable (as far as the AWS API is concerned; the provider itself [isn't doing any validation](https://github.com/hashicorp/terraform-provider-aws/blob/f337f4fa2c620f138c4713f3c6db14334693417c/internal/service/elasticache/replication_group.go#L254-L261) on that argument) depends on whether clustering is enabled and the engine and engine version used.

As far as the specific parameter group that you mentioned, while I'd generally point back to the AWS documentation for that information, the resource documentation mentions that one in particular in one of the callout boxes:

> To enable cluster mode, use a parameter group that has cluster mode enabled. The default parameter groups provided by AWS end with ".cluster.on", for example `default.redis6.x.cluster.on`.

Since this isn't something we can expand on given that myriad of parameter groups available, the AWS documentation should be used as a supplemental guide for what values are acceptable. WIth that in mind, I'm going to close this issue. As always, if you experience further unexpected behavior, please do let us know!

**Closed by justinretzolk** 2024-10-29 19:57 UTC
Labels: bug, service/elasticache, needs-triage

**Comment by EugenKon** [comment] 2024-10-30 13:21
@justinretzolk If you add into documentation the link you provided it would be awesome. https://docs.aws.amazon.com/AmazonElastiCache/latest/dg/ParameterGroups.ListingGroups.html

Thanks.
