### ISSUE TITLE
[Enhancement]: Add support for Redshift Multi-AZ deployment

### ISSUE THREAD

**Issue by radim-silhanek-adastra** [hashicorp/terraform-provider-aws#34926] opened 2023-12-14 16:00 UTC
### Description

Redshift Multi-AZ is generally available since Nov 1st, 2023 - https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-redshift-multi-az-ra3-clusters/. The ability to configure Multi-AZ is missing in aws_redshift_cluster resource. This should be added to the functionality and arguments of this resource. 

### Affected Resource(s) and/or Data Source(s)

aws_redshift_cluster

### Potential Terraform Configuration

```terraform
resource "aws_redshift_cluster" "this" {
  cluster_identifier = "redshift_cluster"
.
.
.
  multi_az = true
.
.
.
}
```

### References

- https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-redshift-multi-az-ra3-clusters/
- https://aws.amazon.com/blogs/big-data/enable-multi-az-deployments-for-your-amazon-redshift-data-warehouse/
- https://docs.aws.amazon.com/redshift/latest/APIReference/API_CreateCluster.html
- https://docs.aws.amazon.com/redshift/latest/APIReference/API_ModifyCluster.html
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-cluster.html#cfn-redshift-cluster-multiaz

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-01-12 17:26
Related #32180

Looks like this is technically a duplicate of ☝️ , but given that there's a new development (this feature is now GA'd), leaving this one open to maintain the great references.

**Closed** 2024-01-29 22:37 UTC
Labels: enhancement, service/redshift
