### ISSUE TITLE
aws_route_table route block generates change on every plan

### ISSUE THREAD

**Issue by szczad** [hashicorp/terraform-provider-aws#2390] opened 2017-11-21 11:48 UTC
### Terraform Version
Terraform v0.11.0

### Affected Resource(s)
provider.aws 1.3.0 (unreleased)

### Terraform Configuration Files
Version 1)
```hcl
resource "aws_route_table" "route_1" {
  vpc_id = "${vpc_id}"
  route {
    cidr_block           = "0.0.0.0/0"
    network_interface_id = "${eni_id}"
    instance_id          = "${instance_id}"
  }
}
```

Version 2)
```hcl
resource "aws_route_table" "route_2" {
  vpc_id = "${vpc_id}"
  route {
    cidr_block           = "0.0.0.0/0"
    network_interface_id = "${eni_id}"
  }
}
```

### Output
Version 1)
```
aws_route_table.route_1: Modifying... (ID: rtb-abcd1234)
  route.#:                                    "0" => "1"
  route.3439688319.cidr_block:                "" => "0.0.0.0/0"
  route.3439688319.egress_only_gateway_id:    "" => ""
  route.3439688319.gateway_id:                "" => ""
  route.3439688319.instance_id:               "" => "i-01234567890"
  route.3439688319.ipv6_cidr_block:           "" => ""
  route.3439688319.nat_gateway_id:            "" => ""
  route.3439688319.network_interface_id:      "" => "eni-abcd1234"
  route.3439688319.vpc_peering_connection_id: "" => ""
  tags.%:                                     "0" => "2"
  tags.Name:                                  "" => "Tag 1"
  tags.Realm:                                 "" => "Realm 1"
Error: Error applying plan:
1 error(s) occurred:
* aws_route_table.route_1: 1 error(s) occurred:
* aws_route_table.route_1: InvalidParameterCombination: The request must contain exactly one of gatewayId, natGatewayId, networkInterfaceId, vpcPeeringConnectionId, egressOnlyInternetGatewayId or i
nstanceId
        status code: 400, request id: 00000000-0000-0000-0000-000000000000
Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```
Version 2)

```
  ~ aws_route_table.route_1
      route.1071501780.cidr_block:                "" => "0.0.0.0/0"
      route.1071501780.egress_only_gateway_id:    "" => ""
      route.1071501780.gateway_id:                "" => ""
      route.1071501780.instance_id:               "" => ""
      route.1071501780.ipv6_cidr_block:           "" => ""
      route.1071501780.nat_gateway_id:            "" => ""
      route.1071501780.network_interface_id:      "" => "eni-abcd1234"
      route.1071501780.vpc_peering_connection_id: "" => ""
      route.3439688319.cidr_block:                "0.0.0.0/0" => ""
      route.3439688319.egress_only_gateway_id:    "" => ""
      route.3439688319.gateway_id:                "" => ""
      route.3439688319.instance_id:               "i-01234567890" => ""
      route.3439688319.ipv6_cidr_block:           "" => ""
      route.3439688319.nat_gateway_id:            "" => ""
      route.3439688319.network_interface_id:      "eni-abcd1234" => ""
      route.3439688319.vpc_peering_connection_id: "" => ""

Plan: 0 to add, 1 to change, 0 to destroy.
```
### Actual Behavior
1) Terraform parser allows mutually exclusive options to be provided in "route" in "aws_route_table" resource (i.e: network_interface_id and instance_id). 
2) Terraform AWS provider generates change for configuration "version 2" every consecutive run. As a workaround one must tweak configuration adding "instance_id" so it looks like "version 1"  to stop planner from creating "changes".

### Expected Behavior
1) Terraform parser detects that two or more mutually exclusive options are provided in same "route" configuration block
2) Actual `terraform plan` does not generate change if "network_interface_id" is provided alone

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
Version 1)
1. Copy configuration "version 1"
2. `terraform plan`
3. `terraform apply`

Version 2)
1. Copy configuration "version 2"
2. `terraform plan`
3. `terraform apply`
4. `terraform plan`

**Comment by nitinsatish** [comment] 2018-01-09 09:20
I also facing the same issue on providing `network_interface_id` to `aws_route_table`

**Comment by kendrickm** [comment] 2018-01-25 17:51
I'm having the same issue
`Terraform v0.11.2
+ provider.aws v0.1.4`

Specifically adding/removing `nat_gateway_id`

**Comment by abridgett** [comment] 2018-03-29 11:13
TF: v0.11.5, provider.aws: v1.12.0
I've managed to find something that half-works for me.  I'm using plain aws_route_tables.

Add _just_ network_interface_id (do not put instance_id in yet - if you do then TF complains that these are incompatible and you have a half-created/updated routing table)

Now this will never settle down - it'll always detect "instance_id" is currently present.

So _now_ add in instance_id to the aws_route_table and TF will accept that it's in sync and stop trying to make any "changes".

**Comment by alkersan** [comment] 2018-08-17 14:40
Issue occurs in Terraform `v0.11.8`, provider.aws `v1.32.0`.

**Comment by GaryGSC** [comment] 2020-08-13 22:01
Bump. 🙂

**Comment by ewbankkit** [comment] 2021-01-07 13:53
I'm going to close this issue as a duplicate of #1426 (an even earlier issue than this one 😄) so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Closed** 2021-01-07 13:53 UTC
Labels: bug, service/ec2
