### ISSUE TITLE
Launch template always shows `latest_version` changing when using lifecycle ignore_changes

### ISSUE THREAD

**Issue by jbehling** [hashicorp/terraform-provider-aws#19235] opened 2021-05-04 18:53 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
terraform 0.15.1 (also re-created with 0.14.3 and 0.14.11)
aws 3.38.0

### Affected Resource(s)

* aws_launch_template

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_launch_template" "this" {
 …
  lifecycle {
    ignore_changes = [
      image_id
    ]
  }
}
```

### Expected Behavior

It should show no changes

### Actual Behavior

```
  ~ resource "aws_launch_template" "this" {
       ...
      ~ latest_version          = 22 -> (known after apply)
      ...
 
        # (11 unchanged attributes hidden)



        # (4 unchanged blocks hidden)
    }
```

Even if I apply, it shows the same change on the next plan.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Works as expected in provider versions <= 3.27. The only thing suspect in this configuration is that `image_id` is ignored.  Rolling back to the previous provider version fixes the issue.

**Comment by Yunsang-Jeong** [comment] 2021-06-14 06:10
Same Symptom on terraform 1.0.0 and aws 3.45.0.
 
```hcl
resource "aws_launch_template" "this" {
 …
  lifecycle {
    ignore_changes = [
      security_group_names
    ]
  }
}
```

```
Plan: 0 to add, 2 to change, 0 to destroy.

Changes to Outputs:
  ~ launch_template = {
      ~ was = {
          ~ default_version = 1 -> (known after apply)
          ~ latest_version  = 1 -> (known after apply)
          ~ this            = {
              ~ default_version                      = 1 -> (known after apply)
              ~ latest_version                       = 1 -> (known after apply)
                # (35 unchanged elements hidden)
            }
            # (3 unchanged elements hidden)
        }
      ~ web = {
          ~ default_version = 1 -> (known after apply)
          ~ latest_version  = 1 -> (known after apply)
          ~ this            = {
              ~ default_version                      = 1 -> (known after apply)
              ~ latest_version                       = 1 -> (known after apply)
                # (35 unchanged elements hidden)
            }
            # (3 unchanged elements hidden)
        }
    }
```

**Comment by obourdon** [comment] 2021-07-02 14:23
On my side migrating from 0.12 to 0.13 was successful without any add/change/destroy
but updating to 0.14 led to ASG and launch template marked as to be changed (applying and relaunching also re-mark them as to be updated as stated above by @jbehling). ASG due to `version` field

Using
```
  lifecycle {
    ignore_changes = [
      latest_version,
    ]
  }
```
within launch template resource definition mark both ASG and launch template to be OK not requiring any update

Terraform 0.14 and above, AWS provider 3.47.0

**Comment by piotrb** [comment] 2021-07-28 21:21
Hi folks, this is a bit of a stale issue but I'm still seeing this with the latest provider .. has there been any work done towards fixing this?

**Comment by obourdon** [comment] 2021-08-13 11:54
From my side, it appeared that under some cases, my workaround above using lifecycle -> ignore-changes -> latest_version was preventing some other template updates to be taken into account when needed. This means that the issue should be fixed more thoroughly.

**Comment by justinretzolk** [comment] 2021-09-24 17:54
Hi all 👋 Thanks for taking the time to submit and discuss this issue. It looks like this is a duplicate of #19411. We like to try to keep discussions consolidated, and while this issue was filed fiirst, it looks like there's a bit more discussion over on the other issue. With that in mind, we’re going to close this new issue in favor of #19411.

**Closed by justinretzolk** 2021-09-24 17:54 UTC
Labels: bug, service/ec2
