### ISSUE TITLE
[Bug]: Terraform CloudFormation Multi Region Stacksets

### ISSUE THREAD

**Issue by rads18** [hashicorp/terraform-provider-aws#33944] opened 2023-10-16 14:55 UTC
### Terraform Core Version

Terraform v1.6.0

### AWS Provider Version

v5.20.1

### Affected Resource(s)

Hello team,

We have been using AWS Stacksets to deploy directly from AWS UI(Cloudformation) and trying to use Terraform to deploy the same Stacksets templates.

Based on documentation it appears we should be able to supply multiple regions but i do not see a key to supply multiple regions for parallel execution. However, per document (link below) for Resource: aws_cloudformation_stack_set_instance it has a operational_preference parameter that allows PARALLEL execution.

### Expected Behavior

Stacksets launched from a region should be able deploy stacks to regions within an account. 
Thats the purpose of using stacksets in AWS.

### Actual Behavior

The resource **aws_cloudformation_stack_set_instance** does not allow multiple regions with only a single "region" key however,  there is a **operation_preferences**  with region_concurrency_type = "PARALLEL".

```
resource "aws_cloudformation_stack_set" "amitest" {
  name = "ami-test-stackset"

  parameters = {
    ImageName = "xxxxxx"
  }

  template_body = file("../cftemplates/TestAmiLambda.yaml")
}

resource "aws_cloudformation_stack_set_instance" "amitest" {
  account_id = "xxxxxxxx"
  region     = "us-east-1"
  timeouts {
    create = "60m"
  }
  operation_preferences {
    region_concurrency_type = "PARALLEL"
  }
  stack_set_name = aws_cloudformation_stack_set.amitest.name
}
```

### Terraform Configuration Files

CreateCloudstackSet.tf

```
resource "aws_cloudformation_stack_set" "amitest" {
  name = "ami-test-stackset"

  parameters = {
    ImageName = "xxxxxx"
  }

  template_body = file("../cftemplates/TestAmiLambda.yaml")
}
```

instance.tf
```
resource "aws_cloudformation_stack_set_instance" "amitest" {
  account_id = "xxxxxxxx"
  region     = "us-east-1"
  timeouts {
    create = "60m"
  }
  operation_preferences {
    region_concurrency_type = "PARALLEL"
  }
  stack_set_name = aws_cloudformation_stack_set.amitest.name
}
```

main.tf
```
provider "random" {}

## Provider us-east-1
provider "aws" {
  region = "us-east-1"
}
```

### Steps to Reproduce

It does not take multiple regions. It deploys fine to single region provided in the code snippet above, but that is not Stackset in AWS. It has to be able to span multiple regions. There is no provision to provide multiple regions, yet in the instance configuration and documentation we can do PARALLEL, what is the meaning and significance for that? 

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudformation_stack_set#region_concurrency_type

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudformation_stack_set_instance

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2023-10-16 20:58
Duplicate of #24752

**Closed by justinretzolk** 2023-10-16 20:58 UTC
Labels: bug, service/cloudformation, needs-triage
