### ISSUE TITLE
[Enhancement]: 

### ISSUE THREAD

**Issue by consultsalman** [hashicorp/terraform-provider-aws#34014] opened 2023-10-19 18:21 UTC
### Description

Hi Team,
Our team uses terraform only to manage AWS resources, recently we had a requirement to use on demand capacity reservation in our AWS EMR cluster.

we were advised to use ondemand_specification with "CapacityReservationOptions".
https://docs.aws.amazon.com/emr/latest/ManagementGuide/on-demand-capacity-reservations.html#on-demand-capacity-reservations-first

while exploring the same in terraform, we figured out it is not supported in terraform yet.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/emr_instance_fleet#on_demand_specification--configuration-block

Could you please consider adding this support in terraform module as well. 

Please let me know if you have more questions.

### Affected Resource(s) and/or Data Source(s)

AWS EMR

### Potential Terraform Configuration

```terraform
we would like to use this configuration (equivalent tf code).

"LaunchSpecifications": 
    {"OnDemandSpecification": {
        "AllocationStrategy": "lowest-price",
        "CapacityReservationOptions":
         {
            "UsageStrategy": "use-capacity-reservations-first"
         }
       }
    }
```

### Would you like to implement a fix?

None

**Comment by AdamTylerLynch** [comment] 2023-11-08 13:24
Duplicate of #30346

**Closed by AdamTylerLynch** 2023-11-08 13:24 UTC
Labels: enhancement, service/emr
