### ISSUE TITLE
Terraform looking in wrong path in non elevated mode Windows

### ISSUE THREAD

**Issue by csetzkorn** [hashicorp/terraform-provider-aws#24259] opened 2022-04-15 12:08 UTC
I am using this simple main.tf

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.10.0"
    }
  }
  required_version = ">= 0.14.9"
}

provider "aws" {
    region = "eu-west-2"
    #shared_credentials_files = ["C:\\Users\\christiansetzkorn\\.aws\\credentials"]
    profile = "default"
}

```
My terraform init runs fine but when I run:

terraform plan 
I get:

```
PS C:\bla\terraform> terraform apply

Error: error configuring Terraform AWS Provider: loading configuration: read C:\data\: The handle is invalid.

with provider["registry.terraform.io/hashicorp/aws"],
    on main.tf line 15, in provider "aws":
    15: provider "aws" {
```

why is terraform looking in C:\data? This is bizarre and even more bizarre is, if I run the same in elevated mode I get this error:

`Error: error configuring Terraform AWS Provider: loading configuration: read C:\Users\greatuser\env\Lib\site-packages\pip\_vendor\certifi: The handle is invalid.`

It may be related to [this issue](https://github.com/hashicorp/terraform/issues/25583)? Is there anything I can do?

**Comment by justinretzolk** [comment] 2022-04-22 20:19
Thanks for taking the time to submit this issue. It looks like this is a duplicate of #24279. We like to try to keep discussions consolidated, so we’re going to close this issue in favor of #24279.

**Closed by justinretzolk** 2022-04-22 20:19 UTC
Labels: needs-triage
