### ISSUE TITLE
aws_cognito_user_pool lifecycle crash 

### ISSUE THREAD

**Issue by ramimohammad** [hashicorp/terraform-provider-aws#26314] opened 2022-08-16 05:40 UTC
Hello Team ,   

required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.8.0"
    }
  }

**when we try to add the following** 

  lifecycle {
      ignore_changes = [account_recovery_setting]
    }
   account_recovery_setting {
     recovery_mechanism {
       name     = "admin_only"
       priority = 1
     }
    }

**it gives this :** 
Error: error updating Cognito User pool (eu-central-1_ID): InvalidParameter: 1 validation error(s) found.
│ - minimum field size of 1, UpdateUserPoolInput.AccountRecoverySetting.RecoveryMechanisms.

**Comment by justinretzolk** [comment] 2022-08-17 20:47
Hey @ramimohammad 👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include all of the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md?plain=1)?

**Comment by jmcvetta** [comment] 2022-10-19 00:21
Duplicate of #21654.

**Comment by justinretzolk** [comment] 2022-11-03 19:05
Hey @ramimohammad 👋 Since we haven't heard back, we'll close this issue for now. If you're still having troubles, please feel free to open a new issue and we'll be happy to keep working with you!

**Closed by justinretzolk** 2022-11-03 19:05 UTC
