### ISSUE TITLE
AssumeRoleTokenProviderNotSetError when using assume_role with mfa enabled

### ISSUE THREAD

**Issue by chrishowell** [hashicorp/terraform-provider-aws#10491] opened 2019-10-13 10:29 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform version: 0.12.10
Go runtime version: go1.13.1
provider.aws ~> 2.32.0

### Affected Resource(s)

* provider "aws"

### Terraform Configuration Files

**env**
```ini
AWS_SDK_LOAD_CONFIG=1
AWS_PROFILE=bar-admin
```

**~/.aws/config**
```ini
[default]
region = eu-west-1
output = json

[profile bar-default]
aws_access_key_id=<key>
aws_secret_access_key=<secret>

[profile bar-admin]
role_arn=arn:aws:iam::<account_id>:role/admin
source_profile=bar-default
mfa_serial=arn:aws:iam::<account_id>:mfa/ch
```

```hcl
resource "aws_iam_group" "admins" {
  name = "admins"
}

resource "aws_iam_role" "admin_mfa_role" {
  name = "admin"
  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::${data.aws_caller_identity.current.account_id}:root"
      },
      "Action": "sts:AssumeRole",
      "Condition": {
        "Bool": {
          "aws:MultiFactorAuthPresent": "true"
        }
      }
    }
  ]
}
EOF
}

resource "aws_iam_group_policy_attachment" "admins_assume_role" {
  group      = "${aws_iam_group.admins.name}"
  policy_arn = "${aws_iam_policy.assume_role.arn}"
}

resource "aws_iam_policy" "assume_role" {
  name = "assume_role"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": {
    "Effect": "Allow",
    "Action": "sts:AssumeRole",
    "Resource": "arn:aws:iam::*:role/*"
  }
}
EOF
}

resource "aws_iam_user" "ch" {
  name = "ch"
}

resource "aws_iam_user_login_profile" "ch_login" {
  user    = "${aws_iam_user.ch.name}"
  pgp_key = "keybase:chrishowell"
}

resource "aws_iam_user_group_membership" "ch_groups" {
  user = "${aws_iam_user.ch.name}"

  groups = [
    "${aws_iam_group.admins.name}"
  ]
}

```

### Debug Output

https://gist.github.com/chrishowell/ddd169c24ba4f0fcaba70a3e2f624a5a

### Panic Output

N/A

### Expected Behavior

As of `terraform-provider-aws_v2.32.0` I believe `assume_role` with mfa enabled should work.

### Actual Behavior

```Error: error creating EC2 Metadata session: AssumeRoleTokenProviderNotSetError: assume role with MFA enabled, but AssumeRoleTokenProvider session option not set.```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

Running locally on Mac OSX Catalina
Brew install of Terraform
No `~/.aws/configuration` file present

### References

* #10379
* #5592

**Comment by lachlancooper** [comment] 2019-12-17 03:29
I can reproduce this issue exactly as described.

I noticed there's a difference in behaviour between specifying the profile in an env var (`AWS_PROFILE=bar-admin`) vs. the provider config directly (`profile = "bar-admin"`). Using the env var results in the above `error creating EC2 Metadata session` message, which (since we're running locally, not on EC2) is perhaps a clue to why this is failing. I think this is closely related to https://github.com/hashicorp/aws-sdk-go-base/issues/7

Specifying the profile in provider config still doesn't work though, and I can't see any indication in the trace logs that terraform is even trying to assume a role. The only error I get is:

```
Error refreshing state: AccessDenied: Access Denied
	status code: 403, request id: 795ACFB7B863F762, host id: XRoHa+G5vU0TKxQkWwyld0p6g/u5Er8T/rd3NjU1rd7odmsFi1JGiZXb3/q42O2DYOCaByEmoFA=
```

**Comment by sean-kang** [comment] 2020-02-04 04:12
Any update on this issue? I am having the exactly same problem. I think that using assume_role with MFA is probably the most common way of access control in big organizations. In my opinion, specifying profile should be enough for Terraform to recognize the use of assume_role with MFA since the configuration is already in ~/.aws/config and ~/.aws/credentials.

**Comment by ryan-gerstenkorn-sp** [comment] 2020-02-09 21:42
As a workaround for anyone running into this when using aws-vault it seems you can remove mfa_serial from the role profile and this will work.

So for example:
```
[profile base]
credential_process = sh -c 'aws-vault exec base --json 2> $(tty)'
mfa_serial = arn:aws:iam::<redacted>:mfa/<user_name>
region = us-east-1

[profile assumed_role]
role_arn = arn:aws:iam::<redacted>:role/<role_to_assume>
source_profile = base
region = us-east-1
Note that the assumed_role does not have a mfa_serial option set, this is what seems to have been triggering this error in my case.
```

And then for your provider something like this should work:
```
provider "aws" {
  region  = "us-east-1
  profile = "assumed_role"
}
```
The problem is this role doesn't seem to work with aws-vault now. To fix that you will likely want to make an assumed_role profile and a assumed_role_tf profile to support both.

It almost seems like in this specific case if an error was not raised, this would simply work. I may look into this more if I have time.

**Comment by mikkopiu** [comment] 2020-05-25 13:18
> One problem is this role doesn't seem to work with aws-vault now. To fix that you will likely want to make an assumed_role profile and an assumed_role_tf profile to support both.

To add (for `aws-vault` users) there's also [`include_profile`](https://github.com/99designs/aws-vault/blob/v6.0.0-beta5/USAGE.md#include_profile) so you can do this:

```
[profile base]
credential_process = sh -c 'aws-vault exec base --json 2> $(tty)'
mfa_serial = arn:aws:iam::<account a>:mfa/<user_name>
region = us-east-1

[profile assumed_role]
role_arn = arn:aws:iam::<account b>:role/<role_to_assume>
source_profile = base
region = us-east-1
# For aws-vault only:
include_profile = base
```

This way `aws-vault exec` will know about the `mfa_serial` and prompt for MFA accordingly, and Terraform won't see the `mfa_serial` in `assumed_role` and lets `aws-vault` do the work.

**Comment by alexander-wiechert** [comment] 2020-08-05 10:58
this does not work for me. Below is my ~/.aws/credentials file.

`[default]
region = eu-central-1
aws_access_key_id = xxx
aws_secret_access_key = xxx
mfa_serial = arn:aws:iam::acount_id_1:mfa/username
credential_process = sh -c 'aws-vault exec default --json 2> $(tty)'

[profile_1]
role_arn = arn:aws:iam::account_id_2:role/SuperAdmin
source_profile = default
include_profile = default`


In terraform I setup the provider like this
`provider "aws" {
  region                  = eu-central-1
  profile                 = "profile_2"
}`

If I issue the terraform command I got this:

terraform init --backend-config=backends/mb.tfbackend 
Initializing modules...

Initializing the backend...

Error: No valid credential sources found for AWS Provider.
	Please see https://terraform.io/docs/providers/aws/index.html for more information on
	providing credentials for the AWS Provider

**Comment by IceBear2k** [comment] 2021-02-09 13:43
> > One problem is this role doesn't seem to work with aws-vault now. To fix that you will likely want to make an assumed_role profile and an assumed_role_tf profile to support both.
> 
> To add (for `aws-vault` users) there's also [`include_profile`](https://github.com/99designs/aws-vault/blob/v6.0.0-beta5/USAGE.md#include_profile) so you can do this:
> 
> ```
> [profile base]
> credential_process = sh -c 'aws-vault exec base --json 2> $(tty)'
> mfa_serial = arn:aws:iam::<account a>:mfa/<user_name>
> region = us-east-1
> 
> [profile assumed_role]
> role_arn = arn:aws:iam::<account b>:role/<role_to_assume>
> source_profile = base
> region = us-east-1
> # For aws-vault only:
> include_profile = base
> ```
> 
> This way `aws-vault exec` will know about the `mfa_serial` and prompt for MFA accordingly, and Terraform won't see the `mfa_serial` in `assumed_role` and lets `aws-vault` do the work.

This workaround works well but isn't flawless. When using VS Code with the Terraform plugin containing Terraform Language Server for example, the language server will perform Terraform commands in the background. While it doesn't output any error message, it tries to call `aws-vault` which in turn ends up writing a file `not a tty` in the project directory, since the language server doesn't provide a tty. I have yet to find a solution to that other than adding `not a tty` to `.gitignore` which seems like a pretty crappy solution.

**Comment by zmingxie** [comment] 2021-02-09 14:27
I ran into a similar issue with the terraform language server, and I change the credential helper process line to something like this which will trigger a dialog box for the MFA prompt:
```
credential_process=aws-vault exec home --json --prompt=osascript
```

I do wish this configuration is more flexible because I do prefer TTY input in most other cases.
 
> This workaround works well but isn't flawless. When using VS Code with the Terraform plugin containing Terraform Language Server for example, the language server will perform Terraform commands in the background. While it doesn't output any error message, it tries to call `aws-vault` which in turn ends up writing a file `not a tty` in the project directory, since the language server doesn't provide a tty. I have yet to find a solution to that other than adding `not a tty` to `.gitignore` which seems like a pretty crappy solution.

**Comment by IceBear2k** [comment] 2021-02-09 14:59
> I ran into a similar issue with the terraform language server, and I change the credential helper process line to something like this which will trigger a dialog box for the MFA prompt:
> 
> ```
> credential_process=aws-vault exec base --json --prompt=osascript
> ```
> 
> I do wish this configuration is more flexible because I do prefer TTY input in most other cases.
> 
> > This workaround works well but isn't flawless. When using VS Code with the Terraform plugin containing Terraform Language Server for example, the language server will perform Terraform commands in the background. While it doesn't output any error message, it tries to call `aws-vault` which in turn ends up writing a file `not a tty` in the project directory, since the language server doesn't provide a tty. I have yet to find a solution to that other than adding `not a tty` to `.gitignore` which seems like a pretty crappy solution.

I'm on Ubuntu and I believe `osascript` is macOS specific. So, it doesn't sound like a solution I could use.

Anyway, this works for me but I'm not proud of it:

```sh
credential_process=sh -c "if [ $(echo $(tty) | cut -c 1-5) = '/dev/' ]; then aws-vault exec base --json 2> $(tty); else return 0; fi"
```

Works as before, minus `not a tty` files created by Terraform Language Server.

**Comment by bertrandmartel** [comment] 2021-03-30 23:26
without using aws-vault, I was able to make it work with `credential_process`  to generate the credentials with a local script and cache the tokens in a new profile  `tf_temp`

The script would:

* check if the token is still valid for the profile `tf_temp`
* if token is valid, extract the token from existing config using `aws configure get xxx --profile tf_temp`
* if token is not valid, prompt use to enter mfa token
* generate the session token with `aws assume-role --token-code xxxx ... --profile your_profile`
* set the temporary profile token tf_temp using `aws configure set xxx --profile tf_temp`

[checkout this gist](https://gist.github.com/bertrandmartel/f6b1d1ac1dbd396a94ba0ac9468d5b3a)
[stackoverflow post](https://stackoverflow.com/a/66878739/2614364)

**Comment by shearn89** [comment] 2022-01-28 11:06
This still appears to be an issue - I have a fairly simple template but recently started using a role in the account and can now no longer deploy...

**Comment by ctriegg-mak** [comment] 2022-03-02 15:00
I've encountered this issue too. Using workarounds always increases the complexity and should not be required. I think it's a common way to use 2FA when assuming a role. :cry:

**Comment by matthewmrichter** [comment] 2022-04-21 18:05
In our case, quick and dirty fix is: 

```
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "< 4.0.0"
    }
```

Using > 4.0.0 we get `Error: error configuring Terraform AWS Provider: loading configuration: assume role with MFA enabled, but AssumeRoleTokenProvider session option not set.`

**Comment by matthewmrichter** [comment] 2022-04-21 19:47
Note, I finally read https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-4-upgrade#changes-to-authentication and it gave me a pretty big clue. Removing the `profile` attribute from the `provider "aws" {}` block allows me to run terraform in an assumed AWS role using `aws-vault`.

**Comment by saholman** [comment] 2022-08-26 20:30
I use the following bash function to get around this issue:

```
function set_aws_creds () {
    unset AWS_ACCESS_KEY_ID
    unset AWS_SECRET_ACCESS_KEY
    unset AWS_SESSION_TOKEN

    ROLE="$( aws.exe configure get role_arn --profile $1 )"
    read AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN <<< $(aws.exe sts assume-role --role-arn $ROLE --role-session-name set-aws-creds-session --output text | awk '/^CREDENTIALS/ {print $2, $4, $5 }')
    export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    export AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
}

```

This is based on this StackOverflow answer: https://stackoverflow.com/a/53199639.

**Comment by mreeves1** [comment] 2023-01-20 06:06
I use https://github.com/broamski/aws-mfa to get around this issue.

I run this script below and then two "dynamic" profiles are created that will last 12 hours. 

This uses the main profile "mreeves" to fetch temporary creds for two profiles "mreeves-admin" and "mreeves-power" it saves to your ~/.aws/credentials file. See this PR to sceptre for how someone suggested they fix it so the boto session cache is respected: https://github.com/Sceptre/sceptre/issues/674. 

There should be a way to "pre-auth" your creds, enter your mfa and then terraform would simply use boto session cache. That's how the aws cli works.

```
#! /usr/bin/env bash

# Authenticate assume roles so mfa is cached
# Workaround because terraform also does not handle an already authed MFA profile correctly:
# https://github.com/hashicorp/terraform-provider-aws/issues/10491
# https://stackoverflow.com/questions/52432717/terraform-unable-to-assume-roles-with-mfa-enabled

DURATION="43200" # 12 hours

aws-mfa --device arn:aws:iam::1234567890:mfa/mreeves \
	--duration "$DURATION" \
	--profile mreeves \
        --assume-role arn:aws:iam::1234567890:role/human-admin \
        --long-term-suffix none \
	--short-term-suffix admin

aws-mfa --device arn:aws:iam::1234567890:mfa/mreeves \
	--duration "$DURATION" \
	--profile mreeves \
        --assume-role arn:aws:iam::1234567890:role/human-power \
        --long-term-suffix none \
	--short-term-suffix power
```

**Comment by gdavison** [comment] 2023-02-28 23:30
Hello, everyone. The issue #2420 also addresses the lack of support for MFA tokens in the AWS Provider. So that any future discussion will be in one place, I'm going to close this issue.

See https://github.com/hashicorp/terraform-provider-aws/issues/2420#issuecomment-1449084088 for the current status of the issue

**Closed** 2023-02-28 23:31 UTC
Labels: bug, service/iam, provider, authentication, roadmap
