### ISSUE TITLE
[Enhancement]: Support `DeploymentTargets` sub arguments for `aws_cloudformation_stack_set_instance`

### ISSUE THREAD

**Issue by AliAllomani** [hashicorp/terraform-provider-aws#35448] opened 2024-01-23 16:50 UTC
### Description

`aws_cloudformation_stack_set_instance` resource support defining `deployment_targets`.`organizational_unit_ids`. However, there is no configurable parameters for `Accounts` and `AccountFilterType` under `deployment_targets`

### Affected Resource(s) and/or Data Source(s)

* aws_cloudformation_stack_set_instance

### Potential Terraform Configuration

```terraform
resource "aws_cloudformation_stack_set_instance" "example" {
  deployment_targets {
    organizational_unit_ids = [aws_organizations_organization.example.roots[0].id]
    accounts = ["11111111111", "22222222222"]
    account_filter_type = "INTERSECTION"
  }

  region         = "us-east-1"
  stack_set_name = aws_cloudformation_stack_set.example.name
}
```

### References

* https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack-instances.html

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-01-23 23:06
Duplicate of #33914

**Closed by justinretzolk** 2024-01-23 23:06 UTC
Labels: enhancement, service/cloudformation, needs-triage
