### ISSUE TITLE
I'm going to lock this issue because it has been closed for _30 days_ ⏳. This helps our maintainers find and focus on the active issues.

### ISSUE THREAD

**Issue by AlexanderLahutsin** [hashicorp/terraform-provider-aws#17946] opened 2021-03-05 11:15 UTC
I'm going to lock this issue because it has been closed for _30 days_ ⏳. This helps our maintainers find and focus on the active issues.

If you feel this issue should be reopened, we encourage creating a new issue linking back to this one for added context. Thanks!

_Originally posted by @hashibot[bot] in https://github.com/hashicorp/terraform-provider-aws/issues/7828#issuecomment-549051280_

**Comment by AlexanderLahutsin** [comment] 2021-03-05 11:36
# Find a certificate that is issued
```
data "aws_acm_certificate" "issued" {
  domain   = "*.example.com"
  statuses = ["ISSUED"]
}
```

Error: No certificate for domain "*.example.com" found in this region

  on .terraform/modules/environment/environment/datasource.tf line 142, in data "aws_acm_certificate" "issued":
 142: data "aws_acm_certificate" "issued" {
 
```
 > % aws acm describe-certificate --certificate-arn arn:aws:acm:eu-west-2:X:certificate/abc
{
    "Certificate": {
        "CertificateArn": "arn:aws:acm:eu-west-2:X:certificate/abc",
        "DomainName": "*.example.com",
        "SubjectAlternativeNames": [
            "*.example.com",
            "example.com"
        ],
```

1. I Imported certs to AWS ACM in manual
2. I written a code (datasource) for parse it, but got fail(

**Comment by ewbankkit** [comment] 2021-03-05 13:04
This is a duplicate of https://github.com/hashicorp/terraform-provider-aws/issues/17947. Closing.

**Closed by ewbankkit** 2021-03-05 13:04 UTC
