### ISSUE TITLE
resource/aws_cloudwatch_event_target: Intermittent acceptance test failures with active tasks

### ISSUE THREAD

**Issue by gdavison** [hashicorp/terraform-provider-aws#18601] opened 2021-04-06 22:27 UTC
Various acceptance tests for `aws_cloudwatch_event_target` fail intermittently with the error

```
Error: Error deleting ECS cluster: ClusterContainsTasksException: The Cluster cannot be deleted while Tasks are active.
```

### Affected Resource

* aws_cloudwatch_event_target

**Comment by ewbankkit** [comment] 2021-04-09 20:25
I just hit this while retesting #18491. I think it's because there is no explicit dependency between the cluster and the task and Terraform attempts to delete the cluster before or in parallel with deleting the task.

**Comment by ewbankkit** [comment] 2021-05-05 12:04
This is a duplicate of #15652 and #15668.

**Closed by ewbankkit** 2021-05-05 12:04 UTC
Labels: service/cloudwatchevents, service/eventbridge, tests
