### ISSUE TITLE
[Enhancement]: Add oversize_handling configuration to AWS WAF for body block

### ISSUE THREAD

**Issue by tadayoni1** [hashicorp/terraform-provider-aws#28461] opened 2022-12-19 19:37 UTC
### Description

Add oversize_handling configuration to AWS WAF for `body` block.

### Affected Resource(s) and/or Data Source(s)

* aws_wafv2_web_acl

### Potential Terraform Configuration

```terraform
statement {
    regex_pattern_set_reference_statement {
        arn = aws_wafv2_regex_pattern_set.this.arn
        field_to_match {
            body {
                oversize_handling = "CONTINUE"
            }
        }
        text_transformation {
            priority = 0
            type     = "NONE"
        }
    }
}
```

### References

This has been fixed for `json_body`, `headers` and `cookies` blocks but missed for `body` block by https://github.com/hashicorp/terraform-provider-aws/pull/26506

### Would you like to implement a fix?

None

**Comment by ErickVaquero** [comment] 2022-12-20 16:47
This appears to be a duplicate of : https://github.com/hashicorp/terraform-provider-aws/issues/25545

**Comment by breathingdust** [comment] 2023-01-24 16:15
Duplicate of #25545

**Closed by breathingdust** 2023-01-24 16:15 UTC
Labels: enhancement, service/wafv2
