### ISSUE TITLE
Error: Cannot import to non-existent resource address

### ISSUE THREAD

**Issue by smoms** [hashicorp/terraform-provider-aws#33104] opened 2023-08-19 08:02 UTC
### Terraform Core Version

 v1.5.5

### AWS Provider Version

~>5.0

### Affected Resource(s)

Not able to import existing resources using _import block_ without error. I am following exercise in module m3: https://github.com/ned1313/Deep-Dive-Terraform/tree/main/m3

### Expected Behavior

When I run _terraform plan_ I should not errors like _Error: Cannot import to non-existent resource address_

### Actual Behavior

WHen I run terraform plan I get:

```shell
Error: Cannot import to non-existent resource address
│
│ Importing to resource address module.main.aws_subnet.public[0] is not possible, because that address does not exist in configuration. Please ensure that the resource key is correct, or remove this import block.
╵
╷
│ Error: Cannot import to non-existent resource address
│
│ Importing to resource address module.main.aws_subnet.public[1] is not possible, because that address does not exist in configuration. Please ensure that the resource key is correct, or remove this import block.
╵
╷
│ Error: Cannot import to non-existent resource address
│
│ Importing to resource address module.main.aws_internet_gateway.this[0] is not possible, because that address does not exist in configuration. Please ensure that the resource key is correct, or remove this import block.
╵
╷
│ Error: Cannot import to non-existent resource address
│
│ Importing to resource address module.main.aws_route.public_internet_gateway[0] is not possible, because that address does not exist in configuration. Please ensure that the resource key is correct, or remove this import block.
╵
╷
│ Error: Cannot import to non-existent resource address
│
│ Importing to resource address module.main.aws_route_table.public[0] is not possible, because that address does not exist in configuration. Please ensure that the resource key is correct, or remove this import block.
╵
╷
│ Error: Cannot import to non-existent resource address
│
│ Importing to resource address module.main.aws_route_table_association.public[0] is not possible, because that address does not exist in configuration. Please ensure that the resource key is correct, or remove this import block.        
╵
╷
│ Error: Cannot import to non-existent resource address
│
│ Importing to resource address module.main.aws_route_table_association.public[1] is not possible, because that address does not exist in configuration. Please ensure that the resource key is correct, or remove this import block.        
╵
```

### Terraform Configuration Files

https://github.com/ned1313/Deep-Dive-Terraform/tree/main/m3

### Steps to Reproduce

https://github.com/ned1313/Deep-Dive-Terraform/tree/main/m3

### Would you like to implement a fix?

None

**Comment by M4elstrom** [comment] 2023-08-20 00:53
I have the same issue!

**Comment by smoms** [comment] 2023-08-20 18:55
It seems it is solved. I recreated the project and run it again. I also found out a typo error in the import.tf file.

**Comment by kbolino** [comment] 2023-08-21 18:23
I'm fairly certain of the cause of this issue, though it may actually lay in Terraform proper rather than the AWS provider.

The issue arises when:
- you are importing multiple resources at the same time, and
- at least one of those resources fails an import validation check (e.g. security group IDs must start with `sg-`), and
- the invalid imports are dependencies of other resources which you're also importing

This leads to the following hypothesized chain of events:
- the planner visits all of the imports in dependency order, then
- the invalid import fails but the error is suppressed, then
- the dependent resource cannot be planned and so appears not to exist

You can solve this problem currently by commenting out the import block for the "non-existent resource" temporarily and then re-running `plan` to reveal the problem, fixing that, and then uncommenting. Though, you may have to repeat the "comment out and re-plan" step multiple times until it reveals another problem besides "non-existent resource", if you have a lot of resources to import.

**Comment by justinretzolk** [comment] 2023-08-21 21:52
Hey @smoms 👋 Thank you for taking the time to raise this! This would be more of a Terraform Core issue, given that it's throwing an error that's more related to the graph. That said, it sounds like the issue may have been a typo, so rather than moving this issue, I'm going to close it out. If you (or anyone else) happens to run into this issue again, please do let us know by opening an issue in the [Terraform Core repository](https://www.github.com/hashicorp/terraform).

**Closed by justinretzolk** 2023-08-21 21:52 UTC
Labels: bug, needs-triage
