### ISSUE TITLE
[Enhancement]: Deletion protection for aws_dynamodb_table_replica

### ISSUE THREAD

**Issue by chandini193** [hashicorp/terraform-provider-aws#34754] opened 2023-12-06 05:55 UTC
### Description

I'd like to enable deletion protection on select dynamodb replica tables using terraform

### Affected Resource(s) and/or Data Source(s)

aws_dynamodb_table_replica

### Potential Terraform Configuration

```terraform
resource "aws_dynamodb_table_replica" "default" {
  name = "example"

  # ...

  deletion_protection = true
}
```

### References

https://github.com/hashicorp/terraform-provider-aws/issues/29876

### Would you like to implement a fix?

None

**Comment by ankon** [comment] 2024-10-25 11:54
This seems to be a duplicate of https://github.com/hashicorp/terraform-provider-aws/issues/30213.

Can we close this, and move the :+1:  from here to there?

**Closed** 2024-10-30 18:28 UTC
Labels: enhancement, service/dynamodb
