### ISSUE TITLE
[New]: aws_networkfirewall_rule_group_association resource

### ISSUE THREAD

**Issue by fawaf** [hashicorp/terraform-provider-aws#34956] opened 2023-12-17 02:46 UTC
### Description

Allows managing Network Firewall rule groups independently from a Network Firewall policy.
Currently all Network Firewall resources (policy, rule groups, and firewall itself), when all deployed with Terraform, are tightly coupled together.

I think it would require some update to the aws_networkfirewall_firewall_policy to ignore stateful_rule_group_reference block configuration's state when empty (and hence managed by the new aws_networkfirewall_rule_group_association resource).

### Requested Resource(s) and/or Data Source(s)

- aws_networkfirewall_rule_group_association (new)
- aws_networkfirewall_firewall_policy (affected, maybe?)

### Potential Terraform Configuration

```terraform
resource "aws_networkfirewall_rule_group" "example" {
  capacity = 100
  name     = "example"
  type     = "STATEFUL"
  rule_group {
    rules_source {
      rules_source_list {
        generated_rules_type = "DENYLIST"
        target_types         = ["HTTP_HOST"]
        targets              = ["test.example.com"]
      }
    }
  }
}

resource "aws_networkfirewall_firewall_policy" "example" {
  name = "example"

  firewall_policy {
    stateless_default_actions          = ["aws:pass"]
    stateless_fragment_default_actions = ["aws:drop"]
  }
}

resource "aws_networkfirewall_rule_group_association" "example" {
  firewall_policy_arn = aws_networkfirewall_firewall_policy.example.arn
  rule_group_arn      = aws_networkfirewall_rule_group.example.arn
  priority            = 123
}
```

### References

same as #21475

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2023-12-18 20:39
Duplicate of #28100

**Closed by justinretzolk** 2023-12-18 20:39 UTC
Labels: needs-triage, service/networkfirewall
