### ISSUE TITLE
[Bug]: Terraform downloading unexpected version of aws provider

### ISSUE THREAD

**Issue by THONGJI** [hashicorp/terraform-provider-aws#39997] opened 2024-11-04 07:42 UTC
### Terraform Core Version

1.9.8

### AWS Provider Version

5.74.0

### Affected Resource(s)

Terraform version: 1.9.8

Think started just now, no matter I use my personal computer or deployment pipeline on server, when I run `terraform init` terraform will help me download older version of aws provider.
This will cause "Resource instance managed by newer provider version" error when run `terraform plan`.

I didn't specify any version in main.tf, **_.terraform.lock.hcl file_** and **_.terraform folder_** is removed before running `terraform init`.

Not sure should I raise the issue here or https://github.com/hashicorp/terraform.

### Expected Behavior

terraform init should download 5.74.0 aws provider

### Actual Behavior

terraform init downloaded 5.41.1 aws provider

### Terraform Configuration Files

```
terraform {
    backend "local" {
    }
}

provider "aws" {
    region = "ap-southeast-1"
}
```

### Steps to Reproduce

1. Download terraform 1.9.8 from [https://releases.hashicorp.com/terraform/1.9.8/](https://releases.hashicorp.com/terraform/1.9.8/)
2. Unzip and place terraform.exe under same directory with main.tf
3. Run `terraform init`

### Debug Output

```
sh-4.4$ ./terraform.exe init
2024-11-04T15:19:18.170+0800 [INFO]  Terraform version: 1.9.8
2024-11-04T15:19:18.203+0800 [DEBUG] using github.com/hashicorp/go-tfe v1.58.0
2024-11-04T15:19:18.203+0800 [DEBUG] using github.com/hashicorp/hcl/v2 v2.20.0
2024-11-04T15:19:18.203+0800 [DEBUG] using github.com/hashicorp/terraform-svchost v0.1.1
2024-11-04T15:19:18.203+0800 [DEBUG] using github.com/zclconf/go-cty v1.14.4
2024-11-04T15:19:18.203+0800 [INFO]  Go runtime version: go1.22.7
2024-11-04T15:19:18.203+0800 [INFO]  CLI args: []string{"C:\\...\\terraform\\terraform.exe", "init"}
2024-11-04T15:19:18.207+0800 [DEBUG] Attempting to open CLI config file: C:\Users\...\AppData\Roaming\terraform.rc
2024-11-04T15:19:18.207+0800 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2024-11-04T15:19:18.207+0800 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2024-11-04T15:19:18.208+0800 [DEBUG] ignoring non-existing provider search directory C:\Users\...\AppData\Roaming\terraform.d\plugins
2024-11-04T15:19:18.208+0800 [DEBUG] ignoring non-existing provider search directory C:\Users\...\AppData\Roaming\HashiCorp\Terraform\plugins      
2024-11-04T15:19:18.209+0800 [INFO]  CLI command args: []string{"init"}
Initializing the backend...
2024-11-04T15:19:18.212+0800 [DEBUG] checking for provisioner in "."
2024-11-04T15:19:18.213+0800 [DEBUG] checking for provisioner in "C:\\...\\terraform"

Successfully configured the backend "local"! Terraform will automatically
use this backend unless the backend configuration changes.
2024-11-04T15:19:18.223+0800 [DEBUG] checking for provisioner in "."
2024-11-04T15:19:18.223+0800 [DEBUG] checking for provisioner in "C:\\...\\terraform"
Initializing modules...
2024-11-04T15:19:18.226+0800 [DEBUG] Module installer: begin ecs_repository
2024-11-04T15:19:18.227+0800 [DEBUG] Module installer: ecs_repository installed at ecs_repository
- ecs_repository in ecs_repository
2024-11-04T15:19:18.227+0800 [DEBUG] Module installer: begin ecs_service
2024-11-04T15:19:18.229+0800 [DEBUG] Module installer: ecs_service installed at ecs_service
- ecs_service in ecs_service
2024-11-04T15:19:18.229+0800 [DEBUG] Module installer: begin ecs_task_definition
2024-11-04T15:19:18.234+0800 [DEBUG] Module installer: ecs_task_definition installed at ecs_task_definition
- ecs_task_definition in ecs_task_definition
Initializing provider plugins...
- Finding hashicorp/aws versions matching "5.54.1"...
2024-11-04T15:19:18.239+0800 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
2024-11-04T15:19:18.328+0800 [DEBUG] GET https://registry.terraform.io/v1/providers/hashicorp/aws/versions
- Finding latest version of hashicorp/null...
2024-11-04T15:19:18.358+0800 [DEBUG] GET https://registry.terraform.io/v1/providers/hashicorp/null/versions
2024-11-04T15:19:18.389+0800 [DEBUG] GET https://registry.terraform.io/v1/providers/hashicorp/aws/5.54.1/download/windows/amd64
2024-11-04T15:19:18.421+0800 [DEBUG] GET https://releases.hashicorp.com/terraform-provider-aws/5.54.1/terraform-provider-aws_5.54.1_SHA256SUMS
2024-11-04T15:19:18.473+0800 [DEBUG] GET https://releases.hashicorp.com/terraform-provider-aws/5.54.1/terraform-provider-aws_5.54.1_SHA256SUMS.72D7468F.sig
- Installing hashicorp/aws v5.54.1...
2024-11-04T15:19:31.321+0800 [DEBUG] Provider signed by 34365D9472D7468F HashiCorp Security (hashicorp.com/security) <security@hashicorp.com>
- Installed hashicorp/aws v5.54.1 (signed by HashiCorp)
2024-11-04T15:19:34.000+0800 [DEBUG] GET https://registry.terraform.io/v1/providers/hashicorp/null/3.2.3/download/windows/amd64
2024-11-04T15:19:34.035+0800 [DEBUG] GET https://releases.hashicorp.com/terraform-provider-null/3.2.3/terraform-provider-null_3.2.3_SHA256SUMS
2024-11-04T15:19:34.064+0800 [DEBUG] GET https://releases.hashicorp.com/terraform-provider-null/3.2.3/terraform-provider-null_3.2.3_SHA256SUMS.72D7468F.sig
- Installing hashicorp/null v3.2.3...
2024-11-04T15:19:34.720+0800 [DEBUG] Provider signed by 34365D9472D7468F HashiCorp Security (hashicorp.com/security) <security@hashicorp.com>
- Installed hashicorp/null v3.2.3 (signed by HashiCorp)
Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-11-04 20:39
Hey @THONGJI 👋 Thank you for taking the time to raise this! The version of the provider that is downloaded is controlled by Terraform, so a bug report for something like that would need to go to the [Terraform Core repository](https://github.com/hashicorp/terraform). That said, I noticed in your logs that you're using a couple of modules. It's possible that one of these modules has a version constraint within it that's dictating what version of the provider is being installed. You can check that with the `terraform providers` command. Here's the output of that command from a small test configuration I created:

```console
$ terraform providers

Providers required by configuration:
.
├── provider[registry.terraform.io/hashicorp/aws]
└── module.test
    └── provider[registry.terraform.io/hashicorp/aws] ~> 4.0
```

Since this isn't something the AWS Provider team will need to take action on, I'm going to close this issue. If you experience any other unexpected behavior with the provider, please do let us know!

**Closed by justinretzolk** 2024-11-04 20:39 UTC
Labels: bug, needs-triage
