### ISSUE TITLE
[Bug]: aws_neptune_cluster_endpoint (api error InvalidParameterValue: Endpoint type not supported by the cluster)

### ISSUE THREAD

**Issue by LoScriptler** [hashicorp/terraform-provider-aws#39776] opened 2024-10-17 16:29 UTC
### Terraform Core Version

1.9.5

### AWS Provider Version

5.72.1

### Affected Resource(s)

aws_neptune_cluster_endpoint

### Expected Behavior

Creation of the custom end point writer for neptune

### Actual Behavior

When I create this resource
`resource "aws_neptune_cluster_endpoint" "neptune_ep_custom_writer" {
  cluster_identifier          = var.switch_endpoint ? var.cluster_id_gamma : var.cluster_id_beta
  cluster_endpoint_identifier = "w-${var.resource_prefix}-endpoint-writer"
  endpoint_type               = "WRITER"
}`
I have an error but if I create READER there is't a error

### Relevant Error/Panic Output Snippet

```shell
> │ Error: creating Neptune Cluster Endpoint: operation error Neptune: CreateDBClusterEndpoint, https response error StatusCode: 400, RequestID: b187f16d-c6c3-4620-aed7-961ae405cd43, api error InvalidParameterValue: Endpoint type not supported by the cluster
│ 
│   with aws_neptune_cluster_endpoint.neptune_ep_custom_writer,
│   on endpoint_custom.tf line 7, in resource "aws_neptune_cluster_endpoint" "neptune_ep_custom_writer":
│    7: resource "aws_neptune_cluster_endpoint" "neptune_ep_custom_writer" {
```

### Terraform Configuration Files

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.72.1"
    }
  }

  required_version = "~> 1.9"
}

provider "aws" {
  region              = var.region
  allowed_account_ids = [var.account_id]
  default_tags {
    tags = {
      ManagedBy  = "terraform"
      Repository = local.repository
      "crif:env" = upper(var.env)
    }
  }
}

resource "aws_neptune_cluster_endpoint" "neptune_ep_custom_writer" {
  cluster_identifier          = var.switch_endpoint ? var.cluster_id_gamma : var.cluster_id_beta
  cluster_endpoint_identifier = "w-${var.resource_prefix}-endpoint-writer"
  endpoint_type               = "WRITER"
}
```

### Steps to Reproduce

simply apply

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-10-21 16:11
Hey @LoScriptler 👋 Thank you for taking the time to raise this! It looks like the error you're receiving is from the AWS API itself, which often indicates a configuration issue. To verify this, I tend to recommend trying the same action using the [AWS CLI](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/neptune/create-db-cluster-endpoint.html) or [API](https://docs.aws.amazon.com/neptune/latest/apiref/API_CreateDBClusterEndpoint.html) directly.

If you're able to successfully take the same action using one of those methods, it's more likely to indicate a bug with the provider. In that case, we may need for you to supply either debug logging (redacted as needed) or a more complete sample configuration that can be used to reproduce the issue. That information will help whoever picks this up to have the necessary information to investigate.

**Comment by LoScriptler** [comment] 2024-10-21 16:23
Hi, yes, I confirm.
The error is from the AWS API. Via AWS cli I have recived the same error.
I have found a work-around using pipeline script.
First time I get via AWS cli the name of the reader instances, and setup the custom ep via terraform in this way:

```
resource "aws_neptune_cluster_endpoint" "neptune_ep_custom_writer" {
  cluster_identifier          = var.switch_endpoint ? var.cluster_id_gamma : var.cluster_id_beta
  cluster_endpoint_identifier = "${var.resource_prefix}-endpoint-writer"
  endpoint_type               = "ANY"
  excluded_members            = [var.excluded_members_endpoint]
}
```

The pipeline script exec a terraform apply using custom "var.excluded_members_endpoint" (contain the writer instance id) provisioned by aws cli script.

**Comment by justinretzolk** [comment] 2024-10-21 18:19
Thanks for follow up here, @LoScriptler! Since this seems to be configuration related, and not something that the AWS Provider team will need to make changes for, I'm going to close this issue. If you experience unexpected behavior in the future, please do let us know!

**Closed by justinretzolk** 2024-10-21 18:19 UTC
Labels: bug, service/neptune, needs-triage
