### ISSUE TITLE
Failing to delete an already provisioned subnet if it was used for an Autoscaling Group (that created some EC2 instances)

### ISSUE THREAD

**Issue by Dzhuneyt** [hashicorp/terraform-provider-aws#9495] opened 2019-07-25 11:31 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.5
+ provider.aws v2.20.0
+ provider.template v2.1.2

### Terraform Configuration Files

```hcl
resource "aws_vpc" "main" {
  cidr_block = "10.0.0.0/16"
  enable_dns_hostnames = true
}
resource "aws_subnet" "subnet1" {
  vpc_id = aws_vpc.main.id
  cidr_block = "10.0.1.0/24"
}
# Read all subnet ids for this vpc/region.
data "aws_subnet_ids" "all_subnets" {
  vpc_id = data.aws_vpc.default.id
  # Wait for the subnets to be actually created, not just the VPC
  depends_on = [
    aws_subnet.subnet1
  ]
}
resource "aws_autoscaling_group" "ecs_cluster_spot" {
  name_prefix = "ecs_cluster_spot"
  termination_policies = [
    "OldestInstance"]
  max_size = local.max_spot_instances
  min_size = local.min_spot_instances
  launch_configuration = aws_launch_configuration.ecs_config_launch_config_spot.name
  lifecycle {
    create_before_destroy = true
  }
  # This is the important part:
  # We attach the subnets of the VPC to the autoscaling group
  vpc_zone_identifier = data.aws_subnet_ids.all_subnets.ids
}
```

I've truncated some pieces of my configuration to the bare minimum. I later add ECS task definitions and services onto the AWS ECS but I don't think these are important for the issue. I might as well launch them using the AWS console and not with Terraform and I assume the effect will be the same.

### Debug Output

```
...
aws_subnet.subnet1: Still destroying... [id=subnet-0a7d3066014860a8e, 18m10s elapsed]
aws_subnet.subnet1: Still destroying... [id=subnet-0a7d3066014860a8e, 18m20s elapsed]
aws_subnet.subnet1: Still destroying... [id=subnet-0a7d3066014860a8e, 18m30s elapsed]
aws_subnet.subnet1: Still destroying... [id=subnet-0a7d3066014860a8e, 18m40s elapsed]
aws_subnet.subnet1: Still destroying... [id=subnet-0a7d3066014860a8e, 18m50s elapsed]
aws_subnet.subnet1: Still destroying... [id=subnet-0a7d3066014860a8e, 19m0s elapsed]
aws_subnet.subnet1: Still destroying... [id=subnet-0a7d3066014860a8e, 19m10s elapsed]
aws_subnet.subnet1: Still destroying... [id=subnet-0a7d3066014860a8e, 19m20s elapsed]
```

After 19 minutes. The subnet is still not destroyed.

### Expected Behavior

subnet1 is destroyed

### Actual Behavior

Destroying subnet1 hangs. If I attempt to manually remove the resource from the AWS console, I get this:
![image](https://user-images.githubusercontent.com/1754428/61871121-a4ada580-aee8-11e9-87bd-1cdc15e8dfc2.png)

I assume this is the same reason why Terraform fails to delete the subnet and hangs.

### Steps to Reproduce

1. `terraform apply`
2. Launch some services in your ECS cluster and instances (I don't think this makes a difference)

### Important Factoids

I removed the "subnet1" definition from my terraform files and added another subnet definition, causing "subnet1" to be marked for destruction. On my attempt to "apply" the changes, I encountered this hang in deletion.

**Comment by bjd2385** [comment] 2019-12-05 19:47
I've just experienced this same thing, believe it or not.
```
aws_subnet.subnet_ovpn: Still destroying... [id=subnet-0e676ec34db23e1d7, 1m40s elapsed]
aws_subnet.subnet_ovpn: Still destroying... [id=subnet-0e676ec34db23e1d7, 1m50s elapsed]
aws_subnet.subnet_ovpn: Still destroying... [id=subnet-0e676ec34db23e1d7, 2m0s elapsed]
aws_subnet.subnet_ovpn: Still destroying... [id=subnet-0e676ec34db23e1d7, 2m10s elapsed]
aws_subnet.subnet_ovpn: Still destroying... [id=subnet-0e676ec34db23e1d7, 2m20s elapsed]
aws_subnet.subnet_ovpn: Still destroying... [id=subnet-0e676ec34db23e1d7, 2m30s elapsed]
aws_subnet.subnet_ovpn: Still destroying... [id=subnet-0e676ec34db23e1d7, 2m40s elapsed]
aws_subnet.subnet_ovpn: Still destroying... [id=subnet-0e676ec34db23e1d7, 2m50s elapsed]
...
```
unfortunate this is an open issue.

**Comment by romafederico** [comment] 2019-12-09 03:29
Any updates on this issue? I bumped into https://aws.amazon.com/blogs/compute/update-issue-affecting-hashicorp-terraform-resource-deletions-after-the-vpc-improvements-to-aws-lambda/ but I can't delete subnets even using provider v2.41.

**Comment by bflad** [comment] 2019-12-09 14:34
Hi folks 👋 If you are seeing `DependencyViolation` errors on EC2 Subnet deletions or long delays in EC2 Subnet deletion, the causes for these will be very specific to your environment and sometimes caused by AWS not properly cleaning up its own infrastructure. Some pointers that may help:

- Ensure no infrastructure creating ENIs within the Subnet exists outside Terraform
- For AWS resources that manage ENIs automatically (including but not limited to Network Load Balancers, Lambda Functions, or EKS Node Groups that automatically provision/delete ENIs), if they require IAM Role permissions to perform these actions, ensure that the Terraform resource with the IAM Role reference also includes explicit `depends_on` to the `aws_iam_role_policy`/`aws_iam_role_policy_attachment` resources so those permissions remain until the AWS resource that needs those permissions is deleted properly first
- Check for lingering ENIs in the Subnet either via the web console (EC2 > Network Interfaces) or via the AWS CLI, e.g. `aws ec2 describe-network-interfaces --filters Name=subnet-id,Values=subnet-XXXXXXXXX` -- these should help narrow down AWS/Terraform resources that are causing the long deletion delays or `DependencyViolation` errors.

**Comment by jlforester** [comment] 2020-01-13 15:36
https://github.com/aws/amazon-vpc-cni-k8s/issues/608#issuecomment-571938279

**Comment by def324** [comment] 2020-02-15 07:54
I'm having the same issue as the OP when trying to change the availability zone of a subnet. Terraform wanted to update the auto scaling group in place, instead of destroying and recreating it. This made the subnet deletion fail as the subnet still had resources in it. There seems to be similar behavior for load balancers and RDS instances which terraform also wants to update in place.

I ended up destroying pretty much the entire infrastructure and recreating from scratch, that was the only workaround I could find.

**Comment by forwardmeasure** [comment] 2020-03-23 18:41
I have the same issue. In my setup, I create a VPC, an EKS, multiple ASGs, etc. The good thing is that Terraform destroys the ASGs (and EC2 instance which are the costly resources). That bad is that the Internet Gateway, subnets, and network interfaces are left dangling.

I have noticed that they eventually get cleaned up by what is likely a background cleanup job the AWS runs to deallocate dangling resources.

**Comment by syerad** [comment] 2020-04-27 11:14
Same problem for me. In my TF script I'm trying to remove one availability zone and all the resources belonging to it. It's not possible due to the fact, that TF is trying to remove the subnet and this can't be deleted because it still has resources in it. Any Ideas how to solve this problem? Any suggestion despite destroying everything?

**Comment by muditmn5** [comment] 2020-09-23 12:10
I tried with refreshing keys like Access key and Secret key
This help to resolved my issue.

**Comment by domhdp** [comment] 2020-10-16 00:38
For anyone who got here because of Jenkins X on EKS, I had this issue too. The `terraform destroy` was stuck and couldn't delete the subnets or the internet gateway.

I manually deleted the NLB that had been created, and then re-ran the `terraform destroy` and then the project was deleted successfully.

**Comment by justinretzolk** [comment] 2021-12-09 22:48
Hey y'all :wave: Thank you for taking the time to file this issue and the ongoing discussion! Given that there's been a number of AWS provider releases since this was initially filed, can anyone confirm whether you're still experiencing this behavior?

**Comment by Nordle** [comment] 2022-01-19 09:18
I still have this behavior
```
module.network.aws_subnet.publics["eu-west-1c"]: Still destroying... [id=subnet-09cca311d14ed9867, 11m40s elapsed]
module.network.aws_subnet.publics["eu-west-1c"]: Still destroying... [id=subnet-09cca311d14ed9867, 11m50s elapsed]
module.network.aws_subnet.publics["eu-west-1c"]: Still destroying... [id=subnet-09cca311d14ed9867, 12m0s elapsed]
module.network.aws_subnet.publics["eu-west-1c"]: Still destroying... [id=subnet-09cca311d14ed9867, 12m10s elapsed]
```

versions
```
Terraform v1.0.4
on linux_amd64
+ provider registry.terraform.io/datadog/datadog v2.20.0
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.71.0
+ provider registry.terraform.io/hashicorp/external v2.2.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/mongodb/mongodbatlas v0.7.0
```

**Comment by johndanek** [comment] 2023-01-27 23:24
Still a problem for me in 2023:

```
aws_subnet.rds-sub-4: Still destroying... [id=subnet-0110394d48dab67a4, 15m0s elapsed]
aws_subnet.rds-sub-3: Still destroying... [id=subnet-0d59b7b57b38d3b93, 15m0s elapsed]
aws_subnet.rds-sub-2: Still destroying... [id=subnet-0932eeb4d560314aa, 15m0s elapsed]
aws_subnet.rds-sub-6: Still destroying... [id=subnet-03ec4ecc7b434ce08, 15m0s elapsed]
aws_subnet.rds-sub-1: Still destroying... [id=subnet-094d00d45f3a3772e, 15m0s elapsed]
```

**Comment by BVADY** [comment] 2023-02-06 09:25
Still a problem, even via the AWS CLI and Console I'm not able to destroy them. Because the subnets contain one or more network interfaces, and cannot be deleted until those network interfaces have been deleted. And when I want to delete those network interfaces, I get this error:  
The network interfaces can't be deleted, Reason: Network interface is currently in use.

My workaround apply again and then destroy.

**Comment by smarshie** [comment] 2023-03-28 09:06
Same problem for me

**Comment by JafarBadour** [comment] 2023-07-17 01:27
Still have the same issue 
![image](https://github.com/hashicorp/terraform-provider-aws/assets/16943355/cb6eb19a-f92c-49a3-ab4f-f648066d85d8)

**Comment by tdaly61** [comment] 2023-08-28 01:38
Just want to add my voice to this issue, I am seeing similar

**Comment by vitalyrychkov** [comment] 2024-02-09 18:05
Having the same issue. In my case Terraform-created subnets cannot be deleted by Terraform due to AWS-created GuardDuty endpoints

**Comment by gdavison** [comment] 2024-04-10 00:30
Hi everyone,

Thank you to everyone who's participated in this discussion. This issue has become a bit of a grab bag of issues related to deleting a subnet when it has EC2 instances or ENIs attached to it. In essence, a subnet cannot be deleted while it has instances or ENIs attached, either using Terraform or the AWS Console.

@bflad's comment (https://github.com/hashicorp/terraform-provider-aws/issues/9495#issuecomment-563265999) gives good advice on troubleshooting which ENIs are still attached.

Since this issue was opened, we have added special handling code to handle a number of ENI types that are not immediately cleaned up when the associated resource is deleted, including Lambdas, Comprehend, and DMS. There may be others that are now lingering that we're not handling in the provider.

In the originally reported issue, a subnet was in use by the autoscaling group and it was then removed from the configuration. If the subnet had been directly assigned to the ASG instead of being assigned via the data source, Terraform would have been aware of the association and should have handled removal appropriately. Unfortunately, there is no way to address this the way that the OP's configuration was written.

It seems like some of the other commenters are similarly trying to delete only the subnet without first removing the resources attached to the subnet. This won't work in either Terraform or the AWS Console.

For other commenters, we'll need more information so that we can look into the problem that you're having. I'm going to close this issue so that we can focus specifically on individual problems instead of one issue that tries to capture all problems with deleting a subnet.

If you're encountering this problem, please open a new issue. If you'd like, can reference this issue from the new issue to link them together. In your new issue, please include:
* Your Terraform configuration
  * If you're making a change to an existing configuration, either indicate which resources you're removing or include before and after configurations
* A debug log (see https://developer.hashicorp.com/terraform/internals/debugging for instructions)

**Closed by gdavison** 2024-04-10 00:30 UTC
Labels: bug, service/ec2, prioritized
