### ISSUE TITLE
aws_sns_topic_subscription resource produced new value for was present but now absent

### ISSUE THREAD

**Issue by jochen42** [hashicorp/terraform-provider-aws#11737] opened 2020-01-23 16:53 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

$ terraform -v
Terraform v0.12.20
+ provider.aws v2.45.0

### Affected Resource(s)

* aws_sns_topic_subscription

### Terraform Configuration Files

```hcl
resource "aws_sns_topic_subscription" "oncall-topic-subscription" {
  endpoint               = "https://alert.examlpe.com/somehook"
  protocol               = "HTTPS"
  topic_arn              = aws_sns_topic.oncall-topic.arn
  endpoint_auto_confirms = true
}
```

### Expected Behavior

It's happening after upgrade from Terraform 0.11 to 0.12. Since the topic_subscription is already in state, aws and there aren't any changes, the existing subscription should keep unchanged.

### Actual Behavior

Terraform fails with the following message

```
>> #1530018634 Error:
>> #1530018634 Error: Error: Provider produced inconsistent result after apply
>> #1530018634 Error:
>> #1530018634 Error: When applying changes to aws_sns_topic_subscription.oncall-topic-subscription,
>> #1530018634 Error: provider "registry.terraform.io/-/aws" produced an unexpected new value for
>> #1530018634 Error: was present, but now absent.
>> #1530018634 Error:
>> #1530018634 Error: This is a bug in the provider, which should be reported in the provider's own
>> #1530018634 Error: issue tracker.
>> #1530018634 Error:
>> #1530018634 Error: ============================================
>> #1530018634 Error: Base path: terraform/k28s/20_infrastructure:
>> #1530018634 Error: ERROR: Terraform apply failed
>> #1530018634 Error: ============================================
2020/01/23 15:21:48 exit status 1
```

### Steps to Reproduce

1. `terraform apply`

### References

* #11611 
* #10549
* #9987

**Comment by jochen42** [comment] 2020-01-23 16:54
#10473, #10930

**Comment by bshilliam** [comment] 2020-01-25 01:18
Hit the same issue. In my case it looked like it was not hitting this retry logic below when it got "pending confirmation" back initially from AWS. So it would end up failing with the same error message as above.

`if strings.Contains(protocol, "http") && subscriptionHasPendingConfirmation(output.SubscriptionArn) {
...`

And the reason it was skipping this was because I had `protocol = "HTTPS"` in my aws_sns_topic_subscription definition.

I don't know how it worked with all caps in versions < 0.12.  But after changing to `protocol = "https"` the creation and update works fine in Terraform.

I'm thinking there should be a validation of lowercase values for protocol.

**Comment by amarouane-ABDELHAK** [comment] 2020-04-03 16:39
@bshilliam I am having the same problem. Where did you add `subscriptionHasPendingConfirmation` in output.tf file?

**Comment by bshilliam** [comment] 2020-04-03 17:32
@amarouane-ABDELHAK, only change needed was to change from `protocol = "HTTPS" ` to `protocol = "https"` in my tf file.

**Comment by amarouane-ABDELHAK** [comment] 2020-04-03 17:37
Thank you. I have protocol `sqs` and it is already in lowercase. so this function`subscriptionHasPendingConfirmation` is a terraform  internal function?

**Comment by bshilliam** [comment] 2020-04-03 22:00
Yea @amarouane-ABDELHAK that was in the internal logic where I found my scenario wasn't triggering properly because of the uppercase HTTP.

**Comment by MattMcKeithen** [comment] 2020-04-06 17:09
I've also encountered this for SQS and it looks like the response to the subscribe request returns "pending confirmation" 
and we end up with 
'Invalid SNS Subscription, receved a "pending confirmation" ARN'

This can be seen by following the logic beginning here:
https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_sns_topic_subscription.go#L223
and here where it returns nil
https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_sns_topic_subscription.go#L109

It appears that if your protocol is http or https it will check for pending confirmation and retry but not for SQS.  I don't think it would be too difficult to add a bit of retry logic here for SQS as well?

You can easily reproduce this in the console or cli.
<entry>
        <key>PendingConfirmation</key>
        <value>true</value>
</entry>

in my case our endpoint is in another account (not sure if that is adding just enough delay?).

----------------------------
My error:

2020-04-06T16:07:08.624Z [DEBUG] plugin.terraform-provider-aws_v2.53.0_x4: 2020/04/06 16:07:08 [DEBUG] [aws-sdk-go] DEBUG: Response sns/Subscribe Details:
2020-04-06T16:07:08.624Z [DEBUG] plugin.terraform-provider-aws_v2.53.0_x4: ---[ RESPONSE ]--------------------------------------
2020-04-06T16:07:08.624Z [DEBUG] plugin.terraform-provider-aws_v2.53.0_x4: HTTP/1.1 200 OK
2020-04-06T16:07:08.624Z [DEBUG] plugin.terraform-provider-aws_v2.53.0_x4: Connection: close
2020-04-06T16:07:08.624Z [DEBUG] plugin.terraform-provider-aws_v2.53.0_x4: Content-Length: 298
2020-04-06T16:07:08.624Z [DEBUG] plugin.terraform-provider-aws_v2.53.0_x4: Content-Type: text/xml
2020-04-06T16:07:08.624Z [DEBUG] plugin.terraform-provider-aws_v2.53.0_x4: Date: Mon, 06 Apr 2020 16:07:07 GMT
2020-04-06T16:07:08.624Z [DEBUG] plugin.terraform-provider-aws_v2.53.0_x4: X-Amzn-Requestid: f1856eaa-ce61-59e5-87b1-39af9b8d044e
2020-04-06T16:07:08.624Z [DEBUG] plugin.terraform-provider-aws_v2.53.0_x4: 
2020-04-06T16:07:08.624Z [DEBUG] plugin.terraform-provider-aws_v2.53.0_x4: 
2020-04-06T16:07:08.624Z [DEBUG] plugin.terraform-provider-aws_v2.53.0_x4: -----------------------------------------------------
2020-04-06T16:07:08.624Z [DEBUG] plugin.terraform-provider-aws_v2.53.0_x4: 2020/04/06 16:07:08 [DEBUG] [aws-sdk-go] <SubscribeResponse xmlns="http://sns.amazonaws.com/doc/2010-03-31/">
2020-04-06T16:07:08.624Z [DEBUG] plugin.terraform-provider-aws_v2.53.0_x4:   <SubscribeResult>
2020-04-06T16:07:08.624Z [DEBUG] plugin.terraform-provider-aws_v2.53.0_x4:     <SubscriptionArn>pending confirmation</SubscriptionArn>
2020-04-06T16:07:08.624Z [DEBUG] plugin.terraform-provider-aws_v2.53.0_x4:   </SubscribeResult>
2020-04-06T16:07:08.624Z [DEBUG] plugin.terraform-provider-aws_v2.53.0_x4:   <ResponseMetadata>
2020-04-06T16:07:08.624Z [DEBUG] plugin.terraform-provider-aws_v2.53.0_x4:     <RequestId>f1856eaa-ce61-59e5-87b1-39af9b8d044e</RequestId>
2020-04-06T16:07:08.624Z [DEBUG] plugin.terraform-provider-aws_v2.53.0_x4:   </ResponseMetadata>
2020-04-06T16:07:08.624Z [DEBUG] plugin.terraform-provider-aws_v2.53.0_x4: </SubscribeResponse>
2020-04-06T16:07:08.624Z [DEBUG] plugin.terraform-provider-aws_v2.53.0_x4: 2020/04/06 16:07:08 [DEBUG] Finished subscribing to topic arn:aws:sns:REGION:ACCOUNT:TOPIC with subscription arn pending confirmation
2020-04-06T16:07:08.624Z [DEBUG] plugin.terraform-provider-aws_v2.53.0_x4: 2020/04/06 16:07:08 [DEBUG] Created new subscription! pending confirmation
2020-04-06T16:07:08.624Z [DEBUG] plugin.terraform-provider-aws_v2.53.0_x4: 2020/04/06 16:07:08 [WARN] Invalid SNS Subscription, received a "pending confirmation" ARN
2020/04/06 16:07:08 [DEBUG] module.MODULE1.module.MODULE2.module.MODULE3.aws_sns_topic_subscription.SUBSCRIPTION: apply errored, but we're indicating that via the Error pointer rather than returning it: Provider produced inconsistent result after apply: When applying changes to module.MODULE1.module.MODULE2.module.MODULE3.aws_sns_topic_subscription.SUBSCRIPTION, provider "aws" produced an unexpected new value for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
2020/04/06 16:07:08 [TRACE] module.MODULE1.module.MODULE2.module.MODULE3: eval: *terraform.EvalMaybeTainted
2020/04/06 16:07:08 [TRACE] EvalMaybeTainted: module.MODULE1.module.MODULE2.module.MODULE3.aws_sns_topic_subscription.SUBSCRIPTION encountered an error during creation, so it is now marked as tainted
2020/04/06 16:07:08 [ERROR] module.MODULE1.module.MODULE2.module.MODULE3: eval: *terraform.EvalApplyPost, err: Provider produced inconsistent result after apply: When applying changes to module.MODULE1.module.MODULE2.module.MODULE3.aws_sns_topic_subscription.SUBSCRIPTION, provider "aws" produced an unexpected new value for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
2020/04/06 16:07:08 [ERROR] module.MODULE1.module.MODULE2.module.MODULE3: eval: *terraform.EvalSequence, err: Provider produced inconsistent result after apply: When applying changes to module.MODULE1.module.MODULE2.module.MODULE3.aws_sns_topic_subscription.SUBSCRIPTION, provider "aws" produced an unexpected new value for was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own issue tracker.

**Comment by IrmantasM** [comment] 2020-04-21 17:53
Encountered just now:

```
Error: Provider produced inconsistent result after apply

When applying changes to module.cloudwatch-log-metric-filters.module.server-log-filter-metric-blah.aws_cloudwatch_log_metric_filter.custom,
provider "registry.terraform.io/-/aws" produced an unexpected new value for
was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

**Comment by dtns2** [comment] 2020-05-01 15:48
Also encountered same issue when re-attaching IAM policies to an IAM role:
```
Error: Provider produced inconsistent result after apply

When applying changes to
module.iam_role_default.aws_iam_role_policy_attachment.iam_role_policy_attach[3],
provider "registry.terraform.io/-/aws" produced an unexpected new value for
was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

**Comment by cedriclecoz** [comment] 2020-05-20 09:49
+1 for the attaching policy to IAM role.

**Comment by willcampbell433** [comment] 2020-05-20 17:18
Encountering same issue when attaching policies to IAM role:

```
Error: Provider produced inconsistent result after apply
When applying changes to aws_iam_role_policy_attachment.db_ops_policy_attach,
provider "aws" produced an unexpected new value for was present, but now
absent.
This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

**Comment by ychenbioinfo** [comment] 2020-06-12 15:31
Same issue when attaching policies

`Error: Provider produced inconsistent result after apply

When applying changes to
aws_iam_role_policy_attachment.attach-ecs-instance-role[2], provider
"registry.terraform.io/-/aws" produced an unexpected new value for was
present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.`

**Comment by magnetik** [comment] 2020-07-07 09:57
Same issue with provider 2.69.0

**Comment by dsg9321** [comment] 2020-07-14 11:23
Faced similar issue.


Error: Provider produced inconsistent result after apply

When applying changes to aws_s3_bucket_object.principal_policy, provider
"registry.terraform.io/-/aws" produced an unexpected new value for was
present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Terraform version : 0.12.28

**Comment by dsg9321** [comment] 2020-07-14 11:32
Faced similar issue

```
Error: Provider produced inconsistent result after apply

When applying changes to aws_s3_bucket_object.principal_policy, provider
"registry.terraform.io/-/aws" produced an unexpected new value for was
present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

```
Terraform version : 0.12.28

**Comment by kabelak** [comment] 2020-08-18 11:34
Same issue.
Terraform: 0.12.20
AWS: 2.70.0
```
Error: Provider produced inconsistent result after apply
 
When applying changes to
aws_cloudwatch_metric_alarm.webserver_httpd_service[2], provider
"registry.terraform.io/-/aws" produced an unexpected new value for was
present, but now absent.
 
This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

**Comment by gclough** [comment] 2020-09-11 15:09
Same issue, with the latest AWS provider:

```
 - Downloading plugin for provider "aws" (hashicorp/aws) 3.6.0...
```

```
$ terraform --version
Terraform v0.12.28
```

ERROR:
```
 Error: Provider produced inconsistent result after apply
 When applying changes to
 module.postgres-db.aws_cloudwatch_event_rule.auto_minor_version_upgrade[0],
 provider "registry.terraform.io/-/aws" produced an unexpected new value for
 was present, but now absent.
 This is a bug in the provider, which should be reported in the provider's own
 issue tracker.
```

**Comment by sannithibalaji** [comment] 2021-01-13 13:55
faced a similar issue, but when I gave the protocol in a small case (https) it worked fine.

**Comment by ignas-sakalauskas-cko** [comment] 2021-02-23 13:59
Just run into the same issue when trying to create cross-account SQS subscription.

**Closed** 2021-03-30 18:11 UTC
Labels: bug, service/sns
