### ISSUE TITLE
secondary source_version in aws_codebuild project

### ISSUE THREAD

**Issue by LevinDmytro2** [hashicorp/terraform-provider-aws#13788] opened 2020-06-17 10:54 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.24

aws provider 2.66
### Affected Resource(s)

* aws_codebuild_project

### Terraform Configuration Files

```hcl

  secondary_sources {
    type              = "BITBUCKET"
    source_identifier = "qa"
    location          = "https://xxxxxx.git"
    git_clone_depth   = 0
    source_version = "refs/heads/master"

  }
```

### Expected Behavior
Adding source version to secondary source version

### Actual Behavior
An argument named "source_version" is not expected here.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The AWS interface has a field that cannot be filled by terraform code when a secondary source is selected

### References

* #0000

**Comment by Wiickette** [comment] 2021-03-06 05:44
Any news here? Having to do this manually really isn't great.

**Comment by zhujik** [comment] 2021-03-26 07:29
Yeah this seems to be easy to add, the aws cli supports setting the source version for secondary sources: https://docs.aws.amazon.com/cli/latest/reference/codebuild/create-project.html

**Comment by DrFaust92** [comment] 2021-04-29 22:07
duplicate of #13241

**Closed by DrFaust92** 2021-04-29 22:07 UTC
Labels: enhancement, service/codebuild
