### ISSUE TITLE
Can't set aws_ssm_maintenance_window_task without target

### ISSUE THREAD

**Issue by stivi21** [hashicorp/terraform-provider-aws#20673] opened 2021-08-24 14:50 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.31
+ provider.aws v3.55.0

### Affected Resource(s)

* aws_ssm_maintenance_window_task

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_ssm_maintenance_window_task" "start" {
  window_id        = <maintenance window created before>
  name             = "StartInfo"
  task_type        = "AUTOMATION"
  task_arn         = "AWS-PublishSNSNotification"
  priority         = 1
  service_role_arn = "arn:aws:iam::<client nr>:role/aws-service-role/ssm.amazonaws.com/AWSServiceRoleForAmazonSSM"

  max_concurrency = "1"
  max_errors      = "0"
}
```

### Panic Output

**Output from the configuration shown above:**

```
aws_ssm_maintenance_window_task.start: Creating...

Error: ValidationException: Maintenance window tasks without targets do not support MaxErrors values. Maintenance window tasks without targets do not support MaxConcurrency values.
        status code: 400, request id: eca7ec60-98e4-4b3f-b024-de9cc809c0e7

  on ssm.tf line 1, in resource "aws_ssm_maintenance_window_task" "start":
   1: resource "aws_ssm_maintenance_window_task" "start" {

```
**If I will delete _max_concurrency_ and _max_errors_ parameters from configuration, the error is:**

```
Error: Missing required argument

  on ssm.tf line 1, in resource "aws_ssm_maintenance_window_task" "start":
   1: resource "aws_ssm_maintenance_window_task" "start" {

The argument "max_concurrency" is required, but no definition was found.

Error: Missing required argument

  on ssm.tf line 1, in resource "aws_ssm_maintenance_window_task" "start":
   1: resource "aws_ssm_maintenance_window_task" "start" {

The argument "max_errors" is required, but no definition was found.
```

### Expected Behavior

Should create maintenance window task without any targets (option: "Task target not required").
This feature was added [here](https://github.com/hashicorp/terraform-provider-aws/commit/596aa3dfc3867a880dea48d52e8802e3a3d11164#diff-73d29f064f84efa3e4b4d70d218de54ac433ec4416067d89b4670d5d699d1629), but I think enough to change from _Required_ to _Optional_ for _max_concurrency_ and _max_errors_ options.

### Actual Behavior

Terraform ending with above errors.

### Steps to Reproduce

1. `terraform apply`

**Comment by DrFaust92** [comment] 2022-03-18 20:07
duplicate of https://github.com/hashicorp/terraform-provider-aws/issues/20090

**Closed by DrFaust92** 2022-03-18 20:07 UTC
Labels: bug, service/ssm
