### ISSUE TITLE
aws_mwaa_environment missing Scheduler count option

### ISSUE THREAD

**Issue by ramarthuluru** [hashicorp/terraform-provider-aws#22704] opened 2022-01-21 02:24 UTC
aws_mwaa_environment resource is missing **Scheduler count** option for **Environment class** section. It is using the default value of 2.

**Comment by wedge-jarrad** [comment] 2022-02-13 19:50
Duplicate of #20185.

**Comment by DrFaust92** [comment] 2022-02-13 21:19
Duplicate of https://github.com/hashicorp/terraform-provider-aws/issues/20185.

**Closed by DrFaust92** 2022-02-13 21:19 UTC
Labels: enhancement, service/mwaa
