### ISSUE TITLE
No visible certificate on AWS console after aws_acmpca_certificate creation

### ISSUE THREAD

**Issue by rmasclef** [hashicorp/terraform-provider-aws#21089] opened 2021-09-29 21:37 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
terraform -v
Terraform v1.0.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.60.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
```

### Affected Resource(s)

* aws_acmpca_certificate

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
  required_version = "~> v1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
  }
}

provider "aws" {
  default_tags {
    tags = {
      CreatedBy   = "rmasclef"
      Scope       = "test-cert-generation"
    }
  }
}

resource "aws_acmpca_certificate_authority" "example" {
  certificate_authority_configuration {
    key_algorithm     = "RSA_4096"
    signing_algorithm = "SHA512WITHRSA"

    subject {
      common_name = "example.com"
    }
  }

  permanent_deletion_time_in_days = 7
}

resource "aws_acmpca_certificate" "example" {
  certificate_authority_arn   = aws_acmpca_certificate_authority.example.arn
  certificate_signing_request = tls_cert_request.csr.cert_request_pem
  signing_algorithm           = "SHA512WITHRSA"
  validity {
    type  = "YEARS"
    value = 1
  }
}

resource "tls_private_key" "key" {
  algorithm = "RSA"
}

resource "tls_cert_request" "csr" {
  key_algorithm   = "RSA"
  private_key_pem = tls_private_key.key.private_key_pem
#  dns_names = [
#    "test.example.com"
#  ]

  subject {
    common_name = "example"
  }
}

```

### Expected Behavior

If the certificate creation succeeded, I should see the certificate in AWS console (Certificate-Manager service).

### Actual Behavior

The certificate is created, I can see the ARN and every other information in the outputs of terraform but I can't actually see the certificate on the AWS Console.

Impact : When we want to create an HTTPS ALB using `terraform-aws-modules/alb/aws` (~> v6.0), we can only pass certificate **arns**, if we pass the ARN of a cert generated by terraform, we end up with the following error :
```
Error: error creating ELBv2 Listener (arn:aws:elasticloadbalancing:eu-west-1:<ACCOUNT_ID>:loadbalancer/net/<LB_NAME>/32114fa74441983e): CertificateNotFound: Certificate 'arn:aws:acm-pca:eu-west-1:<ACCOUNT_ID>:certificate-authority/<PCA_ID>/certificate/<CERT_ID>' not found status code: 400, request id: ...
```

### Steps to Reproduce

1. launch a `terraform apply`
2. go to https://eu-west-1.console.aws.amazon.com/acm/home?region=eu-west-1
3. see that no private cert is present on the page 👍 

### References

I did not find any related issue on that subject, maybe I'm misinterpreting something 🤷‍♂️ 

> NB : if I try to issue a private cert using the PCA created by tf, the issued cert is visible on cert-manager ...

Thanks a lot for your work and your help !

**Comment by rmasclef** [comment] 2021-09-29 21:47
Note : I did not check the behavior of the AWS API on this case.

**Comment by justinretzolk** [comment] 2021-09-30 18:09
Hey @rmasclef 👋 Thank you for taking the time to file this issue, and for supplying the full reproduction configuration - that helps immensely!

I attempted to reproduce using the configuration you provided, but found that I couldn't reproduce the issue. After running the `terraform apply`, it looks like it worked and created the resources at:

```
https://$REGION.console.aws.amazon.com/acm-pca/home?region=$REGION
```

The difference that I noted was that the path included `acm-pca` rather than `acm`. Can you check to see if you're seeing the same?

**Note:** There was an issue with my Terraform run where a certificate was not issued by the CA because it was "not in a valid state for issuing certificates", but that caused the Terraform run to error out; something you didn't mention, so I assume that's based on needing some extra configuration on my end that I didn't bother to try to track down yet.

**Comment by rmasclef** [comment] 2021-09-30 19:48
I’m gonna check again.

About the pca not being in the valid state : yes that’s my bad, I forgot to say that I installed a Cert for the PCA manually (using aws console) so that it can go to “active” state 🤓

if I still reproduce I’m gonna make a little video to show you what I do and see if I do something wrong

**Comment by rmasclef** [comment] 2021-09-30 22:04
OK so I've re-checked and when typing `https://$REGION.console.aws.amazon.com/acm-pca/home?region=$REGION` you reach the private-certificate **authority**, so not the list of the private-certs that have been issued by this PCA 👍 (I don't if it's clear 😬)

I'm gonna take some screenshot of what I'm expecting to see after the terraform apply 👍

**Comment by justinretzolk** [comment] 2021-09-30 22:09
Hey @rmasclef, thanks for the update! Apologies for that URL mishap - since my apply never finished, I never actually had certificates issued and I didn't catch the difference in where we were looking 😅.

**Comment by rmasclef** [comment] 2021-09-30 22:14
No worries, if you want to get the certificate issued you need to create a certificate for the CA itself 👍 to do so, you can go to ACM PCA on the AWS Console, select the PCA, go to `actions` and then click on `install CA certificate` 😄 

I can update the tf code to generate a self-signed cert for the pca if it helps 🤷

**Comment by rmasclef** [comment] 2021-09-30 22:29
regarding the screenshots, here we go 🏃 

1️⃣ I created the PCA with terraform (and installed a Cert on it in order for it to be in `active` state

<img width="1680" alt="Screenshot 2021-10-01 at 00 05 13" src="https://user-images.githubusercontent.com/11849873/135537183-712dc49c-7f80-4394-87bc-50efd65348d7.png">

2️⃣ I can now use the PCA to issue a certificate using the AWS console

<img width="1680" alt="Screenshot 2021-10-01 at 00 05 28" src="https://user-images.githubusercontent.com/11849873/135537372-f26af22a-153b-4087-af3d-82a269fccd95.png">

<img width="1680" alt="Screenshot 2021-10-01 at 00 05 34" src="https://user-images.githubusercontent.com/11849873/135537455-f0d2033b-bc73-498e-958e-88f86ffae1e9.png">

<img width="1680" alt="Screenshot 2021-10-01 at 00 05 40" src="https://user-images.githubusercontent.com/11849873/135537621-95ba0431-bee4-423a-85c7-c11d54cebc90.png">

<img width="1680" alt="Screenshot 2021-10-01 at 00 06 29" src="https://user-images.githubusercontent.com/11849873/135537742-18ad4a45-749d-4adb-8fdf-b942f556753e.png">

<img width="1680" alt="Screenshot 2021-10-01 at 00 06 45" src="https://user-images.githubusercontent.com/11849873/135537839-6ffbedce-80e9-4ed7-8121-39adfa6b5c51.png">

3️⃣ I can now **see** the **private-cert** in AWS Console CertificateManager service page

<img width="1680" alt="Screenshot 2021-10-01 at 00 07 25" src="https://user-images.githubusercontent.com/11849873/135538094-fd81f67a-1f20-4d89-9e6d-f7984ab90862.png">

> Notice the superb work on bluring the IDs 😂 (I didn't get the courage to open photoshop sorry).

---

So what we can see is that creating a Private certificate using my PCA is possible through AWS Console and ends up with a private-certificate that can be seen on ACM Certificate manager page 👍 

What I'm expecting is that my private-cert created with terraform ends up the same way ... which is not the case at this time ... which means the private-cert is not really created 🤷

**Comment by justinretzolk** [comment] 2021-10-01 18:35
Thank you for providing the additional details! I've gone ahead and marked this as a bug so that the team can take a look into this as time permits.

**Comment by mikemorency-sn** [comment] 2022-03-01 03:45
FWIW im also seeing this, but using slightly different versions
`
terraform {
    backend "s3" {}

    required_version = "~> 1.1"

    required_providers {
        aws = {
            source  = "hashicorp/aws"
            version = "~> 4.0"
        }
    }
}
`

**Comment by tomiszili** [comment] 2022-03-07 10:32
Hello!

Any update on this? How to issue a private certificate into an active ACM-PCA properly with terraform?

**Comment by justinretzolk** [comment] 2022-04-06 23:05
Hey @tomiszili 👋 Thank you for checking in on this. Unfortunately, I'm not able to provide an estimate on when this will be looked into due to the potential of shifting priorities (we prioritize work by count of ":+1:" reactions, as well as a few other things). A larger prioritization document is in the works, but in the meantime additional information may be found in our [issue lifecycle document](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/issue-reporting-and-lifecycle.md#issue-lifecycle).

**Comment by NiccoloGiulianelli** [comment] 2022-09-09 14:57
Hey @tomiszili certificates are actually created, but you can't see them on the console or list them using the CLI as there is no equivalent to list-certifcates for AWS private CA. If you run this command:

aws acm-pca get-certificate \
      --certificate-arn arn:aws:acm-pca:region:account:certificate-authority/CA_ID/certificate/certificate_ID \
      --certificate-authority-arn arn:aws:acm-pca:region:account:certificate-authority/CA_ID | \
      jq -r '.Certificate, .CertificateChain'

You can retrieve the certificate

**Comment by david-freistrom** [comment] 2022-09-12 08:58
Hey @NiccoloGiulianelli,

good to know it is created but I cannot reference it at an aws_lb_listener resources using certificate_arn.

`Error: error creating ELBv2 Listener (arn:aws:elasticloadbalancing:eu-west-1:952141670073:loadbalancer/app/itsm-staging-helix-private/92fc010232eda45f): CertificateNotFound: Certificate 'arn:aws:acm-pca:eu-west-1:952141670073:certificate-authority/759aabab-ff5c-46e4-9c9e-f7c3301927c5/certificate/3441bce3bc7c54f97b0f42fb4d5da196' not found`

**Comment by thi-baut** [comment] 2023-06-21 19:51
Hey any news on this? 

I'm creating a private certificate exactly like in this threat (to use it on a private ALB) ; the certificate appears on the PCA Audit Report (= seems created) and aws acm-pca get-certificate allows me to see it's there. I can't see it in the Console. Also Terraform cannot use it with the ALB during its creation (400 / CertificateNotFound). 

Is there a workaround outside of manually creating the private certs and importing them in my code?

**Comment by thi-baut** [comment] 2023-06-22 19:36
Turns out it's not a bug, it's a feature. Certs issued by AWS ACM PCA cannot be association with load balancers and internet-facing AWS services - see https://docs.aws.amazon.com/privateca/latest/userguide/PcaIssueCert.html 

They are also not visible in ACM Console if issued by AWS ACM PCA and the [IssueCertificate](https://docs.aws.amazon.com/privateca/latest/APIReference/API_IssueCertificate.html)) API endpoint

We have to use ACM to issue private certificate for Console usage and ALB association. 

This thread can be closed.

**Closed** 2023-06-26 19:16 UTC
Labels: bug, service/acmpca
