### ISSUE TITLE
Support for SES Email feedback forwarding configuration

### ISSUE THREAD

**Issue by faisalp4p** [hashicorp/terraform-provider-aws#14622] opened 2020-08-13 12:10 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is a configuration about Email feedback forwarding for SES. Currently it is not supported in any of the SES resources. people have to manually do it from the aws console.
![ses_notif_config](https://user-images.githubusercontent.com/3133205/90131574-fc37e100-dd89-11ea-812f-cf4bc99e4e1f.png)

There is a challenge to decide how we can support this configuration in TF. I can think of two options:

1. Make a boolean parameter in `aws_ses_domain_identity` and `aws_ses_email_identity`. Adding a parameter to identity resource itself for notification configuration will be confusing to the users. 
2. Create a dedicated resource called `aws_ses_identity_feedback_forwarding_enabled`. Having a dedicated resource for a simple configuration might be an overkill.

Given both solutions are not perfect I would vote for 2 as it will not touch any existing resources. 

I wanted to get some feedbacks on this. Thanks!

**Comment by kp-autorola** [comment] 2020-08-28 07:23
Duplicate of https://github.com/terraform-providers/terraform-provider-aws/issues/4182

**Comment by djravine** [comment] 2020-10-13 00:34
Vote 2

As with the existing resource `aws_ses_identity_notification_topic` you need to create the `aws_ses_configuration_set` first then reference it in the new resource.

`# SES - Configuration Set
resource "aws_ses_configuration_set" "ses" {
  name = "ses-config"
}

# SES - Event Destination
resource "aws_ses_event_destination" "sns" {
  name                   = "ses-event-sns"
  configuration_set_name = aws_ses_configuration_set.ses.name
  enabled                = true
  matching_types         = ["send", "reject", "bounce", "complaint", "delivery", "open", "click", "renderingFailure"]
  sns_destination {
    topic_arn = aws_sns_topic.events.arn
  }
}

# SES - Event Destination
resource "aws_ses_identity_feedback_forwarding_enabled" "ses" {
  configuration_set_name = aws_ses_configuration_set.ses.name
  enabled                = true
}`

**Comment by yuonoda** [comment] 2020-12-23 02:47
I'm facing this issue now.
Not to send auto-reply to FROM address, I need to turn off feedback forwarding manually.

Suggestion by @djravine really make sense for me.

**Comment by yuonoda** [comment] 2020-12-23 13:11
I opened the draft pull request for this issue.
Because this is my first PR for this repo, I'm welcome for everyone's help.
#16891

**Comment by tmegow** [comment] 2021-08-24 16:22
What's the status on this new resource? I need to disable feedback forwarding.

**Closed** 2022-11-01 15:52 UTC
Labels: enhancement, new-resource, service/ses
