### ISSUE TITLE
[Bug]: Terraform - aws_dynamodb_table resource deletion_protection_enabled option not working

### ISSUE THREAD

**Issue by Dotisandhyarani** [hashicorp/terraform-provider-aws#39617] opened 2024-10-07 21:20 UTC
### Terraform Core Version

1.5.5

### AWS Provider Version

2.15.18 

### Expected Behavior

Should enable the `deletion_protection_enabled` for the `aws_dynamodb_table`

### Actual Behavior

Throws error as unsupported argument
```

│ Error: Unsupported argument
│ 
│   on .terraform/modules/sd_test_table/aws/dynamodb/tables.tf line 11, in resource "aws_dynamodb_table" "dynamo_table":
│   11:   deletion_protection_enabled = var.deletion_protection_enabled
│ 
│ An argument named "deletion_protection_enabled" is not expected here.

```

### Terraform Configuration Files

resource "aws_dynamodb_table" "dynamo_table" {

  name         = var.table_name
  hash_key     = var.hash.key
  range_key    = var.range != null ? var.range.key : null
  billing_mode = var.billing_mode
  deletion_protection_enabled = true
  attribute {
    name = var.hash.key
    type = var.hash.type
  }
}

### Steps to Reproduce

`terraform apply -target aws_dynamodb_table.dynamo_table`

### Would you like to implement a fix?

None

**Comment by stefanfreitag** [comment] 2024-10-09 19:24
Good evening @Dotisandhyarani!

Thank you for taking your time to report the issue. 

Based on your description there seems to be an unsupported argument `deletion_protection_enabled`  for the resource `aws_dynamodb_table` when using the AWS provider version 2.15.18.

I had a look into the release history and change logs for the AWS provider. Actually the argument was added in release v4.59.0. [This link](https://github.com/hashicorp/terraform-provider-aws/releases/tag/v4.59.0) forwards you to the changelog. In the _Enhancements_ section you will find

> resource/aws_dynamodb_table: Add deletion_protection_enabled argument (https://github.com/hashicorp/terraform-provider-aws/issues/29924)

In addition, the [documentation for v4.59.0](https://registry.terraform.io/providers/hashicorp/aws/4.59.0/docs/resources/dynamodb_table) also lists the argument.

Hence, I would kindly ask you to upgrade your provider this least 4.59.0 and give it a try.

**Comment by justinretzolk** [comment] 2024-10-14 18:31
Hey @Dotisandhyarani 👋 Thank you for taking the time to raise this, and thank you to Stefan for catching the version requirement! 

@Dotisandhyarani were you able to test with at least version `4.59.0` to validate that it resolves your issues?

**Comment by Dotisandhyarani** [comment] 2024-10-15 22:22
@justinretzolk I haven't tested it yet, but we might upgrade our AWS provider later. I'll update the issue once I've had a chance to test it.

**Comment by Dotisandhyarani** [comment] 2024-10-16 17:29
**UPDATE**

Tried with below terraform and aws provider version constraint

`
terraform {
  required_version = "1.5.5"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.50.0, < 5.0.0"
    }
  }
}`


but still same issue

`╷
│ Error: Unsupported argument
│ 
│   on .terraform/modules/sd_test_table/aws/dynamodb/tables.tf line 11, in resource "aws_dynamodb_table" "dynamo_table":
│   11:   deletion_protection_enabled = var.deletion_protection_enabled
│ 
│ An argument named "deletion_protection_enabled" is not expected here.
`

Am I missing anything ?

**Comment by stefanfreitag** [comment] 2024-10-16 18:50
Good evening @Dotisandhyarani 
thanks for taking your time for testing the recommendation!

Could you please review the AWS provider version you use? Required is v4.59.0 and in your code it is v4.50.0.
Here it the updated code snippet:

```hcl
aws = {
      source  = "hashicorp/aws"
      version = "~> 4.59.0, < 5.0.0"
    }
```


I tested with below code snippet

```hcl
resource "aws_dynamodb_table" "dynamo_table" {
  name = "dynamo_table"
  hash_key = "id"
  billing_mode = "PAY_PER_REQUEST"
  deletion_protection_enabled = true
  attribute {
    name = "id"
   type = "S"
 }
}
```

and this is the output using v4.59.0

```shell
stefan@stefan-IdeaPad-5-Pro-16ACH6:~/temp$ terraform init
Initializing the backend...
Initializing provider plugins...
- Reusing previous version of hashicorp/aws from the dependency lock file
- Using previously-installed hashicorp/aws v4.59.0

Terraform has been successfully initialized!
[...]
stefan@stefan-IdeaPad-5-Pro-16ACH6:~/temp$ terraform plan

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_dynamodb_table.dynamo_table will be created
  + resource "aws_dynamodb_table" "dynamo_table" {
      + arn                         = (known after apply)
      + billing_mode                = "PAY_PER_REQUEST"
      + deletion_protection_enabled = true
      + hash_key                    = "id"
      + id                          = (known after apply)
      + name                        = "dynamo_table"
      + read_capacity               = (known after apply)
      + stream_arn                  = (known after apply)
      + stream_label                = (known after apply)
      + stream_view_type            = (known after apply)
      + tags_all                    = (known after apply)
      + write_capacity              = (known after apply)
      + attribute {
          + name = "id"
          + type = "S"
        }
      + point_in_time_recovery (known after apply)
      + server_side_encryption (known after apply)
      + ttl (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

The same code snippet used with provider v4.50.0 would give an error during plan phase

```shell
stefan@stefan-IdeaPad-5-Pro-16ACH6:~/temp$ terraform plan
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 29, in resource "aws_dynamodb_table" "dynamo_table":
│   29: deletion_protection_enabled = true
│ 
│ An argument named "deletion_protection_enabled" is not expected here.
```

Hope that helps. If not, please let me know!

**Comment by Dotisandhyarani** [comment] 2024-10-16 19:27
yes, that's working. Thanks!

But just curious, the version constraint ~> 4.50.0, < 5.0.0 in Terraform allows versions in the 4.x series, starting from 4.50.0 up to, but not including, 5.0.0. This means it will match all versions between 4.50.0 and 4.59.x (including 4.59.0) right ?

**Comment by justinretzolk** [comment] 2024-10-16 19:40
Hey @Dotisandhyarani :wave: Glad to hear you were able to get past this! 

When using the `~>` for version constraints, only the rightmost number is iterated, so `~> 4.50.0` would only iterate the `0`. To get any version in the `4.x` series, you'd need to use `~> 4.50`

Since we've confirmed this isn't a bug, I'm going to close this issue. If you run into unexpected behavior in the future, please do let us know!

**Comment by stefanfreitag** [comment] 2024-10-16 19:40
The ~> is explained [here](https://developer.hashicorp.com/terraform/language/expressions/version-constraints). Let me quote:

> [~>](https://developer.hashicorp.com/terraform/language/expressions/version-constraints#-3): Allows only the rightmost version component to increment. This format is referred to as the pessimistic constraint operator. For example, to allow new patch releases within a specific minor release, use the full version number:

> [~> 1.0.4](https://developer.hashicorp.com/terraform/language/expressions/version-constraints#1-0-4): Allows Terraform to install 1.0.5 and 1.0.10 but not 1.1.0.
> [~> 1.1](https://developer.hashicorp.com/terraform/language/expressions/version-constraints#1-1): Allows Terraform to install 1.2 and 1.10 but not 2.0.

In your case of `~>4.50.0` it would allow onlypatch level upgrades, e.g. 4.50.1.

Here you can see the difference between `~>4.50`  (top) and `~>4.50.0` (bottom) 
```shell
Initializing the backend...
Initializing provider plugins...
- Finding hashicorp/aws versions matching "~> 4.50, < 5.0.0"...
- Installing hashicorp/aws v4.67.0...
- Installed hashicorp/aws v4.67.0 (signed by HashiCorp)
```

```shell
stefan@stefan-IdeaPad-5-Pro-16ACH6:~/temp$ terraform init -upgrade
Initializing the backend...
Initializing provider plugins...
- Finding hashicorp/aws versions matching "~> 4.50.0, < 5.0.0"...
- Installing hashicorp/aws v4.50.0...
- Installed hashicorp/aws v4.50.0 (signed by HashiCorp)
```

**Closed** 2024-10-16 19:40 UTC
Labels: bug, service/dynamodb, needs-triage
