### ISSUE TITLE
[Bug]: `aws_iam_user_login_profile` gets replaced if `password_reset_required` is true, user changed their password, and stack got refreshed

### ISSUE THREAD

**Issue by rafalkrupinski** [hashicorp/terraform-provider-aws#36654] opened 2024-03-29 16:06 UTC
### Terraform Core Version

pulumi 3.111.1

### AWS Provider Version

5.42.0

### Affected Resource(s)

aws_iam_user_login_profile

### Expected Behavior

When creating a login profile with `password_reset_required` = true, the user profile should allow that value to be false on AWS the resource was created. That property changes when user changes their password.

### Actual Behavior

application tries to replace `aws_iam_user_login_profile` which fails, as it first tries to create a new one, and AWS doesn't allow two instances for one user.

### Terraform Configuration Files

Please see pulumi-aws issue pulumi/pulumi-aws#3750 for pulumi code.

### Steps to Reproduce

1. create user with profile and required password change
2. login as the new user and change password
3. refresh stack
4. synchronize stack

### Important Factoids

Documentation on aws_iam_user_login_profile.password_reset_required states it 'Only applies on resource creation.' This seems reasonable, but the code doesn't behave this way.

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment] 2024-04-01 17:06
Duplicate of #23567

**Closed by justinretzolk** 2024-04-01 17:06 UTC
Labels: bug, service/iam
