### ISSUE TITLE
Add iot thing group resource

### ISSUE THREAD

**Issue by oleksiyVeretiuk** [hashicorp/terraform-provider-aws#10630] opened 2019-10-25 09:37 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
We are faced with the problem of the lack of availability of several resources related to IoT services, namely IoT Thing Group. Therefore, we suggest adding an IoT Thing Group resource.

### New or Affected Resource(s)

* aws_iot_thing_group

### Potential Terraform Configuration

```hcl
resource "aws_iot_thing_group" "group" {
  name = "thing_group"

  properties {
    description = "test description"
    attributes = {
        "attr1": "val1",
        "attr2": "val2",
    }
    merge = false 
  }
}
```

**Comment by jamescrowley** [comment] 2020-04-30 12:53
Just flagging there's a duplicate here: https://github.com/terraform-providers/terraform-provider-aws/issues/8801 also with an open PR. Would be fab if *one* of these could get some attention from the maintainers. Happy to contribute if useful.

**Comment by ewbankkit** [comment] 2021-11-16 18:53
Closing as a duplicate of #8801.
Policy attachment will be available via the `aws_iot_policy_attachment` resource.

**Closed by ewbankkit** 2021-11-16 18:53 UTC
Labels: enhancement, service/iot

**Comment by joshfriend** [comment] 2022-02-22 18:25
@ewbankkit The docs for `aws_iot_policy_attachment` do not adequately convey that this is possible.

> [target](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/iot_policy_attachment#target) - (Required) The identity to which the policy is attached.

does not indicate what types of resources that `target` may point at.
