### ISSUE TITLE
[Bug]: default_tags ignored when using alias in provider configuration

### ISSUE THREAD

**Issue by stavbernazport** [hashicorp/terraform-provider-aws#34545] opened 2023-11-23 14:52 UTC
### Terraform Core Version

1.5.7

### AWS Provider Version

4.67.0

### Affected Resource(s)

aws_*

### Expected Behavior

Provider default_tags configuration should not be ignored when using alias

### Actual Behavior

When configuring the provider with `alias` it ignores `default_tags` completely 

### Relevant Error/Panic Output Snippet

```shell
#terraform plan output without alias:

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_vpc.test will be created
  + resource "aws_vpc" "test" {
      + arn                                  = (known after apply)
      + cidr_block                           = "192.168.1.0/24"
      + default_network_acl_id               = (known after apply)
      + default_route_table_id               = (known after apply)
      + default_security_group_id            = (known after apply)
      + dhcp_options_id                      = (known after apply)
      + enable_classiclink                   = (known after apply)
      + enable_classiclink_dns_support       = (known after apply)
      + enable_dns_hostnames                 = true
      + enable_dns_support                   = true
      + enable_network_address_usage_metrics = (known after apply)
      + id                                   = (known after apply)
      + instance_tenancy                     = "default"
      + ipv6_association_id                  = (known after apply)
      + ipv6_cidr_block                      = (known after apply)
      + ipv6_cidr_block_network_border_group = (known after apply)
      + main_route_table_id                  = (known after apply)
      + owner_id                             = (known after apply)
      + tags                                 = {
          + "Name" = "test"
        }
      + tags_all                             = {
          + "Name"        = "test"
          + "environment" = "stg"
          + "terraform"   = "true"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.




#terraform plan output with alias:

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_vpc.test will be created
  + resource "aws_vpc" "test" {
      + arn                                  = (known after apply)
      + cidr_block                           = "192.168.1.0/24"
      + default_network_acl_id               = (known after apply)
      + default_route_table_id               = (known after apply)
      + default_security_group_id            = (known after apply)
      + dhcp_options_id                      = (known after apply)
      + enable_classiclink                   = (known after apply)
      + enable_classiclink_dns_support       = (known after apply)
      + enable_dns_hostnames                 = true
      + enable_dns_support                   = true
      + enable_network_address_usage_metrics = (known after apply)
      + id                                   = (known after apply)
      + instance_tenancy                     = "default"
      + ipv6_association_id                  = (known after apply)
      + ipv6_cidr_block                      = (known after apply)
      + ipv6_cidr_block_network_border_group = (known after apply)
      + main_route_table_id                  = (known after apply)
      + owner_id                             = (known after apply)
      + tags                                 = {
          + "Name" = "test"
        }
      + tags_all                             = {
          + "Name" = "test"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

### Terraform Configuration Files

```
#main.tf without alias:

provider "aws" {
  region  = "us-west-2"
  default_tags {
    tags = {
      terraform   = "true"
      environment = "stg"
    }
  }
}

terraform {
  required_providers {
    aws = {
         source  = "hashicorp/aws"
         version = "4.67.0"
       }
  }
}

resource "aws_vpc" "test" {
  cidr_block           = "192.168.1.0/24"
  enable_dns_hostnames = true
  enable_dns_support   = true
  tags = {
    Name = "test"
  }
}
```

```
#main.tf file with alias:

provider "aws" {
  region  = "us-west-2"
  alias   = "uswest2"
  default_tags {
    tags = {
      terraform   = "true"
      environment = "stg"
    }
  }
}

terraform {
  required_providers {
    aws = {
         source  = "hashicorp/aws"
         version = "4.67.0"
       }
  }
}

resource "aws_vpc" "test" {
  cidr_block           = "192.168.1.0/24"
  enable_dns_hostnames = true
  enable_dns_support   = true
  tags = {
    Name = "test"
  }
}
```

### Steps to Reproduce

terraform init
terraform plan
tags are not being propagated

### Important Factoids

An existing workaround would be to add `provider` to each resource and then the tags are being propagated.

The problem is when you have a very large terraform module, that's very annoying and useless.

### Would you like to implement a fix?

None

**Comment by jrkarnes** [comment] 2023-12-08 15:53
I would like to add that the problem happens even when you use an un-aliased structure to try and push the default_tags down as shown here:

```hcl
provider "aws" {
  default_tags {
    tags = {
      (local.ci_id_tag_name) = (local.ci_id_tag_value)
    }
  }
}

provider "aws" {
  alias  = "us-east-1"
  region = "us-east-1"

  ignore_tags {
    key_prefixes = ["catalog:"]
  }
}

provider "aws" {
  alias  = "us-west-2"
  region = "us-west-2"

  ignore_tags {
    key_prefixes = [catalog:", "consumer:"]
  }
}
```

Tried this to get around the `alias` problem and it also fails.

**Comment by justinretzolk** [comment] 2024-08-20 16:49
Hey @stavbernazport 👋 I took another look at this and noticed what's causing the behavior you noticed. In your example for with the alias, your `aws_vpc` resource doesn't have a `provider` argument, so it's [using the default configuration of the provider](https://developer.hashicorp.com/terraform/language/providers/configuration#selecting-alternate-provider-configurations) rather than your aliased one. Since the default configuration isn't explicitly declared, the `default_tags` you're setting for the aliased version of the provider will not be used.

As far as the other issue noted in the most recent comment, please see my comment [here](https://github.com/hashicorp/terraform-provider-aws/issues/30902#issuecomment-1522160649) for a bit more background on why that error occurs in that scenario.

Since this seems to be a matter of adjusting configurations slightly, and not something that the provider team will need to address further, I'm going to close this issue. If you come across unexpected behavior in the future, please do let us know!

**Closed by justinretzolk** 2024-08-20 16:49 UTC
Labels: bug, provider, tags, service/vpc
