### ISSUE TITLE
[Bug]: AWS FSx Subnet issue - non windows

### ISSUE THREAD

**Issue by omerlh** [hashicorp/terraform-provider-aws#39462] opened 2024-09-24 07:29 UTC
### Terraform Core Version

v1.5.7

### AWS Provider Version

5.65.0

### Affected Resource(s)

* aws_fsx_lustre_file_system

### Expected Behavior

Filesystem created with multiple subnets

### Actual Behavior

Getting an error:
```
Attribute subnet_ids supports 1 item maximum, but config has 3 declared.
```

This is expected given this [code](https://github.com/hashicorp/terraform-provider-aws/blob/e6438dde0755e4eb4898551097413e919a5f21b9/internal/service/fsx/lustre_file_system.go#L292)

Very similar to this issue: #12601

### Terraform Configuration Files

```
{
      "//": {
        "metadata": {
          "path": "main/default",
          "uniqueId": "default"
        }
      },
      "automatic_backup_retention_days": 0,
      "data_compression_type": "LZ4",
      "deployment_type": "PERSISTENT_2",
      "file_system_type_version": "2.15",
      "log_configuration": {
        "level": "ERROR_ONLY"
      },
      "metadata_configuration": {
        "iops": 1500,
        "mode": "USER_PROVISIONED"
      },
      "name": "default-fs",
      "per_unit_storage_throughput": 250,
      "root_squash_configuration": {
        "root_squash": "365534:65534"
      },
      "security_group_egress_rules": {
        "out": {
          "cidr_ipv4": "0.0.0.0/0",
          "description": "Allow all traffic",
          "ip_protocol": -1
        }
      },
      "security_group_ingress_rules": {
        "in": {
          "cidr_ipv4": "10.0.0.0/16",
          "description": "Allow all traffic from the VPC",
          "from_port": 0,
          "protocol": "tcp",
          "to_Port": 0
        }
      },
      "source": "terraform-aws-modules/fsx/aws//modules/lustre",
      "storage_capacity": 1200,
      "storage_type": "SSD",
      "subnet_ids": ["a", "b"]
      "version": "1.1.0"
    }
```

### Steps to Reproduce

Create filesystem with more then one subnet 

### Would you like to implement a fix?

Yes

**Comment by stefanfreitag** [comment] 2024-09-26 17:25
Good evening @omerlh,

thank you for bringing this issue to our attention!

The issue reported in #39467 seems to be similar to yours. It also addresses concerns on the subnet identifiers when it comes to a Lustre filesystem.
 
As you already noticed there is a [validation](https://github.com/hashicorp/terraform-provider-aws/blob/e6438dde0755e4eb4898551097413e919a5f21b9/internal/service/fsx/lustre_file_system.go#L292) in place. It helps to ensure that only one subnet can be specified. 

This limitation on one subnet is "just propagated" by the provider and actually an AWS internal thing.
[Here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-fsx-filesystem.html) you find details on the subnet identifiers and the important part seems to be

> For Windows SINGLE_AZ_1 and SINGLE_AZ_2 and all Lustre deployment types, provide exactly one subnet ID.

Hope that helps, if not please let me know. Happy to have a 2nd look.

**Comment by justinretzolk** [comment] 2024-10-30 19:54
Hey @omerlh 👋 Thank you for taking the time to raise this! I think that Stefan's answer above largely covers the answer here, but this was also raised in #39467, so in an attempt to consolidate any further conversations, I'm going to close this as a duplicate.

**Comment by justinretzolk** [comment] 2024-10-30 19:54
Duplicate of #39467

**Closed by justinretzolk** 2024-10-30 19:54 UTC
Labels: bug, service/fsx, needs-triage
