### ISSUE TITLE
[Bug]: Ip address of instance was not updated. TF reports that EC2 will be updated in place, but it does not.

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/terraform-provider-aws#38293] opened 2024-07-08 21:36 UTC
### Terraform Core Version

v1.8.5

### AWS Provider Version

v5.55.0

### Affected Resource(s)

* aws_instance

### Expected Behavior

The instance is not updated in place, because its type was changed and reboot will occur.

### Actual Behavior

The instance is rebooted and its IP was changed

### Relevant Error/Panic Output Snippet

Another example of wrong state after terraform plan/apply:

```console
Terraform will perform the following actions:

  # module.private-cloud.aws_instance.server[0] will be updated in-place
  ~ resource "aws_instance" "server" {
        id                                   = "i-XX"
      ~ instance_type                        = "t3.micro" -> "t2.micro"
        tags                                 = {
            "ConsulAutoJoin" = "nomad-auto-join"
            "Name"           = "nomad-server-0"
            "NomadType"      = "server"
        }
        # (39 unchanged attributes hidden)

        # (8 unchanged blocks hidden)
    }

  # module.private-cloud.aws_instance.www[0] will be updated in-place
  ~ resource "aws_instance" "www" {
        id                                   = "i-XX"
      ~ instance_type                        = "m5.xlarge" -> "m4.xlarge"
        tags                                 = {
            "ConsulAutoJoin" = "nomad-auto-join"
            "Name"           = "nomad-client-0"
            "NomadType"      = "client"
        }
        # (39 unchanged attributes hidden)

        # (9 unchanged blocks hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.
Saved the plan to: ../../state.d/terraform.plan
```

And after apply:

```console
ConnectionInfo = <<EOT

Client EC2 instances: x223
Server EC2 instances: x.66

The Nomad UI can be accessed at http://x66:4646/ui
The Consul UI can be accessed at http://x.66:8500/ui
with the token: x

SSH into client: ssh -i state.d/nomad-www.pem ubuntu@x.223
SSH into server: ssh -i state.d/nomad-www.pem ubuntu@x.66

EOT
consul_server = "http://x.66"
consul_token = <sensitive>

ecrRegistryUrl = "x.dkr.ecr.us-west-2.amazonaws.com"
iguides_bucket_name = "nomad-portal-iguides"
lambdaNames = {
  "autodraft" = "nomad_autodraft"
}
private_ip = "x245"
project_name = "nomad"
public_ip = "x223"
secret_key = <sensitive>
user_bucket_name = "nomad-portal-users"
```

If I plan with `refresh-only` option then changes are visible:

```console
Changes to Outputs:
  ~ ConnectionInfo      = <<-EOT
      - Client EC2 instances: x.223
      + Client EC2 instances: x.151
      - Server EC2 instances: x.66
      + Server EC2 instances: x50

      - The Nomad UI can be accessed at http://5x.66:4646/ui
      + The Nomad UI can be accessed at http://x50:4646/ui
      - The Consul UI can be accessed at http://5x.66:8500/ui
      + The Consul UI can be accessed at http://x.50:8500/ui
        with the token: xx

      - SSH into client: ssh -i state.d/nomad-www.pem ubuntu@x.223
      + SSH into client: ssh -i state.d/nomad-www.pem ubuntu@x.151
      - SSH into server: ssh -i state.d/nomad-www.pem ubuntu@x.66
      + SSH into server: ssh -i state.d/nomad-www.pem ubuntu@x.50
    EOT
  ~ consul_server       = "http://x.66" -> "http://x.50"
  ~ public_ip           = "x.223" -> "x.151"

You can apply this plan to save these new output values to the Terraform state, without
changing any real infrastructure.
```

### Terraform Configuration Files

```hcl
resource "aws_instance" "server" {
  instance_type           = local.server_instance_type
  ami                     = "ami-xxx"
  availability_zone       = "${var.aws_region}a"
  key_name                = aws_key_pair.ssh.key_name
  disable_api_termination = false

  root_block_device {
    volume_type           = "gp3"
    volume_size           = 8
    delete_on_termination = true
  }

  subnet_id                   = aws_subnet.main_a.id
  associate_public_ip_address = true
  iam_instance_profile        = aws_iam_instance_profile.www.name
}
```

### Steps to Reproduce

1. Create an instance
2. Change its type from t3 -> t2
3. Apply the changes.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-07-10 18:25
Hey @EugenKon 👋 Thank you for taking the time to raise this! Are you able to supply a full configuration that can be used to reproduce the issue? I notice from the logging that you provided that you're using modules and outputs -- the way those things are configured can have an impact.

**Comment by EugenKon** [comment] 2024-07-10 18:44
@justinretzolk I can, but I can not send it to your email address, because my email address is blocked in some way =(

**Comment by justinretzolk** [comment] 2024-07-29 15:44
Hmm that's strange @EugenKon -- I'm not sure what email you're trying to send to, but usually folks will encrypt the logs and then upload in a comment here. That said, I reviewed the initial ask again and noticed something that I'd not caught last time.

> The instance is not updated in place, because its type was changed and reboot will occur.

In this case, what Terraform means by "update in place" is that Terraform itself will not be destroying and then re-creating the resource as it does for resources that are not able to be updated (note that the instance ID stays the same, for example). That AWS triggers the instance to reboot after the update isn't something that Terraform has any insight into. We looked into this on a [previous issue](https://github.com/hashicorp/terraform-provider-aws/issues/36376), where a couple of workaround options were presented as well.

Since this is currently behaving as expected, I'm going to close this issue. If you experience unexpected behavior in the future, please do continue to let us know!

**Closed by justinretzolk** 2024-07-29 15:44 UTC
Labels: bug, service/ec2, needs-triage
