### ISSUE TITLE
[Bug]: inline_policy deprecation don't have any reason

### ISSUE THREAD

**Issue by ibaraki-douji** [hashicorp/terraform-provider-aws#40143] opened 2024-11-15 15:05 UTC
### Terraform Core Version

1.9.5

### AWS Provider Version

5.76.0

### Affected Resource(s)

aws_iam_role

### Expected Behavior

inline_policy deprecation don't have any Reason for why it was deprecated
![image](https://github.com/user-attachments/assets/25b33a6a-52ab-40bb-ba27-3a2ccd6322ee)

### Actual Behavior

inline_policy should have the reason why it was deprecated and maybe also the new element that replace that deprecation

### Terraform Configuration Files

```hcl
resource "aws_iam_role" "role" {
  name = "${var.name}"
  inline_policy {
    name = "${var.name}"
    policy = jsonencode({...})
}
```

### Steps to Reproduce

Open VSCode (with HCL extension)

Use the "aws_iam_role" resource with the "inline_policy" block

Look at the code and the "inline_policy" should be marked as deprecated without any reason

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-11-15 15:47
Hey @ibaraki-douji 👋 Thank you for taking the time to raise this! It looks like this is a result of the deprecation message not being exposed by the SDK/Terraform Core in a way that allows the language server to retrieve that information (see https://github.com/hashicorp/vscode-terraform/issues/1729). Upon running `terraform plan`, however, the deprecation message will be included in the output.

Since this is more of an upstream/language server issue, and not something that the AWS Provider team will need to make changes for at this time, I'm going to close this issue for now. If there are changes in the upstream behavior in the future that we need to make adjustments for, we'd be happy to take another look. In the meantime, if you experience any other unexpected behavior, please do let us know!

**Closed as completed by justinretzolk** 2024-11-15 15:47 UTC
Labels: bug, upstream, service/iam
