### ISSUE TITLE
Error when creating aws_opsworks_stack with tags and provider for a different region

### ISSUE THREAD

**Issue by ento** [hashicorp/terraform-provider-aws#6381] opened 2018-11-07 03:02 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```shell
$ terraform -v
Terraform v0.11.10
+ provider.aws v1.42.0
```

### Affected Resource(s)

* aws_opsworks_stack

### Terraform Configuration Files

```hcl
terraform {
  backend "s3" {}

  required_version = "~> 0.11.10"
}

provider "aws" {
  version = "~> 1.25"
  region  = "us-west-2"
}

# This provider is used for creating the aws_opsworks_stack                                                                         
provider "aws" {
  region  = "us-east-1"
  version = "~> 1.25"
  alias   = "east_provider_alias"
}

data "aws_caller_identity" "current" {}

resource "aws_opsworks_stack" "main" {
  provider = "aws.east_provider_alias"
  name     = "test"
  region   = "us-west-2"

  default_availability_zone    = "us-west-2a"
  service_role_arn             = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/aws-opsworks-service-role"
  default_instance_profile_arn = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:instance-profile/aws-opsworks-ec2-role"

  tags {
    Service     = "opsworks-test"
    Environment = "test"
  }
}

output "stack_arn" {
  value = "${aws_opsworks_stack.main.arn}"
}
```

### Debug Output

[Partial log of `TF_LOG=DEBUG terragrunt apply`](https://gist.github.com/ento/d2c714a318029acb66dc7b2534e29b84) where it gives an error.

### Expected Behavior

Stack is created with the specified tags.

### Actual Behavior

- `terraform apply` results in an error. Stack is created but the tags are missing.
- Subsequent applies don't create tags

### Steps to Reproduce

1. You may need to create an OpsWorks stack manually to create the referenced service role and instance profile, while choosing "New IAM Role" and "New IAM Instance Profile" for the respective fields. Sorry I'm lazy and didn't produce a self-contained example above.
2. `terraform apply`

(For the record, I'm using terragrunt and aws-vault but I'm going to write `terraform` for simplicity)

Exploring further behavior:

- No tags created: `aws --region=us-east-1 opsworks list-tags --resource-arn $(terraform output stack_arn)` -> `"Tags": {}`
- Applying again doesn't update tags: `terraform apply` -> "No changes. Infrastructure is up-to-date."
- Refreshing doesn't update the state file with the correct state `terraform refresh && terraform plan` -> "No changes. Infrastructure is up-to-date."

### Important Factoids
I found one event in CloudTrail log which showed that the `TagResource` API was called with a resource ARN that looked like `arn:aws:opsworks:us-west-2:{account_id}:stack/{stack_id}/`, which suggests that the provider is not using the `stack_endpoint` to construct the ARN of the stack.

### References
n/a

**Comment by ewbankkit** [comment] 2021-10-05 11:58
Duplicate of #21148.

**Closed by ewbankkit** 2021-10-05 11:58 UTC
Labels: bug, service/opsworks
