### ISSUE TITLE
[Bug]: Repeatedly attempt to create "aws_ssoadmin_permission_set", when a permission set with the same name already exists.

### ISSUE THREAD

**Issue by rukshantp** [hashicorp/terraform-provider-aws#39297] opened 2024-09-13 05:09 UTC
### Terraform Core Version

1.9.5

### AWS Provider Version

5.67.0

### Affected Resource(s)

aws_ssoadmin_permission_set

### Expected Behavior

Exit terraform apply, when PermissionSet with name AWSOrganizationsFullAccess already exists.

### Actual Behavior

Retry to create the PermissoinSet with already existing name.

### Terraform Configuration Files

```
resource "aws_ssoadmin_permission_set" "AWSOrganizationsFullAccess" {
  instance_arn = "arn:aws:sso:::instance/ssoins-8259e9dc43df5c9f"
  name         = "AWSOrganizationsFullAccess"
  description  = "AWSOrganizationsFullAccess permission set"
  session_duration = "PT8H"
}

resource "aws_ssoadmin_managed_policy_attachment" "AWSOrganizationsFullAccess_AWSOrganizationsFullAccess" {
  instance_arn      = "arn:aws:sso:::instance/ssoins-8259e9dc43df5c9f"
  permission_set_arn = aws_ssoadmin_permission_set.AWSOrganizationsFullAccess.arn
  managed_policy_arn = "arn:aws:iam::aws:policy/AWSOrganizationsFullAccess"
}
```

### Steps to Reproduce

1. Have a existing permission set named AWSOrganizationsFullAccess in AWS account
2. terraform init
3. terraform apply

### Debug Output

[terraform_trace.log](https://github.com/user-attachments/files/16988742/terraform_trace.log)

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-11-04 17:11
Hey @rukshantp  👋 Thanks for taking the time to submit this issue! It looks like this is a duplicate of #38544. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of that one.

**Comment by justinretzolk** [comment] 2024-11-04 17:11
Duplicate of #38544

**Closed by justinretzolk** 2024-11-04 17:11 UTC
Labels: bug, service/ssoadmin
