### ISSUE TITLE
[Bug]: AWS provider do not load the correct profile credentials

### ISSUE THREAD

**Issue by luiszaelot** [hashicorp/terraform-provider-aws#38759] opened 2024-08-07 23:42 UTC
### Terraform Core Version

1.9.3

### AWS Provider Version

5.61.0

### Affected Resource(s)

When you define S3 as backend for terraform state, and setting aws provider with custom profile name (from vars):

```
terraform {
  backend "s3" {
    bucket = "my-bucket-here"
    key    = "path/to/terraform.tfstate"
    region = "us-east-1"
  }
}

provider "aws" {
  region                  = var.aws_region
  profile                 = var.aws_profile
  shared_credentials_files = var.shared_credentials_files
}


variable "aws_profile" {
  default = "default"
  type    = string
}

variable "shared_credentials_files" {
  default = ["~/.aws/credentials"]
  type    = list(string)
}
```

Terraform is not able to access AWS S3 (because it uses the wrong credentials).
```
$ terraform init 
Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
╷
│ Error: Error refreshing state: Unable to access object "path/to/terraform.tfstate" in S3 bucket "my-bucket-here": operation error S3: HeadObject, https response error StatusCode: 403, RequestID: ********, HostID: ******, api error Forbidden: Forbidden
```

Setting my key and secret in `default` profile in AWS credentials file fixed the issue.

### Expected Behavior

The correct profile credentials should be used.

### Actual Behavior

Terraform is picking the `default` profile credentials

### Terraform Configuration Files

Already provided in description

### Steps to Reproduce

Already provided in description

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-08-12 17:06
Hey @luiszaelot 👋 Thank you for taking the time to raise this! Issues with the S3 backend generally should be logged in the [Terraform Core repository](https://github.com/hashicorp/terraform), however, I think I see the issue here.

The authentication for the S3 backend is handled separately from the authentication of the provider, so the `profile` and `shared_configuration_files` arguments you supplied in the `provider` block won't apply to it. Notably, the backend and provider both follow the same [load order for authentication-related arguments](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#authentication-and-configuration) as the AWS CLI. With that in mind, you've only supplied the `bucket`, `key`, and `region` arguments to the S3 backend configuration -- none of the authentication-related arguments. Without logging, I'm assuming that the environment variables related to authentication haven't been set.

Without the access key/secret key, the next credential source is `shared_credentials_files`, which you've set in the AWS provider configuration, but not in the backend configuration. For the backend, this argument [defaults to `~/.aws/credentials`] -- the same location you've set for the `shared_credentials_files` variable. This may have made it seem as though setting the `shared_credentials_files` and `profile` in the provider configuration had an impact, however, without a specific profile defined for the backend, the `default` profile is used. This is why setting the credentials in the `default` profile resolved the issue.

Since this ultimately appears to be either a configuration issue or something that the Terraform Core team will need to address, I'm going to close this issue. If you run into unexpected behavior in the future, please do let us know!

**Closed by justinretzolk** 2024-08-12 17:06 UTC
Labels: bug, needs-triage

**Comment by luiszaelot** [comment] 2024-08-12 23:16
> Hey @luiszaelot 👋 Thank you for taking the time to raise this! Issues with the S3 backend generally should be logged in the [Terraform Core repository](https://github.com/hashicorp/terraform), however, I think I see the issue here.
> 
> The authentication for the S3 backend is handled separately from the authentication of the provider, so the `profile` and `shared_configuration_files` arguments you supplied in the `provider` block won't apply to it. Notably, the backend and provider both follow the same [load order for authentication-related arguments](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#authentication-and-configuration) as the AWS CLI. With that in mind, you've only supplied the `bucket`, `key`, and `region` arguments to the S3 backend configuration -- none of the authentication-related arguments. Without logging, I'm assuming that the environment variables related to authentication haven't been set.
> 
> Without the access key/secret key, the next credential source is `shared_credentials_files`, which you've set in the AWS provider configuration, but not in the backend configuration. For the backend, this argument [defaults to `~/.aws/credentials`] -- the same location you've set for the `shared_credentials_files` variable. This may have made it seem as though setting the `shared_credentials_files` and `profile` in the provider configuration had an impact, however, without a specific profile defined for the backend, the `default` profile is used. This is why setting the credentials in the `default` profile resolved the issue.
> 
> Since this ultimately appears to be either a configuration issue or something that the Terraform Core team will need to address, I'm going to close this issue. If you run into unexpected behavior in the future, please do let us know!

That does totally make sense. Thanks for replying!
