### ISSUE TITLE
[Bug]: aws_batch_job_definition tag broken when no existing tags

### ISSUE THREAD

**Issue by james-flwls** [hashicorp/terraform-provider-aws#38053] opened 2024-06-20 14:18 UTC
### Terraform Core Version

v1.8.5

### AWS Provider Version

v5.54.1

### Affected Resource(s)

* aws_batch_job_definition

### Expected Behavior

Any tags are reflected in AWS

### Actual Behavior

Tags are only added if there is at least one tag in AWS for the batch definition

### Relevant Error/Panic Output Snippet

```shell
The plan / apply looks correct but not reflected in AWS
```

### Terraform Configuration Files

```
resource "aws_batch_job_definition" "main" {

  name                  = var.container_name
  type                  = "container"
  platform_capabilities = [var.platformCapabilities]
  container_properties  = jsonencode(local.container_definition_without_null)
  propagate_tags        = true
  tags = {
    Environment = var.environment
    Namespace   = var.namespace
    Project     = var.project
    Service     = var.app
    Team        = "development"
  }
}
```

### Steps to Reproduce

Running a plan / apply when there are no existsing tags 
```
~ revision                   = 7 -> (known after apply)
 ~ tags                       = {
    "Environment" = "dev"
  + "Namespace"   = "main"
    "Project"     = "xxxx"
  + "Service"     = "xxxx"
  + "Team"        = "development"
}
~ tags_all                   = {
  + "Environment" = "dev"
  + "ManagedBy"   = "terraform"
  + "Namespace"   = "main"
  + "Owner"       = "xxxx"
  + "Project"     = "xxxx"
  + "Role"        = "batch"
  + "Service"     = "xxxx"
  + "SourcePath"  = "xxxx"
  + "Team"        = "development"

```
![tags-missing](https://github.com/hashicorp/terraform-provider-aws/assets/122805425/81f8fcaa-66b9-4c02-99c1-7b20fa5b1e1f)

AWS is missing all tags including from `tags_all`

If I then create a manual tag in AWS `Environment = foo`

Running plan / apply

```
~ revision                   = 8 -> (known after apply)
~ tags                      = {
    ~ "Environment" = "foo" -> "dev"          <------- detects the change
    + "Namespace"   = "main"
      "Project"     = "xxxx"
    + "Service"     = "xxxx"
    + "Team"        = "development"
  }
~ tags_all                   = {
    ~ "Environment" = "foo" -> "dev"
    + "ManagedBy"   = "terraform"
    + "Namespace"   = "main"
    + "Owner"       = "xxxx"
    + "Project"     = "xxxxx"
    + "Role"        = "batch"
    + "Service"     = "xxxx"
    + "SourcePath"  = "xxxxx"
    + "Team"        = "development"
  }
  # (8 unchanged attributes hidden)
}
```
![tags-present](https://github.com/hashicorp/terraform-provider-aws/assets/122805425/27af8fcb-3dd5-49cc-a74a-33bbe617c6e9)

All tags are now present correctly

### Would you like to implement a fix?

No

**Comment by james-flwls** [comment] 2024-06-20 15:11
So it seems that the problem happens when the new definition becomes active. The old definition has the correct tags.

**Comment by andrewmwilson** [comment] 2024-06-26 05:58
I think this is a duplicate of https://github.com/hashicorp/terraform-provider-aws/issues/37254

**Comment by james-flwls** [comment] 2024-06-26 16:23
Possibly a duplicate - its a bit unclear on that ticket if its the same. It implies its related to tags_all and not having any tags on the resource. It is a tag issue on `aws_batch_job_definition` so likely to be related

**Comment by james-flwls** [comment] 2024-09-16 15:29
Is there any idea if this bug will be triaged - would be good to get a fix in as we can't propogate tags at the moment

**Closed** 2024-10-21 20:27 UTC
Labels: bug, service/batch, tags
