### ISSUE TITLE
Add support for LogOptions in VPN Tunnel Options

### ISSUE THREAD

**Issue by vinceoan** [hashicorp/terraform-provider-aws#26408] opened 2022-08-21 00:48 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

* VPN tunnel options feature was added earlier in this issue https://github.com/hashicorp/terraform-provider-aws/issues/11584. However it wasn't fully cover all the tunnel options. The one that is missing is LogOptions. If we can get it added that would fully support all tunnel options available. Thank you!

### New or Affected Resource(s)

* aws_vpn_tunnel_options

### Potential Terraform Configuration

```hcl
resource "aws_vpn_tunnel_options" "main" {
  vpn_connection_id = aws_vpn_connection.main.id
  vpn_tunnel_outside_ip_address = aws_vpn_connection.main.tunnel1_address
  log_options = {CloudWatchLogOptions={LogEnabled=boolean,LogGroupArn=string,LogOutputFormat=string}}
}
```

### References

* [https://docs.aws.amazon.com/cli/latest/reference/ec2/modify-vpn-tunnel-options.html](https://docs.aws.amazon.com/cli/latest/reference/ec2/modify-vpn-tunnel-options.html)

**Comment by bschaatsbergen** [comment] 2022-08-21 09:58
Hi @vinceoan, thanks for raising this; this seems to be a duplicate of: https://github.com/hashicorp/terraform-provider-aws/issues/26389

**Comment by ewbankkit** [comment] 2022-08-22 13:00
@vinceoan Thanks for raising this issue.
It has already been noticed in #26389. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Closed by ewbankkit** 2022-08-22 13:00 UTC
Labels: enhancement, service/vpnsite
