### ISSUE TITLE
[Bug]: Terraform removes existing event notification on a bucket to create a new one without showing a destroy or update in the plan

### ISSUE THREAD

**Issue by saijal** [hashicorp/terraform-provider-aws#35480] opened 2024-01-25 12:01 UTC
### Terraform Core Version

0.13

### AWS Provider Version

3.28.0

### Affected Resource(s)

AWS s3 event notification.

### Expected Behavior

Terraform plan should show a destroy on the exisiting notifications. Since it shows only creation in the plan, it's very unintuitive that exisiting notifications will get replaced and leads to a silent failure. 

### Actual Behavior

Shows only creation of the new event notifications without showing a destroy or update in the plan for existing notifications

### Terraform Configuration Files

```terraform
terraform {
backend "s3" {
bucket = ***
key = ***
region = ***

}

required_version = "0.13.0"
}

provider "aws" {
version = "~> 3.28.0"
region = var.region
}

variable "region" {
default = ***
}
```

### Steps to Reproduce

Add the following to .tf file

```
resource "aws_s3_bucket_notification" "prod-bucket-notification" {
  bucket   = "bucket-name"

  queue {
    queue_arn     = "queue-arn"
    events        = ["s3:ObjectCreated:*"]
    filter_prefix = "input/"
    filter_suffix = ".csv"
  }
}
```

tf plan
tf apply

```terraform
Add a new event notification resource on the same bucket to same .tf file
resource "aws_s3_bucket_notification" "prod-bucket-notification-new" {
  bucket   = "bucket-name"

  queue {
    queue_arn     = "queue-arn"
    events        = ["s3:ObjectCreated:*"]
    filter_prefix = "input/"
    filter_suffix = ".txt"
  }
}
```

tf plan - Shows only creation of new notification
tf apply

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-01-25 21:09
Hey @saijal 👋 Thank you for taking the time to raise this! I noticed that you're using a fairly old version of Terraform and the AWS provider. Are you able to test with newer versions of these to see if that resolves the issue?

**Comment by saijal** [comment] 2024-02-01 11:34
Hey @justinretzolk 
I tested the same with terraform versions 1.0.7 and 1.5.0 and the same behaviour has persisted in both.

**Comment by saijal** [comment] 2024-02-20 11:42
@justinretzolk ^

**Comment by justinretzolk** [comment] 2024-03-13 18:42
Hi @saijal and @limitusus 👋 In reviewing this again, I see the following note in the [`aws_s3_bucket_notification` documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_notification)

> S3 Buckets only support a single notification configuration. Declaring multiple `aws_s3_bucket_notification` resources to the same S3 Bucket will cause a perpetual difference in configuration. See the example "Trigger multiple Lambda functions" for an option.

This is due to a behavior noted on the [`PutBucketNotificationConfiguration` documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketNotificationConfiguration.html) (the API action used by the Terraform AWS provider for this resource):

> This action replaces the existing notification configuration with the configuration you include in the request body.

Because this is expected behavior that we have noted in the documentation, and there's no further action for us to take, I'll close this issue out.

**Closed by justinretzolk** 2024-03-13 18:42 UTC
Labels: bug, service/s3, needs-triage
