### ISSUE TITLE
Support new RDS Multi-AZ DB cluster deployments

### ISSUE THREAD

**Issue by gclough** [hashicorp/terraform-provider-aws#22871] opened 2022-02-01 14:05 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon have released a new "Multi-AZ DB cluster" configuration for RDS PostgreSQL and MySQL databases into beta, so I would like the AWS provider to support creation and maintenance of them:

[Multi-AZ DB cluster deployments](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/multi-az-db-clusters-concepts.html)

### New or Affected Resource(s)

* `aws_rds_multiaz_cluster` or maybe `aws_db_multiaz_cluster` (but I prefer the former)

This should be used in place of the normal resource `aws_db_instance resource`, which is generally used for RDS instances.

### Potential Terraform Configuration

none

### References

none

**Comment by bschaatsbergen** [comment] 2022-03-24 22:18
Duplicate of #23475, released in 4.6.0

cc @justinretzolk

**Closed** 2022-03-24 22:20 UTC
Labels: enhancement, service/rds
