### ISSUE TITLE
Cognito User Pool: cannot modify or remove schema items

### ISSUE THREAD

**Issue by marvincaspar** [hashicorp/terraform-provider-aws#21654] opened 2021-11-05 16:16 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.6
AWS provider 3.63.0

### Affected Resource(s)

* aws_cognito_user_pool

### Terraform Configuration Files

```hcl
resource "aws_cognito_user_pool" "pool" {
  name = "${local.project_name}_user_pool"

  mfa_configuration = "OFF" # todo change later to OPTIONAL

  lambda_config {
    post_authentication = aws_lambda_function.post_authentication.arn
  }

  auto_verified_attributes = [
    "email",
    # "phone_number",
  ]

  username_attributes = ["email"]

  password_policy {
    minimum_length    = 8
    require_lowercase = true
    require_numbers   = true
    require_symbols   = true
    require_uppercase = true
  }

  schema {
    name                = "email"
    attribute_data_type = "String"
    mutable             = false
    required            = true
  }
  schema {
    name                = "phone"
    attribute_data_type = "String"
    mutable             = false
    required            = false
  }
}

resource "aws_cognito_user_pool_client" "client" {
  name = "${local.project_name}_user_pool_client"

  user_pool_id = aws_cognito_user_pool.pool.id

  allowed_oauth_flows                  = ["implicit"]
  allowed_oauth_flows_user_pool_client = true
  allowed_oauth_scopes                 = ["email", "openid"]

  logout_urls   = ["https://${local.domain}"]
  callback_urls = ["https://${local.domain}"]

  supported_identity_providers = ["COGNITO"]
}
```

### Actual Behavior

```sh
  # aws_cognito_user_pool.pool will be updated in-place
  ~ resource "aws_cognito_user_pool" "pool" {
        id                        = "eu-central-1_xxx"
        name                      = "intocourse_user_pool"
        tags                      = {}
        # (9 unchanged attributes hidden)




      ~ password_policy {
          - temporary_password_validity_days = 7 -> null
            # (5 unchanged attributes hidden)
        }

      - schema {
          - attribute_data_type      = "String" -> null
          - developer_only_attribute = false -> null
          - mutable                  = false -> null
          - name                     = "email" -> null
          - required                 = true -> null

          - string_attribute_constraints {
              - max_length = "2048" -> null
              - min_length = "0" -> null
            }
        }
      - schema {
          - attribute_data_type      = "String" -> null
          - developer_only_attribute = false -> null
          - mutable                  = false -> null
          - name                     = "phone" -> null
          - required                 = false -> null

          - string_attribute_constraints {}
        }
      + schema {
          + attribute_data_type = "String"
          + mutable             = false
          + name                = "email"
          + required            = true
        }
      + schema {
          + attribute_data_type = "String"
          + mutable             = false
          + name                = "phone"
          + required            = false
        }
      + schema {
        }

        # (4 unchanged blocks hidden)
    }

...

aws_cognito_user_pool.pool: Modifying... [id=eu-central-1_xxx]
╷
│ Error: error updating Cognito User Pool (eu-central-1_xxx): cannot modify or remove schema items
│ 
│   with aws_cognito_user_pool.pool,
│   on cognito.tf line 1, in resource "aws_cognito_user_pool" "pool":
│    1: resource "aws_cognito_user_pool" "pool" {
│ 
╵
```

### Steps to Reproduce

1. `terraform apply`

**Comment by dolv** [comment] 2021-12-22 21:32
the same issue with terraform 0.13.6

**Comment by dolv** [comment] 2021-12-22 21:45
the same issue with terraform 0.13.6 and aws provider 3.70.0

**Comment by k2glyph** [comment] 2022-01-29 06:49
+1

**Comment by seunggs** [comment] 2022-02-10 05:00
+1

**Comment by ARau87** [comment] 2022-02-14 00:14
+1

**Comment by tooxie** [comment] 2022-03-02 20:23
Please read the community notes and stop commenting with `+1`:

_Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request_

**Comment by accrisoftteam** [comment] 2022-03-07 18:31
Resources could be created with both min and max null on string_attribute_constraints on custom fields, AWS defaults values to 0 and 256 on their side. The problem is, once they are created that way, the are permanently null in states, even if the AWS interface show 0 min and 256 max. Since they are immutable, they can't be fixed with new string_attribute_constraints after they are deployed.

That is my current problem, I created with empty string_attribute_constraints so both min and max were blank, and even though AWS used defaults of 0 and 256, terraform state reader still reads them as null, forever causing problems when apply other resources or adding new fields because planning doesn't like null.

I tried re-importing, still reads as null on both min and max. Is there no way to avoid this problem caused by null string_attribute_constraints arguments?

**Comment by BekzatMakhanbet** [comment] 2022-03-15 20:41
I at first deleted existing pool, and rerun apply command with adding string_attribute_constraints

**Comment by ZsoltPath** [comment] 2022-05-10 10:11
Unfortunately it happens without the string_attribute_constraints

```
      + schema {
          + attribute_data_type      = "String"
          + developer_only_attribute = false
          + mutable                  = true
          + name                     = "adviceAdminRole"
          + required                 = false

          + string_attribute_constraints {}
        }
      - schema {
          - attribute_data_type      = "String" -> null
          - developer_only_attribute = false -> null
          - mutable                  = true -> null
          - name                     = "adviceAdminRole" -> null
          - required                 = false -> null

          - string_attribute_constraints {}
        }
      + schema {
          + attribute_data_type      = "String"
          + developer_only_attribute = false
          + mutable                  = true
          + name                     = "azureGroups"
          + required                 = false

          + string_attribute_constraints {}
        }
      - schema {
          - attribute_data_type      = "String" -> null
          - developer_only_attribute = false -> null
          - mutable                  = true -> null
          - name                     = "azureGroups" -> null
          - required                 = false -> null

          - string_attribute_constraints {}
        }
      + schema {
          + attribute_data_type      = "String"
          + developer_only_attribute = false
          + mutable                  = true
          + name                     = "documentAdminRole"
          + required                 = false

          + string_attribute_constraints {}
        }
      - schema {
          - attribute_data_type      = "String" -> null
          - developer_only_attribute = false -> null
          - mutable                  = true -> null
          - name                     = "documentAdminRole" -> null
          - required                 = false -> null

          - string_attribute_constraints {}
        }
      + schema {
          + attribute_data_type      = "String"
          + developer_only_attribute = false
          + mutable                  = true
          + name                     = "peopleAdminRole"
          + required                 = false

          + string_attribute_constraints {}
        }
```

Terraform v1.1.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v4.4.0

**Comment by bvbiradar** [comment] 2022-06-21 07:02
aws_cognito_user_pool.user_pools: Modifying... [id=pool_id]
╷
│ Error: error updating Cognito User Pool (pool_id): cannot modify or remove schema items
│
│   with aws_cognito_user_pool.user_pools,
│   on cognito.tf line 4, in resource "aws_cognito_user_pool" "user_pools":
│    4: resource "aws_cognito_user_pool" "user_pools" {
│

**Comment by jmcvetta** [comment] 2022-10-19 00:21
Same issue with Terraform v1.3.1 + AWS Provider v4.24.0.

Correct behavior should be to trigger replacement of `aws_cognito_user_pool` resource upon modification of its `schema` attributes.

**Comment by lsacco-nutreense** [comment] 2022-11-01 23:21
@jmcvetta that shouldn't be the correct behavior IMHO. You can go to an existing pool in the console and add attributes without replacing the pool. If you replace the pool, then the ID would change which would cause problems downstream for us, since that's how we bind to it.

**Comment by leonarac** [comment] 2022-11-21 20:03
+1

**Comment by maikonb** [comment] 2022-12-09 02:41
+1

**Comment by leonarac** [comment] 2023-02-15 20:40
> If you dont care about the changes suggested by terraform like in my case, you can simply ignore them by adding this to your resource block:
> 
> ```
> lifecycle {
> 
>     ignore_changes = [
>       password_policy,
>       schema
>     ]
>   }
> ```

This behavior works, I'm using modules and with that block at the end of the resource inside cognito it works perfect for me

**Comment by etwillbefine** [comment] 2023-04-28 08:24
This is an Issue with AWS Cognito User Pools itself. You cannot change or modify standard attributes after user-pool creation. [See their docs](https://repost.aws/knowledge-center/cognito-change-user-pool-attributes) -> long story short -> not possible. Especially with App-Clients being already registered or a SAML App using the User Pool ID for the SAML Entity  ID its a "pain" and is STILL not being addressed properly by AWS (My change was to change email to muteable after registering a SAML provider). In an corporate environment where you can't manage SAML Apps yourself and already using app-clients and changes to a schema can happen from time to time, its honestly a reason to rethink the decision to use AWS Cognito.

For the Terraform Provider it means it's correct to recreate the user pool rather than suggesting an attribute can be replaced during plan phase (which just adds up to the overall confusion). Anyone aware of an issue regarding the general AWS Cognito Behaviour?

**Comment by ffleandro** [comment] 2023-06-21 15:19
Besides the discussion about not being able to edit the schema attributes, terraform is throwing this error for me even when I haven't changed anything in the `password_policy` or `schema` attributes.

**Comment by brunodasilvalenga** [comment] 2023-06-29 02:11
up

**Closed** 2023-07-20 15:07 UTC
Labels: bug, service/cognitoidp
