### ISSUE TITLE
aws_lambda_permission is missing after new aws_lambda_alias is redeployed

### ISSUE THREAD

**Issue by papalagichen** [hashicorp/terraform-provider-aws#12917] opened 2020-04-21 04:18 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.24
+ provider.aws v2.55.0
+ provider.null v2.1.2
+ provider.template v2.1.2

### Affected Resource(s)

* aws_lambda_permission

### Terraform Configuration Files

```hcl
resource aws_lambda_alias new_alias {
  name             = "major"
  function_name    = "${var.lambda_function_name}"
  function_version = "$LATEST"
}

resource aws_lambda_permission allow_api_gateway {
  function_name       = "${var.lambda_function_name}"
  qualifier           = "${aws_lambda_alias.new_alias.name}"
  statement_id_prefix = "AllowInvocationFromApiGateway-"
  action              = "lambda:InvokeFunction"
  principal           = "apigateway.amazonaws.com"
  source_arn          = "${var.source_arn}"
}
```

### Expected Behavior

The `aws_lambda_permission` should be applied again to the new resource `aws_lambda_alias.new_alias`.

### Actual Behavior

The `aws_lambda_permission` is missing from the new resource `aws_lambda_alias.new_alias`.

### Steps to Reproduce

1. Create resource `aws_lambda_alias.old_alias`. Create resource `aws_lambda_permission` which has attribute `qualifier` pointing to `aws_lambda_alias.old_alias.name`
2. Rename `old_alias` to `new_alias`
3. terraform plan
4. terraform apply

### Important Factoids

In my case, the value of `var.lambda_alias_name` is unchanged, but `aws_lambda_alias` is refactored to a different Terraform resource name (Let's assume from `old_alias` to `new_alias`). As expected, `aws_lambda_alias` will be re-created. However, `aws_lambda_permission` will be missing after Terraform apply, even there is no delete for it in Terraform plan result. Run `terraform plan` again, plan result shows the missing `aws_lambda_permission` is going to be created.

My current workaround is to put Lambda function version to be part of `statement_id_prefix`. Whenever a new Lambda function is created and deployed, the aws_lambda_permission will be forced re-created.

**Comment by justinretzolk** [comment] 2021-10-05 18:37
Thanks for taking the time to submit this issue. It looks like this is a duplicate of #20598. While that issue is a bit newer than this one, it's also targeting a newer release of the AWS Provider, so will likely be a bit better of a starting place. We like to try to keep discussions consolidated, so we’re going to close this issue in favor of #20598.

**Closed by justinretzolk** 2021-10-05 18:37 UTC
Labels: service/lambda, needs-triage
