### ISSUE TITLE
aws_elastic_beanstalk_environment thinks there are changes with every plan/apply

### ISSUE THREAD

**Issue by mrubinwch** [hashicorp/terraform-provider-aws#12889] opened 2020-04-19 03:43 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.24
+ provider.archive v1.3.0
+ provider.aws v2.58.0
+ provider.template v2.1.2
```

This issue did not occur on the latest Terraform v.0.11.x

### Affected Resource(s)

* aws_elastic_beanstalk_environment

### Expected Behavior

Terraform should not think that there are changes if I keep running apply.

### Actual Behavior

Every single time I ran plan or apply, Terraform thinks there are changes.

### Example Output

There is a ton of spam like this:

```
      - setting {
          - name      = "UpdateLevel" -> null
          - namespace = "aws:elasticbeanstalk:managedactions:platformupdate" -> null
          - value     = "patch" -> null
        }
      + setting {
          + name      = "UpdateLevel"
          + namespace = "aws:elasticbeanstalk:managedactions:platformupdate"
          + value     = "patch"
        }
      - setting {
          - name      = "UpperBreachScaleIncrement" -> null
          - namespace = "aws:autoscaling:trigger" -> null
          - value     = "1" -> null
        }
      + setting {
          + name      = "UpperBreachScaleIncrement"
          + namespace = "aws:autoscaling:trigger"
          + value     = "1"
        }
      - setting {
          - name      = "UpperThreshold" -> null
          - namespace = "aws:autoscaling:trigger" -> null
          - value     = "80" -> null
        }
      + setting {
          + name      = "UpperThreshold"
          + namespace = "aws:autoscaling:trigger"
          + value     = "80"
        }
```

**Comment by mrubinwch** [comment] 2020-04-20 19:16
Despite being shown dozens of seemingly changed `setting` entries, like so:

```
      - setting {
          - name      = "RollingUpdateEnabled" -> null
          - namespace = "aws:autoscaling:updatepolicy:rollingupdate" -> null
          - value     = "true" -> null
        }
      + setting {
          + name      = "RollingUpdateEnabled"
          + namespace = "aws:autoscaling:updatepolicy:rollingupdate"
          + value     = "true"
        }
      - setting {
          - name      = "RollingUpdateType" -> null
          - namespace = "aws:autoscaling:updatepolicy:rollingupdate" -> null
          - value     = "Health" -> null
        }
      + setting {
          + name      = "RollingUpdateType"
          + namespace = "aws:autoscaling:updatepolicy:rollingupdate"
          + value     = "Health"
        }
      + setting {
          + name      = "SSHSourceRestriction"
          + namespace = "aws:autoscaling:launchconfiguration"
          + value     = "tcp, 22, 22, sg-d9eedbac"
        }
      - setting {
          - name      = "SSHSourceRestriction" -> null
          - namespace = "aws:autoscaling:launchconfiguration" -> null
          - value     = "tcp,22,22,sg-d9eedbac" -> null
        }
```

it seems that the last one - `SSHSourceRestriction` - the culprit. If I change my file from:

```
  setting {
    namespace = "aws:autoscaling:launchconfiguration"
    name      = "SSHSourceRestriction"
    value     = "tcp, 22, 22, ${aws_security_group.bastion.id}"
  }
```

to

```
  setting {
    namespace = "aws:autoscaling:launchconfiguration"
    name      = "SSHSourceRestriction"
    value     = "tcp,22,22,${aws_security_group.bastion.id}"
  }
```

the entire resource suddenly needs no changes.

It seems there are two issues:

1. If Terraform detects a change from one `setting` entry, why am I being shown dozens of `setting` entries that are seemingly changed? This seems like an outright bug.
2. Perhaps `SSHSourceRestriction` should get special handling in order to not be so sensitive to whitespace - it seems fragile to do an exact string compare against AWS output; what if that changes tomorrow?

**Comment by alexharv074** [comment] 2020-07-10 16:27
Appears to be a duplicate of https://github.com/terraform-providers/terraform-provider-aws/issues/1471

**Comment by mrubinwch** [comment] 2020-09-24 11:55
@alexharv074 Can we get some movement on this?

**Comment by justinretzolk** [comment] 2021-10-05 18:33
Thanks for taking the time to submit this issue. It looks like this is a duplicate of #1471. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #1471.

**Closed by justinretzolk** 2021-10-05 18:33 UTC
Labels: service/elasticbeanstalk, needs-triage
