### ISSUE TITLE
aws_cloudformation_stack_set_instance deployment to Organization/OU

### ISSUE THREAD

**Issue by yanivillouz** [hashicorp/terraform-provider-aws#20765] opened 2021-09-02 12:17 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
aws_cloudformation_stack_set_instance reosurce should support deploying to OU or organization not only to an account 

### New or Affected Resource(s)

* aws_cloudformation_stack_set_instance

### Potential Terraform Configuration

```hcl
resource "aws_cloudformation_stack_set_instance" "stacksets" {
  stack_set_name = "read_only_access"
  region = "eu-west-1"
  OrganizationalUnitIds = ["x9-sssssssssss","w3-tyt6tyyy"]
}
```

### References

* #0000

**Comment by oscarwest** [comment] 2021-09-21 11:41
Seems to be a duplicate of https://github.com/hashicorp/terraform-provider-aws/issues/12425

**Comment by yanivillouz** [comment] 2021-09-22 12:36
Yep
Thanks

**Comment by anGie44** [comment] 2021-10-05 20:58
Closing as a duplicate

**Closed by anGie44** 2021-10-05 20:58 UTC
Labels: enhancement, service/cloudformation
