### ISSUE TITLE
CloudFront: RealtimeLogConfigInUse error while renaming aws_cloudfront_realtime_log_config resource

### ISSUE THREAD

**Issue by finferflu** [hashicorp/terraform-provider-aws#18331] opened 2021-03-22 19:03 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

v0.13.5

### Affected Resource(s)

* aws_cloudfront_realtime_log_config
* aws_cloudfront_distribution (?)

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Trimmed down, can provide full config if needed
resource "aws_cloudfront_realtime_log_config" "this" {
  name          = local.logging_resource_name
  sampling_rate = 100
  fields = [
  ...
  ]

  endpoint {
    stream_type = "Kinesis"

    kinesis_stream_config {
      role_arn   = aws_iam_role.realtime_logging.arn
      stream_arn = var.kinesis_stream_arn
    }
  }

  depends_on = [aws_iam_role_policy.realtime_logging]
}


resource "aws_cloudfront_distribution" "storefront_distribution" {
  ...

  default_cache_behavior {
    ...
    realtime_log_config_arn = aws_cloudfront_realtime_log_config.this.arn
  }

  ordered_cache_behavior {
    ...
    realtime_log_config_arn = aws_cloudfront_realtime_log_config.this.arn
  }
}
```

### Debug Output

Can provide debug output if required.

### Expected Behavior

A change in the `aws_cloudfront_realtime_log_config` resource resulting in a replacement should not cause an error.

### Actual Behavior

Running `terraform apply` causes:

```sh
Error: error deleting Cloudfront Real-time Log Config (arn:aws:cloudfront::xxx:realtime-log-config/my-log-config-name): RealtimeLogConfigInUse: The CloudFront real-time log configuration is still being used.
```

### Steps to Reproduce

1. Change the value of `aws_cloudfront_realtime_log_config`'s `name` attribute
1. Run `terraform apply`

**Comment by gdavison** [comment] 2021-03-23 22:13
Hi @finferflu, thank you for reporting this. Unfortunately, because of how Terraform currently models dependencies between resources, there isn't a good way to fix this problem. There is an [open issue on Terraform core](https://github.com/hashicorp/terraform/issues/16065) to address this.

There is a potential workaround described at https://github.com/hashicorp/terraform/issues/16065#issuecomment-328648133, which may work. Essentially, you will need to remove the realtime log from the CloudFront Distribution, then re-create the realtime log configuration, then re-attach the configuration to the CloudFront Distribution.

Since this issue requires changes to the core Terraform dependency model, I'm going to close this issue. Once the support is available, we will address this and other issues caused by dependencies across resources. You may be able to find other workarounds or solutions in our forums for the [AWS Provider](https://discuss.hashicorp.com/c/terraform-providers/tf-aws/33) or [Terraform](https://discuss.hashicorp.com/c/terraform-core/27).

**Closed by gdavison** 2021-03-23 22:13 UTC
Labels: needs-triage, service/cloudfront

**Comment by finferflu** [comment] 2021-03-24 16:35
Hi @gdavison, thanks for the feedback and the suggestions. I do hope issue [#16065](https://github.com/hashicorp/terraform/issues/16065) gets addressed at some point as it's been around for a while!

**Comment by gdavison** [comment] 2021-03-24 17:09
I hope so! From what I understand, the current dependency model is deeply entwined in Terraform, so this is going to be a very complicated fix to make.
