### ISSUE TITLE
aws_wafv2_web_acl : Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by janul** [hashicorp/terraform-provider-aws#23390] opened 2022-02-25 20:25 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Related:
- 👉 #23390
- #23423
- #23936
- #23992
- #24386
- #27175
- #27273
- #27479
- #28191
- #28672
- #29012
- #29304
- #30858

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.74.3
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

* aws_wafv2_web_acl
* aws_wafv2_regex_pattern_set

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_wafv2_regex_pattern_set" "example-regex" {
  name        = "example"
  description = "Example regex pattern set"
  scope       = "REGIONAL"

  regular_expression {
    regex_string = "one"
  }
  regular_expression {
    regex_string = "two"
  }
}
resource "aws_wafv2_web_acl" "test-waf" {
  name  = "Test-ACLS-dev"
  scope = "REGIONAL"
  default_action {
    allow {}
  }
  visibility_config {
    cloudwatch_metrics_enabled = false
    metric_name                = "Test-ACLS-metrics-dev"
    sampled_requests_enabled   = false
  }
  tags = {
    #"desc" = "sd  ample test"
  }
 rule {
    name     = "Test-Rate-Limits-dev"
    priority = 0
    statement {
      rate_based_statement {
        aggregate_key_type = "IP"
        limit              = 500
      }
    }
    visibility_config {
      cloudwatch_metrics_enabled = true
      metric_name                = "Test-Rate-Limits-dev"
      sampled_requests_enabled   = true
    }
    action {
      block {
        custom_response {
          response_code = 403
        }
      }
    }
  }
  rule {
    name     = "HEAnet-custom-deny-URL-Rule"
    priority = 8
    action {
      block {}
    }


    statement {

      regex_pattern_set_reference_statement {

        arn = aws_wafv2_regex_pattern_set.example-regex.arn
        field_to_match {
          query_string {}
        }
        text_transformation {
          priority = 0
          type     = "NONE"
        }
      }
    }


    visibility_config {
      cloudwatch_metrics_enabled = true
      metric_name                = "Test-custom-deny-URL-Rule-dev"
      sampled_requests_enabled   = true
    }

  }

}

```

### Expected Behavior
created/updated resourse

### Actual Behavior
There are two issues.
1. I can create resource but every time doing plan/apply I get following output
``
Note: Objects have changed outside of Terraform
Terraform detected the following changes made outside of Terraform since the last "terraform apply":
  aws_wafv2_web_acl.test-waf has changed
  ~ resource "aws_wafv2_web_acl" "test-waf" {
        id         = "663afe0a-40f9-44f7-881a-74cea5ded06c"
        name       = "Test-ACLS-dev"
        tags       = {}
        # (5 unchanged attributes hidden)
        # (4 unchanged blocks hidden)
    }
``
2 . then when you update for example tags in aws_wafv2_web_acl and run apply the terraform throws an error.
`` 
vertex "aws_wafv2_web_acl.test-waf" error: Provider produced inconsistent final plan
``

when modified tags in  aws_wafv2_web_acl   and apply changes:

 vertex "aws_wafv2_web_acl.test-waf" error: Provider produced inconsistent final plan

### Steps to Reproduce

1. `terraform apply`
2.  modify for example tags in aws_wafv2_web_acl 
4. again `terraform apply`

### References

* #0000

**Comment by janul** [comment] 2022-03-13 12:18
I have tested with 
provider registry.terraform.io/hashicorp/aws v4.5.0
So tags are not allowed anymore for aws_wafv2_web_acl   which is good.
However every time I run : `terraform plan`
I get `Note: Objects have changed outside of Terraform`  for **_aws_wafv2_web_acl_**
`terraform apply` doesn't do anything : _**No changes. Your infrastructure matches the configuration.**_

**Comment by chrisnellis** [comment] 2022-08-16 21:15
I was seeing this issue due to setting default tags in the AWS provider. That may be a legitimate outstanding issue

**Comment by dbdoyle182** [comment] 2022-09-22 13:30
I ran into this issue the other day with tags on the WAF, it seems there may be an issue with the way tags are handled by the aws provider for some resources.

Workaround was:

1. Modify the tags via CLI to the desired values.
2. Modify the remote state directly to match the tags I wanted.
3. Run plan to ensure there were no changes related to tags on the wafv2 resources.

**Comment by tolidano** [comment] 2022-09-22 15:48
Dupe of https://github.com/hashicorp/terraform-provider-aws/issues/23992 additional workarounds available there.

**Comment by mmaetzler** [comment] 2022-11-04 23:34
FYI: This issues with WAFv2 has been reported multiple times: 

- #23390
- #23423
- #23936
- #23992
- #24386
- #27175
- #27273
- #27479

**Comment by YakDriver** [comment] 2023-07-13 21:15
**NOTE:** I cannot reproduce this error after trying various configurations. _**Let us know**_ if this is still a problem! If we don't hear and can't reproduce, we plan to close this on or around **July 20, 2023**. The evidence suggests this is OBE (ie, fixed in the interim).

For more details see #23992 ([comment](https://github.com/hashicorp/terraform-provider-aws/issues/23992#issuecomment-1634920741)).

**Comment by YakDriver** [comment] 2023-07-13 21:44
I tried this config to reproduce this specific issue. I got no errors.

Here's my process to attempt to reproduce the problem:
1. `apply` config as is
2. remove `default_tags` and `apply`
3. change `tags` values and `apply`
4. remove `tags` and `apply`
5. `apply` again

### Config

```terraform
provider "aws" {
  default_tags {
    tags = {
      fine_night = "tonight"
      fine_day   = "tomorrow"
    }
  }
}

resource "aws_wafv2_regex_pattern_set" "test" {
  name        = "wafv23992test"
  description = "Example regex pattern set"
  scope       = "REGIONAL"

  regular_expression {
    regex_string = "one"
  }

  regular_expression {
    regex_string = "two"
  }
}

resource "aws_wafv2_web_acl" "test" {
  name  = "wafv23992test"
  scope = "REGIONAL"
  default_action {
    allow {}
  }

  visibility_config {
    cloudwatch_metrics_enabled = false
    metric_name                = "Test-ACLS-metrics-dev"
    sampled_requests_enabled   = false
  }

  tags = {
    "desc" = "sample test"
  }

  rule {
    name     = "Test-Rate-Limits-dev"
    priority = 0
    statement {
      rate_based_statement {
        aggregate_key_type = "IP"
        limit              = 500
      }
    }
    visibility_config {
      cloudwatch_metrics_enabled = true
      metric_name                = "Test-Rate-Limits-dev"
      sampled_requests_enabled   = true
    }
    action {
      block {
        custom_response {
          response_code = 403
        }
      }
    }
  }

  rule {
    name     = "HEAnet-custom-deny-URL-Rule"
    priority = 8
    action {
      block {}
    }

    statement {
      regex_pattern_set_reference_statement {
        arn = aws_wafv2_regex_pattern_set.test.arn
        field_to_match {
          query_string {}
        }
        text_transformation {
          priority = 0
          type     = "NONE"
        }
      }
    }

    visibility_config {
      cloudwatch_metrics_enabled = true
      metric_name                = "Test-custom-deny-URL-Rule-dev"
      sampled_requests_enabled   = true
    }
  }
}
```

**Comment by justinretzolk** [comment] 2023-07-20 17:22
Hi all :wave: As was mentioned above, this issue appears to be fixed when using a minimum Terraform version of 1.4.2 and a minimum AWS Provider version of 4.67.0 (preferably Terraform 1.5.3 or later and AWS Provider 5.8.0 or later). If you experience any additional unexpected behaviors with versions that meet these requirements, please open a new issue so that we can investigate further.

**Closed by justinretzolk** 2023-07-20 17:22 UTC
Labels: bug, waiting-response, service/wafv2
