### ISSUE TITLE
[Enhancement]: Quicksight Resource: aws_quicksight_data_source does not support parameter SecretARN 

### ISSUE THREAD

**Issue by shahriteshj** [hashicorp/terraform-provider-aws#36005] opened 2024-02-28 14:42 UTC
### Description

As a user of Quicksight, I would like to be able to create datasource via Terraform which can be used to connect Quicksight to databases like RDS Oracle using SecretArn

Currently resource aws_quicksight_data_source only supports credentials as either credential_pair (username and password) or copy_source_arn (ARN of datasource that has credential pair that you want to use)

Adding parameter secretARN would help not using static password while creation of datasource

### Affected Resource(s) and/or Data Source(s)

aws_quicksight_data_source

### Potential Terraform Configuration

```terraform
resource "aws_quicksight_data_source" "example" {
# ... other configuration ...

  Credentials = {
    secretArn = 'arn:aws:secretsmanager:us-east-1:account-id:secret:SECRET-NAME'
  }
}
```

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/quicksight_data_source

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment] 2024-03-13 14:56
Duplicate of #28484

**Closed by justinretzolk** 2024-03-13 14:56 UTC
Labels: enhancement, service/quicksight, needs-triage
