### ISSUE TITLE
[Bug]: instance identifier change forces replacement for aws_rds_cluster_instance

### ISSUE THREAD

**Issue by gurpalw** [hashicorp/terraform-provider-aws#35596] opened 2024-02-01 13:24 UTC
### Terraform Core Version

1.7.2

### AWS Provider Version

5.34.0

### Affected Resource(s)

aws_rds_cluster_instance

### Expected Behavior

changing the instance name shouldn't force replacement of the instance

### Actual Behavior

plan shows forced replacement
```
 # module.database.aws_rds_cluster_instance.aurora_postgres_cluster_instance[1] must be replaced
-/+ resource "aws_rds_cluster_instance" "aurora_postgres_cluster_instance" {
redacted
      ~ identifier                            = "redacted-production-tmp" -> "redacted-production-2" # forces replacement
redacted
      
    }
```

### Terraform Configuration Files

included elsewhere

### Steps to Reproduce

1. change instance identifier
2. run plan

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment] 2024-03-13 21:47
Hey @gurpalw 👋 Thank you for taking the time to raise this! Changes to the `identifier` argument trigger a replacement because the function that's used modify an RDS instance [doesn't offer](https://docs.aws.amazon.com/sdk-for-go/api/service/rds/#ModifyDBInstanceInput) the ability to update the identifier. As such, in order to make that modification, the resource must be replaced.

Since this is expected behavior, and not something we're able to change with the current API structure, closing.

**Closed by justinretzolk** 2024-03-13 21:47 UTC
Labels: bug, service/rds, needs-triage
