### ISSUE TITLE
[Enhancement]: Add support for ElastiCache Serverless

### ISSUE THREAD

**Issue by MichaelMandel26** [hashicorp/terraform-provider-aws#34590] opened 2023-11-28 10:38 UTC
### Description

As announced by AWS, there is now a serverless option of ElastiCache. This issue is to request adding support for it.

### Affected Resource(s) and/or Data Source(s)

* aws_elasticache_replication_group
* elasticache_cluster

### References

- [Announcement](https://aws.amazon.com/blogs/aws/amazon-elasticache-serverless-for-redis-and-memcached-now-generally-available/)
- [API Reference](https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_CreateServerlessCache.html)

### Would you like to implement a fix?

No

**Comment by haraldmeister** [comment] 2023-11-29 16:04
On the purpose, it would be nice to implement a new resource as proposed in the followings:

### Requested Resource(s) and/or Data Source(s)

* **aws_elasticache_serverless** (**NEW**)

### Potential Terraform Configuration

```terraform
resource "aws_vpc" "example" {
  cidr_block = "10.0.0.0/16"
}

resource "aws_subnet" "example" {
  vpc_id     = aws_vpc.example.id
  cidr_block = "10.0.1.0/24"

  tags = {
    Name = "my-subnet"
  }
}

resource "aws_elasticache_subnet_group" "example" {
  name       = "my-cache-subnet"
  subnet_ids = [aws_subnet.example.id]

resource "aws_elasticache_user" "default" {
  user_id       = "defaultUserID"
  user_name     = "default"
  access_string = "on ~app::* -@all +@read +@hash +@bitmap +@geo -setbit -bitfield -hset -hsetnx -hmset -hincrby -hincrbyfloat -hdel -bitop -geoadd -georadius -georadiusbymember"
  engine        = "REDIS"
  passwords     = ["password123456789"]
}

resource "aws_elasticache_user_group" "example" {
  engine        = "REDIS"
  user_group_id = "userGroupId"
  user_ids      = [aws_elasticache_user.default.user_id]

  lifecycle {
    ignore_changes = [user_ids]
  }
}


## Redis cluster

resource "aws_elasticache_serverless" "example" {
  cluster_id           = "cluster-example" #mandatory
  engine               = "redis" #mandatory | or "memcached"
  description          = "Description"
  security_group_ids   = ["sg-0exxxxxyyyyzzz"]
  encryption           = "aws/elasticache" # or KMS ARN
  user_group           = aws_elasticache_user_group.example.user_group_id
  subnet_group_name    = aws_elasticache_subnet_group.example.name
  automatic_backup     = false
  usage_limits = {
     memory  =  100 #GB
     compute =  10000 #ECPUs
  }
  tags = {
    Name = "my-serverless-cache"
  }
}
```

**Comment by meetreks** [comment] 2023-12-06 14:37
I have looked at the changes needed and picked it up. Will update in this forum.

**Comment by meetreks** [comment] 2023-12-12 22:19
Done with the resource creation, writing some acpt tests. Will aim for this weeks release for sure.

**Comment by meetreks** [comment] 2023-12-13 15:54
I  ran some tests and can see the config working on the console....last bits and pieces to tidy up. Getting some panic errors which I hope will be fixed tody

**Comment by meetreks** [comment] 2023-12-14 14:53
Most tests work now, just some minor tidy ups and some documentation to go. Nearly there...

**Comment by meetreks** [comment] 2023-12-15 13:32
ACCP tests are all fine. Ran a few more today and all are working as intended. Getting ready for the PR now!

**Comment by meetreks** [comment] 2023-12-15 17:23
Please track this PR for more details -- https://github.com/hashicorp/terraform-provider-aws/pull/34951
I will watch the pipeline and see if anything comes out of the woodwork

**Closed** 2024-01-03 23:31 UTC
Labels: enhancement, new-resource, service/elasticache

**Comment by Menahem1** [comment] 2024-01-12 15:45
Hello,
How to get the endpoint (attribute reference) with only the address on string format ? 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_serverless_cache

**Comment by TonyLovesDevOps** [comment] 2024-01-12 16:07
> Hello, How to get the endpoint (attribute reference) with only the address on string format ? https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_serverless_cache

It seems that the `endpoint` attribute is exposed as a list. This seemed to work for me:

```hcl
resource "aws_elasticache_serverless_cache" "example" {
  engine = "memcached"
  name   = "example"
}

output "example_endpoint_address" {
  value = aws_elasticache_serverless_cache.example.endpoint.0.address
}
```
