### ISSUE TITLE
[Bug]: Terrafrom doesn't allow update a aws_imagebuilder_image_recipe resource with a new AMI ID

### ISSUE THREAD

**Issue by khaledfarah** [hashicorp/terraform-provider-aws#28677] opened 2023-01-05 05:11 UTC
### Terraform Core Version

1.3.6

### AWS Provider Version

4.35.0

### Affected Resource(s)

* aws_imagebuilder_image_recipe

### Expected Behavior

When updating an `aws_imagebuilder_image_recipe` resource that Terraform created with a new AMI ID, it should update without issues, or its version number should auto-update. This behavior is standard in AWS other resources. 

### Actual Behavior

- The process fails with a ResourceAlreadyExistsExceptionerror message 

### Terraform Configuration Files

resource "aws_imagebuilder_image_recipe" "this" {
}

### Steps to Reproduce

- Create an `aws_imagebuilder_image_recipe` resource
- Apply it
- Update the "AMI_ID" field
- Try to apply it again

### Would you like to implement a fix?

None

**Comment by mattburgess** [comment] 2023-01-30 22:04
@khaledfarah - the underlying AWS service doesn't allow for Image Recipe's to be updated in place. I'm interested in your description of Terraform's behaviour here though; All of that resource's attributes, except for `tags` are marked as `ForceNew` which should have meant that if you made any changes to your `aws_imagebuilder_image_recipe` resource's attributes it should have attempted to delete the old recipe and create a new one. You mention the "AMI_ID" field in your original report but I see no such attribute. Did you mean the `parent_image` attribute? If you're able to provide the resource configuration with both its original and updated attribute values I can see if I can reproduce here.

**Comment by justinretzolk** [comment] 2023-11-17 19:42
Since we haven't heard back in a while, I'm going to close this issue out. If you're still having troubles, or have future issues with the AWS Provider, please feel free to open a new issue (referencing this one for context as needed).

**Closed by justinretzolk** 2023-11-17 19:41 UTC
Labels: bug, waiting-response, service/imagebuilder
