### ISSUE TITLE
aws_rds_cluster.rds_cluster is empty tuple when using resource "aws_db_proxy_target"

### ISSUE THREAD

**Issue by nirsv** [hashicorp/terraform-provider-aws#15486] opened 2020-10-05 13:26 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_db_proxy_target

### Terraform Configuration Files

```hcl
resource "aws_db_proxy_target" "rds-db-proxy-target" {
  db_cluster_identifier = aws_rds_cluster.rds_cluster.id
  db_proxy_name          = aws_db_proxy.rds-db-proxy.name
  target_group_name      = aws_db_proxy_default_target_group.rds-db-proxy-target-group.name
}
```

### Debug Output
```hcl
Error: Unsupported attribute

  on rds.tf line 78, in resource "aws_db_proxy_target" "rds-db-proxy-target":
  78:   db_cluster_identifier = aws_rds_cluster.rds_cluster.id
    |----------------
    | aws_rds_cluster.rds_cluster is empty tuple
```
This value does not have any attributes.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by anGie44** [comment] 2020-10-06 00:10
Hi @nirsv, thank you for creating this issue! Do you mind providing the complete configuration or the configuration you are using for the `rds_cluster` resource to further investigate the behavior you're experiencing?

**Comment by nirsv** [comment] 2020-10-06 07:41
```
resource "aws_rds_cluster" "rds_cluster" {
  cluster_identifier = "my-rds-cluster"
  apply_immediately            = true
  db_subnet_group_name         = var.rds_subnet_group_name
  availability_zones           = var.availability_zones
  engine                       = "aurora-postgresql"
  engine_version               = "10.7"
  backup_retention_period      = 7
  preferred_backup_window      = "03:22-03:52"
  preferred_maintenance_window = "sun:08:04-sun:08:34"
  master_username              = "master_username"
  master_password              = "master_password"
  skip_final_snapshot          = true
  vpc_security_group_ids = [data.aws_security_group.default_sg.id]
  deletion_protection    = true
}
```

**Comment by tyg03485** [comment] 2020-11-10 09:38
Same here

**Comment by anGie44** [comment] 2020-11-11 15:34
Hi @nirsv and @tyg03485 -- do you mind providing the terraform version and AWS Provider version you used when coming across this error? 

I haven't been able to reproduce a scenario in terraform 0.12/0.13.3 using the latest AWS Provider version `3.14.1` with this type of config below. 
**The only noticeable difference here is that the `rds_cluster` resource `engine_version` uses `11.7` (using `10.7` returned apply time error: `Error: error registering RDS DB Proxy (example/default) Target: InvalidParameterValue: Unsupported Database engine or engine mode for DB Cluster`):

```hcl
resource "aws_db_proxy" "test" {
  depends_on = [
    aws_secretsmanager_secret_version.test,
    aws_iam_role_policy.test
  ]

  name                   = "example"
  debug_logging          = false
  engine_family          = "POSTGRESQL"
  idle_client_timeout    = 1800
  require_tls            = true
  role_arn               = aws_iam_role.test.arn
  vpc_security_group_ids = [aws_security_group.test.id]
  vpc_subnet_ids         = aws_subnet.test.*.id

  auth {
    auth_scheme = "SECRETS"
    description = "test"
    iam_auth    = "DISABLED"
    secret_arn  = aws_secretsmanager_secret.test.arn
  }
}

resource "aws_db_subnet_group" "test" {
  name       = "example"
  subnet_ids = aws_subnet.test.*.id
}

# Secrets Manager setup

resource "aws_secretsmanager_secret" "test" {
  name                    = "example"
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "test" {
  secret_id     = aws_secretsmanager_secret.test.id
  secret_string = "{\"username\":\"db_user\",\"password\":\"db_user_password\"}"
}

# IAM setup

resource "aws_iam_role" "test" {
  name               = "example"
  assume_role_policy = data.aws_iam_policy_document.assume.json
}

data "aws_iam_policy_document" "assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["rds.amazonaws.com"]
    }
  }
}

resource "aws_iam_role_policy" "test" {
  role   = aws_iam_role.test.id
  policy = data.aws_iam_policy_document.test.json
}

data "aws_iam_policy_document" "test" {
  statement {
    actions = [
      "secretsmanager:GetRandomPassword",
      "secretsmanager:CreateSecret",
      "secretsmanager:ListSecrets",
    ]
    resources = ["*"]
  }

  statement {
    actions   = ["secretsmanager:*"]
    resources = [aws_secretsmanager_secret.test.arn]
  }
}

# VPC setup

data "aws_availability_zones" "available" {
  state = "available"

  filter {
    name   = "opt-in-status"
    values = ["opt-in-not-required"]
  }
}

resource "aws_vpc" "test" {
  cidr_block = "10.0.0.0/16"
}

resource "aws_security_group" "test" {
  name   = "example"
  vpc_id = aws_vpc.test.id

  ingress {
    from_port = 0
    to_port   = 65535
    protocol  = "tcp"
    self      = true
  }
}

resource "aws_subnet" "test" {
  count             = 2
  cidr_block        = cidrsubnet(aws_vpc.test.cidr_block, 8, count.index)
  availability_zone = data.aws_availability_zones.available.names[count.index]
  vpc_id            = aws_vpc.test.id
}

data "aws_rds_engine_version" "test" {
  engine = "aurora-postgresql"
}

resource "aws_rds_cluster" "test" {
  apply_immediately            = true
  availability_zones           = [data.aws_availability_zones.available.names[0], data.aws_availability_zones.available.names[1]]
  backup_retention_period      = 7
  cluster_identifier           = "example"
  db_subnet_group_name         = aws_db_subnet_group.test.id
  deletion_protection          = false
  engine                       = data.aws_rds_engine_version.test.engine
  engine_version               = data.aws_rds_engine_version.test.version
  master_username              = "test"
  master_password              = "testtest"
  preferred_backup_window      = "03:22-03:52"
  preferred_maintenance_window = "sun:08:04-sun:08:34"
  skip_final_snapshot          = true
  vpc_security_group_ids       = [aws_security_group.test.id]
}

resource "aws_db_proxy_default_target_group" "test" {
  db_proxy_name = aws_db_proxy.test.name

  connection_pool_config {}
}

resource "aws_db_proxy_target" "test" {
  db_cluster_identifier = aws_rds_cluster.test.id
  db_proxy_name         = aws_db_proxy.test.name
  target_group_name     = aws_db_proxy_default_target_group.test.name
}
```
Also debug/trace logs would be greatly appreciated to better pinpoint the cause of error or if not readily available, a configuration with the dependencies would be of great help 🙏

**Comment by bflad** [comment] 2021-01-22 17:34
It's been a long time since we heard from you here so we're going to close this out. If you're still having this problem, please feel free to reply with answers to the question above.

**Closed by bflad** 2021-01-22 17:34 UTC
Labels: service/rds, waiting-response
