### ISSUE TITLE
aws_eks_cluster fails to delete on destroy

### ISSUE THREAD

**Issue by spanktar** [hashicorp/terraform-provider-aws#18570] opened 2021-04-05 17:40 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
terraform -v
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/aws v3.35.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
```

### Description

When I run Terraform destroy, the EKS cluster is listed as slated to be destroyed, but is never listed in the actions taken.

```
# aws_eks_cluster.default will be destroyed
  - resource "aws_eks_cluster" "default" {
      - arn                       = "arn:aws:eks:us-east-1:1234567890:cluster/eks-cluster" -> null
      - certificate_authority     = [
          - {
              - data = "REDACTED"
            },
        ] -> null
      - created_at                = "2021-04-01 19:21:27.065 +0000 UTC" -> null
      - enabled_cluster_log_types = [
          - "api",
          - "audit",
          - "authenticator",
          - "controllerManager",
          - "scheduler",
        ] -> null
      - endpoint                  = "https://ASDFGHJKLQWERTYUIOPZXCVBNMQWERTY.gr7.us-east-1.eks.amazonaws.com" -> null
      - id                        = "eks-cluster" -> null
      - identity                  = [
          - {
              - oidc = [
                  - {
                      - issuer = "https://oidc.eks.us-east-1.amazonaws.com/id/ASDFGHJKLQWERTYUIOPZXCVBNMQWERTY"
                    },
                ]
            },
        ] -> null
      - name                      = "eks-cluster" -> null
      - platform_version          = "eks.4" -> null
      - role_arn                  = "arn:aws:iam::1234567890:role/eks-cluster-assume-role" -> null
      - status                    = "ACTIVE" -> null
      - tags                      = {
          - "Name"          = "rwd-dev-nlp-beta-eks-cluster"
        } -> null
      - version                   = "1.18" -> null

      - kubernetes_network_config {
          - service_ipv4_cidr = "172.20.0.0/16" -> null
        }

      - vpc_config {
          - cluster_security_group_id = "sg-05ace68ca45dc621e" -> null
          - endpoint_private_access   = false -> null
          - endpoint_public_access    = true -> null
          - public_access_cidrs       = [
              - "0.0.0.0/0",
            ] -> null
          - security_group_ids        = [
              - "sg-079089114b58b3892",
            ] -> null
          - subnet_ids                = [
              - "subnet-01c66ec307530952d",
              - "subnet-044774425d99d62ab",
              - "subnet-09c64c4b2918bd4a3",
              - "subnet-09f3216220dc6ec8d",
              - "subnet-0ef4e786dd603ddd3",
              - "subnet-0f8460ff9ca3f792d",
            ] -> null
          - vpc_id                    = "vpc-12345678901234567" -> null
        }
    }
```

Then on destroy, it is missing from the list of things it destroys.

### Affected Resource(s)

* aws_eks_cluster
* aws_iam_openid_connect_provider

### Terraform Configuration Files

```hcl
resource "aws_eks_cluster" "default" {
  name     = local.name_eks
  role_arn = aws_iam_role.eks_assume_role.arn
  version  = "1.18"

  enabled_cluster_log_types = [
      "api",
      "audit",
      "authenticator",
      "controllerManager",
      "scheduler",
  ]

  vpc_config {
    security_group_ids = [aws_security_group.eks_cluster.id]
    subnet_ids         = concat(aws_subnet.private.*.id, aws_subnet.public.*.id)
  }

  depends_on = [
    aws_iam_role_policy_attachment.eks_AmazonEKSClusterPolicy,
    aws_iam_role_policy_attachment.eks_AmazonEKSServicePolicy,
    aws_cloudwatch_log_group.eks_cloudwatch_log_group
  ]

  tags = merge(local.tags,
    map(
      "Name", format("%s-eks-cluster", local.name)
    )
  )
}

### OIDC config
resource "aws_iam_openid_connect_provider" "cluster_oidc_provider" {
  client_id_list  = ["sts.amazonaws.com"]
  thumbprint_list = [data.tls_certificate.cluster.certificates.0.sha1_fingerprint]
  url             = aws_eks_cluster.default.identity.0.oidc.0.issuer
}

data "tls_certificate" "cluster" {
  url = aws_eks_cluster.default.identity.0.oidc.0.issuer
}
```

### Expected Behavior

The EKS Cluster should be deleted on destroy.

### Actual Behavior

The EKS Cluster was not deleted on destroy.

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

### Important Factoids

This was working fine until I added the OIDC stuff in order to use the new AWS EBS/EFS CSI StorageDrivers.

The Leaning Tower of Pisa took 344 years to build, beginning in August 1173. Nobody said the factoids had to be relevant.

* #0000

**Comment by spanktar** [comment] 2021-04-16 17:02
Happy to help triage if needed.

**Comment by mattburgess** [comment] 2023-01-16 22:25
@spanktar I know it's been a while but I'm unable to replicate this issue given an EKS cluster and the OpenID connect provider config. If you're able to reproduce this using recent versions of Terraform and the AWS provider then I'm happy to try to triage/reproduce this with you.

**Comment by bryantbiggs** [comment] 2024-09-05 14:59
@spanktar is this issue still relevant or can we close it out?

**Comment by justinretzolk** [comment] 2024-11-11 18:37
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.

**Closed by justinretzolk** 2024-11-11 18:37 UTC
Labels: bug, waiting-response, service/eks
