### ISSUE TITLE
[Bug]: Error: reading AWS SSO Identity Store Group Data Source: operation error identitystore: GetGroupId, https response error StatusCode: 400

### ISSUE THREAD

**Issue by popsicleslayer** [hashicorp/terraform-provider-aws#28139] opened 2022-12-02 15:21 UTC
### Terraform Core Version

1.3.6

### AWS Provider Version

4.45

### Affected Resource(s)

data "aws_identitystore_group"

### Expected Behavior

Terraform should have been planned and applied as usual. There should be no problem retrieving any of the information regarding the identity store group.

### Actual Behavior

For every request made there is an HTTPS response error

### Relevant Error/Panic Output Snippet

```shell
`│ Error: reading AWS SSO Identity Store Group Data Source (): operation error identitystore: GetGroupId, https response error StatusCode: 400, RequestID: xxxxxxxxx, AccessDeniedException: User: arn:aws:sts::xxxxxxxxxxxx:assumed-role/role/configure is not authorized to perform: identitystore:GetGroupId because no identity-based policy allows the identitystore:GetGroupId action
│ 
│   with module.readonly_assignment.data.aws_identitystore_group.this["email@email.com"],
│   on .terraform/modules/readonly_assignment/main.tf line 1, in data "aws_identitystore_group" "this":
│    1: data "aws_identitystore_group" "this" {
`
```

### Terraform Configuration Files

Data source:

```terraform
data "aws_identitystore_group" "this" {
  for_each          = local.group_list
  identity_store_id = local.identity_store_id

   alternate_identifier {
     unique_attribute {
       attribute_path  = "DisplayName"
       attribute_value = each.key
     }
   }
}
```

Role permissions:

```terraform
...
{
            "Sid": "IdentityStore",
            "Effect": "Allow",
            "Action": [
                "identitystore:DescribeUser",
                "identitystore:ListUsers",
                "identitystore:DescribeGroup",
                "identitystore:ListGroups"
            ],
            "Resource": "*"
        }
```

### Steps to Reproduce

terraform plan

### Important Factoids

At first, I thought that this was filter field deprecation related, but after modifying the code to use the new block (alternate_identifier), the error persisted. Only reverting to a provider version = 4.37 allowed the plan to succeed. I reverted this far back, as this code is part of a pipeline that runs on a monthly cron job, and that was the version available when it last succeeded.

### Would you like to implement a fix?

None

**Comment by mariusmitrofan** [comment] 2022-12-12 08:38
Same here!

**Comment by adamthomason** [comment] 2022-12-14 16:12
I'm also seeing this issue. Is this related to the recent rebrand of SSO to IAM Identity Center?

**Comment by Phylu** [comment] 2022-12-23 09:16
I think, this is a duplicate of: https://github.com/hashicorp/terraform-provider-aws/issues/27830

**Comment by ewbankkit** [comment] 2023-01-17 20:40
@popsicleslayer We were unable to reproduce this in our acceptance tests, so I went ahead and restored the old `filter` functionality (using the `ListGroups` API) in https://github.com/hashicorp/terraform-provider-aws/pull/28937.
If this does not fix the issue, please open a new issue.
Thanks.

**Closed** 2023-01-17 20:40 UTC
Labels: bug, service/identitystore
