### ISSUE TITLE
Cannot create canary: minimum field size of 1, GetCanaryInput.Name.

### ISSUE THREAD

**Issue by sentinel09** [hashicorp/terraform-provider-aws#20053] opened 2021-07-02 10:23 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
* CLI version: 0.14.6
* Provider version: 3.47.0

### Affected Resource(s)

* aws_synthetics_canary

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_synthetics_canary" "canary" {
  name                 = var.canary_name
  artifact_s3_location = "s3://${aws_s3_bucket.cloudwatch_canary_bucket.id}/canary"
  execution_role_arn   = aws_iam_role.canary_iam_role.arn
  handler              = "healthcheck.handler"
  runtime_version      = "syn-python-selenium-1.0"
  zip_file             = "${path.module}/files/canary.zip"

  schedule {
    expression = "rate(1 minute)"
  }
  run_config {
    timeout_in_seconds = 60
  }
}

data "archive_file" "healtchcheck_canary" {
  type        = "zip"
  output_path = "${path.module}/files/canary.zip"
  source {
    content  = file("../tpl/npd/canary_python.tpl")
    filename = "python/scripts/canary_python.py"
  }
}
```

### Debug Output
```hcl
module.canary.aws_synthetics_canary.canary: Creating...

Error: error reading Synthetics Canary: InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, GetCanaryInput.Name.


  on ../modules/cloudwatch/main.tf line 126, in resource "aws_synthetics_canary" "canary":
 126: resource "aws_synthetics_canary" "canary" {
```

### Expected Behavior
Canary created.

### Actual Behavior
Canary not created.
Value for var.canary_name is "test_canary"

### Steps to Reproduce

1. `terraform plan -out=planfile`
2. `terraform apply planfile`

**Comment by DrFaust92** [comment] 2021-07-07 19:02
Duplicate of #18636

**Closed by DrFaust92** 2021-07-07 19:02 UTC
Labels: bug, service/synthetics
