### ISSUE TITLE
Issue downloading terraform provider - aws_2.34.0 - hangs

### ISSUE THREAD

**Issue by neelam-007** [hashicorp/terraform-provider-aws#12925] opened 2020-04-21 17:10 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_2.34.0

### Expected Behavior
plugin downloaded successfully

### Actual Behavior

terraform init hangs:
`Downloading plugin for provider "aws" (2.34.0)`

### Steps to Reproduce

1. `terraform init`

### Important Factoids
This was working yesterday
### References

**Comment by bflad** [comment] 2020-07-07 18:14
Hi @neelam-007 👋  Are you still having this issue? In order to continue troubleshooting this, we would need to see [Terraform debug logs](https://www.terraform.io/docs/internals/debugging.html), e.g. `TF_LOG=debug terraform init`. Thanks.

**Comment by bflad** [comment] 2021-01-22 17:22
It's been a long time since we heard from you here so we're going to close this out. If you're still having this problem, please feel free to open a new issue and complete all of the information requested in the [Bug Report template](https://github.com/hashicorp/terraform-provider-aws/issues/new?template=Bug_Report.md) so that we can attempt to understand and reproduce the problem.

**Closed by bflad** 2021-01-22 17:22 UTC
Labels: provider, waiting-response
