### ISSUE TITLE
Appstream 2.0 error in domain_join_info

### ISSUE THREAD

**Issue by bommireddy98** [hashicorp/terraform-provider-aws#26682] opened 2022-09-07 07:25 UTC
### Terraform CLI and Terraform AWS Provider Version
C:\data\repo\appstream\aws>terraform -v
Terraform v1.1.9
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v4.22.0

### Affected Resource(s)
# Image builder
resource "aws_appstream_image_builder" "mds_appstream_image_builder" {
  name                           = var.image_builder_name
  description                    = var.image_builder_description
  display_name                   = var.image_builder_display_name
  enable_default_internet_access = var.image_builder_enable_default_internet_access
  image_name                     = var.image_builder_image_name
  instance_type                  = var.image_builder_instance_type
  iam_role_arn                   = var.image_builder_iam_role_arn
  vpc_config {
    subnet_ids         = [var.subnet_id]
    security_group_ids = [var.security_group_ids]
  }
  tags = var.tags
}

### Terraform Configuration Files

```hcl

region         = "us-east-1"
bucket         = "state.us-east-1.mds.bidcomp-dev.network"
dynamodb_table = "mds-us-east-1-state-lock"

### Expected Behavior

No Error, Image builder should be successful implemented

### Actual Behavior

│ Error: error setting `domain_join_info` for AppStream ImageBuilder (mds-appstream-image-builder-dev-us-east-1): domain_join_info: '': source data must be an array or slice, got map
│ 
│   with module.appstream.aws_appstream_image_builder.mds_appstream_image_builder,
│   on modules/appstream/main.tf line 64, in resource "aws_appstream_image_builder" "mds_appstream_image_builder":
│   64: resource "aws_appstream_image_builder" "mds_appstream_image_builder" {
│ 

Could you please find a solution for this?

**Comment by justinretzolk** [comment] 2022-09-13 17:45
Hey @bommireddy98 👋 Thanks for taking the time to submit this issue. It looks like this is a duplicate of #26677. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #26677.

**Closed by justinretzolk** 2022-09-13 17:45 UTC
Labels: service/appstream, needs-triage
