### ISSUE TITLE
tests/db_proxy: Too many transfer encodings on Terraform 0.15.0-alpha

### ISSUE THREAD

**Issue by YakDriver** [hashicorp/terraform-provider-aws#17779] opened 2021-02-23 21:13 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Acceptance Test

These `aws_db_proxy` tests produce `transport connection broken: too many transfer encodings` errors on Terraform v0.15.0-alpha:

```
TestAccAWSDBProxy_disappears
    resource_aws_db_proxy_test.go:480: unexpected PreCheck error: RequestError: send request failed
        caused by: Post "https://rds.us-west-2.amazonaws.com/": net/http: HTTP/1.x transport connection broken: too many transfer encodings: ["chunked" "chunked"]
--- FAIL: TestAccAWSDBProxy_disappears (2952.57s)

TestAccAWSDBProxy_IdleClientTimeout
    resource_aws_db_proxy_test.go:480: unexpected PreCheck error: RequestError: send request failed
        caused by: Post "https://rds.us-west-2.amazonaws.com/": net/http: HTTP/1.x transport connection broken: too many transfer encodings: ["chunked" "chunked"]
--- FAIL: TestAccAWSDBProxy_IdleClientTimeout (3017.58s)

TestAccAWSDBProxy_Name
    resource_aws_db_proxy_test.go:480: unexpected PreCheck error: RequestError: send request failed
        caused by: Post "https://rds.us-west-2.amazonaws.com/": net/http: HTTP/1.x transport connection broken: too many transfer encodings: ["chunked" "chunked"]
--- FAIL: TestAccAWSDBProxy_Name (2977.42s)

TestAccAWSDBProxy_Tags
    resource_aws_db_proxy_test.go:480: unexpected PreCheck error: RequestError: send request failed
        caused by: Post "https://rds.us-west-2.amazonaws.com/": net/http: HTTP/1.x transport connection broken: too many transfer encodings: ["chunked" "chunked"]
--- FAIL: TestAccAWSDBProxy_Tags (3082.71s)

TestAccAWSDBProxyDefaultTargetGroup_disappears
    resource_aws_db_proxy_test.go:480: unexpected PreCheck error: RequestError: send request failed
        caused by: Post "https://rds.us-west-2.amazonaws.com/": net/http: HTTP/1.x transport connection broken: too many transfer encodings: ["chunked" "chunked"]
--- FAIL: TestAccAWSDBProxyDefaultTargetGroup_disappears (2817.32s)

TestAccAWSDBProxyDefaultTargetGroup_MaxConnectionsPercent
    resource_aws_db_proxy_test.go:480: unexpected PreCheck error: RequestError: send request failed
        caused by: Post "https://rds.us-west-2.amazonaws.com/": net/http: HTTP/1.x transport connection broken: too many transfer encodings: ["chunked" "chunked"]
--- FAIL: TestAccAWSDBProxyDefaultTargetGroup_MaxConnectionsPercent (3244.17s)
```

### Affected Resources

* aws_db_proxy

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_secretsmanager_secret" "test" {
  name                    = "yakame"
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "test" {
  secret_id     = aws_secretsmanager_secret.test.id
  secret_string = "{\"username\":\"db_user\",\"password\":\"db_user_password\"}"
}

# IAM setup

resource "aws_iam_role" "test" {
  name               = "yakole"
  assume_role_policy = data.aws_iam_policy_document.assume.json
}

data "aws_iam_policy_document" "assume" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      type        = "Service"
      identifiers = ["rds.amazonaws.com"]
    }
  }
}

resource "aws_iam_role_policy" "test" {
  role   = aws_iam_role.test.id
  policy = data.aws_iam_policy_document.test.json
}

data "aws_iam_policy_document" "test" {
  statement {
    actions = [
      "secretsmanager:GetRandomPassword",
      "secretsmanager:CreateSecret",
      "secretsmanager:ListSecrets",
    ]
    resources = ["*"]
  }

  statement {
    actions   = ["secretsmanager:*"]
    resources = [aws_secretsmanager_secret.test.arn]
  }
}

# VPC setup

data "aws_availability_zones" "available" {
  state = "available"

  filter {
    name   = "opt-in-status"
    values = ["opt-in-not-required"]
  }
}

resource "aws_vpc" "test" {
  cidr_block = "10.0.0.0/16"

  tags = {
    Name = "yakag"
  }
}

resource "aws_security_group" "test" {
  name   = "yakroup"
  vpc_id = aws_vpc.test.id
}

resource "aws_subnet" "test" {
  count             = 2
  cidr_block        = cidrsubnet(aws_vpc.test.cidr_block, 8, count.index)
  availability_zone = data.aws_availability_zones.available.names[count.index]
  vpc_id            = aws_vpc.test.id

  tags = {
    Name = "yaknet-${count.index}"
  }
}

resource "aws_db_proxy" "test" {
  depends_on = [
    aws_secretsmanager_secret_version.test,
    aws_iam_role_policy.test
  ]

  name                   = "yakoxy"
  engine_family          = "MYSQL"
  role_arn               = aws_iam_role.test.arn
  vpc_security_group_ids = [aws_security_group.test.id]
  vpc_subnet_ids         = aws_subnet.test.*.id

  auth {
    auth_scheme = "SECRETS"
    description = "test"
    iam_auth    = "DISABLED"
    secret_arn  = aws_secretsmanager_secret.test.arn
  }
}
```

### References

* https://github.com/hashicorp/terraform/releases/tag/v0.15.0-alpha20210210

**Comment by bflad** [comment] 2021-02-24 00:17
I believe this is a duplicate of https://github.com/hashicorp/terraform-provider-aws/issues/17010 and not Terraform 0.15 specific (more Go version specific).

**Closed** 2021-02-25 17:02 UTC
Labels: alpha-testing, service/ec2, service/iam, service/rds, service/secretsmanager, terraform-0.15, tests
