### ISSUE TITLE
[Bug]:`aws_grafana_workspace_api_key` - `seconds_to_live` change should force recreation

### ISSUE THREAD

**Issue by dpattmann** [hashicorp/terraform-provider-aws#27662] opened 2022-11-04 22:59 UTC
### Terraform Core Version

1.3.2

### AWS Provider Version

4.38.0

### Affected Resource(s)

* aws_grafana_workspace_api_key

### Expected Behavior

When changing the `seconds_to_live` parameter, the resource should be replaced.

### Actual Behavior

Terraform tries to update the resource, but the update has no effect.

### Terraform Configuration Files

```
resource "aws_iam_role" "test" {
  name = "delete-me"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Sid    = ""
        Principal = {
          Service = "grafana.amazonaws.com"
        }
      },
    ]
  })
}

resource "aws_grafana_workspace" "test" {
  account_access_type      = "CURRENT_ACCOUNT"
  authentication_providers = ["SAML"]
  permission_type          = "SERVICE_MANAGED"
  role_arn                 = aws_iam_role.test.arn
}

resource "aws_grafana_workspace_api_key" "test" {
  key_name        = "delete-me"
  key_role        = "EDITOR"
  seconds_to_live = 3600
  workspace_id    = aws_grafana_workspace.test.id
}

terraform {
  required_version = ">= 1.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4.8"
    }
  }
}

provider "aws" {
  profile = "default"
  region = "eu-central-1"
}
```

### Steps to Reproduce

Change the `seconds_to_live` parameter

```
resource "aws_grafana_workspace_api_key" "grafana_api_key" {
  key_name        = "test-key"
  key_role        = "ADMIN"
  seconds_to_live = 600
  workspace_id    = aws_grafana_workspace.grafana_workspace.id
}
```

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment] 2022-11-07 20:29
Hey @dpattmann 👋 Thanks for taking the time to submit this issue. It looks like this is a duplicate of #27123. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of that one.

Duplicate of #27123

**Closed by justinretzolk** 2022-11-07 20:29 UTC
Labels: bug, service/iam, needs-triage, service/grafana
