### ISSUE TITLE
Can't import _domainkey aws_route53_record.

### ISSUE THREAD

**Issue by adamdonahue** [hashicorp/terraform-provider-aws#21121] opened 2021-10-01 17:23 UTC
```
$ terraform version
Terraform v0.13.7

+ provider registry.terraform.io/hashicorp/aws v3.60.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.4
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

Attempting to import the following record fails:

```
$ terraform import 'aws_route53_record.route53_alias["3x6jr7puidd7aqtkh56b2fiagfc2xcgy._domainkey.our-domain.com."]' 'Z04069581CFCSW4QREQQE_3x6jr7puidd7aqtkh56b2fiagfc2xcgy._domainkey.our-domain.com._CNAME'

Error: InvalidInput: 1 validation error detected: Value 'domainkey.our-domain.com.' at 'startRecordType' failed to satisfy constraint: Member must satisfy enum value set: [AAAA, A, CAA, NS, SOA, SPF, MX, PTR, CNAME, DS, TXT, SRV, NAPTR]
	status code: 400, request id: b2b5ba0a-9b97-43d4-93c7-fd40bc12c4b8
```

My impression from reading through prior issues is that this was fixed, although it's not clear if a syntax change of the import format is required.  How can we work around the issue?  What am I missing here?  (The fixed bug is "unable to import records with underscores" -- which implies that any number of underscores would be allowed -- but it seems only to handle _leading_ underscores?)

(For the record, using underscores as a delimiter in this way with no way of escaping them seems non-ideal.  Shouldn't we at least use a delimiter that would not be accepted within a valid AWS record name to simplify things?)

**Comment by justinretzolk** [comment] 2021-10-01 19:04
Hey @adamdonahue 👋 Thanks for taking the time to submit this issue. It looks like this is a duplicate of #16213 (which actually looks like it has an open PR that will fix it waiting for review!). We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #16213.

**Closed by justinretzolk** 2021-10-01 19:04 UTC
Labels: needs-triage

**Comment by adamdonahue** [comment] 2021-10-01 19:47
No problem, thanks for the pointer!
