### ISSUE TITLE
Add support for AuthTokenUpdateStrategy to aws_elasticache_replication_group

### ISSUE THREAD

**Issue by karlismelderis** [hashicorp/terraform-provider-aws#11524] opened 2020-01-08 14:18 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Every time auth_token changes terraform is destroying Redis cluster.
it should/could be possible to set new token without destroy if TF would use AuthTokenUpdateStrategy option.

### New or Affected Resource(s)

* aws_elasticache_replication_group

### Potential Terraform Configuration

```hcl
resource "aws_elasticache_replication_group" "as_redis" {
  auth_token = "some_super_secret_new_token"
  auth_token_update_strategy = "<set|rotate>"
  engine = "redis"
  transit_encryption_enabled = true
  lifecycle {
    prevent_destroy = true
  }
}
```

### References

* #0000

**Comment by christoph-h** [comment] 2021-05-18 21:38
There is an open PR, that should allow to update the auth token using the rotate strategy: https://github.com/hashicorp/terraform-provider-aws/pull/16203

**Comment by bskrtich** [comment] 2022-05-03 17:46
The code for this request was merged last year, This issue can be closed.

**Comment by Israphel** [comment] 2022-10-17 20:48
> The code for this request was merged last year, This issue can be closed.

where? I don't see the feature 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_replication_group#auth_token

**Comment by hskrtich** [comment] 2022-10-17 20:53
@Israphel Here is the PR for it. https://github.com/hashicorp/terraform-provider-aws/pull/16203

**Comment by hskrtich** [comment] 2022-10-17 20:53
This issue is a dupe of https://github.com/hashicorp/terraform-provider-aws/issues/15561

**Comment by Israphel** [comment] 2022-10-17 21:30
so, they didn't add the update strategy, they're allowing to change auth_token outside

**Comment by hskrtich** [comment] 2022-10-17 23:34
ah sorry, I was confused with the description of this issue. The "Every time auth_token changes terraform is destroying Redis cluster." part is fixed. The "AuthTokenUpdateStrategy option" part is not implemented.

**Comment by varkey** [comment] 2023-08-10 12:23
Adding support for `AuthTokenUpdateStrategy` will also help if one wants to migration from `Redis Auth` to `RBAC` which would require the `AuthTokenUpdateStrategy` to be set to `DELETE`

https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Clusters.RBAC.html#Migrate-From-RBAC-to-Auth

**Closed** 2023-11-21 14:39 UTC
Labels: enhancement, service/elasticache, prioritized
