### ISSUE TITLE
[Bug]: Assigning multiple role policies using  aws_iam_role_policy_attachment fails with ConcurrentModification error

### ISSUE THREAD

**Issue by jandryse** [hashicorp/terraform-provider-aws#34371] opened 2023-11-13 12:58 UTC
### Terraform Core Version

1.6.2

### AWS Provider Version

5.25.0

### Affected Resource(s)

aws_iam_role_policy_attachment

### Expected Behavior

It should be possible to assign multiple policies to the same role.

### Actual Behavior

When multiple policies are assigned, it very often fails with ConcurrentModification exception. It may be related to some changes in AWS, since the same code, with the same version of terraform and aws provider was working last week.

### Relevant Error/Panic Output Snippet

```shell
Error: attaching policy arn:aws:iam::12545454:policy/test-policy-5 to IAM Role test-role: ConcurrentModification: Another request updating the entity is in progress. Please try again later.
│ 	status code: 409, request id: aaaaa-bbbbb-ccccc-ddddd-fea34e635b6a
│
│   with aws_iam_role_policy_attachment.test_attach[5],
│   on init.tf line 101, in resource "aws_iam_role_policy_attachment" "test_attach":
│  101: resource "aws_iam_role_policy_attachment" "test_attach" {
```

### Terraform Configuration Files

```
variable "profile" {}
variable "region" {}

provider "aws" {
  profile = var.profile
  region  = var.region
}

terraform {
  required_version = ">= 1.0"
  backend "s3" {
    key = "spikes/role-benchmark/terraform.tfstate"
  }
  required_providers {
    aws = {
      source ="hashicorp/aws"
      version = "= 5.25.0"
    }

  }
}


data "aws_iam_policy_document" "assume_role" {
  statement {
    effect = "Allow"

    principals {
      type        = "Service"
      identifiers = ["ec2.amazonaws.com"]
    }

    actions = ["sts:AssumeRole"]
  }
}

resource "aws_iam_role" "role" {
  name               = "test-role"
  assume_role_policy = data.aws_iam_policy_document.assume_role.json
}

data "aws_iam_policy_document" "policy" {
  statement {
    effect    = "Allow"
    actions   = ["ec2:Describe*"]
    resources = ["*"]
  }
}

resource "aws_iam_policy" "policy" {
  count = 8
  name        = "test-policy-${count.index}"
  description = "A test policy"
  policy      = data.aws_iam_policy_document.policy.json
}


resource "aws_iam_role_policy_attachment" "test_attach" {
  count = 8
  role       = aws_iam_role.role.name
  policy_arn = aws_iam_policy.policy[count.index].arn
}

```

### Steps to Reproduce

apply the provided terraform.  Or create new terraform, which assigns 8 polices to a role

### Would you like to implement a fix?

None

**Comment by flichtenheld** [comment] 2023-11-13 14:47
I updated last week from 5.20.0 to 5.24.0 and started to see these errors. So I think this was introduced earlier than 5.25.0

**Comment by dezren39** [comment] 2023-11-13 14:58
I switched
from (which pulled 5.25.0)
```
      version = "~>5.0"
```
to
```
      version = "5.24.0"
```
and apply now succeeds.

**Comment by flichtenheld** [comment] 2023-11-13 15:19
> This does not fail reliably for me. So it seems to depend on a race condition. Something to keep in mind when trying to bisect.

Sorry, to clarify: It does not fail reliably for me with our actual code. Tested the example given in the report and that fails always. Probably the high amount of attachments makes it easier to hit the race condition.

**Comment by rhowe** [comment] 2023-11-13 15:42
I have started seeing this with version 3.76.1. I suspect AWS IAM behaviour has changed.

**Comment by jarpat** [comment] 2023-11-13 15:47
Just wanted to report I am also seeing this with:

```
bash-4.2# terraform version
Terraform v1.4.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.4.0
```

as of today.

**Comment by flichtenheld** [comment] 2023-11-13 16:00
> I have started seeing this with version 3.76.1. I suspect AWS IAM behaviour has changed.

Yes, I tried bisecting this. But found no version with which it actually works. So it looks indeed like AWS-side change.

**Comment by flichtenheld** [comment] 2023-11-13 16:02
`terraform apply -parallelism=1` works around the problem.

**Comment by mgusiew-guide** [comment] 2023-11-13 18:03
I haven't changed Terraform or Terraform AWS version recently and I started to see this today. I also observe the problem on older branches. So this is regression on AWS side. I agree that retries on conflict may be needed to solve this problem.

**Comment by venkatamutyala** [comment] 2023-11-13 19:28
We had a regression run on our end early Friday without issues. Saturday/Sunday have been failures. We run our regressions against us-west-2 but given IAM is a global service region may not matter in this case.

**Comment by flichtenheld** [comment] 2023-11-13 22:02
Tried to implement some testing for my patch. But now I can't reproduce the issue anymore. Maybe AWS fixed their stuff?

**Comment by venkatamutyala** [comment] 2023-11-14 01:32
@flichtenheld thanks for making the PR. I just tried recreating the issue twice this evening (Pacific Time) and was unsuccessful. My team's infra-regression suites are working fine this afternoon, which is great. Hopefully, your PR can get merged in soon so that we can avoid this issue in the future.

**Comment by r0bnet** [comment] 2023-11-14 06:25
We have the same issue but with `aws_iam_user_policy_attachment` and it started last week on Friday (10.11.2023). It's flaky and doesn't seem to appear all the times. Updating to v2 of the Go SDK might solve it since it has automatic retries for various HTTP status codes. I assume that the HTTP status code is 400 when this error is encountered since something similar was already an issue few years ago when it comes to the `aws_organizations_policy_attachment` resource: https://github.com/hashicorp/terraform-provider-aws/issues/5073

So my idea: either switch to v2 for IAM and hope that its solved or implement a retry mechanism for `create` and maybe `update` and `delete`.

**Comment by mgusiew-guide** [comment] 2023-11-14 11:25
FTR the error went away yesterday afternoon so I contacted AWS to get some explanation. I was told that recently AWS made changes in IAM API, in particular AttachRolePolicy, AttachUserPolicy, and AttachGroupPolicy started to throw ConcurrentModificationException in case of concurrent requests. After the change AWS noticed elevated ConcurrentModification errors when calling IAM APIs. Because of that the issue has been resolved and the service is operating normally. Will try to clarify if "resolved" means that the feature was rolled back or something else.

**Closed** 2023-11-14 22:42 UTC
Labels: bug, service/iam

**Comment by mgusiew-guide** [comment] 2023-11-15 06:31
Got some updates from AWS side:
- The ConcurrentModificationException related change was rolled back
- Currently, it is not planned to roll out the changes in the future since it is impacting the customer's environment. There will be an announcement or notification regarding this if it is further planned to be implemented in the future

Hope that helps
