### ISSUE TITLE
Output type from data aws_pricing_product has been changed with provider version 4.22

### ISSUE THREAD

**Issue by bpazdziur** [hashicorp/terraform-provider-aws#25771] opened 2022-07-11 14:49 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform version: 1.1.7
hashicorp/aws provider version: 4.22

### Affected Resource(s)

* aws_pricing_product

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
data "aws_pricing_product" "database" {
  service_code = "AmazonRDS"
  filters {
    field = "instanceType"
    value = "db.t3.micro"
  }
  filters {
    field = "databaseEngine"
    value = "PostgreSQL"
  }
  filters {
    field = "deploymentOption"
    value = "Single-AZ"
  }
  filters {
    field = "location"
    value = "US East (N. Virginia)"
  }
}

locals {
  raw_data = jsondecode(data.aws_pricing_product.database.result)
  total_ram_gb    = split(" ", local.raw_data.product.attributes.memory)
}

output "raw_data" {
  value       = local.raw_data
}

```
### Expected Behavior
Output for raw_data
```
  raw_data = {
      product         = {
          attributes    = {
              currentGeneration       = "Yes"
              databaseEngine          = "PostgreSQL"
              deploymentOption        = "Single-AZ"
              engineCode              = "14"
              instanceFamily          = "General purpose"
              instanceType            = "db.t3.micro"
              instanceTypeFamily      = "T3"
              licenseModel            = "No license required"
              location                = "US East (N. Virginia)"
              locationType            = "AWS Region"
              memory                  = "1 GiB"
...
			  }
		}
	}
```
`total_ram_gb` is equal 1 
### Actual Behavior

Error during terraform plan:
```
Error: Unsupported attribute

  on ..\..\..\..\modules\rds-module\alerting-module-cloudwatch\01_locals.tf line 13, in locals:
  13:   total_ram_gb    = local.raw_data.product.attributes.memory
    |----------------
    | local.raw_data is "{\"product\":{\"productFamily\":\"Database Instance\",\"attributes\":{\"engineCode\":\"14\",\"instanceTypeFamily\":\"T3\",\"memory\":\"1 GiB\",
...
```
### Steps to Reproduce

1. `terraform plan`

### Important Factoids
It seems like the output from the data 'aws_pricing_product' has been changed and need to be double jsondecode to achieve the terraform object.
Changing 
```hcl
raw_data = jsondecode(data.aws_pricing_product.database.result)
```
into
```hcl
raw_data = jsondecode(jsondecode(data.aws_pricing_product.database.result))
```
solves the problem and gives the same output, but I think this is not a proper behavior

**Comment by bendrucker** [comment] 2022-07-14 23:44
This is caused by an upstream issue with all AWS SDKs, described here:

https://github.com/aws/aws-sdk-go/issues/4480

While the API has always returned an array of JSON strings in `PriceList`, the model configuration previously instructed AWS SDKs to treat each array element as a JSON object.

While this issue is easily patched, I'll wait to see what AWS says about whether this change was intentional and/or might be reverted.

**Comment by bendrucker** [comment] 2022-07-20 18:53
`aws-sdk-go` has been patched and https://github.com/hashicorp/terraform-provider-aws/pull/25907 will fix this

**Comment by bendrucker** [comment] 2022-08-01 19:23
This is fixed in the latest release by https://github.com/hashicorp/terraform-provider-aws/pull/25955 and should be closed

**Closed** 2023-06-21 15:08 UTC
Labels: bug, upstream, service/pricing
