### ISSUE TITLE
Support for new feature S3 Multi-region access point

### ISSUE THREAD

**Issue by sumitag** [hashicorp/terraform-provider-aws#20998] opened 2021-09-22 23:05 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add support for new feature S3 Multi-region access point.

### New or Affected Resource(s)

s3control create-multi-region-access-point

### References

* https://docs.aws.amazon.com/AmazonS3/latest/userguide/CreatingMultiRegionAccessPoints.html

**Comment by justinretzolk** [comment] 2021-09-23 00:02
Hi @sumitag 👋 Thanks for taking the time to submit this issue. It looks like this is a duplicate of #20799. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #20799.

**Closed by justinretzolk** 2021-09-23 00:02 UTC
Labels: enhancement, needs-triage
