### ISSUE TITLE
[Bug]: aws_cognito_user_pool being created with non-standard birthdate schema

### ISSUE THREAD

**Issue by wmhartl** [hashicorp/terraform-provider-aws#38197] opened 2024-06-29 19:39 UTC
### Terraform Core Version

1.9.0

### AWS Provider Version

5.56.1

### Affected Resource(s)

aws_cognito_user_pool

### Expected Behavior

Up until some point recently, this worked fine, resulting in a user pool with the appropriate birthdate:
```
aws cognito-idp describe-user-pool --user-pool-id <redacted>
```
shows in SchemaAttributes:
```
            {
                "Name": "birthdate",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "10",
                    "MaxLength": "10"
                }
            },
```

### Actual Behavior

Now what's happening when a new user pool is created, birthdate `MinLength` appears to be set incorrectly at **4**, when it should be **10** per the spec:
```
            {
                "Name": "birthdate",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "4",
                    "MaxLength": "10"
                }
            },
```

### Relevant Error/Panic Output Snippet

```shell
~ resource "aws_cognito_user_pool" "pool" {
        id                         = "<redacted>"
        name                       = "<redacted>"
        tags                       = {}
        # (16 unchanged attributes hidden)

      - schema {
          - attribute_data_type      = "String" -> null
          - developer_only_attribute = false -> null
          - mutable                  = true -> null
          - name                     = "birthdate" -> null
          - required                 = false -> null

          - string_attribute_constraints {
              - max_length = "10" -> null
              - min_length = "4" -> null
            }
        }

        # (10 unchanged blocks hidden)
    }
╷
│ Error: updating Cognito User Pool (<redacted>): cannot modify or remove schema items
│ 
│   with module.<redacted>,
│   on <redacted> line 19, in resource "aws_cognito_user_pool" "pool":
│   19: resource "aws_cognito_user_pool" "pool" {
```

### Terraform Configuration Files

```
resource "aws_cognito_user_pool" "pool" {
  name = "<redacted>"
  auto_verified_attributes = [
    "email",
  ]

  mfa_configuration = "OPTIONAL"
  sms_authentication_message = "Your authentication code is {####}."

  account_recovery_setting {
    recovery_mechanism {
      name     = "verified_email"
      priority = 1
    }
    recovery_mechanism {
      name     = "verified_phone_number"
      priority = 2
    }
  }

  email_configuration {
    ...
  }

  lambda_config {
    custom_message = data.aws_lambda_function.custom_email_responses.arn
  }

  schema {
    attribute_data_type      = "String"
    developer_only_attribute = false
    mutable                  = true
    name                     = "email"
    required                 = true

    string_attribute_constraints {
      max_length = "2048"
      min_length = "0"
    }
  }

  sms_configuration {
    external_id    = data.aws_iam_role.cognito_sms.name
    sns_caller_arn = data.aws_iam_role.cognito_sms.arn
  }

  software_token_mfa_configuration {
    enabled = true
  }

  username_configuration {
    case_sensitive = false
  }

  password_policy {
    minimum_length                   = 16
    require_lowercase                = true
    require_numbers                  = true
    require_symbols                  = true
    require_uppercase                = true
    temporary_password_validity_days = 7
  }
}
```

### Steps to Reproduce

`terraform apply` with no changes required

Deleting and recreating the pool does not solve the issue

### References

[Cognito Developer Guide](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html#cognito-user-pools-standard-attributes) references the OpenID Connect Spec which calls for a 10 digit birthdate "YYYY-MM-DD" per ISO 8601-1.

### Would you like to implement a fix?

None

**Comment by wmhartl** [comment] 2024-06-29 21:01
This might be an AWS issue given I've replicated the issue via the console also. I've filed a support request with AWS and will follow-up here with the outcome.

**Comment by jamie1911** [comment] 2024-06-30 16:46
> This might be an AWS issue given I've replicated the issue via the console also. I've filed a support request with AWS and will follow-up here with the outcome.

This is still occurring, like you mentioned, creating it via AWS console yields the same results of the birthday schema getting set with `min_length` of 4.

Did AWS get back to you about this?

**Comment by wmhartl** [comment] 2024-06-30 17:22
> > This might be an AWS issue given I've replicated the issue via the console also. I've filed a support request with AWS and will follow-up here with the outcome.
> 
> This is still occurring, like you mentioned, creating it via AWS console yields the same results of the birthday schema getting set with `min_length` of 4.
> 
> Did AWS get back to you about this?

Not yet

**Comment by wmhartl** [comment] 2024-07-01 00:32
Support said there was already "an internal ticket to our service team requesting confirmation on this." No ETA at the moment.

**Comment by dbaggott** [comment] 2024-07-01 20:14
For the scenario in which you have *previously* created user pools and terraform tries to update the existing "birthdate" schema, you can stop this via `ignore_changes`:

```
lifecycle {
  // temporary workaround for https://github.com/hashicorp/terraform-provider-aws/issues/38197
  ignore_changes = [schema]
}
```

Given that the cognito schemas are immutable anyway, it's not even possible for terraform to apply any changes...

**Comment by hanoj-budime** [comment] 2024-07-02 08:07
Currently, Terraform is not aware of the recent changes from AWS regarding Cognito `SchemaAttributes`, particularly the `birthdate` attribute. This discrepancy will impact the Terraform `plan` and `apply` processes, as the schema attribute validation will not match.

For example, Terraform will try to match the schema here, but due to the recent changes in AWS Cognito `SchemaAttributes`, particularly the `birthdate` attribute, the validation will fail as the schema attributes will not align.

https://github.com/hashicorp/terraform-provider-aws/blob/a8bfcb31bceea157fcafc63c284ed7e3c62534ab/internal/service/cognitoidp/user_pool.go#L2038

https://github.com/hashicorp/terraform-provider-aws/blob/a8bfcb31bceea157fcafc63c284ed7e3c62534ab/internal/service/cognitoidp/user_pool.go#L2057-L2067

**Comment by wmhartl** [comment] 2024-07-03 17:46
Heard from AWS:
```
======
Thank you for contacting AWS Customer Support regarding the failure to update the Amazon Cognito User pool via Terraform. We have identified the root cause of the issue, which was due to a code deployment on Monday, July 1, 2024, at 19:00:08 UTC. This code deployment was to support customers who provide only the year (YYYY) as birthdate, but it inadvertently affected customers using Terraform to update user pools.

In the meantime, we recommend creating a new Cognito User pool [1] by explicitly passing the birthdate in the User pool schema and setting the minimum length to 10. This will enable you to create a new User Pool with the default minimum length set to 10.

We are also investigating a permanent resolution to this issue and implementing additional controls to prevent its recurrence. We apologize for the impact this has had on your organization and appreciate your patience as we work to resolve the issue for you.
```

**Comment by hanoj-budime** [comment] 2024-07-04 09:28
@wmhartl, 😅..

Basically, they fixed their own bug now and asking us to explicitly address birthdate attribute.. funny..


Terraform-team ? any plans on this ..

**Comment by hanoj-budime** [comment] 2024-07-04 12:18
Once this changes are GA release from AWS. we have to explicitly tell our new user pools
backward compatibility
``` tf
schema: [{name="birthdate",attribute_data_type="String",mutable=true,required=false,min=10,max=10}]
```

**Comment by hanoj-budime** [comment] 2024-07-11 10:52
Actually, there is no backward compatibility due to recent changes by the AWS Cognito team.

I ran multiple scenario cases, both on existing deployments and new deployments. It's very hard to control whether the same TF code is deployed or not. Checking if the new deployment addresses explicitly, and for the old deployment, we can't address explicitly for now because it will be consider as a custom:xxx attribute.

``` tf
schema: [{name="birthdate",attribute_data_type="String",mutable=true,required=false,min=10,max=10}]
```

**Comment by hanoj-budime** [comment] 2024-07-11 10:57
Terraform team, if possible, could you support `StringAttributeConstraints` for `birthdate` with a `MinLength` of 4 or 10 as a validation on your end? That would resolve most of the production impact issues right away.

This means we are expecting either 4 or 10, so it will not impact new resources or existing resources. What do you think?

https://github.com/hashicorp/terraform-provider-aws/blob/a8bfcb31bceea157fcafc63c284ed7e3c62534ab/internal/service/cognitoidp/user_pool.go#L2057-L2067

**Comment by Naton-1** [comment] 2024-07-22 14:39
@wmhartl Any response back from AWS support?

**Comment by wmhartl** [comment] 2024-07-22 14:54
> @wmhartl Any response back from AWS support?

They said they reverted the change. I haven't checked yet since I'm not using the field at the moment.

**Comment by Naton-1** [comment] 2024-07-22 20:14
I created a basic Cognito user pool in Terraform and can confirm that I'm not seeing this issue anymore. AWS fixed it on their end by reverting the `birthdate` schema minimum length change.

I deployed the following using AWS provider v5.55.0:
```
resource "aws_cognito_user_pool" "beans" {
  name = "Beans"
}
```

I then checked the user pool details by running this command, and noticed that the `birthdate` minimum length is now back to its original value of  `10`.
```
$ aws cognito-idp describe-user-pool --user-pool-id <id>
{
    "Name": "birthdate",
    "AttributeDataType": "String",
    "DeveloperOnlyAttribute": false,
    "Mutable": true,
    "Required": false,
    "StringAttributeConstraints": {
        "MinLength": "10",
        "MaxLength": "10"
    }
},
```

Running `terraform plan` no longer tries to (impossibly) change the Cognito user pool schema anymore.

I think we can close this issue.

**Comment by wmhartl** [comment] 2024-07-22 21:55
> Unfortunately, for my user pools that were created _after_ AWS made this change but _before_ they reverted it, Terraform still tries to (impossibly) change the `birthdate` schema. I don't know how to fix it besides destroying and replacing it.

Yeah, there's isn't a way as far as I know. Since I'm not using the field, I just ignored the change, in the same way above @dbaggott posted.

**Comment by hanoj-budime** [comment] 2024-07-23 02:45
> I created a basic Cognito user pool in Terraform and can confirm that I'm not seeing this issue anymore. AWS fixed it on their end by reverting the `birthdate` schema minimum length change.
> 
> I deployed the following using AWS provider v5.55.0:
> 
> ```
> resource "aws_cognito_user_pool" "beans" {
>   name = "Beans"
> }
> ```
> 
> I then checked the user pool details by running this command, and noticed that the `birthdate` minimum length is now back to its original value of `10`.
> 
> ```
> $ aws cognito-idp describe-user-pool --user-pool-id <id>
> {
>     "Name": "birthdate",
>     "AttributeDataType": "String",
>     "DeveloperOnlyAttribute": false,
>     "Mutable": true,
>     "Required": false,
>     "StringAttributeConstraints": {
>         "MinLength": "10",
>         "MaxLength": "10"
>     }
> },
> ```
> 
> Running `terraform plan` no longer tries to (impossibly) change the user pool `birthdate` schema anymore.
> 
> I think we can close this issue.

Yes, AWS confirmed that they have reverted min length 4 for birthday, because of global issue for terraform users.

**Comment by justinretzolk** [comment] 2024-07-26 18:29
Hey all 👋 Thank you for taking the time to raise this, and for the back and forth here. Given that the change has been reverted on the AWS end, it doesn't look like any additional changes are needed on the AWS Provider side. With that in mind, I'm going to close this issue.

**Closed by justinretzolk** 2024-07-26 18:29 UTC
Labels: bug, needs-triage, service/cognitoidp
