### ISSUE TITLE
Elasticache Redis Multi AZ not enabled

### ISSUE THREAD

**Issue by vioan** [hashicorp/terraform-provider-aws#13706] opened 2020-06-10 14:21 UTC
Hi,

I am trying to get an Elasticache (Redis) instance up and running (cluster mode disabled) and for that I was starting with the first two examples from documentation: 
https://www.terraform.io/docs/providers/aws/r/elasticache_replication_group.html

but it seems that even if everything is provisioned and working, the Multi AZ is still Disabled. I have the Failover enabled. Any idea what is wrong? 

I am 90% sure I tried these two examples a few weeks ago and Multi AZ was enabled, as far as I remember. After having the cluster up & running I can enable Multi AZ from AWS console, but I would like to have it in terraform, of course.

Thank you very much!

Here is the code I am using:
~~~
resource "aws_elasticache_replication_group" "example-1" {
  automatic_failover_enabled    = true
  availability_zones            = ["eu-central-1a", "eu-central-1b"]
  replication_group_id          = "tf-rep-group-1"
  replication_group_description = "test description"
  node_type                     = "cache.t3.micro"
  number_cache_clusters         = 2
  parameter_group_name          = "default.redis5.0"
  port                          = 6379
}

resource "aws_elasticache_replication_group" "example-2" {
  automatic_failover_enabled    = true
  availability_zones            = ["eu-central-1a", "eu-central-1b"]
  replication_group_id          = "tf-rep-group-2"
  replication_group_description = "test description"
  node_type                     = "cache.t3.micro"
  number_cache_clusters         = 2
  parameter_group_name          = "default.redis5.0"
  port                          = 6379

  lifecycle {
    ignore_changes = ["number_cache_clusters"]
  }
}

resource "aws_elasticache_cluster" "replica" {
  count = 1

  cluster_id           = "tf-rep-group-1-${count.index}"
  replication_group_id = "${aws_elasticache_replication_group.example-2.id}"
}
~~~

And here are two screenshots after terraform created the resources:

![ElastiCache Management Console 2020-06-10 16-18-43](https://user-images.githubusercontent.com/1939297/84279299-1d841300-ab36-11ea-8a3d-c5859b1584c3.png)

![ElastiCache Management Console 2020-06-10 16-09-37](https://user-images.githubusercontent.com/1939297/84278310-dd706080-ab34-11ea-9b99-c26077645ead.png)

**Comment by F8aAr** [comment] 2020-06-11 09:54
Hello,

**Comment by asaltbde** [comment] 2020-06-11 14:58
We have the same issue also.

**Comment by mattdrees** [comment] 2020-06-11 23:54
I ran into this yesterday.
After digging a little bit, it seems that AWS only recently added a 'MultiAZ' attribute to the cli; see https://github.com/boto/botocore/commit/5fd5baa152a057c161840b3ef60a34d5177b4563#diff-be2136ac185370e57999c1dbe65ba6b5. 
I'm guessing that the attribute was also only added to the aws api recently, as well. And I'm guessing that, prior to that, the api simply set Multi-AZ to whatever AutomaticFailoverEnabled was set to. And after that, it simply defaulted Multi-AZ to false. (Which is not backwards compatible, IMO, but maybe AWS doesn't see it that way.)

**Comment by mattdrees** [comment] 2020-06-12 00:09
So, one solution could be to add a new `multi_az` attribute to `aws_elasticache_replication_group`. This would reflect the (new?) reality that multi-az is independent from automatic-failover-enabled, from AWS' point of view.

Another solution might be to begin explicitly sending MultiAZ as true when `automatic_failover_enabled` is true. This would preserve the old behavior for terraform users. But I'm not sure how feasible that is.


For now, this workaround seems to work ok:
```hcl
resource "aws_elasticache_replication_group" "test" {
  automatic_failover_enabled    = true
  engine                        = "redis"
  engine_version                = "5.0.6"
  node_type                     = "cache.t3.micro"
  number_cache_clusters         = 2
  parameter_group_name          = "default.redis5.0"
  subnet_group_name  = aws_elasticache_subnet_group.subnet_group.name
  replication_group_description = "A automatic_failover_enabled=true replication group that should also be multi-az, but is not, without help."
  replication_group_id          = "should-be-multi-az"

  provisioner "local-exec" {
    environment = {
      REPLICATION_GROUP_ID = aws_elasticache_replication_group.test.replication_group_id
    }
    command = <<-EOT
      aws elasticache modify-replication-group \
        --replication-group-id $REPLICATION_GROUP_ID \
        --multi-az-enabled \
        --apply-immediately
    EOT
  }

}

```

**Comment by acerest** [comment] 2020-06-12 04:21
We have this issue too, and we opened a ticket in AWS, they said that the GO SDK was already updated
[CreateReplicationGroupInput](https://docs.aws.amazon.com/sdk-for-go/api/service/elasticache/#CreateReplicationGroupInput)
Hope you guys could fix it ASAP!
Thank you very much!

**Comment by mattdrees** [comment] 2020-06-12 14:23
@acerest did AWS say that the updated GO SDK will restore the old behavior, or that it simply has a MultiAZ field that you can use?

**Comment by acerest** [comment] 2020-06-15 03:30
> @acerest did AWS say that the updated GO SDK will restore the old behavior, or that it simply has a MultiAZ field that you can use?

@mattdrees Sorry for replying late, it's just a parameter
`
const (
    // MultiAZStatusEnabled is a MultiAZStatus enum value
    MultiAZStatusEnabled = "enabled"

    // MultiAZStatusDisabled is a MultiAZStatus enum value
    MultiAZStatusDisabled = "disabled"
)
`

**Comment by gibsonje** [comment] 2020-06-23 17:59
I'm having this issue now and my old cloud formation is having the same problem if applied today.

It seems that in CFN they split out  the field to "MultiAZEnabled" explicitly. Without digging deeper, I think terraform is not passing that along (or allowing you to set it).

**Comment by goodspellar** [comment] 2020-06-23 18:11
I added a draft PR for this change, but it's dependent on aws-sdk-go 1.32.7 being merged first

**Comment by nordcave** [comment] 2020-06-26 10:14
> 
> 
> I added a draft PR for this change, but it's dependent on aws-sdk-go 1.32.7 being merged first

I see that this one has been merged already. Is there are some more problems?
![image](https://user-images.githubusercontent.com/33480297/85846745-d16fda00-b795-11ea-94c8-a8afdd7cb6b7.png)

**Comment by ImperialXT** [comment] 2020-06-29 00:59
Wouldn't there need to be a PR to the Terraform repo itself updating it to use that version? Just because it's been released by AWS doesn't mean Terraform automatically uses it. So it's dependant on https://github.com/terraform-providers/terraform-provider-aws/pull/13803 from what I can tell.

**Comment by Type1J** [comment] 2020-07-06 22:27
#13803 is merged, now.

**Comment by Type1J** [comment] 2020-07-07 01:06
Is `multi_az` going to be added, or is it going to be implied by `automatic_failover_enabled`? The docs seem to say that `automatic_failover_enabled` does imply MultiAZ: https://www.terraform.io/docs/providers/aws/r/elasticache_replication_group.html#automatic_failover_enabled

> automatic_failover_enabled - (Optional) Specifies whether a read-only replica will be automatically promoted to read/write primary if the existing primary fails. If true, Multi-AZ is enabled for this replication group. If false, Multi-AZ is disabled for this replication group. Must be enabled for Redis (cluster mode enabled) replication groups. Defaults to false.

**Comment by ppapishe** [comment] 2020-07-07 16:35
So, will there be a new PR to update the tf resource to take multi-az as an attribute?

**Comment by ahmedfourti** [comment] 2020-07-07 16:44
+1 for multi-az attribute !

**Comment by Zakaria-Maj** [comment] 2020-07-08 14:47
+1 for multi-az attribute !

**Comment by mattdrees** [comment] 2020-07-08 15:01
If you'd like to see this fixed, you might consider adding your "thumbs up" to @goodspellar 's PR: https://github.com/terraform-providers/terraform-provider-aws/pull/13909

**Comment by cdtweb** [comment] 2020-07-08 16:16
Running into this same problem today.

**Comment by mattdrees** [comment] 2020-07-27 15:47
@breathingdust could I respectfully ask for your reasoning on labelling this an enhancement? From a user-experience POV, this is a bug. The resource doesn't do what the docs say it will do.

**Comment by sc250024** [comment] 2020-07-28 14:10
Everything @mattdrees said. This issue has been open for long enough now.

**Comment by breathingdust** [comment] 2020-07-28 23:27
My bad @mattdrees! I've corrected the labeling.

**Comment by tdmalone** [comment] 2020-08-24 15:12
Lots of changes to auto failover/Multi-AZ parts of the AWS docs in [this commit](https://github.com/awsdocs/amazon-elasticache-docs/commit/fae531d55d0600acfe3e434f0bb22b06cde30d46) from June, but I can't quite figure out why Multi-AZ / auto-failover is now two separate options, or how it's meant to behave... I'm fairly sure before that there was only one option, called Multi-AZ in the console but auto-failover in the API.

**Comment by mattdrees** [comment] 2020-08-24 15:27
Right, there was only one api attribute before, and they [added](https://awsapichanges.info/archive/changes/db86f9-elasticache.html#CreateReplicationGroup) a second (`MultiAZEnabled`) api attribute. 

I can't find docs on the intended behavior change. 
Maybe you can now have auto-failover within a single AZ? Maybe to save to save on network costs? :shrug:

**Comment by aruandre** [comment] 2020-09-09 08:56
Same problem when deploying with CloudFormation

**Comment by suvorovk-els** [comment] 2020-10-06 15:02
Here's a workaround for time being:

```
resource "null_resource" "nr" {
  triggers = {
    cache = aws_elasticache_replication_group.cache.id
  }
  provisioner "local-exec" {
    command = "aws elasticache modify-replication-group --replication-group-id ${aws_elasticache_replication_group.cache.id} --multi-az-enabled --apply-immediately"
  }
}
```

This will update MultiAZ setting with aws cli after aws_elasticache_replication_group is created.

Keep in mind that your aws_elasticache_replication_group must have multiple availability zones (set via `availability_zones`).
Also note that aws cli version must be recent enough to support `--multi-az-enabled` flag.

**Closed** 2021-01-28 18:19 UTC
Labels: bug, service/elasticache
