### ISSUE TITLE
Provider produced inconsistent final plan `aws_s3_bucket_object`

### ISSUE THREAD

**Issue by Jorge-Rodriguez** [hashicorp/terraform-provider-aws#17434] opened 2021-02-03 15:49 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.2
+ provider registry.terraform.io/hashicorp/aws v3.26.0

### Affected Resource(s)

* aws_s3_bucket_object

### Terraform Configuration Files

```hcl
module "store_one" {
  source  = "terraform-aws-modules/lambda/aws"
  version = "~> 1.30"

  function_name = "planmill-store-one"
  source_path   = "${path.module}/lambdas/store_one"
  handler       = "store_one.handler"
  runtime       = "python3.8"
  memory_size   = 256
  timeout       = 900
  publish       = true

  vpc_subnet_ids         = data.terraform_remote_state.core.outputs.vpc.private_subnets
  vpc_security_group_ids = [data.terraform_remote_state.core.outputs.vpc.default_security_group_id]

  tags = local.tags

  cloudwatch_logs_retention_in_days = 3
}
```

### Expected Behavior

Terraform apply succeeds

### Actual Behavior

Error: Provider produced inconsistent final plan

When expanding the plan for
module.store_one.aws_s3_bucket_object.lambda_package[0] to include new values
learned so far during apply, provider "registry.terraform.io/hashicorp/aws"
produced an invalid new value for .version_id: was known, but now unknown.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by Jorge-Rodriguez** [comment] 2021-03-02 15:31
This seems to be a regression of #14900

**Comment by bflad** [comment] 2021-03-03 18:37
Hi @Jorge-Rodriguez 👋  Sorry this was previously missed in our normal triage process. This is certainly a bug in the resource or Terraform CLI. Since I happened to see you also discussing this on https://github.com/hashicorp/terraform-provider-aws/issues/17860 and the cause/fix are likely the same, I'm going to close this issue here to consolidate efforts and discussions there. Thank you again for submitting this and hopefully we can get to the bottom of things.

**Closed by bflad** 2021-03-03 18:37 UTC
Labels: needs-triage, service/s3
