### ISSUE TITLE
S3 bucket creation | Existing Buckets

### ISSUE THREAD

**Issue by rishabhjain1510** [hashicorp/terraform-provider-aws#26006] opened 2022-07-27 16:49 UTC
while creating a S3 bucket using terraform, if that bucket already exists we are facing an weird issue

Current Scenario: 
S3 bucket :- "test-rishabh-111"  
This bucket was created via terraform different product about 1 year ago 
![image](https://user-images.githubusercontent.com/89471097/181275041-eb84eccb-66e2-4830-a4d2-d40e3678abac.png)

When created the same bucket via Terraform using below code 

resource "aws_s3_bucket" "test_bucket" {
  bucket = "test-rishabh-111"
}
-----Terraform Apply-------------
$ terraform13 apply --auto-approve
aws_s3_bucket.test_bucket: Creating...
aws_s3_bucket.test_bucket: Still creating... [10s elapsed]
aws_s3_bucket.test_bucket: Still creating... [20s elapsed]
aws_s3_bucket.test_bucket: Creation complete after 22s [id=test-rishabh-111]
----------------------------------------------------------------------------------------

Terraform says it has been successfully created .  and adds this resources in the state also. 

Expected Behavior 

This should have given the error that bucket already exist , at least should not have include the resource under the state. 

Now the same resource is managed by the two different states. 

If i delete any tf resource it will delete the s3 bucket also. 

Terraform Version Details:
AWS Provider :- 3.75.1
Terraform Version : 0.13.6

**Comment by gdavison** [comment] 2022-07-27 17:34
This is a duplicate of ##13587

**Closed by gdavison** 2022-07-27 17:34 UTC
Labels: bug, service/s3
