### ISSUE TITLE
Order is lost for data `aws_iam_policy_document` when applied to S3 buckets, iam roles, kms keys, etc

### ISSUE THREAD

**Issue by nitrocode** [hashicorp/terraform-provider-aws#11801] opened 2020-01-29 20:10 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

See also #21968 

### Terraform Version

```
✗ terraform --version
Terraform v0.12.20
+ provider.aws v2.46.0
```

### Affected Resource(s)

* `aws_ecr_repository_policy`
* `aws_kms_key`
* `aws_s3_bucket`
* `aws_launch_configuration`
* `aws_lb_listener`
* `aws_codeartifact_domain_pernission_policy`

### Terraform Configuration Files

If running locally, please add your own real roles to `local.secrets_roles` otherwise the kms policy will fail.

```hcl
provider "aws" {
  region = "us-east-1"
}

data "aws_caller_identity" "current" {}

locals {
  id = data.aws_caller_identity.current.account_id
  secrets_roles = [
    "asnip",
    "esnip",
    "lsnip",
    "psnip",
    "wsnip",
    "csnip",
#    "default",
  ]

  secrets_roles_arns = sort([
    for role in local.secrets_roles :
    "arn:aws:iam::${local.id}:role/${role}"
  ])

  secrets_admin = [
    "arn:aws:iam::${local.id}:role/sre"
  ]
}

data "aws_iam_policy_document" "secrets" {
  policy_id = "secrets-policy"

  statement {
    sid       = "Enable IAM User Permissions"
    effect    = "Allow"
    resources = ["*"]
    actions = [
      "kms:Create*",
      "kms:Describe*",
      "kms:Enable*",
      "kms:List*",
      "kms:Put*",
      "kms:Update*",
      "kms:Revoke*",
      "kms:Disable*",
      "kms:Get*",
      "kms:Delete*",
      "kms:ScheduleKeyDeletion",
      "kms:CancelKeyDeletion",
    ]

    principals {
      type        = "AWS"
      identifiers = local.secrets_admin
    }
  }

  statement {
    sid       = "Allow use of the key"
    effect    = "Allow"
    resources = ["*"]

    actions = [
      "kms:Encrypt",
      "kms:Decrypt",
      "kms:ReEncrypt*",
      "kms:GenerateDataKey*",
      "kms:DescribeKey",
      "kms:CreateGrant",
      "kms:ListGrants",
      "kms:RevokeGrant"
    ]

    principals {
      type = "AWS"

      identifiers = local.secrets_roles_arns
    }
  }
}

resource "aws_kms_key" "secrets_test" {
  description         = "test Default key for secrets encryption."
  key_usage           = "ENCRYPT_DECRYPT"
  is_enabled          = true
  enable_key_rotation = false

  policy = data.aws_iam_policy_document.secrets.json
}

resource "aws_kms_alias" "secrets_test" {
  name          = "alias/secrets-test"
  target_key_id = aws_kms_key.secrets_test.key_id
}

output "role_arns" {
  value = local.secrets_roles_arns
}

output "policy_json" {
  value = data.aws_iam_policy_document.secrets.json
}

output "key_policy_json" {
  value = aws_kms_key.secrets_test.policy
}
```

In terraform console

`local.secrets_roles_arns` is alphabetical
```
[
  "arn:aws:iam::1234567890:role/asnip",
  "arn:aws:iam::1234567890:role/csnip",
  "arn:aws:iam::1234567890:role/esnip",
  "arn:aws:iam::1234567890:role/lsnip",
  "arn:aws:iam::1234567890:role/psnip",
  "arn:aws:iam::1234567890:role/wsnip",
]
```

`data.aws_iam_policy_document.secrets.json` is reverse alphabetical which is expected (https://github.com/terraform-providers/terraform-provider-aws/issues/6107) 
```
...
      "Principal": {
        "AWS": [
          "arn:aws:iam::1234567890:role/wsnip",
          "arn:aws:iam::1234567890:role/psnip",
          "arn:aws:iam::1234567890:role/lsnip",
          "arn:aws:iam::1234567890:role/esnip",
          "arn:aws:iam::1234567890:role/csnip",
          "arn:aws:iam::1234567890:role/asnip"
        ]
      }
...
```

`aws_kms_key.secrets_test.policy` returns the same output which is perfect
```
      "Principal": {
        "AWS": [
          "arn:aws:iam::1234567890:role/wsnip",
          "arn:aws:iam::1234567890:role/psnip",
          "arn:aws:iam::1234567890:role/lsnip",
          "arn:aws:iam::1234567890:role/esnip",
          "arn:aws:iam::1234567890:role/csnip",
          "arn:aws:iam::1234567890:role/asnip"
        ]
      }
```

After applying the above, I added a `default` role to `local.secrets_roles` and I see this in the plan

```
...
                      ~ Principal = {
                          ~ AWS = [
                              - "arn:aws:iam::1234567890:role/asnip",
                              - "arn:aws:iam::1234567890:role/psnip",
                                "arn:aws:iam::1234567890:role/wsnip",
                              - "arn:aws:iam::1234567890:role/csnip",
                              - "arn:aws:iam::1234567890:role/esnip",
                              + "arn:aws:iam::1234567890:role/psnip",
                                "arn:aws:iam::1234567890:role/lsnip",
                              + "arn:aws:iam::1234567890:role/esnip",
                              + "arn:aws:iam::1234567890:role/default",
                              + "arn:aws:iam::1234567890:role/csnip",
                              + "arn:aws:iam::1234567890:role/asnip",
                            ]
                        }
...
```

### Expected Behavior

Order should be retained. I wouldn't mind the reverse alphabetical order at the very least.

### Actual Behavior

Random order

### Steps to Reproduce

1. Create a few roles (or reuse them)
2. Set the `local.secrets_roles` with actual roles
3. `terraform apply`
4. Change `local.secrets_roles` by adding another existing role
5. `terraform plan` and you will see random order

### Important Factoids

I edited a policy in AWS console, changed the order of principal aws to alphabetical, saved it, and also saw a random order. Perhaps it is the AWS API that is reordering them?

### References

* #6107 
* #402
* #438

### Workaround

* [Find Terraform Changes in JSON](https://gist.github.com/nitrocode/4820ba57f3bf5ef4d4254738496fc79c)

After upgrading to Terraform 0.14.x, my most recent workaround is by supplying an output

```
output "key_policy_json" {
  value = data.aws_iam_policy_document.secrets.json
}
```

Then in the `terraform plan` or `terraform apply`, it will hide all the unchanged and only show the few that changed. 

```
              ~ {
                  ~ Principal = {
                      ~ AWS = [
                            # (250 unchanged elements hidden)
                            "arn:aws:iam::1234567890:role/csnip",
                          + "arn:aws:iam::1234567890:role/default",
                            "arn:aws:iam::1234567890:role/esnip",
                            # (125 unchanged elements hidden)
                        ]
                    }
                    # (4 unchanged elements hidden)
                },
```

**Comment by joshmyers** [comment] 2021-03-18 16:24
After looking into this issue and looking into the jen20 library for awspolicyequivalency and https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_kms_key.go#L205 nothing in Terraform was causing the policy re ordering and the Terraform outputs looked as I'd expect.

As it turns out, KMS just saves in a random order. This can be replicated with a plain old `aws_kms_key` (read: not related to the loops/maps/for_each as above) passing in a policy, and later appending a new principal.

Can also replicate this in the AWS console:
* Create a key with a policy
* Edit the policy
* Save the policy
* The ordering has randomly/non deterministically changed.

**Comment by chroju** [comment] 2021-05-21 08:17
I'm experiencing a similar problem with Terraform 0.15.4 .

Terraform 0.15.4 will now report the changes made outside of Terraform as part of the plan result. Some list orders is not retained, so Terraform always reports list orders have been changed like below.

This problem has no real impact, but the plan results are unnecessarily long, and visibility is degraded.

```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_iam_role.example has been changed
  ~ resource "aws_iam_role" "example" {
      ~ assume_role_policy    = jsonencode(
          ~ {
              ~ Statement = [
                  ~ {
                      ~ Principal = {
                          ~ AWS = [
                              - "arn:aws:iam::XXXXXXXXXXXX:user/aaaaa",
                              + "arn:aws:iam::XXXXXXXXXXXX:user/ccccc",
                                "arn:aws:iam::XXXXXXXXXXXX:user/bbbbb",
                              + "arn:aws:iam::XXXXXXXXXXXX:user/aaaaa",
                                "arn:aws:iam::XXXXXXXXXXXX:user/ddddd",
                              - "arn:aws:iam::XXXXXXXXXXXX:user/ccccc",
                            ]
                        }
                        # (3 unchanged elements hidden)
                    },
                ]
                # (1 unchanged element hidden)
            }
        )
        id                    = "example"
        name                  = "example"
        tags                  = {}
        # (8 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

**Comment by nitrocode** [comment] 2021-05-23 18:10
Even though the api returns it in a random order, couldn't the apply save the tfstate in alphabetical order and then have the plan retrieve it from the api and alphabetize it again to diff it thereby avoiding the reorder shown in the diff?

**Comment by zpallin** [comment] 2021-05-25 18:29
> I'm experiencing a similar problem with Terraform 0.15.4 .

Same.

Using Terraform 0.15.4 and applying for a directory with 30+ ecr repository resources with policies. Those policies are having their Principals section randomly sorted by AWS IAM, but I cannot `lifecycle ignore_changes` nor will `terraform refresh` get rid of the changes.

**Comment by faucherb94** [comment] 2021-05-25 22:46
+1 for this, seeing it in both KMS resource-based-policies and IAM resources.

**Comment by stephank** [comment] 2021-05-28 08:09
May not even be limited to `assume_role_policy`. I'm also seeing this on the `policy` attribute of an `aws_s3_bucket`. (I'm also using the `jsonencode` approach.)

**Comment by junaid-ali** [comment] 2021-05-31 11:52
Same issue here with `0.15.4` for `aws_launch_configuration` and `nlb.aws_lb_listener`

**Comment by cavallos** [comment] 2021-05-31 14:18
Same issue with 0.15.4 and aws_kms_key policy

**Comment by tzahari** [comment] 2021-06-02 06:32
Same issue here with ```0.14.11```and ```aws_codeartifact_domain_permissions_policy```

**Comment by pavelpichrt** [comment] 2021-06-07 10:06
Same issue here, this makes the idea of checking the plan nearly impossible without some programmatic filtering on the client side, as this bug generates thousands of lines of redundant plan code (in our case) and everything else gets lost in the noise.

**Comment by acook-id11** [comment] 2021-06-07 21:29
Same problem here with an S3 Bucket Policy. Terraform 15.5

**Comment by mjreed-turner** [comment] 2021-06-09 14:10
Just another "me, too". This is tehncially AWS's fault if it's reordering lists inside JSON; that's supposed to be a no-no. But since these particular lists are semantically treated as sets, probably Terraform should special-case the comparison so that it doesn't care about order.

**Comment by RLuckom** [comment] 2021-06-11 15:04
This issue affects `1.0` as well.

**Comment by coltaan** [comment] 2021-07-03 05:15
It still affects 1.0.1 as well.
For me all resources (usually policies) which has any ARN list like the example below are affected:
```
...
        Principal = {
            AWS = [
                "arn:aws:iam::123456789012:user/user-0",
                "arn:aws:iam::123456789012:user/user-1",                            ]
          }
...

```

**Comment by ChristophShyper** [comment] 2021-07-07 10:38
Confirming it works like that for ANY policy. Suggestion about sorting principals before storing and comparing should do the trick here.

@nitrocode can you change the title so it's not misleading?

**Comment by Raunok87** [comment] 2021-07-16 19:33
can confirm this same issue exists in 1.0.2 as well.  Ordering is not respected and subsequent runs will throw warnings for differing "changes" each time, even though no actual changes have been made.

**Comment by jonathanio** [comment] 2021-07-16 19:42
I don't think this is an issue with the version of Terraform, but the version of the AWS provider itself, as this is wholly within the `aws_iam_policy_document`. Until this is fixed here, upgrading Terraform will not help?

**Comment by eddycharly** [comment] 2021-07-27 11:16
Strangely enough terraform 0.14.11 shows no diff but 0.15.5 shows a diff, so it might be related to the terraform version somewhat.

**Comment by jw-maynard** [comment] 2021-07-27 16:53
We skipped 0.15 and went to 1.0 but I can confirm that on 0.14 I did not see this issue and after upgrading to 1.0 I now see this in a number of places. Sorting the lists in the terraform code does not help.

**Comment by eddycharly** [comment] 2021-07-27 18:04
IMO the way terraform core compares sets has changed. Even though it shows a diff, in the end it says the resource is up to date, weird.

**Comment by kcd83** [comment] 2021-07-28 23:19
As @chroju points out the issue is just _state change detection_ and not the _execution plan_

> Unless you have made equivalent changes ... the following plan may include actions to undo or respond to these changes.

So you often see

> Plan: 0 to add, 0 to change, 0 to destroy.

It feels like the distinction between an ordered list and an unordered set could be first-class consideration in both to handle all these cases where dubious APIs by AWS and others return things in random order

It might help if a core Hashicorp person could explain the rationale this is only in the plan phase as it seems intentional. 

Mitigations could include
- a configuration option to hide noop changes in state change detection
- a mechanism for providers to declare if an array is an ordered list or unordered set to opt into this behaviour

**Comment by dsunil79** [comment] 2021-08-19 18:41
we noticed similar issue as well

**Comment by sergchernata** [comment] 2021-09-10 17:17
Seeing this on version `1.0.5` with `aws_iam_role` in Principal > Service.

**Comment by yongzhang** [comment] 2021-09-17 06:34
same issue on `aws_ecr_repository_policy`

**Comment by vftona** [comment] 2021-09-23 23:22
This issue is still present on `1.0.7`

**Comment by sergei-ivanov** [comment] 2021-09-28 15:51
I think all that's needed is a smarter diff function for `policy` attributes in various AWS resources. So that first of all both local and remote policy documents are normalised by sorting principals and actions, and by wrapping singular items in lists, and only then the two normalised policies should be structurally compared. That would have eliminated almost all false drifts that we are seeing on a daily basis. I am currently upgrading to Terraform 1.0 and this non-deterministic ordering results in drifts being reported all the time, even after an explicit `terraform refresh`. This is going to be an even bigger source of noise from now on.

**Comment by drmjo** [comment] 2021-10-04 03:14
this is causing extra "false" diffs.

as a user i have to sift through this and figure out if the change is an "actual" change or just an ordering in a list issue .. this defeats the purpose of an automated drift detection system.

the returned list is not in the same order either .. each API call returns the principals in a "new" order. so no matter what i do an how i order these things there is always going to be a diff .. 

Its a list so I would assume it should be ordered by definition, even though the order does not make a difference in permissions.

This is an AWS API issue I would say as appose to this provider.

even the AWS UI does this .. If you refresh the KMS key view page a couple of times you will notice the principals in the policy returned in random orders.

**Comment by internetcoffeephone** [comment] 2021-10-14 11:41
This issue is still present on `1.0.9`

**Comment by rwstauner** [comment] 2021-11-05 19:32
Just to clarify: the aws api is returning these policy values in an inconsistent order, so this behavior would be present for any client... I can make the same api request twice and i'll get two different orders.

**Comment by mzupan** [comment] 2021-11-07 01:18
@rwstauner right and probably the best solution is to do what @ewbankkit is saying with a function to sort what the API is returning so we have consistent results.

**Comment by breathingdust** [comment] 2021-11-10 17:27
Hi all 👋  Just letting you know that this is issue is featured on this quarters roadmap. We will be a looking for a pattern to implement that can help resolve both this and related issues. 

If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!

**Comment by eytanhanig** [comment] 2021-11-10 23:54
How AWS stores resources/objects in their backend is quite different than what they present to users, and for many years I've suspected that when appropriate they either **store some data in unordered sets** or have code that somewhere along the line **treats some data as unordered lists**. Unfortunately **JSON does not support unordered sets**, resulting in what should be an **unordered** list instead being returned to us as a **reordered** list. This phenomenon is not unique to AWS, and can sometimes be seen when diffing JSON-formatted Terraform statefiles.

Instructing Terraform to ignore reordering is one solution, however IMO it's potentially worth natively supporting the concept unordered sets. As for identifying them, perhaps we can utilize the results of existing unit tests?

**Comment by elkh510** [comment] 2021-11-16 05:48
hi
any updates here?

**Comment by stawii** [comment] 2021-11-16 10:03
Wouldn't automagically sorting lists in AWS API response **AND** expected principals before comparing solve this? This *should* be easy ;)

**Comment by YakDriver** [comment] 2021-11-30 22:27
### Ordering is easy but...

"Order" in the context of this issue has two caveats:
1. We're talking about the order of a JSON array within JSON data. With `aws_iam_policy_document`, we have some say in the order because we're generating the JSON. But, with the plain `policy` argument set to `jsonencode()` or a heredoc (🙀), we don't do anything with the order. That's not to say we couldn't but so far we haven't crossed that bridge. Hopefully, we won't have to.
2. AWS is the data store for the JSON data and _does not_ preserve order. We can preserve order in state but as far as how things show up in the AWS console, we have no control. Even after an import, currently we would simply use the order as provided by AWS.

### What are we solving?

I see there being two problems:
1. avoiding perpetual diffs
2. providing a minimal diff in the case of an actual out-of-band drift detection

Our approach will be to fix **#** 1 and then see where we're at with **#** 2. Currently the two problems are intertwined in the issues to the point they are convulting each other. Once pain points are alleviated (hopefully) with #21968, we'll need your input to determine what problems still remain.

**Comment by anthonyAdhese** [comment] 2021-12-16 13:55
Could it be that v3.69 doesn't fix all of the issues for this issue? I still have issues with aws_s3_bucket_policy showing a diff due to ordering.

**Comment by ewbankkit** [comment] 2021-12-16 13:57
@anthonyAdhese Could you paste in an example of the diff that is shown? Thanks.

**Comment by anthonyAdhese** [comment] 2021-12-16 14:06
> @anthonyAdhese Could you paste in an example of the diff that is shown? Thanks.

```
# aws_s3_bucket_policy.customer_cloud_resources["xxx"] will be updated in-place
  ~ resource "aws_s3_bucket_policy" "customer_cloud_resources" {
        id     = "doggybites-cloud-resources-xxx"
      ~ policy = jsonencode(
            {
              - Statement = [
                  - {
                      - Action    = "s3:GetObject"
                      - Effect    = "Allow"
                      - Principal = {
                          - AWS = "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity XXX"
                        }
                      - Resource  = "arn:aws:s3:::doggybites-cloud-resources-xxx/public_html/*"
                      - Sid       = ""
                    },
                  - {
                      - Action    = "s3:ListBucket"
                      - Condition = {
                          - StringLike = {
                              - s3:prefix = "public_html/*"
                            }
                        }
                      - Effect    = "Allow"
                      - Principal = {
                          - AWS = "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity XXX"
                        }
                      - Resource  = "arn:aws:s3:::doggybites-cloud-resources-xxx"
                      - Sid       = ""
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> (known after apply)
        # (1 unchanged attribute hidden)
    }
```
Never had an issue with it in the past but we've upgraded from v3.23 a few weeks ago and this is the first run since then I believe.

Debug output was this:
Expected:
```
{
    "Version": "2012-10-17",
    "Statement": [{
        "Sid": "",
        "Effect": "Allow",
        "Principal": {
            "AWS": "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity XXX"
        },
        "Action": "s3:GetObject",
        "Resource": "arn:aws:s3:::doggybites-cloud-resources-xxx/public_html/*"
    }, {
        "Sid": "",
        "Effect": "Allow",
        "Principal": {
            "AWS": "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity XXX"
        },
        "Action": "s3:ListBucket",
        "Resource": "arn:aws:s3:::doggybites-cloud-resources-xxx",
        "Condition": {
            "StringLike": {
                "s3:prefix": "public_html/*"
            }
        }
    }]
}
```
Received:
```
{
    "Statement": [{
        "Action": "s3:GetObject",
        "Effect": "Allow",
        "Principal": {
            "AWS": "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity XXX"
        },
        "Resource": "arn:aws:s3:::doggybites-cloud-resources-xxx/public_html/*",
        "Sid": ""
    }, {
        "Action": "s3:ListBucket",
        "Condition": {
            "StringLike": {
                "s3:prefix": "public_html/*"
            }
        },
        "Effect": "Allow",
        "Principal": {
            "AWS": "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity XXX"
        },
        "Resource": "arn:aws:s3:::doggybites-cloud-resources-xxx",
        "Sid": ""
    }],
    "Version": "2012-10-17"
}
```
We do generate this policy with a jsonencode operation but I gave it a go with just a normal call like this:
`policy = data.aws_iam_policy_document.s3_public_html_access_policy[each.value].json`
and was still the same.

**Closed** 2021-12-16 22:22 UTC
Labels: enhancement, service/iam, service/kms, service/sts

**Comment by YakDriver** [comment] 2021-12-16 22:36
@anthonyAdhese We hoped to alleviate the majority of a pain points with this push. I ask that you give 3.70.0 a try when it is available. If you're still seeing issues, please open a new issue! We will need a complete config to be able to reproduce the issue.

**Comment by dsnellgrove** [comment] 2021-12-17 17:38
The form of the defect described here https://github.com/hashicorp/terraform-provider-aws/issues/11801#issuecomment-848984552 is still occurring.
```
$ terraform --version
Terraform v1.1.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.70.0
```

**Comment by yongzhang** [comment] 2021-12-20 01:44
> 

I think if you plan the second time, you won't see the diffs.

**Comment by yongzhang** [comment] 2021-12-20 01:44
> The form of the defect described here [#11801 (comment)](https://github.com/hashicorp/terraform-provider-aws/issues/11801#issuecomment-848984552) is still occurring.
> 
> ```
> $ terraform --version
> Terraform v1.1.1
> on darwin_amd64
> + provider registry.terraform.io/hashicorp/aws v3.70.0
> ```

I think if you plan the second time, you won't see the diffs.

**Comment by dsnellgrove** [comment] 2021-12-20 11:26
It still occurs on every plan for a random selection of resources even after applying changes but I'll be switching to one of the newly reported defects that cover my specific remaining symptoms as suggested by YakDriver.

Thanks all for the great work on the larger issue group, it's clearly been a lot of work!
