### ISSUE TITLE
Intermittent provider failure difficult to reproduce

### ISSUE THREAD

**Issue by mehemken** [hashicorp/terraform-provider-aws#23850] opened 2022-03-24 13:43 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
❯ terraform version
Terraform v1.1.2  # But this also happens with 0.15.x on my other machine
❯ terraform init

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of hashicorp/aws from the dependency lock file
- Using previously-installed hashicorp/aws v4.6.0  # but this also happens in >=3.70

Terraform has been successfully initialized!
...
```

### Affected Resource(s)
* the whole thing

### Terraform Configuration Files

[My configuration files][meh-config]. But this happens with any configuration.

### Expected Behavior

Normal terraform

### Actual Behavior

Various errors that I can simply ignore and re-run the same terraform command and get normal behavior.

```
# This one happens after entering 'yes' in the apply user input
│ Error: Unrecognized remote plugin message:
│
│ This usually means that the plugin is either invalid or simply
│ needs to be recompiled to support the latest protocol.
```

```
# This one happens with terraform plan
│ Error: Failed to load plugin schemas
│
│ Error while loading schemas for plugin components: Failed to obtain provider schema: Could not load the schema for provider registry.terraform.io/hashicorp/aws: failed to
│ instantiate provider "registry.terraform.io/hashicorp/aws" to obtain schema: Unrecognized remote plugin message:
│
│ This usually means that the plugin is either invalid or simply
│ needs to be recompiled to support the latest protocol...
```

### Steps to Reproduce

Honestly I don't know. This happens intermittently and it is very annoying. Sometimes things will work normally for 30 min and then just as I'm on the verge of deploying a beautiful piece of infrastructure I get the errors. 

1. `terraform apply`
1. `terraform plan`

### Important Factoids

This started happening in Q3 2021 when I got the apple M1 machines. I've fallen victim to this on the MacBook Air and the MacBook Pro.

[meh-config]: https://github.com/mehemken/tf-aws-provider-bug-reproduction "meh-config"

**Comment by justinretzolk** [comment] 2022-03-24 18:58
Hey @mehemken 👋 Thank you for taking the time to raise this! I realize this may be difficult given the intermittent nature of this issue, but can you try to capture debug logs (and redact them as needed) while reproducing this so that we have all of the necessary information in order to look into it?

**Comment by mehemken** [comment] 2022-03-25 13:24
Thanks, @justinretzolk . I'll get some debug logs as soon as I can. Hopefully today, if not tomorrow.

**Comment by chrisgilbert** [comment] 2022-03-25 17:21
I also seem to be getting this too. I had it on terraform 1.1.3, and then just got it again when updating to 1.1.7. 

It took me awhile to work out that the tfenv tool was downloading the amd64 version of terraform by default, which only seems to intermitently work on the M1. When I switched it to the arm64 version, it was much more reliable and seems OK now. I did that with:

```
TFENV_ARCH=arm64 tfenv install 1.1.7
```
Whether or not you are using tfenv, you can check whether you are using the amd64 version or the arm64 one with `terraform version` (at least, it tells me on 1.1.3 and up).

I guess you might also need to do another `terraform init` to download the arm64 version of the AWS provider to match.

**Comment by mhemken-vts** [comment] 2022-03-28 17:52
Thanks @chrisgilbert ,
Turns out we get a 403 error when downloading terraform versions below 1.0 on arm64 architecture. There's already an issue about it https://github.com/tfutils/tfenv/issues/319

**Comment by bryanhiestand** [comment] 2022-05-04 01:50
> I also seem to be getting this too. I had it on terraform 1.1.3, and then just got it again when updating to 1.1.7.
> 
> It took me awhile to work out that the tfenv tool was downloading the amd64 version of terraform by default, which only seems to intermitently work on the M1. When I switched it to the arm64 version, it was much more reliable and seems OK now. I did that with:
> 
> ```
> TFENV_ARCH=arm64 tfenv install 1.1.7
> ```
> 
> Whether or not you are using tfenv, you can check whether you are using the amd64 version or the arm64 one with `terraform version` (at least, it tells me on 1.1.3 and up).
> 
> I guess you might also need to do another `terraform init` to download the arm64 version of the AWS provider to match.

Setting `GODEBUG=asyncpreemptoff=1` fixed all of my issues with amd64 compiled versions of terraform running under Rosetta 2. [Apple M1, terraform and golang
](https://yaleman.org/post/2021/2021-01-01-apple-m1-terraform-and-golang/)

**Comment by justinretzolk** [comment] 2022-05-06 18:24
Hey y'all 👋 Given that this appears to be an issue of `tftenv` grabbing the `amd64` version of Terraform rather than the `arm64` version, I'm going to close this issue. If you feel that I've done this in error, please do let me know.

**Closed by justinretzolk** 2022-05-06 18:24 UTC
Labels: bug, provider
