### ISSUE TITLE
[Bug]: aws_iam_policy_document json output is "known after apply" when any depends exists

### ISSUE THREAD

**Issue by dmoses-xh** [hashicorp/terraform-provider-aws#38893] opened 2024-08-15 22:32 UTC
### Terraform Core Version

1.9.1

### AWS Provider Version

5.62.0

### Affected Resource(s)

data.aws_iam_policy_document

### Expected Behavior

When a `data.aws_iam_policy_document` has a dependency but all the statements are able to be known, there is no reason the output json should not also be known.

### Actual Behavior

when a `data.aws_iam_policy_document` has ANY dependency then the json output is `known after apply`, even when all the contents that make up the json are KNOWN

### Terraform Configuration Files

```hcl
terraform {
  required_version = "1.9.1"
}

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.62.0"
    }
  }
}

provider "aws" {
  region = "us-east-2"
}

resource "aws_iam_role" "example" {
  name = "example"

  assume_role_policy = jsonencode({})
}

data "aws_iam_policy_document" "example" {
  statement {
    sid    = "InvokesLambdas"
    effect = "Allow"
    actions = [
      "lambda:InvokeFunction",
    ]
    resources = [
      "arn", # a common example for this is a lambda arn that doesn't change on lambda deploy
    ]
  }
  # comment this depends and the plan is correct
  depends_on = [aws_iam_role.example]
}

resource "aws_iam_role_policy" "example" {
  name   = "example"
  role   = "example"
  policy = data.aws_iam_policy_document.example.json
}
```

### Steps to Reproduce

Run the above with a `terraform plan`
Notice the unknown json even though all of the statement is known.

```hcl
Terraform will perform the following actions:

  # data.aws_iam_policy_document.example will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "aws_iam_policy_document" "example" {
      + id            = (known after apply)
      + json          = (known after apply)
      + minified_json = (known after apply)

      + statement {
          + actions   = [
              + "lambda:InvokeFunction",
            ]
          + effect    = "Allow"
          + resources = [
              + "arn",
            ]
          + sid       = "InvokesLambdas"
        }
    }

  # aws_iam_role.example will be created
  + resource "aws_iam_role" "example" {
      + arn                   = (known after apply)
      + create_date           = (known after apply)
      + force_detach_policies = false
      + id                    = (known after apply)
      + managed_policy_arns   = (known after apply)
      + max_session_duration  = 3600
      + name                  = "example"
      + name_prefix           = (known after apply)
      + path                  = "/"
      + tags_all              = (known after apply)
      + unique_id             = (known after apply)
        # (1 unchanged attribute hidden)

      + inline_policy (known after apply)
    }

  # aws_iam_role_policy.example will be created
  + resource "aws_iam_role_policy" "example" {
      + id          = (known after apply)
      + name        = "example"
      + name_prefix = (known after apply)
      + policy      = (known after apply)
      + role        = "example"
    }

Plan: 2 to add, 0 to change, 0 to destroy.
```

Run `terraform plan` again with the depends commented out.  Notice the data doesn't show as the json is known and now the role_policy can be correctly shown

```hcl
Terraform will perform the following actions:

  # aws_iam_role.example will be created
  + resource "aws_iam_role" "example" {
      + arn                   = (known after apply)
      + create_date           = (known after apply)
      + force_detach_policies = false
      + id                    = (known after apply)
      + managed_policy_arns   = (known after apply)
      + max_session_duration  = 3600
      + name                  = "example"
      + name_prefix           = (known after apply)
      + path                  = "/"
      + tags_all              = (known after apply)
      + unique_id             = (known after apply)
        # (1 unchanged attribute hidden)

      + inline_policy (known after apply)
    }

  # aws_iam_role_policy.example will be created
  + resource "aws_iam_role_policy" "example" {
      + id          = (known after apply)
      + name        = "example"
      + name_prefix = (known after apply)
      + policy      = jsonencode(
            {
              + Statement = [
                  + {
                      + Action   = "lambda:InvokeFunction"
                      + Effect   = "Allow"
                      + Resource = "arn"
                      + Sid      = "InvokesLambdas"
                    },
                ]
              + Version   = "2012-10-17"
            }
        )
      + role        = "example"
    }

Plan: 2 to add, 0 to change, 0 to destroy.
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-08-19 21:05
Hey @dmoses-xh 👋 Thank you for taking the time to raise this! The behavior you're seeing here is one controlled by Terraform, and not something that the AWS provider can control. This is described in the Terraform documentation under [Data Resource Behavior](https://developer.hashicorp.com/terraform/language/data-sources#data-resource-behavior).

As you mentioned, the parts of the policy are determined by the arguments that are supplied, so they're known during plan time. The `json` and `minified_json` attributes, however, [are `Computed`](https://github.com/hashicorp/terraform-provider-aws/blob/be7be81584b81d7b40c0a317882d6666da4444a3/internal/service/iam/policy_document_data_source.go#L63-L70). When Terraform must delay reading a resource until apply time, the plan appears as shown in your examples -- known values are printed while `Computed` attributes are represented by `(known after apply)`.

Since this is expected behavior, and not something the provider team will need to make further changes for, I'm going to close this issue. If you run into unexpected behavior in the future, please do let us know!

**Closed by justinretzolk** 2024-08-19 21:05 UTC
Labels: bug, service/iam, needs-triage
