### ISSUE TITLE
Add AWS Glue Schema Registry to aws provider

### ISSUE THREAD

**Issue by njoaquim** [hashicorp/terraform-provider-aws#16411] opened 2020-11-24 17:56 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Glue Schema Registry is a serverless feature of AWS Glue, enables you to validate and control the evolution of streaming data using registered Apache Avro schemas. The Schema Registry integrates with other AWS Services such Apache Kafka/Amazon Managed Streaming for Apache Kafka (MSK), Amazon Kinesis Data Streams, Apache Flink/Amazon Kinesis Data Analytics for Apache Flink, and AWS Lambda.

### New or Affected Resource(s)

New
* aws_glue_registry
* aws_glue_schema
* aws_glue_schema_version

### Potential Terraform Configuration

```hcl
resource "aws_glue_registry" "example-registry" {
  name     = "example"
  description = "example"
  tags          = var.tags
}

resource "aws_glue_schema" "example-schema" {
  name     = "example"
  registry_arn = "arn:aws:glue:eu-central-1:XXXXXXXXXX:registry/example-registry"
  data_format = "Apache Avro"
  compatibility_mode = "BACKWARD"
  description = "example"
  tags          = var.tags
}

resource "aws_glue_schema_version" "example-schema-version" {
  name              = "example"
  description       = "example"
  schema_arn = "arn:aws:glue:eu-central-1:XXXXXXXXXX:schema/example/example-schema"
  schema_definition    = var.schema_definition
}


```

### References

https://aws.amazon.com/about-aws/whats-new/2020/11/control-evolution-data-streams-using-aws-glue-schema-registry/

* #0000

**Comment by DrFaust92** [comment] 2020-11-24 18:27
Duplicate of #16342

**Closed by DrFaust92** 2020-11-24 18:27 UTC
Labels: enhancement, needs-triage, service/glue
