### ISSUE TITLE
[Bug]: Provider produced inconsistent final plan for complex `aws_wafv2_web_acl` configurations

### ISSUE THREAD

**Issue by mkielar** [hashicorp/terraform-provider-aws#27273] opened 2022-10-17 10:06 UTC
Related:
- #23390
- #23423
- #23936
- #23992
- #24386
- #27175
- 👉 #27273
- #27479
- #28191
- #28672
- #29012
- #29304
- #30858

### Terraform Core Version

1.3.1

### AWS Provider Version

4.34.

### Affected Resource(s)

* `aws_wafv2_web_acl`

### Expected Behavior

Running `terraform apply` should finish successfully

### Actual Behavior

Running `terraform apply` fails, and outputs a ~2.5MB Go StackTrace.

### Relevant Error/Panic Output Snippet

```shell
Plan: 0 to add, 1 to change, 0 to destroy.

Error: Provider produced inconsistent final plan

When expanding the plan for aws_wafv2_web_acl.main to include new values
learned so far during apply, provider "registry.terraform.io/hashicorp/aws"
produced an invalid new value for .rule: planned set element
cty.ObjectVal(map[string]cty.Value{"action":cty.ListValEmpty(cty.Object(map[string]cty.Type{"allow":cty.List(cty.Object(map[string]cty.Type{"custom_request_handling":cty.List(cty.Object(map[string]cty.Type{"insert_header":cty.Set(cty.Object(map[string]cty.Type{"name":cty.String,
"value":cty.String}))}))})),
"block":cty.List(cty.Object(map[string]cty.Type{"custom_response":cty.List(cty.Object(map[string]cty.Type{"custom_response_body_key":cty.String,
"response_code":cty.Number,

... (this continues for 2,5MB (see "_expected/out.log" in attached ZIP File)
```

### Terraform Configuration Files

See attached: [tf-waf-custom-response-bug.zip](https://github.com/hashicorp/terraform-provider-aws/files/9798659/tf-waf-custom-response-bug.zip)

### Steps to Reproduce

1. `terraform init`
2. `terraform apply -var='v=1'`
   This will deploy all resources and will provision `v1` of the Custom Response we configure for WAF WebACL to display a Maintenance Page. This should pass correctly.
3. `terraform apply -var='v=2' --auto-approve > out.log 2>&1`   
    This will mimic making modification to the HTML in Custom Response (terraform will use a differenf file to generate a change in WebACL Custom Response Configuration). You should see a very long exception logged.

### Debug Output

N/A

### Panic Output

See `_expected/out.log` in attached ZIP file.

### Important Factoids

1. I initially thought the error is caused by HTML in CustomResource, but then I started reproducing this error with minimal configuration, and only was able to reproduce when I added all of the rules we use in our production. E.g., if you remove the last set of rules (the `dynamic` section operating on `local.managed_rules`) the error no longer occurs. This would suggest that the error is a result of overall complexity (or perhaps size?) of the change to apply, or a combination of settings, rather than a single setting. But that's just my impression.
2. I have tried several other changes to work around the issue, and it seems like trying to change any _custom response_ in this particular setup causes that error. 
2.1. I eventually changed the `website` rule to returning a `307` response with `Location` header, and that would still fail when trying to apply the change
2.2. I also tried to remove the `custom response` for `api` rule, and make it also only respond with status and headers, and terraform failed to remove _custom response_ in this case as well (in this case the reponse is just a simple JSON, so it seems the content is irrelevant).
3. I also tried running that with `TF_LOG=debug` (unfortunately don't have that log anymore) and I remember seeing several _"Produced inconsistent plan, but we don't care because it's using legacy SDK"_ sort of messages around all WAFv2 resource (not just WebACL). Perhaps that's related?

### Would you like to implement a fix?

No

**Comment by ewbankkit** [comment] 2022-10-17 15:29
@mkielar Thanks for raising this issue 👏.
Does the same error occur if you use **v4.33.0** of the Terraform AWS Provider?

Possibly related:

* https://github.com/hashicorp/terraform-provider-aws/pull/26506
* https://github.com/hashicorp/terraform-provider-aws/pull/22452

**Comment by mkielar** [comment] 2022-10-18 07:11
@ewbankkit, yup, **v4.33.0** also fails. I haven't verified if its exactly the same error but it looks similar after a brief review. Attached: [out_4_33.zip](https://github.com/hashicorp/terraform-provider-aws/files/9807399/out_4_33.zip)

**Comment by fabricef-p** [comment] 2022-10-18 08:43
I can confirm we are also affected by this issue

**Comment by xael-fry** [comment] 2022-10-26 05:21
It look as the same problem as #23936, #27175, #23390

**Comment by mmaetzler** [comment] 2022-11-04 23:33
FYI: This issues with WAFv2 has been reported multiple times: 

- #23390
- #23423
- #23936
- #23992
- #24386
- #27175
- #27273
- #27479

**Comment by smailc** [comment] 2023-01-11 13:39
Is this being worked on? Just started happening for me. Adding any new block and attempting apply gives a huge provider error.

**Comment by petur** [comment] 2023-02-03 14:28
This started happening after upgrading to version 4.52.0, even with no changes in the configuration. After the provider is upgraded, `terraform plan` shows a huge diff for the resource (even if nothing is really changing), then when it tries to apply it fails with this error.

Staying on 4.51.0 isn't a viable workaround because `oversize_handling` will become required soon.

**Comment by bkona-alopa** [comment] 2023-02-07 09:50
Same thing is happening after upgrading to version 4.52.0.

**Comment by nodomain** [comment] 2023-03-20 21:39
Workaround to pin version to 4.51.0 did not do the trick here. Any other workarounds?

**Comment by nunofernandes** [comment] 2023-05-16 11:16
The workaround for me was to taint the resource and then apply. It recreates the WAFv2.
Another option that I did and worked was to use aws console to delete a few of the rules in the WAF and then doing an apply. That also worked (sometimes).

**Comment by YakDriver** [comment] 2023-07-13 21:17
**NOTE:** I cannot reproduce this error after trying various configurations. _**Let us know**_ if this is still a problem! If we don't hear and can't reproduce, we plan to close this on or around **July 20, 2023**. The evidence suggests this is OBE (ie, fixed in the interim).

For more details see #23992 ([comment](https://github.com/hashicorp/terraform-provider-aws/issues/23992#issuecomment-1634920741)).

**Comment by mkielar** [comment] 2023-07-14 06:30
@YakDriver, thanks for looking into the issue.

I have tested some configurations this morning, mostly the ones I currently have + the ones I'm planning to migrate to:
```
1.4.2 + 4.67.0: worked!
1.4.6 + 4.67.0: worked!
1.5.3 + 5.8.0:  worked! # Needed to refactor excluded_rule => rule_action_override for this to work,
```
I can also say I've introduced some (sometimes significant) changes to my WAF deployment scripts since this ticket was raised, and all of them worked without issues. Looks like this is indeed resolved, at least for my case.

**Comment by justinretzolk** [comment] 2023-07-20 17:23
Hi all :wave: As was mentioned above, this issue appears to be fixed when using a minimum Terraform version of 1.4.2 and a minimum AWS Provider version of 4.67.0 (preferably Terraform 1.5.3 or later and AWS Provider 5.8.0 or later). If you experience additional unexpected behaviors with versions that meet these parameters, please open a new issue so that we can investigate further.

**Closed by justinretzolk** 2023-07-20 17:23 UTC
Labels: bug, waiting-response, service/wafv2
