### ISSUE TITLE
[Bug]: Resource: aws_vpc_peering_connection_options

### ISSUE THREAD

**Issue by network-charles** [hashicorp/terraform-provider-aws#31068] opened 2023-04-29 13:02 UTC
### Terraform Core Version

0.13+

### AWS Provider Version

4.65.0

### Affected Resource(s)
```terraform
resource "aws_vpc_peering_connection_options" "requester" {
  provider = aws.requester

  # As options can't be set until the connection has been accepted
  # create an explicit dependency on the accepter.
  vpc_peering_connection_id = aws_vpc_peering_connection_accepter.peer.id

  requester {
    allow_remote_vpc_dns_resolution = true
  }
}
```
### Expected Behavior

- The requester account ought to work with "accepter" resource to approve the connection so it becomes active.

### Actual Behavior

The resource failed. It only worked when I used ```provider = aws.accepter``` there.

### Relevant Error/Panic Output Snippet

```shell
Error: modifying EC2 VPC Peering Connection (pcx-xxxx) Options: OperationNotPermitted: User xxxx does not have permission to modify the accepter side peering options
```

### Terraform Configuration Files
```terraform
resource "aws_vpc" "VPC_A_Acct_1" {
  cidr_block       = "192.168.0.0/16"
  instance_tenancy = "default"
  enable_dns_hostnames = true
  enable_dns_support = true

  provider = aws.Account_1

  tags = {
    Name = "VPC_A_Acct_1"
  }
}

resource "aws_vpc" "VPC_A_Acct_2" {
  cidr_block       = "172.20.0.0/16"
  instance_tenancy = "default"
  enable_dns_hostnames = true
  enable_dns_support = true
  
  provider         = aws.Account_2

  tags = {
    Name = "VPC_A_Acct_2"
  }
}

# Requester's side of the connection.
resource "aws_vpc_peering_connection" "VPC_A_Acct_1_and_VPC_A_Acct_2_Peering" {
  vpc_id        = aws_vpc.VPC_A_Acct_1.id # VPC Peering Requester; source. Can be in the same account or another.
  provider      = aws.Account_1 # Allows the Requester VPC in another account to be applied into the resource

  peer_owner_id = var.peer_owner_id_acct_2 # The account that creates the VPC Peering
  peer_vpc_id   = aws_vpc.VPC_A_Acct_2.id        # The Accounts VPC Peering Accepter; destination.

  tags = {
    Name = "VPC_A_Acct_1_and_VPC_A_Acct_2_Peering"
    Side = "Requester"
  }
}

resource "aws_vpc_peering_connection_accepter" "peer" {
  vpc_peering_connection_id = aws_vpc_peering_connection.VPC_A_Acct_1_and_VPC_A_Acct_2_Peering.id
  auto_accept = true
  provider = aws.Account_2

  tags = {
    Side = "Accepter"
  }
}

resource "aws_vpc_peering_connection_options" "Requester" {
  vpc_peering_connection_id = aws_vpc_peering_connection.VPC_A_Acct_1_and_VPC_A_Acct_2_Peering.id
  provider = aws.Account_1 

  accepter {
    allow_remote_vpc_dns_resolution = true
  }

  depends_on = [ aws_vpc_peering_connection_options.Accepter, aws_vpc_peering_connection_accepter.peer ]

}

resource "aws_vpc_peering_connection_options" "Accepter" {
  provider                  = aws.Account_2
  vpc_peering_connection_id = aws_vpc_peering_connection.VPC_A_Acct_1_and_VPC_A_Acct_2_Peering.id

  accepter {
    allow_remote_vpc_dns_resolution = true
  }

}
```

### Steps to Reproduce

Just do a ```terraform apply -auto-approve```

### Important Factoids

I use VS Code. I also use the Linux version of terraform in my CLI.

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment] 2023-06-12 21:28
Hey @network-charles 👋 Thank you for taking the time to raise this! Is the sample configuration that you provided the one that errored? If so, if I'm reading the documentation for this resource correctly, I believe the issue is the use of the `accepter` block rather than the `requester` block here:

```terraform
resource "aws_vpc_peering_connection_options" "Requester" {
  vpc_peering_connection_id = aws_vpc_peering_connection.VPC_A_Acct_1_and_VPC_A_Acct_2_Peering.id
  provider = aws.Account_1 

  accepter {
    allow_remote_vpc_dns_resolution = true
  }

  depends_on = [ aws_vpc_peering_connection_options.Accepter, aws_vpc_peering_connection_accepter.peer ]
}
```

**Comment by network-charles** [comment] 2023-07-26 19:40
Hi Justin, sorry for the late reply.
You are correct, the issue is for the `accepter` block. I was surprised that I had to use the alias `Account_1` in both the `requester` and the `accepter` block.

**Comment by justinretzolk** [comment] 2023-08-04 16:58
Thank you for coming back with the update! With that in mind, I'll go ahead and close this one out. If you feel I've done this in error, please do let me know.

**Closed by justinretzolk** 2023-08-04 16:58 UTC
Labels: bug, service/vpc
