### ISSUE TITLE
[Bug]: aws_spot_instance_request ignores metadata_options block

### ISSUE THREAD

**Issue by aprescott706** [hashicorp/terraform-provider-aws#35883] opened 2024-02-19 20:46 UTC
### Terraform Core Version

1.5.7, 1.3.7

### AWS Provider Version

5.37.0

### Affected Resource(s)

aws_spot_instance_request

### Expected Behavior

Deploying the following configuration should create a spot instance with IMDSv2 enabled.

resource "aws_spot_instance_request" "example" {
  ami           = "ami-0bd145fb0f2dd3da5"
  instance_type = "t2.micro"

  metadata_options {
    http_tokens = "required"
  }
}

### Actual Behavior

The resulting instance is still using IMDSv1.

### Terraform Configuration Files

terraform {
  required_version = ">= 1.3, < 1.6"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

resource "aws_spot_instance_request" "example" {
  ami           = "ami-0bd145fb0f2dd3da5"
  instance_type = "t2.micro"

  metadata_options {
    http_tokens = "required"
  }
}

### Steps to Reproduce

With the above configuration:

Run terraform plan -out .tfplan
Run terraform apply .tfplan

### Important Factoids

No errors are encountered. The plan picks up changes to the http_tokens property when switched between "required" and "optional" but IMDS always remains on version 1.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-03-14 15:46
It looks like this is a duplicate of #25896, so I'll be closing it with that in mind. That said, I did find a comment on [a similar issue](https://github.com/hashicorp/terraform-provider-aws/issues/21204#issuecomment-1852032527) that called out one of the notes in the [`aws_spot_instance_request` documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/spot_instance_request). This note indicates that AWS strongly advises against using the legacy APIs associated with this resource, and that we recommend using the [`aws_instance` resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance) with `instance_market_options` instead.

**Comment by justinretzolk** [comment] 2024-03-14 15:46
Duplicate of #25896

**Closed by justinretzolk** 2024-03-14 15:46 UTC
Labels: bug, service/ec2, needs-triage
