### ISSUE TITLE
[Enhancement]: AWS Directory Service "Notification"

### ISSUE THREAD

**Issue by marcosentino** [hashicorp/terraform-provider-aws#27981] opened 2022-11-23 16:15 UTC
### Description

Add support for managing notification setting in AWS Directory service.

### Affected Resource(s) and/or Data Source(s)

aws_directory_service_directory

### Potential Terraform Configuration

```terraform
Expectation:
resource "aws_directory_service_directory" "directory" {
  notification_setting {
  }
}
```

### References

Manual method: https://docs.aws.amazon.com/directoryservice/latest/admin-guide/ms_ad_enable_notifications.html

**Comment by TheJacobWalters** [comment] 2022-11-23 16:31
Is it possible to create a directory service notification through the API? 

I looked at the documentation here

https://docs.aws.amazon.com/directoryservice/latest/devguide/API_CreateDirectory.html

and I am not seeing any calls with names like "CreateNotification" and I'm not seeing that AWS API call CreateDirectory can have a notification specified?

Is that accurate?

**Comment by DrFaust92** [comment] 2022-12-13 21:25
seems to be duplicate of #28279 which has a bit more info.

**Closed by DrFaust92** 2022-12-13 21:25 UTC
Labels: enhancement, service/ds
