### ISSUE TITLE
Unable to create Aurora Serverless v2 instance w/Terraform but can in AWS Console

### ISSUE THREAD

**Issue by borinquenkid** [hashicorp/terraform-provider-aws#24502] opened 2022-05-02 15:38 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform 1.1 aws-provider 4.12.1
### Affected Resource(s)

* aws_rds_cluster

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_rds_cluster" "default" {
  count              = "1"
  cluster_identifier = "${var.db_rds_instance_identifier}-cluster"
  availability_zones = data.terraform_remote_state.plxis_cde.outputs.azs[local.region_short_name]

  engine         = "aurora-postgresql"
  engine_version = "13.6"
  engine_mode    = "serverless"

  database_name                       = "${var.environment}-${local.region_short_name}-${var.context}-db"
  master_username                     = <>
  master_password                     = <>
  final_snapshot_identifier           = "DELETE-ME"
  skip_final_snapshot                 = false
  backup_retention_period             = 5
  preferred_backup_window             = "02:00-03:00"
  preferred_maintenance_window        = "sun:05:00-sun:06:00"
  port                                = "3306"
  db_subnet_group_name                = aws_db_subnet_group.default.id
  vpc_security_group_ids              =  [aws_security_group.rds.id]
  storage_encrypted                   = true
  apply_immediately                   = true
  db_cluster_parameter_group_name     = "default.aurora-postgresql13"
  iam_database_authentication_enabled = true
  enable_http_endpoint                = true



  serverlessv2_scaling_configuration {
    max_capacity = 1.0
    min_capacity = 0.5
  }


  lifecycle {
    create_before_destroy = true
  }

}
```

### Debug Output

 Error: error creating RDS cluster: InvalidParameterValue: The engine mode serverless you requested is currently unavailable.
│       status code: 400, request id: efbd5336-2bc0-42f8-ab2b-01f1bf33a9d9

### Expected Behavior

Create Aurora Serverless 2 Cluster

### Actual Behavior

Did not create Aurora Serverless 2 Cluster

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

None

### References
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless-v2-administration.html

```aws rds create-db-cluster --engine aurora-postgresql  --engine-version 13.6 --serverless-v2-scaling-configuration MinCapacity=0.5,MaxCapacity=1.0 ```

* #0000
*

**Comment by justinretzolk** [comment] 2022-05-02 16:00
Hey @borinquenkid  👋 Thank you for taking the time to raise this! So that we have all of the necessary information in order to look into this, can you update the issue description to include all of the information requested in the [bug report template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md?plain=1)?

**Comment by ewbankkit** [comment] 2022-05-02 18:09
@borinquenkid A documentation update has just been merged in https://github.com/hashicorp/terraform-provider-aws/pull/24491 and will be released this week.
`engine_mode = "provisioned"` is required for Aurora Serverless v2.

**Comment by borinquenkid** [comment] 2022-05-03 14:04
I modified the rds.rtf 
```
resource "aws_rds_cluster" "default" {
  count              = "1"
  cluster_identifier = "dev-awse-vpsbillingdb-cluster"
  availability_zones = data.terraform_remote_state.plxis_cde.outputs.azs[local.region_short_name]

  engine         = "aurora-postgresql"
  engine_version = "13.6"
  engine_mode    = "provisioned"

  database_name                       = "devAwseVpsBillingDb"
  master_username                     = var.db_user
  master_password                     = var.db_password
  final_snapshot_identifier           = "DELETE-ME"
  skip_final_snapshot                 = false
  backup_retention_period             = 5
  preferred_backup_window             = "02:00-03:00"
  preferred_maintenance_window        = "sun:05:00-sun:06:00"
  port                                = var.db_port
  db_subnet_group_name                = aws_db_subnet_group.cluster.id
  vpc_security_group_ids              =  [aws_security_group.rds.id]
  storage_encrypted                   = true
  apply_immediately                   = true
  db_cluster_parameter_group_name     = "default.aurora-postgresql13"
  iam_database_authentication_enabled = true
  enable_http_endpoint                = true



  serverlessv2_scaling_configuration {
    max_capacity = 1.0
    min_capacity = 0.5
  }


  lifecycle {
    create_before_destroy = true
  }

}
```
I get success from terraform but then I run the following the next day
```
vps-billing wduque$ aws rds describe-db-cluster-endpoints --region us-east-1  --db-cluster-identifier dev-awse-vpsbillingdb-cluster
{
    "DBClusterEndpoints": [
        {
            "DBClusterIdentifier": "dev-awse-vpsbillingdb-cluster",
            "Endpoint": "dev-awse-vpsbillingdb-cluster.cluster-c4ciafbqkip2.us-east-1.rds.amazonaws.com",
            "Status": "creating",
            "EndpointType": "WRITER"
        },
        {
            "DBClusterIdentifier": "dev-awse-vpsbillingdb-cluster",
            "Endpoint": "dev-awse-vpsbillingdb-cluster.cluster-ro-c4ciafbqkip2.us-east-1.rds.amazonaws.com",
            "Status": "creating",
            "EndpointType": "READER"
        }
    ]
}
```
When I create from the AWS console and I run the cli I get this:
```
 aws rds describe-db-cluster-endpoints --region us-east-1  --db-cluster-identifier  postgresql-cluster-from-console
{
    "DBClusterEndpoints": [
        {
            "DBClusterIdentifier": "postgresql-cluster-from-console",
            "Endpoint": "postgresql-cluster-from-console.cluster-c4ciafbqkip2.us-east-1.rds.amazonaws.com",
            "Status": "available",
            "EndpointType": "WRITER"
        },
        {
            "DBClusterIdentifier": "postgresql-cluster-from-console",
            "Endpoint": "postgresql-cluster-from-console.cluster-ro-c4ciafbqkip2.us-east-1.rds.amazonaws.com",
            "Status": "available",
            "EndpointType": "READER"
        }
    ]
}

```

**Comment by mcbainuk12** [comment] 2022-05-03 14:57
Hello,

I've just had the above issue, but it's due to us missing an important step, that's not documented "yet". It's in here though
https://github.com/hashicorp/terraform-provider-aws/issues/24349

we need to add 
resource "aws_rds_cluster_instance" "cluster_instances" {
  instance_class     = "db.serverless"
  engine             = aws_rds_cluster.default.engine
  engine_version     = aws_rds_cluster.default.engine_version
}

I've not tried it myself yet. but it seems like this is the cause of the instances being stuck in CREATING.

**Comment by mcbainuk12** [comment] 2022-05-03 17:49
I was having the same problem. Hopefully the Terraform docs will be updated with a good example of serverless v2.
I think what's missing is the fact you still need to add a db instance to the cluster

resource "aws_rds_cluster_instance" "cluster_instances" {
  cluster_identifier = aws_rds_cluster.this.id
  instance_class     = "db.serverless"
  engine             = aws_rds_cluster.this.engine
  engine_version     = aws_rds_cluster.this.engine_version
}

Where the instance class is the important bit.

After adding this, it worked for me. I hink you can also add a reader instance in another AZ for failover.... but don't quote me on that.

**Comment by anGie44** [comment] 2022-05-13 15:17
Note: remaining action item for this issue may be to add a serverless v2 example in the docs as suggested by @mcbainuk12 above since the required param has been updated in v4.13.0.

**Closed** 2022-05-17 17:00 UTC
Labels: documentation, service/rds
