### ISSUE TITLE
[Bug]: Error: Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by converseml** [hashicorp/terraform-provider-aws#29304] opened 2023-02-08 15:42 UTC
Related:
- #23390
- #23423
- #23936
- #23992
- #24386
- #27175
- #27273
- #27479
- #28191
- #28672
- #29012
- 👉 #29304
- #30858

### Terraform Core Version

Terraform v1.3.7

### AWS Provider Version

v4.53.0

### Affected Resource(s)

aws_wafv2_web_acl

### Expected Behavior

on second terraform apply rule changes successful

### Actual Behavior

on second terraform apply rule changes fail

│ When expanding the plan for aws_wafv2_web_acl.prod_cloudoffice-test to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .rule:
│ planned set element
│ cty.ObjectVal(map[string]cty.Value{"action":cty.ListValEmpty(cty.Object(map[string]cty.Type{"allow":cty.List(cty.Object(map[string]cty.Type{"custom_request_handling":cty.List(cty.Object(map[string]cty.Type{"insert_header":cty.Set(cty.Object(map[string]cty.Type{"name":cty.String,
│ "value":cty.String}))}))})), "block":cty.List(cty.Object(map[string]cty.Type{"custom_response":cty.List(cty.Object(map[string]cty.Type{"custom_response_body_key":cty.String, "response_code":cty.Number,
│ "response_header":cty.Set(cty.Object(map[string]cty.Type{"name":cty.String, "value":cty.String}))}))})),
│ "captcha":cty.List(cty.Object(map[string]cty.Type{"custom_request_handling":cty.List(cty.Object(map[string]cty.Type{"insert_header":cty.Set(cty.Object(map[string]cty.Type{"name":cty.String,
│ "value":cty.String}))}))})),

### Terraform Configuration Files

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
  }
}

resource "aws_wafv2_web_acl" "prod_cloudoffice-test" {
  name = "prod_cloudoffice-test"
  #description = ""
  scope = "REGIONAL"
  
  default_action {
    block {}
  }

  visibility_config {
    cloudwatch_metrics_enabled = true
    metric_name                = "prod_cloudoffice"
    sampled_requests_enabled = true
  }   

  rule {
      name     = "AWS-AWSManagedRulesBotControlRuleSet"
      priority = 0

      override_action {

          none {}
      }

      statement {

          managed_rule_group_statement {
              name        = "AWSManagedRulesBotControlRuleSet"
              vendor_name = "AWS"

              managed_rule_group_configs {
                  aws_managed_rules_bot_control_rule_set {
                      inspection_level = "COMMON"
                  }
              }

              rule_action_override {
                  name = "SignalNonBrowserUserAgent"

                  action_to_use {

                      count {}
                  }
              }
              rule_action_override {
                  name = "CategorySocialMedia"

                  action_to_use {

                      count {}
                  }
              }
              rule_action_override {
                  name = "CategorySearchEngine"

                  action_to_use {

                      count {}
                  }
              }
              rule_action_override {
                  name = "CategorySeo"

                  action_to_use {

                      count {}
                  }
              }
              rule_action_override {
                  name = "CategoryLinkChecker"

                  action_to_use {

                      count {}
                  }
              }
          }
      }
  
    visibility_config {
        cloudwatch_metrics_enabled = true
        metric_name                = "prod_cloudoffice-test-new"
        sampled_requests_enabled = true
    }
  }

  rule {
    name     = "exception-canaries"
    priority = 1

    action {
        count {}
    }

    rule_label {
        name = "guideit:goodbots"
    }

    statement {

        or_statement {
            statement {

                byte_match_statement {
                    positional_constraint = "CONTAINS"
                    search_string         = "canary"

                    field_to_match {

                        single_header {
                            name = "user-agent"
                        }
                    }

                    text_transformation {
                        priority = 0
                        type     = "LOWERCASE"
                    }
                }
              }
            statement {

                byte_match_statement {
                    positional_constraint = "CONTAINS"
                    search_string         = "CloudWatchSynthetics/arn:aws:synthetics:us-west-2:480119773629:canary:t1"

                    field_to_match {

                        single_header {
                            name = "user-agent"
                        }
                    }

                    text_transformation {
                        priority = 0
                        type     = "NONE"
                    }
                }
            }
            statement {

                byte_match_statement {
                    positional_constraint = "CONTAINS"
                    search_string         = "CloudWatchSynthetics/arn:aws:synthetics:us-west-2:480119773629:canary:admin-le-vel-com"

                    field_to_match {

                        uri_path {}
                    }

                    text_transformation {
                        priority = 0
                        type     = "NONE"
                    }
              }
            }
        }
    }

    visibility_config {
        cloudwatch_metrics_enabled = true
        metric_name                = "canary-monitoring-test"
        sampled_requests_enabled   = true
    }
  }
}

### Steps to Reproduce

terraform apply
modify rule 
terraform apply

### Would you like to implement a fix?

None

**Comment by rwrock** [comment] 2023-02-10 14:30
I'm have the same problem, when I change a simple tag for example. (Removing provider tags)

**Comment by jstarktb** [comment] 2023-02-10 17:28
Same problem here as well - changing simple tags

**Comment by rrossouw01** [comment] 2023-02-12 17:21
In the CLI I need `--cli-binary-format raw-in-base64-out`  to update a web-acl. 
 I wonder if the terraform resource need to base64 encode string matches. 
 Under ByteMatchStatement in the API doc: https://docs.aws.amazon.com/pdfs/waf/latest/APIReference/waf-apiref.pdf I see this "If you're using the AWS WAF API Specify a base64-encoded version of the value."

**Comment by rodrigobsimon** [comment] 2023-02-13 14:31
Same problem here guys, did anyone manage to solve it?

**Comment by rejiem** [comment] 2023-02-14 10:08
same problem here, any fix or workaround would be much appreciated

**Comment by NiallJude** [comment] 2023-02-21 13:34
Running into this too. Tag changes causing the longest error I have ever seen.

**Comment by ascopes** [comment] 2023-02-28 14:14
Not sure if it is related, but I am seeing the same error and same symptoms.

It appears that for me it is related to the rule overrides mechanism.

```terraform
    statement {
      managed_rule_group_statement {
        name        = "AWSManagedRulesCommonRuleSet"
        vendor_name = "AWS"
        rule_action_override {
          action_to_use {
            allow {}
          }
          name = "SizeRestrictions_BODY"
        }
      }
    }
```

The above fails with an extremely complicated error message that fills over 95,000 lines of logs (perhaps worth the dev team considering making this message easier to read in the future..?)

Changing it to this makes it work for me:

```terraform
    statement {
      managed_rule_group_statement {
        name        = "AWSManagedRulesCommonRuleSet"
        vendor_name = "AWS"
        rule_action_override {
          action_to_use {
            allow {
              custom_request_handling {
                insert_header {
                  // Workaround for Terraform breaking if this block is empty, despite the WAF schema allowing it
                  // to be optional... Ideally we'd just use an `allow {}` block with nothing in it.
                  name = "X-AWS-WAFV2-ACL-Allow"
                  value = "SizeRestrictions_BODY"
                }
              }
            }
          }
          name = "SizeRestrictions_BODY"
        }
      }
    }
```

...Followed by applying Terraform twice in a row to verify the second run passes.

This is far from ideal to be injecting garbage headers into the WAF handling to handle this. However, given the oversize handling requirement has come into action and the v4 Terraform provider is needed to configure that, this is a blocking issue for anyone who uses an automated devops pipeline without the ability to immediately exclude changes to this module.

**Comment by ascopes** [comment] 2023-03-01 16:41
Think we've come up with a workaround. Creating a rule that "does nothing" that always causes a new resource to be created on each build seems to do the trick. I've had two consecutive builds in CI pass by doing this.

```terraform
rule {
    // Hack that always includes a field change to prevent rules being updated on the fly, which
    // currently triggers https://github.com/hashicorp/terraform-provider-aws/issues/29304
    name = "WorkaroundForGH29304"
    priority = 999999999
    action {
      block {}
    }
    statement {
      label_match_statement {
        scope = "LABEL"
        key   = "PLEASE_IGNORE_ME_${uuid()}"
      }
    }
    visibility_config {
      cloudwatch_metrics_enabled = false
      metric_name                = "not-applicable"
      sampled_requests_enabled   = false
    }
  }
```

**Comment by mbsimonovic** [comment] 2023-03-06 09:04
i'm getting the same error when i add this rule (example from https://docs.aws.amazon.com/waf/latest/developerguide/waf-bot-control-example-user-agent-exception.html):

```
dynamic "rule" {
    for_each = var.allow_postman ? [true] : []
    content {
      name     = "user-agent-rule"
      priority = 11

      action {
        block {}
      }
      statement {
        and_statement {
          statement {
            label_match_statement {
              key   = "awswaf:managed:aws:bot-control:signal:non_browser_user_agent"
              scope = "LABEL"
            }
          }
          statement {
            not_statement {
              statement {
                byte_match_statement {
                  search_string = "sendgrid"
                  field_to_match {
                    single_header {
                      name = "user-agent"
                    }
                  }
                  text_transformation {
                    priority = 0
                    type     = "LOWERCASE"
                  }
                  positional_constraint = "CONTAINS"
                }
              }
            }
          }
        }
      }

      visibility_config {
        cloudwatch_metrics_enabled = true
        metric_name                = "user-agent-rule"
        sampled_requests_enabled   = true
      }
    }
  }
```
The plan looks correct:
```
      + rule {
          + name     = "user-agent-rule"
          + priority = 11

          + action {

              + block {
                }
            }

          + statement {
              + and_statement {
                  + statement {

                      + label_match_statement {
                          + key   = "awswaf:managed:aws:bot-control:signal:non_browser_user_agent"
                          + scope = "LABEL"
                        }
                    }
                  + statement {

                      + not_statement {
                          + statement {

                              + byte_match_statement {
                                  + positional_constraint = "CONTAINS_WORD"
                                  + search_string         = "postman"

                                  + field_to_match {

                                      + single_header {
                                          + name = "user-agent"
                                        }
                                    }

                                  + text_transformation {
                                      + priority = 0
                                      + type     = "LOWERCASE"
                                    }
                                }
                            }
                        }
                    }
                }
            }

          + visibility_config {
              + cloudwatch_metrics_enabled = true
              + metric_name                = "user-agent-rule"
              + sampled_requests_enabled   = true
            }
        }
```
what seems to make it fail is statement->not_statement->statement->byte_match_statement. If not_statement is replaced with a plain byte_match statement then it doesn't fail:

```
dynamic "rule" {
    for_each = var.allow_postman ? [true] : []
    content {
      name     = "user-agent-rule"
      priority = 11

      action {
        block {}
      }
      statement {
        and_statement {
          statement {
            label_match_statement {
              key   = "awswaf:managed:aws:bot-control:signal:non_browser_user_agent"
              scope = "LABEL"
            }
          }


              statement {
                byte_match_statement {
                  search_string = "sendgrid"
                  field_to_match {
                    single_header {
                      name = "user-agent"
                    }
                  }
                  text_transformation {
                    priority = 0
                    type     = "LOWERCASE"
                  }
                  positional_constraint = "CONTAINS"
                }
              }
            
          
        }
      }

      visibility_config {
        cloudwatch_metrics_enabled = true
        metric_name                = "user-agent-rule"
        sampled_requests_enabled   = true
      }
    }
  }
```

**Comment by ascopes** [comment] 2023-03-08 11:36
For now, we've had to just disable running in WAF changes to work around this. If needbe we might have to migrate stuff to CloudFormation scripts that get invoked via Terraform until this can be fixed. Probably worth being prioritised though since WAF components affect the overall security of cloud systems.

**Comment by hypsrizzari** [comment] 2023-03-09 21:12
There are several bugs opened that look related to this issue.  I was in the same boat having to taint the resource to get it to apply.  The comment in the bug resolved it for me with AWS provider 4.5x.  Hope it helps.  Kudos to the author.

https://github.com/hashicorp/terraform-provider-aws/issues/28191#issuecomment-1398853194

**Comment by nunofernandes** [comment] 2023-05-16 11:06
Hello.. Also have the same issue:

```
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.waf.module.waf.aws_wafv2_web_acl.main[0] to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .rule: planned set element
│ cty.ObjectVal(map[string]cty.Value{"action":cty.ListValEmpty(cty.Object(map[string]cty.Type{"allow":cty.List(cty.Object(map[string]cty.Type{"custom_request_handling":cty.List(cty.Object(map[string]cty.Type{"insert_header":cty.Set(cty.Object(map[string]cty.Type{"name":cty.String,
│ "value":cty.String}))}))})), "block":cty.List(cty.Object(map[string]cty.Type{"custom_response":cty.List(cty.Object(map[string]cty.Type{"custom_response_body_key":cty.String, "response_code":cty.Number,
│ "response_header":cty.Set(cty.Object(map[string]cty.Type{"name":cty.String, "value":cty.String}))}))})),
│ "captcha":cty.List(cty.Object(map[string]cty.Type{"custom_request_handling":cty.List(cty.Object(map[string]cty.Type{"insert_header":cty.Set(cty.Object(map[string]cty.Type{"name":cty.String, "value":cty.String}))}))})),
│ "challenge":cty.List(cty.Object(map[string]cty.Type{"custom_request_handling":cty.List(cty.Object(map[string]cty.Type{"insert_header":cty.Set(cty.Object(map[string]cty.Type{"name":cty.String, "value":cty.String}))}))})),
│ "count":cty.List(cty.Object(map[string]cty.Type{"custom_request_handling":cty.List(cty.Object(map[string]cty.Type{"insert_header":cty.Set(cty.Object(map[string]cty.Type{"name":cty.String, "value":cty.String}))}))}))})),
│ "captcha_config":cty.ListValEmpty(cty.Object(map[string]cty.Type{"immunity_time_property":cty.List(cty.Object(map[string]cty.Type{"immunity_time":cty.Number}))})), "name":cty.StringVal("swoogo-waf-blocklist-tor-stage"),
│ "override_action":cty.ListVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"count":cty.ListValEmpty(cty.EmptyObject), "none":cty.ListVal([]cty.Value{cty.EmptyObjectVal})})}), "priority":cty.NumberIntVal(3),
│ "rule_label":cty.SetValEmpty(cty.Object(map[string]cty.Type{"name":cty.String})),
│ "statement":cty.ListVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"and_statement":cty.ListValEmpty(cty.Object(map[string]cty.Type{"statement":cty.List(cty.Object(map[string]cty.Type{"and_statement":cty.List(cty.Object(map[string]cty.Type{"statement":cty.List(cty.Object(map[string]cty.Type{"and_statement":cty.List(cty.Object(map[string]cty.Type{"statement":cty.List(cty.Object(map[string]cty.Type{"byte_match_statement":cty.List(cty.Object(map[string]cty.Type{"field_to_match":cty.List(cty.Object(map[string]cty.Type{"all_query_arguments":cty.List(cty.EmptyObject),
....
```

Running terraform 1.3.0 with provider version 4.66.0.

The output is quite big... 
If I taint the aws_wafv2_web_acl resource, it works.

**Comment by ascopes** [comment] 2023-05-16 13:30
@nunofernandes it seems to be a bug in Terraform 1.3. I upgraded our team to use Terraform 1.4 and it magically started to work again. Bizarre.

**Comment by alexander-ruiz-mf** [comment] 2023-05-25 20:24
We have seen this on terraform 0.13.7 as well

**Comment by YakDriver** [comment] 2023-07-13 21:21
**NOTE:** I cannot reproduce this error after trying various configurations. _**Let us know**_ if this is still a problem! If we don't hear and can't reproduce, we plan to close this on or around **July 20, 2023**. The evidence suggests this is OBE (ie, fixed in the interim).

For more details see #23992 ([comment](https://github.com/hashicorp/terraform-provider-aws/issues/23992#issuecomment-1634920741)).

**Comment by justinretzolk** [comment] 2023-07-20 17:24
Hi all :wave: As was mentioned above, this issue appears to be fixed when using a minimum Terraform version of 1.4.2 and a minimum AWS Provider version of 4.67.0 (preferably Terraform 1.5.3 or later and AWS Provider 5.8.0 or later). If you experience additional unexpected behaviors with versions that meet these parameters, please open a new issue so that we can investigate further.

**Closed by justinretzolk** 2023-07-20 17:24 UTC
Labels: bug, waiting-response, service/wafv2
