### ISSUE TITLE
[ECS] Support enable-execute-command for aws_ecs_service

### ISSUE THREAD

**Issue by kamilhristov** [hashicorp/terraform-provider-aws#18122] opened 2021-03-16 13:03 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS finally released new feature that allows executing commands on ECS containers including Fargate.

### New or Affected Resource(s)

* aws_ecs_service

### Potential Terraform Configuration

```hcl
enable_execute_command = true/false
```

### References

* https://aws.amazon.com/blogs/containers/new-using-amazon-ecs-exec-access-your-containers-fargate-ec2/

**Comment by dimisjim** [comment] 2021-03-16 13:49
Duplicate of https://github.com/hashicorp/terraform-provider-aws/issues/18112

**Closed** 2021-03-16 13:59 UTC
Labels: enhancement, needs-triage, service/ecs
