### ISSUE TITLE
InvalidParameterException : aws_eks_addon

### ISSUE THREAD

**Issue by khirodpatra** [hashicorp/terraform-provider-aws#26145] opened 2022-08-05 12:14 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

AWS provider Version : * v3.75.2
Terraform Version : 1.1.9

### Affected Resource(s)

EKS
EBS-CSI-DRIVER

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_eks_addon" "ebs-csi" {
  depends_on = [aws_iam_openid_connect_provider.energyip-eks-cluster]
  cluster_name = aws_eks_cluster.eks-cluster.name
  addon_name   = "aws-ebs-csi-driver"
}
```

### Debug Output

Error: error creating EKS Add-On (eks-cluster:aws-ebs-csi-driver): InvalidParameterException: Addon version specified is not supported for the cluster platform version
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "bee03bf4-7239-42a1-acec-29c4ae659cf8"
  },
  AddonName: "aws-ebs-csi-driver",
  ClusterName: "eks-cluster",
  Message_: "Addon version specified is not supported for the cluster platform version"
}

### Expected Behavior

The above code should deploy the ebs-csi driver as per the cluster version. 
In my case the EKS cluster version is : 1.22

### Actual Behavior

Error: error creating EKS Add-On (eks-cluster:aws-ebs-csi-driver): InvalidParameterException: Addon version specified is not supported for the cluster platform version

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by khirodpatra** [comment] 2022-08-08 16:25
As per the doc "[addon_version]" is optional and I guess it should pick the latest available version in the cluster.

**Comment by mattburgess** [comment] 2022-10-25 20:58
Hi @khirodpatra - I'm unable to reproduce this using the latest version of the Terraform provider (4.36.1). When I use the following TF code, I see the addon successfully created at version `v1.11.4-eksbuild.1`:

```hcl
resource "aws_eks_addon" "ebs-csi" {
  cluster_name = aws_eks_cluster.example.name
  addon_name   = "aws-ebs-csi-driver"
}
```

**Comment by bryantbiggs** [comment] 2024-09-05 14:49
@khirodpatra is this still an issue or are we able to close this out now?

**Comment by justinretzolk** [comment] 2024-09-05 17:08
Since it looks like this hasn't been reproducible since at least version 4.36.1, I'm going to close this issue. If you encounter this issue again in more recent versions, please open a new issue so that we can triage it appropriately.

**Closed by justinretzolk** 2024-09-05 17:08 UTC
Labels: enhancement, service/eks
