### ISSUE TITLE
provider default_tags not working for root_block_device tags

### ISSUE THREAD

**Issue by pbdger** [hashicorp/terraform-provider-aws#21915] opened 2021-11-26 11:56 UTC
### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.11
on linux_arm64
+ provider registry.terraform.io/hashicorp/aws v3.66.0

### Affected Resource(s)
```
resource "aws_instance" "influxdb" {
  root_block_device {
    tags = 
      {
        foo  = "bar"
      }
  }
}


provider "aws" {
  default_tags {
    tags = {
      environment = "dev"
    }

  }
}
```

### Expected Behavior

Root-Volume of aws_instance should have tags;
```
environment   = "dev"
foo                   = "bar"
```

### Actual Behavior

Root-Volume of aws_instace has tag;
```
foo = "bar"
```

### Steps to Reproduce

1. `terraform apply`

**Comment by breathingdust** [comment] 2021-11-26 20:11
Duplicate of #19890

Thanks for the report @pbdger, I'll close this issue to keep attention focused on the original issue.

**Closed by breathingdust** 2021-11-26 20:11 UTC
Labels: service/ec2, needs-triage
