### ISSUE TITLE
Elasticache Replication Group InvalidParameterCombination: No modifications were requested

### ISSUE THREAD

**Issue by Zogoo** [hashicorp/terraform-provider-aws#16564] opened 2020-12-03 12:07 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform: 0.12.26
AWS provider: 3.19

### Affected Resource(s)

* aws_elasticache_replication_group

### Debug Output

`terraform plan` will show following output

```terraform
 # module.redis.aws_elasticache_replication_group.sidekiq will be updated in-place
  ~ resource "aws_elasticache_replication_group" "sidekiq" {
        at_rest_encryption_enabled    = false
        auto_minor_version_upgrade    = true
        automatic_failover_enabled    = true
        engine                        = "redis"
      ~ engine_version                = "6.0.5" -> "6.x"
        id                            = "****-cluster-elastic-cache"
        maintenance_window            = "sat:17:00-sat:18:00"
}
```

### Panic Output

`terraform apply` fail with following message

```
Error: error updating Elasticache Replication Group (****-cluster-elastic-cache): InvalidParameterCombination: No modifications were requested
	status code: 400, request id: b87ad43c-9781-4db8-9b2c-28fa2f182355
```

### Expected Behavior

Should apply without resource modification.

### Actual Behavior

Failing with message mentioned in "Panic Output" part.

### Steps to Reproduce

Any aws_elasticache_replication_group with REDIS 6.X version

1. `terraform apply`

### Important Factoids

It seems like Terraform state hold version number after resource applied to AWS when first time create AWS environments.
Second apply fail with because you cannot specify minor version of redis it self.

### References
` Any request with a specific version value will be rejected, an exception will be thrown and the process will fail.`
https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/supported-engine-versions.html#redis-version-6.x

**Comment by Zogoo** [comment] 2020-12-03 14:24
Currently I'm solving this issue with following way.
```terraform
lifecycle {
 ignore_changes = [engine_version]
}
```
This actually make sense since AWS team wants to manage minor versions for us. And I think no need to Terraform state hold this information anymore. If it would be solved by internal feature on Terraform that will be nice.

**Comment by DirkRusche** [comment] 2021-01-12 15:18
Duplicate to #15625?

**Comment by gurchik** [comment] 2021-04-01 20:20
Yes this looks like a duplicate of #15625

**Comment by breathingdust** [comment] 2021-09-16 16:29
Closing as this appears to be a duplicate of a resolved issue.

**Closed by breathingdust** 2021-09-16 16:29 UTC
Labels: service/elasticache
