### ISSUE TITLE
aws_route53_record can not change routing policy from simple to weighted

### ISSUE THREAD

**Issue by ekanai** [hashicorp/terraform-provider-aws#11485] opened 2020-01-06 03:52 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.18
+ provider.aws v2.43.0

### Affected Resource(s)

* aws_route53_record

### Terraform Configuration Files

```hcl
resource "aws_route53_record" "route53_com_A" {
  zone_id = aws_route53_zone.zone.id
  name    = "route53.com."
  type    = "A"

  alias {
    name                   = aws_lb.lb.dns_name
    zone_id                = aws_lb.lb.zone_id
    evaluate_target_health = "false"
  }

  weighted_routing_policy {
    weight = 100
  }

  set_identifier = "blue"
}
```

### Debug Output
```
  # aws_route53_record.route53_com_A will be updated in-place
  ~ resource "aws_route53_record" "route53_com_A" {
        allow_overwrite = true
        fqdn            = "route53.com"
        id              = "id"
        name            = "route53.com"
        records         = []
      + set_identifier  = "blue"
        ttl             = 0
        type            = "A"
        zone_id         = "id"

        alias {
            evaluate_target_health = false
            name                   = "name"
            zone_id                = "id"
        }

        weighted_routing_policy {
            weight = 100
        }
    }

```

### Panic Output

Error: [ERR]: Error building changeset: InvalidChangeBatch: [Tried to delete resource record set [name='route53.com., type A, SetIdentifier blue cannot be created as a non-weighted set exists with the same name and type.]

### Expected Behavior

record will be updated in-place from simple to weighted .

### Actual Behavior

delete and create were failed .

### Steps to Reproduce

1. change aws_route53_record resource from simple to weighted.
2. `terraform apply`

**Comment by Gujarats** [comment] 2020-01-21 04:51
We are also experience it on the Terraform previous version `0.11.14`. hopefully this version also get fixed.

**Comment by jtcressy** [comment] 2020-05-18 19:10
Also experiencing this issue. The only way for me to work around it is to delete the records and let terraform recreate them, potentially causing downtime if this process takes longer than the record's TTL. TF 0.12.21, provider version 2.61.

**Comment by DSdatsme** [comment] 2020-05-31 14:12
Can you share your simple routing policy terraform config?
Because when you are changing from simple to weighted, your plan should show that it's adding a weighted policy, that is not shown in the debug output you share.

here is the expected plan output

```terraform
  # aws_route53_record.issue-policy will be updated in-place
  ~ resource "aws_route53_record" "issue-policy" {
        fqdn           = "test.awesome.com"
        id             = "XYZXYZ_test.awesome.com_A"
        name           = "test.awesome.com"
        records        = []
      + set_identifier = "random-ip"
        ttl            = 0
        type           = "A"
        zone_id        = "XYZXYZ"

        alias {
            evaluate_target_health = false
            name                   = "foo.awesome.com"
            zone_id                = "XYZXYZ"
        }

      + weighted_routing_policy {
          + weight = 100
        }
    }
```

Previous config (simple policy):
```terraform
resource "aws_route53_record" "issue-policy" {
  name           = "test.awesome.com"
  type           = "A"
  zone_id        = aws_route53_zone.awesome_zone.zone_id
  alias {
    name                   = "foo.awesome.com."
    zone_id                = aws_route53_zone.awesome_zone.zone_id
    evaluate_target_health = "false"
  }
}
```

New config (weighted policy):
```terraform
resource "aws_route53_record" "issue-policy" {
  name           = "test.awesome.com"
  type           = "A"
  zone_id        = aws_route53_zone.awesome_zone.zone_id
  alias {
    name                   = "foo.awesome.com."
    zone_id                = aws_route53_zone.awesome_zone.zone_id
    evaluate_target_health = "false"
  }

  set_identifier = "random-ip"
  weighted_routing_policy {
      weight = 100
    }
}
```


It worked for me. Let me know if I am missing something🤔.
Terraform version: 0.12.19
AWS provider version: 2.49

**Comment by jtcressy** [comment] 2020-06-01 17:59
I know this was not covered in the OP, but are you able to change from `weighted_routing_policy` to `failover_routing_policy` and vice-versa? Making this change in my own code triggers this scenario. (tf version 0.12.24, aws provider 2.60)

**Comment by franksunjin** [comment] 2020-11-25 17:02
Have the same experience. Interesting that I can update the record in console from Simple to Weighted, but not using API. Wonder how is that possible since console should be just a wrapper for API.

**Comment by milo-chai-epic** [comment] 2021-11-15 06:56
> Can you share your simple routing policy terraform config? Because when you are changing from simple to weighted, your plan should show that it's adding a weighted policy, that is not shown in the debug output you share.
> 
> here is the expected plan output
> 
> ```terraform
>   # aws_route53_record.issue-policy will be updated in-place
>   ~ resource "aws_route53_record" "issue-policy" {
>         fqdn           = "test.awesome.com"
>         id             = "XYZXYZ_test.awesome.com_A"
>         name           = "test.awesome.com"
>         records        = []
>       + set_identifier = "random-ip"
>         ttl            = 0
>         type           = "A"
>         zone_id        = "XYZXYZ"
> 
>         alias {
>             evaluate_target_health = false
>             name                   = "foo.awesome.com"
>             zone_id                = "XYZXYZ"
>         }
> 
>       + weighted_routing_policy {
>           + weight = 100
>         }
>     }
> ```
> 
> Previous config (simple policy):
> 
> ```terraform
> resource "aws_route53_record" "issue-policy" {
>   name           = "test.awesome.com"
>   type           = "A"
>   zone_id        = aws_route53_zone.awesome_zone.zone_id
>   alias {
>     name                   = "foo.awesome.com."
>     zone_id                = aws_route53_zone.awesome_zone.zone_id
>     evaluate_target_health = "false"
>   }
> }
> ```
> 
> New config (weighted policy):
> 
> ```terraform
> resource "aws_route53_record" "issue-policy" {
>   name           = "test.awesome.com"
>   type           = "A"
>   zone_id        = aws_route53_zone.awesome_zone.zone_id
>   alias {
>     name                   = "foo.awesome.com."
>     zone_id                = aws_route53_zone.awesome_zone.zone_id
>     evaluate_target_health = "false"
>   }
> 
>   set_identifier = "random-ip"
>   weighted_routing_policy {
>       weight = 100
>     }
> }
> ```
> 
> It worked for me. Let me know if I am missing something🤔. Terraform version: 0.12.19 AWS provider version: 2.49

Hi buddy~ Do you apply this change?  I test with your TF version and the AWS provider version still meets this error.

**Comment by justinretzolk** [comment] 2021-11-18 22:37
Hey y'all 👋 Thank you for taking the time to file this issue and for the discussion around it! Given that there's been a number of AWS provider releases since the last update, can anyone confirm whether you're still experiencing this behavior?

**Comment by OrdinaryFan** [comment] 2021-11-26 02:41
Encountered the same problem, terraform version 0.12.2, AWS provider version 2.14. The strange thing is that two route53 record changes were made, one failure and one success. I compared two state files. The `allow_overwrite` corresponding to the failure is true, and the success is null, but the configuration item is not explicitly configured in the configuration file. Not sure if this is the cause of the error.

**Comment by OrdinaryFan** [comment] 2021-11-26 05:04
yes, the reason should be `allow_overwrite`, I update this config to false, then do the terraform apply, it will be fine. It seems that a previous version of the resource set the value to true by default.

**Comment by benreynolds-drizly** [comment] 2022-12-29 17:39
I just encountered this error using terraform `v1.3.0` and AWS provider `4.48.0`. I'm attempting to create a record set using the following resource within a module which is invoked two times. One of the records creates as expected and the second fails with `Tried to create resource record set [...] but it already exists`

```
resource "aws_route53_record" "balanced" {
  zone_id         = local.r53_zone_id
  name            = "root.${local.r53_zone_name}"
  type            = "A"
  health_check_id = aws_route53_health_check.cluster_aggregate.id

  alias {
    name                   = aws_lb.this.dns_name
    zone_id                = aws_lb.this.zone_id
    evaluate_target_health = true
  }

  set_identifier  = local.public_dns
  weighted_routing_policy {
    weight = local.weight
  }
}
```

**Comment by justinretzolk** [comment] 2023-01-04 17:26
Hey @benreynolds-drizly 👋 It looks like you may be hitting a slightly different error than was initially reported here. You'll likely be better served opening a fresh issue so that we can take a look into that.

Based on the previous replies, it appears that this may have come down to the `allow_overwrite` argument changing its default value at some point. That particular argument is [computed](https://github.com/hashicorp/terraform-provider-aws/blob/037b56194ce54c93113e046ff44b278ce3513f98/internal/service/route53/record.go#L238), so it's hard for me to say when this may have changed. Given the circumstances, I'm going to close this issue, as it seems to have been resolved. If you experience this issue in the future, please open a fresh issue so that we can take another look.

**Closed by justinretzolk** 2023-01-04 17:26 UTC
Labels: service/route53
