### ISSUE TITLE
AWS SSO - Support for Customer managed IAM policies with permission sets

### ISSUE THREAD

**Issue by henilshah1** [hashicorp/terraform-provider-aws#26068] opened 2022-08-01 14:00 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon released new feature for SSO that allows customer managed keys to be assigned to permission sets to provide fine grained access. 
https://aws.amazon.com/about-aws/whats-new/2022/07/aws-single-sign-on-aws-sso-aws-identity-access-management-iam-customer-managed-policies-cmps/

### New or Affected Resource(s)
This feature will require new resource block to support adding custom customer managed policies to permission set..

### References
https://aws.amazon.com/about-aws/whats-new/2022/07/aws-single-sign-on-aws-sso-aws-identity-access-management-iam-customer-managed-policies-cmps/

**Comment by bschaatsbergen** [comment] 2022-08-01 20:21
Hi @henilshah1, thanks for raising this. I'll take a look at it.

**Comment by paulschwarzenberger** [comment] 2022-08-10 08:00
this looks to me like a duplicate of https://github.com/hashicorp/terraform-provider-aws/issues/25904

**Closed** 2022-09-08 13:52 UTC
Labels: enhancement, service/sso
