### ISSUE TITLE
[Enhancement]: Support CodePipeline v2

### ISSUE THREAD

**Issue by shblue21** [hashicorp/terraform-provider-aws#34838] opened 2023-12-09 10:35 UTC
### Description

In late October, AWS CodePipeline v2 was released.
It has the same structure as V1, and the SDK is also distributed.

I'm working on it and hope to open a PR and ask for reviews soon.

### Affected Resource(s) and/or Data Source(s)

aws_codepipeline

### Potential Terraform Configuration

```terraform
resource "aws_codepipeline" "codepipeline" {
  name     = "tf-test-pipeline"
 ...
pipelineType = "V2"
...
}
```

### References

- https://aws.amazon.com/about-aws/whats-new/2023/10/aws-codepipeline-parameterized-pipelines/?nc1=h_ls
- https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/codepipeline@v1.22.5/types#PipelineType

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment] 2023-12-12 21:09
Duplicate of #34122

**Closed by justinretzolk** 2023-12-12 21:09 UTC
Labels: enhancement, service/codepipeline, needs-triage

**Comment by shblue21** [comment] 2023-12-16 04:10
ok I'll drop it
