### ISSUE TITLE
[Bug]: aws_launch_template.block_device_mapping.ebs.kms_key_id is not accept arn now

### ISSUE THREAD

**Issue by cn00** [hashicorp/terraform-provider-aws#38633] opened 2024-08-01 02:28 UTC
### Terraform Core Version

1.9.x

### AWS Provider Version

5.50+

### Affected Resource(s)

* aws_instance
* aws_ebs_volume
* aws_launch_template
* aws_kms_key

### Expected Behavior

success launching a new EC2 instance 

### Actual Behavior

aws_launch_template.block_device_mapping.ebs.kms_key_id is not accept arn now, maybe this is due to the recent updates of aws 

### Relevant Error/Panic Output Snippet

```log
Launching a new EC2 instance: i-03781f2dd0af0684e. Status Reason: Instance became unhealthy while waiting for instance to be in InService state. Termination Reason: Client.InvalidKMSKey.InvalidState: The KMS key provided is in an incorrect state
```

### Terraform Configuration Files

```tf
# Define a kms resource
resource "aws_kms_key" "ebs" {}
# Define launch template
resource "aws_launch_template" "app_1" {
  image_id = data.aws_ami.ubuntu.id
  instance_type = "t2.micro"
  block_device_mappings {
    device_name = "/dev/sda1"
    ebs {
      volume_size = 10
      volume_type = "gp2"

      # terrafrom plan Error: "block_device_mappings.0.ebs.0.kms_key_id" \
      #(60ce0cae-a6be-4ac5-ab4e-135cc2636db6) is an invalid ARN: arn: invalid prefix
      kms_key_id = aws_kms_key.ebs.key_id 

      # terrafrom plan&apply ok,but launching instance failed: \
      # Launching a new EC2 instance: i-03781f2dd0af0684e. \
      # Status Reason: Instance became unhealthy while \
      # waiting for instance to be in InService state. \
      # Termination Reason: Client.InvalidKMSKey.InvalidState: \
      # The KMS key provided is in an incorrect state
      kms_key_id = aws_kms_key.ebs.arn 
    }
  }
}
```

### Steps to Reproduce

```shell
terraform plan
```

### Panic Output

```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: "block_device_mappings.0.ebs.0.kms_key_id" (60ce0cae-a6be-4ac5-ab4e-135cc2636db6) is an invalid ARN: arn: invalid prefix
│ 
│   with module.main.aws_launch_template.default,
│   on ../../main/ec2.tf line 73, in resource "aws_launch_template" "default":
│   73:       kms_key_id = aws_kms_key.ebs.id
│ 
╵
make: *** [plan] Error 1
```

### References

- [launch_template](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#kms_key_id)

### Would you like to implement a fix?

Yes

**Comment by justinretzolk** [comment] 2024-08-27 21:18
Hey @cn00 👋 Thank you for taking the time to raise this! While the argument that you're setting within the `aws_launch_template` argument is called `kms_key_id`, an ARN is expected here (note: the naming of this matches the [underlying API](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_LaunchTemplateEbsBlockDeviceRequest.html)). With that in mind, using `aws_kms_key.ebs.arn` as the value for that argument is the correct solution.

As far as the error that you received when using that value, the key detail is here:

```console
      # Termination Reason: Client.InvalidKMSKey.InvalidState:
      # The KMS key provided is in an incorrect state
```

I found what seems to be a fairly helpful post in [AWS' forums](https://repost.aws/questions/QUZ45_zICASs-KJ6ByEpvChA/auto-scaling-group-in-eks-with-encrypted-ebs-volumes). Ultimately the error message points to an issue with the state of the KMS key (in all likelihood a configuration issue), rather than the `aws_launch_template` resource itself. With that in mind, I'm going to close this issue. If you experience unexpected behavior with the provider in the future, please do let us know!

**Closed by justinretzolk** 2024-08-27 21:18 UTC
Labels: bug, service/ec2, service/kms, needs-triage, service/ebs, service/ec2ebs
