### ISSUE TITLE
Cannot use provider v2.70.1 with Terraform v0.12.24

### ISSUE THREAD

**Issue by dbcelm** [hashicorp/terraform-provider-aws#22565] opened 2022-01-13 07:22 UTC
Hi Team,

My existing setup is using AWS provider v2.70.0 along with Terraform v0.12.24, recently we got notified by AWS regarding Lambda state related changes and that made us to update our provider to v2.70.1, but for some reason even after updating provider version to 2.70.1, terraform still uses v2.70.0 and always pulls that. Is there any minimum Terraform version requirement to use AWS Provider version 2.70.1?

**Comment by justinretzolk** [comment] 2022-01-13 22:57
Hey @dbcelm 👋 Thank you for taking the time to file this issue. So that we have all of the information that we need in order to look into this, can you provide the rest of the information requested in the [bug template](https://github.com/hashicorp/terraform-provider-aws/blob/main/.github/ISSUE_TEMPLATE/Bug_Report.md)?

As far as I'm aware, there shouldn't be a minimum version of Terraform in order to use `v2.70.1`, but I'll try to double check that in the meantime in case I'm not recalling something. One thing that you might try would be to run `terraform providers` in the root of the configuration directory to see if perhaps there's a version constraint somewhere in the configuration that's causing `v2.70.0` to be pulled in rather than `v2.70.1`.

**Comment by udh-mendix** [comment] 2022-01-14 09:21
I have a similar issue. Our config defines `version = "<3.0"` for aws provider but it's picking up `2.70.0` and not `2.70.1`. I also tried explicitly setting the version to `2.70.1` but that causes the plan to fail with ```Error: provider.aws: no suitable version installed
  version requirements: "2.70.1"
  versions installed: none```

**Comment by justinretzolk** [comment] 2022-01-15 00:00
Hey @udh-mendix -- thank you for the update. Can you confirm what version of Terraform you're using, and I'll dig into this a bit more?

**Comment by udh-mendix** [comment] 2022-01-17 11:01
Hi @justinretzolk , I'm using Terraform `12.9`

**Comment by justinretzolk** [comment] 2022-01-22 00:02
Hi @udh-mendix and @dbcelm 👋 I've done a bit of testing and confirmed that if you're using Terraform `0.12`, you'll need to use Terraform `0.12.31` in order to use AWS provider version `2.70.1`. I'm talking to the team to confirm my suspicions, but I suspect this is due to `2.70.1` being signed with the updated GPG key after the [codecov incident](https://discuss.hashicorp.com/t/terraform-updates-for-hcsec-2021-12/23570), as this was the only release in the `2.x.x`  series to occur after the key was rotated.

**Comment by justinretzolk** [comment] 2022-01-24 19:44
Hi all, I wanted to follow up on my previous comment now that I've had the chance to confirm with the team. My assumption that this had to do with the new GPG key has been confirmed. I'll wait to hear back before closing this out so that I can be certain y'all feel the question has been answered.

**Comment by udh-mendix** [comment] 2022-01-28 12:13
Hi @justinretzolk , I can confirm that I'm able to use AWS provider version `2.70.1` with Terraform `0.12.31`. Thanks for your help!

**Closed** 2022-01-28 17:02 UTC
Labels: provider
