### ISSUE TITLE
[Bug]: aws_imagebuilder_image_recipe cannot be deleted due to resource dependency

### ISSUE THREAD

**Issue by phr3nzii** [hashicorp/terraform-provider-aws#40128] opened 2024-11-14 11:58 UTC
### Terraform Core Version

1.9.8

### AWS Provider Version

5.74.0, 5.75.1

### Affected Resource(s)

aws_imagebuilder_image_pipeline
aws_imagebuilder_image_recipe
aws_imagebuilder_component

### Expected Behavior

When updating the `data` property of an `aws_imagebuilder_component` resource, any associated `aws_imagebuilder_image_recipe` needs to be replaced, and then any associated `aws_imagebuilder_image_pipeline` should also be replaced.

This is how things behaved up until 5.74.0

### Actual Behavior

Terraform attempts to delete the `aws_imagebuilder_image_recipe` resource before it updates the associated `aws_imagebuilder_component` resource. However, it is unable to do so as the Image Builder Pipeline depends on it, so AWS returns an error:
> ResourceDependencyException: Resource dependency error: The resource ARN 'arn:aws:imagebuilder:us-east-1:123456789012:image-recipe/recipe-name/1.0.0' has other resources depended on it.

### Relevant Error/Panic Output Snippet

```shell
ResourceDependencyException: Resource dependency error: The resource ARN 'arn:aws:imagebuilder:us-east-1:123456789012:image-recipe/recipe-name/1.0.0' has other resources depended on it.
```

### Terraform Configuration Files

resource "aws_iam_role" "example" {
  name               = "example"
  assume_role_policy = data.aws_iam_policy_document.example.json
}

resource "aws_iam_instance_profile" "example" {
  name = "example"
  role = aws_iam_role.example.name
}

resource "aws_imagebuilder_infrastructure_configuration" "example" {
  name                          = "example"
  instance_profile_name         = aws_iam_instance_profile.example.name
  terminate_instance_on_failure = true
}

resource "aws_imagebuilder_component" "example" {
  data = yamlencode(
    {
      phases = [
        {
          name = "build"
          steps = [
            {
              action = "ExecuteBash"
              inputs = {
                commands = [
                  "echo Hello"
                ]
              }
              name      = "echo"
              onFailure = "Abort"
            },
          ]
        }
      ]
      schemaVersion = 1.0
    }
  )
  name     = "echo"
  platform = "Linux"
  version  = "1.0.0"
}

resource "aws_imagebuilder_image_recipe" "example" {
  name         = "example"
  parent_image = "arn:aws:imagebuilder:us-east-1:aws:image/amazon-linux-2023-arm64/2024.7.19/1"
  version      = "1.0.0"

  component {
    component_arn = aws_imagebuilder_component.example.arn
  }
}

resource "aws_imagebuilder_image_pipeline" "example" {
  name                             = "example"
  image_recipe_arn                 = aws_imagebuilder_image_recipe.example.arn
  infrastructure_configuration_arn = aws_imagebuilder_infrastructure_configuration.example.arn
  distribution_configuration_arn   = aws_imagebuilder_distribution_configuration.example.arn
}

### Steps to Reproduce

- Apply the example config
- Change the `data` of the `aws_imagebuilder_component.example` resource, e.g. change the `echo` command
- Attempt to apply the new configuration, where the pipeline will be updated in place. You will receive the error
- Downgrade to version 5.73.0 of the AWS provider
- Apply again now and the changes will be successfully applied

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-11-14 19:56
Hey @phr3nzii 👋 Thank you for taking the time to raise this! It looks like this is a duplicate of another issue that we received a report on a couple of weeks ago (#39985) which has comments suggesting how to resolve this. With that in mind, I'm going to close this issue as a duplicate of #39985. If you experience any other unexpected behavior, please do let us know!

**Comment by justinretzolk** [comment] 2024-11-14 19:56
Duplicate of #39985

**Closed by justinretzolk** 2024-11-14 19:56 UTC
Labels: bug, service/iam, needs-triage, service/imagebuilder
