### ISSUE TITLE
[Bug]:  Provider "registry.terraform.io/hashicorp/aws" requires explicit configuration. 

### ISSUE THREAD

**Issue by shalomb** [hashicorp/terraform-provider-aws#38890] opened 2024-08-15 20:28 UTC
### Terraform Core Version

1.7.x 

### AWS Provider Version

5.61.0

### Affected Resource(s)

Provider configuration

### Expected Behavior

With the use of the `hashicorp/aws` provider that has no default provider configuration i.e. using multiple [aliased configurations](https://developer.hashicorp.com/terraform/language/providers/configuration#alias-multiple-provider-configurations) for a multi-region deployment with all resources being explicitly provided [alternate provider configuration](https://developer.hashicorp.com/terraform/language/providers/configuration#selecting-alternate-provider-configurations) - terraform has been able to use our configuration without issue up until `5.61` of the `aws` provider.

### Actual Behavior

Inside terraform enterprise (TFE), terraform performs a plan but just shows this error.

![image](https://github.com/user-attachments/assets/48788e25-836d-48ee-a17f-5e9a24da1d54)

The error message isn't clear what the source is and the line numbering isn't helpful (and seems strange).

On closer inspection, you see terraform is actually able to generate a full plan _but_ then fails afterwards with the `Provider "registry.terraform.io/hashicorp/aws" requires explicit configuration` error below (presumably in doing something that is not explicit/that I require).

### Relevant Error/Panic Output Snippet

```hcl
│ Error: Invalid provider configuration
│
│ Provider "registry.terraform.io/hashicorp/aws" requires explicit
│ configuration. Add a provider block to the root module and configure the
│ provider's required arguments as described in the provider documentation.
│
╵
╷
│ Error: No valid credential sources found
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on <empty> line 0:
│   (source code not available)
│
│ Please see https://registry.terraform.io/providers/hashicorp/aws
│ for more information about providing credentials.
│
│ Error: failed to refresh cached credentials, no EC2 IMDS role found,
│ operation error ec2imds: GetMetadata, request canceled, context deadline
│ exceeded
```

### Terraform Configuration Files

i.e.
```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.59.0"
    }
  }
}

provider "aws" {
  region     = "eu-central-1"
  alias      = "eu-central-1"
  access_key = data.vault_aws_access_credentials.creds.access_key
  secret_key = data.vault_aws_access_credentials.creds.secret_key
  token      = data.vault_aws_access_credentials.creds.security_token
}

provider "aws" {
  region     = "us-east-1"
  alias      = "us-east-1"
  ...
}

module "cloudfront" {
  source    = "terraform-aws-modules/cloudfront/aws"
  version   = "3.4.0"
  providers = { aws = aws.us-east-1 }   # <--- non-default provider

  ...
}

resource "aws_cloudfront_origin_access_control" "oac" {
  provider = aws.us-east-1              # <--- non-default provider

}
```

### Steps to Reproduce

Change 

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "5.59.0"
    }
  }
}
```

to 

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.60"        # <--- seems to be the version introducing the break
    }
  }
}
```

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-08-20 18:47
Hey @shalomb 👋 Thank you for taking the time to raise this! I attempted to reproduce this (albeit, locally, rather than in a Terraform Enterprise instance), but wasn't able to. I'll outline my reproduction below.

### File Structure and Configuration

Here's how the reproduction was structured, for reference.

```console
$ tree .
.
├── main.tf
├── module
│   └── main.tf
└── terraform.tfvars
```

Complete configuration files are within these disclosure trianges.

<details>
<summary>
./main.tf

</summary>

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.59.0"
    }
  }
}

variable "access_key" {}
variable "secret_key" {}
variable "token" {}

provider "aws" {
  alias      = "usw1"
  region     = "us-west-1"
  access_key = var.access_key
  secret_key = var.secret_key
  token      = var.token
}

data "aws_region" "with-alias" {
  provider = aws.usw1
}

module "test" {
  source = "./module"
  providers = {
    aws = aws.usw1
  }
}

output "root-region" {
  value = data.aws_region.with-alias.name
}

output "module-region" {
  value = module.test.region
}

```
</details>

<details>
<summary>
./module/main.tf

</summary>

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

data "aws_region" "current" {}

output "region" {
  value = data.aws_region.current.name
}
```
</details>

### Reproduction

Note that in the environment I'm testing in, there are no AWS-related configuration files, environment variables, etc. that would automatically authenticate the AWS Provider. This means that authentication **must** be provided explicitly in the configuration. Values were set in the `terraform.tfvars` file.

Initial apply, using the version you mentioned was working:

```console
$ terraform --version
Terraform v1.9.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.59.0

$ terraform apply --auto-approve
...omitted for brevity...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

module-region = "us-west-1"
root-region = "us-west-1"
```

In `./main.tf`, `terraform.required_providers.aws.version` was then updated to `~> 5.0` and the test attempted again. For good measure, I then deleted the state and tested with the newer version without an existing state, with the same result.

```console
$ terraform --version
Terraform v1.9.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.63.1

$ terraform apply --auto-approve
...omitted for brevity...

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

module-region = "us-west-1"
root-region = "us-west-1"
```

To test a theory, I added a resource that doesn't explicitly have a `provider` argument defined:

```hcl
data "aws_region" "without-alias" {}
```

I'm then able to reproduce the issue you described; even in version 5.59.0:

```console
$ terraform --version
Terraform v1.9.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.59.0

$ terraform apply --auto-approve
module.test.data.aws_region.current: Reading...
data.aws_region.with-alias: Reading...
data.aws_region.with-alias: Read complete after 0s [id=us-west-1]
module.test.data.aws_region.current: Read complete after 0s [id=us-west-1]

Changes to Outputs:
  + module-region = "us-west-1"
  + root-region   = "us-west-1"

You can apply this plan to save these new output values to the Terraform state, without changing any real infrastructure.
╷
│ Error: Invalid provider configuration
│
│ Provider "registry.terraform.io/hashicorp/aws" requires explicit configuration. Add a provider block to the root module and configure the provider's required arguments as described
│ in the provider documentation.
│
╵
╷
│ Error: No valid credential sources found
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on <empty> line 0:
│   (source code not available)
│
│ Please see https://registry.terraform.io/providers/hashicorp/aws
│ for more information about providing credentials.
│
│ Error: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, request canceled, context deadline exceeded
│
╵
```

This is the behavior I would expect, and falls in line with what's documented in [Default Provider Configurations](https://developer.hashicorp.com/terraform/language/providers/configuration#default-provider-configurations). One thing of note is that while the output does appear to show the plan phase succeeding, the error is output at the end of the plan phase. This lines up with (and I can only assume is the cause of) the same behavior in Terraform Enterprise.

If you're not explicitly configuring the default provider in the configuration, it may have been that something else changed around the same time as you upgraded the version of the AWS Provider. Perhaps credentials were previously set at the Terraform Enterprise workspace level, and those have since been removed; it's hard to say for certain without additional logging. Based on the information above, however, this will need to be solved by a configuration change rather than a change within the AWS Provider. With that in mind, I'm going to close this issue.

**Closed by justinretzolk** 2024-08-20 18:47 UTC
Labels: bug, service/cloudfront, needs-triage
