### ISSUE TITLE
[Bug]: Not able to create two AWS resourcegroups in us-east-1 region

### ISSUE THREAD

**Issue by ashutosh-gupta-ext** [hashicorp/terraform-provider-aws#34808] opened 2023-12-08 12:13 UTC
### Terraform Core Version

Terraform v1.3.5

### AWS Provider Version

version = "~> 4.5"

### Expected Behavior

Terraform should be able to create 2 resource groups with different names in us-east-1.
idh-global-p-cpl-resourcegroup_global
idh-global-p-cpl-resourcegroup

### Actual Behavior

Terraform is failing to create 2 aws resource groups with different names in us-east-1. Terraform is able to do same thing in other region.

### Relevant Error/Panic Output Snippet

```shell
│ Error: creating Resource Groups Group (idh-global-p-cpl-resourcegroup_global): BadRequestException: Cannot create group: group already exists
│ 
│   with module.resource-group-us-east-1.aws_resourcegroups_group.resource-group["resourcegroup_global"],
│   on ../../../modules/idh/resourcegroup/resourceview.tf line 2, in resource "aws_resourcegroups_group" "resource-group":
│    2: resource "aws_resourcegroups_group" "resource-group" {
│
```

### Terraform Configuration Files

...

### Steps to Reproduce

module "resource-group-us-east-1" {
  source = "../../../modules/idh/resourcegroup"

  idh_instance              = local.idh_instance
  idh_tenant                = local.idh_tenant
  service_names           = ["resourcegroup-global", "resourcegroup"] 
  
  providers = {
        aws = aws.us-east-1
  }                          
}

variable "service_names" {
  type        = list(string)
}

resource "aws_resourcegroups_group" "resource-group" {
  for_each = toset( var.service_names )
  name    = "idh-${var.idh_instance}-${var.idh_tenant}-${each.key}"

  resource_query {
    type = "TAG_FILTERS_1_0"
    query = jsonencode(
{
  "ResourceTypeFilters": [
    "AWS::AllSupported"
  ],
  "TagFilters": [
    {
      "Key": "idhub-resource"
    }
  ]
}
    )
  }
}

### Debug Output

...

### Would you like to implement a fix?

None

**Comment by ashutosh-gupta-ext** [comment] 2023-12-11 08:34
Same code is working in other regions but not in us-east-1 region

**Comment by acwwat** [comment] 2024-01-13 09:11
I am not able to reproduce the problem with a simplified test case below using Terraform 1.6.6 and AWS Provider 5.31.0. The other possible cause is that you have the resource group created outside of Terraform in your account in us-east-1. I would recommend double checking that in AWS Management Console.

```tf
resource "aws_resourcegroups_group" "resource-group" {
	name = "idh-global-p-cpl-resourcegroup"
	resource_query {
		type = "TAG_FILTERS_1_0"
		query = jsonencode({
			"ResourceTypeFilters": [
				"AWS::AllSupported"
			],
			"TagFilters": [
				{
					"Key": "idhub-resource"
				}
			]
		})
	}
}

resource "aws_resourcegroups_group" "resource-group-global" {
	name = "idh-global-p-cpl-resourcegroup_global"
	resource_query {
		type = "TAG_FILTERS_1_0"
		query = jsonencode({
			"ResourceTypeFilters": [
				"AWS::AllSupported"
			],
			"TagFilters": [
				{
					"Key": "idhub-resource"
				}
			]
		})
	}
}
```

```tf
C:\working\test>terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  + create

Terraform will perform the following actions:

  # aws_resourcegroups_group.resource-group will be created
  + resource "aws_resourcegroups_group" "resource-group" {
      + arn      = (known after apply)
      + id       = (known after apply)
      + name     = "idh-global-p-cpl-resourcegroup"
      + tags_all = (known after apply)

      + resource_query {
          + query = jsonencode(
                {
                  + ResourceTypeFilters = [
                      + "AWS::AllSupported",
                    ]
                  + TagFilters          = [
                      + {
                          + Key = "idhub-resource"
                        },
                    ]
                }
            )
          + type  = "TAG_FILTERS_1_0"
        }
    }

  # aws_resourcegroups_group.resource-group-global will be created
  + resource "aws_resourcegroups_group" "resource-group-global" {
      + arn      = (known after apply)
      + id       = (known after apply)
      + name     = "idh-global-p-cpl-resourcegroup_global"
      + tags_all = (known after apply)

      + resource_query {
          + query = jsonencode(
                {
                  + ResourceTypeFilters = [
                      + "AWS::AllSupported",
                    ]
                  + TagFilters          = [
                      + {
                          + Key = "idhub-resource"
                        },
                    ]
                }
            )
          + type  = "TAG_FILTERS_1_0"
        }
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_resourcegroups_group.resource-group: Creating...
aws_resourcegroups_group.resource-group-global: Creating...
aws_resourcegroups_group.resource-group-global: Creation complete after 1s [id=idh-global-p-cpl-resourcegroup_global]
aws_resourcegroups_group.resource-group: Creation complete after 1s [id=idh-global-p-cpl-resourcegroup]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
```

**Comment by gdavison** [comment] 2024-02-13 19:57
Hi @ashutosh-gupta-ext, the error message says that the Resource Group `resourcegroup_global` already exists

> Cannot create group: group already exists

As @acwwat suggests, have you checked in the AWS Console to see if it already present? If so, you could import that resource

**Comment by justinretzolk** [comment] 2024-03-19 21:43
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.

**Closed by justinretzolk** 2024-03-19 21:43 UTC
Labels: bug, waiting-response, service/resourcegroups
