### ISSUE TITLE
[Bug]: Terraform removes existing event notification on a bucket to create a new one

### ISSUE THREAD

**Issue by saijal** [hashicorp/terraform-provider-aws#28945] opened 2023-01-18 07:37 UTC
### Terraform Core Version

0.13

### AWS Provider Version

3.28.0

### Affected Resource(s)

AWS s3 event notification. 

### Expected Behavior

Should a new event notification

### Actual Behavior

Deletes the existing event notification and creates the new one

### Terraform Configuration Files

terraform {
  backend "s3" {
    bucket  = ***
    key     = ***
    region  = ***

  }

  required_version = "0.13.0"
}

provider "aws" {
  version = "~> 3.28.0"
  region  = var.region
}

variable "region" {
  default = ***
}

### Steps to Reproduce

1. Add the following to .tf file 
```
resource "aws_s3_bucket_notification" "prod-bucket-notification" {
  bucket   = "bucket-name"

  queue {
    queue_arn     = "queue-arn"
    events        = ["s3:ObjectCreated:*"]
    filter_prefix = "input/"
    filter_suffix = ".csv"
  }
}
```
2. tf plan
3. tf apply 
4. Add a new event notification resource on the same bucket to same .tf file 

```
resource "aws_s3_bucket_notification" "prod-bucket-notification-new" {
  bucket   = "bucket-name"

  queue {
    queue_arn     = "queue-arn"
    events        = ["s3:ObjectCreated:*"]
    filter_prefix = "input/"
    filter_suffix = ".txt"
  }
}
```
5. tf plan 
6. tf apply

### Debug Output

Plan: 1 to add, 0 to change, 0 to destroy.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2023-01-18 16:31
Hey @saijal 👋 Thank you for taking the time to raise this! In this case, this is expected behavior that is called out on the documentation page for the [`aws_s3_bucket_notification` resource](https://registry.terraform.io/providers/hashicorp/aws/3.28.0/docs/resources/s3_bucket_notification):

> S3 Buckets only support a single notification configuration. **Declaring multiple `aws_s3_bucket_notification` resources to the same S3 Bucket will cause a perpetual difference in configuration.** See the example "Trigger multiple Lambda functions" for an option.

As mentioned in the note, there is an option for getting around this found in the [Trigger multiple Lambda functions](https://registry.terraform.io/providers/hashicorp/aws/3.28.0/docs/resources/s3_bucket_notification#trigger-multiple-lambda-functions) example configuration.

Since this is expected behavior, I'll close this issue out. If you feel I've done this in error, please do let me know.

**Closed by justinretzolk** 2023-01-18 16:31 UTC
Labels: bug, service/s3, needs-triage
