### ISSUE TITLE
No Certificate found for this domain issue

### ISSUE THREAD

**Issue by madhavidhurve** [hashicorp/terraform-provider-aws#15759] opened 2020-10-21 11:52 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform Version
0.12.29
Terraform Provider version
 2.70.0

### Affected Resource(s)

aws_acm_certificate_validation

### Terraform Configuration Files

resource "aws_acm_certificate" "cert" {
    domain_name = "example123.com"
    validation_method = "DNS"
    tags = {
      Name = "certificate_01"
    }
}
data "aws_acm_certificate" "domain_cert" {
    domain = "example123.com"
    types = ["AMAZON_ISSUED"]
    statuses = ["PENDING_VALIDATION"]
}
resource "aws_acm_certificate_validation" "cert_validation" {
  certificate_arn = data.aws_acm_certificate.domain_cert.arn
}
### Expected Behavior

DataSource should return arn value for certificate_arn parameter

### Actual Behavior

Error: No certificate for domain "example123.com" found in this region

### Steps to Reproduce

1. Create the certificate using aws_acm_certificate resource.
2. Once the certificate is created, it will be in **PENDING_VALIDATION** state, now perform terraform plan/apply using 
    aws_acm_certificate_validation resource.

**Comment by anGie44** [comment] 2020-10-22 06:24
Hi @madhavidhurve, thank you for raising this issue! in following the `Steps to Reproduce`, it seems the `aws_acm_certificate_validation` resource will fail on creation if the CNAME is not added to your DNS configuration (ref: https://aws.amazon.com/premiumsupport/knowledge-center/acm-certificate-pending-validation/). are you by chance also configuring this in terraform via the `aws_route53_record` resource?

**Comment by madhavidhurve** [comment] 2020-10-22 07:18
Hi @anGie44, thank you for your reply. On the basis of our understanding, aws_acm_certificate_validation resource adds the
CNAME record to Route53 hosted zone and once the CNAME record is added the status changes from PENDING_VALIDATION
to ISSUED. 
Earlier we had tested this scenario with two domains, wherein we created the certificate and its state was PENDING_VALIDATION 
and later after that we executed the aws_acm_certificate_validation resource which added the CNAME record of both the domains to Route53 hosted zone and changed its state from PENDING_VALIDATION to ISSUED.
This scenario worked only once and next day when we again created new certificate having PENDING_VALIDATION state
and executed the aws_acm_certificate_validation resource at that time only one domain got validated and the other
domain showed message as "No certificate found for this domain" issue.
Now, its not validating for both the domains and it keeps on raising this error.

**Comment by madhavidhurve** [comment] 2020-10-30 15:48
Hi Team,
  Could you please provide your inputs on the issue we have raised, so that we can proceed with the implementation.
Please let us know if we need to incorporate any additional thing to the existing workflow to achieve expected result.

**Comment by anGie44** [comment] 2020-10-30 20:46
Hi @madhavidhurve 👋 in the scenario you've presented: 
(1) terraform plan/apply `aws_acm_certificate`resource
(2) terraform plan/apply `aws_acm_certificate_validation` resource
This will not work given the `aws_acm_certificate` resource returns from creation when it reaches the `PENDING_VALIDATION` status, and thus the `aws_acm_certificate` data-source will not achieve the expected result of reading the ACM cert, unless you're manually taking the validation records and creating them in your DNS system before the timeout completes. 

With this being said, I recommend having a look at these examples to get the acm certificate data-source to work as expected if indeed needed in your workflow (since once the `aws_acm_certificate` resource is created, the `arn` can be used from it directly to feed other places, like `aws_route53_record` resources, etc.):
* an end-to-end configuration example in the AWS Provider: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate_validation
* or this popular module https://registry.terraform.io/modules/terraform-aws-modules/acm/aws/latest

Additional ACM documentation can be found here: https://docs.aws.amazon.com/acm/latest/userguide/gs-acm-validate-dns.html

Hope these help! And If you have further questions, please reach out!

**Comment by bflad** [comment] 2021-01-22 17:35
It's been a long time since we heard from you here so we're going to close this out. Hopefully the information provided above helped resolve any issues.

**Closed by bflad** 2021-01-22 17:35 UTC
Labels: service/acm, waiting-response
