### ISSUE TITLE
[Bug]: aws_guardduty_organization_configuration not accepting detector ID 

### ISSUE THREAD

**Issue by willhume** [hashicorp/terraform-provider-aws#34765] opened 2023-12-06 16:03 UTC
### Terraform Core Version

v1.5.4

### AWS Provider Version

v5.29.0

### Affected Resource(s)

aws_guardduty_detector
aws_guardduty_organization_configuration

### Expected Behavior

```
resource "aws_guardduty_detector" "detector" {
  enable = true
}
resource "aws_guardduty_organization_configuration" "guardduty_org" {
  auto_enable_organization_members = "ALL"
  detector_id = aws_guardduty_detector.detector.id

  datasources {
    s3_logs {
      auto_enable = false
    }
    kubernetes {
      audit_logs {
        enable = false
      }
    }
    malware_protection {
      scan_ec2_instance_with_findings {
        ebs_volumes {
          auto_enable = false
        }
      }
    }
  }
}
```
Should create the configuration 

### Actual Behavior

You get an error `The request is rejected because an invalid or out-of-range value is specified as an input parameter.` from using the dectector ID. I tried hard coding as well and still getting errors. This follows what the documentation suggests to do. 

### Relevant Error/Panic Output Snippet

```shell
aws_guardduty_organization_configuration.guardduty_org: Creating...
╷
│ Error: updating GuardDuty Organization Configuration (8c7c91f6dfe7464da1a2aa1c408013d7): BadRequestException: The request is rejected because an invalid or out-of-range value is specified as an input parameter.
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "0c26485a-b1eb-490e-9615-9fe57806550c"
│   },
│   Message_: "The request is rejected because an invalid or out-of-range value is specified as an input parameter.",
│   Type: "InvalidInputException"
│ }
│ 
│   with aws_guardduty_organization_configuration.guardduty_org,
│   on guardduty.tf line 5, in resource "aws_guardduty_organization_configuration" "guardduty_org":
│    5: resource "aws_guardduty_organization_configuration" "guardduty_org" {
│ 
╵
```

### Terraform Configuration Files

```
## GuardDuty Org settings
resource "aws_guardduty_detector" "detector" {
  enable = true
}
resource "aws_guardduty_organization_configuration" "guardduty_org" {
  auto_enable_organization_members = "ALL"
  detector_id = aws_guardduty_detector.detector.id

  datasources {
    s3_logs {
      auto_enable = false
    }
    kubernetes {
      audit_logs {
        enable = false
      }
    }
    malware_protection {
      scan_ec2_instance_with_findings {
        ebs_volumes {
          auto_enable = false
        }
      }
    }
  }
}

resource "aws_guardduty_organization_admin_account" "guardduty_org_admin" {
  admin_account_id = "<redacted>"
}
```

### Steps to Reproduce

Terraform plan and apply 

### Would you like to implement a fix?

None

**Comment by nbhadauria** [comment] 2023-12-08 02:10
Check if the account you are using to run this from is designated admin 

you console should show an option like this:

![image](https://github.com/hashicorp/terraform-provider-aws/assets/2682947/b1edb090-346b-4f4a-8820-489e52bad3f3)

Read More https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_organizations.html

**Comment by justinretzolk** [comment] 2024-01-18 17:56
Hey @Whume-Stitchfix 👋 Thank you for taking the time to raise this! Were you able to look into the suggestion above to see if that helped? If not, are you able to supply debug logging (redacted as needed) so that whoever looks into this issue has that information?

**Comment by brakf** [comment] 2024-02-05 12:12
Hi,
I am having a very similar issue. I think it is the same but they might have changed the error message. 
I can confirm that I am in the designated admin account as suggested. 

Here is my configuration:
`resource "aws_guardduty_organization_admin_account" "this" {
  admin_account_id = local.audit_account_id

  provider = aws.management
}

resource "aws_guardduty_detector" "this" {
  enable = true
}

resource "aws_guardduty_organization_configuration" "this" {
  auto_enable_organization_members = "ALL"

  detector_id = aws_guardduty_detector.this.id

  datasources {

    malware_protection {
      scan_ec2_instance_with_findings {
        ebs_volumes {
          auto_enable = true
        }
      }
    }
  }
}
`

Here is the error message:
`aws_guardduty_organization_configuration.this: Creating...
╷
│ Error: updating GuardDuty Organization Configuration (dbb8a758196d4e17acc1b1e1aedb9a92): BadRequestException: The request failed because you do not have required AWS Organization master permission.
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "2328d568-8aca-49ea-9594-93b008e93490"
│   },
│   Message_: "The request failed because you do not have required AWS Organization master permission.",
│   Type: "InvalidInputException"
│ }
│ 
│   with aws_guardduty_organization_configuration.this,
│   on main.tf line 11, in resource "aws_guardduty_organization_configuration" "this":
│   11: resource "aws_guardduty_organization_configuration" "this" {
│ 
╵`

**Comment by brakf** [comment] 2024-02-05 12:16
Update:
I removed the datasources block and it worked!
Then, I added it back into the config and ran the update. As expected it failed, so the cause of the failure must be within that block

**Comment by twelsh-aw** [comment] 2024-02-23 17:14
Just chiming in: but this is the same error I got when trying to apply `aws_guardduty_organization_configuration` in an account that was not the delegated admin **_for that region_**. 

In particular, once I updated the account to be the delegated admin in all the regions I was applying against, this error went away.

**Comment by kitos9112** [comment] 2024-03-11 18:24
> Just chiming in: but this is the same error I got when trying to apply `aws_guardduty_organization_configuration` in an account that was not the delegated admin **_for that region_**.
> 
> In particular, once I updated the account to be the delegated admin in all the regions I was applying against, this error went away.

Thanks for the pointer! I encountered the same issue. This AWS terraform resource should throw a similar pointer though :)

**Comment by justinretzolk** [comment] 2024-03-13 18:33
Based on the replies here, it looks like this isn't something that will need to be addressed by the provider, so we'll close this issue for now. If you experience similar issues in the future that are unresolved by the things mentioned above, please open a new issue so that we can triage it effectively.

@kitos9112 I'd be remiss if I didn't address your point a bit before I close this out. In this case, we return [the error AWS returns](https://github.com/hashicorp/terraform-provider-aws/blob/d3b0bb5078357f9bb9cef9684c91d25b14b64dc2/internal/service/guardduty/organization_configuration.go#L189-L191), so unfortunately there's not much we could do to provide further clarity, as much as we'd like to.

**Closed by justinretzolk** 2024-03-13 18:33 UTC
Labels: bug, service/guardduty, needs-triage
