### ISSUE TITLE
Terraform AWS Provider 4 version breaks "aws_s3_bucket" resource and not supports backward compatibility

### ISSUE THREAD

**Issue by menahemo** [hashicorp/terraform-provider-aws#23159] opened 2022-02-13 10:09 UTC
We are getting the following errors:
* provider.aws: version = "~> 4.0"

[33m
[1m[33mWarning: [0m[0m[1mInterpolation-only expressions are deprecated[0m

[0m  on main.tf line 2, in resource "aws_s3_bucket" "frontend_bucket":
   2:   bucket = [4m"${local.bucket_name}"[0m
[0m
Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.

(and 14 more similar warnings elsewhere)
[0m[0m
[33m
[1m[33mWarning: [0m[0m[1mQuoted references are deprecated[0m

[0m  on main.tf line 108, in resource "aws_cloudfront_distribution" "frontend_distribution":
 108:       [4m"origin"[0m
[0m
In this context, references are expected literally rather than in quotes.
Terraform 0.11 and earlier required quotes, but quoted references are now
deprecated and will be removed in a future version of Terraform. Remove the
quotes surrounding this reference to silence this warning.

(and one more similar warning elsewhere)
[0m[0m
[33m
[1m[33mWarning: [0m[0m[1mQuoted type constraints are deprecated[0m

[0m  on var.tf line 2, in variable "_domains":
   2: variable _domains { type = [4m"list"[0m }
[0m
Terraform 0.11 and earlier required type constraints to be given in quotes,
but that form is now deprecated and will be removed in a future version of
Terraform. To silence this warning, remove the quotes around "list" and write
list(string) instead to explicitly indicate that the list elements are
strings.

(and 7 more similar warnings elsewhere)
[0m[0m
[0m[1m[32mTerraform has been successfully initialized![0m[32m[0m
[0m[32m
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.[0m
[terragrunt] [/home/ec2-user/jenkins2/workspace/STAGING_Infra_Update_PR_Apply/dome9-terraform-infrastructure-live/central/stg/eu-west-1/infra_modules/msp_frontend] 2022/02/13 08:33:48 Running command: terraform apply -lock-timeout=20m -auto-approve -input=false -auto-approve -no-color

Error: Value for unconfigurable attribute

  on main.tf line 1, in resource "aws_s3_bucket" "frontend_bucket":
   1: resource "aws_s3_bucket" "frontend_bucket" {

Can't configure a value for "versioning": its value will be decided
automatically based on the result of applying this configuration.

Error: Value for unconfigurable attribute

  on main.tf line 1, in resource "aws_s3_bucket" "frontend_bucket":
   1: resource "aws_s3_bucket" "frontend_bucket" {

Can't configure a value for "website": its value will be decided automatically
based on the result of applying this configuration.

Error: Value for unconfigurable attribute

  on main.tf line 1, in resource "aws_s3_bucket" "frontend_bucket":
   1: resource "aws_s3_bucket" "frontend_bucket" {

Can't configure a value for "logging": its value will be decided automatically
based on the result of applying this configuration.

Error: Value for unconfigurable attribute

  on main.tf line 3, in resource "aws_s3_bucket" "frontend_bucket":
   3:   acl    = "private"

Can't configure a value for "acl": its value will be decided automatically
based on the result of applying this configuration.

Error: Value for unconfigurable attribute

  on main.tf line 4, in resource "aws_s3_bucket" "frontend_bucket":
   4:   policy = "${data.aws_iam_policy_document.website_bucket_policy.json}"

Can't configure a value for "policy": its value will be decided automatically
based on the result of applying this configuration.

Error: Value for unconfigurable attribute

  on main.tf line 1, in resource "aws_s3_bucket" "frontend_bucket":
   1: resource "aws_s3_bucket" "frontend_bucket" {

Can't configure a value for "logging": its value will be decided automatically
based on the result of applying this configuration.

Error: Value for unconfigurable attribute

  on main.tf line 1, in resource "aws_s3_bucket" "frontend_bucket":
   1: resource "aws_s3_bucket" "frontend_bucket" {

Can't configure a value for "versioning": its value will be decided
automatically based on the result of applying this configuration.

Error: Value for unconfigurable attribute

  on main.tf line 1, in resource "aws_s3_bucket" "frontend_bucket":
   1: resource "aws_s3_bucket" "frontend_bucket" {

Can't configure a value for "website": its value will be decided automatically
based on the result of applying this configuration.

Error: Value for unconfigurable attribute

  on main.tf line 3, in resource "aws_s3_bucket" "frontend_bucket":
   3:   acl    = "private"

Can't configure a value for "acl": its value will be decided automatically
based on the result of applying this configuration.

Error: Value for unconfigurable attribute

  on main.tf line 4, in resource "aws_s3_bucket" "frontend_bucket":
   4:   policy = "${data.aws_iam_policy_document.website_bucket_policy.json}"

Can't configure a value for "policy": its value will be decided automatically
based on the result of applying this configuration.

**Comment by enarmontas** [comment] 2022-02-14 09:44
I can confirm the same issue. I solved it by locking the older provider version for now.

**Comment by justinretzolk** [comment] 2022-02-14 22:15
Hey y'all 👋 Thank you for taking the time to raise this issue and for the additional discussion around it. In this case, this is a duplicate of #23106. We like to try to keep the discussion centralized where possible, and the discussion on that issue is pretty active, so we'll close this one for now in favor of #23106.

**Closed by justinretzolk** 2022-02-14 22:15 UTC
Labels: service/s3, service/cloudfront, needs-triage
