### ISSUE TITLE
Implement AWS WAFv2 "Custom Response Bodies"

### ISSUE THREAD

**Issue by wesleywh** [hashicorp/terraform-provider-aws#18907] opened 2021-04-15 20:52 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It looks like generate a "Custom Response Bodies" are not supported by terraform? Is this true? This is for AWS WAFv2. I don't see any option to actually generate this with terraform docs which tells me that this might not actually be supported.

Just putting in a request to get this supported by terraform. Thanks!

### New or Affected Resource(s)

* aws_wafv2_web_acl

### Potential Terraform Configuration

```
resource "aws_wafv2_web_acl" "application" {
    name     = "..."
    scope    = "CLOUDFRONT"

    description = "..."
 
    default_action {
        allow {}
    }
  
    rule {
      ...
    }

    custom_response_body = {
         <json_obj>
    }
...
...
```

### References
Couldn't find anything referencing this.

**Comment by YakDriver** [comment] 2021-04-16 05:21
@wesleywh Thanks for bringing this up! This appears to be a duplicate of #18754. Since up votes help us prioritize our work, I'm going to close this to focus future travelers to that issue.

**Closed by YakDriver** 2021-04-16 05:21 UTC
Labels: enhancement, needs-triage, service/wafv2
