### ISSUE TITLE
Terraform doesn't detect client secret value change when updated from AWS console

### ISSUE THREAD

**Issue by ccsandhanshive** [hashicorp/terraform-provider-aws#22524] opened 2022-01-11 15:27 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.31
+ provider.aws v3.61.0

### Affected Resource(s)

aws_lb_listener, aws_lb_listener_rule

### Terraform Configuration Files

```hcl
resource "aws_lb" "front_end" {
  # ...
}

resource "aws_lb_target_group" "front_end" {
  # ...
}

resource "aws_lb_listener" "front_end" {
  load_balancer_arn = aws_lb.front_end.arn
  port              = "443"
  protocol          = "HTTPS"

  default_action {
    type = "authenticate-oidc"

    authenticate_oidc {
      authorization_endpoint = "https://example.com/authorization_endpoint"
      client_id              = "client_id"
      client_secret          = "client_secret"
      issuer                 = "https://example.com"
      token_endpoint         = "https://example.com/token_endpoint"
      user_info_endpoint     = "https://example.com/user_info_endpoint"
    }
  }

  default_action {
    type             = "forward"
    target_group_arn = aws_lb_target_group.front_end.arn
  }
}
```
Above given code snippet is terraform provided example for aws_lb_listener
### Expected Behavior

On successful creation of the resource from terraform, when user tries to change the client secret value from AWS console, terraform should detect the changes of client secret.

### Actual Behavior

Terraform doesn't detect any changes made to client secret, when client secret value is being updated from AWS console

### Steps to Reproduce

1. `terraform apply`
2. `change client secret of LB listener resource on AWS console`
3. `terraform apply`

### Important Factoids

Is this an intentional behavior from terraform side wherein client secret changes are not being detected or is it a bug.

Kindly confirm.

**Comment by justinretzolk** [comment] 2022-01-11 19:11
Hey @ccsandhanshive 👋 Thank you for taking the time to file this issue! I've taken a look, and it appears this is expected behavior. The codebase for the AWS provider calls this out [here](https://github.com/hashicorp/terraform-provider-aws/blob/d30ffe12a372215dfa3f756648c1ace4681fc607/internal/service/elbv2/listener.go#L941-L947); to save you a click: 

```plaintext
// The LB API currently provides no way to read the ClientSecret
// Instead we passthrough the configuration value into the state
```

Since this appears to be a limitation on AWS' side, we'll close this issue for now. If you feel we've done this in error, please do let us know.

**Closed by justinretzolk** 2022-01-11 19:11 UTC
Labels: service/elbv2, needs-triage
