### ISSUE TITLE
[Bug]: Issue with Latest Terraform AWS Provider Version v5.71.0 #1

### ISSUE THREAD

**Issue by manesanket11** [hashicorp/terraform-provider-aws#39681] opened 2024-10-11 07:42 UTC
### Terraform Core Version

v1.9.5

### AWS Provider Version

v5.71.0

### Affected Resource(s)

Installing hashicorp/aws v5.71.0...
╷
│ Error: Failed to install provider
│
│ Error while installing hashicorp/aws v5.71.0: archive has incorrect
│ checksum
│ zh:21f5d77f2859d9ddb5fafa7b6cfd0efdf82977c631ce788e56728afc6da17323
│ (expected
│ zh:c164d3ed13eb4c28ac243221591fc4ac3cfe621f8cd20af[53]

### Expected Behavior

It should not give this error

### Actual Behavior

Hello Everyone,

Looks like there is an issue with the Latest Terraform AWS Provider Version v5.71.0. I am getting below error while executing terraform code. it works fine when I set the provider version to the hashicorp/aws v5.70.0

Installing hashicorp/aws v5.71.0...
╷
│ Error: Failed to install provider
│
│ Error while installing hashicorp/aws v5.71.0: archive has incorrect
│ checksum
│ zh:21f5d77f2859d9ddb5fafa7b6cfd0efdf82977c631ce788e56728afc6da17323
│ (expected
│ zh:c164d3ed13eb4c28ac243221591fc4ac3cfe621f8cd20af[53]

### Terraform Configuration Files

terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
  }
}

### Steps to Reproduce

terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
  }
}

### Would you like to implement a fix?

None

**Comment by anmolsha-te** [comment] 2024-10-11 07:47
This issue is duplicate of https://github.com/hashicorp/terraform-provider-aws/issues/39676

**Comment by reixd** [comment] 2024-10-11 07:47
Quick workaround until filxed

```
provider "aws" {
  region = var.region
  version = "< 5.71.0"
}
```

**Comment by jeremychauvet** [comment] 2024-10-11 07:53
Hello 👋🏼
Running a terraform init -upgrade should help.
Full explanation on #39676

**Comment by bassmanitram** [comment] 2024-10-11 09:58
Needless to say, but just in case of any confusion, this occurs for any version of Terraform that can use V5 of the AWS provider.

**Comment by justinretzolk** [comment] 2024-10-11 15:22
Copying over my comment from #39676:

Hey everyone 👋 Thank you very much for taking the time to raise this, and for adding reactions to help ensure it was brought to our attention -- that's extremely helpful. We ran into an issue with our release process that led to this, and so have pulled the 5.71.0 release to resolve the immediate issue. We're working through the release issue internally, and will make a new release once we're confident that it has been resolved.

Since the issue reported here has been resolved, I'm going to close this issue out. Thank you again to all who reported -- if you run into issues in the future, please do continue to let us know!

**Closed by justinretzolk** 2024-10-11 15:22 UTC
Labels: bug, provider

**Comment by myshon** [comment] 2024-10-15 06:32
![image](https://github.com/user-attachments/assets/41941463-1294-4589-af34-d5da960eafb6)
I suggest extending weekends for employees, not for simple bugs. ;) Can't wait for the patch—really don’t want to be fixing multiple pipelines myself.
