### ISSUE TITLE
[Bug]: Lex Bot Version History Lost When Creating New Version

### ISSUE THREAD

**Issue by hrsh1209** [hashicorp/terraform-provider-aws#39764] opened 2024-10-17 10:45 UTC
### Terraform Core Version

1.9.5

### AWS Provider Version

5.71.0

### Affected Resource(s)

resource - aws_lexv2models_bot_version

### Expected Behavior

When updating the Lex bot, the system should create a new version for the updated bot. Preserve all previous versions. Provide the ability to view and access all historical versions of the bot

### Actual Behavior

Each time when we deployment it overwrites the existing bot version and creates new version. The old version is deleted, resulting in a loss of version history. We cannot maintain a record of previous bot version on aws.

### Relevant Error/Panic Output Snippet

```shell
resource "aws_lexv2models_bot_version" "lex_bot_versioning_live" {
      ~ bot_version          = "1" -> (known after apply)
      ~ description          = "Live version 2 for config 03e7c8b3559da9dc3b73da31c6d1939f" -> "Live version 3 for config ad780b72e2b26f35a665c23464f909d3" # forces replacement
      ~ id                   = "GXHFIROMEC,1" -> (known after apply)
        # (2 unchanged attributes hidden)
    }
```

### Terraform Configuration Files

```hcl
resource "aws_lexv2models_bot_version" "lex_bot_versioning_live" {
  for_each    = local.lex_bots
  bot_id      = awscc_lex_bot.lex_bot[each.key].id
  description = "Live version ${var.live_version} for config ${local.bot_config_hash[each.key].live}"
  locale_specification = { 
    for lang in each.value.languages : 
    lang => { source_bot_version = "DRAFT" } 
  }
}
```

### Steps to Reproduce

1. Set up a Terraform configuration using the AWSCC provider for Lex bot deployment.
2. Define a Lex bot resource in your Terraform configuration, specifying the initial bot version details.
3. Apply the Terraform configuration to create the initial bot version.
4. Modify the Terraform configuration to update the Lex bot with a new version (e.g., by changing the bot file location or content).
5. Apply the Terraform configuration again to create a new bot version.
6. Check the AWS Console or use AWS CLI to list the Lex bot versions.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-10-18 22:34
Hey @hrsh1209 👋 Thank you for taking the time to raise this! I took a look at the resource documentation and noted the following:

> Terraform resource for managing an AWS Lex V2 Models Bot Version.

My read is that this resource is for managing a _specific_ version, and that this is working as expected. The [API reference](https://docs.aws.amazon.com/lexv2/latest/APIReference/API_CreateBotVersion.html) seems to confirm this:

> Creates an immutable version of the bot. When you create the first version of a bot, Amazon Lex sets the version number to 1. Subsequent bot versions increase in an increment of 1. The version number will always represent the total number of versions created of the bot, not the current number of versions. If a bot version is deleted, that bot version number will not be reused.

Since the version is immutable, you're not updating the version, but rather replacing it. This can be seen in your output logs with the "forces replacement" indication:

```console
description          = "Live version 2 for config 03e7c8b3559da9dc3b73da31c6d1939f" -> "Live version 3 for config ad780b72e2b26f35a665c23464f909d3" # forces replacement
```

Since the resource is being replaced, the current version is being deleted and a new version is being created. If you wanted to retain prior versions, you'll need to refactor your configuration such that a new `aws_lexv2models_bot_version` resource is created for every version. You should be able to do this using the `for_each` that you're already using.

Since this is working as expected, and there's no further action for the AWS Provider team to take, I'm going to close this issue. If you experience unexpected behavior in the future, please do let us know!

**Closed by justinretzolk** 2024-10-18 22:34 UTC
Labels: bug, needs-triage, service/lexv2models
