### ISSUE TITLE
[Bug]: `aws_lambda_function` requires code even with publish disabled

### ISSUE THREAD

**Issue by pcallewaert** [hashicorp/terraform-provider-aws#29043] opened 2023-01-23 13:41 UTC
### Terraform Core Version

1.3.7

### AWS Provider Version

4.51.0

### Affected Resource(s)

* aws_lambda_function

### Expected Behavior

With publish set to `false`, the `filename`, `image_uri` or `s3_bucket` were allowed to be not set (v4.50.0)

### Actual Behavior

Returns error during `validate`:

```shell
│ Error: Invalid combination of arguments
│ 
│   with aws_lambda_function.my_lambda,
│   on katalog-lambdas.tf line 23, in resource "aws_lambda_function" "my_lambda":
│   23: resource "aws_lambda_function" "my_lambda" {
│ 
│ "filename": one of `filename,image_uri,s3_bucket` must be specified
╵
╷
│ Error: Invalid combination of arguments
│ 
│   with aws_lambda_function.my_lambda,
│   on katalog-lambdas.tf line 23, in resource "aws_lambda_function" "my_lambda":
│   23: resource "aws_lambda_function" "my_lambda" {
│ 
│ "image_uri": one of `filename,image_uri,s3_bucket` must be specified
╵
╷
│ Error: Invalid combination of arguments
│ 
│   with aws_lambda_function.my_lambda,
│   on katalog-lambdas.tf line 23, in resource "aws_lambda_function" "my_lambda":
│   23: resource "aws_lambda_function" "my_lambda" {
│ 
│ "s3_bucket": one of `filename,image_uri,s3_bucket` must be specified
```

### Terraform Configuration Files

```terraform
resource "aws_lambda_function" "my_lambda" {
  function_name = "my_lambda"
  role          = "<valid role>"
  handler       = "index.handler"
  runtime       = "nodejs16.x"
  timeout       = 60
  description   = "Lambda reproduce error"
  publish       = false
}
```

### Steps to Reproduce

Install provider v4.50.0

Try `terraform validate` with above code. => Should succeed.

Upgrade provider to v4.51.0:

Execute `terraform validate` => Will fail

### References

I think it's related with the refactor in https://github.com/hashicorp/terraform-provider-aws/pull/28963

### Would you like to implement a fix?

No

**Comment by justinretzolk** [comment] 2023-01-23 19:40
Hey @pcallewaert 👋 Thank you for taking the time to raise this! The `publish` argument refers to whether or not [Lambda function versions](https://docs.aws.amazon.com/lambda/latest/dg/configuration-versions.html) are created when a change occurs. When set to `false`, a function version isn't published, but the function _is_ still created in AWS, therefor the Lambda function package must still be supplied by setting on of:

- `image_uri`
- `filename`
-  `s3_bucket`, `s3_key`, and `s3_object_version`

**Comment by pcallewaert** [comment] 2023-01-25 08:46
Hello @justinretzolk,

AFAIK we imported most of our lambda functions, so there was no initial deployment package. We use this to manage the runtime and env variables, not the code.
This was allowed to v4.50.0, since v4.51.0 this now fails with the mentioned error.
Should we pass a dummy value in the `filename` setting?

**Comment by maystreet-its** [comment] 2023-01-27 22:05
This completely broke our deployments and appears to be a valid regression.  An upgrade to 4.51 from 4.50 should not trigger breakage.

**Comment by mdemartinis** [comment] 2023-02-03 19:17
Same situation happened to me. A lot of Lambdas have been imported prior v4.51.0 and now I can't apply changes because it is requesting the code to deploy.
It would be ideal to have a flag to choose if code will be deployed or not. Eventually, if trying to create a new Lambda with no code, make it fail, but allow updating the resource without code.

**Comment by Deadvi5** [comment] 2023-03-08 15:37
Same situation happened to me too. When we create the infrastructure for the first time without a deployed package (obviously) it's going to break the apply. It's not the ideal situation

**Comment by jar-b** [comment] 2023-03-09 20:06
Likely introduced in #28963

**Comment by AntonyOnScript** [comment] 2023-04-07 00:50
> This completely broke our deployments and appears to be a valid regression. An upgrade to 4.51 from 4.50 should not trigger breakage.

i think the same

**Comment by delsantosmiranda** [comment] 2023-04-28 16:20
A workaround to resolve this is to pass the filename with any file, and create an ignore_changes block for the filename.
That way terraforn will not try to apply this configuration to the lambda and apply will not break.

`  filename                       = "function.zip"
  lifecycle {
    ignore_changes = [filename]
  }`

**Comment by justinretzolk** [comment] 2023-06-09 17:56
Thank you for mentioning that workaround @delsantosmiranda 🎉. 

On reviewing this again, with an edge case such as only using the `aws_lambda_function` to manage certain aspects of imported Lambda functions, that workaround is the best path forward unless the underlying API has such functionality added, since modifying the resource to work around not fully managing the function would go against the [design principle](https://developer.hashicorp.com/terraform/plugin/best-practices/hashicorp-provider-design-principles#resource-and-attribute-schema-should-closely-match-the-underlying-api) of matching the underlying API.

With that in mind, I'm going to close this issue. If you feel I've done this in error, or have additional thoughts that should be considered, please do let me know.

**Closed by justinretzolk** 2023-06-09 17:56 UTC
Labels: service/lambda
