### ISSUE TITLE
AWS MemoryDB for Redis Resources

### ISSUE THREAD

**Issue by kolanos** [hashicorp/terraform-provider-aws#20631] opened 2021-08-20 00:49 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS has recently announced [MemoryDB for Redis](https://aws.amazon.com/blogs/aws/introducing-amazon-memorydb-for-redis-a-redis-compatible-durable-in-memory-database-service/) and it is already GA. Would be great if `terraform-provider-aws` supported this service. Appears to have a lot of overlap with ElastiCache Redis.

I didn't see an issue for this service, so wanted to make sure one was created to track progress.

### New or Affected Resource(s)

* TBD

### Potential Terraform Configuration

TBD

### References

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2021/08/amazon-memorydb-redis/)
* [Blog post](https://aws.amazon.com/blogs/aws/introducing-amazon-memorydb-for-redis-a-redis-compatible-durable-in-memory-database-service/)

**Comment by ewbankkit** [comment] 2021-08-20 11:48
Requires [AWS SDK v1.40.26](https://github.com/aws/aws-sdk-go/releases/tag/v1.40.26):

* #20632

**Comment by Alexx-G** [comment] 2021-10-11 07:52
@ewbankkit @anGie44 Given that MemoryDB is already available in [multiple regions](https://docs.aws.amazon.com/general/latest/gr/memorydb-service.html), do you have a guesstimate on the timeline for this feature?

**Comment by lemon-li** [comment] 2021-11-01 13:11
any progress ?

**Comment by grepsedawk** [comment] 2021-11-01 16:52
Bumping this issue won't get you anywhere. If you want this dropped make a PR.

**Comment by kaelo-dev** [comment] 2021-11-29 06:47
Does anyone know if Terraform supports MemoryDB For Redis yet?

**Comment by grepsedawk** [comment] 2021-11-29 16:49
@kaelo-dev the issue is still open and the aren't any merged PRs, I'd say it probably isn't complete yet.
But you can always check the docs to see if it's been added.

**Comment by HugoICSilva** [comment] 2021-12-06 10:16
Any news regarding MemoryDB for Redis in TF?
BR

**Comment by grepsedawk** [comment] 2021-12-06 14:02
Bumping this issue won't get your anyway, don't be rude.

**Comment by roberth-k** [comment] 2021-12-14 16:12
I'll pick this up.

Looking at the API documentation, there's a lot that can be ported from ElastiCache with some modernisation. I'm planning to trickle this as separate resource PR-s as follows:

- `aws_memorydb_subnet_group`. This also delivers some of the underlying utility boilerplate, such as tagging functions.
- `aws_memorydb_parameter_group`
- `aws_memorydb_acl`
- `aws_memorydb_user`
- With the above four in place, `aws_memorydb_cluster`, but excluding restore from snapshot.
- `aws_memorydb_snapshot`
- Restore from snapshot support in `aws_memorydb_cluster`.

I can submit PR-s for a few of the prerequisite resources in before holidays, but the `aws_memorydb_cluster` would have to wait until next year.

**Comment by roberth-k** [comment] 2022-01-07 11:42
With the exception of `aws_memorydb_snapshot` and sweepers, the service is available as of 3.71.0.

**Closed** 2022-01-10 14:25 UTC
Labels: enhancement
