### ISSUE TITLE
Add Data Source: aws_api_gateway_method

### ISSUE THREAD

**Issue by vab2048** [hashicorp/terraform-provider-aws#26381] opened 2022-08-18 20:35 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Suppose you are importing an Open API spec file using `resource "aws_api_gateway_rest_api"` like so:

```terraform
resource "aws_api_gateway_rest_api" "example" {
  name = "Test"
  description = "API for testing"
  body = file("${path.module}/api-gateway-spec.json")
  endpoint_configuration {
    types = ["REGIONAL"]
  }
}
```

It is expected that the spec contain additional metadata (`x-amazon-apigateway-integration`) for each method so everything will be configured. 

However I cannot pre-populate the methods with this data (the file is what it is).

And so without the `x-amazon-apigateway-integration` everything is setup except for the method integration. It would be useful to have a data provider which can get all of the required data for a specific method path (including the path's `resource_id`, `rest_api_id`, etc.) so it could be used later to calls to the `aws_api_gateway_integration` resource.

**Comment by justinretzolk** [comment] 2022-08-18 21:04
Hey @vab2048 👋 Thanks for taking the time to submit this issue. It looks like this is a duplicate of #26204. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #26204.

**Closed by justinretzolk** 2022-08-18 21:04 UTC
Labels: enhancement, new-data-source, service/apigateway

**Comment by vab2048** [comment] 2022-08-18 21:58
Thanks, I'll give that issue an upvote 👍
