### ISSUE TITLE
AWS_Appstream_fleet_stack_Association

### ISSUE THREAD

**Issue by sandy6377** [hashicorp/terraform-provider-aws#22932] opened 2022-02-03 23:22 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
 terraform cli version 0.12.29 and aws provider version >3.70

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
resource "aws_appstream_fleet_stack_association" "fsassociation" {
  depends_on = [
    aws_appstream_stack.appstream_stack,
    aws_appstream_fleet.appstream_fleet
  ]
  stack_name = aws_appstream_stack.stack_name.name
  fleet_name = aws_appstream_fleet.fleet_name.name
}

# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by sandy6377** [comment] 2022-02-03 23:25
Actual code:

resource "aws_appstream_fleet_stack_association" "fsassociation" {
  depends_on = [
    aws_appstream_stack.appstream_stack,
    aws_appstream_fleet.appstream_fleet
  ]
  stack_name = aws_appstream_stack.stack_name.name
  fleet_name = aws_appstream_fleet.fleet_name.name
}


tf version: 0.12.29 and AWS version 3.70 and above

output issue: its creating the fleet stack association for first time with error

Error: error reading AppStream Fleet Stack Association (example_stack/example_fleet): No stack "example_fleet" associated with fleet "example_stack"

when i try redeploying then : 
Error: error creating AppStream Fleet Stack Association (): LimitExceededException: The Fleet attachment limit to stack error_stack was exceeded. Requested: 2, Limit: 1

**Comment by justinretzolk** [comment] 2022-02-16 21:33
Hey @sandy6377 👋 Thanks for taking the time to submit this issue. It looks like this is a duplicate of #22625. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #22625.

**Closed by justinretzolk** 2022-02-16 21:33 UTC
Labels: needs-triage
