### ISSUE TITLE
[Bug]: Getting invalid value for capacity_provider_strategy while trying to create an ECS

### ISSUE THREAD

**Issue by Prabhanjali** [hashicorp/terraform-provider-aws#37865] opened 2024-06-06 15:01 UTC
### Terraform Core Version

0.15.4

### AWS Provider Version

3.68.0

### Affected Resource(s)

aws_ecs_service, aws_ecs_cluster

### Expected Behavior

to avoid this error and this service to be worked without any errors

### Actual Behavior

I've previously used AWS provider version of 3.57.0. Recently, I changed the version to 3.68.0, from then, I'm encountering this issue.

**Error:**

```console
'Error: Provider produced inconsistent final plan'
When expanding the plan for aws_ecs_service.task_service[0] to include new values learned so far during apply, provider '"registry.terraform.io/hashicorp/aws" produced an invalid new value for' '.capacity_provider_strategy: planned set element'
cty.ObjectVal(map[string]cty.Value{"base":cty.NullVal(cty.Number), '"capacity_provider":cty.StringVal(""), "weight":cty.NullVal(cty.Number)})' does not correlate with any element in actual.
```

### Relevant Error/Panic Output Snippet

```console
'Error: Provider produced inconsistent final plan'
When expanding the plan for aws_ecs_service.task_service[0] to include new values learned so far during apply, provider '"registry.terraform.io/hashicorp/aws" produced an invalid new value for' '.capacity_provider_strategy: planned set element'
cty.ObjectVal(map[string]cty.Value{"base":cty.NullVal(cty.Number), '"capacity_provider":cty.StringVal(""), "weight":cty.NullVal(cty.Number)})' does not correlate with any element in actual.
```

### Terraform Configuration Files

```hcl
resource "aws_autoscaling_group" "test" {
  # ... other configuration, including potentially other tags ...

  tag {
    key                 = "AmazonECSManaged"
    value               = true
    propagate_at_launch = true
  }
}

resource "aws_ecs_capacity_provider" "test" {
  name = "test"

  auto_scaling_group_provider {
    auto_scaling_group_arn         = aws_autoscaling_group.test.arn
    managed_termination_protection = "ENABLED"

    managed_scaling {
      maximum_scaling_step_size = 1000
      minimum_scaling_step_size = 1
      status                    = "ENABLED"
      target_capacity           = 10
    }
  }
}
```

### Steps to Reproduce

1. terraform init
2. terraform plan
3. terraform apply

### Would you like to implement a fix?

None

**Comment by Prabhanjali** [comment] 2024-06-07 11:30
Hey, Can anyone check this issue and let me know how to fix this?

**Comment by justinretzolk** [comment] 2024-06-11 17:35
Hey @Prabhanjali 👋 Thank you for taking the time to raise this! The version of Terraform and the AWS Provider that you're using are both quite old at this point. Can you test with more recent versions to see if the issue persists?

**Comment by Prabhanjali** [comment] 2024-06-12 04:44
sure, if I change the version of terraform/ aws provider, are there any changes that I need to change for the existing configurations of my ECS and it's supporting services?

**Comment by Prabhanjali** [comment] 2024-06-14 14:19
@justinretzolk, do we have any restrictions to use the terraform version with aws provider version?? What is the **maximum aws provider** version that **0.15.4** terraform version accepts? Is there any documentation for this?

**Comment by justinretzolk** [comment] 2024-06-14 17:12
Hey @Prabhanjali 👋 To my knowledge, 0.15 should still work with largely every provider, but that'll begin to change as providers adopt later revisions of Terraform's underlying framework, the AWS provider included. For now, even the most recent versions work with that version of Terraform:

```console
$ terraform -v
Terraform v0.15.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v5.54.1
```

**Comment by Prabhanjali** [comment] 2024-06-17 04:26
Hey @justinretzolk, thanks for your reply. Let me check and get back to you

**Comment by Prabhanjali** [comment] 2024-06-18 14:32
@justinretzolk, Can you let me know in which version of aws provider the below issue is resolved?
```
'Error: Provider produced inconsistent final plan'
When expanding the plan for aws_ecs_service.task_service[0] to include new values learned so far during apply, provider '"registry.terraform.io/hashicorp/aws" produced an invalid new value for' '.capacity_provider_strategy: planned set element'
cty.ObjectVal(map[string]cty.Value{"base":cty.NullVal(cty.Number), '"capacity_provider":cty.StringVal(""), "weight":cty.NullVal(cty.Number)})' does not correlate with any element in actual.
```

It's hard to trail all the provider versions and there are changes to the resources like capacity_provider in the terraform major version 4 when compared to 3.

**Comment by justinretzolk** [comment] 2024-07-02 19:58
Hey @Prabhanjali 👋 That's a fairly generic error, so we unfortunately wouldn't be able to deduce that kind of information from that alone. If it's at all possible, it may be worth creating a small reproduction that you can test against later versions, so as to not impact your other workloads. Given that we don't backport fixes as far back as the version you're currently using, we'll need confirmation that this impacts more recent versions to ensure that this gets prioritized in a timely manner.

**Comment by Prabhanjali** [comment] 2024-07-03 16:29
@justinretzolk, can you please let me know in which terraform and aws provider version this issue is resolved?

**Comment by justinretzolk** [comment] 2024-07-29 16:26
Hey @Prabhanjali 👋 It would be difficult for us to determine exactly which versions experience this behavior without manually stepping through each one. It could be that the issue occurs even with more recent versions of Terraform and the AWS provider, however, without a configuration that can be used to reproduce the issue, we're not able to verify that. If you're able to reproduce with recent versions of Terraform and the AWS provider and then provide us a sample configuration and/or debug logging (redacted as needed), we'd be happy to look at this more. Unfortunately, without that information, we'll need to close this issue as unreproducible.

**Comment by justinretzolk** [comment] 2024-08-30 16:17
Since we haven't heard back, and with my previous comment in mind, I'm going to close this issue. If you experience unexpected behavior with the provider in the future, please do let us know!

**Closed by justinretzolk** 2024-08-30 16:17 UTC
Labels: bug, waiting-response, service/ecs, needs-triage
