### ISSUE TITLE
When creating a new SNS subscription, with the same endpoint of an existing subscription, it recreates it

### ISSUE THREAD

**Issue by IslamAzab** [hashicorp/terraform-provider-aws#9883] opened 2019-08-26 18:42 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```bash
Terraform v0.12.6
+ provider.aws v2.21.1
+ provider.google v2.12.0
+ provider.template v2.1.2
```

### Affected Resource(s)

* `aws_sns_topic_subscription`

### Terraform Configuration Files

```hcl
resource "aws_sns_topic_subscription" "some_subscription" {
  topic_arn              = "arn:aws:sns:eu-west-1:123456:topic_name"
  protocol               = "https"
  endpoint               = "https://some.subscriptions.com/"
  endpoint_auto_confirms = true
}

resource "aws_sns_topic_subscription" "a_new_subscription_with_the_same_url" {
  topic_arn              = "arn:aws:sns:eu-west-1:123456:topic_name"
  protocol               = "https"
  endpoint               = "https://some.subscriptions.com/"
  endpoint_auto_confirms = true
}
```

### Expected Behavior

When creating a new subscription, with the same `endpoint` of an existing subscription, plan should fail with the following error.

When the same is tried from AWS console, we get this error message.
```
Couldn't create subscription.
Error code: InvalidParameter - Error message: Invalid parameter: Attributes Reason: Subscription already exists with different attributes
```

### Actual Behavior

Creating a new subscription with the same url does not fail, but recreates the old subscription.

```bash
  # module.some_subscription will be created
  + resource "aws_sns_topic_subscription" "a_new_subscription_with_the_same_url" {
      + arn                             = (known after apply)
      + confirmation_timeout_in_minutes = 1
      + endpoint                        = "https://some.subscriptions.com/"
      + endpoint_auto_confirms          = true
      + filter_policy                   = jsonencode({})
      + id                              = (known after apply)
      + protocol                        = "https"
      + raw_message_delivery            = false
      + topic_arn                       = "arn:aws:sns:eu-west-1:123456:topic_name"
    }
```

### Steps to Reproduce

1.  create an `aws_sns_topic_subscription` `some_subscription`
2. `terraform apply`
3. create a new `aws_sns_topic_subscription` `a_new_subscription_with_the_same_url` with the same `endpoint`
4. `terraform apply`

### References

* #0000

**Comment by agonbina** [comment] 2020-04-29 13:13
I would really like to understand the thinking behind this behavior (whoever implemented it) ...
myself and my team have wasted a couple of days all together on multiple occasions while debugging this issue.

**Comment by luk2302** [comment] 2021-03-17 11:37
That is expected behaviour as far as terraform and AWS SNS is concerned. If you run the same subscribe command twice in the aws cli you will not get an error, it will look like it succeeded and will still only have created one subscription. In general terraform does not verify different resources against each other - the two subscriptions resources are valid. You tell SNS "I want to subscribe this thing to SNS" twice and SNS chooses to "ignore" one of those requests because it already has an active subscription for that endpoint. 

Note that if you have different attributes for the same endpoint subscription terraform will still stay "go ahead, apply those two subscriptions" but the requests will then actually fail. Terraform does not perform all the verifications that AWS will do, and neither is it terraform's job to do so.

**Comment by justinretzolk** [comment] 2021-12-09 22:11
Thank you for the excellent breakdown @luk2302! There's not much more that I could say that hasn't already, but suffice it to say that the previous comment is accurate in that this would be expected behavior in this scenario. Given that's the case, we'll close this issue. If you feel we've done this in error, please do let us know.

**Closed by justinretzolk** 2021-12-09 22:11 UTC
Labels: service/sns, needs-triage
