### ISSUE TITLE
[Bug]: "provider" could be fetched from the state

### ISSUE THREAD

**Issue by EugenKon** [hashicorp/terraform-provider-aws#39588] opened 2024-10-03 21:34 UTC
### Terraform Core Version

v1.9.5

### AWS Provider Version

v5.67.0

### Affected Resource(s)

* provider aws

### Expected Behavior

When we delete resources in "west" region we also delete provider definition for that region. We do not expect to delete those at two steps:
* delete resources at region
* delete provider definition for that retion
The information about "west" region should be read from state file.

### Actual Behavior

It allows to delete resources at two steps:
* delete resources at "west" region
* plan/apply
* delete definition of provider for "west" region
* plan/apply

### Terraform Configuration Files

provider "aws" {
  alias = "east"
  region = "us-east-1"
}

provider "aws" {
  alias  = "west"
  region = "us-west-1"
}

resource "aws_s3_bucket" "west-planitar-public-releases" {
  provider = aws.west

  bucket        = "west-planitar-public-releases"
  force_destroy = false
  tags = {
    "project" = "software"
  }
}

### Steps to Reproduce

1. Define provider and resource at different region for main configuration
2. plan/apply
3. Delete provider and resource at different region
4. plan/apply

### Debug Output

╷
│ Error: Provider configuration not present
│
│ To work with aws_s3_bucket.west-planitar-public-releases (orphan) its original provider
│ configuration at provider["registry.terraform.io/hashicorp/aws"].west is required, but it has
│ been removed. This occurs when a provider configuration is removed while objects created by that
│ provider still exist in the state. Re-add the provider configuration to destroy
│ aws_s3_bucket.west-planitar-public-releases (orphan), after which you can remove the provider
│ configuration again.
╵
╷
│ Error: Provider configuration not present

### Would you like to implement a fix?

None

**Comment by trevorrea** [comment] 2024-10-04 11:30
Is this not expected behaviour? How would Terraform be able to remove the resources from AWS without a provider defintion for that region?

**Comment by dimaman2001** [comment] 2024-10-06 15:39
@EugenKon - The state file only stores which provider manages any given resource by referencing its location within your configuration tree. It does *not* store the provider definition such as region, credentials, default_tags, etc.

Feel free to post a state file if you disagree.

**Comment by trevorrea** [comment] 2024-10-07 08:25
This is an excerpt from a statefile:-

```
    {
      "module": "<redacted>",
      "mode": "managed",
      "type": "<redacted>",
      "name": "<redacted>",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"].ap-northeast-2",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "account_id": "<redacted>",
            "arn": "<redacted>",
            "id": "<redacted>",
            "region": "ap-northeast-2",
            "tags": {},
            "tags_all": {}
          },
          "sensitive_attributes": [],
          "private": "<redacted>",
        }
      ]
    }
```

If you don't have:-

```
provider "aws" {
  alias  = "ap-northeast-2"
  region = "ap-northeast-2"
}
```

in your Terraform configuration Terraform is unable to manage the resource.

**Comment by EugenKon** [comment] 2024-10-07 15:47
If I understand correct, the credentials are used from SSO, so they do not need to be stored at terraform state file.

@trevorrea 
It seems state file has all information which is at configuration file:
![image](https://github.com/user-attachments/assets/e1485114-08f2-4d79-982a-171bbba79b4d)

So if we know the region from the state file and based on that region from state file the credentials are fetched from SSO why we need to have `provider "aws"` in the configuration when we want to delete a resource?

**Comment by dimaman2001** [comment] 2024-10-07 18:44
@EugenKon - Its simply not how Terraform works. The provider definition must be within your configuration. Many users set various fields on the provider and these are *not* persisted in state. State will only store provider location and alias.

As an aside, this has nothing to do with *this* repository. Your question should be moved to [https://github.com/hashicorp/terraform](https://github.com/hashicorp/terraform)

**Comment by trevorrea** [comment] 2024-10-07 19:14
The state file is referencing the provider alias. If the provider definition for the region doesn't exist then the alias doesn't either. 

As @dimaman2001 says this is just the way Terraform works. It's not a bug in the AWS provider or Terraform itself. Questions like this belong in the Terraform community forums.

**Comment by EugenKon** [comment] 2024-10-07 19:44
This is not a question. It just works in unexpected way.
IMHO: If configuration is removed, the resources should just be removed automatically without further fancy steps. This is not how it should be designed =(

**Comment by asbarbati** [comment] 2024-10-12 20:39
> This is not a question. It just works in unexpected way. IMHO: If configuration is removed, the resources should just be removed automatically without further fancy steps. This is not how it should be designed =(

@EugenKon I can fully understand your frustration. I encountered a similar issue myself and spent a considerable amount of time resolving it. 
I can suggest to you to checkout the official KB about it here: https://support.hashicorp.com/hc/en-us/articles/1500000332721-Error-Provider-configuration-not-present.

Unfortunately this issue is agnostic from the provider used.

**Closed** 2024-10-15 21:22 UTC
Labels: bug, service/s3, needs-triage
