### ISSUE TITLE
no valid credential sources for Terraform AWS Provider found

### ISSUE THREAD

**Issue by AlexanderLahutsin** [hashicorp/terraform-provider-aws#23167] opened 2022-02-14 06:35 UTC
AWS Provider v4.00.0 - ptoblem
AWS Provider v3.64.0 - ok

╷
│ Error: error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
│
│ Please see https://registry.terraform.io/providers/hashicorp/aws
│ for more information about providing credentials.
│
│ Error: no EC2 IMDS role found, operation error ec2imds: GetMetadata, canceled, context deadline exceeded
│
│
│   with provider[“registry.terraform.io/hashicorp/aws”],
│   on main.tf line 13, in provider “aws”:
│   13: provider “aws” {
│

```
provider "aws" {
  profile                 = "test"
  shared_credentials_file = "~/.aws/credentials"
  region                  = "eu-west-2"
}

```

I changed this  "~/.aws/credentials" to "full path" and all ok but it's not useful for developing!

**Comment by limratechnologies** [comment] 2022-02-14 07:10
Same Issue here using **role_arn**, works in 3.74.2 but the same error in 4.0.0

```
provider "aws" {
  profil     = "test"
  role_arn = "xxx"
  regio     = "ap-southeast-2"
}
```

**Comment by phajduk** [comment] 2022-02-14 08:23
@AlexanderLahutsin  / @limratechnologies guys double check if your issues are related to @gdavison answer here https://github.com/hashicorp/terraform-provider-aws/issues/23131#issuecomment-1036643595. I believe you face exactly the same problem as described in the above issue.

**Comment by AlexanderLahutsin** [comment] 2022-02-14 09:01
> @AlexanderLahutsin / @limratechnologies guys double check if your issues are related to @gdavison answer here [#23131 (comment)](https://github.com/hashicorp/terraform-provider-aws/issues/23131#issuecomment-1036643595). I believe you face exactly the same problem as described in the above issue.

This is a problem that will snowball.

**Comment by ti33lee** [comment] 2022-02-14 09:37
specifying a known working provider version fixed it for me:

`terraform {
      required_providers {
         aws = {
         source = "hashicorp/aws"
         version = "= 3.74.2"
        }
     }
  }`

**Comment by phajduk** [comment] 2022-02-14 10:07
That's what @AlexanderLahutsin mentioned in the very first message, rollback to version <4.0 of this provider fixes the problem. We will have a lot of such Issues created in incoming weeks but the new version is major one so breaking changes should be expected.

**Comment by phajduk** [comment] 2022-02-14 10:32
Something like this:

```
terraform {
 ... some backend config if needed lands here ...
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "3.74.2" <- you hardcode provider version here
    }
  }
}

provider "aws" {
  region  = "ap-southeast-2"
  assume_role {
  role_arn = "xxx"
  }
}
```

Let us know if that solves the problem.

**Comment by atikhono** [comment] 2022-02-14 10:43
I have the same issue with 4.0.0 and empty provider config (provider "aws" {}) on a EC2 instance with an instance profile. Works with latest 3.x.

**Comment by phajduk** [comment] 2022-02-14 14:55
@AlexanderLahutsin I'm not a maintainer, nor hashicorp employee. I provide workaround for a breaking change which I also struggle with. You complain to the person who tries to help you. Major release always can introduce breaking change like in this. We need to wait for wider context or docs from maintainers. If you find ultimate solution by yourself, feel free to share it, without complains about breaking changes...

**Comment by limratechnologies** [comment] 2022-02-14 20:16
> Something like this:
> 
> ```
> terraform {
>  ... some backend config if needed lands here ...
>   required_providers {
>     aws = {
>       source = "hashicorp/aws"
>       version = "3.74.2" <- you hardcode provider version here
>     }
>   }
> }
> 
> provider "aws" {
>   region  = "ap-southeast-2"
>   assume_role {
>   role_arn = "xxx"
>   }
> }
> ```
> 
> Let us know if that solves the problem.

Thanks for your suggestion, it still won't work with the suggested code block on 4.x.x.

**Comment by justinretzolk** [comment] 2022-02-14 22:54
Hey y'all 👋 Thank you for taking the time to raise this, and for the ongoing discussion. It looks like this is a duplicate of #23110, which has quite a bit of additional discussion. We like to try to keep discussions centralized when possible, so we'll close this one in favor of #23110. If you feel we've done this in error, please do let us know.

**Closed by justinretzolk** 2022-02-14 22:54 UTC
Labels: bug, provider, authentication
