### ISSUE TITLE
[Bug]: experimental features in s3 module being ended in terraform 1.3.0

### ISSUE THREAD

**Issue by Irindul** [hashicorp/terraform-provider-aws#27382] opened 2022-10-21 15:29 UTC
### Terraform Core Version

1.3.0

### AWS Provider Version

4.35.0

### Expected Behavior

Nothing should change on the resources on terraform update. 

### Actual Behavior

The terraform init failed with error: 
```
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│ Error: Experiment has concluded
│ 
│   on .terraform/modules/bucket/aws/s3/main.tf line 2, in terraform:
│    2:   experiments = [module_variable_optional_attrs, ]
│ 
│ Experiment "module_variable_optional_attrs" is no longer available. The
│ final feature corresponding to this experiment differs from the
│ experimental form and is available in the Terraform language from Terraform
│ v1.3.0 onwards.
╵
```

### Terraform Configuration Files

```terraform
terraform {
  required_version = "1.3.0"

  backend "gcs" {
    bucket = "some-bucket
    prefix = "some-prefix"
  }

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.35.0"
    }
  }
}

provider "aws" {
  region = "eu-central-1"
}
```

### Steps to Reproduce

Use AWS provider in code. 
Upgrade terraform from 1.2.9 to 1.3.0

**Comment by justinretzolk** [comment] 2022-10-21 15:52
Hey @Irindul 👋 Thank you for taking the time to raise this! You're receiving that message because the experiment ended with version `1.3.0` of Terraform, [where that is now a native capability](https://github.com/hashicorp/terraform/blob/v1.3/CHANGELOG.md#130-september-21-2022). Since that feature is now native to Terraform, removing reference to it in the [`experiments` argument](https://developer.hashicorp.com/terraform/language/settings#experimental-language-features) will stop the error from being thrown.

Since this is expected behavior since the `1.3.0` release of Terraform, we'll close this issue for now. If you feel we've done this in error, please do let us know.

**Closed by justinretzolk** 2022-10-21 15:52 UTC
Labels: bug, needs-triage

**Comment by Irindul** [comment] 2022-10-24 08:12
Hello! Thanks for taking the time to answer. Indeed I went to fast Friday and misread the error. I thought it was coming from the provider code, but it was something we enabled on our side. 
Thanks again for the clarification :)
