### ISSUE TITLE
3.14.0 Regression: Error: InvalidParameter: 1 validation error(s) found. - minimum field size of 1, ListTargetsByRuleInput.EventBusName.

### ISSUE THREAD

**Issue by PaulDMendoza** [hashicorp/terraform-provider-aws#16069] opened 2020-11-06 01:32 UTC
Looks like 3.14.0 has a regression. 

My code deployment process which runs every couple hours just started failing today. I also noticed that an hour ago 3.14 of this package was released. I'm getting a bunch of these errors when I run a plan operation. This is blocking my deployments. I'll try and specify the old version of this package in my code but you should try and resolve this quickly. 

```
Error: InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, ListTargetsByRuleInput.EventBusName.
```

![image](https://user-images.githubusercontent.com/1039795/98315233-a049b680-1f8c-11eb-9a11-f41c0c4b2563.png)

![image](https://user-images.githubusercontent.com/1039795/98315169-785a5300-1f8c-11eb-962f-57ce6d1ad536.png)

**Comment by PaulDMendoza** [comment] 2020-11-06 02:00
Update: Specifying 3.13.0 let my Terraform Plan command and deployment work.

```
provider "aws" {
  version = "3.13.0"
  region  = var.region
}

```

**Comment by uncycler** [comment] 2020-11-06 02:10
I also experience this issue with version 3.14.0

**Comment by YuxuanLin** [comment] 2020-11-06 04:11
Same issue

**Comment by clevertime** [comment] 2020-11-06 04:27
we're having the same failure with 3.14.0 and using `aws_cloudwatch_event_target`

**Comment by Gooygeek** [comment] 2020-11-06 04:27
Same.
From what I can tell it appears to be the 'aws_cloudwatch_event_target' which is supposed to have a default value for 'event_bus_name' but instead throws an error.
#15922

**Comment by g-sree** [comment] 2020-11-06 05:00
I have the same error


Error: InvalidParameter: 1 validation error(s) found.
--
  | - minimum field size of 1, ListTargetsByRuleInput.EventBusName.
  |

**Comment by anwickes** [comment] 2020-11-06 05:59
Same error here guys....

Error: InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, ListTargetsByRuleInput.EventBusName.

**Comment by raj-yadav9** [comment] 2020-11-06 06:06
Error: InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, ListTargetsByRuleInput.EventBusName.

**Comment by g-sree** [comment] 2020-11-06 06:10
> I have the same error
> 
> ## Error: InvalidParameter: 1 validation error(s) found.
>   | - minimum field size of 1, ListTargetsByRuleInput.EventBusName.
>   |

I have pinned the previous version for now

```
provider "aws" {
  version = "~> 3.13.0"
  region  = var.aws_region

```

**Comment by bobmacks** [comment] 2020-11-06 06:27
Skipping 3.14.0 fixes my failing pipelines - and should allow for next version up
```
provider "aws" {
  version = "~> 3.0,!= 3.14.0"
  region  = var.aws_region
```

**Comment by lttmtins** [comment] 2020-11-06 10:01
Same for 3.15!

**Comment by hostmit** [comment] 2020-11-06 10:57
What's the root cause? What's to change in TFE?

**Comment by IMKnysh** [comment] 2020-11-06 11:48
@hostmit You can pin aws provider version

**Comment by remilapeyre** [comment] 2020-11-06 11:58
The bug is not triggered by the unit tests, could someone having an example that triggers it post it so it can be reproduced?

**Comment by arnvid** [comment] 2020-11-06 12:03
Root cause is:
```
resource"aws_lambda_permission""my-lambda-perms" {​​​​​​​​
statement_id  ="AllowExecutionFromCloudWatchEventsI"
action        ="lambda:InvokeFunction"
function_name =aws_lambda_function.my-lambda-functions.function_name
principal     ="events.amazonaws.com"
}​​​​​​​​

```

I changed it to:

```
resource"aws_lambda_permission""my-lambda-perms" {​​​​​​​​
statement_id  ="AllowExecutionFromCloudWatchEventsI"
action        ="lambda:InvokeFunction"
function_name =aws_lambda_function.my-lambda-functions.function_name
source_arn    =aws_cloudwatch_event_rule.config_my_event.arn
qualifier     =aws_lambda_alias.my-lambda-alias.name
}​​​​​​​​
```

Which includes the source_arn that should be there according to docs.. and also added the qualifier..
and I removed 3 things in the state to clean up the state to allow it to run:
tf state rm module.avm-baseline.aws_cloudwatch_event_target.config_my_event_target
tf state rm module.avm-baseline.aws_lambda_function.my-lambda-functions
tf state rm module.avm-baseline.aws_lambda_permission.my-lambda-perms

to force redeploy

**Comment by z0ph** [comment] 2020-11-06 12:10
Same issue here. fixed the provider version to "3.13.0"

**Comment by theophilechevalier** [comment] 2020-11-06 13:26
It seems the problem is linked to state migration from `3.13.x` to `3.14.0`

Simple example to reproduce:
```hcl
terraform {
  required_version = ">= 0.12"
}

provider "aws" {
  region  = "eu-central-1"
  version = "3.13.0"
}

resource "aws_cloudwatch_event_rule" "cloudwatch_event_is_alive" {
  name                = "cer-is_alive"
  description         = "Trigger lambda is alive every 1 minutes"
  schedule_expression = "rate(1 minute)"
  is_enabled          = true
}

resource "aws_cloudwatch_event_target" "cloudwatch_event_target_is_alive" {
  rule      = aws_cloudwatch_event_rule.cloudwatch_event_is_alive.name
  target_id = "lambda_is_alive"
  arn       = aws_lambda_function.test_lambda.arn
}

resource "aws_lambda_permission" "allow_cloudwatch_event_to_call_lamdba_is_alive" {
  statement_id  = "AllowExecutionFromCloudWatch"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.test_lambda.arn
  principal     = "events.amazonaws.com"
  source_arn    = aws_cloudwatch_event_rule.cloudwatch_event_is_alive.arn
}

resource "aws_iam_role" "iam_for_lambda" {
  name = "iam_for_lambda"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}

resource "aws_lambda_function" "test_lambda" {
  filename      = "exports.zip"
  function_name = "lambda_function_name"
  role          = aws_iam_role.iam_for_lambda.arn
  handler       = "exports.test"

  source_code_hash = data.archive_file.init.output_base64sha256

  runtime = "python3.8"
}

data "archive_file" "init" {
  type        = "zip"
  source_file = local_file.foo.filename
  output_path = "exports.zip"

  depends_on = [local_file.foo]
}

resource "local_file" "foo" {
  content  = "def test(): pass"
  filename = "exports.py"
}
```

```
$ terraform init
$ terraform apply -auto-approve
```

Change `version = "3.13.0"` to `version = "3.14.0"

```
$ terraform init
$ terraform plan
```

```
aws_iam_role.iam_for_lambda: Refreshing state... [id=iam_for_lambda]
aws_cloudwatch_event_rule.cloudwatch_event_is_alive: Refreshing state... [id=cer-is_alive]
aws_lambda_function.test_lambda: Refreshing state... [id=lambda_function_name]
aws_lambda_permission.allow_cloudwatch_event_to_call_lamdba_is_alive: Refreshing state... [id=AllowExecutionFromCloudWatch]
aws_cloudwatch_event_target.cloudwatch_event_target_is_alive: Refreshing state... [id=cer-is_alive-lambda_is_alive]

Error: InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, ListTargetsByRuleInput.EventBusName.
```

**Comment by bflad** [comment] 2020-11-06 13:51
Marking as 3.15.0, but we may release as 3.14.1.

**Comment by arnvid** [comment] 2020-11-06 13:51
I have been looking at the differences between the two state file version - the one where the error would be - and the one after I removed the conflicting entries from state and re-ran the workspace in TFE. There is no real change that shows a clear reason why this would happen. some objects are NULL in old state

**Comment by tcdev00** [comment] 2020-11-06 13:54
> Skipping 3.14.0 fixes my failing pipelines - and should allow for next version up
> 
> ```
> provider "aws" {
>   version = "~> 3.0,!= 3.14.0"
>   region  = var.aws_region
> ```

This worked for me too.

**Comment by arnvid** [comment] 2020-11-06 13:57
We would need to change this and re-run potentially 300 workspaces.

**Comment by kdubmartins** [comment] 2020-11-06 13:58
Happening to me as well, without lambdas nor cloudwatch-event resources. Error is thrown somewhere around refreshing of `aws_route53_record` resources. Falling back to 3.13.0 fixes it.

**Comment by yghern** [comment] 2020-11-06 15:04
Seems related to some names length. Provider 3.14 works perfectly fine for my resources with shorter names, fails for the same code but a few letters more in the name.
(fine) glue-crawler-event-compressed-sns-topic-dev
(fine) glue-crawler-event-compressed-sns-topic-test
(fail) glue-crawler-event-compressed-sns-topic-research
(fail) glue-crawler-event-compressed-sns-topic-staging
The resources that I am creating in the module are aws_cloudwatch_event_rule, aws_cloudwatch_event_target, and aws_sns_topic

**Comment by tburow** [comment] 2020-11-06 18:06
@bflad this is occurring for us on more then just Cloudwatch Event Target - seeing the error on multiple resources.

**Comment by bflad** [comment] 2020-11-06 18:08
@tburow can you please show the Terraform CLI output?

**Comment by tburow** [comment] 2020-11-06 18:20
> @tburow can you please show the Terraform CLI output?

disreguard - I think im getting scrambled up in teh debug output - I clearly see the event ones - the deeper down the list of the output the more scrabled/interleaved the errors and its not as clear.

**Comment by bflad** [comment] 2020-11-06 18:23
@tburow no worries. Hopefully a lot of that confusion will clear up when we go through the effort of https://github.com/hashicorp/terraform-provider-aws/issues/15892, which will enforce error messages from the AWS Go SDK to include some additional context, e.g. in this case `error reading CloudWatch Events Target (ID): {ERROR}`

**Comment by bflad** [comment] 2020-11-06 18:24
The fix for this has been merged and will release with version 3.14.1 of the Terraform AWS Provider, in the next 20-30 minutes. 👍

**Comment by tburow** [comment] 2020-11-06 18:24
2020-11-06T18:00:19.451Z [DEBUG] plugin.terraform-provider-aws_v3.14.0_x5: 2020/11/06 18:00:19 [DEBUG] [aws-sdk-go] DEBUG: Request sns/GetSubscriptionAttributes Details:
2020-11-06T18:00:19.451Z [DEBUG] plugin.terraform-provider-aws_v3.14.0_x5: ---[ REQUEST POST-SIGN ]-----------------------------
2020-11-06T18:00:19.451Z [DEBUG] plugin.terraform-provider-aws_v3.14.0_x5: POST / HTTP/1.1
2020-11-06T18:00:19.451Z [DEBUG] plugin.terraform-provider-aws_v3.14.0_x5: Host: sns.us-east-1.amazonaws.com
2020-11-06T18:00:19.451Z [DEBUG] plugin.terraform-provider-aws_v3.14.0_x5: User-Agent: aws-sdk-go/1.35.19 (go1.14.5; linux; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.12.28 (+https://www.terraform.io)
2020-11-06T18:00:19.451Z [DEBUG] plugin.terraform-provider-aws_v3.14.0_x5: Content-Length: 169
2020-11-06T18:00:19.451Z [DEBUG] plugin.terraform-provider-aws_v3.14.0_x5: Authorization: REDACTED
2020-11-06T18:00:19.451Z [DEBUG] plugin.terraform-provider-aws_v3.14.0_x5: Content-Type: application/x-www-form-urlencoded; charset=utf-8
2020-11-06T18:00:19.451Z [DEBUG] plugin.terraform-provider-aws_v3.14.0_x5: X-Amz-Date: 20201106T180019Z
2020-11-06T18:00:19.451Z [DEBUG] plugin.terraform-provider-aws_v3.14.0_x5: Accept-Encoding: gzip
2020-11-06T18:00:19.451Z [DEBUG] plugin.terraform-provider-aws_v3.14.0_x5: Action=GetSubscriptionAttributes&SubscriptionArn=arn%3Aaws%3Asns%3Aus-east-1%3A050439152187%3Araves-dev-glacier%REDACTED&Version=2010-03-31
2020-11-06T18:00:19.451Z [DEBUG] plugin.terraform-provider-aws_v3.14.0_x5: -----------------------------------------------------
2020-11-06T18:00:19.452Z [DEBUG] plugin.terraform-provider-aws_v3.14.0_x5: 2020/11/06 18:00:19 [DEBUG] [aws-sdk-go] DEBUG: Validate Request events/ListTargetsByRule failed, not retrying, error InvalidParameter: 1 validation error(s) found.
2020-11-06T18:00:19.452Z [DEBUG] plugin.terraform-provider-aws_v3.14.0_x5: - minimum field size of 1, ListTargetsByRuleInput.EventBusName.
2020-11-06T18:00:19.452Z [DEBUG] plugin.terraform-provider-aws_v3.14.0_x5: 2020/11/06 18:00:19 [DEBUG] [aws-sdk-go] DEBUG: Build Request events/ListTargetsByRule failed, not retrying, error InvalidParameter: 1 validation error(s) found.
2020-11-06T18:00:19.452Z [DEBUG] plugin.terraform-provider-aws_v3.14.0_x5: - minimum field size of 1, ListTargetsByRuleInput.EventBusName.
2020-11-06T18:00:19.452Z [DEBUG] plugin.terraform-provider-aws_v3.14.0_x5: 2020/11/06 18:00:19 [DEBUG] [aws-sdk-go] DEBUG: Sign Request events/ListTargetsByRule failed, not retrying, error InvalidParameter: 1 validation error(s) found.
2020-11-06T18:00:19.452Z [DEBUG] plugin.terraform-provider-aws_v3.14.0_x5: - minimum field size of 1, ListTargetsByRuleInput.EventBusName.
2020-11-06T18:00:19.452Z [DEBUG] plugin.terraform-provider-aws_v3.14.0_x5: 2020/11/06 18:00:19 [DEBUG] [aws-sdk-go] DEBUG: Validate Request events/ListTargetsByRule failed, not retrying, error InvalidParameter: 1 validation error(s) found.
2020-11-06T18:00:19.452Z [DEBUG] plugin.terraform-provider-aws_v3.14.0_x5: - minimum field size of 1, ListTargetsByRuleInput.EventBusName.
2020-11-06T18:00:19.452Z [DEBUG] plugin.terraform-provider-aws_v3.14.0_x5: 2020/11/06 18:00:19 [DEBUG] [aws-sdk-go] DEBUG: Build Request events/ListTargetsByRule failed, not retrying, error InvalidParameter: 1 validation error(s) found.
2020-11-06T18:00:19.452Z [DEBUG] plugin.terraform-provider-aws_v3.14.0_x5: - minimum field size of 1, ListTargetsByRuleInput.EventBusName.
2020-11-06T18:00:19.452Z [DEBUG] plugin.terraform-provider-aws_v3.14.0_x5: 2020/11/06 18:00:19 [DEBUG] [aws-sdk-go] DEBUG: Sign Request events/ListTargetsByRule failed, not retrying, error InvalidParameter: 1 validation error(s) found.
2020-11-06T18:00:19.452Z [DEBUG] plugin.terraform-provider-aws_v3.14.0_x5: - minimum field size of 1, ListTargetsByRuleInput.EventBusName.
~

**Closed** 2020-11-06 18:23 UTC
Labels: bug, regression, service/cloudwatchevents

**Comment by KyMidd** [comment] 2020-11-06 19:28
Confirm new version (3.14.1) fixed it for us. Thanks for jumping on this quickly team!
