### ISSUE TITLE
[Bug]: data "aws_db_instance" does not return correct values after changing TF version

### ISSUE THREAD

**Issue by rapides** [hashicorp/terraform-provider-aws#35595] opened 2024-02-01 10:00 UTC
### Terraform Core Version

1.7.2

### AWS Provider Version

4.6.7

### Affected Resource(s)

* aws_db_instance (data)

### Expected Behavior

Both attributes `engine` and `storage_encrypted` should return correct values. In my case it should be:
- engine -> `"postgres"`
- storage_encrypted -> `true`

### Actual Behavior

It returns something else and because of it TF plan wants to replace my DB instance.

<img width="995" alt="image" src="https://github.com/hashicorp/terraform-provider-aws/assets/2733755/0a507874-0717-4888-8d9c-ba82d13979ac">

<img width="839" alt="image" src="https://github.com/hashicorp/terraform-provider-aws/assets/2733755/8ff38e15-280e-4350-bca8-7073f8815a31">

### Terraform Configuration Files

```terraform
data "aws_db_instance" "primary" {
  db_instance_identifier = var.primary_db_identifier
}

locals {
  rds_identifier      = "name-${var.environment}-${data.aws_db_instance.primary.engine}-${var.name_identifier}"
  enabled_log_exports = ["postgresql", "upgrade"]
}

resource "aws_db_instance" "replica" {
  identifier = local.rds_identifier

  replicate_source_db          = data.aws_db_instance.primary.db_instance_identifier
  vpc_security_group_ids       = [aws_security_group.sg_rds_replica.id]
  instance_class               = var.db_instance_class
  storage_encrypted            = data.aws_db_instance.primary.storage_encrypted
  performance_insights_enabled = true
  skip_final_snapshot          = true
  deletion_protection          = true
  ca_cert_identifier           = "rds-ca-rsa2048-g1"

  tags = merge(var.tags, {
    Name = local.rds_identifier
  })

  depends_on = [
    aws_security_group.sg_rds_replica,
    // Log group must exist first, otherwise AWS will create it automatically,
    // and it will have to be imported to Terraform
    aws_cloudwatch_log_group.main
  ]
}
```

### Steps to Reproduce

1. Be on version 1.4.7 of Terraform and change to 1.7.2
2. See the attributes of `data.aws_db_instance` are not the same

### Important Factoids

I had a stable environment on TF version 1.4.7. After changing to 1.7.2 this data resource is not returning its attributes properly. Moreover, I changed the AWS provider version to the latest one and then I noticed that the `engine` attribute is properly returned, but no luck with `storage_encrypted`.

### Would you like to implement a fix?

None

**Comment by justinretzolk** [comment] 2024-03-13 21:32
Hey @rapides 👋 Thank you for taking the time to raise this! I'm not sure I follow where you're saying that the data source does not return data properly. Based on the screenshots provided, the values for those two arguments are marked as "known after apply". Given that these both have interpolations of `data.aws_db_instance`, I'd be curious to know how you're setting `var.primary_db_identifier`. I've often seen things like this caused by the behavior mentioned in [Data Resource Behavior](https://developer.hashicorp.com/terraform/language/data-sources#data-resource-behavior) where the data source read is being deferred until apply time.

**Comment by justinretzolk** [comment] 2024-07-23 21:02
Since we haven't heard back, I'm going to close this issue. If you're still having trouble, please feel free to open a new issue, referencing this one for context as needed.

**Closed by justinretzolk** 2024-07-23 21:02 UTC
Labels: bug, waiting-response, service/rds, needs-triage
