### ISSUE TITLE
[Bug]: `aws_wafv2_web_acl` description/tag changes result in inconsistent final plan

### ISSUE THREAD

**Issue by maxeaubrey** [hashicorp/terraform-provider-aws#27479] opened 2022-10-26 10:05 UTC
Related:
- #23390
- #23423
- #23936
- #23992
- #24386
- #27175
- #27273
- 👉 #27479
- #28191
- #28672
- #29012
- #29304
- #30858

### Terraform Core Version

1.3.3

### AWS Provider Version

4.36.1

### Affected Resource(s)

* aws_wafv2_web_acl

### Expected Behavior

It's possible to update tags and description of `aws_wafv2_web_acl` resources. 

After importing pre-existing rules (thanks to recently added support for `rate_based_statements`), we're met with `Provider produced inconsistent final plan` when just changing description and tags on the resource.

I don't believe `rate_based_statement` support is the culprit but I didn't investigate additional problems in depth.

### Actual Behavior

Any applies modifying the tags or description of an `aws_wafv2_web_acl` resource result in  `Provider produced inconsistent final plan`.

Modifying rules doesn't result in any errors.

### Relevant Error/Panic Output Snippet

```shell
Error: Provider produced inconsistent final plan

When expanding the plan for module.traefik.aws_wafv2_web_acl.public[0] to include new values learned so far during apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .rule: planned set element cty.ObjectVal(map[string]cty.Value{"action":cty.ListValEmpty(cty.Object(map[string]cty.Type{"allow":cty.List(cty.Object(map[string]cty.Type{"custom_request_handling":cty.List(cty.Object(map[string]cty.Type{"insert_header":cty.Set(cty.Object(map[string]cty.Type{"name":cty.String, "value":cty.String}))}))})), "block":cty.List(cty.Object(map[string]cty.Type{"custom_response":cty.List(cty.Object(map[string]cty.Type{"custom_response_body_key":cty.String, "response_code":cty.Number, "response_header":cty.Set(cty.Object(map[string]cty.Type{"name":cty.String, "value":cty.String}))}))})), "captcha":cty.List(cty.Object(map[string]cty.Type{"custom_request_handling":cty.List(cty.Object(map[string]cty.Type{"insert_header":cty.Set(cty.Object(map[string]cty.Type{"name":cty.String, "value":cty.String}))}))})), [... trimmed]
```

### Terraform Configuration Files

```
provider "aws" {}

resource "aws_wafv2_web_acl" "public" {
  name        = "Public"
  description = "Some ACL"
  scope       = "REGIONAL"

  default_action {
    allow {}
  }

  rule {
    name     = "rule0"
    priority = 0

    action {
      block {
        custom_response {
          response_code = 429
        }
      }
    }

    statement {
      rate_based_statement {
        aggregate_key_type = "IP"
        limit              = 100

        scope_down_statement {
          statement {
            byte_match_statement {
              search_string         = "example.com"
              positional_constraint = "EXACTLY"

              field_to_match {
                single_header {
                  name = "host"
                }
              }

              text_transformation {
                priority = 0
                type     = "NONE"
              }
            }
          }
        }
      }
    }

    visibility_config {
      cloudwatch_metrics_enabled = true
      metric_name                = "rule0"
      sampled_requests_enabled   = true
    }
  }

  visibility_config {
    cloudwatch_metrics_enabled = true
    metric_name                = "public"
    sampled_requests_enabled   = true
  }
}
```

### Steps to Reproduce

1. Create a wafv2_web_acl resource
2. Modify the description or tags in a subsequent terraform apply

### Important Factoids

We discovered this issue after importing rules (thanks to recently added rate_based_statement support) while changing the description, but after further testing the only consistent reason for failure were changes to the `description` field or new/changed tags. 

### References

- https://docs.aws.amazon.com/waf/latest/APIReference/API_UpdateWebACL.html
- #27113

**Comment by ewbankkit** [comment] 2022-10-26 11:37
Similar:

* https://github.com/hashicorp/terraform-provider-aws/issues/27273
* https://github.com/hashicorp/terraform-provider-aws/issues/27175

**Comment by aholthagerty** [comment] 2022-11-01 21:01
Same issue, I believe:  https://github.com/hashicorp/terraform-provider-aws/issues/23936

**Comment by a-schaefers** [comment] 2022-11-01 22:31
I can reproduce this bug as well.

**Comment by mmaetzler** [comment] 2022-11-04 23:36
FYI: This issues with WAFv2 has been reported multiple times: 

- #23390
- #23423
- #23936
- #23992
- #24386
- #27175
- #27273
- #27479

**Comment by emmaLP** [comment] 2022-11-14 11:24
This issue is still happening in version 4.39.0. Can we get an update please

**Comment by YakDriver** [comment] 2023-07-13 21:18
**NOTE:** I cannot reproduce this error after trying various configurations. _**Let us know**_ if this is still a problem! If we don't hear and can't reproduce, we plan to close this on or around **July 20, 2023**. The evidence suggests this is OBE (ie, fixed in the interim).

For more details see #23992 ([comment](https://github.com/hashicorp/terraform-provider-aws/issues/23992#issuecomment-1634920741)).

**Comment by justinretzolk** [comment] 2023-07-20 17:23
Hi all :wave: As was mentioned above, this issue appears to be fixed when using a minimum Terraform version of 1.4.2 and a minimum AWS Provider version of 4.67.0 (preferably Terraform 1.5.3 or later and AWS Provider 5.8.0 or later). If you experience additional unexpected behaviors with versions that meet these parameters, please open a new issue so that we can investigate further.

**Closed by justinretzolk** 2023-07-20 17:23 UTC
Labels: bug, waiting-response, service/wafv2
