### ISSUE TITLE
[Bug]: 2.70.2 does not install properly - error fetching

### ISSUE THREAD

**Issue by abower-digimarc** [hashicorp/terraform-provider-aws#28706] opened 2023-01-06 00:37 UTC
### Terraform Core Version

0.12.31

### AWS Provider Version

2.70.2

### Affected Resource(s)

We use atlantis to run terraform on github. Many of our projects specify "~> 2.0" for AWS provider version. This has worked fine, up through 3:40PM Pacific Time, just before 2.70.2 was released. Once that release happened, none of our plans would work. They all error with this message:

```
Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "github" (hashicorp/github) 4.9.4...
- Downloading plugin for provider "aws" (hashicorp/aws) 2.70.2...

Error installing provider "aws": failed to find downloaded plugin in cache /home/atlantis/.atlantis/plugin-cache/linux_amd64.

Error: failed to find downloaded plugin in cache /home/atlantis/.atlantis/plugin-cache/linux_amd64
```

We manually specify 2.70.1, and everything runs. It appears there's a problem with the download or binary itself, on 2.70.2

### Expected Behavior

The plugin should have downloaded and installed.

### Actual Behavior

Something failed in the plugin download/install, so the plugin wasn't found in the cache directory.

```
Error installing provider "aws": failed to find downloaded plugin in cache /home/atlantis/.atlantis/plugin-cache/linux_amd64.

Error: failed to find downloaded plugin in cache /home/atlantis/.atlantis/plugin-cache/linux_amd64


### Relevant Error/Panic Output Snippet

```shell
Error installing provider "aws": failed to find downloaded plugin in cache /home/atlantis/.atlantis/plugin-cache/linux_amd64.

Error: failed to find downloaded plugin in cache /home/atlantis/.atlantis/plugin-cache/linux_amd64
```

### Terraform Configuration Files

```hcl
terraform {
  required_version = "= 0.12.31"
}

provider "aws" {
  region  = var.region
  version = "2.70.1"
  profile = "evt-infracore"
}

provider "github" {
  owner = "EVRYTHNG"
  token = var.github_token
}

terraform {
  required_providers {
    github = {
      version = "4.9.4"
    }
  }
}
```

### Steps to Reproduce

have anything that specifies 

```hcl
provider "aws" {
  region  = var.region
  version = "~> 2.0"
  profile = "evt-infracore"
}
```

run `terraform init`.

### Would you like to implement a fix?

None

**Comment by tsingh-asapp** [comment] 2023-01-06 09:36
After the provider is been published recently the issue is been started.
https://registry.terraform.io/providers/hashicorp/aws/2.70.2
<img width="619" alt="image" src="https://user-images.githubusercontent.com/119655364/210973422-cdc85815-4ed7-421c-a25c-5835b26fa55f.png">

**Comment by ewbankkit** [comment] 2023-01-06 13:14
With this configuration:

```hcl
provider "aws" {
  version = "~> 2.0"
}

resource "aws_vpc" "test" {
  cidr_block = "10.1.0.0/16"

  tags = {
    Name = "ewbankkit-test-01-06-2023"
  }
}
```

##### Terraform CLI 1.0

```console
% terraform version
Terraform v1.0.9
on darwin_amd64
% terraform init

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/aws versions matching "~> 2.0"...
- Installing hashicorp/aws v2.70.2...
- Installed hashicorp/aws v2.70.2 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

╷
│ Warning: Version constraints inside provider configuration blocks are deprecated
│ 
│   on main.tf line 2, in provider "aws":
│    2:   version = "~> 2.0"
│ 
│ Terraform 0.13 and earlier allowed provider version constraints inside the provider configuration block, but that is now deprecated and will be removed
│ in a future version of Terraform. To silence this warning, move the provider version constraint into the required_providers block.
╵

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

##### Terraform CLI 0.13

```console
% terraform version
Terraform v0.13.7
% terraform init

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/aws versions matching "~> 2.0"...
- Installing hashicorp/aws v2.70.2...
- Installed hashicorp/aws v2.70.2 (signed by HashiCorp)

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

##### Terraform CLI 0.12

```console
% terraform version
Terraform v0.12.31
% terraform init 

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "aws" (hashicorp/aws) 2.70.2...

Error installing provider "aws": failed to find installed plugin version 2.70.2; this is a bug in Terraform and should be reported.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occurred.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/darwin_amd64


Error: failed to find installed plugin version 2.70.2; this is a bug in Terraform and should be reported
```

##### Terraform CLI 0.11

```console
% terraform version
Terraform v0.11.15
% terraform init

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "aws" (2.70.1)...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

**.N.B.** `v2.70.1` was installed in this case.

**Comment by ewbankkit** [comment] 2023-01-06 13:20
#### Terraform CLI 0.12

```console
% TF_LOG=DEBUG terraform init
2023/01/06 08:15:43 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
2023/01/06 08:15:43 [INFO] Terraform version: 0.12.31  
2023/01/06 08:15:43 [INFO] Go runtime version: go1.12.13
2023/01/06 08:15:43 [INFO] CLI args: []string{"/Users/ewbankkit/bin/terraform", "init"}
2023/01/06 08:15:43 [DEBUG] Attempting to open CLI config file: /Users/ewbankkit/.terraformrc
2023/01/06 08:15:43 Loading CLI configuration from /Users/ewbankkit/.terraformrc
2023/01/06 08:15:43 Loading CLI configuration from /Users/ewbankkit/.terraform.d/credentials.tfrc.json
2023/01/06 08:15:43 [INFO] CLI command args: []string{"init"}
2023/01/06 08:15:43 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----

Initializing the backend...
2023/01/06 08:15:43 [DEBUG] New state was assigned lineage "19614db6-09e0-2a16-a52c-cb9691ac40ee"
2023/01/06 08:15:43 [DEBUG] checking for provider in "."
2023/01/06 08:15:43 [DEBUG] checking for provider in "/Users/ewbankkit/bin"
2023/01/06 08:15:43 [DEBUG] checking for provisioner in "."
2023/01/06 08:15:43 [DEBUG] checking for provisioner in "/Users/ewbankkit/bin"
2023/01/06 08:15:43 [INFO] Failed to read plugin lock file .terraform/plugins/darwin_amd64/lock.json: open .terraform/plugins/darwin_amd64/lock.json: no such file or directory
2023/01/06 08:15:43 [DEBUG] checking for provider in "."
2023/01/06 08:15:43 [DEBUG] checking for provider in "/Users/ewbankkit/bin"

2023/01/06 08:15:43 [DEBUG] plugin requirements: "aws"="~> 2.0"
2023/01/06 08:15:43 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
Initializing provider plugins...
2023/01/06 08:15:43 [DEBUG] Service discovery for registry.terraform.io at https://registry.terraform.io/.well-known/terraform.json
- Checking for available provider plugins...
2023/01/06 08:15:44 [DEBUG] fetching provider versions from "https://registry.terraform.io/v1/providers/-/aws/versions"
2023/01/06 08:15:44 [DEBUG] GET https://registry.terraform.io/v1/providers/-/aws/versions
2023/01/06 08:15:44 [DEBUG] fetching provider location from "https://registry.terraform.io/v1/providers/hashicorp/aws/2.70.2/download/darwin/amd64"
2023/01/06 08:15:44 [DEBUG] GET https://registry.terraform.io/v1/providers/hashicorp/aws/2.70.2/download/darwin/amd64
2023/01/06 08:15:44 [DEBUG] verified GPG signature with key from HashiCorp Security (hashicorp.com/security) <security@hashicorp.com>
2023/01/06 08:15:44 [DEBUG] getting provider "aws" (hashicorp/aws) version "2.70.2"
2023/01/06 08:15:44 [DEBUG] plugin cache is disabled, so downloading aws 2.70.2 from https://releases.hashicorp.com/terraform-provider-aws/2.70.2/terraform-provider-aws_2.70.2_darwin_amd64.zip?checksum=sha256:726960b1e0014629d3e7cd73799e1e840c8dfa30cbc70c827adecd7823eb22a9
- Downloading plugin for provider "aws" (hashicorp/aws) 2.70.2...
2023/01/06 08:15:47 [DEBUG] looking for the aws 2.70.2 plugin we just installed
2023/01/06 08:15:47 [DEBUG] checking for provider in ".terraform/plugins/darwin_amd64"
2023/01/06 08:15:47 [WARN] found legacy provider "terraform-provider-aws_2.70.2"
2023/01/06 08:15:47 [DEBUG] all plugins found discovery.PluginMetaSet{discovery.PluginMeta{Name:"aws_2.70.2", Version:"0.0.0", Path:"/Users/ewbankkit/tmp/provider-v2.x/.terraform/plugins/darwin_amd64/terraform-provider-aws_2.70.2"}:struct {}{}}

2023/01/06 08:15:47 [DEBUG] filtered plugins discovery.PluginMetaSet{}
Error installing provider "aws": failed to find installed plugin version 2.70.2; this is a bug in Terraform and should be reported.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occurred.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/darwin_amd64


Error: failed to find installed plugin version 2.70.2; this is a bug in Terraform and should be reported
```

**Comment by HenriBlacksmith** [comment] 2023-01-06 14:34
Same issue occurring on our project starting today with Terrafom 0.12.31:

```shell
Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "aws" (hashicorp/aws) 2.70.2...

Installing provider "aws": failed to find installed plugin version 2.70.2; this is a bug in Terraform and should be reported.
Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occurred.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/linux_amd64

Error: failed to find installed plugin version 2.70.2; this is a bug in Terraform and should be reported
```

**Comment by breathingdust** [comment] 2023-01-06 16:08
Just update to say we are working on a resolution and hope to have an update for you very soon.

**Comment by ewbankkit** [comment] 2023-01-06 19:21
@CorbinGraham Yes, we are having some trouble trying to migrate a half-remembered, last used over a year ago, build process from TeamCity to GitHub Actions for this version of the provider 😄.
We seem to be missing an all-important space character somewhere!

**Comment by ewbankkit** [comment] 2023-01-06 20:45
Terraform AWS Provider [**v2.70.4**](https://registry.terraform.io/providers/hashicorp/aws/2.70.4) has been released and verified to install correctly with Terraform 0.11 and 0.12.

**Comment by ewbankkit** [comment] 2023-01-06 20:47
Closed via https://github.com/hashicorp/terraform-provider-aws/pull/28739.
Fixed via https://github.com/hashicorp/terraform-provider-aws/pull/28744.

**Closed by ewbankkit** 2023-01-06 20:47 UTC
Labels: bug, provider
