### ISSUE TITLE
IAM Access Control for Apache Kafka on Amazon MSK

### ISSUE THREAD

**Issue by danmcnulty** [hashicorp/terraform-provider-aws#19296] opened 2021-05-10 14:01 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please implement IAM Access Control for Apache Kafka on Amazon MSK which was recently released as described at https://aws.amazon.com/about-aws/whats-new/2021/05/introducing-iam-access-control-amazon-msk/

### New or Affected Resource(s)

* aws_msk_cluster

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* https://aws.amazon.com/about-aws/whats-new/2021/05/introducing-iam-access-control-amazon-msk/
* https://docs.aws.amazon.com/msk/latest/developerguide/iam-access-control.html

**Comment by ewbankkit** [comment] 2021-05-10 17:25
Duplicate of #19295.

**Closed by ewbankkit** 2021-05-10 17:25 UTC
Labels: enhancement, service/kafka
