### ISSUE TITLE
API Gateway v2 integration & route: ConflictException due to concurrent modification

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-aws#18018] opened 2021-03-10 13:50 UTC
Getting error when creating multiple `aws_apigatewayv2_integration` and  `aws_apigatewayv2_route` resources

```
error creating API Gateway v2 integration: ConflictException: Unable to complete operation due to concurrent modification. Please try again later.
```

```
error creating API Gateway v2 route: ConflictException: Unable to complete operation due to concurrent modification. Please try again later
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.6
AWS provider 3.24.0

### Affected Resource(s)

- aws_apigatewayv2_integration
- aws_apigatewayv2_route

### Terraform Configuration Files

```
resource "aws_apigatewayv2_integration" "lambda" {
  for_each               = local.lambda_resources
  api_id                 = aws_apigatewayv2_api.this.id
  credentials_arn        = aws_iam_role.api.arn
  integration_type       = "AWS_PROXY"
  connection_type        = "INTERNET"
  integration_method     = "POST"
  integration_uri        = each.value
  payload_format_version = "2.0"
}
```

```
resource "aws_apigatewayv2_route" "lambda" {
  for_each  = local.lambda_resources
  api_id    = aws_apigatewayv2_api.this.id
  route_key = "${each.value.method} ${each.value.endpoint}"
  target    = "integrations/${aws_apigatewayv2_integration.lambda[each.key].id}"
}
```

**Comment by ewbankkit** [comment] 2021-03-10 16:34
@dovydas-phrasee Thanks for raising this issue.
How many integrations are being created in parallel?

**Comment by dovydas-phrasee** [comment] 2021-03-10 17:02
@ewbankkit Around 30

**Comment by ewbankkit** [comment] 2021-03-10 21:17
I get no errors creating 30 integrations in parallel for a single API:

```
aws_apigatewayv2_integration.test[1]: Creating...
aws_apigatewayv2_integration.test[24]: Creating...
aws_apigatewayv2_integration.test[8]: Creating...
aws_apigatewayv2_integration.test[10]: Creating...
aws_apigatewayv2_integration.test[6]: Creating...
aws_apigatewayv2_integration.test[27]: Creating...
aws_apigatewayv2_integration.test[21]: Creating...
aws_apigatewayv2_integration.test[12]: Creating...
aws_apigatewayv2_integration.test[25]: Creating...
aws_apigatewayv2_integration.test[3]: Creating...
aws_apigatewayv2_integration.test[5]: Creating...
aws_apigatewayv2_integration.test[29]: Creating...
aws_apigatewayv2_integration.test[22]: Creating...
aws_apigatewayv2_integration.test[7]: Creating...
aws_apigatewayv2_integration.test[18]: Creating...
aws_apigatewayv2_integration.test[15]: Creating...
aws_apigatewayv2_integration.test[20]: Creating...
aws_apigatewayv2_integration.test[17]: Creating...
aws_apigatewayv2_integration.test[13]: Creating...
aws_apigatewayv2_integration.test[11]: Creating...
aws_apigatewayv2_integration.test[14]: Creating...
aws_apigatewayv2_integration.test[28]: Creating...
aws_apigatewayv2_integration.test[26]: Creating...
aws_apigatewayv2_integration.test[4]: Creating...
aws_apigatewayv2_integration.test[16]: Creating...
aws_apigatewayv2_integration.test[19]: Creating...
aws_apigatewayv2_integration.test[9]: Creating...
aws_apigatewayv2_integration.test[23]: Creating...
aws_apigatewayv2_integration.test[2]: Creating...
aws_apigatewayv2_integration.test[0]: Creating...
aws_apigatewayv2_integration.test[8]: Creation complete after 0s [id=8tat3ai]
aws_apigatewayv2_integration.test[24]: Creation complete after 0s [id=piif7ak]
aws_apigatewayv2_integration.test[1]: Creation complete after 2s [id=qs76lrn]
aws_apigatewayv2_integration.test[25]: Creation complete after 1s [id=qqoarni]
aws_apigatewayv2_integration.test[27]: Creation complete after 1s [id=p3x8si4]
aws_apigatewayv2_integration.test[21]: Creation complete after 1s [id=1cp3yx9]
aws_apigatewayv2_integration.test[12]: Creation complete after 1s [id=ze1952f]
aws_apigatewayv2_integration.test[3]: Creation complete after 1s [id=ecfw9rh]
aws_apigatewayv2_integration.test[7]: Creation complete after 1s [id=9l5h8kj]
aws_apigatewayv2_integration.test[10]: Creation complete after 1s [id=6mp1qze]
aws_apigatewayv2_integration.test[6]: Creation complete after 1s [id=k7xydv3]
aws_apigatewayv2_integration.test[11]: Creation complete after 1s [id=yrd1h78]
aws_apigatewayv2_integration.test[22]: Creation complete after 1s [id=h8gkcvr]
aws_apigatewayv2_integration.test[17]: Creation complete after 1s [id=di979ym]
aws_apigatewayv2_integration.test[14]: Creation complete after 1s [id=achqvu1]
aws_apigatewayv2_integration.test[28]: Creation complete after 1s [id=zjv5kck]
aws_apigatewayv2_integration.test[5]: Creation complete after 1s [id=wijbomi]
aws_apigatewayv2_integration.test[13]: Creation complete after 1s [id=0r5tzr2]
aws_apigatewayv2_integration.test[16]: Creation complete after 1s [id=meil19d]
aws_apigatewayv2_integration.test[26]: Creation complete after 1s [id=eqzg6hm]
aws_apigatewayv2_integration.test[29]: Creation complete after 1s [id=9e8an0r]
aws_apigatewayv2_integration.test[19]: Creation complete after 1s [id=pqyq93n]
aws_apigatewayv2_integration.test[20]: Creation complete after 1s [id=fqmu575]
aws_apigatewayv2_integration.test[15]: Creation complete after 1s [id=y3vzc7f]
aws_apigatewayv2_integration.test[4]: Creation complete after 1s [id=vn9vnjm]
aws_apigatewayv2_integration.test[23]: Creation complete after 1s [id=r2amamr]
aws_apigatewayv2_integration.test[2]: Creation complete after 1s [id=zbsslb2]
aws_apigatewayv2_integration.test[0]: Creation complete after 1s [id=wu9h0dv]
aws_apigatewayv2_integration.test[9]: Creation complete after 1s [id=ek7epw2]
aws_apigatewayv2_integration.test[18]: Creation complete after 1s [id=i6gmi8g]
```

@dovydas-phrasee You could try lowering the [parallelism](https://www.terraform.io/docs/cli/commands/apply.html#parallelism-n) value for `terraform apply`.

**Comment by dovydas-phrasee** [comment] 2021-03-12 09:42
@ewbankkit tried to lower parallelism to 5, but it didn't help. And got error for creating `aws_apigatewayv2_route`
```
error creating API Gateway v2 route: ConflictException: Unable to complete operation due to concurrent modification. Please try again later

```

**Comment by alexjurkiewicz** [comment] 2021-03-26 04:50
There is a similar restriction with AppSync APIs (#16211). I am interested in contributing to a solution here. I believe the provider could implement a per-api-id semaphore to prevent concurrent access.

This solution seems novel in the codebase, so I would like maintainer feedback about the best approach 🙏

**Comment by Burnett2k** [comment] 2021-07-20 15:41
I am experiencing a similar issue when trying to create `aws_apigatewayv2_route`. In my case, we have a module that allows a map of routes to be passed in, which are then created using a `for_each`. We are seeing about a 40% failure rate with the error below. Sometimes it works flawlessly, other times it fails. It is very intermittent which also makes it hard to reproduce consistently.

```
error creating API Gateway v2 route: ConflictException: Unable to complete operation due to concurrent modification. Please try again later
```

It appears a similar issue was fixed for apigatewayv1 by adding retry logic here: https://github.com/hashicorp/terraform-provider-aws/blob/5e6e4dfee3c1e97336cb996fffe4fbf4a5270134/aws/config.go#L679-L686

Could we potentially add that same fix for apigatewayv2?

**Comment by okdana** [comment] 2021-09-17 17:38
I'm also seeing this, with `aws` 3.57. I have less than a dozen routes+integrations being created from a map by a [module](https://github.com/terraform-aws-modules/terraform-aws-apigateway-v2), and i get one to three `ConflictException`s like this for the integrations at least half the time i try to `apply`. Adding `-parallelism=1` seems to work around it 100% of the time, though i wouldn't say my testing has been exhaustive yet.

I think the v1 fix mentioned in the previous comment is related to the nearly identical issue #16439.

**Comment by DanyC97** [comment] 2021-11-01 18:46
okay so it looks like i've managed to find out the [PR](https://github.com/hashicorp/terraform-provider-aws/pull/13497) which wasn't added in the changelog  followed by another commit https://github.com/hashicorp/terraform-provider-aws/commit/d906813c60bd8f5b664849498932f4473c4105fe

**Comment by DanyC97** [comment] 2021-11-09 21:33
@maryelizbeth 👋  sorry to tag you directly, by a long shot is anything you or anyone in your team get this issue back on the radar ?

Nowadays a lot of folks are using either v1 or v2 of the API GW and i'm very much surprised that up until now this issue hasn't been a priority.

Would appreciate if the priority gets bumped  (i'm not there yet to contribute , otherwise i would have done it already as spent 2 weeks fighting with this issue)

**Comment by si3mshady** [comment] 2021-12-07 01:21
Seeing the same error when trying to create a simple serverless function with a custom authorizer. This is a bad bug. 



   Resource handler returned    
                                                                                             message: "Unable to complete 
                                                                                             operation due to concurrent  
                                                                                             modification. Please try     
                                                                                             again later. (Service:       
                                                                                             ApiGateway, Status Code:     
                                                                                             409, Request ID: fa501120-9c 
                                                                                             3f-4efa-90c0-355bc14c00cb,   
                                                                                             Extended Request ID: null)"  
                                                                                             (RequestToken: 93f797df-     
                                                                                             fe7d-5e0d-9d16-287af48122e7, 
                                                                                             HandlerErrorCode:            
                                                                                             AlreadyExists)                                  The following resource(s)    
                                                                                             failed to create:            
                                                                                             [CustomAuthorizer]. Rollback 
                                                                                             requested by user.

**Comment by dgrushkin-techstack** [comment] 2022-01-10 11:16
Hey guys, any ETA about this fix?

**Comment by hajdukd** [comment] 2022-03-31 12:38
Also an issue for private service integrations :/ Please give ETA for the fix?

**Comment by andrey-clearscale** [comment] 2022-08-29 07:52
The same issue with aws_apigatewayv2_api_mapping

**Comment by zjalicf-cyberlab** [comment] 2023-02-27 13:11
Hi guys, I am also getting 
`creating API Gateway v2 integration: ConflictException: Unable to complete operation due to concurrent modification. Please try again later.`

```
module.api_gateway.aws_apigatewayv2_integration.this["PATCH /{proxy+}"]: Creating...
module.api_gateway.aws_apigatewayv2_integration.this["POST /{proxy+}"]: Creating...
module.api_gateway.aws_apigatewayv2_integration.this["DELETE /{proxy+}"]: Creating...
module.api_gateway.aws_apigatewayv2_integration.this["OPTIONS /xyz"]: Creating...
module.api_gateway.aws_apigatewayv2_integration.this["POST /xyz"]: Creating...
module.api_gateway.aws_apigatewayv2_integration.this["OPTIONS /{proxy+}"]: Creating...
module.api_gateway.aws_apigatewayv2_integration.this["GET /{proxy+}"]: Creating...
module.api_gateway.aws_apigatewayv2_integration.this["DELETE /{proxy+}"]: Creation complete after 1s [id=gyl0mnl]
module.api_gateway.aws_apigatewayv2_integration.this["POST /{proxy+}"]: Creation complete after 1s [id=5d787ga]
module.api_gateway.aws_apigatewayv2_integration.this["GET /{proxy+}"]: Creation complete after 1s [id=nbs78ys]
module.api_gateway.aws_apigatewayv2_integration.this["POST /xyz"]: Creation complete after 1s [id=iwszqfo]
module.api_gateway.aws_apigatewayv2_integration.this["OPTIONS /{proxy+}"]: Creation complete after 1s [id=ko65n7t]
module.api_gateway.aws_apigatewayv2_integration.this["OPTIONS /xyz"]: Creation complete after 1s [id=z62zgam]
╷
│ Error: creating API Gateway v2 integration: ConflictException: Unable to complete operation due to concurrent modification. Please try again later.
│ 
│   with module.api_gateway.aws_apigatewayv2_integration.this["PATCH /{proxy+}"],
│   on .terraform/modules/api_gateway/main.tf line 143, in resource "aws_apigatewayv2_integration" "this":
│  143: resource "aws_apigatewayv2_integration" "this" {
│ 
```

This should be fixed...

**Comment by remil1000** [comment] 2023-02-28 07:47
I think the related commit that was implemented for API Gateway v1 (and REST API) is this one https://github.com/hashicorp/terraform-provider-aws/commit/d906813c60bd8f5b664849498932f4473c4105fe
it has been shuffled around since and the piece of code is now located here https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/conns/config.go#L261

I'm not familiar with AWS Go SDK internals nor Terraform handlers but would it be possible to use something very similar for API Gateway v2 by importing `github.com/aws/aws-sdk-go/service/apigatewayv2` in `internal/conns/config.go` and then adding the following right next to https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/conns/config.go#L261 

```
client.apigatewayv2.Handlers.Retry.PushBack(func(r *request.Request) {
	if tfawserr.ErrMessageContains(r.Error, apigatewayv2.ErrCodeConflictException, "try again later") {
		r.Retryable = aws.Bool(true)
	}
})
```

it seems the apigatewayv2 package in AWS Go SDK implements the exact same Exception
https://github.com/aws/aws-sdk-go/blob/main/service/apigatewayv2/errors.go#L28
vs
https://github.com/aws/aws-sdk-go/blob/main/service/apigateway/errors.go#L23

**Closed** 2023-03-10 15:57 UTC
Labels: enhancement, service/apigatewayv2
