### ISSUE TITLE
Launch template version not changed since new provider version 3.68

### ISSUE THREAD

**Issue by sbroix** [hashicorp/terraform-provider-aws#22032] opened 2021-12-03 08:45 UTC
Hello, 

Since the new provider release (3.68), when a launch template version need to be updated (user data updated, AMI...). The update of version is not noticed during the apply. 

In case of an auto-scaling group attached to the last version of the launch template, this is a problem because during the apply, the auto-scaling group will not automatically select the last version anymore. We are obligated to launch a second apply to work.

It was working with the previous version (3.67), and I don't see any modifications about launch templates in this release, so I conclude this is a bug.

Screen attached to show the problem  :
On the first screen, you can see a change in the user-data, and terraform notify a change of default_version/last_version. In addition, the auto-scaling group is automatically updated with the new version (this is a terraform action with AWS provider 3.67)
<img width="952" alt="Screenshot 2021-12-03 at 09 50 42" src="https://user-images.githubusercontent.com/52855175/144573652-7056d626-ec18-474f-ae51-0fd316bb61d0.png">

And now the same terraform configuration but with the AWS provider 3.68. Only the launch template is updated, and it is not noticed the version update (in this case, I need to launch a second apply to update the auto-scaling-group): 
<img width="927" alt="Screenshot 2021-12-03 at 09 51 25" src="https://user-images.githubusercontent.com/52855175/144573760-786d1832-305e-4dd6-b6d3-522ae603ae13.png">

Here is the code: 
`
resource "aws_launch_template" "ECSLaunchTemplate" {
  name                                = "hv-ecs-cluster"
  image_id                          = "ami-12345"
  instance_type                 = "t3.xlarge"
  update_default_version = true
  user_data                        = base64encode(data.template_file.user_data.rendered)
}
`

**Comment by camaeel** [comment] 2021-12-03 08:51
Looks like a duplicate of https://github.com/hashicorp/terraform-provider-aws/issues/22015

**Comment by ewbankkit** [comment] 2021-12-03 12:29
@sbroix Thanks for raising this issue.
It has already been noticed in #22015. I'm going to close this one as a duplicate so that we can concentrate discussion in the linked issue.
Please add any additional comments there.

**Closed by ewbankkit** 2021-12-03 12:29 UTC
Labels: bug, service/ec2
