### ISSUE TITLE
[Docs]: resource aws_eks_cluster has an argument bootstrap_cluster_creator_admin_permissions with incorrect default

### ISSUE THREAD

**Issue by TheLastRedNinja** [hashicorp/terraform-provider-aws#38185] opened 2024-06-28 16:02 UTC
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#bootstrap_cluster_creator_admin_permissions

### Description

The argument `bootstrap_cluster_creator_admin_permissions` is said to have the default value of `true`. 
Upon inspection the value in fact has the default value of `false`  

### References

N/A

### Would you like to implement a fix?

None

**Comment by stefanfreitag** [comment] 2024-06-29 12:14
Hi @TheLastRedNinja,

is this a potential duplicate of #36259 ?

**Comment by justinretzolk** [comment] 2024-07-02 14:54
Duplicate of #36259

**Closed by justinretzolk** 2024-07-02 14:54 UTC
Labels: documentation, service/eks, needs-triage
