### ISSUE TITLE
[Bug]: Plugin crashed when trying to import Lightsail Instances

### ISSUE THREAD

**Issue by elliotrpage** [hashicorp/terraform-provider-aws#37470] opened 2024-05-13 13:49 UTC
### Terraform Core Version

1.8.3

### AWS Provider Version

5.49.0

### Affected Resource(s)

aws_lightsail_instance

### Expected Behavior

A terraform file generated by the import process would have been created.

### Actual Behavior

Plugin crashed, threw an error. Full error text below.

### Relevant Error/Panic Output Snippet

```shell
aws_lightsail_instance.wordpress_dev: Preparing import... [id=WP_Lamp-Dev]
aws_lightsail_instance.wordpress_prod: Preparing import... [id=WP_Lamp-Prod]
aws_lightsail_instance.wordpress_uat: Preparing import... [id=WP_Lamp-UAT]
aws_lightsail_instance.wordpress_dev: Refreshing state... [id=WP_Lamp-Dev]
aws_lightsail_instance.wordpress_uat: Refreshing state... [id=WP_Lamp-UAT]
aws_lightsail_instance.wordpress_prod: Refreshing state... [id=WP_Lamp-Prod]

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-aws_v5.49.0_x5.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x1453ea4]

goroutine 88 [running]:
github.com/hashicorp/terraform-provider-aws/internal/tags.(*TagData).ValueString(...)
        github.com/hashicorp/terraform-provider-aws/internal/tags/key_value_tags.go:629
github.com/hashicorp/terraform-provider-aws/internal/tags.KeyValueTags.ResolveDuplicates(0x1e58ece0, {0x1343abb8, 0x1f7a04e0}, 0x0, 0x0, {0x3eb92590, 0x1e764690})
        github.com/hashicorp/terraform-provider-aws/internal/tags/key_value_tags.go:738 +0x154
github.com/hashicorp/terraform-provider-aws/internal/provider.tagsResourceInterceptor.run({0x1db32d90, 0x119cb014, 0x119cb010}, {0x1343abb8, 0x1f7a04e0}, {0x13456ba8, 0x1e764690}, {0x1163af20, 0x1e5d82a0}, 0x2, ...)
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:365 +0xb47
github.com/hashicorp/terraform-provider-aws/internal/provider.New.(*wrappedResource).Read.interceptedHandler[...].func9(0x1e764690, {0x1163af20, 0x1e5d82a0})
        github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:122 +0x37c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x1dfa2fc0, {0x1343abb8, 0x1f73bcc8}, 0x1e764690, {0x1163af20, 0x1e5d82a0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:790 +0x7e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x1dfa2fc0, {0x1343abb8, 0x1f73bcc8}, 0x1e75afc0, {0x1163af20, 0x1e5d82a0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/resource.go:1089 +0x538
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x1e57dc00, {0x1343abb8, 0x1f73bc38}, 0x1e74b8c0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/grpc_provider.go:667 +0x4e0
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ReadResource(0x1dc7e0f0, {0x1343abb8, 0x1f73b968}, 0x1e74b8c0)
        github.com/hashicorp/terraform-plugin-mux@v0.15.0/tf5muxserver/mux_server_ReadResource.go:35 +0x1d6
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x1da7e190, {0x1343abb8, 0x1f73aff0}, 0x1de8e360)
        github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov5/tf5server/server.go:775 +0x4c8
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1154c360, 0x1da7e190}, {0x1343abb8, 0x1f73aff0}, 0x1d8c6800, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:482 +0x98
google.golang.org/grpc.(*Server).processUnaryRPC(0x1d5b3408, {0x1343abb8, 0x1f73af60}, {0x134583f4, 0x1d982368}, 0x1fadfa28, 0x1e682390, 0x1b7bbd74, 0x0)
        google.golang.org/grpc@v1.63.2/server.go:1369 +0xf44
google.golang.org/grpc.(*Server).handleStream(0x1d5b3408, {0x134583f4, 0x1d982368}, 0x1fadfa28)
        google.golang.org/grpc@v1.63.2/server.go:1780 +0x10cf
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.63.2/server.go:1019 +0xaa
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 37
        google.golang.org/grpc@v1.63.2/server.go:1030 +0x12f

Error: The terraform-provider-aws_v5.49.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Terraform Configuration Files

import {
  to = aws_lightsail_instance.wordpress_dev
  id = "WP_Lamp-Dev"
}

import {
  to = aws_lightsail_instance.wordpress_uat
  id = "WP_Lamp-UAT"
}

import {
  to = aws_lightsail_instance.wordpress_prod
  id = "WP_Lamp-Prod"
}

### Steps to Reproduce

Run terraform plan -generate-config-out=generated.tf
Error is thrown

### Would you like to implement a fix?

No

**Comment by acwwat** [comment] 2024-05-14 03:17
Duplicate of https://github.com/hashicorp/terraform-provider-aws/issues/32430.

**Closed** 2024-05-24 18:52 UTC
Labels: bug, crash, service/lightsail
