### ISSUE TITLE
aws_appstream_image_builder throws error with empty domain_join_info

### ISSUE THREAD

**Issue by jhancock93** [hashicorp/terraform-provider-aws#26677] opened 2022-09-07 01:36 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v1.2.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.29.0
+ provider registry.terraform.io/hashicorp/external v2.2.2
+ provider registry.terraform.io/hashicorp/local v2.2.3
+ provider registry.terraform.io/hashicorp/null v3.1.1
+ provider registry.terraform.io/hashicorp/random v3.4.2
+ provider registry.terraform.io/hashicorp/time v0.8.0

### Affected Resource(s)

* aws_appstream_image_builder

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_appstream_image_builder" "image_builder" {
  # Image Builder only needs to be created in nonprod and the created image can be shared with prod account
  count                          = var.create_appstream_image_builder ? 1 : 0
  name                           = "My-Image-Builder"
  description                    = "AppStream Image Builder"
  display_name                   = "AppStream Image Builder"
  enable_default_internet_access = false
  image_name                     = "My Image Builder"
  instance_type                  = "stream.standard.medium"

  vpc_config {
    security_group_ids = [module.appstream_sg.security_group_id]
    subnet_ids         = [local.primary_private_subnet_ids[0]]
  }
}
```

### Debug Output
│ Error: error setting `domain_join_info` for AppStream ImageBuilder (My-Image-Builder): domain_join_info: '': source data must be an array or slice, got map
│ 
│   with module.persistent.aws_appstream_image_builder.image_builder[0],
│   on ../../modules/persistent/appstream.tf line 6, in resource "aws_appstream_image_builder" "image_builder":
│    6: resource "aws_appstream_image_builder" "image_builder" {

### Expected Behavior

AppStream Image Builder should be created without errors

### Actual Behavior

AppStream image builder resource fails during terraform plan phase with:
```error domain_join_info: '': source data must be an array or slice, got map```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

This error did not occur with hashicorp aws provider version v4.20.0

### References

* #0000

**Comment by justinretzolk** [comment] 2022-09-13 17:48
Similar to #24798, which was fixed by #26454.

**Comment by jhancock93** [comment] 2022-09-25 22:49
> Similar to #24798, which was fixed by #26454.

This still doesn't seem to be resolved with latest provider version (v4.32.0)

**Comment by justinretzolk** [comment] 2022-11-03 18:43
Hey @jhancock93 👋 Thank you for following up. I see my mistake now in that the linked issue/PR were for the `aws_appstream_fleet` resource, despite the issue referencing `aws_appstream_image_builder`. Since you mentioned you didn't run into this with version `4.20.0`, I'll mark this as a regression as well.

**Comment by braun1928** [comment] 2022-11-15 14:15
@justinretzolk I created a branch with small changes that fix this, if you want to check out the [diff](https://github.com/hashicorp/terraform-provider-aws/compare/main...braun1928:terraform-provider-aws:b-appstream_image-domain_join_info-vpc_config).

I was attempting to create a test for it as well, but my AWS access is very limited and I can't create the necessary resources to complete it.

**Comment by PatriQ1414** [comment] 2022-11-16 11:43
I am still facing this error in v4.39.0
Any workaround?

**Comment by PatriQ1414** [comment] 2022-11-16 11:51
> I am still facing this error in v4.39.0 Any workaround?

Downgraded to 4.28 and still getting the same error

**Comment by nngabriel** [comment] 2022-11-25 19:42
I'm experiencing the same issue with v4.41.0.

**Comment by tjames-stig** [comment] 2022-12-05 22:40
I've identified 4d802fe269dd40d80582161cbe52e23f0ed9169b as the commit which introduced the regression, but I don't know enough about the release cycles to tell what version of the provider needs to be downgraded to as a workaround.

**Comment by pureiboi** [comment] 2022-12-06 12:21
I have identified this section of code is causing the issue, 

the method in **image_builder.go**

`func resourceImageBuilderRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
`

```
	if err = d.Set("domain_join_info", flattenDomainInfo(imageBuilder.DomainJoinInfo)); err != nil {
		return diag.FromErr(fmt.Errorf("error setting `%s` for AppStream ImageBuilder (%s): %w", "domain_join_info", d.Id(), err))
	}

	if err = d.Set("vpc_config", flattenVPCConfig(imageBuilder.VpcConfig)); err != nil {
		return diag.FromErr(fmt.Errorf("error setting `%s` for AppStream ImageBuilder (%s): %w", "vpc_config", d.Id(), err))
	}

```

both **domain_join_info** and **vpc_config** is throwing error:

after the section of code setting domain_join_info is removed, below will surface for vpc_config. 


`│ Error: error setting `vpc_config` for AppStream ImageBuilder (linux-image-builder-test-tf): vpc_config: '': source data must be an array or slice, got map`


I may be able to help, however with limited knowledge on golang and code structure,  need more time on this.

**Comment by liamraeAL** [comment] 2023-01-04 16:27
Any update on this? Still blocking our development.

**Comment by nngabriel** [comment] 2023-01-04 19:38
Is there a way to push this? or collaborate to make it happen?

**Comment by tjames-stig** [comment] 2023-01-10 18:38
I've got a PR up and linked to this, with all the appropriate acceptance testing performed. I would be happy to help out and do whatever is needed to make my PR viable for merging.

**Closed** 2023-01-17 17:55 UTC
Labels: bug, regression, service/appstream
