### ISSUE TITLE
aws_glue_partition_index fails to create and causes state inconsistency for pre-existing tables with a large number of partitions

### ISSUE THREAD

**Issue by jlundstedt** [hashicorp/terraform-provider-aws#22910] opened 2022-02-02 22:15 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.4 using AWS provider v3.74.0

### Affected Resource(s)

* `aws_glue_partition_index`

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Above a standard table is created in the database and a large number of partitions is added externally

# Improve query performance by indexing partitions
resource "aws_glue_partition_index" "my_index" {
  database_name = "my_database"
  table_name    = aws_glue_catalog_table.data_table.name

  partition_index {
    index_name = "my-index"
    keys       = ["column1", "column2"]
  }
}
```

Repurposing the [example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/glue_partition_index) to point to a real Glue table with a large number of partitions (about 250,000 in our case), should suffice.

### Debug Output

This Terraform runs in a CI pipeline where I cannot presently enable debugging.

### Expected Behavior

Terraform initiates the resource creation, and adds the resource to the state once its creation has been successfully initiated. I suppose it could also wait, but AWS documents the resource can take a [long time](https://aws.amazon.com/blogs/big-data/improve-query-performance-using-aws-glue-partition-indexes/) to create:

> The Status column of the newly created partition index shows the status as Creating. Wait for the partition index to be Active. The process takes about 1 hour because more number of partitions longer it takes for index creation and we have 367,920 partitions on this table.

### Actual Behavior

Terraform errors out via a timeout:

```
Error: error while waiting for Glue Partition Index (<account_id>:<database>:<table>:<index>) to become available: timeout while waiting for state to become 'ACTIVE' (last state: 'CREATING', timeout: 2m0s)
  with module.my_module.aws_glue_partition_index.my_partition_index,
  on ../../my-app/main.tf line 203, in resource "aws_glue_partition_index" "my_partition_index":
 203: resource "aws_glue_partition_index" "my_partition_index" {
```

After the partition index is created successfully on the AWS side, applies error out because Terraform does not import the already created resource:

```
module.my_module.aws_glue_partition_index.my_partition_index: Creating...
Error: error creating Glue Partition Index: AlreadyExistsException: Partition Index <index> already exists with the same name.
  with module.my_module.aws_glue_partition_index.my_partition_index,
  on ../../my-app/main.tf line 203, in resource "aws_glue_partition_index" "my_partition_index":
 203: resource "aws_glue_partition_index" "my_partition_index" {
```

The only way to recover from this to a successful `terraform apply` is to manually import the resource into the state.

### Steps to Reproduce

1. `terraform apply`
2. Observe failure
3. Rerun `terraform apply`
4. Observe second failure which is reproducible indefinitely.

### Important Factoids

* Bug is only reproducible against a table with a large number of partitions, such as a table containing organizational CloudTrail data for a large AWS Organization. The failure was observed in the real world against a table with roughly 250,000 partitions.

### References

* All referenced inline above.

**Comment by jlundstedt** [comment] 2022-02-02 22:20
Looks like @TDanielsHL reported this in #22908 just a few hours ago as an enhancement request. However, I would tend to consider this more of a bug, since Terraform can't automatically recover from this failure.

**Comment by TDanielsHL** [comment] 2022-02-03 00:19
> Looks like @TDanielsHL reported this in #22908 just a few hours ago as an enhancement request. However, I would tend to consider this more of a bug, since Terraform can't automatically recover from this failure.

I'm OK with classifying it however the experts decide, but I took the presence of timeout meta-arguments to be an optional feature as opposed to something standard.

Using Terraform for this provisioning is great, just need it to be reliable!

**Comment by DrFaust92** [comment] 2022-02-04 06:35
Duplicate of https://github.com/hashicorp/terraform-provider-aws/issues/22908

**Closed by DrFaust92** 2022-02-04 06:35 UTC
Labels: service/glue, needs-triage
