### ISSUE TITLE
[Bug]: │ This is a bug in the provider, which should be reported in the provider's own issue tracker.

### ISSUE THREAD

**Issue by chrisolido** [hashicorp/terraform-provider-aws#38461] opened 2024-07-22 02:55 UTC
### Terraform Core Version

0.9.1

### AWS Provider Version

5.59.0

### Affected Resource(s)

Circle CI

### Expected Behavior

Should run the release smoothly 

### Actual Behavior

│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵

Exited with code exit status 1

### Relevant Error/Panic Output Snippet

```shell
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.crs.aws_ecs_task_definition.taskDefinition to include new values learned so far during apply
```

### Terraform Configuration Files

│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.crs.aws_ecs_task_definition.taskDefinition to include new values learned so far during apply

### Steps to Reproduce

│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.crs.aws_ecs_task_definition.taskDefinition to include new values learned so far during apply

### Debug Output

│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.crs.aws_ecs_task_definition.taskDefinition to include new values learned so far during apply

### Panic Output

│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.crs.aws_ecs_task_definition.taskDefinition to include new values learned so far during apply

### Important Factoids

│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.crs.aws_ecs_task_definition.taskDefinition to include new values learned so far during apply

### References

│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.crs.aws_ecs_task_definition.taskDefinition to include new values learned so far during apply

### Would you like to implement a fix?

None

**Comment by jared-rowe** [comment] 2024-07-22 03:36
Same issue here with `aws_ecs_task_definition`

Terraform Core Version
`1.9.2`

AWS Provider Version
`5.59.0`

Error:
```
Error: Provider produced inconsistent final plan
When expanding the plan for aws_ecs_task_definition.<the_task> to include new
values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" produced an invalid new value for
.container_definitions: inconsistent values for sensitive attribute.
This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

Resolved by pinning AWS provider to `5.58.0`

**Comment by ewbankkit** [comment] 2024-07-22 11:38
Relates https://github.com/hashicorp/terraform-provider-aws/pull/38016.

**Comment by ewbankkit** [comment] 2024-07-22 12:02
@chrisolido @jared-rowe Thanks for reporting this issue 👏.
A couple of questions to help with a quick resolution:
* Are you seeing these errors when creating completely new task definitions or when planning/applying updates to existing (pre-v5.59.0) resources?
* Can you share the `container_definitions` configuration (as much as possible) that is causing the problem?

**Comment by cdsre** [comment] 2024-07-22 13:43
@ewbankkit We are seeing it on new deployments. during the apply it doesnt show a container task definition in the resource

```hcl
  # module.container_ui[0].aws_ecs_task_definition.this will be created
  + resource "aws_ecs_task_definition" "this" {
      + arn                      = (known after apply)
      + arn_without_revision     = (known after apply)
      + cpu                      = "256"
      + execution_role_arn       = (known after apply)
      + family                   = "example"
      + id                       = (known after apply)
      + memory                   = "512"
      + network_mode             = "awsvpc"
      + requires_compatibilities = [
          + "FARGATE",
        ]
      + revision                 = (known after apply)
      + skip_destroy             = false
      + tags                     = {
          + "Name" = "example"
        }
      + tags_all                 = {
          + "Environment"     = "development"
          + "EnvironmentName" = "DW037"
          + "Name"            = "example"
          + "Owner"           = "example"
          + "Pipeline"        = "https://example.com/devops-terraform-modules/example/-/pipelines/130717"
          + "Terraform"       = "true"
        }
      + task_role_arn            = (known after apply)
      + track_latest             = false
    }
```

If we replay this CI job, then it does go ahead and redeploy the resources successfully and the apply shows the container_defs on the second run

```hcl 
# module.container_ui[0].aws_ecs_task_definition.this will be created
  + resource "aws_ecs_task_definition" "this" {
      + arn                      = (known after apply)
      + arn_without_revision     = (known after apply)
      + container_definitions    = jsonencode(
            [
              + {
                  + Command                = null
                  + Cpu                    = 0
                  + CredentialSpecs        = null
                  + DependsOn              = null
                  + DisableNetworking      = null
...
...
...
                 + VolumesFrom            = null
                  + WorkingDirectory       = null
                },
            ]
        )
      + cpu                      = "256"
...
```

**Comment by ThomasMarcelo** [comment] 2024-07-22 14:02
I started having the same issue today:
```
  │ Error: Provider produced inconsistent final plan
  │ 
  │ When expanding the plan for aws_ecs_task_definition.api to include new
  │ values learned so far during apply, provider
  │ "registry.terraform.io/hashicorp/aws" produced an invalid new value for
  │ .container_definitions: inconsistent values for sensitive attribute.
  │ 
  │ This is a bug in the provider, which should be reported in the provider's
  │ own issue tracker.
```

This is my task definition:
```terraform
resource "aws_ecs_task_definition" "api" {
  family                   = "${var.name}-${var.app_name}-api"
  network_mode             = "awsvpc"
  requires_compatibilities = ["FARGATE"]
  cpu                      = 512
  memory                   = 3072
  execution_role_arn       = data.aws_iam_role.ecs_execution_role.arn
  task_role_arn            = data.aws_iam_role.ecs_execution_role.arn

  // I even added this because I saw it as a solution for similar issues in the past, but no success
  lifecycle {
    ignore_changes = all
  }
// -----

  container_definitions = jsonencode([
    {
      name   = "${var.name}-${var.app_name}-api"
      image  = "${aws_ecr_repository.api.repository_url}:latest"
      cpu    = 512
      memory = 3072
      portMappings = [
        {
          containerPort = 3100
          hostPort      = 3100
          protocol      = "tcp"
        }
      ]
      environment = [
        for k, v in var.env_vars : {
          name  = k
          value = (
            contains(keys(local.urls), k) ? local.urls[k] : v
          )
        }
      ]
      secrets = [for secret in var.secrets : {
        name      = "${secret}",
        valueFrom = "${data.aws_secretsmanager_secret.secrets.arn}:${secret}::"
      }]
      command = ["yarn", "workspace", "${var.app_name}-api", "run", "start"]
      healthCheck = {
        command  = ["CMD-SHELL", "curl -f -k http://localhost:3100/health"]
        interval = 30
        timeout  = 10
        retries  = 3
        startPeriod = 60
      }
      logConfiguration = {
        logDriver = "awslogs"
        options = {
          "awslogs-group"         = data.aws_cloudwatch_log_group.log-group.name
          "awslogs-region"        = var.aws_region
          "awslogs-stream-prefix" = "${var.name}-${var.app_name}-api"
        }
      }
    }
  ])
  tags = {
    Name = "${var.name}-${var.app_name}-api-task-definition"
  }
}
```

**Comment by jared-rowe** [comment] 2024-07-22 23:59
Hi 

> @chrisolido @jared-rowe Thanks for reporting this issue 👏. A couple of questions to help with a quick resolution:
> 
> * Are you seeing these errors when creating completely new task definitions or when planning/applying updates to existing (pre-v5.59.0) resources?
> * Can you share the `container_definitions` configuration (as much as possible) that is causing the problem?

Hi @ewbankkit - thanks for jumping on this quickly.

Errors are occurring with new deployments creating new task definitions with `v5.59.0`.
Task definition with container definition (resource names, env vars, etc. have been generalised) looks like:
```
resource "aws_ecs_task_definition" "this" {
  family                             = "example-family"
  network_mode               = "awsvpc"
  requires_compatibilities = ["FARGATE"]
  cpu                                 = 1024
  memory                          = 4096
  execution_role_arn         = aws_iam_role.task_execution.arn

  container_definitions = jsonencode([
    {
      name  = local.container_name
      image = local.image
      portMappings = [
        {
          containerPort = 1234,
          hostPort      = 1234
        }
      ]
      environment = [
        {
          name  = "example1"
          value = "123"
        },
        {
          name  = "example2"
          value = "456"
        },
        {
          name  = "example3"
          value = "789"
        }
      ]
      secrets = [
        {
          name      = "example4"
          valueFrom = aws_ssm_parameter.secret_launch_code.arn
        }
      ]
      logConfiguration = {
        logDriver = "awslogs"
        options = {
          "awslogs-group"         = aws_cloudwatch_log_group.task_logs.name
          "awslogs-region"        = data.aws_region.current.name
          "awslogs-stream-prefix" = "ecs"
        }
      }
    }
  ])
}
```

**Comment by aldenbe** [comment] 2024-07-23 04:24
> @chrisolido @jared-rowe Thanks for reporting this issue 👏. A couple of questions to help with a quick resolution:
> 
> * Are you seeing these errors when creating completely new task definitions or when planning/applying updates to existing (pre-v5.59.0) resources?
> * Can you share the `container_definitions` configuration (as much as possible) that is causing the problem?

See https://github.com/hashicorp/terraform-provider-aws/issues/38482 which I closed as duplicate, this issue was introduced in version v5.59.0 downgrading to v5.58.0 works as expected.

**Comment by thomaszlow** [comment] 2024-07-23 08:13
@aldenbe  You made my week! Downgrading to v5.58.0 also worked for my new task deployments.

I did a lot of debugging the last days to find out what is causing the issue but couldn't find anything.
My first thought was that a line break in the healthCheck is the problem because it is marked in the Actions log as an error but removing all healtChecks didn't solve it.

![image](https://github.com/user-attachments/assets/ed44dade-8d7c-4ee3-b170-a7de52b97e23)

**Comment by ewbankkit** [comment] 2024-07-23 15:03
@jared-rowe Thanks for you example configuration -- we can reproduce the issue with it.

**Closed** 2024-07-23 21:05 UTC
Labels: bug, regression, service/ecs, prioritized
