### ISSUE TITLE
Additional statistics on Amazon CloudWatch Metric Streams

### ISSUE THREAD

**Issue by JeanFred** [hashicorp/terraform-provider-aws#24970] opened 2022-05-24 13:09 UTC
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Amazon CloudWatch announces support for additional statistics such as percentiles on CloudWatch Metric Streams.

### New or Affected Resource(s)

* `aws_cloudwatch_metric_stream`

### Potential Terraform Configuration

```hcl
resource "aws_cloudwatch_metric_stream" "example" {
  name          = "example"
  role_arn      = aws_iam_role.example.arn
  firehose_arn  = aws_kinesis_firehose_delivery_stream.example.arn
  output_format = "json"

  statistics_configuration {
    additional_statistics = ["p50", "p90"]
    include_metric  {
      metric_name = "AWS/ApplicationELB",
      namespace =  "TargetResponseTime"
    }
  }

  statistics_configuration {
    additional_statistics =  ["p90"]
    include_metric  {
      metric_name = "AWS/ApiGateway"
      namespace =  "IntegrationLatency"
    }
    include_metric  {
      metric_name = "AWS/ApiGateway"
      namespace =  "Latency"
    }
  }
}
```

### References

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2022/04/amazon-cloudwatch-metric-streams-additional-statistics/).
* [User Guide](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-metric-streams-statistics.html).
* original implementation of `aws_cloudwatch_metric_stream` resource: #18525
* CloudFormation docs:
   * [AWS::CloudWatch::MetricStream#StatisticsConfigurations](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-metricstream.html#cfn-cloudwatch-metricstream-statisticsconfigurations)
   * [AWS::CloudWatch::MetricStream MetricStreamStatisticsConfiguration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudwatch-metricstream-metricstreamstatisticsconfiguration.html)
   * [AWS::CloudWatch::MetricStream MetricStreamStatisticsMetric](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudwatch-metricstream-metricstreamstatisticsmetric.html)

**Comment by justinretzolk** [comment] 2022-05-24 15:12
Hey @JeanFred 👋 Thanks for taking the time to submit this issue. It looks like this is a duplicate of #24716. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #24716.

**Closed by justinretzolk** 2022-05-24 15:12 UTC
Labels: enhancement, service/cloudwatch, needs-triage

**Comment by JeanFred** [comment] 2022-05-24 16:21
> Hey @JeanFred wave Thanks for taking the time to submit this issue. It looks like this is a duplicate of #24716. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #24716.

Thanks for connecting this to the right issue! I did look through existing issues but evidently missed it.
